### ISSUE TITLE
Default locales in editing form when creating a new culture of an existing doc

### ISSUE THREAD

**Issue by asaunier** [c2corg/v6_ui#10]
As for now the editing form queries the API to get figures and locales of the document to edit.

What is the correct way to fill the editing form when creating a new culture for an existing doc? Since the culture does not exist yet, the API requests will fail if trying to retrieve the locales for the new culture.

Several approaches may be considered:
* requesting any other culture => but what culture? and it's not that relevent since we don't want the model to be fed by locales from another culture.
* getting only the figures and geometry => but then the model would not be fully initialized for the locales attributes
* making the API send a "locales" object with empty values except "culture"? For the standard "show" view, it is still better that the API replies "Not Found" when requesting a culture that does not exist, isn't it?

Should I open an issue in the API?

**Comment by tsauerwein** [comment]
When creating a translation for a document it might be useful to have the existing texts of another language at hand, so that you see what you are translating. But I don't know if that is planned.

If not a pragmatic solution would be to return an empty locales array when `?l=none` in the API.
