### ISSUE TITLE
On route, links to material article are not migrated

### ISSUE THREAD

**Issue by HSERGERAERT** [c2corg/v6_ui#1005]
**on v5**, route http://www.camptocamp.org/routes/784566/fr/la-pyramide-traversee-toit-pyramide-petite-traversee
The route has a connection, in material section,  to the article "material" http://www.camptocamp.org/articles/185384/fr/le-contenu-du-sac-alpinisme-rocheux-de-f-a-ad

**on v6** the article exists 
https://www.demov6.camptocamp.org/articles/185384/fr/le-contenu-du-sac-alpinisme-rocheux-de-f-a-ad

but the route has no connection to the article
https://www.demov6.camptocamp.org/routes/784566/fr/la-pyramide-traversee-toit-pyramide-petite-traversee, only "sangles" was migrated

**Comment by tsauerwein** [comment]
When was the association between the route and article created? Because in the v5 database that we made the migration with, this article only has associations to 4 other articles (which are shown).

**Comment by gottferdom** [comment]
I don't think the association exists in the database. In v5, the article link is displayed depending on the route characteristics (activity, difficulty, ...). So this isn't a migration problem.

**Comment by tsauerwein** [comment]
> In v5, the article link is displayed depending on the route characteristics (activity, difficulty, ...).

Can you give more information about how this works?

**Comment by gottferdom** [comment]
The code is here on v5: https://github.com/c2corg/camptocamp.org/blob/72e777075f2e6260b1d2ef563ab0f90c383038ba/apps/frontend/modules/routes/templates/_i18n.php

Basically, if some conditions are met, a link to a specific article is added in gear section. There are several articles (https://github.com/c2corg/camptocamp.org/blob/9a44a3b50ab2681a5e27435e1469c3911a192f6d/deployment/conf.ini-dist#L81)

To translate the logic:
* if activity is snowshoeing or skiing, add article on skitouring gear (id 183333)
* if activity is snow/ice/mixed and global rating <= PD+, add article for easy snow/ice/mixed (185750)
* if activity is mountain climbing and global rating <= AD, then 185384
* if rock climbing and equipment is P1 or P1+ then 185384
* if rock climbing and equipment is P2 or more and global rating <= AD and there isn't also the mountain climbing activity on the route, then 183332
* if ice climbing, then 194479
* if (skitouring or snow/ice/mixed or moutain climbing or snowshoeing) and glacier route is checked, then 185750 (but at anchor #glacier-gear)

In addition to this, there are some strings for each language to display the link.

Yes, it's a bit complicated :stuck_out_tongue_closed_eyes:

**Comment by tsauerwein** [comment]
Thanks for the info!

> Yes, it's a bit complicated

Then it is unlikely that we will have the time to do it for the Go Live.

**Comment by gottferdom** [comment]
> Then it is unlikely that we will have the time to do it for the Go Live.

I never thought it would/could be so.

**Comment by fbunoz** [comment]
> fbunoz did most of this work, he may be able to correct me

It is correct.
It is complicated because it misses some articles or chapters for some rating ranges. An objective is to improve these articles.

**Comment by brunobesson** [comment]
@fbunoz you should have taken a look 2 days ago :wink: 
I had incorrectly reported the logic, #1417 should be the final stage.

**Comment by desnoes** [comment]
This route does not contain a link to the article : http://www.demov6.camptocamp.org/routes/796500/fr/mont-blanc-sortie-depuis-le-sommet-du-pilier-rouge-du-brouillard while it is the case for this one: http://www.demov6.camptocamp.org/routes/53788/en/mont-blanc-traverse-of-the-3-monts
