### ISSUE TITLE
Typo in less file?

### ISSUE THREAD

**Issue by brunobesson** [c2corg/v6_ui#1008]
https://github.com/c2corg/v6_ui/blob/master/less/floatbuttons.less#L79

This is not a class name nor a CSS identifier

**Comment by asaunier** [comment]
Perhaps it is not a classname but an element name (created by an angular directive), as ``p`` or ``h3``.
I wonder if it is actually still used. I see no other occurence of ``app-edit-button`` : https://github.com/c2corg/v6_ui/search?utf8=%E2%9C%93&q=app-edit-button and no angular directive named ``appEditButton``.

@ginold could you check please?

**Comment by ginold** [comment]
indeed, as i mentioned in #988 app-edit-button does not exist anymore and the code linked to it can be removed.
