### ISSUE TITLE
Icons for Creative Commons' licence are too huge

### ISSUE THREAD

**Issue by dribagnac** [c2corg/v6_ui#1010]
For most people, the informations of the kind of licence is not usuful or even more useless or not understandable.

   For example, an outing, some huge icons are displayed inside the Information's panel. Why not display     - smaller
- or/and elsewhere
- or/and within a tooltip ?

   Eg 
http://www.demov6.camptocamp.org/outings/822024/fr/tete-de-ferret-par-la-dotse#/&gid=1&pid=2

**Comment by brunobesson** [comment]
Although I'm widely open to discussion on where to place the licence information (I think it would be best outside of informations box), I think on the contrary that the licence is an important information (people shouldn't find it useless!) that shouldn't be hidden.

**Comment by asaunier** [comment]
I think the licence info should indeed be placed in the "info blocks", perhaps in a dedicated block, along with the ``quality`` attribute. Both info are metadata, not actual data of the describe WP, route, etc.

This point should be considered along with the document organisation issue https://github.com/c2corg/v6_ui/issues/449

**Comment by dribagnac** [comment]
Most people are not aware of the meaning of this licence.
   Few people need this kind of information. 
   So my suggestion is just to show it smaller/elsewhere ...

**Comment by asaunier** [comment]
> Most people are not aware of the meaning of this licence.

This is actually the point! And the reason why licences should be made obvious (but OK to make the icons smaller).

**Comment by fbunoz** [comment]
On desktop, the licence icons are in the middle of the page, with many blank around : it seems like the most important info in the page !
Whereas the most important is the title, activities, cotations, altitude, ...
The licence info must be shown after these info.

**Comment by brunobesson** [comment]
I'm closing the issue, points are addressed in other related issues. Feel free to reopen if needed.
