### ISSUE TITLE
Main menu not collapsable for desktop

### ISSUE THREAD

**Issue by dribagnac** [c2corg/v6_ui#1011]
The main menu on the left (Home, Topoguide, Forum...) can be collapsed for small and medium device but not desktop.

   It would be great to allow it to be closed (and reopen by the open/close's icon [3 dashes])

**Comment by brunobesson** [comment]
Several users have expressed their will to have a collpased side menu event on desktop. Appart from the complexity it adds (we would need to store the user's preferences), there is also a problem with the ads (yes, ads are disturbing, etc, but still they are an important part of the association fundings to pay server costs).
I also do not focus on the vertical space problem for ads, this should be adressed in another issue.

Still, I would like to propose the following behaviour if we agree on allowing to collapse the menu on desktop:
* on mobile, use menu as is, but enhance it with #997 
* on tablet, make the menu collapsed, but do not allow clicking directly on an item: clicking expands it first, then one can select the wanted item. this would allow to remove the tooltips that are IMHO quite disturbing and anti-ergonomic on other displays
* on desktop, allow to collapse menu to put it in a state similar to tablets

**Comment by fbunoz** [comment]
Ok with that.

I add an improvment : on mobile with 1280px width screen, in landscape view, collapse the menu as in normal view. For now, it is only collapsed as on tablet.
In the menu CSS, the @media (max-width: 620px) must be changed to 650px, add a float:left; on the .logo, and change the .footer position (bottom: 5px).
You can test with the forum (I made the change, but it will be removed by the bug https://github.com/c2corg/v6_forum/issues/67).

**Comment by brunobesson** [comment]
I can't look into details your proposal right now, but I don't like the idea of having specific breakpoints. If the default breakpoint needs to be changed, then do it. But we should not create exceptions.

**Comment by brunobesson** [comment]
See also #1717 for a discussion on this matter.
