### ISSUE TITLE
Issues with map search

### ISSUE THREAD

**Issue by tsauerwein** [c2corg/v6_ui#1019]
Reported in https://github.com/c2corg/v6_ui/pull/1001#issuecomment-262853243

* [ ] The results are often too wide and do not fit in the map (unless the screen is quite wide).

![photon](https://cloud.githubusercontent.com/assets/1192331/20610865/9c1ae5a0-b2a0-11e6-8ab5-218b487d5352.jpg)

* [ ] Perhaps not all the results are relevant. For instance addresses or city POIs:

<img width="368" alt="capture d ecran 2016-11-24 a 23 28 24" src="https://cloud.githubusercontent.com/assets/1192331/20610808/8a89e68e-b29f-11e6-9d8d-676060b2ac20.png">

**Comment by desnoes** [comment]
I would close this issue (very very low priority IMHO). Anybody disagrees ?

**Comment by stef74** [comment]
I havé same réactions 😆 You can close

**Comment by brunobesson** [comment]
If it's low priority, then just don't handle it. But for now, I wouldn't close.

**Comment by stef74** [comment]
Milestone later it s good ...

**Comment by asaunier** [comment]
Another similar issue: https://github.com/c2corg/v6_ui/issues/1131
