### ISSUE TITLE
Sidemenu is displayed above the slideshow

### ISSUE THREAD

**Issue by asaunier** [c2corg/v6_ui#1040]
![sans titre](https://cloud.githubusercontent.com/assets/1192331/20726235/ef9e22aa-b674-11e6-8187-dcfb11f2d310.png)

**Comment by dkocich** [comment]
My Chrome and FF works fine on c2corgv6

**Comment by asaunier** [comment]
Indeed but http://www.demov6.camptocamp.org/ is not up-to-date yet. So the changes in the menu styles are not available yet. I had tested in a local instance.

**Comment by asaunier** [comment]
It seems there is the same problem with the modal messages in Discourse.

<img width="1044" alt="capture d ecran 2016-11-29 a 23 05 24" src="https://cloud.githubusercontent.com/assets/1192331/20730971/81534ece-b688-11e6-96ea-1dfbd60f9e9c.png">

Perhaps some ``z-index`` a bit too big?

**Comment by ginold** [comment]
Indeed i have changed the z-index to 10000 because Discourse had the top bar 1001 :P i will investigate.
