### ISSUE TITLE
Poor error message when login fails

### ISSUE THREAD

**Issue by asaunier** [c2corg/v6_ui#1041]
At least a translation problem.

<img width="300" alt="capture d ecran 2016-11-29 a 23 49 35" src="https://cloud.githubusercontent.com/assets/1192331/20732341/8f8a392a-b68e-11e6-8315-3893be2ada59.png">

**Comment by loicperrin** [comment]
So what is the problem in this case (to find the right translation)?
The user has entered a wrong username or a wrong password?

**Comment by asaunier** [comment]
> The user has entered a wrong username or a wrong password?

Yes.

Actually there is already a translation for "Login failed:" in Transifex.
https://www.transifex.com/camptocamp-association/c2corg_ui/viewstrings/#fr/v6/96458637?q=Login%20failed

And the message should be translated here (or perhaps only marked as to be translated?):
https://github.com/c2corg/v6_ui/blob/6d385f9fb2fc96325a52e3dbbf2e1b62efd0c381/c2corg_ui/static/js/apiservice.js#L379

**Comment by loicperrin** [comment]
So it is OK in Transifex, the modification has to be made in the API code.

**Comment by stef74** [comment]
@asaunier why do you remove "association" ? Its a translation issue (it's my understanding).

**Comment by asaunier** [comment]
I don't think it is a translation issue. The string "Login failed:" is indeed translated in Transifex. It's rather a code problem.

**Comment by loicperrin** [comment]
I think there are other error messages with account creation that cannot be translated in Transifex.
