### ISSUE TITLE
Waypoint articles/books associations not showing

### ISSUE THREAD

**Issue by ginold** [c2corg/v6_ui#1045]
some associated articles and books don't show up in the waypoint-view because the condition doesn't take them under account.

`% if 'recent_outings' in waypoint['associations'] and waypoint['associations']['recent_outings']['total'] > 0:`

**Comment by asaunier** [comment]
Could you give a link on github to the code you are pointing please?

**Comment by ginold** [comment]
https://github.com/c2corg/v6_ui/blob/master/c2corg_ui/templates/waypoint/view.html#L165

maybe other document types have this old condition too. To verify.

**Comment by asaunier** [comment]
OK thanks. It seems the condition has not been updated after books and articles associations have been added.

**Comment by desnoes** [comment]
seems to be fixed on demo
