### ISSUE TITLE
Climbing_outdoor WP : missing restricted access field

### ISSUE THREAD

**Issue by fbunoz** [c2corg/v6_ui#1047]
As explained [here](https://github.com/c2corg/v6_api/blob/master/c2corg_api/models/waypoint.py#L227-L237), for a climbing_outdoor WP, the access_period text field is used to describe the details of a restricted access : forbidden period, sector or route, the reasons, a link to the source, etc.
Then, the access_period field it must be visible for a climbingoutdoor WP, but the title should be "restricted access ("Restrictions d'accès" in FR).

**Comment by desnoes** [comment]
@fbunoz: it did not catch the problem. Only the title should be modified ? Transifex issue o more than that ?
