### ISSUE TITLE
Redirect to add slug drops HTTPS

### ISSUE THREAD

**Issue by tsauerwein** [c2corg/v6_ui#1051]
When I open the URL `https://.../outings/826204/fr` in HTTPS, a redirect is made to `http://.../outings/826204/fr/tete-du-...` in HTTP.

The redirect should be made to a URL with HTTPS.

To test:
https://www.demov6.camptocamp.org/outings/826204/fr
-> http://www.demov6.camptocamp.org/outings/826204/fr/tete-du-parmelan-par-le-petit-montoir

**Comment by asaunier** [comment]
Duplicate of https://github.com/c2corg/v6_ui/issues/981
