### ISSUE TITLE
Reports are not shown correctly in feed

### ISSUE THREAD

**Issue by asaunier** [c2corg/v6_ui#1052]
No idea what happened:

<img width="620" alt="capture d ecran 2016-11-30 a 22 20 17" src="https://cloud.githubusercontent.com/assets/1192331/20775663/6d11856e-b75c-11e6-8f31-cf97c53470d0.png">

@fbunoz Do you remember what it was?

**Comment by tsauerwein** [comment]
It's a report. Should reports be shown in the feed?

**Comment by dkocich** [comment]
Accident reports? I think that some reports can be shown on feed (avalanches), but it is probably not interesting to show everything (person fall with some injury, etc.).

**Comment by asaunier** [comment]
> It's a report. Should reports be shown in the feed?

Yes

All document creations should be advertised in the feed (images being a bit special).

**Comment by fbunoz** [comment]
> Do you remember what it was?
It's a xreport.

It would be useful that the exact date (and time until seconds) appear in a tooltip on the text "il y a 9 jours".

**Comment by dkocich** [comment]
is this already fixed? I see that it is ok (only feed on userprofile page, I could not find xreport on the main page feed)

![image](https://cloud.githubusercontent.com/assets/6165660/20892948/56adf124-bb10-11e6-9fd2-6535059baa6b.png)

**Comment by asaunier** [comment]
Xreports are now correctly shown in the feed.
