### ISSUE TITLE
Field glacier_gear not shown for hiking and strange behaviors

### ISSUE THREAD

**Issue by fbunoz** [c2corg/v6_ui#1053]
- [x] On the edit page of a hiking route, the field glacier_gear is not shown.
- [x] During the migration, the glacier_gear is set for all the route to 'no' or 'glacier_safety_gear' : https://github.com/c2corg/v6_api/blob/master/c2corg_api/scripts/migration/documents/routes.py#L102-L104.
The count is correct : https://www.demov6.camptocamp.org/routes#glac=no%252Cglacier_safety_gear (36822)
But when we show or edit a hiking route, the glacier_gear field is empty (we must add ski activity to see the field).
- [x] If we add ski activity and set the glacier_gear field to 'no', there is no change on this field : https://www.demov6.camptocamp.org/routes/diff/822350/fr/1297082/1302508 (but there is a change on the main wp whereas no change has been done in the edit form !)
- [x] Same behavior if we set the glacier_gear field to 'glacier_safety_gear' : https://www.demov6.camptocamp.org/routes/diff/822103/fr/1296830/1302509
The diff page seems not take account the glacier_gear field.

**Comment by stef74** [comment]
@desnoes @loicperrin @fbunoz please test and close

**Comment by loicperrin** [comment]
Fixed
