### ISSUE TITLE
(De)associating a route to an existing outing without GPX data should update the georef

### ISSUE THREAD

**Issue by brunobesson** [c2corg/v6_ui#1056]
Based on #1006 

A route without GPX data has georef automatically computed from assoiated route(s).
When (de)associating routes to an outing, it's georef should be computed again, the same way.

**Comment by fbunoz** [comment]
After association or dissociation of a route, the outing geometry is updated only if the (de)association was done in the edit form. The update is even done everytime : https://github.com/c2corg/v6_api/issues/574
Using the association tool on the read page doesn't update the geometry.

**Comment by asaunier** [comment]
> A route without GPX data has georef automatically computed from assoiated route(s).
When (de)associating routes to an outing, it's georef should be computed again, the same way.

According to my tests in the demo, the default point georef for outings with no GPS track is actually updated when associating another route, as well as when deassociating one.
=> OK

> Using the association tool on the read page doesn't update the geometry.

Indeed it seems this tool only updates the association, not the document itself thus not its geometry either. No suprise, it's only an association tool...

Please note the default geometry is actually updated next time the document is edited.
