### ISSUE TITLE
Notification when adding comment to an outing

### ISSUE THREAD

**Issue by loicperrin** [c2corg/v6_ui#1066]
There is no notification when a comment is added to an outing. So the user cannot guess that someone has commented his outing.

**Comment by asaunier** [comment]
Since comments use Discourse, I guess the Discourse notifications could (?) be used here as well.

**Comment by stef74** [comment]
@fbunoz could also do by discourse parametrization ?

**Comment by stef74** [comment]
@arnaud-morvan what is the job for auto subscribe the "participant" to her comment thread ?

**Comment by arnaud-morvan** [comment]
There is a "Invite" button in discourse topics which seems reachable by API using pydiscourse client.
https://github.com/bennylope/pydiscourse/blob/9108939503aa0b9084c890d94e1c0478d2cf15f9/pydiscourse/client.py#L526
In API we could use it to send a notification to existing participants in the outing when the comment topic is created. The considered users will get a notification in discourse about the new comment topics.

**Comment by arnaud-morvan** [comment]
Once the user have read the topic, he will receive further notifications depending on his settings (by default, readed topics are passed to "follow" notification state.

**Comment by fbunoz** [comment]
> In API we could use it to send a notification to existing participants in the outing when the comment topic is created.

It seems a good way to notify the participants.
But be careful, the invitation must be done on the 2nd post, because there are many comments without response, only with the first post posted by "system" : https://forum.camptocamp.org/c/comments?ascending=true&order=posts
I don't know why, maybe caused by the robots ?

**Comment by arnaud-morvan** [comment]
This is impossible for us to create the notification on the second post.
The notification need to be send from the API that get only the request for the topic creation.

**Comment by brunobesson** [comment]
Could it be possible to use the API so that the first comment is written directly in the outing footer. Only on submission would the discussion be started in discourse. Thus, there would be no need for an initial sytem post, and "empty" discussions created.

**Comment by brunobesson** [comment]
>I don't know why, maybe caused by the robots ?
No, it because people click on the button to start the discussion, but in the end do not post their message.

**Comment by arnaud-morvan** [comment]
> Could it be possible to use the API so that the first comment is written directly in the outing footer.

Yes it is possible, but not easy. This would require a lot of work, and may raise much more questions / problems.
IMHO, we should not have customised the discourse embed behavior like we have already done, by creating the topic when the user click on a button in the topoguide.

**Comment by brunobesson** [comment]
>we should not have customised

What other proposal do you suggest then? How could it be possible to comment a topoguide document?

**Comment by arnaud-morvan** [comment]
Discourse in it's native embed functionnality created the topic the first time the embed iframe is requested (the first time the topoguide document is shown) and maintain it self the relation between the document and the comments topics.
We have forced this behavior to create the topic when the user click on "Post the first comment" and this is already really complex to handle.

**Comment by arnaud-morvan** [comment]
If we add an input control at the end of the topoguide document, for the first comment, this will require a lot of work, and the user will get no toolbar, no preview, we may have problems with encodings, ...

**Comment by loicperrin** [comment]
I guess this issue cannot be tested on demo because Discourse is not active. Am I right?

**Comment by arnaud-morvan** [comment]
The demo forum is working, but there may still be a SSL problem on demo : https://github.com/c2corg/v6_api/issues/637
If you try to get the demo forum with https you get an invalid certifcate error.

**Comment by arnaud-morvan** [comment]
Also note that you will get the notification in discourse, but mails are not activated on demo.

**Comment by loicperrin** [comment]
> The demo forum is working, but there may still be a SSL problem on demo

It works indeed, but when I click on "Publier le premier commentaire", for example on this outing http://www.demov6.camptocamp.org/outings/828454/fr/dome-de-la-coche-versant-nw I get: "Internal Server Error : Error with Discourse"

**Comment by arnaud-morvan** [comment]
I've changes the scheme from HTTPS to HTTP for api requests to discourse, it is now possible to add comments in demo.

**Comment by desnoes** [comment]
@loicperrin @arnaud-morvan @fjacon : i've just tried and i am not able to log in to the forum. I get "login failed: unknown error". I am not able to test this issue. Am i the only one to observe this problem ?

**Comment by desnoes** [comment]
I have found the problem. When i click on comment, i was asked to log in, but on the https version of the forum.

**Comment by desnoes** [comment]
it works correctly on demo
