### ISSUE TITLE
Add a revert action in the wiki 

### ISSUE THREAD

**Issue by asaunier** [c2corg/v6_ui#1068]
In v5 it is possible to revert changes in a document by opening the document history, opening a document version before the changes to cancel and editing from this version (the old version is loaded in the editing form). Saving the form (even without any change) creates a new version based upon the data of the old version.
This feature is available to any contributor (not only moderators). Of course a warning is displayed in the editing form saying that the data are out of date.

In v6 we could have another approach if something is more convenient (a "restore this version" button?) but as for now I think the v5 approach is pretty efficient and would require no API change. I am not sure but I think this is also the approach used on wikipedia.

TODO:
* [x] make the edit button available in the archived version and open a special editing route with the archive id. For instance http://www.camptocamp.org/routes/edit/45297/fr/22
 * [ ] personal documents: only show edit button if user has edit rights on the document (or limit tool to moderators?)
* [x] Open the archive in the editing form:
 * [x] Add a pyramid route for such URLs with pretty much the same view
 * [x] except that the editing form is fed using a archive API request. Associations are not provided for such request and are anyway not relevant to restore an archive (associations history is not connected to document history). For instance: http://api.demov6.camptocamp.org/routes/390305?l=fr vs http://api.demov6.camptocamp.org/routes/390305/fr/633669
 * [x] add a warning in the editing form
 * [ ] Ignore associations (including for enabling the save button when associated WP etc. are mandatory)

**Comment by fbunoz** [comment]
> I think the v5 approach is pretty efficient

Yes : 
- It allows to do some changes on the old version before saving the revert.
- It allows to see and copy text with tags from the old version, if we don't want to revert all the text but only a little part.

**Comment by asaunier** [comment]
Pull requests for this issue:
* UI: https://github.com/c2corg/v6_ui/pull/1669
* API: https://github.com/c2corg/v6_api/pull/671
