### ISSUE TITLE
On tablet, left-menu has tooltips but they are hidden

### ISSUE THREAD

**Issue by brunobesson** [c2corg/v6_ui#1070]
Maybe the z-index (the default in bootstrap is 1070 for tooltips), or an overflow property?

![toto](https://cloud.githubusercontent.com/assets/2234024/20827923/1d6f6304-b875-11e6-953d-c4e097149aaa.png)

**Comment by ginold** [comment]
should be fixed by https://github.com/c2corg/v6_ui/commit/804550c319c7d9f4249f2ddb9c7d7ff457d7e29b

maybe the demo is not updated.

**Comment by stef74** [comment]
it's ok
