### ISSUE TITLE
No close outing end date button on mobile

### ISSUE THREAD

**Issue by brunobesson** [c2corg/v6_ui#1071]
Not sure this is really an issue, maybe it's intendend (at least when I have a look at the code).
So this is just for confirmation.

On mobile, when creating or editing an outing: the cross button near to the end date picker for a multi-day outing is not displayed.

**Comment by fbunoz** [comment]
I confirm the cross button to remove the end date is not shown on mobile.

**Comment by brunobesson** [comment]
On the other side, I tested by removing the end date with the date picker (`Clear`), and the outing is created appropriately. 
So this may be just a design choice.
Personnaly, I am OK with the current state. @asaunier or whoever is responsible for this part, could you confirm the desgin choice?

**Comment by ginold** [comment]
Probably I did this part, in fact it's hidden because it aligns better on mobile. If you prefer we can have something like this :

![screenshot from 2016-12-02 11-02-58](https://cloud.githubusercontent.com/assets/7814311/20830001/f2826e5c-b87e-11e6-98c5-0834e24778a4.png)

**Comment by desnoes** [comment]
@brunobesson : could you test ?

**Comment by brunobesson** [comment]
It's OK, although the layout could be improved a little.

**Comment by stef74** [comment]
With a new issue 😌 The goal is put in production quickly 😜

**Comment by brunobesson** [comment]
As I don't know the reasons you and @asaunier have to put it in production ASAP, I only focus on the ticket.
