### ISSUE TITLE
Date picker layout

### ISSUE THREAD

**Issue by brunobesson** [c2corg/v6_ui#1072]
Buttons are not placed properly, bottom margin is incorrect

![toto](https://cloud.githubusercontent.com/assets/2234024/20828053/e519c96c-b875-11e6-8237-26dd471063e6.png)

**Comment by brunobesson** [comment]
Also, why use 3 different colors for buttons? And these colors do not seem to respect the color palette?

**Comment by ginold** [comment]
Those are the default values and color. But you are completely right there should be a margin and a different button style, it annoys me too :P

**Comment by brunobesson** [comment]
See also #1135
