### ISSUE TITLE
Add new outing box layout in feed

### ISSUE THREAD

**Issue by brunobesson** [c2corg/v6_ui#1073]
On mobile, the position is OK, but on tablet and desktop, there is a missing top margin.
![toto](https://cloud.githubusercontent.com/assets/2234024/20828160/6168a1c8-b876-11e6-9455-320d4eae87ff.png)

**Comment by tsauerwein** [comment]
I also think the additional box around the button is not required.

**Comment by ginold** [comment]
I was going to do that, but if you can, you have to change/replace :

```
.action-line  {     
    padding-top: 5px;
    padding-left: 10px;
} 

#feed .list-item {
    margin: 10px;
}

.feed-list-item {
    padding-bottom: 2px;
}
```

![screenshot from 2016-12-02 10-57-44](https://cloud.githubusercontent.com/assets/7814311/20829847/2be6c70c-b87e-11e6-8bf2-83501d80cc11.png)

**Comment by brunobesson** [comment]
Feel free to do it!
Otherwise, I can work on it, but this may not be ready for GO live (dunno if I'll have time to work on it this week-end)
