### ISSUE TITLE
Missing translations

### ISSUE THREAD

**Issue by asaunier** [c2corg/v6_ui#1077]
Moving here new comments about i18n 

@desnoes https://github.com/c2corg/v6_ui/issues/705#issuecomment-264414244
> Outing: there are still 3 bugs
> - 'height_diff': @asaunier did a PR for this issue (https://github.com/c2corg/v6_ui/pull/1069)
> - 'True' instead of 'yes': i don't know wether it is a translation error or not

![sortie](https://cloud.githubusercontent.com/assets/19892089/20829451/669348dc-b87c-11e6-9953-c3e3795b1cce.jpg)

**Comment by asaunier** [comment]
> 'height_diff': @asaunier did a PR for this issue (#1069)

Indeed. The PR is merged but I can't see the new string ``height_diff``. Perhaps I should have waited Travis testing was fixed (does it impact the pushing of new strings to Transifex when a PR is merged?).

> 'True' instead of 'yes': i don't know wether it is a translation error or not

Not a translation error, simply a value error => the boolean value should be transformed to yes/no/... before being translated. Already reported here https://github.com/c2corg/v6_ui/issues/978

**Comment by stef74** [comment]
@asaunier Move to 6.x ?

**Comment by asaunier** [comment]
It's not critical anyway.

**Comment by desnoes** [comment]
> 'height_diff' => bug has been fixed.
> 'True' => the bug is still there

**Comment by asaunier** [comment]
> 'True' => the bug is still there

Since this problem is already reported at https://github.com/c2corg/v6_ui/issues/978 and since the other problem is fixed, I close the issue.
