### ISSUE TITLE
Show title_prefix of routes

### ISSUE THREAD

**Issue by tsauerwein** [c2corg/v6_ui#108]
`title_prefix` contains the name of the main waypoint of a route and can be shown in:

 * listings
 * detail view
 * simple search results

**Comment by asaunier** [comment]
``title_prefix`` must be shown (if set) in front of ``title`` for route documents.

**Comment by asaunier** [comment]
> title_prefix contains the name of the main waypoint of a route and can be shown in:
listings

Requires https://github.com/c2corg/v6_common/pull/6 and that the UI's and API's requirements.txt are updated:
https://github.com/c2corg/v6_ui/blob/master/requirements.txt#L15
https://github.com/c2corg/v6_api/blob/master/requirements.txt#L30
