### ISSUE TITLE
Add user advance search

### ISSUE THREAD

**Issue by loicperrin** [c2corg/v6_ui#1084]
In the page "Topoguide", an item "users" should be added to the list of types of documents, in order to display list of users.
This list should be filtered by:
-  name: "Topoguide name" and "forum name", and if possible with only one field for both names
- category
- activity
And of course, the list is filtered according to the map, as for other "objects".

**Comment by asaunier** [comment]
A tricky thing I guess: not-public profiles should not be listed or only with minimal info (topo name only?).

**Comment by HSERGERAERT** [comment]
Is it usual on web site to have a list of contributors/users ?

On my first test, I was a bit frustrated not to have that list, the one requested by Loic.
But thinking how the other web platform are acting, I don't feel this is usual to have such list.
Therefore, we should think first of the added value for the change request.  
Should it be a topic to postpone until we have the specifications of tags, because we may have the need to tag some users ?

If we would like to go ahead, I would not recommend a list of users, but the possibility to have in "My preference" the followed users, with 2 options, add and delete. Adding would be the existing functions in outing creation (to add contributors on your outing), it works well from the test I did.

**Comment by tsauerwein** [comment]
> ... but the possibility to have in "My preference" the followed users, with 2 options, add and delete.

See also https://github.com/c2corg/v6_ui/issues/1013

**Comment by jmarcmod** [comment]
Cette issue a été ouverte notamment pour permettre aux membres qui recherchent des partenaires dans les rubriques dédiées du forum, d'aller consulter le profil topoguide des membres en général inconnus susceptibles d'aller sortir avec eux. 
Tant qu'il n'y aura pas de solution à l'issue passerelle profil forum -> profil topoguide cf [forum #54](https://github.com/c2corg/v6_forum/issues/54), la seule solution est une recherche sur l'ensemble des contributeurs (a minima via pseudo topoguide, visible dans le profil forum).
L'issue #1013 ne répond pas à ce besoin.

**Comment by stef74** [comment]
Il est beaucoup plus simple de creer un lien (issue je sais plus combien) ... que de faire cette liste.

Avec l'evol sur la recherche des contributeurs dans les suivi ... l'urgence est moins grande.

Ca reste a affiner je tag later.

**Comment by jmarcmod** [comment]
En fait cette recherche existe déjà ! Mais elle est cachée.
On va dans "mes amis" : https://www.camptocamp.org/following
et là la recherche peut se faire sur n'importe quel pseudo topoguide (ami ou pas) !
Le résultat est le pseudo, cliquable.
Quant on clique, on obtient une card ; quand on clique à l'intérieur... on ouvre le profil topoguide !
(après il faut penser à appuyer sur le bouton "-" pour supprimer l'ami si en fait on ne veut pas le suivre)
Bref, tout y est, faut juste le mettre en valeur et sans tous ces détours.

**Comment by asaunier** [comment]
Jean-Marc

cet outil c'est la recherche simple appliquée aux contributeurs. Si on veut l'utiliser alors on l'active dans le champ de recherche simple en haut des pages.

Si on veut une page dédiée comme les pages de recherche avancée comme pour les sorties, les itinéraires, les images etc. alors il faut construire cette page. Ce n'est pas trivial.

**Comment by jmarcmod** [comment]
Je ne comprends pas bien. Entre tes 2 options, il y en a une 3ème, qui consiste à mettre un simple bouton quelque part, menant à une page identique à celle de la recherche d'amis, à la différence près qu'elle se contentera, si on clique sur le résultat renvoyé par la recherche, de faire afficher le profil, sans enregistrer le membre comme ami.
Certes ce ne serait pas une vraie recherche avancée, mais elle ne perturberait pas la recherche simple sur des noms topographiques.

**Comment by asaunier** [comment]
Il faut de la cohérence, pas faire des pages qui fonctionnent de telle manière pour un type de document et de telle autre manière pour un autre.

**Comment by jmarcmod** [comment]
OK à terme. Je pensais plutôt à une solution d'urgence en attendant (car c'est réclamé d'un peu partout).

**Comment by stef74** [comment]
Je propose de ne l'activer que dans la recherche simple ...

**Comment by jmarcmod** [comment]
> Je propose de ne l'activer que dans la recherche simple ...

OK pour une solution d'urgence ; mais à tester d'abord sur la demo, pour voir si ça ne perturbe pas trop la recherche topographique, sachant que de nombreux pseudos sont des noms de lieux.

**Comment by asaunier** [comment]
@desnoes @stef74 Est-ce que cette demande pourrait être précisée (spécifications) ?

Par ex : 
* page de recherche avancée classique, avec liste de cards, filtre cartographique (désactivé par défaut, comme pour les images), quelques filtres (avec 1 champ texte, catégories et activités ca doit tenir tout dans les critères de premier niveau - comme pour les régions)
* cards : les mêmes que dans la page "mes amis"
* actuellement le service API permettant de lister des utilisateurs n'est pas public et requiert d'être identifié il me semble => est-ce qu'on le passe public ?! est-ce qu'on limite cette page de recherche des contributeurs aux visiteurs identifiés seulement ?
* où fait-on apparaître cette page ? Dans la partie topoguide ?

**Comment by desnoes** [comment]
> page de recherche avancée classique, avec liste de cards, filtre cartographique (désactivé par défaut, comme pour les images), quelques filtres (avec 1 champ texte, catégories et activités ca doit tenir tout dans les critères de premier niveau - comme pour les régions)

Ca me semble très bien.

> cards : les mêmes que dans la page "mes amis"

oui

> actuellement le service API permettant de lister des utilisateurs n'est pas public et requiert d'être identifié il me semble => est-ce qu'on le passe public ?! est-ce qu'on limite cette page de recherche des contributeurs aux visiteurs identifiés seulement ?

Oui, il faut la limiter aux membres identifiés.

> où fait-on apparaître cette page ? Dans la partie topoguide ?

oui, dans la partie topoguide.
