### ISSUE TITLE
robots.txt is not made available with nginx

### ISSUE THREAD

**Issue by asaunier** [c2corg/v6_ui#1088]
A ``robots.txt`` file is available, see the apache config at https://github.com/c2corg/v6_ui/blob/master/apache/wsgi.conf.in#L7

But it seems missing in the actual demov6/prod config, using nginx instead of Apache.

**Comment by asaunier** [comment]
The syntax seems to be
```
  location /robots.txt {
    alias /path/to/basedir/c2corg_ui/static/robots.txt;
  }
```
Don't know if it is possible not to hard-code ``/path/to/basedir``?

**Comment by stef74** [comment]
#1152

**Comment by asaunier** [comment]
The PR is merged but not available in prod yet.
