### ISSUE TITLE
Contextual Help

### ISSUE THREAD

**Issue by stef74** [c2corg/v6_ui#1096]
TDB

**Comment by desnoes** [comment]
Requirements:

- A question marking is displayed when the mousse hover over a field
- When clicking on a field, a window is opened. It contains a text which gives information about this field (ex: difficulty)
- The window contains a close button.

example: http://www.pre-prod.dev.camptocamp.org/outings/527014/fr/gouffre-d-enfer-cascade-du-gouffre-d-enfer

**Comment by stef74** [comment]
I have more simple approach allready use ... if you over with a mouse or click in mobile you can show black pop-up (as in card)

![tooltip](https://cloud.githubusercontent.com/assets/3962997/23164623/4f76c06a-f838-11e6-9b8e-b5c83e2c7dea.png)

No need question mark  or close buttun.

In term of code is simple add : 
uib-tooltip="{{'height_diff_difficulties'| translate}}" tooltip-append-to-body="true"

You have only to defined a key for translation. 

I can do the job but need : 
- define key : You can simple use field_name_description 
- which field need contextual help and where (not necessary all).

**Comment by brunobesson** [comment]
I don't agree. Tooltips aren't appropriate for this kind of contextual help which can be pretty long (it is often several paragraphs).

**Comment by stef74** [comment]
We can do multine in tooltips ? 

For mobile on chrome it's work not on safari. But for me contextual help in mobile is not necessary (mobile cannot have the same feature than desktop). 

I have not the knowledge to propose a better solution ... just capacity to copy an existing one.

**Comment by arnaud-morvan** [comment]
It is possible to open modal dialog, sometime on the element.onClick, but for links, we should add a "i" button near the link. The modal is closed by clicking (touching) outside.
Here is a snapshot : 
![modal](https://cloud.githubusercontent.com/assets/6095494/23998280/de88c0e0-0a54-11e7-905d-1fdca2608179.png)

**Comment by fbunoz** [comment]
We must have contextual help on tablet and mobile.

**Comment by asaunier** [comment]
Using a modal window is indeed probably a good idea, especially if the help content is a bit long.
In v5 you could have a small window listing for instance the possible values of a rating attribute with explanations about those values.

**Comment by fjacon** [comment]
@desnoes we need your OK and one example of help text that we could add on demo.
thanks.

**Comment by desnoes** [comment]
Here is an example of a help text for the selection of the activity.

**Activités**
Type d'activités : dans une liste ou un document, passez la souris sur les pictogrammes pour connaître leur signification.
Un document peut être associé à une ou plusieurs activités :

 -**ski, surf** : randonnée à ski et/ou surf
 - **raquette** : randonnée en raquettes
- **alpinisme neige, glace, mixte** : alpinisme sur neige, glace ou mixte (en haute montagne)
- **rocher haute montagne** : alpinisme sur rocher, grandes voies en montagne (équipées ou non)
- **escalade** : bloc, voies d'une ou plusieurs longueurs en falaise (équipées ou non)
- **cascade** : cascade de glace hors haute montagne, dry-tooling
- **randonnée pédestre / trail** : randonnée pédestre et trail en terrain montagneux (et non en plaine), sur sentier balisé ou non, ou hors sentier
- **parapente montagne** : descente en parapente après une montée à pied ou à ski (vol rando, paralpinisme)

La différence entre les activités **escalade** et **rocher haute montagne** se fait principalement sur l'altitude du sommet de la voie, mais pas sur l'équipement. En Europe, les règles suivantes s'appliquent :
- altitude < 2100m : escalade
- altitude entre 2100m et 2400m : escalade ou rocher haute montagne, mais majoritairement escalade
- altitude entre 2400m et 2700m : escalade ou rocher haute montagne, mais majoritairement rocher haute montagne
- altitude > 2700m : rocher haute montagne
Pour une altitude entre 2100m et 2700m, les 2 activités peuvent être sélectionnées en cas de doute.

**Comment by asaunier** [comment]
Documentation for the contextual help directive is available at https://github.com/c2corg/v6_ui/pull/1601#issue-224529791

**Comment by asaunier** [comment]
I think there is a problem left with PR #1601: it's OK with simple strings passed as ``context-help-content="{{'Some text' | translate}}"`` but it seems the translation does not work for complex strings passed as a partial (HTML file) ``context-help-content-url="/static/partials/contexthelp/activities.html"``.

**Comment by desnoes** [comment]
works fine on demo ( http://www.demov6.camptocamp.org/outings/edit/828508/fr)

**Comment by asaunier** [comment]
> works fine on demo

Except that the text is not translated. I have opened a dedicated issue at https://github.com/c2corg/v6_ui/issues/1610
