### ISSUE TITLE
URL redirections and SEO

### ISSUE THREAD

**Issue by stef74** [c2corg/v6_ui#1098]
"Pages de référencement Google"

I don't know what is the job remaining ...

**Comment by asaunier** [comment]
I don't even know what's this mean...

**Comment by stef74** [comment]
If an extract of release document part bases on "cahier des charge" ...

2016-12-04 20:45 GMT+01:00 Alex Saunier <notifications@github.com>:

**Comment by asaunier** [comment]
Still don't understand. Please clarify the task. For me "Pages de référencement Google" is too confusing and doesn't really make sense. Do you mean the sitemap file?
If yes the issue has already been addressed https://github.com/c2corg/v6_ui/issues/343

**Comment by HSERGERAERT** [comment]
This topic cames from a discussion with @fjacon . 
My understanding. v6 will have the same URL address than v5, www.camptocamp.org.
We have to ensure that Google won't redirect Google searches on v5-archive but on the right pages of the v6.
That's my understanding, don't know if there are particular actions to do.

**Comment by asaunier** [comment]
OK thanks for the explanations.
I have retitled the issue to make it a bit clearer.
There are indeed a few redirections to do. For instance http://www.camptocamp.org/summits/43836/fr/dorenaz to http://www.camptocamp.org/waypoints/43836/fr/dorenaz

Milestone cannot be 6.3 (no use to make such changes in 4 months). It's a golive task (already listed in the golive trello).

**Comment by stef74** [comment]
It's milestone 6.2 in realease exel sheet ... for the purpose if additionnal work needed after go live. I know we use micro tagging for specific data ... but i don't know if it's allready relevant.

@lbesson Some ideas ?

**Comment by asaunier** [comment]
@stef74 OK, for golive we'll do the changes listed in Trello. Please list additional tasks and set milestone accordingly if needed.

**Comment by asaunier** [comment]
@stef74 I have postponed the issue to 6.1 since "base" redirection tasks are listed in Trello.

**Comment by stef74** [comment]
It's not clear if extra work needed ...
