### ISSUE TITLE
Some WP cannot be edited

### ISSUE THREAD

**Issue by asaunier** [c2corg/v6_ui#110]
For instance id 636651 => API returns a 400 error

**Comment by tsauerwein** [comment]
This is the error returned by the API:

    {
      "status": "error",
      "errors": [{
        "location": "body",
        "description": "Required",
        "name": "document.climbing_outdoor_types.0"
      }, {
        "location": "body",
        "description": "\"None\" is not iterable",
        "name": "document.orientation"
      }, {
        "location": "body",
        "description": "\"None\" is not iterable",
        "name": "document.best_periods"
      }, {
        "location": "body",
        "description": "\"None\" is not iterable",
        "name": "document.equipment_ratings"
      }, {
        "location": "body",
        "description": "\"None\" is not iterable",
        "name": "document.climbing_styles"
      }]
    }

**Comment by asaunier** [comment]
Thanks. Seems related to missing attributes not available in the editing form yet. => will most likely be fixed when all the WP attributes are finally added.

**Comment by tsauerwein** [comment]
The fields are actually included in the request, it looks like a problem with the API.

**Comment by asaunier** [comment]
> it looks like a problem with the API.

I think it's a problem with the WP editing form!

I just tried to create a new "climbing_outdoor" waypoint. No pb with the standard attributes. If I add for instance an ``equipment_ratings``(see by the way this issue/PR: #289 ) the API complains that:

> {"status": "error", "errors": [{"description": "\"P1+\" is not iterable", "name": "document.equipment_ratings", "location": "body"}, {"description": "\"None\" is not iterable", "name": "document.climbing_outdoor_types", "location": "body"}, {"description": "\"None\" is not iterable", "name": "document.best_periods", "location": "body"}, {"description": "\"None\" is not iterable", "name": "document.orientation", "location": "body"}, {"description": "\"None\" is not iterable", "name": "document.climbing_styles", "location": "body"}, {"description": "Required", "name": "document.rock_types.0", "location": "body"}]}

=> equipment_ratings, best_periods, orientation, climbing_styles etc. should be arrays in the JSON request. As for now they are scalar:
```
climbing_outdoor_types: null
climbing_styles: null
equipment_ratings: "P1+"
```
They should rather be
```
climbing_outdoor_types: []
climbing_styles: []
equipment_ratings: ["P1+"]
```
@ginold could you have a look please?

**Comment by tsauerwein** [comment]
`null` should also be accepted by the API: https://github.com/c2corg/v6_api/issues/55

**Comment by asaunier** [comment]
So you mean we are waiting for a bugfix in Cornice in order to support ``null`` instead of ``[]``?

At least for ``equipment_ratings`` this is not a Cornice issue and we can make the change without waiting.

**Comment by tsauerwein** [comment]
> So you mean we are waiting for a bugfix in Cornice in order to support null instead of []?

I have to make a PR or do a fix in the API.

> At least for equipment_ratings this is not a Cornice issue and we can make the change without waiting.

True.

**Comment by fjacon** [comment]
@ginold : Can be closed ?

**Comment by ginold** [comment]
seems to be fixed. Closing.
