### ISSUE TITLE
Impossible to display an outing

### ISSUE THREAD

**Issue by loicperrin** [c2corg/v6_ui#1100]
When I try to display https://www.demov6.camptocamp.org/outings/93037/fr/signal-du-venetier-voie-plume, I get a "Internal Server Error", whereas there is no problem when displaying other outings, even if they are associated to xreport.

**Comment by asaunier** [comment]
Please check if the issue is not already reported before creating a new one: https://github.com/c2corg/v6_ui/issues/1099
