### ISSUE TITLE
Image in feed

### ISSUE THREAD

**Issue by stef74** [c2corg/v6_ui#1104]
The image are very bad and too "width"

![capture d ecran 2016-12-05 a 21 21 19](https://cloud.githubusercontent.com/assets/3962997/20901071/24c8f930-bb31-11e6-8b51-72c6a06a1bd4.png) 

We have to limit the width to 3 time the heigh ...

**Comment by stef74** [comment]
I have juste change width=100% by width=50% rendering is better 

![capture d ecran 2016-12-05 a 21 39 37](https://cloud.githubusercontent.com/assets/3962997/20901712/12d7a00c-bb34-11e6-9206-040850fa4044.png)

**Comment by asaunier** [comment]
When there is only one image, it's too bad not to use the full card width. I prefer the original layout.

**Comment by stef74** [comment]
On layout perspective ... ok but if look my screenshoot the image are very bad 

![capture d ecran 2016-12-05 a 22 59 45](https://cloud.githubusercontent.com/assets/3962997/20904195/d9299918-bb3e-11e6-900c-00513f67fdc4.png)
![Uploading Capture d’écran 2016-12-05 à 22.59.54.png…]()

Honnestly the rendering of feed in large screen for image is very bad, all the image are completly deformed.
All the sky in landscape are truncated.

**Comment by ginold** [comment]
This might actually be the case but probably _only_ for panoramic pictures, all the other "normal" pictures should be ok.

**Comment by stef74** [comment]
> This might actually be the case but probably only for panoramic pictures, all the other "normal" pictures should be ok.

If you have the look on this one ... is not OK (the original image is classical 4/3)

![capture](https://cloud.githubusercontent.com/assets/3962997/20920455/54b0be16-bba0-11e6-9df9-c285bac0c3a1.PNG)

In fact two problem  
- quality of image
- proportion of image (a 4/3 image are not adpat to te show in panoramic format).

**Comment by ginold** [comment]
![screenshot from 2016-12-06 10-46-09](https://cloud.githubusercontent.com/assets/7814311/20920685/3d398cc6-bba1-11e6-8754-da00fd7b4116.png)
When I look at it like this, it looks perfectly fine. What i notice, is that the image gets a little blurry when you hover on it (browser things).

**Comment by tsauerwein** [comment]
The problem is on larger screens where the image is shown resized with a width > 400px. Could you maybe do it so that the image is shown with a maximum width of 400px?

**Comment by stef74** [comment]
@ginold perfect is not the appriate term but it's accetpatble (sorry but in original image of alex you can show 5 lengh of climbing ... on yours 3 and on mine only 1.5)
With width screen the feed are more wide (it's good point to use the space) ... but the image are not good (quality and content of image show).

Have look alex's image ...

**Comment by asaunier** [comment]
Do you mean that feed cards are wider on bigger screens? The cards should not be wider than the image width (400px?), so that the images are not zoomed (poor quality). In addition the height should grow too when the width is increased (cards would then take more vertical space but wider screens are generally also higher).

**Comment by ginold** [comment]
So the fix would be to use a fixed height and width for the feed cards, because now it's a percentage so it might get a little too big and stretch the image :ok_hand:

**Comment by stef74** [comment]
If you have a look on this image (more vertical) 
![ski](https://cloud.githubusercontent.com/assets/3962997/20959856/7f1a6b44-bc5d-11e6-8c24-a069d8f7a90d.PNG)

if you have a look on original image : 
http://sos.exo.io/c2corg_demov6_active/1481093802_1943988014.jpg

The rendering on feed if very strange ...

Test en 1920*1080 screen (not very big).

**Comment by stef74** [comment]
Quality if image (large screen)
Oginal Format image

**Comment by ginold** [comment]
Keep in mind that the images in the feed and the original images are not the same! original are.. original - nearly no changes to the quality and dimensions. The images in the feed are much smaller and of poorer quality.

**Comment by stef74** [comment]
yes I know but if it's smaller normally the quality are not be worst. In last case the croping approach is very strange.
An option can be add black (or withe) zone like 16/9 film if image not fit the same format.
Square format is probaly also most adapt in many case.
