### ISSUE TITLE
Prevent multiple image uploads

### ISSUE THREAD

**Issue by asaunier** [c2corg/v6_ui#1112]
After dragging images to the upload panel, it is possible to click several times in a row on the "save" button. This will trigger several identical POST ``images/list`` requests to the API.

It seems that only the first one succeeds, the other returns a 500 error. Because of the image filename unicity constraint I guess. So it probably does not create duplicates in the DB.

In addition there is no indicator showing that the images are being saved.

TODO:
* [ ] show a loading indicator when saving image (using the ``app-loading`` directive?)
* [x] disable the buttons when the "save" button has been pressed

**Comment by HSERGERAERT** [comment]
Tested this morning with outing http://www.demov6.camptocamp.org/outings/828236/fr/bel-oiseau-couloir-sse.
Only the first picture was loaded, the others weren't, no link with image sizing.
I loaded successfully the first one.
Then I moved, and came back later on the outing, it wasn't possible to add pictures. Is-it the same issue ?

**Comment by asaunier** [comment]
@HSERGERAERT I have not been able to reproduce the behaviour you describe on demov6, including with a normal (not moderator) account. No problem to load images, including in several times, opening another page in the meantime etc.

Clicking several times on the "save" button does what I have described above: images are saved only once, the subsequent requests fails with a 500 error, which is actually OK since it's the same image file. Of course it works if I upload several times the same image (but than filenames are different).

**Comment by HSERGERAERT** [comment]
@asaunier : test made right now, it works.
