### ISSUE TITLE
Impossible to confirm account creation

### ISSUE THREAD

**Issue by loicperrin** [c2corg/v6_ui#1115]
When I create a new account, I don't receive the e-mail to validate it. Same pb if I use the function "password forgotten".
Blocking issue: users can not create accounts.

**Comment by asaunier** [comment]
I have just tested the password resetting procedure and have actually received an email, as expected.
Perhaps look at your spam directory?

**Comment by loicperrin** [comment]
> I have just tested the password resetting procedure

I have tested it again with another e-mail, and I have received e-mail. But I cannot change the password: message "Password could not be changed" (maybe already in another issue?).

> Perhaps look at your spam directory?

No.

I have also tested account creation with another e-mail => mail received. But error message when I click on the confirm link: 
"Your account could not be activated:
Unknown error"

**Comment by loicperrin** [comment]
- [ ]  I cannot change the password: message "Password could not be changed"
- [ ] error message when I click on the confirm link:
"Your account could not be activated:
Unknown error"

**Comment by HSERGERAERT** [comment]
Tested this morning. **Successful on my side**.
@loicperrin : was it working on previous version ?

**Comment by dkocich** [comment]
For me, everything (register, get and activate email, change password) was ok on demov6

**Comment by stef74** [comment]
Tested ... but not work !
On creation page : unknown error

**Comment by stef74** [comment]
If I try to resubmit the form ... user/email allready exist ! but no email. Test with my profesionnal email.

**Comment by asaunier** [comment]
I have tested:
* on demov6: password change and also account creation: worked as expected
* on the future prod: password change: worked as expected.

**Comment by stef74** [comment]
The problem if user have issue ... no contact information are provided. It's good idea to add a link to contact article. (the contact link in menu is too tiny to be visible ...)

**Comment by asaunier** [comment]
On the future prod I have just tried to create a new account: I have received the validation email but clicking on the link returned an error because of Discourse (which seems not correctly configured on the prod):

![sans titre2](https://cloud.githubusercontent.com/assets/1192331/20966167/5bf058b0-bc79-11e6-801a-a57b758cf9fd.png)

**Comment by loicperrin** [comment]
>  I cannot change the password: message "Password could not be changed"

To be more precise: I can change my password if I am loggued in and I use the "Mon compte" form. But I get this error when using the function "password forgotten" and clicking on the received link (https://www.demov6.camptocamp.org/auth#change_password=newpass_0c0a23df963cc9948e4caf83e10c9b635f079a2668738b5cb03b29cfb0643075)

Hereafter is the link I have finally received 4 hours after request to activate a new account (seems to be a pb with yahoo mail, when I test with google I receive the link more quickly) : https://www.demov6.camptocamp.org/auth#validate_register_email=regemail_b69acdf1c5459219b34fcc7a5a390980c2ba8966abfcc4b64368a8836d6b8159
If  I click on this link I get the error message (and it was the same with the link I have received immediatly yesterday on my c2c.org email).

> was it working on previous version ?

I don't know, It is the 1st time I test this functionnality.

**Comment by stef74** [comment]
I suspect is related to some mailbox

Could you test on production ? (i have send you the acces)

**Comment by stef74** [comment]
I have tested email config ... some improvement is needed 
http://www.mail-tester.com/web-cwgux

I check if production is better

**Comment by stef74** [comment]
production : http://www.mail-tester.com/web-898o6

**Comment by stef74** [comment]
If you have look on more impacting point :
[ ] -1.246		RCVD_IN_BL_SPAMCOP_NET sparkpost is in blacklist nothing do on our side
[ ] -2.749		TVD_SPACE_RATIO_MINFP ... https://wiki.apache.org/spamassassin/Rules/TVD_SPACE_RATIO "it's the ratio of spaces to non-spaces in each paragraph. apparently messages where generally there are lots of spaces mean the message is spam." 
[ ] You do not have a DMARC record, please add a TXT record to your domain _dmarc.camptocamp.org with the following value:  v=DMARC1; p=none


@mfournier could you have a look on DMARC
@asaunier could you havce a look on content mail 

For black list I have no solution because is sparkpost not camptocamp.org is blacklisted.

**Comment by asaunier** [comment]
> could you havce a look on content mail

What am I supposed to do? :p 
I won't change all the email contents before the golive. And to add what?
All contents are available here: https://github.com/c2corg/v6_api/tree/master/c2corg_api/emails/i18n/fr

**Comment by stef74** [comment]
Based sur spamAssassin filetring :

> According to a comment in the rules file "it's the ratio of spaces to non-spaces in each paragraph. apparently messages where generally there are lots of spaces mean the message is spam."
> 
> Extra space in HTML messages will be ignored in mail clients, but may not be ignored in pattern-matching filters. Slightly different messages may be sent to each recipient to avoid filtering.

**Comment by asaunier** [comment]
I don't think we can remove spaces in https://github.com/c2corg/v6_api/blob/master/c2corg_api/emails/i18n/fr/registration_body or https://github.com/c2corg/v6_api/blob/master/c2corg_api/emails/i18n/fr/password_change_body :)

**Comment by loicperrin** [comment]
> Could you test on production ?

Both problems seem do not appear in production

**Comment by stef74** [comment]
I close and open a ticket just for DMARC
