### ISSUE TITLE
Selecting a GPX file for a route or an outing only works once

### ISSUE THREAD

**Issue by brunobesson** [c2corg/v6_ui#1119]
If you reinit the geometry, then select a file again, it is not taken into account.

Steps to reproduce:

* start the creation of an outing or a route
* select GPX file
* map is updated
* click on reinit button
* upload file again
* map isn't updated, and new geometry is ignored when saving

This seems to be related to the secodn upload only, other combinations are OK (drawing geo first, then uploading file, etc)

**Comment by asaunier** [comment]
I cannot reproduce the problem with the last version of the master branch in Chromium 55 and Firefox 50 => no problem to upload another track after resetting the initial one, when saving the outing, the last track is actually used as geometry.

**Comment by brunobesson** [comment]
Alas it is still happening to me with FF 50.1.0 on master...

**Comment by brunobesson** [comment]
Duplicate of #1320
