### ISSUE TITLE
Impossible to add comments

### ISSUE THREAD

**Issue by desnoes** [c2corg/v6_ui#1125]
I am not able to add a comment on any document (outing, route) on the demo version. [edit: on the prod too]
I did not find any issue concerning this point. If it is not relevant => close the issue.

**Comment by asaunier** [comment]
Could you precise what is the problem, what you do and what happens?

I have just tested on the demo: adding a comment seems to work except that my browser has blocked the popup that is opened when clicking the "add a comment" button. Then it's not possible to press the button again ("topic id already exists") until the page is reloaded.

Relying on a popup is not a very satisfaying/user friendly solution...

**Comment by brunobesson** [comment]
>Relying on a popup is not a very satisfaying/user friendly solution...

It's even horrific :wink: 
I thought that would be solved for GoLive (but didn't inspect it, it was so obvious for me, my bad).

**Comment by ginold** [comment]
It should at least reload the comments section with the button "Demarrer la discussion", this would be 'nearly' obvious to click there next. I can have a look and try to do at least this.

**Comment by desnoes** [comment]
> I have just tested on the demo: adding a comment seems to work except that my browser has blocked the popup that is opened when clicking the "add a comment" button. Then it's not possible to press the button again ("topic id already exists") until the page is reloaded.

This is exactly what i've got. I think we will have many problem with users (like me !) that don't figure out there is a popup for the comments.

**Comment by HSERGERAERT** [comment]
I made a successful test.
Correct, we have to access the popup, one time. I don't see a problem.
Can we close the issue ?

**Comment by stef74** [comment]
I have identified on safari the first pop up doesn't appear ... to solve i have authorized pop-up bu in safari by defaut is blocked.
We have to communicate on this point ... pop up must be authorized for camptocamp.org

**Comment by HSERGERAERT** [comment]
Same on Chrome, by default it's locked

**Comment by HSERGERAERT** [comment]
You can authorize pop-up only for www.camptocamp.org, at least on Chrome

**Comment by stef74** [comment]
We can close ? no action identified
