### ISSUE TITLE
Infinite loop when logging out from forum.

### ISSUE THREAD

**Issue by arnaud-morvan** [c2corg/v6_ui#1127]
When we logout from the forum, we are redirected to https://www.camptocamp.org/auth-sso?logout
And browser loop on refreshing the page.

**Comment by asaunier** [comment]
Same problem on https://www.demov6.camptocamp.org/

But it works normally with the http URL: https://www.demov6.camptocamp.org/

When logging out from https://forum.demov6.camptocamp.org/
one is redirected to http://www.demov6.camptocamp.org/auth-sso?logout (http, not https)
Shouldn't it redirect to https://www.demov6.camptocamp.org/auth-sso?logout (https!)?

**Comment by tsauerwein** [comment]
> Shouldn't it redirect to https://www.demov6.camptocamp.org/auth-sso?logout (https!)?

Isn't this configured in the Discourse settings?

**Comment by asaunier** [comment]
Perhaps this is not related to the infinite loop. As reported by @arnaud-morvan in prod it loops on https://www.camptocamp.org/auth-sso?logout

Perhaps in prod we have the https page because http redirections to https are forced (HSTS?)?

**Comment by tsauerwein** [comment]
> As reported by @arnaud-morvan in prod it loops on https://www.camptocamp.org/auth-sso?logout

I also have the infinite loop on localhost. PR is coming.

**Comment by tsauerwein** [comment]
> Perhaps in prod we have the https page because http redirections to https are forced (HSTS?)?

In prod it works correctly, the redirect is made to https://www.camptocamp.org/auth-sso?logout

**Comment by arnaud-morvan** [comment]
I've changed the settings in discourse to use HTTPS for login/logout

**Comment by tsauerwein** [comment]
Thanks!

**Comment by fbunoz** [comment]
> I've changed the settings in discourse to use HTTPS for login/logout

I had always the problem on the demo after each demo update.
I changed the url to add the https, and it worked correctly.
But at the next update, it was returned to http, and I should make the change again.
I don't know where was the default config defined, but it was wrong.
