### ISSUE TITLE
Advertisement images should use HTTPS

### ISSUE THREAD

**Issue by tsauerwein** [c2corg/v6_ui#1132]
Some of the banner images of the advertisement service are not using HTTPS:

> Mixed Content: The page at 'https://www.camptocamp.org/' was loaded over HTTPS, but requested an insecure image 'http://i.imgur.com/SmhiNVU.gif'. This content should also be served over HTTPS.

> Mixed Content: The page at 'https://www.camptocamp.org/' was loaded over HTTPS, but requested an insecure image 'http://sos.exo.io/c2corg_demov6_active/1480069059_471364301BI.png'. This content should also be served over HTTPS.

**Comment by asaunier** [comment]
OK thanks. I have made sure the adserver uses https URLs for the banner images and will send a reminder to the advertisement team.
