### ISSUE TITLE
Prod - upload of picture is not working

### ISSUE THREAD

**Issue by HSERGERAERT** [c2corg/v6_ui#1134]
I made test to link pictures to a profile, or to an outing, I always get the message "unexpected error".
(I have seen a similar issue from Martin but can't find it)

**Comment by asaunier** [comment]
Martin has reported the problem here: https://github.com/c2corg/v6_ui/issues/929#issuecomment-265545710

I don't close the issue because it's probably a distinct problem.

**Comment by stef74** [comment]
but we can merge in one issue ...

**Comment by asaunier** [comment]
I would prefer not. As I said it's probably 2 different issues, as a result 2 different solutions to bring.

**Comment by HSERGERAERT** [comment]
Do you need details (profile or outing) ? or do you have the same issue yourself ?
Image was 65 ko
https://www.camptocamp.org/outings/510181/fr/bel-oiseau-couloir-sse-en-boucle-par-le-col-de-bel-oiseau#/&gid=1&pid=4

**Comment by asaunier** [comment]
I had the same problem uploading an image on an outing, but I don't really have more info than you.

The image upload seems to work but the API request fails with error:
```
{"status": "error", "errors": [{"location": "body", "description": "please consult the server logs", "name": "unexpected error"}]}
```
The request payload seems OK (all data including filename from the image backend are provide).
Looking at the logs is required, I don't really know how to do it on the new infra.

**Comment by HSERGERAERT** [comment]
@asaunier @mfournier @stef74 
Agreement with status Blocking and Go-live, Hope infra has a hint how to solve this issue

**Comment by loicperrin** [comment]
Same pb, error "please consult the server logs : unexpected error" when uploading an image on an outing (after manuel resizing to 500 ko)

**Comment by tsauerwein** [comment]
The public address `images.camptocamp.org` is used, which is not yet available. We should use the internal address of the image service for the API config.

**Comment by asaunier** [comment]
Changes have been made and I have succeeded in uploading an image to a route.
