### ISSUE TITLE
Add DMARC record

### ISSUE THREAD

**Issue by stef74** [c2corg/v6_ui#1136]
To improve deliverability add DMARC reccord 

> You do not have a DMARC record, please add a TXT record to your domain _dmarc.camptocamp.org with the following value: v=DMARC1; p=none

ANtispam test for prod : http://www.mail-tester.com/web-898o6

See original discussion #1115

**Comment by mfournier** [comment]
```
$ host -t TXT _dmarc.camptocamp.org
_dmarc.camptocamp.org descriptive text "v=DMARC1; p=none"
```

@stef74 can you recheck and take care of closing the issue if the mail-tester check is happy ?

**Comment by stef74** [comment]
score 7.3 great ;-) http://www.mail-tester.com/web-p2ta0

**Comment by mfournier** [comment]
On Mon, Dec 12, 2016 at 02:25:05AM -0800, stef74 wrote:
> score 7.3 great ;-) http://www.mail-tester.com/web-p2ta0

Great, and the TVD_SPACE_RATIO_MINFP is easily fixable:
https://wiki.apache.org/spamassassin/Rules/TVD_SPACE_RATIO
