### ISSUE TITLE
Missing recentering tools in mobile maps

### ISSUE THREAD

**Issue by stef74** [c2corg/v6_ui#1137]
On mobile we don't have recentring tools on the map.

**Comment by ginold** [comment]
you sure you clicked on the map button on the bottom of the page? or is it another page you are speaking of?
![screenshot from 2016-12-08 12-22-20](https://cloud.githubusercontent.com/assets/7814311/21008213/03fd7aac-bd41-11e6-807d-d51b3d25d486.png)

**Comment by stef74** [comment]
My screen (iphone5s) 
![img_0867](https://cloud.githubusercontent.com/assets/3962997/21008543/757fb3a6-bd42-11e6-846e-013fa3264ceb.PNG)

**Comment by stef74** [comment]
@ginold it s Word on m'y iPad mini not on m'y iPhone , size screen issue ?

**Comment by ginold** [comment]
I don't understand 

>  it s Word on m'y iPad mini 

You are browsing with Word (microsoft) ? :confused:  i think not. 
All in all, it's surely not a screen size issue.

**Comment by brunobesson** [comment]
I think I saw someone reporting something similar: apparently on some devices buttons are placed on an upper position and hidden by the header.

**Comment by brunobesson** [comment]
E.g. on my phone, I get the following result: 
![screenshot_2016-12-24-08-39-30](https://cloud.githubusercontent.com/assets/2234024/21465867/ba48d0fc-c9b4-11e6-9805-9d24833e286a.png)

**Comment by stef74** [comment]
Word = works. It s probably an issue of size if screen ...

**Comment by stef74** [comment]
I can show it in chrome on IOS not on safari.

**Comment by stef74** [comment]
Same issue on iphone 7s (screen are more big than 5)

**Comment by fjacon** [comment]
So it is just a problem on safari, right ?

**Comment by dkocich** [comment]
> So it is just a problem on safari, right ?

Yes, I see this problem only on iPhone (portrait view) with BrowserStack.

A problem is probably with the use of calc in CSS http://caniuse.com/#feat=calc and VH http://caniuse.com/#feat=viewport-units (known issues for Safari). Some styles are not applied the same way and then there are some differences on some places in different browsers and versions. I am trying to solve this using media queries to target only iPhone's safari and apply different styles but I am not sure if it is a good way.
http://stephen.io/mediaqueries/
https://css-tricks.com/snippets/css/media-queries-for-standard-devices/

**Comment by asaunier** [comment]
Tested in browserstack.com (emulator):
* Android 6 Chrome or FF: OK
* Android 4.4 Chrome or FF: OK (but KO on my real Android 4.4 phone with Chrome: the navigation and recentering tools are hardly/not visible)
* iOS 10 with Safari: KO (no navigation or recentering tools visible)
* Safari in iPhone 6S: KO (not visible)
* Chrome on iPhone 6S: OK
* FF on iPhone 6S: OK
* Safari 10.1 on macOS Sierra: OK
* Windows Phone 8.1: OK

**Comment by asaunier** [comment]
Perhaps it's worth testing if this (old) PR fixes the problem https://github.com/c2corg/v6_ui/pull/1506

**Comment by desnoes** [comment]
It does not work on Chrome (Androïd, Galaxy j5)
![screenshot_20170720-131246](https://user-images.githubusercontent.com/19892089/28414817-868462e4-6d4d-11e7-8f0e-449ce0903782.png)

**Comment by asaunier** [comment]
> It does not work on Chrome (Androïd, Galaxy j5)

But it does not work either in prod, does it?

PR #1755 only impacts webkit-based browsers such as Safari, not Chrome or FF.

**Comment by desnoes** [comment]
No it does not work either on prod. I thought the PR would solve the issue for all browsers.

**Comment by stef74** [comment]
Tested on Iphone5S. Ok on landscape ... not in portrait.

**Comment by asaunier** [comment]
> I thought the PR would solve the issue for all browsers.

The PR explicitly mentions that it only concern Safari. It's an old PR by @dkocich that I have updated (but made no further improvements about other browsers).

> Tested on Iphone5S. Ok on landscape ... not in portrait.

OK thanks.
Does the PR introduce layout flaws or does it only improve a bit the layout without impacting other configs?
The question is: Is it OK to merge the PR even though all parts of the issue are not fixed or should we rather wait?

**Comment by asaunier** [comment]
@desnoes I have just updated the demo website to make it use branch map-recenter-position-safari (see PR https://github.com/c2corg/v6_ui/pull/1755). It's a quite outdated branch (1.5 month old), so many fixes and improvements currently in prod are not available but at least it should bring some improvements about the recentering tool buttons positioning with Safari. For instance in the outings advanced search page: http://www.demov6.camptocamp.org/outings

Could you have this page tested on several devices/browsers and let me know if it's OK to merge this PR?
Thanks!

**Comment by desnoes** [comment]
Test on Samsung Galaxy J5 with Chrome => ok

**Comment by julsbreakdown** [comment]
:tada:
