### ISSUE TITLE
Cropped dropdown in following page

### ISSUE THREAD

**Issue by tonio** [c2corg/v6_ui#1140]
In https://www.camptocamp.org/following

Parent container height isn't big enough, dropdown is cropped with a bad scroll…

![screenshot from 2016-12-08 11-11-53](https://cloud.githubusercontent.com/assets/21686/21006048/7ff2a876-bd37-11e6-9de4-a492e868a1a9.png)

**Comment by ginold** [comment]
the parent div probably needs `overflow-y: visible;`

**Comment by stef74** [comment]
@tonio confirm is ok for you (in production since 1 hour) ?

**Comment by tonio** [comment]
![screenshot from 2016-12-16 16-00-12](https://cloud.githubusercontent.com/assets/21686/21267084/10b4c11a-c3a9-11e6-8b71-8a2f3b278329.png)

Nearly (-:  now just a small unexpected scroll. (Linux, FF up-to-date, cache cleared)

**Comment by desnoes** [comment]
fixed on demo
