### ISSUE TITLE
Sitemap in prod have an error

### ISSUE THREAD

**Issue by stef74** [c2corg/v6_ui#1141]
I have tested the sitemap on google webmaster tools : www.camptocamp.org/sitemap.xml ... but error on date 

![capture](https://cloud.githubusercontent.com/assets/3962997/21006267/696a2010-bd38-11e6-96de-3e7cce2fb897.PNG)

**Comment by brunobesson** [comment]
According to the specifications (https://www.sitemaps.org/protocol.html), there is no error there, the current values are valid W3C date and time formats (https://www.w3.org/TR/NOTE-datetime). Which online tool did you use for validation?

**Comment by stef74** [comment]
google wbemaster tools ;-)

**Comment by brunobesson** [comment]
I investigated a little bit more and indeed, looks like the format for the sitemapindex file has bad `<lastmod>` values (while it is correct for sitemaps). The format is `2016-12-08T10:17:34.963608` when it should be `2016-12-08T10:17:34.963608+00:00`

**Comment by stef74** [comment]
I test this morning but not blocking point

**Comment by stef74** [comment]
it's ok
