### ISSUE TITLE
Scroll in topoguide searches

### ISSUE THREAD

**Issue by brunobesson** [c2corg/v6_ui#1144]
Currently, the scroll applies to both the results and the filter part.
Thus, when we scroll down, we cannot navigate within result pages (the green arrows). I feel that at least this element should remain visible.

What do you think?

**Comment by ginold** [comment]
you mean that the green arrows should always be visible? 
I agree, or at least put the same arrow at the end of the list.

**Comment by brunobesson** [comment]
@ginold yes that's it

**Comment by brunobesson** [comment]
There is at least the navigation items in the bottom of the list. Closing.
