### ISSUE TITLE
In associated cards, activity is not translated

### ISSUE THREAD

**Issue by brunobesson** [c2corg/v6_ui#1145]
Some examples:

* Route associated to outing
![toto](https://cloud.githubusercontent.com/assets/2234024/21008660/fa9c0954-bd42-11e6-8adf-aa47110b942d.png)
* last outings of a route
![toto2](https://cloud.githubusercontent.com/assets/2234024/21008661/fa9c5512-bd42-11e6-9ba3-47a3d2890d1e.png)

**Comment by asaunier** [comment]
There are also some rating tooltips that are not translated (whereas they are translated in Transifex). Some others are actually translated.

Perhaps related to https://github.com/c2corg/v6_ui/issues/1147

**Comment by desnoes** [comment]
fixed on demo
