### ISSUE TITLE
On user's profile page, add link to add him to ones friends

### ISSUE THREAD

**Issue by brunobesson** [c2corg/v6_ui#1146]
Currently, there are many missing _shortcuts_ in V6 to ease or simplify actions.
One of them could be adding a button to add/remove a user to your friends list.

**Comment by tsauerwein** [comment]
Apparently the star button is not clear enough. What could we do to make it more obvious?

![image](https://cloud.githubusercontent.com/assets/266474/21009056/ec469ade-bd44-11e6-9a62-4b406d7933f1.png)

**Comment by brunobesson** [comment]
You're right, I missed it!
Don't have an answer yet, it's too new to make any suggestion.

**Comment by tsauerwein** [comment]
Maybe display it on the same line as the user name?

**Comment by asaunier** [comment]
In Twitter, the follow button contains a text, not an icon. It's probably clearer.
But it means the button should be moved somewhere else.
