### ISSUE TITLE
First access (non connected mode): message error caused by the feed

### ISSUE THREAD

**Issue by desnoes** [c2corg/v6_ui#1148]
I asked a friend of mine to test the first release. She has got the following error message (Browser: safari). She does not have any account.
![telechargement](https://cloud.githubusercontent.com/assets/19892089/21009148/76d02f58-bd45-11e6-8813-6fe52cfd08da.png)

**Comment by asaunier** [comment]
Has she tried to reload the page?

Perhaps she is behind a proxy that strips some headers, as reported by @lbesson ?

**Comment by tsauerwein** [comment]
> Perhaps she is behind a proxy that strips some headers, as reported by @lbesson ?

In the logs I see no problem with the feed. So that could be likely.

**Comment by HSERGERAERT** [comment]
I already had this issue. I suppose the person already did test on demov6.
The cache might be the problem. If the person can connect then it should be solved.

@desnoes : can you confirm if the person already did test on Beta server, the one from c2c or from SA.
If yes, then we should not investigate.

**Comment by asaunier** [comment]
Also try to clear the browser cache, just in case?

**Comment by stef74** [comment]
I wait @desnoes answer and probably close after

**Comment by desnoes** [comment]
She reload the page and it was ok => close the issue
