### ISSUE TITLE
Is it a problem to access the auth page when already authenticated?

### ISSUE THREAD

**Issue by asaunier** [c2corg/v6_ui#115]
Could we have a conflict if the user logs in using the auth page while already logged in?

**Comment by gberaudo** [comment]
What do you mean by `conflict`?

**Comment by asaunier** [comment]
No clue. Just wanting to make sure it is not a big deal if for some reason a user opens the auth page and reauthenticates (possibly with another username) while still authenticated.

**Comment by gberaudo** [comment]
In the case you describes, the user authentication (in both UI and forum) will be replaced by the new one.
I think it is the expected behaviour. Right?

**Comment by asaunier** [comment]
OK thanks.
