### ISSUE TITLE
Many users haven't understood the outing's wizard

### ISSUE THREAD

**Issue by brunobesson** [c2corg/v6_ui#1150]
Thus, many outings have only informations concerning the first page (on desktop). See e.g. https://www.camptocamp.org/outings/828389/fr/six-blanc-val-ferret-par-la-combe-n. Maybe we should disable the submit button unless on last page? But this could be applied to creation only, not edition. Or, clicking on it when not on the last wizard page goes to next page unless it's the last one?

**Comment by asaunier** [comment]
That's what I was afraid of and asked in this duplicate issue https://github.com/c2corg/v6_ui/issues/987
In don't think we can wait for 6.3...

**Comment by brunobesson** [comment]
Sorry, I missed it. Closing this issue thus. But indeed, #987 should be labelled with a high priority.

**Comment by ginold** [comment]
It would perhaps be nice to have a little tutorial when you first visit the page, as done on blablacar or airbnb or other pages when they put new functionalities.

The page black outs all the background and shows step-by-step new buttons etc.

**Comment by asaunier** [comment]
OK but that's quite a huge work I guess...

**Comment by stef74** [comment]
A video exist ...

2016-12-08 14:58 GMT+01:00 Alex Saunier <notifications@github.com>:

**Comment by HSERGERAERT** [comment]
Does it help ?
https://drive.google.com/file/d/0ByXg-Z7AjNOYUk9BOE9uYzRZUUU/view?usp=sharing
https://drive.google.com/file/d/0ByXg-Z7AjNOYWTZUSnJKMnVDTE0/view?usp=sharing
