### ISSUE TITLE
Suggestions for optimization of the UI

### ISSUE THREAD

**Issue by dkocich** [c2corg/v6_ui#1151]
Please look at results of tests here if we should create fixes for smaller issues
- https://developers.google.com/speed/pagespeed/insights/?url=camptocamp.org&tab=mobile
- http://nibbler.silktide.com/en_US/reports/www.camptocamp.org
- https://gtmetrix.com/reports/camptocamp.org/hy0HqEKu

**Comment by stef74** [comment]
@mfournier gzip compression seem to be not activated

**Comment by mfournier** [comment]
@stef74 @dkocich I activated this on the demo server. Waiting for feedback on this before updating this in production. nb: it's a trivial haproxy config, no code change, so no need to wait for 6.1 to enable this.

**Comment by asaunier** [comment]
@mfournier Thanks, that's really cool!
It brings a great gain in terms of file sizes.
For instance:
* ``deps.js``: 298 KB in demo / 906 KB in prod
* ``build.js``: 195 KB in demo / 536 KB in prod
* ``build.min.css``: 51 KB in demo / 232 KB in prod 
* personal feed API  request: 4.7 KB in demo / 28.8 KB in prod (not the same content though)

It seems to work for the demo forum as well.

I have observed no problem while testing the demo.
I am +1 to push this change to the prod.

**Comment by stef74** [comment]
Go for prod

**Comment by mfournier** [comment]
done
