### ISSUE TITLE
Outing creation: bug with safari

### ISSUE THREAD

**Issue by desnoes** [c2corg/v6_ui#1156]
The user told me all the pictos are overlapping (safari)=> he clicked on one picto and this has selected all activities. 
https://www.camptocamp.org/outings/828399/fr/pene-det-pouri-depuis-le-virage-d-aoube
and comments
https://forum.camptocamp.org/t/828399-fr/173287

Here is his screen shot 
![capture d ecran 2016-12-08 a 14 38 40](https://cloud.githubusercontent.com/assets/19892089/21012207/33dbcd6e-bd55-11e6-8e85-4478398988de.png)

**Comment by asaunier** [comment]
What version of Safari? An old one?

I'm pretty sure I have never observed this with my Safari at home. I know that @stef74 and others have tested with Safari as well.

**Comment by stef74** [comment]
I restest this evening ... but i have not observe any issue like this on safari

**Comment by asaunier** [comment]
I have asked for a more precise version info but the user told me that
> Mon MacBookPro est équipé avec safari, version de 2013.

I have recommended to upgrade.

**Comment by stef74** [comment]
I confirm if is ok this evening and probably close

**Comment by stef74** [comment]
As mentionned in comments Upgrad fixe the issue
