### ISSUE TITLE
Map position is lost when changing doc type

### ISSUE THREAD

**Issue by loicperrin** [c2corg/v6_ui#1162]
On routes result page, I center the map on the area where I want to find routes.
If I want to see WP/Access, I lost the previous map position when changing "route" to "WP".

**Comment by asaunier** [comment]
A new page is loaded when changing the document type, all filters are indeed reset.
It could be possible tough when changing the page to get the bbox parameter if any and to add it to the new page URL before loading it.

**Comment by loicperrin** [comment]
OK

**Comment by fbunoz** [comment]
On Desktop and mobile (FF) : when changing the doc type, the map is zoomed out (one zoom step), whereas the bbox is correct. Then, the results are in a virtual rectangle smaller than the visible map : 

![map-extend](https://cloud.githubusercontent.com/assets/3902555/22621826/d0ff42e2-eb2c-11e6-940c-319efa1456fa.png)
