### ISSUE TITLE
Profile tool

### ISSUE THREAD

**Issue by loicperrin** [c2corg/v6_ui#1163]
It would be very useful to add "profile tool" to see the profile of GPS track on outing (as in V5).

**Comment by lbesson** [comment]
Is it something that will be done by the SA? I would be interested to work on it if not.

**Comment by HSERGERAERT** [comment]
Hi @lbesson , clearly not in the actual contract of the SA, it's an extra request. We would love that you take care of the demand.

**Comment by lbesson** [comment]
Is there currently a way to retrieve the gpx / coordinates from the api?

**Comment by tsauerwein** [comment]
> Is there currently a way to retrieve the gpx / coordinates from the api?

No need to make an extra request, the geometry is already available. You can check how it is done for the map:

https://github.com/c2corg/v6_ui/blob/master/c2corg_ui/static/js/map/map.js#L66-L67
https://github.com/c2corg/v6_ui/blob/7a304a7d4eb8d4713acd5561ed9316497efd1dd6/c2corg_ui/templates/outing/view.html#L41-L53

**Comment by lbesson** [comment]
Ok, I see that elevation seems to be available (it wasn't in v5)

One question though: is the geometry simplified server side (that was the case in v5)?

**Comment by tsauerwein** [comment]
Client-side and server-side, yes.

**Comment by brunobesson** [comment]
See #1728

**Comment by asaunier** [comment]
In production.
