### ISSUE TITLE
Show only one feed entry per document

### ISSUE THREAD

**Issue by stef74** [c2corg/v6_ui#1164]
According to specification https://docs.google.com/document/d/1QWQFIqSO1YVPFKCRjI7FlYsCcMPLru668u9Qj4O5npw/edit

> the activity feed would not advertise the document updates, only the creations.

Lot of complaint about update ... too many update.

**Comment by asaunier** [comment]
> the activity feed would not advertise the document updates, only the creations.

That's the case I think.

But uploading images or associating users to an outing are marked as updates though.
Perhaps we should make sure that the feed contains only one card for a given document at a time.

**Comment by stef74** [comment]
> Patrick Vuilleumier a mis à jour un itinéraire  

is an un update ?

**Comment by tsauerwein** [comment]
Patrick Vuilleumier added photos and also created this route?

**Comment by desnoes** [comment]
> Perhaps we should make sure that the feed contains only one card for a given document at a time.
Yes, when a user upload its image one by one, the result is awful on the feed.

**Comment by asaunier** [comment]
@tsauerwein Despite what we have discussed this morning, it seems that in some cases several cards are actually created. See the example below I have found 15 min ago in my feed: same user, same document (a route), same actions (images uploading).

![sans titre](https://cloud.githubusercontent.com/assets/1192331/21142927/bdab8bd6-c144-11e6-86f4-1947ab6e21f0.png)

**Comment by tsauerwein** [comment]
Yes, this is excactly the case I mentioned. Patrick V. is not the creator of [this route](https://www.camptocamp.org/routes/830730/fr/louettes-econdoue-couloir-w), and in this case a feed entry is created each time fotos are uploaded.

**Comment by fbunoz** [comment]
By default, only outing, route and waypoint creations should be showed in the feed.
Other entries (changes, association, images, ...) should be showed only if the membrer has configured the feed to add some entry types.
For now, the feed is polluted by : 

- image uploading (and the bugs on image upload makes the users prefer to upload their images one by one to not lose all upload)
- members association to outings

**Comment by tsauerwein** [comment]
Do you have an example of what you would consider "pollution" in the feed?

To give some background about what is shown in the feed and how the feed entries are generated:

- The creation of a new document (except user profiles and images) generates a feed entry.
- When updating the participants of an outing, the **existing** feed entry for the outing is updated and the time is set to now, so that the entry appears at the top of the feed. No new feed entry is generated.
- When uploading images, the **existing** feed entry for the document, that the images are uploaded to, is updated and the time is set to now. If another user, than the creator of the document, uploads images, a new feed entry is generated (see https://github.com/c2corg/v6_ui/issues/1164#issuecomment-266745141, this can be optimized but there only very few examples in the feed).

Based on this, what improvements would you like see?

**Comment by desnoes** [comment]
@tsauerwein: your specs are fine to me. Some user defined settings for the feed could be conisdered but i think this is for later. The priority is to have only one card per outing/route and this is the case with the proposed spec.

**Comment by tsauerwein** [comment]
> ... the proposed spec.

To be clear: This is not the proposed spec, this is how it works right now.

**Comment by desnoes** [comment]
Ok, i clarify the need: the objective is to have only one card per outing/route/WP in the feed viewed by an user. 
So if a document is created => the card is created and appears in the feed,, as it is currently the case. When an outing/route/WP is modified (updating the participants of an outing/ uploading images), a new card shall not be generated. The existing card should be updated with the new information. The updated card is then moved to the top of the feed.

**Comment by asaunier** [comment]
> By default, only outing, route and waypoint creations should be showed in the feed.
Other entries (changes, association, images, ...) should be showed only if the membrer has configured the feed to add some entry types.

@fbunoz Who has decided this?
That kind of instructions should be validated by the coordination. I have seen no debate about this among the coordination.

@tsauerwein don't take these requests into account until further confirmation. Thanks.

**Comment by fbunoz** [comment]
> what you would consider "pollution" in the feed?

For example, there are 3 entries for 1 outing : 
![feed_v6](https://cloud.githubusercontent.com/assets/3902555/21329657/20677344-c63a-11e6-8a09-d9bd111d2695.png)

> When updating the participants of an outing, the existing feed entry for the outing is updated and the time is set to now, so that the entry appears at the top of the feed. No new feed entry is generated.

Ok !
It is not clear by reading "xxx has updated an outing", I thougth there is another entry for the creation.
It is the concept of the feed.

**Comment by stef74** [comment]
@tsauerwein it is possible to have only one card in the feed for a document ... if i update image on outing i only show last update

**Comment by asaunier** [comment]
This is an API issue (the UI simply display the cards according to the data provided by the API feed service). I have created a dedicated API issue at https://github.com/c2corg/v6_api/issues/598

**Comment by stef74** [comment]
open until API fix ... user test UI not API

**Comment by asaunier** [comment]
But we're not going to open a UI issue for every API issue if there is nothing to do in the UI!?
Testers should also have a look at the API list of issues.

**Comment by celinestern** [comment]
My tests: 
When I upload pictures one after one, only one card is comming up in the feed.
When I upload pictures with the account of someone else who's associated in the outing, one other card is comming up the feed. 
Then we still have 2 cards for one outing.
But I don't really understand what it's suppose to be the goal...

**Comment by stef74** [comment]
Yes is correct ! one card per user per document.
Could you quick check if personnal feed is also consistent

**Comment by celinestern** [comment]
It's ok too in my personal feed

**Comment by asaunier** [comment]
> But I don't really understand what is suppose to be the goal...

@celinestern See the explanations here: https://github.com/c2corg/v6_api/issues/598#issuecomment-274816798
