### ISSUE TITLE
Route creation: select the first waypoint as main waypoint by default

### ISSUE THREAD

**Issue by brunobesson** [c2corg/v6_ui#1165]
Currently, no waypoint is by default the main waypoint, thus users create routes without prefixed name.

Several possibilities:
* select first waypoint as main waypoint by default. It should then removed if needed
* if no waypoint is selected when creating route, select highest one. But this causes a problem if we do not want a main waypoint, it would requires to edit afterwards
* if no waypoint is selected, ask question whether or not to associate one. Bad UI IMHO

**Comment by desnoes** [comment]
fixed on demo. There is a small traduction issue, i have translated the string ' unset main waypoint' in transiflex.

**Comment by fbunoz** [comment]
The problem came back with the last prod update.

**Comment by asaunier** [comment]
I have just tested with FF 50.1 on the demo and observed no problem: http://www.demov6.camptocamp.org/routes/828342/fr/un-itineraire-pour-main-wp-par-defaut
(I have created a route and only associated the WP => it has been made the main WP directly with no additional action, as expected).

Changes propaged to production recently seem to have no relationship with this feature:
> Image title should not be required when editing an image 
Incorrect WP longitude validation 
Add pagination buttons at the bottom of advanced search results 
Image upload: copyright should be allowed only for moderators 
Map scale design Ergo / Design 
Outing creation: the route search engine is confusing 
fixed WP 'Access': display errorfor the field "Type de transport en commun" 
Comments in topoguide
Add possibility to enlarge or hide map in the advanced search pages 
Show link "more results" only for the main simple search tool 
Sitemap in prod have an error
Cropped dropdown in following page 
No close outing end date button on mobile
Lien profil topoguide -> profil forum

**Comment by desnoes** [comment]
I didn't notice any problem since the last update.
@fbunoz: would you check again? If you do not observe the problem, please close the issue.

**Comment by desnoes** [comment]
I have juste tested on desktop (Chrome) on both the demo and the site, it works as expected.
@fbunoz and @stef74 : would you please check quickly ? Otherwise i will close this issue.

**Comment by stef74** [comment]
what is the test ?

**Comment by desnoes** [comment]
According to Bubu, there is a bug in the selection of a WP by default. Alex and i think it works fine.

----- Mail original -----
De: "stef74" <notifications@github.com>
À: "c2corg/v6_ui" <v6_ui@noreply.github.com>
Cc: "desnoes" <mathieu.desnoes@free.fr>, "State change" <state_change@noreply.github.com>
Envoyé: Jeudi 12 Janvier 2017 10:42:18
Objet: Re: [c2corg/v6_ui] Route creation: select the first waypoint as main waypoint by default (#1165)



what is the test ?

**Comment by stef74** [comment]
So I have to create a new route et add a WP ?

**Comment by desnoes** [comment]
>So I have to create a new route et add a WP ?
yes

**Comment by fbunoz** [comment]
> So I have to create a new route et add a WP ?

Yes.
But test also by creating a new route from the WP page : the WP is automaticaly associated, but it is not defined as main WP.
Ex : https://www.demov6.camptocamp.org/routes/828353/fr/creation-d-un-itineraire-depuis-la-page-d-un-wp-il-n-est-pas-mis-en-wp-principal-par-defaut

**Comment by desnoes** [comment]
@asaunier: do you have enough instructions ? It seems the explanations from @fbunoz are sufficient, aren't they ?

**Comment by fbunoz** [comment]
When we create a route from the page of a WP, the WP is automatically associated, but it is not set as main WP.
Ex : https://www.camptocamp.org/routes/add#w=841309

**Comment by fbunoz** [comment]
It works fine on the demo :-)
I need test on mobile, but it should work.
