### ISSUE TITLE
Accident reports associated to an outing isn't listed in the outing

### ISSUE THREAD

**Issue by brunobesson** [c2corg/v6_ui#1172]
See e.g. https://www.camptocamp.org/xreports/762685/fr/chute-dans-les-grands-couloirs-a-la-grande-casse and https://www.camptocamp.org/outings/762647/fr/grande-casse-couloir-des-italiens-greater-grands-couloirs

Note that the associated outing appears correctly in the report.

**Comment by brunobesson** [comment]
This bug was easy to fix! :+1:

**Comment by desnoes** [comment]
fixed on demo
