### ISSUE TITLE
Images: UI must use date and time instead of date

### ISSUE THREAD

**Issue by brunobesson** [c2corg/v6_ui#1176]
* On image page, date and time only displays date
* When editing, this is a date selector and not a date and time selector

**Comment by fbunoz** [comment]
It is a big bug : the Exif time is not stored.

- [From the API](https://api.camptocamp.org/images/829497), the time is 2016-12-07T00:00:00+00:00
- But in the Exif ([in the Jpeg](https://media.camptocamp.org/c2corg_active/1481324429_523379614.jpg)), the time is : 2016-12-07 15:01:57

In an image doc from the V5, the time has been migrated correctly.
To correct the time, after fixed the bug, we need to reback only the image uplaoded in the V6.

**Comment by loicperrin** [comment]
If time of images uploaded in V6 is not stored, this bug should be fixed in high prio.

**Comment by fbunoz** [comment]
The bug is worst as described here : https://github.com/c2corg/v6_images/issues/34

**Comment by brunobesson** [comment]
@stef74 you changed the priority from 6.1 to 6.4. IMHO, 6.4 is not a good choice, this is a pretty serious bug. The main impact being the ordering of pictures, which needs EXIF info.

**Comment by stef74** [comment]
this issue is part 6.1 milestone : https://github.com/c2corg/v6_ui/milestone/10

**Comment by brunobesson** [comment]
Grmpf. My bad, I'm sorry. It's the second time it happens to me.
The line in github is not clear enough :wink: 

>@stef74 modified the milestone: V6.1, V6.4 5 days ago

**Comment by asaunier** [comment]
*[ ] Concerning the image datetime details, it seems an API issue, see https://github.com/c2corg/v6_api/issues/599#issuecomment-271585546

* [ ] Concerning the image editing, there is also a UI problem because only a date selector is provided, not a time selector.

**Comment by tsauerwein** [comment]
https://github.com/c2corg/v6_ui/pull/1394 makes sure that the datetime is extracted correctly. What is left to do is to update the edit form so that also the time can be changed.

**Comment by fbunoz** [comment]
Is there a script to update all images uploaded on the V6 until now ?
It's all images from this one : https://api.camptocamp.org/images/828237 (included), ~10000 images.

**Comment by asaunier** [comment]
No

**Comment by fbunoz** [comment]
Ok, I created a new issue : https://github.com/c2corg/v6_ui/issues/1419

**Comment by asaunier** [comment]
Closing the issue since it seems to work according to this example http://www.demov6.camptocamp.org/images/828388/fr/ctpyipip

**Comment by fbunoz** [comment]
It doesn't work with this photo : the date is the date of last file change. https://www.camptocamp.org/images/844781/fr/descente-du-cap-de-la-pene

For this photo, there isn't a date, but the EXIF has a date : https://www.camptocamp.org/images/844791/fr/aiguille-de-charlanon-sommet

It seems that the IPTC date is extracted. It is the EXIF date which is correct.

**Comment by loicperrin** [comment]
If the fix has been pushed in prod, I confirm there is still some problems. 
In this outing https://www.camptocamp.org/outings/846310/fr/pic-du-rognolet-lac-le-lay-col-de-paris-st-jacques-col-s-de-montartier, photo#2 has been taken after photo#3.

**Comment by dkocich** [comment]
> If the fix has been pushed in prod, I confirm there is still some problems.
> In this outing https://www.camptocamp.org/outings/846310/fr/pic-du-rognolet-lac-le-lay-col-de-paris-st-jacques-col-s-de-montartier, photo#2 has been taken after photo#3.

Everything is ok with ordering (based on time visible in Img details).

**Comment by loicperrin** [comment]
> Everything is ok with ordering (based on time visible in Img details).

Indeed now it is OK (maybe it has been fixed in a recent version).
