### ISSUE TITLE
Images are not ordered by date

### ISSUE THREAD

**Issue by brunobesson** [c2corg/v6_ui#1177]
In an outing or wherever applies, images should be sorted by date, or by default, by id.

**Comment by loicperrin** [comment]
This point is very uncomfortable: if we upload image one by one, the last one appears first. This is not logical!

**Comment by asaunier** [comment]
> This point is very uncomfortable: if we upload image one by one, the last one appears first. This is not logical!

Perhaps only in the page you are currently uploading images? I admit it is a weird behaviour but when you reload the page, the images are sorted in the order they have been uploaded. Aren't they?

**Comment by loicperrin** [comment]
> when you reload the page, the images are sorted in the order they have been uploaded. Aren't they?

Yes probably indeed.

**Comment by fbunoz** [comment]
See also : https://github.com/c2corg/v6_ui/issues/1176

**Comment by desnoes** [comment]
Fixed on demo -cf. http://www.demov6.camptocamp.org/outings/828402/en/tete-de-vauclave-rrr). I have uploaded the images in a disorder manner and they are displayed ordered by date and time.
