### ISSUE TITLE
Search: problem with filters (value selection on mobile)

### ISSUE THREAD

**Issue by desnoes** [c2corg/v6_ui#1179]
I found a big problem for the search, which is mainly apparent with a mobile (galaxy J5, lastest version of Android). 

When i open all the filters, i have the following initial state
![initial state](https://cloud.githubusercontent.com/assets/19892089/21073174/5add235c-bed8-11e6-8bc2-f7e874c97e5b.jpg)

Then, i want to modify one parameter, for instance 'altitude maximale'. I had many difficulty and often it was impossible to move the right orangeous circle that represent the upper bound (first big issue). Then i found it was possible to clik somewhere in the horizontal bar to move this upper bound. I realized the value of the parameter is not updated. In the following image, the value should not be 8850m, it should be at least the half. On desktop, the problem is the same. If i use the mouse to move the upper bound, its value is modified immediatly.
![search bug](https://cloud.githubusercontent.com/assets/19892089/21073202/b85bf526-bed8-11e6-899a-342a16cb92de.jpg)

On mobile, it is almost impossible to select the orientation. I never succeeded to select NW. Maybe a list would be easier to handle on mobile.

**Comment by AlexisDemongeot** [comment]
What's not work : if you try to move the boundaries (upper or lower bound) just touching near the orange circle on the scale, and the nearest cirle come where you touch. Scaling values doesn't change. It's not working on Chrome PC, Android or Windows phone.

![capture](https://cloud.githubusercontent.com/assets/24522280/21100129/af851f54-c072-11e6-891e-aecda613d30d.PNG)

On Chrome and out-of-box navigator on CM11 (Android 4.4) I had no problem to see and manage searching fields. I had no problem on orientation nor other fields with scale. And scaling value change without problem.

On Windows mobile, it's a little bit difficult to act on the orange circle, the move yet serve to change between opened tabs. 

![screenshot_2016-12-12-14-02-30](https://cloud.githubusercontent.com/assets/24522280/21100365/fdb454e6-c073-11e6-849a-5ee5ba317ee7.png)

And for orientation, it works well (try to not seeing the problem scaling by touching only) : 

![screenshot_2016-12-12-14-02-00 1](https://cloud.githubusercontent.com/assets/24522280/21100367/02ec3c8a-c074-11e6-9667-27ab4dd662cd.png)

**Comment by desnoes** [comment]
You are lucky Alexis. For me this is still a nightmare. It is simply not usable (with Chrome and Android 6.0.1).

**Comment by brunobesson** [comment]
For range sliders usability, see also #1256 

BTW, maybe we could close this issue that describes 2 problems being separately exposed in #1256 and #1257
@desnoes are you OK with this, or did I miss something?

**Comment by desnoes** [comment]
@brunobesson : ok with your comment. I close this issue.
