### ISSUE TITLE
Prerender image dimensions

### ISSUE THREAD

**Issue by lbesson** [c2corg/v6_ui#1180]
https://www.camptocamp.org/images

Images load creates a lot of flickering. Are the image dimensions still stored in v6 and could it be returned by the API? This way, image thumbnails could be pre-sized thus avoiding the rather annoying flicker.

**Comment by asaunier** [comment]
There have been changes on the cards columns, it's available in the demo but not in prod yet.
Now all images cards are squared, thus have a fixed size.

**Comment by ginold** [comment]
>Are the image dimensions still stored in v6 and could it be returned by the API?

I think they are not, but this would also allow to have a nice zoom-in animation when clicking on an image in the gallery (the plugin needs to know the thumbnail size and the original dimensions).

@lbesson, has the issue been fixed for you? I think the images don't flicker anymore.

**Comment by asaunier** [comment]
> Are the image dimensions still stored in v6 and could it be returned by the API?

Stored: yes, see: https://github.com/c2corg/v6_api/blob/master/c2corg_api/models/image.py#L41-L43
Returned: yes, see https://github.com/c2corg/v6_common/blob/master/c2corg_common/fields_image.py#L11-L12

Set: no clue...

**Comment by desnoes** [comment]
@lbesson : could you test if it is fixed on the demo site ?

**Comment by lbesson** [comment]
Not before the 27th
