### ISSUE TITLE
Images associated to a profile are not shown if profile is not geoloalized

### ISSUE THREAD

**Issue by brunobesson** [c2corg/v6_ui#1183]
Note: I only report a behaviour mentionned in the forum, this issue needs to be tested.
See https://forum.camptocamp.org/t/questions-publiques-attendant-une-reponse/173588/12?u=b_b

**Comment by asaunier** [comment]
Indeed. My mistake. PR #1211 should fix the problem.

**Comment by stef74** [comment]
@asaunier not ready to test ?

**Comment by asaunier** [comment]
The PR has been merged an hour ago. I don't think the demo has been updated in the meantime.
