### ISSUE TITLE
Strange ordering of outings in search with parentheses

### ISSUE THREAD

**Issue by brunobesson** [c2corg/v6_ui#1184]
See https://forum.camptocamp.org/t/recueil-de-bugs-divers-sur-le-topoguide/173596/15?u=b_b

Outings ordering is strange:
https://www.camptocamp.org/outings#bbox=-416959%252C4518874%252C1216958%252C6681125&q=pravouta
![toto1](https://cloud.githubusercontent.com/assets/2234024/21093062/203badb2-c050-11e6-9528-40c3f6db82dc.png)

**Comment by asaunier** [comment]
Could you precise what is strange?
Please note changes have already been done in cards sorting, see the demo, not in prod yet.

**Comment by tsauerwein** [comment]
Also note that if you are searching with a filter on the title, the results are ordered by a relevance score for the search term.

**Comment by asaunier** [comment]
Probably a duplicate of https://github.com/c2corg/v6_ui/issues/1130 :)

**Comment by brunobesson** [comment]
>Probably a duplicate

Yes, closing this issue, thus.
