### ISSUE TITLE
WP hut field "custodianship" is not displayed correctly

### ISSUE THREAD

**Issue by fbunoz** [c2corg/v6_ui#1185]
On the edit page, the field "custodianship" can take [4 values](https://github.com/c2corg/v6_common/blob/master/c2corg_common/attributes.py#L606-L611), as specified : 

-    'accessible_when_wardened'
-    'always_accessible'
-    'key_needed',
-    'no_warden'

But in the doc page, the value  'always_accessible' is displayed as 'yes'.
The values are translated correctly in transifex, it is not a translation issue.

Ex : https://www.camptocamp.org/waypoints/108508/fr/refuge-des-oulettes-de-gaube

**Comment by desnoes** [comment]
fixed on demo
