### ISSUE TITLE
Cards improvements

### ISSUE THREAD

**Issue by asaunier** [c2corg/v6_ui#1186]
* [x] Cards should be a bit wider but less high => use 2 columns instead of 3 for standard screens. 3 columns (or more) only for very big screens. Perhaps also increase a bit the threshold at which only one column is used.
* [x] As much as possible, we should avoid having too many lines
* [x] Reduce the font size to about 75%

**Comment by stef74** [comment]
For infos in search v5 we can see around 12 document in one screen (1366x786) see : http://www.pre-prod.dev.camptocamp.org/outings to compare. In v6 we can also see 12 but some infos is missing.

And 24 in home ... but it's not the topic here.

**Comment by asaunier** [comment]
> For infos in search v5 we can see around 12 document in one screen (1366x786) see : 

Here is what I can see in my browser for the v5 preprod site (I have removed your URL because I am not sure it should be made public):

<img width="400" alt="capture d ecran 2016-12-12 a 17 24 27" src="https://cloud.githubusercontent.com/assets/1192331/21106882/0df83a7c-c090-11e6-9257-e878b6fb5134.png">
