### ISSUE TITLE
Add possibility to enlarge or hide map in the advanced search pages

### ISSUE THREAD

**Issue by asaunier** [c2corg/v6_ui#1187]
Perhaps a duplicate of https://github.com/c2corg/v6_ui/issues/428 but I prefer to create a new issue to make it clearer.

* [x] No change for mobile screens: the map is hidden by default and shown full page on request.
* [x] Keep the default behaviour as is: half page map by default for desktop screen.
* [x] Add button to enlarge the map to the full page (perhaps keep the menu and header visible)
* [x] Add a button to hide the map

**Comment by mgerbaux** [comment]
Same evolution should be planned for georeferenced document pages (with a vertical enlargement of the map)

**Comment by asaunier** [comment]
> Same evolution should be planned for georeferenced document pages (with a vertical enlargement of the map)

Perhaps you're right but that's not what should be done in this issue. If needed it should be discussed in a dedicated issue. I have then made obvious this is not a task required for this issue, thanks :)

**Comment by fbunoz** [comment]
> it should be discussed in a dedicated issue.

Done : https://github.com/c2corg/v6_ui/issues/1191

**Comment by ginold** [comment]
Continuing the discussion from #1191 

**Still a question: where to put the toggle list/map buttons?**


Normal

![screenshot from 2016-12-13 15-42-32](https://cloud.githubusercontent.com/assets/7814311/21144409/ca5070d0-c14a-11e6-8711-c498b7b0889f.png)

enlarge map (if anyone knows the function to update the map on resize it would be cool)

![screenshot from 2016-12-13 15-42-03](https://cloud.githubusercontent.com/assets/7814311/21144419/d4678658-c14a-11e6-8240-07dfe9efb193.png)

enlarge list

![screenshot from 2016-12-13 15-42-17](https://cloud.githubusercontent.com/assets/7814311/21144432/d9755486-c14a-11e6-9906-c17a8784bdc3.png)

**Comment by tsauerwein** [comment]
Not an answer to your question: But the map looks like you want to call [ol.Map#updateSize](http://openlayers.org/en/master/apidoc/ol.Map.html#updateSize) after having changed the size of the map.

**Comment by asaunier** [comment]
> Still a question: where to put the toggle list/map buttons?

Several possibilities:
* use the same approach than in a mobile screen => buttons in the bottom right corner of the map.
 * pros: consistent with the mobile
 * cons: not that visible and perhaps there are too many items on the map (attribution icon for instance)
* add the buttons near the filters buttons ("view results", "clear filters" etc.)
 * pros: more visible (especially if we use text buttons)
 * cons: enough space?
* @mgerbaux has suggested to make it possible to drag the map left border to resize it.
 * pros: more flexible about the size
 * cons: not that visible (need some kind of handle) + a bit less "on/off"

What happens when the map is closed? Will we have the same number of columns or more columns?

**Comment by asaunier** [comment]
> use the same approach than in a mobile screen => buttons in the bottom right corner of the map.

But then where are the "show map" button(s) placed when the map is hidden?

> add the buttons near the filters buttons ("view results", "clear filters" etc.)

But then where are the "hide map" button(s) placed when the map is full sized (filters are no longer visible)?

See @ginold 's suggestion at https://github.com/c2corg/v6_ui/pull/1208#issuecomment-266836063

**Comment by stef74** [comment]
On large screen we have the possibility to show 6 column without map ... so take in account, and also to push offset search to 48. 
The more efficient is to have offset base on column number ... but more simple is to incrase the ofsset to max possibility

**Comment by desnoes** [comment]
Result is very nice. Maybe the translation could be changed to avoid 'voir les listes' :)
