### ISSUE TITLE
Add possibility to enlarge or hide map in the document pages

### ISSUE THREAD

**Issue by fbunoz** [c2corg/v6_ui#1191]
Perhaps a duplicate of https://github.com/c2corg/v6_ui/issues/428 but I prefer to create a new issue to make it clearer.

* [ ] For mobile screens : the map is hidden by default (I prefer but must be discussed) and shown full page on request.
* [ ] For desktop screen : 230x height map by default and shown full page on request.
* [ ] Add button to enlarge the map to the full page (en return to default state by reclicking it).
* [ ] On desktop screen width < 2000px, fold the left menu to the hamburger menu. Keep the top menu.

**Comment by ginold** [comment]
>  For  desktop screen : 230x height map by default and shown full page on request.

I don't quite understand: 230px height map for advanced search? why 230? where would it be shown?
How about displaying the search how it is but let the user hide/show the map or list like this:

Normal

![screenshot from 2016-12-13 15-42-32](https://cloud.githubusercontent.com/assets/7814311/21144409/ca5070d0-c14a-11e6-8711-c498b7b0889f.png)

enlarge map (if anyone knows the function to update the map on resize it would be cool)

![screenshot from 2016-12-13 15-42-03](https://cloud.githubusercontent.com/assets/7814311/21144419/d4678658-c14a-11e6-8240-07dfe9efb193.png)

enlarge list

![screenshot from 2016-12-13 15-42-17](https://cloud.githubusercontent.com/assets/7814311/21144432/d9755486-c14a-11e6-9906-c17a8784bdc3.png)

**Comment by asaunier** [comment]
> I don't quite understand: 230px height map for advanced search? why 230?

I don't understand either. The current default size seems pretty good to me. I would recommend to keep it as is.

> How about displaying the search how it is but let the user hide/show the map or list like this:

@ginold Could you precise what you mean?
The screenshots seem to be what is wanted but I don't understand what you suggest to pass from one state to another?

**Comment by stef74** [comment]
For me it's not the right issue ... here the map on document not on search. This issue is Less priority than map in search ...

**Comment by ginold** [comment]
>  pass from one state to another? 

That is a good question, looking on the actual layout it's difficult to find a place for such a button (or 2 buttons -> toggle map and toggle list).

Maybe in the blue title next to the document type name ?

**Comment by asaunier** [comment]
@stef74 Arf, you're right :)

**Comment by stef74** [comment]
the right issue is #1187

**Comment by ginold** [comment]
^ right! but the questions/answers are still valid. Let's continue in the right issue.

**Comment by asaunier** [comment]
Why closing the issue? It has not been addressed. I have reopened it.
I will remove our recent comments when you have moved your screenshots to the right issue.

**Comment by ginold** [comment]
I thought it was a duplicate or a badly-explained-issue.

**Comment by asaunier** [comment]
> For mobile screens : the map is hidden by default (I prefer but must be discussed) and shown full page on request.

That makes sense indeed. A bit like in the advanced search pages.

For the other screen sizes (tablet/desktop), I recommend a single behaviour, consistent with the advanced search behaviour: small map by default (as currently) with a button to make the map grow to the full "payload" space (whole page except the left menu and header - as in the advanced search pages), the "enlarge" button being replaced by a "reduce" one.

I also recommend to try reusing the approach of the advanced search pages: the map container is enlarged (others are made invisible) and an event is launched, triggering the map object update. Perhaps we could reuse many of the changes done at https://github.com/c2corg/v6_ui/pull/1208/files

**Comment by stef74** [comment]
fix by new design
