### ISSUE TITLE
Filters window does not close correctly

### ISSUE THREAD

**Issue by desnoes** [c2corg/v6_ui#1192]
I do a search on the topoguide page. I click on all filters, then i click on 'Supprimer les filtres' and only the lower part of the window is removed, the upper part is still visible. It looks like 'supprimer les filtres' only remove filters related to the activity.
![filters](https://cloud.githubusercontent.com/assets/19892089/21106388/37b08f4c-c08e-11e6-9c45-34f5e00c4138.jpg)

**Comment by asaunier** [comment]
"Supprimer les filtres" removes... applied filters. It's a reset button you can use to make a new search.

If you want to hide the filters, ie. show the results, click on "Voir les résultats" :)

**Comment by desnoes** [comment]
Yes, but if i don't want to apply any filter i have to click on "Voir les résultats". This is weird.
Maybe the title "Supprimer les filtres" should be modified by "Réinitialiser les filtres" which is more accurate.
Anyway, this is not the top priority.

**Comment by asaunier** [comment]
> Yes, but if i don't want to apply any filter i have to click on "Voir les résultats".

No. If you click on "Voir les résultats", you see the results. The button has no impact on the filters. Which is logical.

Honestly I think the current behaviour is straighforward.
If you prefer, it is possible to change the translations, but that's a Transifex task, not a dev one.
Could we close the issue then?
