### ISSUE TITLE
Mountain bike ratings are not show in card

### ISSUE THREAD

**Issue by stef74** [c2corg/v6_ui#1195]
- [x] Add VTT rating in all card

**Comment by desnoes** [comment]
Example of MTB route: https://www.camptocamp.org/routes/829371/fr/tour-horaire-de-la-vallee-d-oueil

**Comment by asaunier** [comment]
> Example of MTB route

Thanks!
Then we can see the MTB route card for instance in this outing: https://www.camptocamp.org/outings/829390/fr/tour-horaire-de-la-vallee-d-oueil

The API actually returns the MTB ratings for the associated route: https://api.camptocamp.org/outings/829390
![capture du 2017-05-18 20-23-39](https://cloud.githubusercontent.com/assets/1192331/26217501/ee829856-3c07-11e7-8445-5b40033aeaec.png)

Probably a problem in https://github.com/c2corg/v6_ui/blob/master/c2corg_ui/static/js/card.js#L225 then
