### ISSUE TITLE
On creation/edition module, allow to increase textual box size

### ISSUE THREAD

**Issue by mgerbaux** [c2corg/v6_ui#1197]
For textual field, boxes are sometimes too small to work properly (for example for article).
![screenshot at 2016-12-13 09 04 57](https://cloud.githubusercontent.com/assets/22116605/21132345/ba65d070-c113-11e6-8648-3c9ab7b591a6.png)
In this screenshot, its obvious that this box could be higher for this screen

In V5; such boxes could be increased at demand

**Comment by fbunoz** [comment]
Moreover, the box should be resizable only for the height and not for the width.
To do that : 

- Remove !important attributs on all rules for height on textarea (there are several rules...).
- Add the rule on textarea : 
```resize: vertical;```

**Comment by ginold** [comment]
exactly what I wanted to do, thanks for pointing it out.
Maybe a good idea would be to implement an automatic height, getting bigger with text? 
It even is the case here, in the comment textarea of github.

**Comment by AlexisDemongeot** [comment]
Just a comment (if Textarea auto height is doing the job): 
Actualy, we can resize textual fields but only the widht : 
![image](https://cloud.githubusercontent.com/assets/24522280/23275687/c94e114c-fa07-11e6-9002-e7f55017b55e.png)
