### ISSUE TITLE
Banner sometimes overlaps the last sidemenu item

### ISSUE THREAD

**Issue by asaunier** [c2corg/v6_ui#1203]
This problem occurs since we have recently changed the sidemenu, adding an "outing" entry and moving "Camptocamp Association" to the footer.
The last action has pushed the banner up a bit.

We must update the CSS threshold that masks the banner when the window is not high enough.

**Comment by asaunier** [comment]
That could be fixed here https://github.com/c2corg/v6_ui/blob/master/less/sidemenu.less#L67-L77
But I would rather recommend to use shorter translations for the footer links and make sure those links use 2 lines, not 3. For instance in French "Licences des contenus" => "Licences", "Camptocamp Association" => "L'Association"?

@stef74 @mgerbaux @desnoes @loicperrin @fbunoz what do you think?

**Comment by stef74** [comment]
c2c Association ? ok for license

**Comment by asaunier** [comment]
I have just changed for "Licences" in Transifex for the French translation and for "Licenze" in Italian. I have not changed the other languages (footer links seem to be on 2 lines for those languages).

**Comment by stef74** [comment]
I don't show any banner ... @desnoes @loicperrin @mgerbaux could you confirm ?

**Comment by brunobesson** [comment]
I confirm this is the case. A minor bug, I could take a look.

**Comment by brunobesson** [comment]
See #1228

(there is a _little_ overlap problem)

**Comment by brunobesson** [comment]
Was e.g. ![overlap](https://cloud.githubusercontent.com/assets/2234024/21231060/3e61f780-c2e7-11e6-9946-c00bf32bdec3.png)

**Comment by stef74** [comment]
@brunobesson we can close ?

**Comment by brunobesson** [comment]
Yes, #1228 solved the issue.
