### ISSUE TITLE
Incorrect association removal permission in editing mode

### ISSUE THREAD

**Issue by asaunier** [c2corg/v6_ui#1209]
Changes have been done recently to show the association removal button only to authorized people.
But it seems nothing has been done in the editing forms: with a standard user I cannot remove associated WP to a route (not button shown in the route detail view), but the buttons are actually shown in the editing form.

=> detail views and editing forms should be consistent with each other.

**Comment by fbunoz** [comment]
> with a standard user I cannot remove associated WP to a route (not button shown in the route detail view), but the buttons are actually shown in the editing form.

Ok, it's just a design issue.
