### ISSUE TITLE
Parse BBcode etc. when displaying the content of a document

### ISSUE THREAD

**Issue by asaunier** [c2corg/v6_ui#121]
Documents contain BBcode as well as additional formating syntaxes.

See http://www.camptocamp.org/articles/151910/fr/aide-mise-en-forme-du-texte for details about the formatting syntaxes available in v5.

* [x] BBcode (see #127)
* [x] Markdown (see #127)
* [ ] Custom tags (see #131)

**Comment by asaunier** [comment]
In v5, text fields parsing is done at https://github.com/c2corg/camptocamp.org/blob/master/apps/frontend/lib/helper/FieldHelper.php#L739-L783

It relies on several helpers:
* SmartFormat: https://github.com/c2corg/camptocamp.org/blob/master/apps/frontend/lib/helper/SmartFormatHelper.php
* sfBBCode/sfPunBBCodeParserPlugin:  
 * https://github.com/c2corg/camptocamp.org/blob/master/plugins/sfPunBBCodeParserPlugin/lib/helper/sfBBCodeHelper.php
 * https://github.com/c2corg/camptocamp.org/blob/master/plugins/sfPunBBCodeParserPlugin/lib/sfPunBBCodeParser.class.php

**Comment by asaunier** [comment]
A few python BBcode parsers are available:
* https://github.com/search?utf8=%E2%9C%93&q=bbcode+python
* https://pypi.python.org/pypi?%3Aaction=search&term=bbcode&submit=search

Among them:
* bbcode
 * https://github.com/dcwatson/bbcode
 * https://pypi.python.org/pypi/bbcode/1.0.21
* postmarkup
 * https://code.google.com/archive/p/postmarkup/
 * https://pypi.python.org/pypi/postmarkup/1.2.2
 * https://www.willmcgugan.com/blog/tech/post/bbcode-python-module/
 * a fork: https://github.com/frol/postmarkup
* bbcodepy (the new-tag system is interesting) https://github.com/vishnevskiy/bbcodepy

**Comment by asaunier** [comment]
A blog about Markdown parsers: http://lepture.com/en/2014/markdown-parsers-in-python

Markdown parsers:
* Python-markdown:
 * https://pypi.python.org/pypi/Markdown
 * https://pythonhosted.org/Markdown/
 * extension for Github-Flavored Markdown (maybe not needed?) https://github.com/google/py-gfm
* Mistune (claims to be 4x faster than python-markdown):
 * https://github.com/lepture/mistune
 * http://mistune.readthedocs.org/en/latest/
* Sundown/Hoedown (written in C => fast!)
 * https://github.com/vmg/sundown
 * https://github.com/hoedown/hoedown
 * a python-binding: https://github.com/FSX/misaka
 * another: https://github.com/hhatto/python-hoedown

By the way a markdown parser in JS: https://github.com/chjj/marked

**Comment by gottferdom** [comment]
As we are migrating data from the previous forums, maybe we could also consider modifying the current syntax if needed (e.g. a c2c-specific syntax that can be replaced by standards).
I know it is not in the scope for c2c SA, but I would say: do not hesitate to if you feel it's better. We could then include this change in the migration.

(just a thought)

**Comment by asaunier** [comment]
@gottferdom OK. Well my concern is that doing syntax conversion during the data migration might be quite a lot of extra work. Depends also if it's easier to change/convert the syntaxes while migrating or to parse them (+ the custom tags) when generating a document page.

**Comment by gottferdom** [comment]
Yeah of course, that's the idea: what has the lowest cost: migrate data, or write custom parsers? I just wanted to express that, IMHO, feel free to choose the best alternative meeting your needs.

**Comment by asaunier** [comment]
v5 formatting syntax is REALLY complicated with many mixed syntaxes and really complicated custom tags. For instance the pitch tags (aka ``L#``): http://www.camptocamp.org/articles/305462/fr/aide-topoguide-l-balise-de-description-des-longueurs

**Comment by stef74** [comment]
Could you list all custom syntax ? ... identify if exist an alternative "standard" syntax and identitify the workload to "convert" in migration data. Le l# is a nightmare for sur ... is allready a nightmare for use it ! Can you simplify by "simple" table ? On other way to analyse is list standard syntax ... and identify the syntaxe we use ... association / dev team can be help on this subject ... I don't know if is relevant.

**Comment by asaunier** [comment]
> Could you list all custom syntax ?

Isn't it the job of the association to make such a list?

**Comment by stef74** [comment]
Probably in this case could you list syntax allready take in account
(standard syntax)

2016-02-03 15:06 GMT+01:00 Alex Saunier <notifications@github.com>:
