### ISSUE TITLE
Route ratings are not shown in the card anymore

### ISSUE THREAD

**Issue by fbunoz** [c2corg/v6_ui#1212]
https://www.camptocamp.org/waypoints/532445/fr/sierra-de-montroig

The route ratings are not shown on the routes cards. Yesterday it was shown (if I'm not wrong).
The html contains a rating, but it is not displayed : 
```
<div class="global-rating flex flexend-align margin-b-sm" ng-init="globalRatings = cardCtrl.getGlobalRatings()" ng-show="::globalRatings">
    <span class="icon-rating"></span>
    <!-- ngRepeat: (attr, val) in ::globalRatings --><!-- ngIf: ::val -->
    <div ng-repeat="(attr, val) in ::globalRatings" class="rating ng-scope" uib-tooltip="global_rating" ng-if="::val">
        <span class="value ng-binding">TD-</span>
    </div>
    <!-- end ngIf: ::val --><!-- end ngRepeat: (attr, val) in ::globalRatings -->
</div>
```

**Comment by ginold** [comment]
will be fixed in https://github.com/c2corg/v6_ui/pull/1173
I don't know why it didn't appear anymore.

**Comment by brunobesson** [comment]
@stef74 IMHO this is an important usability issue. As the fix should be pretty straightforward, could we plan this for next release?

**Comment by brunobesson** [comment]
@ginold OK, then my comment is useless, sorry.

**Comment by stef74** [comment]
@brunobesson is in prod, that is the reactivity :+1:
