### ISSUE TITLE
Incorrect public_transportation_types value for access waypoints

### ISSUE THREAD

**Issue by desnoes** [c2corg/v6_ui#1214]
In a WP with Access_type = "accès", the field "Type de transport en commun" should not contain the field "remontée mécanique"

**Comment by fbunoz** [comment]
Be careful.
Before removing this option, we must move the value to the "Remontée mécanique" boolean field.
There has been a mistake during the migration.
There are 72 WP impacted : https://www.camptocamp.org/waypoints#wtyp=access&tpty=cable_car

**Comment by asaunier** [comment]
An alembic script is required to:
* set the ``Waypoint.lift_access`` attribute to ``True`` if ``Waypoint. public_transportation_types`` contains the ``cable_car`` value
* remove value ``cable_car`` from the possible values of ``Waypoint. public_transportation_types``
