### ISSUE TITLE
WP 'Access': the field "Accès" should be renamed "Accès TC" 

### ISSUE THREAD

**Issue by desnoes** [c2corg/v6_ui#1218]
WP 'Acces': the field "Accès" should be renamed "Accès TC" (OK if we can do it in Transifex, but please check that it is not a common name used elsewhere)

**Comment by brunobesson** [comment]
@desnoes I just committed #1401 assuming the french translation for `access` field should be "Accès routier". But here you're saying it should rather be "Accès en transport en commun". What's the correct choice?

**Comment by fbunoz** [comment]
For an access WP, there are 2 text fields to describe the access : road access, an public transport access.
The V5 "road access" has been migrated in "description", and "PT access" in "access".
Be careful when you change the field name : "PT access" must be used only withe access WP.
Hut and climbing site WP use also this field, but as pedestrian access. And product WP uses it as "access" (road or pedestrian : last kilometers from the associated access or from an always accessible village).

**Comment by brunobesson** [comment]
The art of obfuscating simple things in an attempt of optimization that may be useless :wink: I'll have a look later.

**Comment by fbunoz** [comment]
I didn't say that each WP type must have its field name, but be careful with side effects :-)

**Comment by brunobesson** [comment]
@fbunoz are you sure there is an access field for huts?

**Comment by brunobesson** [comment]
@asaunier @fbunoz is the 'access' field still supposed to be available for huts? The API doesn't seem to return it.
I am working on #1401 to take into account more complicated cases:

* description field should be renamed 'road access' for waypoints
* access field may have different names depending on whether the waypoint is an access, a climbing_indoor, a climbing_outdoor, a local_product, or a *hut* (?)

I seem to handle it properly for all cases except huts: I can edit the field, but it is not returned by the API. Should I open a API issue?

(see also #942)

**Comment by fbunoz** [comment]
> I can edit the field, but it is not returned by the API. Should I open a API issue?

Yes, open an issue.
The V5 hut access fields has been migrated in V6 WP access field : https://github.com/c2corg/v6_api/blob/master/c2corg_api/scripts/migration/documents/waypoints/huts.py#L95
But the data don't appear in access field at the edition when changing WP type to product for instance.
I hope it's just an API issue and not a migration issue.

**Comment by brunobesson** [comment]
I opended c2corg/v6_api#611

**Comment by brunobesson** [comment]
I think this issue is solved, isn't it?

**Comment by desnoes** [comment]
@brunobesson : yes it is solved
