### ISSUE TITLE
IPhone iOS10.1.1: display errors

### ISSUE THREAD

**Issue by desnoes** [c2corg/v6_ui#1224]
Home page observed by a friend with its iphone 5c (iOS 10.1.1):

![img_1592](https://cloud.githubusercontent.com/assets/19892089/21227942/3b320c40-c2dc-11e6-9830-fb0f3d7ee029.PNG)

**Comment by stef74** [comment]
no issue on my side same version in iphone 5s

**Comment by desnoes** [comment]
this on a Iphone 5c

**Comment by ginold** [comment]
iphone model should not be the issue... is it on safari?

**Comment by desnoes** [comment]
i was unable to get the safari's version => i close this issue
