### ISSUE TITLE
Section folding

### ISSUE THREAD

**Issue by brunobesson** [c2corg/v6_ui#1226]
I know the subject as already been discussed before, but still, I would like to debate some more.

I don't understand the choice made to collapse some section by default. What's the interest? On desktop an tablets, it's easier and more elegant to scroll a little bit rather than clicking on the icons to expand each and every box (and some of them __are__ always read in outings and in routes - examples on demand). Even on mobile, scrolling is the usual way. The only problem could be the general information section, where some parts should be moved to the bottom (using flex layout, maybe?) but others __need__ to be open by default.

IMHO, all boxes should be open by default. And one will collapse them only for printing (thanks to @flob38). The only problem being the one described above with the general information section on mobile.

**Comment by stef74** [comment]
@brunobesson this type of question is not relevant in github ... but probably yes (my opinion is to limit scroll in mobil ...)

**Comment by brunobesson** [comment]
>this type of question is not relevant in github

Why? OK, this could be discussed in the association-specific forum too. But this is more tech oriented IMHO.

**Comment by stef74** [comment]
For me is not technical discussion is pure ergonomic ... forum or with
"ergonomic team" who manage dicussion in trello I can add you if you need

2016-12-15 16:36 GMT+01:00 Bruno Besson <notifications@github.com>:

**Comment by brunobesson** [comment]
>I can add you if you need

Nope, thanks. I'll let you defend my ideas :wink:

**Comment by brunobesson** [comment]
@stef74 @asaunier there seems to be a consensus for opening all sectiosn by default. From the coordination point of view, is this decided and approved?
I could then work on it (an easy task, AFAIK)

**Comment by asaunier** [comment]
@brunobesson I quite agree that in a desktop browser it makes more sense to open all the sections by default. It's probably not the same with a mobile (all closed by default?) but that could be improved later.
So I'm +1 for this change.

It should be quite easy to do since there is a boolean argument that indicates if the field must be open or closed: 
https://github.com/c2corg/v6_ui/blob/master/c2corg_ui/templates/helpers/view.html#L482

If we are sure all fields will always be open by default anyway, we could make more changes to remove the argument (or revert it to make "open" the default setting?).

If you'd like to take care of this, that would be really cool, thanks :)

**Comment by brunobesson** [comment]
IMHO, it should also be open by default on mobile, but as you said, we can discuss it further later. I'll propose a PR to open all sections (hoping I won't forget any :stuck_out_tongue:).
I would rather leave the helper code as is for now, until we have properly decided whether all sections will be open by default or not.
Do you agree? I plan to do it either tonight or tomorrow.

**Comment by asaunier** [comment]
Looks good to me!

By the way I don't have a strong opinion about the mobile, I have just the feeling that for a small screen it's more convenient to open the attribute only on demand, or at least the minor ones. But that makes things more complicated.

> I'll propose a PR to open all sections (hoping I won't forget any 😛).

Perhaps this list could help you:
https://github.com/c2corg/v6_ui/search?utf8=%E2%9C%93&q=get_document_locale_text
=> you need to add ``True`` as third argument of all occurences of ``get_document_locale_text``.

**Comment by brunobesson** [comment]
#1266 fixes the issue for main sections.
There is still another part that should be handled: information block on mobile. Currently it is collapsed by default, which I find as disturbing as the other fields. The only thing that is currently restraining me from opening everything is the licence section.

Any thoughts? Either we find a way to move it to the page bottom, or maybe we could make it the only part collapsed by default.

**Comment by brunobesson** [comment]
>There is still another part that should be handled: information block on mobile

#1270 handles this.

With both PRs, I think we solve this issue.
