### ISSUE TITLE
Offset search need to be multiple of 4

### ISSUE THREAD

**Issue by stef74** [c2corg/v6_ui#1229]
The layout of card permit to have 4 column in large screen ... so we need to be multiple of 4.

In this case have place for 2 additionnal card.

Idealy offset need to be a multiple of column ... but more simple simple is to set 32.

When #1187 to be done we can have possibilty to show 48 card (more than 2500px)

**Comment by stef74** [comment]
probably more API issue ... I don't know if UI manage it self the number of result

**Comment by tsauerwein** [comment]
This is the good place. The UI can pass the maximum number of results with the request.

See: https://github.com/c2corg/v6_api/blob/master/c2corg_api/views/waypoint.py#L79-L81

**Comment by stef74** [comment]
So we have to change : 
https://github.com/c2corg/v6_ui/blob/8c3dce09a3d9bb6543ceeb50215d1f1829ee59c5/c2corg_ui/views/document.py#L48

and also this one : https://github.com/c2corg/v6_ui/blob/ce2996f9c5b3c1314f02f9f66b92aa1e9745b213/c2corg_ui/static/js/search/pagination.js#L66 ????
