### ISSUE TITLE
Outing: wrong title after selection of another oute

### ISSUE THREAD

**Issue by desnoes** [c2corg/v6_ui#1234]
I have created an outing based on an incorrect route (Charmant Som : Face E). Then i modified the route (Charmant Som : par la Balme de l'Air) and the title is not changed. cf. https://www.camptocamp.org/outings/832757/fr/charmant-som-face-e-dalles-inferieures
I have checked with another outing and observed the same problem.

**Comment by fbunoz** [comment]
As on V5, the outing title isn't linked to the route tiltle : by default, it's the route title, but you can change the outing title as you want.
I changed the title of your outing.
