### ISSUE TITLE
Color contrast (forum): citation in a message

### ISSUE THREAD

**Issue by desnoes** [c2corg/v6_ui#1236]
Feedback from a daltonian: it is difficult to distinguish between the background of the message and the citation. The 2 colors (withe and grey) are too close in the color spectrum. More constrast color is required.
![contrast forum](https://cloud.githubusercontent.com/assets/19892089/21308323/c1b0e62e-c5d9-11e6-908c-7cdc8b45f6dc.jpg)

**Comment by desnoes** [comment]
I created this issue in the wrong repository (v6_ui instead of v6_forum). Is it possible to move it to the correct place or i have to close this issue and create it again in v6_forum?

**Comment by stef74** [comment]
Sorry we havé to close and recreate. You can directly assign to bubu
