### ISSUE TITLE
Orientation selection with rosette

### ISSUE THREAD

**Issue by desnoes** [c2corg/v6_ui#1237]
When i select NE and NW, 90% of the time i would like to select the complete area from NE to NW and thus include the N. It would be great to select automatically N.
More generally, an orientation should be automatically seletected if its two neighbors have been selected.

**Comment by asaunier** [comment]
> When i select NE and NW, 90% of the time i would like to select the complete area from NE to NW and thus include the N.

But then it will not be possible to manage the 10 other %...
And how do you know it should not be NE to NW via S instead?

We create potential problem and add some work just to save a few clicks from time to time. Are you sure it's really worth the cost?

**Comment by desnoes** [comment]
For the 10% you have to click on the orientation you want to remove. 
However, this does not solve the problem, since you have to be aware of 
that. I close the issue.
