### ISSUE TITLE
Equipment quality field in climbing site waypoint

### ISSUE THREAD

**Issue by brunobesson** [c2corg/v6_ui#1239]
Equipment value is quoted `['P1']`. I assume the corresponding i18n key should be displayed instead.

![toto](https://cloud.githubusercontent.com/assets/2234024/21319883/44be5760-c60f-11e6-864b-6472263c8e2e.png)

**Comment by desnoes** [comment]
this bug is already reported in #1075

**Comment by brunobesson** [comment]
Argh! I thought I had followed the issues created properly recently so I didn't check for existing tickets. I apologize to everyone...
