### ISSUE TITLE
Connexion : Tor Browser 6.0.8 (based on Firefox 45.6.0)

### ISSUE THREAD

**Issue by desnoes** [c2corg/v6_ui#1247]
Report from a contributor using Tor Browser.

https://forum.camptocamp.org/t/impossible-de-creer-une-sortie/174746/9?u=miko

He is connected. He received the followings error messages:
- i want to consult my profile: "La récupération des données du fil a échoué : no permission to see the feed : Forbidden"
- i want to modify the account's parameters : "Récupération des données du compte impossible :
Unauthorized: UserAccountRest.get__GET failed permission check : Forbidden"
- i want to modify my preferences: "La récupération des préférences a échoué : Unauthorized: UserFilterPreferencesRest.get__GET failed permission check : Forbidden"
- i want to modify my list of  friends: "La récupération de la liste suivie a échoué : Unauthorized: UserFollowingRest.get__GET failed permission check : Forbidden"
- i want to modify the list of avanche forecast reports: "La récupération des bulletins auxquels vous êtes abonné a échoué : Unauthorized: UserMailinglistsRest.get__GET failed permission check : Forbidden"

**Comment by stef74** [comment]
Clearly not a priority

**Comment by brunobesson** [comment]
He was blocking third party cookies with the browser. Issue is fixed!
