### ISSUE TITLE
Maps : background layer selector

### ISSUE THREAD

**Issue by asaunier** [c2corg/v6_ui#125]
Here are a few examples in ngeo:
http://camptocamp.github.io/ngeo/master/examples/backgroundlayer.html
http://camptocamp.github.io/ngeo/master/examples/backgroundlayerdropdown.html

I have also noticed some work has been done in GMF. For instance:
http://adube.github.io/ngeo/gmf-background-selector-mobile/examples/contribs/gmf/mobilebackgroundlayerselector.html
http://adube.github.io/ngeo/gmf-background-selector-mobile/examples/contribs/gmf/apps/mobile/index.html
even though the example above might be a little overkill => we need a simple way to switch among background layers by clicking on an icon or a dropdown on the map.

@tsauerwein I have noticed you have worked in GMF mobile background selector, what do you recommend?

Related to https://github.com/c2corg/v6_ui/issues/67

**Comment by tsauerwein** [comment]
The ngeo can be of use. To we have more detailed specifications on how the background-selector and the layer selector should look like?

**Comment by asaunier** [comment]
Not really. I think that having a background selector dropdown (only one background at a time, no need to handle opacity) is OK. Please note that when changing the background layer we may have to update the map projection (for instance if using the swisstopo WMTS).

Not much instructions about the layer selector either. We don't really need a tree (?) and have not that many layers to display: the geographical document types such as WP (not sure if we need to be able to show WP types separately), routes, outings, images, areas, users, accidents, etc. + some extra layers such as the ">30° slopes" layer http://www.camptocamp.org/map?map_x=737760.64227729&map_y=5740502.0377603&map_zoom=14&tree_layers=slopes
