### ISSUE TITLE
Transifex variable to add

### ISSUE THREAD

**Issue by loicperrin** [c2corg/v6_ui#1254]
- [x] In the WP page: in the card of associated articles, the category does not use the Transifex variable. See https://www.camptocamp.org/waypoints/104291/fr/col-du-lautaret : "soft_mobility" is displayed, where as it is translated in Transifex

**Comment by asaunier** [comment]
> In the WP page: in the card of associated articles, the category does not use the Transifex variable. See https://www.camptocamp.org/waypoints/104291/fr/col-du-lautaret : "soft_mobility" is displayed, where as it is translated in Transifex

Ditto for the article type (collaborative or personal). They should actually be translated:
https://github.com/c2corg/v6_ui/blob/master/c2corg_ui/static/partials/cards/articles.html#L9-L13
https://github.com/c2corg/v6_ui/blob/master/c2corg_ui/templates/i18n.html#L182

But it's probably related to a translation issue sometimes observed with the other cards content (eg. activity tooltips): https://github.com/c2corg/v6_ui/issues/1145
By the way it seems a fix has been pushed for the latter issue and will soon be available in prod.
Actually it seems the problem above is also fixed on the demo: https://www.demov6.camptocamp.org/waypoints/104291/fr/col-du-lautaret

**Comment by desnoes** [comment]
fixed on demo
