### ISSUE TITLE
Slider not usable

### ISSUE THREAD

**Issue by stef74** [c2corg/v6_ui#1256]
On iPhone 5s/ Safari slider are not usable ... if i try to click on IT ... it sélect the slider

**Comment by stef74** [comment]
![img_0894](https://cloud.githubusercontent.com/assets/3962997/21434542/5e6b9606-c875-11e6-9db5-ec26630ed24a.PNG)

**Comment by ginold** [comment]
It happens when you tap and hold in order to move the handle? that is probably the default browser behavior, to select text around... we should preventDefault() or `-webkit-user-select: none;.`

**Comment by desnoes** [comment]
I have the same problem with a Galaxy J5 (with Chrome and Android 6.0.1)
see #1179

**Comment by dkocich** [comment]
Slider is working fine with a Huawei P8 Lite (Chrome/Opera and Android 6.0)

**Comment by dkocich** [comment]
I cannot reproduce this problem on any iOS device (with Safari/Chrome) using Browserstack or with my Android. @stef74 @desnoes can you please tell me if you still experience this issue or is it ok already? Thanks!

**Comment by desnoes** [comment]
i confirm i still experience the issue. The left bound is ok, but i cannot select/displace the bound on the right. The only possibility it is to click on the bar, then the right bound is moving to the left. Then i am able to select and displace it.

**Comment by asaunier** [comment]
I have tested en emulated version of iOS 10 (iphone 7) and had no special problem.
I have also tested on my Android phone using a recent Chrome, it also works even though not very fluid (my phone is old) and with the horizontal panning issue described at https://github.com/c2corg/v6_ui/issues/1622

**Comment by stef74** [comment]
I have retested, it's better but not very efficient at all. But I propose to close. Emulator for this kind of problem is not very representative.
