### ISSUE TITLE
Filter: resetting range slider issue

### ISSUE THREAD

**Issue by brunobesson** [c2corg/v6_ui#1257]
This issue was maybe partially described in #1179, but it was no the main problem described (which focused mainly on usability .

Here is the thing: when using a range slider, the reset applied (e.g. when clicking on reset filters) is only partial: the range values are correctly reset, but the slider feedback remains where it was selected before. When interacting again and changing any value, behaviour is correct again.

First: selecting a range
![snapshot1](https://cloud.githubusercontent.com/assets/2234024/21438524/cd4a478e-c889-11e6-8928-a977d830a291.png)

Second, resetting filter: only values are updated
![snapshot2](https://cloud.githubusercontent.com/assets/2234024/21438525/cd4d5d52-c889-11e6-9c6c-e1c92586ae3f.png)

Third, chnange upper boud again: values are updated according to new slider positions.
![snapshot3](https://cloud.githubusercontent.com/assets/2234024/21438526/cd4fe4fa-c889-11e6-863b-75ee19d1fe6f.png)

This applies at least to both conditions slider for outings and elevation for routes.

**Comment by asaunier** [comment]
> Second, resetting filter: only values are updated

It's a know issue: see first point of https://github.com/c2corg/v6_ui/issues/655
Unfortunately I have not been able to find a solution yet.

**Comment by brunobesson** [comment]
OK, closing it as duplicate.
