### ISSUE TITLE
Why different colors for homepage toolbar and other pages actions

### ISSUE THREAD

**Issue by brunobesson** [c2corg/v6_ui#1260]
On mobile, both the homepage toolbar and the other pages action bars are placed on the bottom:
![snapshot8](https://cloud.githubusercontent.com/assets/2234024/21440589/ff0b629e-c893-11e6-93f9-05079ef25812.png)
![snapshot9](https://cloud.githubusercontent.com/assets/2234024/21440588/ff09bed0-c893-11e6-9e04-d2e518a7970f.png)

Appart from the text, why are they not using the same colors? Is it intended that the home page toolbar has lighter colors?

**Comment by stef74** [comment]
For personnal filter activated or not color change ... so it s normale. The color on HomePage permit to increase visibility ?

**Comment by brunobesson** [comment]
I didn't understand a word of what you wrote :wink:

**Comment by stef74** [comment]
For personnal Feed activated or not : you have two options ( activated or not) two color is consistant. For préférence use grey as other ... but if you use à color on Feed is more visible

**Comment by brunobesson** [comment]
OK now I understand. I'm not focusing on the buttons, but on the toolbar background.

**Comment by stef74** [comment]
Ok ... probably use the more contrasted
