### ISSUE TITLE
When unsetting main waypoint, route title in form isn't cleared

### ISSUE THREAD

**Issue by brunobesson** [c2corg/v6_ui#1265]
Related to #1221 and #1165 

When editing a route that already has a main point, unsetting it doesn't reset first input field, although save is OK.
E.g. 
![certif1](https://cloud.githubusercontent.com/assets/2234024/21455601/e3018324-c921-11e6-96c4-d2c4bfad6261.png)

**Comment by desnoes** [comment]
This bug seems to be fixed in the demo.
@brunobesson: could you test to confirm ?

**Comment by brunobesson** [comment]
No, I don't observe any change: clicking `unset from main waypoint` wont update top field.

**Comment by desnoes** [comment]
did you try on the demo ?

----- Mail original -----
De: "Bruno Besson" <notifications@github.com>
À: "c2corg/v6_ui" <v6_ui@noreply.github.com>
Cc: "desnoes" <mathieu.desnoes@free.fr>, "Comment" <comment@noreply.github.com>
Envoyé: Jeudi 12 Janvier 2017 10:48:39
Objet: Re: [c2corg/v6_ui] When unsetting main point, route title in form isn't cleared (#1265)



No, I don't observe any change: clicking unset from main waypoint wont update top field.

**Comment by brunobesson** [comment]
Of course.

**Comment by brunobesson** [comment]
Note that there is the same behaviour if the main waypoint is deleted.

**Comment by desnoes** [comment]
Sorry, you are right. It is possible to unset all WP, which should not be allowed

**Comment by asaunier** [comment]
>  It is possible to unset all WP, which should not be allowed

Are you sure it is not allowed?
It is not allowed/possible to dissociate all WP from a route but I think it is allowed/possible to have no main waypoint for a route (eg. a raid).

**Comment by brunobesson** [comment]
>Sorry, you are right. It is possible to unset all WP, which should not be allowed

As @asaunier mentioned, it is allowed. But it has nothing to do with what I am describing.
To repoduce:

* go to http://www.demov6.camptocamp.org/routes/46799/fr/wetterhorn-par-le-rosenlauigletscher
* edit
* click on unset main waypoint > is the text field above cleared appropriately?

Do the same but instead of unsetting main point, remove it > what's happening?

**Comment by asaunier** [comment]
The main waypoint text input is correctly updated when clicking on "Set as main waypoint" of another WP card, done here:
https://github.com/c2corg/v6_ui/blob/435ced5f68b88c019ce45727b3af43193b20898c/c2corg_ui/templates/helpers/edit.html#L16

but indeed it is not refreshed when clicking on "Unset as main waypoint", it seems something like ``${model}.main_waypoint_title = '';`` is missing at
https://github.com/c2corg/v6_ui/blob/435ced5f68b88c019ce45727b3af43193b20898c/c2corg_ui/templates/helpers/edit.html#L21
