### ISSUE TITLE
Image upload: copyright should be allowed only for moderators

### ISSUE THREAD

**Issue by loicperrin** [c2corg/v6_ui#1272]
When uploading an image (with an account which have no moderators right), I can select "copyright" for its type. This type should be allowed only for moderators.

**Comment by asaunier** [comment]
In addition I think "copyright" is only allowed for books (covers).

Perhaps the list of image types should be filtered here: https://github.com/c2corg/v6_ui/blob/master/c2corg_ui/static/partials/imageuploader.html#L78

**Comment by celinestern** [comment]
Ok, "copyright" choice is not present for "simple" member.
