### ISSUE TITLE
Distorted images in slideshow

### ISSUE THREAD

**Issue by Rupicapra-rupicapra** [c2corg/v6_ui#1274]
Hello there,
When viewing image in the lightbox/preview (eg. viewing image from outing, user profile…), its size is changed to fit in the screen, but without keeping ratio. It's more obvious with portrait images, or when resizing window.

Config (if it may help): Firefox ESR 45.5.0 on Debian 8.

**Comment by brunobesson** [comment]
I observed some problems on mobile when switching from portrait to landscape and reverse. But not on desktop... Could you post a screenshot?

**Comment by Rupicapra-rupicapra** [comment]
Sure,
![Resizing](http://montagnisme.fr/static/Resized_image.png)

**Comment by brunobesson** [comment]
Have you resized the window after having open the slideshow? 
Otherwise, I fear the problem only occurs on this quite old version of Firefox... You are the first one to raise such an issue. I can check later with racing conditions such as your screenshot.

**Comment by Rupicapra-rupicapra** [comment]
The first time I noticed this, no. I started resizing the window to make some tests and the screenshots.
I’ll test this tomorrow on a more recent version of Firefox, and I'll give you more details.

**Comment by Rupicapra-rupicapra** [comment]
Well, I do not have this behavior with Firefox 50.1.0 on Windows 10.

**Comment by stef74** [comment]
Ok so we can close ?

**Comment by Rupicapra-rupicapra** [comment]
I think so. I close this issue.

**Comment by asaunier** [comment]
There are quite a lot of feedbacks about distorted images. Is it really related to the (old) version of the browsers? This problem has recently been reported on a brand new PC using Windows 10 + Edge.

Could it be related to missing height/width?
Do we have steps to reproduce the problem?
