### ISSUE TITLE
Add pagination buttons at the bottom of advanced search results

### ISSUE THREAD

**Issue by asaunier** [c2corg/v6_ui#1275]
Else the user has to go back to the top of the page to go to the next page.

**Comment by stef74** [comment]
It is simply to change pagination offset to 32 ? Because is a multiple of 4 ...

**Comment by asaunier** [comment]
> It is simply to change pagination offset to 32 ? Because is a multiple of 4 ...

This has no connection with the issue fixed by this PR :)
In addition I don't see the point of having 32 results. Depending on the number of columns, you might have a different number of cards in each column anyway. But is it really a problem?

**Comment by desnoes** [comment]
Works fine on demo
