### ISSUE TITLE
Image association tool

### ISSUE THREAD

**Issue by loicperrin** [c2corg/v6_ui#1283]
There are several problems with image association tool:
- [ ] It is not possible to associate an outing from the detailed view of an image, where as it is possible to associate WP of routes. This should be discussed: maybe it is dangerous to let users associate documents from this page, as there is no "save" button and only moderators can desassociate
- [x] When editing the image, after selecting the outing to associate, the card does not appear. But the association is OK when saving the image.

**Comment by fjacon** [comment]
@stef74 for first point : is there anything to do ? 
Does not look like a bug.

**Comment by stef74** [comment]
@desnoes you opinion ?

**Comment by desnoes** [comment]
I recommend to skip the first point.

**Comment by stef74** [comment]
So I close
