### ISSUE TITLE
Incorrect WP longitude validation

### ISSUE THREAD

**Issue by asaunier** [c2corg/v6_ui#1286]
The WP editing form validates the longitude only between -90 and 90° instead of -180 an 180°:
https://github.com/c2corg/v6_ui/blob/master/c2corg_ui/templates/waypoint/edit.html#L178

<img width="387" alt="capture d ecran 2016-12-30 a 10 22 18" src="https://cloud.githubusercontent.com/assets/1192331/21562669/f62d553c-ce7a-11e6-869e-5b5658f104d0.png">

**Comment by desnoes** [comment]
Fixed on demo
