### ISSUE TITLE
Bad parsing of url bbcode tag

### ISSUE THREAD

**Issue by fbunoz** [c2corg/v6_ui#1291]
If we put an url bbcode tag on a text, and if the url contains '&', the '&' are transformed to &.amp;
```[url=https://www.camptocamp.org/routes#act=rock_climbing&crtyp=single]texte[/url]```
Ex: https://www.demov6.camptocamp.org/routes/828297/fr/test-iti-avc-wp-principal

**Comment by fbunoz** [comment]
The bad url seems to be decoded correctly by some browsers : https://www.camptocamp.org/routes#act=rock_climbing&amp;crtyp=single
It is not critical.

**Comment by tsauerwein** [comment]
Should be fixed with https://github.com/c2corg/v6_ui/pull/1656. Could you try, @fbunoz?

**Comment by brunobesson** [comment]
The issue if fixed when in bbcode tags. But the default link detection misses it.
