### ISSUE TITLE
Edit page : conflict between map and modal box

### ISSUE THREAD

**Issue by fbunoz** [c2corg/v6_ui#1293]
On the edit page of a WP, route or outing, when we click on the "Center on my position" button on the map, it open the summary modal box (with quality choice, save button, etc).

**Comment by brunobesson** [comment]
I assume this is because the action would like to rewrite the location (adding coordinates) and thus submits the form?

**Comment by asaunier** [comment]
> when we click on the "Center on my position" button on the map, it open the summary modal box

Same behaviour when pressing the ENTER key in a text input (except textareas) as described in the (probably related) issue https://github.com/c2corg/v6_ui/issues/1528 : 
* the map is recentered on the user's current position (as if the "center on my position" button was clicked)
* the quality modal box is shown

**Comment by asaunier** [comment]
See #1743 for investigations
