### ISSUE TITLE
List of best months to practice climbing is not sorted correctly

### ISSUE THREAD

**Issue by TotoXe** [c2corg/v6_ui#1294]
While updating climbing sites [Notre-Dame du Cros](https://www.camptocamp.org/waypoints/688819/fr/notre-dame-du-cros-secteur-gendarme), I noticed the list of best months to practice climbing is sorted  likely in the order the months have been selected. 
This is not a bug since months are listed but it is clearly... not clear !

List must be sorted logically ie in the ascending order taking into account numbers associated to months.
A priori, only the way points of type climbing site use these data.

![image](https://cloud.githubusercontent.com/assets/5667732/21622571/757d2df4-d1fe-11e6-9126-4dbefdb86e25.png)

**Comment by stef74** [comment]
@TotoXe it's regression of v5 or not ? if yes ... add bug label

**Comment by TotoXe** [comment]
Cannot access to v5. I think it is a regression.

**Comment by brunobesson** [comment]
@asaunier couldn't the list of periods be sorted already from the API side?

**Comment by asaunier** [comment]
This is an API issue, not a UI one. The UI shows what it receives from the API:
<img width="173" alt="capture d ecran 2017-01-15 a 20 11 55" src="https://cloud.githubusercontent.com/assets/1192331/21965378/f8853f8e-db5e-11e6-856a-e50988c905c8.png">

**Comment by brunobesson** [comment]
I opened c2corg/v6_api#603

@asaunier I let you close this issue if appropriate
