### ISSUE TITLE
Associating books from route edition page

### ISSUE THREAD

**Issue by brunobesson** [c2corg/v6_ui#1298]
When editing or creating a route, the association tool deosn't return book results, whereas it does in the view page.
Associating books to a route is a common task, which currently needs to be done after edition.

What do you think about adding book results when editing?

**Comment by brunobesson** [comment]
Do you propose I make a PR for this?

**Comment by brunobesson** [comment]
>In the detail view, we have dataset="wrcb"

Thus, we should allow articles, too. Isn't it?

**Comment by asaunier** [comment]
> Thus, we should allow articles, too. Isn't it?

I guess so.

> Do you propose I make a PR for this?

As you want. Not sure the change I suggest is enough but since it is an easy change, it's worth trying.

**Comment by brunobesson** [comment]
I think I misused the tags here and it went undersea. The PR for this issue has been merged, and the code went in production some time ago. Closing.
