### ISSUE TITLE
Distances for mountainbiking are displayed in meters instead of kilometers

### ISSUE THREAD

**Issue by asaunier** [c2corg/v6_ui#1300]
In the detail view:

![capture du 2017-01-04 18-48-55](https://cloud.githubusercontent.com/assets/1192331/21652804/990c1ab8-d2ae-11e6-8c92-59d847baaa61.png)

In the editing form:

![sans titre](https://cloud.githubusercontent.com/assets/1192331/21652815/a0c39416-d2ae-11e6-8a88-efc8d2a9c0a9.png)

**Comment by desnoes** [comment]
edition form: distance is given in meters (to remain consistent with data already in the DB)
display: distance is given in km

**Comment by asaunier** [comment]
OK thanks, so no change then? I think it's already how it works in prod.

**Comment by asaunier** [comment]
PR #1301 has been updated.

**Comment by desnoes** [comment]
it has been fixed on demo
