### ISSUE TITLE
Singular/plural for search filter labels

### ISSUE THREAD

**Issue by dkocich** [c2corg/v6_ui#1302]
"Durations" filter shows "days" when the filter is set only to 1 "day". The same problem is with other languages also (ein Tag/ zwei Tage, ...) 

![image](https://cloud.githubusercontent.com/assets/6165660/21654014/09c8071c-d2b4-11e6-83dc-6a0b7185bc9a.png)

**Comment by tsauerwein** [comment]
See https://angular-gettext.rocketeer.be/dev-guide/annotate/#plurals
