### ISSUE TITLE
Add more column in card list when screen are large

### ISSUE THREAD

**Issue by stef74** [c2corg/v6_ui#1304]
Due to the hiding map, we can easly had one or two column for large screen. I have tested on mys side and the rederendering is better (iwth only 4th column card are too wide).

Probably need to had more than 30 results but it's an other point.

I try to do The PR by myself

**Comment by brunobesson** [comment]
Working, although break points are not optimal IMHO. I wonder if there isn't a problem with the media query used: it applies the same layout with or without the map. Thus, it may be OK without the map, but not when map is shown. @stef74 have you taken this into account?

**Comment by stef74** [comment]
I have observed that when map is hidden the number of column is increasing. So I not challenge more than that ... but I have found is strange that is work as well based only on size of screen. 
We can do a media query on more precise element ?

**Comment by brunobesson** [comment]
>We can do a media query on more precise element ?

Nope.

**Comment by stef74** [comment]
I idea to test the fact map is hidden or not in CSS

**Comment by brunobesson** [comment]
It is not the right way to do it. Instead, there are flex properties that should be able to solve this (so I think, at least, using shrink and grow properties, in addition to max-width, or smth similar). It should be investigated this way.

**Comment by stef74** [comment]
An other way is to use class no-map ... but I think I have the solution. 
flex-basis:-moz-min-content and min-width:250px ... tested on my firefox it's seem to work

I have check the support of this properties

**Comment by stef74** [comment]
https://developer.mozilla.org/fr/docs/Web/CSS/flex-basis#Compatibilité_des_navigateurs

flex based on content not supported by safarari ... with special properties for firefox. I'm not sure is a good idea to implement it. 

I have found an other similar and tested on browser (not on my vm) with fixed width (it's not so bad) with sucess ... in many size and with(out) map. 
flex-basis:  auto;
width:300 px;

We can after remove media query based on flex basis.

**Comment by stef74** [comment]
We can close
