### ISSUE TITLE
Icon Size reduction

### ISSUE THREAD

**Issue by stef74** [c2corg/v6_ui#1309]
Some people have complaint on size

- [x] Activity icon in creation/edition
- [x] snow infos & activities icon 
- [ ] map icon

**Comment by stef74** [comment]
#1308

**Comment by stef74** [comment]
I try to reduce size of icon on map ... but I not found here is it "examine" feature in browser is not able to localize correctly the CSS line concerned.

**Comment by tsauerwein** [comment]
> I try to reduce size of icon on map ...

See https://github.com/c2corg/v6_ui/blob/master/c2corg_ui/static/js/map/map.js#L440

**Comment by stef74** [comment]
I have try to do something ... but I probably not understanding how it's work

**Comment by desnoes** [comment]
@stef74: please check, i seems ok for me

**Comment by stef74** [comment]
Ok for me ... we can also close issue related to avalanch sign
