### ISSUE TITLE
Image weight optimization

### ISSUE THREAD

**Issue by fbunoz** [c2corg/v6_ui#1311]
I uploaded a photo : 912 x 1216 px and 528 518 bytes.
The most of my images have this size (or 1216 x 912 px), because it correspond to 1/3 of the full size of my APN. I prefer reduce the size with an integer ratio to optimize the noise reduction.
I reduce the size to ~1200px and 4-500ko to limit the weigth of the images on the c2c server. I use a bigger size (weigth : ~1Mo) only for very beautiful photos or reusable photos to add route track.

But the result is : 

- The original photo, with the same size and weight as the uploaded photo : https://media.camptocamp.org/c2corg_active/1483653583_50441338.jpg
- The BI photo, with the same size as original size (because original < 1500px), but with a higher weight : 547 971 bytes !
https://media.camptocamp.org/c2corg_active/1483653583_50441338BI.jpg

It means that the original photo has been resized (without change the size) to generate the BI photo, although it was not necessary. And the resizing has increased the weight !
On the V5, when the original size was smaller than BI max size, the photo was not resized for BI, and on the disk a simple unix link was created to the original photo. The disk space was saved.
On the V6, we lost 535 kB.

If we can't use unix link for BI, it would better to generate a BI image lighter than the original.

**Comment by asaunier** [comment]
This issue should be moved to https://github.com/c2corg/v6_images/issues

**Comment by fbunoz** [comment]
Moved to https://github.com/c2corg/v6_images/issues/33
