### ISSUE TITLE
Toggle map and list on mobile

### ISSUE THREAD

**Issue by brunobesson** [c2corg/v6_ui#1312]
In response to #1187, #1208 introduced new buttons to hide the map or the results.
This is not working properly on mobile layout (and there is already a button to toggle between results and map).

@ginold @asaunier could adding class `hidden-xs` to the new buttons be enough to solve this?

**Comment by desnoes** [comment]
When i click on the map button, nothing happens (Galaxy j5 with Chrome).

**Comment by stef74** [comment]
same on safari

**Comment by brunobesson** [comment]
@stef74 @desnoes I don't understand your comments. What needs to be tested here is that the buttons for full size map or list are not visible on mobile (which is working for me).

Are you referring to the small world button that is used, on mobile, to switch between the results and the map ? (Again, this is working for me on chrome)

**Comment by AlexisDemongeot** [comment]
The small world button is working to see or hide the map. On Galaxy S3, Android Nougat and Chrome. This button is working on the production site and the demo site. 

Hiding list is not working on the production site. It appears to leave on a blank page.

I'll test it on the stock android 7 navigator and windows phone as soon I have the code to go on the demo site (I've forgot them).

**Comment by desnoes** [comment]
> What needs to be tested here is that the buttons for full size map or list are not visible on mobile (which is working for me).
You are right, the button for hidding list is not visible anymore.
But the map is always hidden even when i click on the button.
Chrome version 51.0.2704.81
Android: 6.0.1

**Comment by brunobesson** [comment]
@desnoes @AlexisDemongeot @stef74 There seem to be a lot of confusion here.

On mobile, the switch is done through the "world" button, and you both seem to say it is working. This is working for me, but maybe not for you. If so, could you open an issue? (but I don't think anything changed concerning this since previous release).

On tablet and desktop, do the buttons work? It works for me. Open an issue if not, but again, I don't think anything changed since.

As for the buttons to widen/hide results and map, you all agree they are hidden on mobile. So *this* issue is fixed.
