### ISSUE TITLE
The "badge/first quote" feature leads to missing page

### ISSUE THREAD

**Issue by LaurentBonnaud** [c2corg/v6_ui#1319]
On this page:

  https://forum.camptocamp.org/users/laurentb2/notifications

I have a link named "Vous avez gagné First Quote" that points to this URL:

  https://forum.camptocamp.org/badges/15/first-quote?username=laurentb2

but the page displays:
```
:(
Page introuvable
lors d'une tentative de chargement /badges/15
Oups, l'application a essayé de charger une URL qui n'existe pas. 
```

**Comment by brunobesson** [comment]
This is a known bug that only affects already registered users (pre v6) while they are not active on the forum. It disappears quickly after, so we decided not to deal with it. 
Thanks for the report though.
