### ISSUE TITLE
Do not display virtual WP on the map of an associated route

### ISSUE THREAD

**Issue by fbunoz** [c2corg/v6_ui#1321]
On the page of a route associated to a WP whose type = virtual, the virtual WP must not be displayed on the map.
Example where a virtual WP clutters the map without adding an information : https://www.camptocamp.org/routes/418850/fr/grand-tour-du-pic-d-asti-par-la-pointe-joanne-le-col-agnel-et-le-pic-segure

**Comment by desnoes** [comment]
fixed on demo (FF)
