### ISSUE TITLE
search xreports

### ISSUE THREAD

**Issue by desnoes** [c2corg/v6_ui#1324]
Errors in the adavnced search:
- 'supérieur à 3 m' should be replace by 'supérieur à 3 mois': it seems the transiflex variable is 'more_than_3m' which is not the correct one.
- '25' should be replaced by 'supérieur à 25' (to be validated) 

![xreprts](https://cloud.githubusercontent.com/assets/19892089/21759077/b251953e-d641-11e6-82f5-2bd3342d12ec.jpg)

**Comment by desnoes** [comment]
@mgerbaux: could you check the advanced search for xreports ?

**Comment by mgerbaux** [comment]
> could you check the advanced search for xreports ?
No more remark than desnoes' one

**Comment by desnoes** [comment]
@mgerbaux : what about the '25'? isn't it 'more than 25' ?

**Comment by mgerbaux** [comment]
>what about the '25'? isn't it 'more than 25' ?

Probably…
It should be coherent with the values in the edition form, but I do not know what it looks ike in V6…

**Comment by dkocich** [comment]
@desnoes what is the problem with more_than_3m? The string code should be fine (any translations have to be changed in Transifex). https://github.com/c2corg/v6_common/blob/1e3fe0991ecc8acbb0d9234f96eb71413089aa7f/c2corg_common/attributes.py#L725
When I checked some time ago the majority of data is between 0-5 with max around 10 I think so I set filter to 0-25. Right now it returns 0-25 and not more (it can be changed later).

**Comment by desnoes** [comment]
@dkocich: this is a translation error in transifex. In the past we had some problem with transifex variables used in different context and leading to translation errors. It was my concern. I made the modification in transifex.
Concerning the string '25', we must cross-checked with the edition form of xreports. For the time being, i don't think this is a real problem.

**Comment by desnoes** [comment]
@mgerbaux: do you agree to close the issue ?

**Comment by mgerbaux** [comment]
> @mgerbaux: do you agree to close the issue ?
OK, it seems to left only translatuion improvement
