### ISSUE TITLE
Replace buttons with links when possible

### ISSUE THREAD

**Issue by brunobesson** [c2corg/v6_ui#1326]
Currently, many buttons are used were links should be instead. This causes usablity problems, because one cannot open the link in a new tab or window. When possible, we should use `<a>` tags instead.

Here, I try to list were changes could be made. Do not hesitate to add other items.

* [ ] add new outing button in feed<sup>1</sup>
* [ ] add new outing button in route page, within outings section<sup>1</sup>
* [x] view more results in route or waypoint page, within outings section
* [x] view more results in route page, within routes section
* [ ] add new route to waypoint, within routes section<sup>1</sup>
* [ ] cards in edit pages, i.e. associated entities<sup>2</sup>
* [ ] results in maps (see #1159)
* [ ] comments section
* [ ] edit button

<sup>1</sup> These buttons use the `protected-url-btn` directive which redirects to login page instead if not already logged in. Can this be adapted to work with links?

<sup>2</sup> Here, there seem to be instructions not to enable it (https://github.com/c2corg/v6_ui/blob/master/c2corg_ui/static/js/card.js#L167), but why?

**Comment by mgerbaux** [comment]
>2 Here, there seem to be instructions not to enable it (https://github.com/c2corg/v6_ui/blob/master/c2corg_ui/static/js/card.js#L167), but why?

That would be great if we could progress on this issue  : make the cards clickable on edit forms would  improve for sure the entry of outings
