### ISSUE TITLE
AssertionErrors when running the UI unit tests

### ISSUE THREAD

**Issue by asaunier** [c2corg/v6_ui#1337]
Since a couple of weeks, when running ``make check`` in the UI, the tests seem to pass but many ``AssertionErrors`` are output in the console:

```
.....Exception ignored in: <bound method IteratorWrapper.__del__ of <webtest.lint.IteratorWrapper object at 0x7fa80422e780>>
Traceback (most recent call last):
  File "/home/alex/Desktop/v6_ui/.build/venv/lib/python3.5/site-packages/webtest/lint.py", line 312, in __del__
    "Iterator garbage collected without being closed")
AssertionError: Iterator garbage collected without being closed
.
----------------------------------------------------------------------
Ran 62 tests in 10.737s
```

**Comment by dkocich** [comment]
I also see it. It was probably made by the latest "webtest" change a few weeks back ([2016-12-16](https://webtest.readthedocs.io/en/latest/changelog.html#id1)).
Probably similar to issue https://github.com/Pylons/webtest/issues/168 ?

**Comment by asaunier** [comment]
Release 1.7.1 of WebTest is out as of today. I don't know if it the upgrade is made automatically by some of our dependencies but I no longer observe the problem when running the tests either in my local instance or  on the dev server.

@dkocich is OK with yours?

If yes, I suggest to close the issue.

**Comment by dkocich** [comment]
@asaunier my tests are ok now. They reported fix after latest update in the discussion I linked. Closing now.
