### ISSUE TITLE
Page titles remain angular tags

### ISSUE THREAD

**Issue by ginold** [c2corg/v6_ui#134]
I don't know how it works on your computers guys, but on mine and on my smartphone the pages from the demo c2c.org added to the history or favorites will display a page's title not like "Waypoints" but {{waypoints | translate}}, not "Welcome" but {{welcome | translate}}. 
This looks awful. 
![screenshot from 2016-02-03 09 19 33](https://cloud.githubusercontent.com/assets/7814311/12776566/458f14cc-ca57-11e5-92cc-6b1c1f8acb27.png)

**Comment by asaunier** [comment]
OK, thanks for noticing. It's indeed a problem.
Perhaps we'll have to use ``ng-bind`` instead of a "bracket" expression as hinted here: https://github.com/c2corg/v6_ui/pull/113#issuecomment-175139492

**Comment by asaunier** [comment]
Fix by https://github.com/c2corg/v6_ui/pull/138
