### ISSUE TITLE
Images uploader should upload images sequentially

### ISSUE THREAD

**Issue by asaunier** [c2corg/v6_ui#1340]
Forked from https://github.com/c2corg/v6_ui/issues/929#issuecomment-269907514

A problem with the image uploader is that **it tries to upload all submitted images at the same time**. Which is a non-sense: if too many images are uploaded at the same time, the bandwidth might be not enough to send all of them in a reasonable amount of time, thus causing timeout errors.

**It would make more sense that only 1 or 2 images are uploaded at the same time and that the uploader starts uploading additional images when the latter uploads are done.**

By the way I have realized that when many images are uploaded in the same batch, the API request to save the associated data (not the files!) takes a while... Perhaps there are things to optimize in the API to reduce the delay needed to save those data?

**Comment by tsauerwein** [comment]
> By the way I have realized that when many images are uploaded in the same batch, the API request to save the associated data (not the files!) takes a while... 

See also: https://github.com/c2corg/v6_api/issues/569

**Comment by arnaud-morvan** [comment]
@asaunier : Do you remember why you put a ``this.scope_.$apply()`` executed every second in the ``upload_`` method here : 
https://github.com/c2corg/v6_ui/blob/ecb06aa78ac6bea80d56a74b2f9d96a4d4254553/c2corg_ui/static/js/imageuploader.js#L190
Because it seems to work perfectly without that.

**Comment by asaunier** [comment]
I don't remember at all.
Feel free to remove it if you think it is useless.

**Comment by stef74** [comment]
![img_0229](https://cloud.githubusercontent.com/assets/3962997/23184860/a86723b0-f881-11e6-8fc7-a65ddca6b42d.PNG)
I havé Try to upload 10 photos ... but error message on browser

**Comment by arnaud-morvan** [comment]
This shoud be related with SSL error on demo : #637

**Comment by desnoes** [comment]
Upload of several images works fine. It is impossible to save the images.

**Comment by arnaud-morvan** [comment]
Note that we have also added Retry/Cancel buttons in case of failure.
It is possible to test it by enabling throttling in browser development tools.

**Comment by desnoes** [comment]
> enabling throttling in browser development tools

What do you mean exactly ? I am not an expert in those things. My browser cannot be configure that much at work.

**Comment by arnaud-morvan** [comment]
If you are using firefox or chrome, You can use Ctrl + Shift + i to open the dev tools
In chrome you should go to the network tab, and there is a throttling option in the top toolbar.
In Firefox I don't find it.

**Comment by desnoes** [comment]
It works fine on demo
