### ISSUE TITLE
Enable to load "prefs" filters in advanced search filters

### ISSUE THREAD

**Issue by asaunier** [c2corg/v6_ui#1342]
Users would like to easily apply their preferences (currently used only for the homepage feed) to advanced search pages.

If applicable, activities filter would use the preferred activities and the map would be recentered on the preferred areas. 2 options for the areas:
* use the overall bbox of preferred areas
* actually filter on the preferred areas by adding a ``a=...`` parameter to the URL. For instance https://www.camptocamp.org/outings#a=14427,14421

Questions:
* It should possible to toggle on/off those preferred filters: on/off button in the interface?
* Should those filters be applied by default? (the initial URL must be consistent then and make it obvious preferred filters are applied)
* Should we use a special URL parameter to enable the preferred filters (eg. ``#pref=true``) or retrieve the user's preferences (via an API call? or from the localstorage?) such as ``#a=123,456&act=skitouring,ice_climbing``?

**Comment by stef74** [comment]
Probably need to open discussion on trello/forum ... but I prefer discuss with possibility technically validated (and have macro cost).

But my opinion : 
- for activities is pertinent ( a toogle can be good idea ... reuse the same as in a feed)
- for aera the interact with map can be very confusion ... 

Probably we need to have : 
- map centering on the "union" of aera in pref user search by default ( and not reset it if change filter ... but is probably an other issue)
- offer possibility to filter on area show on the map ( as in airbnb we can filter on "quartier" ... but not search on it directly) You can check by defaut the area of user preference ... but we need to reuse the filtering aera on advanced search for area out of preference.

Concerning url ... they can be consistent, if you need to show on the url the filter added by preference. 
![capture](https://cloud.githubusercontent.com/assets/3962997/21854352/b487d05e-d81a-11e6-913a-142182b2706a.PNG)

**Comment by desnoes** [comment]
> It should possible to toggle on/off those preferred filters: on/off button in the interface?

yes. If you are doing research in a region which was not set in your preference, you need to toggle off the preferred filters. Otherwise, if for instance you are searching for routes and then huts, the preferred filters will apply when you will switch between the 2 search and it will be very annoying.

>Should those filters be applied by default?

yes

**Comment by asaunier** [comment]
Here are my suggestions about making the personal preferences (areas and activities) available in the various advanced search pages.

Concerned document types would be:
* outings, routes, images => areas + activities
* waypoints => areas
* areas => no prefs
* books => activities (but is it really useful?)
* articles => activities (but is it really useful?)
* accident reports => areas + activities (but is it really useful?)

For the 3 last types, I am unsure applying prefs is really relevant (?) but I guess applying the "directive" as design below would be possible and not too complicated since available for the other document types. Just let me know.

## Main principle

Advanced search works by adding filtering parameters to the URL of the search page. Especially activities (``act``) or areas (``a``).

For example skitouring outings in Mont-Blanc and Chablais: https://www.camptocamp.org/outings#a=14410,14411&act=skitouring

The main principle here is to create an angularJS directive (a button) that - when clicked - will open an advanced search page with the ``act`` and ``a`` parameters depending on the current user's prefs:
* would only be visible for authenticated users
* applied filters would depend on the target document type (see the list above)
* prefs would be retrieved using the ``users/preferences`` API service (already used by the "My Preferences" page in the UI). To avoid making a request every time the directive is clicked, the prefs could be cached in the browser ``localStorage`` (or ``sessionStorage``?) and updated when changes are done in the ``My Preferences`` page.

The button/directive could be placed in the following places:
* homepage ("Outings" button at the beginning of the feed?)
* guidebook startpage with special cards (=special design) in the existing "Outings", "Routes" and "Waypoints" sections
* in the advanced search pages themselves, as an additional button next to the existing buttons ("More filters", "Show results", "Clear filters")?

Question: what would happen when clicking the "my prefs" button in an advanced search page with already some active filters? Would it reset all the filters and use only the "prefs" filters or would it simply adds/replaces the areas and activities filters?

**Comment by stef74** [comment]
@desnoes could open the consultation to other implicated member (celine, loic etc ...)

**Comment by stef74** [comment]
The option to offer filter on area is not in this issue (the area selected only provide from pref user) ? For me is good idea on UX point of view to show area selected ( prevent question like ... how I show this outing ... not this etc ...). All search parameter should be show on user interface.

**Comment by asaunier** [comment]
> The option to offer filter on area is not in this issue?

No, it's a different issue. It's better to split the problems in smaller blocks than to do everything at once.
The behaviour I have described can work, whether an area selector is provided or not.
Actually it's a matter of setting the filtering parameters in the URL.

See https://www.camptocamp.org/outings#a=14410,14411&act=skitouring which works as expected, even though there is no area selector.

**Comment by stef74** [comment]
>  It's better to split the problems in smaller blocks than to do everything at once.

Yes ... and No. To implement yes ... but it's better to have global vision of what we do in future to not create a blocking point. 

But in this case I not identify a blocking point, we probably need to add a selector on area showed on map.

**Comment by asaunier** [comment]
We won't create any blocking points. Adding ``act`` or ``a`` parameters in the URL is the only way to apply user's preferences and are already supported as is. The goal of this issue is to add a simple tool to take the user's prefs into account and add the matching params.

An area selector is not required to do so. By the way it would probably add quite a lot of work because it has much more impact on the advanced search interface.

The description above is not incompatible with an area selector, which would anyway also add an ``a`` parameter in the URL. Both tools are complementary and not really overlapping each other.
That's why I recommend to keep the issues apart.

**Comment by desnoes** [comment]
> Question: what would happen when clicking the "my prefs" button in an advanced search page with already some active filters? Would it reset all the filters and use only the "prefs" filters or would it simply adds/replaces the areas and activities filters?

I would reset all the filters and use only the "prefs" filters.

Question: is-it alos possible to manage the langage pref (#1382) ?

**Comment by asaunier** [comment]
> Question: is-it also possible to manage the langage pref (#1382) ?

@desnoes If issue #1382 is addressed before the current issue, it is indeed possible to take the language pref into account. But it's not blocking: the lang pref could be added later too.

**Comment by desnoes** [comment]
@asaunier: I understand it is not blocking. There is also #1437 which addresses a similar topic.

**Comment by asaunier** [comment]
> prefs would be retrieved using the users/preferences API service (already used by the "My Preferences" page in the UI). To avoid making a request every time the directive is clicked, the prefs could be cached in the browser localStorage (or sessionStorage?) and updated when changes are done in the My Preferences page.

I have thought of several options concerning this part.

Option 1

Get the prefs (areas + activities) along with other user data when authenticating and save them in a ``prefs`` attribute in ``userData`` (which is saved in the session/localStorage). This way the prefs are always available when the user is authenticated and can be used to build filters at anytime with no additional API request (might be useful if we add a discourse feed in the homepage based upon the discourse API with some params based upon the preferred activities).
TODO:
* make the API provide prefs in the authenticating response
* store ``prefs`` in the usual ``userData``
* make the "My preferences" page use the stored prefs instead of requesting the  existing ``users/preferences`` API service (we must make sure changes in one tab are propagated to the others, in order to avoid desynchronization)
* update ``userData.prefs`` when the user updates their preferences in their "My preferences" page

Option 2a

Prefs are retrieved using the existing ``users/preferences`` API service when needed (ie. when the user clicks on a "apply my prefs" button, eg. in the outings advanced search, in a "See outings in my regions/activities" in the homepage etc.
TODO
* ``prefs`` are also stored in ``userData`` but only when an explicit preferences request is made (remains empty if no action using the user's prefs is performed)
* when clicking a "use my prefs" button or when loading the "My preferences" page, a preferences request is made to the API, stored to ``userData`` (+ other tabs are synced).
* prefs are send used to build the advanced search URL with ``a`` and ``act`` params (or to apply prefs to the discourse feed in the homepage)

Option 2b

To avoid a delay caused by the preferences API request made when pushing a button using those prefs (applying prefs to the advanced search for instance), we could trigger the preferences API request automatically in the background after the user authenticates. This way prefs are directly available.

It might be needed if the discourse feed in the homepage is set up anyway.
Then perhaps using option 1 makes more sense? But the latter option implies changes in the API (options 2a and 2b don't) and perhaps a bit longer authenticating response?

**Comment by desnoes** [comment]
@asaunier : option 1 seems good to me.
I think we should apply preference anytime. If a user wants to search documents that are not in its preferences (e.g. activity ski => climbing), then he has to deselect the criteria in the filter and select new ones for his search. The question is when and how the system come back to the user preference settings ? I would suggest the default preference are set in the advanced search each time the user click on 'more filters'. What is your opinion ?

**Comment by asaunier** [comment]
@tsauerwein If you have time, I would be pretty interested to have your opinion about the options (or others) described at https://github.com/c2corg/v6_ui/issues/1342#issuecomment-277632869

**Comment by asaunier** [comment]
Discussed with @tsauerwein 

* we have to be careful with cached preferences because a user might change their preferences in a device and the new prefs should be updated in the other devices (eg. mobile, other tabs or other browsers)
* having the prefs loaded on demand would avoid this problem but on the other hand add some delay when  applying prefs (to actually get the prefs before applying them). We have considered making a background prefs request on every page that (could) use the prefs but it could make quite a lot of (uncached) requests to the API (for instance the home page might need the prefs)

We have realized that:
* getting the prefs along with other user data when authenticating would make more sense
* nice to have: update the prefs in other devices/tabs when prefs are updated (this happens not that often but else a sign out/in would be required). Perhaps a similar mechanism to the sign in being propagated to all tabs could be used.
* Such prefs data should be updated for already logged in users when the system is first pushed to prod.

So we need a mix of option 1 (except that the "My preferences" page would still make an actual API request to be sure the prefs are up-to-date before updating them) + option 2a (to get the prefs when missing).

**Comment by desnoes** [comment]
It works fine on demo
