### ISSUE TITLE
Reduce icons size on map

### ISSUE THREAD

**Issue by stef74** [c2corg/v6_ui#1343]
#1309 
reduction on icon on map

do something on : 
https://github.com/c2corg/v6_ui/blob/master/c2corg_ui/static/js/map/map.js#L440

But not clear what exactly ....

**Comment by brunobesson** [comment]
I started some work on branch map-cons-size: https://github.com/c2corg/v6_ui/tree/map-icons-size

I am not sure what your goal is. To me, the main problem is that highlighted icons are too big (scaled by a factor 2). Currently, I thus apply a factor of 1.2 only, which seems enough.

@stef74 Are there other things to do?

**Comment by stef74** [comment]
I would also reduce the base icon itself

**Comment by brunobesson** [comment]
Which ones? They don't have the same size. E.g. outings seem small enough for me?

**Comment by stef74** [comment]
Hello,

For me all are too big

waypoint is very too big !
Route can be reduce a little to ease the search in some "dense" sector
Outings ... for me te too but ...  and the precision for outings is not
relevant.

The most important point is WP .... they hide some information in the map !



2017-01-17 9:59 GMT+01:00 Bruno Besson <notifications@github.com>:

**Comment by brunobesson** [comment]
@stef74 I rework my PR to ensure all icons have the same size (because OL uses SVG, the width and height defined are relevant and were not all the same) and reduced it some more. Are you OK like this?

See #1465

**Comment by brunobesson** [comment]
Working on demo
