### ISSUE TITLE
The text in the wind rose is not clickable

### ISSUE THREAD

**Issue by fbunoz** [c2corg/v6_ui#1344]
The texte N, E, S, W in the new wind rose design is not clickable.
As the mouse is attracted by the text, we instinctivly click on the text to select an orientation. But as the text is not clickable, there is no change.
It is better if the text is clickable.

Moreover, the text can be bigger : font-size = 60 instead of 40.

**Comment by brunobesson** [comment]
Fixed by #1351

**Comment by desnoes** [comment]
it has been fixed on demo
