### ISSUE TITLE
Search: bug with 'distance' criteria

### ISSUE THREAD

**Issue by desnoes** [c2corg/v6_ui#1347]
It seems the distance criteria is not handle correctly (meter instead of km ?)
Activity: hikking
All search parameters are the default ones => 7377 results
![bug serarch distance](https://cloud.githubusercontent.com/assets/19892089/21883404/408da044-d8af-11e6-96ed-1eae2d6a781c.jpg)

When the distance criteria is set to 95 km => 0 result
![bug search distance 2](https://cloud.githubusercontent.com/assets/19892089/21883410/486d791a-d8af-11e6-918d-07c944ad81d4.jpg)

**Comment by asaunier** [comment]
Perhaps related to https://github.com/c2corg/v6_ui/issues/1300 ?

**Comment by desnoes** [comment]
It seems to be likely, but i don't know how it is managed in the code.

----- Mail original -----
De: "Alex Saunier" <notifications@github.com>
À: "c2corg/v6_ui" <v6_ui@noreply.github.com>
Cc: "desnoes" <mathieu.desnoes@free.fr>, "Author" <author@noreply.github.com>
Envoyé: Jeudi 12 Janvier 2017 10:47:30
Objet: Re: [c2corg/v6_ui] Search: bug with 'distance' criteria (#1347)



Perhaps related to #1300 ?

**Comment by desnoes** [comment]
The bug is not fixed on Chrome

**Comment by asaunier** [comment]
@desnoes You're right: I have made the change for the mountainbike routes but have forgotten to fix the ``route_length`` filter. I don't know why because your screenshots were explicit enough, sorry!
A fix has been applied https://github.com/c2corg/v6_ui/pull/1384 but won't be available until the next release.

**Comment by desnoes** [comment]
fixed on demo
