### ISSUE TITLE
Map does not display on mobile

### ISSUE THREAD

**Issue by desnoes** [c2corg/v6_ui#1353]
The map is always hidden even when i click on the "world" button.
Chrome version 51.0.2704.81
Android: 6.0.1

This bug appeared since the correction of issue #1312.

It seems that @stef74 also observed this bug. Could you confirm?

**Comment by brunobesson** [comment]
There can be absolutely no relation between #1312 and the bug you are observing :wink: More likely other commits are the cause of this.
Still, I can't observe them.
Can you confirm it is working in prod but not on demo?

**Comment by desnoes** [comment]
>Can you confirm it is working in prod but not on demo?

I confirm. In prod, i click on 'hide list' => a grey square appears on the screen => i click on the world button => the map appears at the same location of the grey square.
On the map, if i click on 'show list' => the map is hidden and the cards are displayed.

**Comment by brunobesson** [comment]
>i click on 'hide list'

What? But there is (or should be) no hide list button on mobile! (at least on the demo). How can you do that? Do you have a screenshot?

**Comment by desnoes** [comment]
> What? But there is (or should be) no hide list button on mobile! (at least on the demo). How can you do that? Do you have a screenshot?

My description concerned the usage in prod, not in demo.

Here is a screen shot of what i get on demo. When i click on the wordl button, the screen remains unchanged, the map is not displayed.
![screenshot_20170112-135651](https://cloud.githubusercontent.com/assets/19892089/21891093/53b09768-d8d1-11e6-856f-99efb0f5d282.png)

**Comment by brunobesson** [comment]
OK then. That's strange, and I cannot help further, because all my devices work fine...

**Comment by AlexisDemongeot** [comment]
The rounded earth-like button works fine on : 

Windows phone 10.0.14393.448
Microsoft Edge 38.14393.448.0

Android 7.1.1
Chrome 55.0.2883.91

Doesn't work on Android stock navigator (apprently not maintened) : 42.0.2311.1185 (747cb06)

**Comment by stef74** [comment]
Not working on firefox desktop (I reduce the size of screen) vesrion ESR 45.6 (the last one une ESR branch)

**Comment by desnoes** [comment]
I have updated Chrome and it works (sorry for the inconvenience, i thought my version was the last one but in fact it wasn't).
@stef74 : can i close the issue ?

**Comment by stef74** [comment]
Nopt work on firefox ... work on chrome

**Comment by AlexisDemongeot** [comment]
Apparently not work on stock browser too : 
https://forum.camptocamp.org/t/tres-triste-de-ne-plus-venir-sur-camp-to-camp/176947/110

I guess it's his problem.

**Comment by asaunier** [comment]
We had this problem again this morning during a meeting with Xavier from :ratio: the map could not be loaded on his iphone /using a recent Safari).

**Comment by stef74** [comment]
Yes not work in safari ...

**Comment by asaunier** [comment]
I have not found the guilty commit yet but at least by testing the previous releases in my dev instance with Chrome, FF and Safari, I can say that
* v6.0.4 is OK for all 3 browsers https://github.com/c2corg/v6_ui/releases/tag/v6.0.4
* v6.0.5 is KO for FF and Safari (Chrome OK I think - don't remember) https://github.com/c2corg/v6_ui/releases/tag/v6.0.5

=> ie. the bug has been introduced between January 4th, 2017 https://github.com/c2corg/v6_ui/commits/master?after=Y3Vyc29yOv6Y2xWyNELbXr22U0vtnY8kGSH2KzE3NA%3D%3D and december 22, 2016 https://github.com/c2corg/v6_ui/commits/master?after=Y3Vyc29yOv6Y2xWyNELbXr22U0vtnY8kGSH2KzIwOQ%3D%3D

**Comment by brunobesson** [comment]
I didn't have time to investigate a lot, but it sems to be a CSS issue. On FF and Chrome, both `<div class="map-right">` tags toggle the `show` class. However, the map is no visible in FF.

(this is another subject, but the positioning has defaults with chrome too - maybe we'll be able to solve both issues together)

**Comment by brunobesson** [comment]
Maybe another solution, too, could be to handle the toggle the same way it is done on larger screens. To be investigated...

**Comment by brunobesson** [comment]
:v: we have a solution with #1438

**Comment by desnoes** [comment]
Good news ! Thanks @brunobesson

**Comment by fbunoz** [comment]
It works on FF and android 4.3.

**Comment by stef74** [comment]
Ok on safari
