### ISSUE TITLE
Gear field title management

### ISSUE THREAD

**Issue by fbunoz** [c2corg/v6_ui#1364]
On the route edit page, the text field "gear" should be renammed "specific gear".
On the route reading page, the text field "gear" could be keeped as "gear", because it contains specific gear (field content) + (later) the links to the common gear articles.

The links to common gear articles are not present but there is an issue : https://github.com/c2corg/v6_ui/issues/1005

For the moment, we could use "specific gear" in both case. But the translation can't be changed, as "gear" ID is also used for an article category. We must define a new translation ID for "specific gear".

**Comment by brunobesson** [comment]
@fbunoz Note that there is another PR for #1005, I would appreciate your feedback concerning the anchor problem.

**Comment by desnoes** [comment]
Fixed on demo
