### ISSUE TITLE
Add "my outings" link in user's menu

### ISSUE THREAD

**Issue by brunobesson** [c2corg/v6_ui#1368]
Some users have difficulties finding their outings list. Should we add another item to the current menu? Or do you think there are already too many items?

We could also think ahead and take statistics page: how will this one be positioned and accessed?

@desnoes could you ask the current task force you're leading?

**Comment by stef74** [comment]
Which menu ?

**Comment by brunobesson** [comment]
>Which menu ?

The user's menu. The one in blue you can access from the top right.

**Comment by stef74** [comment]
Yes ... but it's not simple change ... filtering on user is not available throught search

**Comment by brunobesson** [comment]
What? No. Producing a link to the user's outing page is easy (there is already this link on the user's profile page).

**Comment by asaunier** [comment]
> Some users have difficulties finding their outings list. 

There's a big orange "show this user's outings" button at the top of the profile feed!?
Why would users see the menu you suggest if they cannot see this button in their profile?

@stef74 Yes, it's easy. It seems you have not seen this big orange button I was just talking about :P

**Comment by brunobesson** [comment]
>There's a big orange "show this user's outings" button at the top of the profile feed!?
Why would users see the menu you suggest if they cannot see this button in their profile?

Apparently, it's not obvious to follow the path my profile to see your outings. The problem may not be that htey don't find the profile menu item or don't see the orange button then, but rather that it seems not logical to them to go this way.

**Comment by asaunier** [comment]
That's how it was done in v5!?

**Comment by stef74** [comment]
You are agree the link allready exist ... i don't remeber you have not only the feed in user profil

**Comment by desnoes** [comment]
Maybe, the size font of the message 'Voir les sorties de cet utilisateur' could be increased.

**Comment by stef74** [comment]
@brunobesson when you create and issue than you handle please add association label :-)

**Comment by fbunoz** [comment]
> That's how it was done in v5!?

On V5, in the menu "My C2C", there was 3 items : 

- my outings
- my images
- my xreports

Then we were be able to acces to our outings list from any c2c page, in 1 clic.

**Comment by asaunier** [comment]
OK, feel free to add such a link to the menu.

**Comment by brunobesson** [comment]
OK, although translations have not been updated.

**Comment by asaunier** [comment]
The translation for "My outings" was not available when the v6.0.7 image was created an hour ago. I made the translation in the meantime but it's too late for this release.

**Comment by stef74** [comment]
but ok for prod ?

**Comment by asaunier** [comment]
Nope. The same docker image will be used. The image is built once for all for a given release.
