### ISSUE TITLE
TypeError with some waypoints (with no geometry?)

### ISSUE THREAD

**Issue by asaunier** [c2corg/v6_ui#137]
* type "age" in simple search
* choose "Vallée des perroquets - bloc age"

=> error 500:

```
File "/home/alex/v6_ui/c2corg_ui/views/waypoint.py", line 42, in view
￼￼'geometry': self._get_geometry(waypoint['geometry']['geom']),
File "/home/alex/v6_ui/c2corg_ui/views/document.py", line 174, in _get_geometry
￼￼return asShape(json.loads(data))
File "/usr/lib/python3.4/json/__init__.py", line 312, in loads
￼￼s.__class__.__name__))
TypeError: the JSON object must be str, not 'NoneType'
```

**Comment by tsauerwein** [comment]
To reproduce you can directly open http://c2corgv6-demo.gis.internal/waypoints/103899/fr, right?

**Comment by asaunier** [comment]
Indeed

**Comment by fbunoz** [comment]
It is allowed not to georef a "climbing site" in V5, for sub-site, to have only one WP for the whole site on the map. Then there are 160 WP without georef : http://www.camptocamp.org/sites/list/geom/no
But we'll have to improve the map to allowed that all WP are georef with a good display on the map.

**Comment by asaunier** [comment]
Coordinates are a required field for all waypoints in v6.
Georeferencing sub-sites makes sense, doesn't it? This way you can spot on the map where the subsites are.

**Comment by fbunoz** [comment]
Yes, but in the first version of V5 map, it caused some problem in the display.
There is always a problem : http://www.camptocamp.org/map?map_x=659594.22623803&map_y=5555691.6353353&map_zoom=10&tree_layers=sites
The main WP for a site is masked by the sub WP.
I don't know how to avoid this.

**Comment by asaunier** [comment]
We could use clusters when icons are too close from each other:
http://openlayers.org/en/v3.15.1/examples/earthquake-clusters.html
