### ISSUE TITLE
Use CSS only to style snow conditions for mobile

### ISSUE THREAD

**Issue by brunobesson** [c2corg/v6_ui#1373]
Instead of having 2 components, one being always hidden while the other is shown, CSS is enough to style the table for mobile.

**Comment by brunobesson** [comment]
See #1366

**Comment by stef74** [comment]
@brunobesson is not on demo ? so use ready for demo ;-)

**Comment by brunobesson** [comment]
Sorry. Both names are confusing to me, I often have to check @asaunier explanations for this.

**Comment by brunobesson** [comment]
OK on chrome and firefox. Could someone test on IE or Edge and Safari, although I'm pretty confident it works?

**Comment by stef74** [comment]
who have edge in mobile ?  I test safari

**Comment by stef74** [comment]
have an example of outing with snow conditions ?

**Comment by brunobesson** [comment]
Can't you create one?

http://www.demov6.camptocamp.org/outings/828340/fr/wetterhorn-par-le-rosenlauigletscher

**Comment by stef74** [comment]
ok on safari
