### ISSUE TITLE
Paragliding landing icon error

### ISSUE THREAD

**Issue by desnoes** [c2corg/v6_ui#1386]
topoguide home page: https://www.demov6.camptocamp.org/topoguide
Section waypoints: the icon for the WP 'paragliding landing' is not the correct one.

**Comment by brunobesson** [comment]
This is a more general issue with the paragliding landing icon. I renamed the issue accordingly.

**Comment by asaunier** [comment]
> This is a more general issue with the paragliding landing icon

Indeed. It impacts also the icon in front of the title in a paragliding landing area page:
http://www.demov6.camptocamp.org/waypoints/828392/fr/zzzzzz

At first I thought the character used in the icons SVG font was probably not the good one:
https://github.com/c2corg/v6_ui/blob/a7428f9c0269ed03b047df9678e09dd05e27e460/less/waypoint-types.less#L90-L92

but in the SVG file https://raw.githubusercontent.com/c2corg/v6_ui/a7428f9c0269ed03b047df9678e09dd05e27e460/c2corg_ui/static/img/fonts/waypoint_types.svg seems to be consistent with the character code!?

Perhaps we have to recreate the ``waypoint_types`` font files according to the instructions available at https://github.com/c2corg/v6_ui/tree/a7428f9c0269ed03b047df9678e09dd05e27e460/c2corg_ui/static/img/fonts
