### ISSUE TITLE
Preview modal issues

### ISSUE THREAD

**Issue by brunobesson** [c2corg/v6_ui#1387]
The button and content of the modal dialog for preview are not placed correctly. Problem is, it requires some javascript to handle window resizing and ensure modal remains fullscreen.

**Comment by asaunier** [comment]
> The button and content of the modal dialog for preview are not placed correctly. 

Could you provide a screenshot? I don't understand the problem with the "close" button and the preview content: they look normal for me. Is it related to some browser or device (mobile phone?)?

**Comment by brunobesson** [comment]
E.g. on mobile:
![certif20](https://cloud.githubusercontent.com/assets/2234024/22103927/4cb8f8b2-de3d-11e6-9e5f-a5e5f0b0354e.png)

The placement is using percents, while we would rather a fixed right and bottom margin.

**Comment by asaunier** [comment]
OK, then it's a mobile issue? If yes, perhaps you should update the issue title to clarify it (I see no problem in FF and Chromium on a desktop screen).

**Comment by brunobesson** [comment]
>it's a mobile issue?

I wouldn't say that. On desktop too, the positioning varies with the window size, althoughthe problem isn't obvious.
