### ISSUE TITLE
Impossible to 'serve' v6_ui

### ISSUE THREAD

**Issue by stef74** [c2corg/v6_ui#1388]
Since laste update impossible to make -f config/stef serve

![capture d ecran 2017-01-18 a 21 39 08](https://cloud.githubusercontent.com/assets/3962997/22082123/c7648260-ddc6-11e6-8710-f2f4b77cf056.png)

**Comment by stef74** [comment]
probably need to update common ...

**Comment by brunobesson** [comment]
This is not an issue. Run `make -f config upgrade` first.

**Comment by asaunier** [comment]
> probably need to update common ...

Exactly.
When changes are done in file ``requirements.txt`` https://github.com/c2corg/v6_ui/commits/master/requirements.txt it is required to run the ``upgrade`` target.

```
make -f config/... clean upgrade install clear-cache check
```
