### ISSUE TITLE
Broken styles for tags "important" and "warning"

### ISSUE THREAD

**Issue by asaunier** [c2corg/v6_ui#1392]
![capture du 2017-01-19 12-21-19](https://cloud.githubusercontent.com/assets/1192331/22104943/eb0312d8-de41-11e6-8fd0-81805d354a9e.png)
![capture du 2017-01-19 12-22-00](https://cloud.githubusercontent.com/assets/1192331/22104942/eb02a474-de41-11e6-85e9-6ea2442200a1.png)

See for instance https://www.camptocamp.org/routes/45607/fr/chamechaude-versant-w

It was not like this a few weeks ago. Perhaps those styles have been impacted (on purpose?) by recent changes in the CSS.

**Comment by brunobesson** [comment]
That's because the styling is only applied inside `view-details-description`, while it should be `description` instead.

**Comment by desnoes** [comment]
fixed on demo
