### ISSUE TITLE
Better position of feed preferences buttons?

### ISSUE THREAD

**Issue by asaunier** [c2corg/v6_ui#1403]
In a mobile screen, when logged in, the home page always have the preferences-related buttons displayed at the bottom. Which is a bit a pity because you generally don't need them whereas they take quite a lot of space in the screen.

What about only showing them near the "Feed activity" title? They would then slide away when scrolling down the page.

**Comment by brunobesson** [comment]
I agrre these buttons take too much place. It's the same for the usual float buttons, but maybe it's harder to move (I was at least thinking of hiding them when a textfield is being edited)
