### ISSUE TITLE
Duplication of route cards in waypoint document

### ISSUE THREAD

**Issue by desnoes** [c2corg/v6_ui#1405]
Document: https://www.camptocamp.org/waypoints/380283/fr/le-ferrouillet
The route https://www.camptocamp.org/routes/648021/fr/pointe-n-du-ferrouillet-traversee-sifflet-greater-sciallet-greater-scia-greater-ferrouillet is displayed 3 times for the same activity.

![wp - duplication of route cards](https://cloud.githubusercontent.com/assets/19892089/22148667/c3d54072-df0f-11e6-9d34-31a32cbf95e4.jpg)

Same problem for route https://www.camptocamp.org/routes/380286/fr/pointe-n-du-ferrouillet-arete-ne-ebauche

**Comment by asaunier** [comment]
This issue has already been reported at https://github.com/c2corg/v6_api/issues/589

**Comment by dkocich** [comment]
I see 3 route edits in one day (maybe because of some bug version wasn't updated so it is showing three docs instead of one?)  
![image](https://cloud.githubusercontent.com/assets/6165660/22148801/8dc41214-df10-11e6-94e4-787f8f575c34.png)

**Comment by desnoes** [comment]
@asaunier @dkocich : ok, i close this issue

**Comment by asaunier** [comment]
> I see 3 route edits in one day (maybe because of some bug version wasn't updated so it is showing three docs instead of one?)

@desnoes It's probably by chance that there are 3 edits on this day and 3 cards. Why would having edits on the same date make a difference with the other edits?

This route is associated to 3 WP (Pointe N du Ferrouillet, Brèche N du Ferrouillet, Pointe Centrale N du Ferrouillet) which are "child-waypoints" of the example WP "Le Ferrouillet".
That seems to be the use case described at https://github.com/c2corg/v6_api/issues/589

> ok, i close this issue ?

@desnoes Please do.
