### ISSUE TITLE
Image editing map section

### ISSUE THREAD

**Issue by asaunier** [c2corg/v6_ui#1408]
The map section could be more individualized in the image editing form, with a title (as for WP, routes or outings I think). In addition adding the lon/lat fields (as for WP) would make sense.

<img width="967" alt="capture d ecran 2017-01-20 a 22 03 20" src="https://cloud.githubusercontent.com/assets/1192331/22165586/e502c47a-df5c-11e6-83aa-91f9063b57d3.png">

**Comment by desnoes** [comment]
ok on demo
