### ISSUE TITLE
Bad display of embedded image in "access" text field

### ISSUE THREAD

**Issue by fbunoz** [c2corg/v6_ui#1411]
On [this doc](https://www.camptocamp.org/waypoints/102068/fr/baou-de-saint-jeannet), an image is inserted in the text field "access".
But it is displayed with slideshow info : buton in "access" title bar, image title with "tag" picto under the image, image at left instead of right, etc. If we show the image infos in the slide show and close the slideshow, the infos are displayed under the embedded image.

I don't know if the same bug exist for other text field which are not "description".

**Comment by asaunier** [comment]
Most likely a CSS selector problem?

**Comment by brunobesson** [comment]
The problem seems similar to the warning and important tags reported in #1392: the styling works only in the description field.

**Comment by brunobesson** [comment]
This is fixed. Closing.
