### ISSUE TITLE
Show only filled docs in the feed

### ISSUE THREAD

**Issue by fbunoz** [c2corg/v6_ui#1416]
In the feed, an empty outing (or any other doc type) shouldn't generate any entry.
For the outings, the quality field is useful mainly to filter empty outings and show only filled outing.

Related association topic : https://forum.camptocamp.org/t/sorties-vides/175438

**Comment by asaunier** [comment]
This is probably a 100% API-related issue, that should be moved to https://github.com/c2corg/v6_api/issues

The tricky thing is that feed entries are created/updated only when:
* the document is created
* images are uploaded to the document
* for outings: participants are associated

=> if a document (eg. an outing) is created with a poor quality and if the feed service filters on quality, documents with poor quality will never be shown in the feed, even though the quality is eventually improved. On the other hand, if an empty outing is created with an "excellent" quality, it will not be possible to hide the feed entry even though the quality is set back to "empty".

@desnoes @stef74 The present improvement request should probably considered along with other improvements listed at https://github.com/c2corg/v6_api/issues/635

**Comment by desnoes** [comment]
> The present improvement request should probably considered along with other improvements listed at c2corg/v6_api#635

Yes, you are right.
