### ISSUE TITLE
Images : update incorrect date and time using a script

### ISSUE THREAD

**Issue by fbunoz** [c2corg/v6_ui#1419]
All images from 828237 to ??? (~10000 images) have bad date and time, caused by https://github.com/c2corg/v6_ui/issues/1176
They must be corrected by a script.

**Comment by fbunoz** [comment]
Be careful : even if some fixes do that the time is extracted from the photo (and not only the date), it is not the good date/time.
Then, we must wait for https://github.com/c2corg/v6_api/issues/627 is fixed before running this script.

**Comment by asaunier** [comment]
Closing this issue because it's not a UI issue, rather an API issue.
