### ISSUE TITLE
xreports: titles and selectors are not displayed correctly

### ISSUE THREAD

**Issue by desnoes** [c2corg/v6_ui#1421]
Many titles or selector fields are not displayed correctly. The transifex variable is displayed instead of the translated string.
See result: http://www.demov6.camptocamp.org/xreports/828390/fr/toto

![serac bug 1](https://cloud.githubusercontent.com/assets/19892089/22280502/88c1dea8-e2d1-11e6-9e17-dc65bcff9f4b.jpg)

**Comment by brunobesson** [comment]
I am seing the translations (although many miss an uppercase letter) with Firefox and Chrome... Don't understand why you get this result?

**Comment by tsauerwein** [comment]
Are there English translations for these strings?

**Comment by asaunier** [comment]
> Are there English translations for these strings?

No

There are >100 strings not translated in English in Transifex: https://www.transifex.com/camptocamp-association/c2corg_ui/translate/#en/v6/102266491?translated=no

**Comment by dkocich** [comment]
While translating EN someone should also look at other languages. There are often upper/lower case letters changing so it would probably be good to make every first letter uppercase...?

![image](https://cloud.githubusercontent.com/assets/6165660/22282619/e2c620a6-e2dd-11e6-9767-609da3ad076a.png)
