### ISSUE TITLE
Coordinates should not be required when editing an image

### ISSUE THREAD

**Issue by asaunier** [c2corg/v6_ui#1427]
Lon/lat fields are marked as ``required`` in the image editing form.
https://github.com/c2corg/v6_ui/blob/master/c2corg_ui/templates/image/edit.html#L179
As a result it is no longer possible to edit an image without providing coordinates.

By the way the "what is missing" button does not notify that those data are missing. There is probably something missing in the config of mandatory attributes. 

Geolocalizing images is not mandatory, thus lon/lat attributes should not be made required.

**Comment by desnoes** [comment]
fixed on demo
