### ISSUE TITLE
Show only filled docs in Search results page

### ISSUE THREAD

**Issue by loicperrin** [c2corg/v6_ui#1437]
In the search results page, the filter on quality field should be activated by default on the level 1 for min value, so that empty outings (or any other doc type) do not appear on this page by default. The user can modify this value if he wants to display them.

Related association topic : https://forum.camptocamp.org/t/sorties-vides/175438

**Comment by asaunier** [comment]
It's really important that all filters applied to a search appears in the URL (to make them reproductible and to be consistent among all filters). Which means that if a quality filter must be applied, the matching param must appear in the URL when opening such a page.

**Comment by stef74** [comment]
Yes completly agreee with @asaunier so we have to had &qa=draft%252Cgreat on each request by default

**Comment by desnoes** [comment]
This subject was discussed in the forum (https://forum.camptocamp.org/t/prepositionnement-du-filtre-sur-la-completude/192483) => there is an agreement for only addressing the outings. The other documents (routes, WP...) are not concerned.

Proposition : in the menu:  modify the url of the outing search page ('https://www.camptocamp.org/outings' =>'https://www.camptocamp.org/outings#qa=draft,great'). This solution is simple and consistent with other filters ( filtering criteria shall appear in the url).

**Comment by asaunier** [comment]
> OK for a PR ?

@desnoes This looks like a simple solution, OK for me.
