### ISSUE TITLE
In image edition, do not allow to change the licence to copyright

### ISSUE THREAD

**Issue by fbunoz** [c2corg/v6_ui#1441]
The licence of an image should be changed to copyright only by a moderator.
But for now, everybody can change the licence of its personal images to copyright.
The copyright option must be limited to moderator only.
A simple member must be able to choose between personal and collaborative licence only.

There is no problem in the image upload tool, only in the image edit form when we modify an image.

**Comment by asaunier** [comment]
It would make sense to appky a kind of filter in the image editing form at https://github.com/c2corg/v6_ui/blob/master/c2corg_ui/templates/image/edit.html#L145
the same way than it's done in the image uploader:
https://github.com/c2corg/v6_ui/blob/master/c2corg_ui/static/partials/imageuploader.html#L83
https://github.com/c2corg/v6_ui/blob/master/c2corg_ui/static/js/imageuploader.js#L480-L489

**Comment by asaunier** [comment]
> The licence of an image should be changed to copyright only by a moderator.

I have suggested a PR to fix the problem in the UI. #1459

But some checks might be needed in the API as well. Please open an API issue then.

**Comment by desnoes** [comment]
the bug has been fixed
