### ISSUE TITLE
Flexbox in topoguide

### ISSUE THREAD

**Issue by stef74** [c2corg/v6_ui#1448]
Card via ferrata are not the same than other 

![capture d ecran 2017-01-30 a 21 07 28](https://cloud.githubusercontent.com/assets/3962997/22439547/5614522a-e730-11e6-96ae-411f6694bdad.png)

@brunobesson : Probably need to use some solution than other card in search or doc.

**Comment by brunobesson** [comment]
Kudos for noting this. I pushed PR #1450 for this.

**Comment by desnoes** [comment]
fixed in demo
