### ISSUE TITLE
Missing translation for licence type

### ISSUE THREAD

**Issue by fbunoz** [c2corg/v6_ui#1451]
All translation ID are translated in transifex, but it misses some translations about licence type : 

- [ ] In article edition, the licence types are not translated in the selector : 'collab' and 'personal' even in french (https://www.demov6.camptocamp.org/articles/edit/828400/en)
- [ ] In a page of an image, or in the slideshow, the personal licence is not translated : 'personal' instead of 'personnelle' in FR (https://www.demov6.camptocamp.org/images/828416/fr/-).
- [ ] when editing an image, tranlastion is missing too
- [ ] In the image filter, the licence selector uses the article licence options instead of image licence options : 'collaboratif' instead of 'collaborative' (idem for 'personnel' (https://www.demov6.camptocamp.org/images)

**Comment by brunobesson** [comment]
I have a branch ready for the first 3 points (I added the case of an image edition).

However, there is something confusing for the last one. This is rather a translation key clash.

The image_types are defined as follows:

    image_types = [
        'collaborative',
        'personal',
        'copyright'
    ]

And the articles_types as

    article_types = [
        'collab',
        'personal'
    ]

So there is an overlap in the translations. Currently, both `collab` and `collaborative` are translated as `collaboratif` in french. So there is no female translation currently.
@asaunier @fbunoz what should we do? Do we need to modify the keys in v6_api?

**Comment by asaunier** [comment]
> Do we need to modify the keys in v6_api?

I recommend using the same gender for both ``image_types`` and ``article_types``. After all both are "types". Actually I would have recommended to have ``collaborative`` instead of ``collab`` in ``article_types``. I don't really understand why such a difference, especially since both attributes have ``personal`` as possible value.

Since changing those values would impact the database itself (those values are used as "enumerations" for ``image_types`` and ``article_types`` fields), it's not a trivial change (but not impossible).

**Comment by brunobesson** [comment]
>I recommend using the same gender for both

I would agree with this advice. If there is no opposition, then we could create an issue in v6_api for using `collaborative` instead of `collab` for articles?

AFAIK #1454 is enough to solve this issue then?

**Comment by asaunier** [comment]
> I would agree with this advice. If there is no opposition, then we could create an issue in v6_api for using collaborative instead of collab for articles?

Up to you. But if we can live with it, I would recommend to leave it as it. Else we need to create an Alembic script to update the values in the articles table. Not sure it's worth doing it!?

**Comment by fbunoz** [comment]
I prefer the same words for article and image, because it concerns the licence (and it implies different right of edition, but it almost identical between article and image when the licence is the same).
We can renaming the field name for article : "Type d'article (licence)", to be consistent with image type filed name ( "Type d'image (licence)" ).

**Comment by brunobesson** [comment]
OK, let's consider this issue is fixed with #1454

**Comment by desnoes** [comment]
fixed in demo
