### ISSUE TITLE
Editing form map not correctly recentered in FF

### ISSUE THREAD

**Issue by asaunier** [c2corg/v6_ui#1452]
When editing a WP in Firefox, the feature is actually shown on the map but the map is not recentered/zoomed on it (as in Chrome).

**Comment by dkocich** [comment]
Can you give some example link? I tried to edit 3 points on prod+demo and I see no problem - it was zoomed and centred every time.

**Comment by asaunier** [comment]
> I tried to edit 3 points on prod+demo and I see no problem

With Firefox?

For instance http://www.demov6.camptocamp.org/waypoints/edit/397185/fr

With Chrome/Chromium:

![capture du 2017-01-31 13-26-14](https://cloud.githubusercontent.com/assets/1192331/22464785/e03df518-e7b8-11e6-9b8d-ff5583d49d78.png)

With Firefox:

![capture du 2017-01-31 13-27-45](https://cloud.githubusercontent.com/assets/1192331/22464825/15493c2c-e7b9-11e6-9880-50c6f6f8f89e.png)

**Comment by dkocich** [comment]
This is strange - for me it was exactly opposite. In this case, everything was fine with FF and Chrome was zoomed out. When I tried to log in again (reload authentication after demo update) + refresh few times, it is ok in both browsers.

The only thing I can think of now is that I noticed that there is an area assoc. on API to this WP http://api.demov6.camptocamp.org/waypoints/397185 and map normally zooms also on the geom. of associated documents. Some errors with auth. maybe caused that map didn't refresh and stayed zoomed out?... I will investigate it.

**Comment by dkocich** [comment]
For this one I get
http://localhost:6558/waypoints/edit/820438/fr?debug

```
TypeError: Cannot read property '0' of null
    at Object.ol.extent.extendCoordinate (extent.js:352)
    at Object.ol.extent.boundingExtent (extent.js:45)
    at ol.interaction.Modify.handlePointerAtPixel_ (modify.js:707)
    at ol.interaction.Modify.addFeature_ (modify.js:202)
    at ol.interaction.Modify.handleFeatureAdd_ (modify.js:287)
    at ol.Collection.boundListener (index.js:17)
    at ol.Collection.ol.events.EventTarget.dispatchEvent (eventtarget.js:88)
    at ol.Collection.insertAt (collection.js:129)
    at ol.Collection.push (collection.js:153)
    at ol.source.Vector.<anonymous> (vector.js:307)
```

**Comment by asaunier** [comment]
> The only thing I can think of now is that I noticed that there is an area assoc. on API to this WP http://api.demov6.camptocamp.org/waypoints/397185 and map normally zooms also on the geom. of associated documents.

I don't think associated documents are shown on the map in the editing form.

**Comment by desnoes** [comment]
i did not observe the bug with FF. I used the example given above (http://www.demov6.camptocamp.org/waypoints/edit/397185/fr). I close the issue ?

**Comment by asaunier** [comment]
I can lo longer reproduce the problem either !?
OK I close the issue, thanks for testing!
