### ISSUE TITLE
Use npm package references for some packages

### ISSUE THREAD

**Issue by asaunier** [c2corg/v6_ui#1455]
* [x] angular-recaptcha https://github.com/c2corg/v6_ui/blob/master/package.json#L17 See https://www.npmjs.com/package/angular-recaptcha => perhaps we could upgrade to 4.0.1 instead of 3.0.1
* [ ] angular-debounce https://github.com/c2corg/v6_ui/blob/master/package.json#L34 See https://www.npmjs.com/package/angular-debounce but not sure it's the same package!

**Comment by dkocich** [comment]
`angular-debounce`
It isn't.

- Our - latest 0.1.7 https://github.com/shahata/angular-debounce/releases
- The one from NPM don't have this version... https://github.com/rubenv/angular-debounce/releases

**Comment by asaunier** [comment]
> It isn't same.

OK than please close the issue when your PR #1479 is merged. Thanks!
