### ISSUE TITLE
Use release tag instead of commit hash as UI version id

### ISSUE THREAD

**Issue by asaunier** [c2corg/v6_ui#1458]
See https://github.com/c2corg/v6_ui/blob/master/c2corg_ui/templates/sidemenu.html#L70-L74

**Comment by asaunier** [comment]
Could be achieved by modifying (or extending) https://github.com/c2corg/v6_ui/blob/master/config/default#L26
using 
```
git describe --tags `git rev-parse HEAD`
```
instead of 
```
git rev-parse --short HEAD
```

For instance:
```
$ git describe --tags `git rev-parse HEAD`
v6.1.5
```

That might impact the health service https://github.com/c2corg/v6_ui/blob/bcb6106395398029498bc77cad98349d98b748b7/c2corg_ui/views/health.py#L29 so perhaps it is safer to add a ``tag`` data next to the ``version`` data.

Template https://github.com/c2corg/v6_ui/blob/master/c2corg_ui/templates/sidemenu.html#L71-L72 should be updated as well as some view file I guess.

**Comment by asaunier** [comment]
It seems it does not work as expected in the demo:
<img width="245" alt="capture d ecran 2017-05-14 a 10 16 53" src="https://cloud.githubusercontent.com/assets/1192331/26032226/7da04772-388e-11e7-9c8c-ecdeeb06d099.png">

**Comment by desnoes** [comment]
I cannot observe the string 'version' in the home page. Where should it be visible ?

![bug release tag](https://cloud.githubusercontent.com/assets/19892089/26035576/22cd2108-38cf-11e7-9dfb-0e2d2ffb27a5.png)

**Comment by asaunier** [comment]
Your screen is too small. The version info is not shown when the screen height is not enough. See my screenshot above (but the version number seems to be not correct in the demo). See also https://github.com/c2corg/v6_ui/pull/1630#issuecomment-300601307

**Comment by asaunier** [comment]
I prefer reopening the issue because the version info is not correct in demo (probably not in prod either). See https://github.com/c2corg/v6_ui/issues/1458#issuecomment-301297791

**Comment by asaunier** [comment]
In prod ``version: 0`` is shown as well, instead of the actual release number.

The ``common.ini`` file in the docker containers is indeed ``release = 0``:
https://github.com/c2corg/v6_ui/blob/master/common.ini.in#L40

It seems
```
https://github.com/c2corg/v6_ui/blob/master/config/default#L27
```
is not correctly taken into account (on the contrary of the ``version`` param above). By the way I am not even sure the config file above is actually used when building the docker image.

Perhaps we could simply add the version number by hand in the ``docker-compose.yml`` file?

**Comment by desnoes** [comment]
> Perhaps we could simply add the version number by hand in the docker-compose.yml file?

ok for me

**Comment by asaunier** [comment]
> Perhaps we could simply add the version number by hand in the docker-compose.yml file?

I have done so in the demo, adding a ``ui > environment > release`` parameter in the demo's ``docker-compose.yml``, set to the current release number and it works.
![capture du 2017-06-23 17-12-52](https://user-images.githubusercontent.com/1192331/27488394-3c0f6112-5837-11e7-8cfa-63b4d9060b07.png)

**Comment by desnoes** [comment]
I am unable to test, i cannot observe the text for the version. My screen height is not large enough.

**Comment by desnoes** [comment]
@stef74 @brunobesson : do you have the possibiliby to test this issue. The screen height is not enough. I can't see the added text.

**Comment by brunobesson** [comment]
Even if your screen is too small, you could resize your browser window :wink: 
Anyway, I tested it and it's OK.

**Comment by desnoes** [comment]
> Even if your screen is too small, you could resize your browser window 

I did this operation, but the text still did not show up.

**Comment by desnoes** [comment]
ERRATUM: i can observe the text. Sorry for the inconvenience.

----- Mail original -----
De: "Bruno Besson" <notifications@github.com>
À: "c2corg/v6_ui" <v6_ui@noreply.github.com>
Cc: "desnoes" <mathieu.desnoes@free.fr>, "State change" <state_change@noreply.github.com>
Envoyé: Mercredi 28 Juin 2017 13:46:50
Objet: Re: [c2corg/v6_ui] Use release tag instead of commit hash as UI version id (#1458)



Even if your screen is too small, you could resize your browser window 😉 
Anyway, I tested it and it's OK.
