### ISSUE TITLE
Missing translation ID in xreport

### ISSUE THREAD

**Issue by fbunoz** [c2corg/v6_ui#1473]
- [x] In the xreport read and edit page, the title of the section "personal" must have a specific translation ID to avoid conflict with other uses of "personal". Because "personal" is the translation ID for "personal licence", using for image and article. The xreport section title should be "personal infos" ("Infos personnelles" in FR).
- [x] ~~~In the outing read and edit page, the field title for the checkbox "soft mobility outing" must have a specific translation ID.
For now, the ID is "public_transport", which is also use in access WP.
It should be "soft mobility outing", to allow the outings with bicycle access.~~~

**Comment by fbunoz** [comment]
> For now, the ID is "public_transport", which is also use in access WP.

Wrong, in access WP it's public_transportation_rating

**Comment by brunobesson** [comment]
Translation is OK when editing xreport, but the box doesn't appear in view. Is there some reason it is not shown? I am checking a report I made with my own account.

**Comment by desnoes** [comment]
@mgerbaux @fbunoz : the box is displayed in the preview but not in view. Is-it the expected result ?

**Comment by fbunoz** [comment]
In V5, only the field "author" was visible in view for simple membre.
For moderator, all field of "personal" box was visible.
In the preview, it's better to show the same field as the view, the only the "author" field should be shown.

**Comment by desnoes** [comment]
@fbunoz : so the bug is fixed in view but a minor bug remain in preview. I am right ?
