### ISSUE TITLE
Comments not displayed correctly when not authenticated

### ISSUE THREAD

**Issue by desnoes** [c2corg/v6_ui#1475]
It is not possible to display the comment of this outing (FF): https://www.camptocamp.org/outings/848376/fr/col-de-balafrasse-par-la-colombiere
I know there is one comment, i post it this morning.

![bug commentaires](https://cloud.githubusercontent.com/assets/19892089/22666065/89a2f0b0-ecb7-11e6-8655-f7cf2a410529.jpg)

**Comment by asaunier** [comment]
I have the same problem with FF and Safari. OK with Chrome.
Ditto with this other outing (most likely all outings, do we have an example with routes or other document types?): https://www.camptocamp.org/outings/848493/fr/dent-de-valerette-versant-nw-x2

**Comment by desnoes** [comment]
when i open the comment from my profile (forum), it is displayed correctly.

> Ditto with this other outing (most likely all outings, do we have an example with routes or other document types?): https://www.camptocamp.org/outings/848493/fr/dent-de-valerette-versant-nw-x2

What does 'Ditto' mean ? In the link you've given, comments are displayed correctly.

**Comment by asaunier** [comment]
Ditto = Idem

**Comment by fbunoz** [comment]
I see no problem on FF.
Maybe a 503 error on forum server can create this problem sometime ?

**Comment by desnoes** [comment]
The problem disapeared this morning.

**Comment by asaunier** [comment]
I just had the same problem with Chrome! Then it's not limited to FF or Safari.
In addition I have noticed that the problem seems to occur only when not authenticated. If I log in, the comments are correctly displayed. If I log out and refresh the page, the comments are not correctly displayed.

**Comment by asaunier** [comment]
When opening a page with comments such as https://www.camptocamp.org/outings/848376/fr/col-de-balafrasse-par-la-colombiere

I observe the following error in my network console when not authenticated:
```
Request URL:https://forum.camptocamp.org/embed/comments?topic_id=178827
Request Method:GET
Status Code:403 Forbidden
```

If authenticated I get an HTML page that is used to display the comments in the iframe.

I guess there is a permission error that makes comments topics not accessible to anonymous users.
@arnaud-morvan @fbunoz any hint about this problem? Perhaps the permissions about the comments category have been modified?

**Comment by arnaud-morvan** [comment]
I do not reproduce, tested with firefox and chromium.
For me this comment is correctly displayed when not authenticated.

**Comment by asaunier** [comment]
I reproduce this behaviour 100% of the time with Chromium 55 and FF 51 on my Ubuntu laptop.
Ditto at home with my MacBook on Chrome 56, FF and a recent Safari.
I have just tried in Browserstack with Edge14/Win10: same behaviour.

Authenticated: comments are displayed as expected.
Not authenticated: comments are not rendered as expected:

![capture du 2017-03-02 10-17-10](https://cloud.githubusercontent.com/assets/1192331/23500803/8e35f118-ff31-11e6-9c32-70b36d4435ae.png)
![capture du 2017-03-02 10-17-20](https://cloud.githubusercontent.com/assets/1192331/23500804/8e3b0fae-ff31-11e6-9169-e3172793bc76.png)

See for instance https://www.camptocamp.org/outings/857542/fr/breitwangflue-flying-circus

Please make sure to refresh the page after logging out.

**Comment by arnaud-morvan** [comment]
Sorry, I was logged on forum, not on topoguide, seems that the expirations are not the same.
I can reproduce, I will investigate.

**Comment by arnaud-morvan** [comment]
The comment category on production server has been passed to private.
In my memory, at the v6.0 golive: 
* this category was child of a top level category.
* the top level category may be private but the child category public.
This seems it have been changed (comments parent category has been removed, and comments promoted to top level).

Note that it is possible to hide the category from the home page, in category settings : "Retirer cette catégorie de la page d'accueil" but it is still visible in the categories dropdown list.

**Comment by arnaud-morvan** [comment]
I see two options : 
* Change the permissions on the comments category
* Display a message instead of the errorred 401 iframe

**Comment by asaunier** [comment]
@arnaud-morvan Thanks for investigating!

@fbunoz could you make changes in the forum admin and make the comments public?

**Comment by jmarcmod** [comment]
J'ai rendu la catégorie "Commentaires" visible à tous, donc en particulier aux invités.
C'est OK désormais ?

**Comment by asaunier** [comment]
@jmarcmod Ca semble tout bon par ex https://www.camptocamp.org/outings/848376/fr/col-de-balafrasse-par-la-colombiere ou https://www.camptocamp.org/outings/857542/fr/breitwangflue-flying-circus y compris en invité.
Merci :)
