### ISSUE TITLE
Scroll up with pagination buttons

### ISSUE THREAD

**Issue by asaunier** [c2corg/v6_ui#1486]
In the advanced search, it would be handy to go back to the top of the list after clicking on the pagination buttons (especially the ones in the bottom toolbar).

I have tried to add commands like
``window.scrollTo(0, 0);``
or
``$('.list').scrollTop = 0;`` 
to the ``goTo`` actions in https://github.com/c2corg/v6_ui/blob/master/c2corg_ui/static/js/search/pagination.js#L99-L136 (or to type the commands in my console) but with no success yet. An idea anyone? :)

A few tips using angular and ``scrollTop``:
http://stackoverflow.com/questions/23736647/how-to-retain-scroll-position-of-ng-repeat-in-angularjs
http://stackoverflow.com/questions/24040985/scroll-to-top-of-div-in-angularjs

**Comment by tsauerwein** [comment]
`$('.documents-list-section').scrollTop(0)` does the trick.

**Comment by brunobesson** [comment]
Working on demo.
