### ISSUE TITLE
Advanced search API returns an error if offset is above 9970

### ISSUE THREAD

**Issue by brunobesson** [c2corg/v6_ui#1487]
Maybe this could be an API issue too, but is it really pertinent to show a "Go to last" button if there are so many results?
Hiding the button until there are fewer results would make sense too.

**Comment by brunobesson** [comment]
E.g.

https://api.demov6.camptocamp.org//outings?bbox=587706,5526776,660474,5661916&pl=fr&offset=9971
and
https://api.demov6.camptocamp.org//outings?bbox=587706,5526776,660474,5661916&pl=fr&offset=9970

**Comment by dkocich** [comment]
duplicate of https://github.com/c2corg/v6_api/issues/578

**Comment by dkocich** [comment]
Hiding that button on UI is a good idea (oops - I wanted to close API issue).

**Comment by brunobesson** [comment]
@dkocich I now of the c2corg/v6_api#578 issue. But is it really a duplicate if it concerns another project? IMHO we should close the issue in v6-api instead. Moreover, I have a PR for this issue.

**Comment by brunobesson** [comment]
>oops - I wanted to close API issue

OK, we're on the same line then. Thanks.

**Comment by brunobesson** [comment]
Working on demo.
