### ISSUE TITLE
Add buttons to share documents on social network

### ISSUE THREAD

**Issue by mgerbaux** [c2corg/v6_ui#1495]
On V5, we used this application https://www.addthis.com/get/share , that offers to share a document on several sociail network
This sharing buttons could be add in the floating "more" button, on the right of the documents

**Comment by mgerbaux** [comment]
if of any interest, code by @lbesson on V5  : https://trac.dev.camptocamp.org/search?q=addthis

**Comment by mgerbaux** [comment]
I discover that this button was available on demo, but I do not know since when ?
It misses a picture in the date to share, compared to V5

**Comment by brunobesson** [comment]
Since I worked on it last week.
On the picture inclusion side, did you test sharing on facebook or another social media? Because the demo site is password protected, we cannot test it until it goes live, but it should be OK.

**Comment by mgerbaux** [comment]
I test it on facebook for outings (until the preview).
So waiting for a real test on prod :o) For next release ?

**Comment by brunobesson** [comment]
If it's on the demo, then it will be pushed in produiction next time, unless we discover problems.

**Comment by brunobesson** [comment]
See #1714
