### ISSUE TITLE
Archive versions of images seem inaccessible

### ISSUE THREAD

**Issue by asaunier** [c2corg/v6_ui#1503]
See for instance https://www.camptocamp.org/images/history/208579/fr or https://www.camptocamp.org/images/history/851612/fr

**Comment by tsauerwein** [comment]
See https://github.com/c2corg/v6_api/issues/410

**Comment by tsauerwein** [comment]
Have you tested if the archive pages now work properly for images and areas?

**Comment by dkocich** [comment]
Sorry, my mistake. Should we reopen the issue and label it with "ready for demo"?

Yes. It works fine. Examples:
http://localhost:6558/images/history/208579/fr
http://localhost:6558/areas/14441/fr/14440
