### ISSUE TITLE
Conflicting i18n keys for books and images

### ISSUE THREAD

**Issue by lbesson** [c2corg/v6_ui#1514]
Book and images share the same i18n key ("topo") for a type. Topoguide books thus have a type "Tracé, schéma" in french (should be "Topoguide")

https://github.com/c2corg/v6_common/blob/1e3fe0991ecc8acbb0d9234f96eb71413089aa7f/c2corg_common/attributes.py#L564
https://github.com/c2corg/v6_common/blob/1e3fe0991ecc8acbb0d9234f96eb71413089aa7f/c2corg_common/attributes.py#L639

**Comment by asaunier** [comment]
Indeed.
A (temporary?) simple solution would be to change the translation to "Topo", it would work for both types.

**Comment by asaunier** [comment]
It is also possible to change one of those values. It would require to create an alembic script to update the data type and the existing documents. See this PR about a similar change: https://github.com/c2corg/v6_api/pull/652
