### ISSUE TITLE
Improve access to the SERAC DB

### ISSUE THREAD

**Issue by desnoes** [c2corg/v6_ui#1516]
The access to the SERAC DB is not user friendly. Solution: create a dedicated home page for SERAC (similar to the topoguide HP: https://www.camptocamp.org/topoguide)

**Comment by asaunier** [comment]
@desnoes @mgerbaux We need more details about the content of this page. Could you precise the needs?

(partial) TODO:
* [ ] Add a new route/view/template for this static page
* [ ] Design template according to the desired content
* [ ] Update the URL of the xreport entry in the side menu

**Comment by mgerbaux** [comment]
I propose this type of page
![1412112537_1597118560 jpg](https://cloud.githubusercontent.com/assets/22116605/24581859/b4dfdd06-1723-11e7-93ed-fe0b11b96058.png)

it should be homogenized in design with https://www.camptocamp.org/topoguide (if needed, we can use a darker picture)

**Comment by asaunier** [comment]
@mgerbaux Thanks! Looks good to me.

**Comment by asaunier** [comment]
A very first and unfinished version is available here https://github.com/c2corg/v6_ui/pull/1591

**Comment by desnoes** [comment]
I let @mgerbaux validate this issue. I found the result very nice!
