### ISSUE TITLE
xreports: reduce the number of categories for avalanche slope

### ISSUE THREAD

**Issue by desnoes** [c2corg/v6_ui#1519]
There is currently 8 categories:
less than 30°
30°-32°
33°-35°
36°-38°
39°-41°
42°-44°
45°-47°
more than 47°

Modification to have only 5 categories:
less than 30° 
30° to 35° (include previous 30°-32° and 33°-35° categories)
35° to 40° (include previous 36°-38° and 39°-41° categories)
more than 40° (include previous 42°-44° and 45°-47° categories)
unknown

Open question: how do we proceed with former xreports ? We modify them in order to cast with the 5 categories ? we don't change ?

**Comment by asaunier** [comment]
> Open question: hwo do we proceed with former xreports ? We modify them in order to cast with the 5 categories ? we don't change ?

The requested change requires changes in the database anyway. Former reports will have to be updated.

**Comment by brunobesson** [comment]
Good thing we've set up alembic :wink:

**Comment by asaunier** [comment]
> Good thing we've set up alembic 

For sure!
It has already been used twice for user account blocking and the document deleting tool.

**Comment by mgerbaux** [comment]
> Modification to have only 5 categories:
> less than 30°
> 30° to 35° (include previous 30°-32° and 33°-35° categories)
> 35° to 40° (include previous 36°-38° and 39°-41° categories)
> more than 40° (include previous 42°-44° and 45°-47° categories)
> unknown

to be consistent with swisstopo and IGN (even if not mentionned by Omoret, but it was the idea to note easily slope on map), I think we should have 6 classes

- <30
- 30-35
- 35-40
- 40-45
- `>45`
- unknown

**Comment by desnoes** [comment]
@mgerbaux : could you check with O. Moret ? Maybe it is important for researcher to follow their specifications ?

**Comment by mgerbaux** [comment]
> @mgerbaux : could you check with O. Moret ? Maybe it is important for researcher to follow their specifications ?
I have validated this proposition with him

**Comment by asaunier** [comment]
TODO:
* [ ] update the list of values at https://github.com/c2corg/v6_common/blob/master/c2corg_common/attributes.py#L744-L753
* [ ] update translation keys at https://github.com/c2corg/v6_ui/blob/master/c2corg_ui/templates/i18n.html#L513-L520 (translations in Transifex will be lost and will have to be recreated)
* [ ] create an API alembic script to convert the values of the existing xreports

@desnoes @mgerbaux please provide an explicit conversion table between the old values and the new ones:
>    'slope_lt_30',
    'slope_30_32',
    'slope_33_35',
    'slope_36_38',
    'slope_39_41',
    'slope_42_44',
    'slope_45_47',
    'slope_gt_47'

**Comment by desnoes** [comment]
Here is my proposition:

slope_lt_30 =>slope_lt_30
slope_30_32 =>slope_30_35
slope_33_35 =>slope_30_35
slope_36_38 =>slope_35_40
slope_39_41 =>slope_35_40
slope_42_44 =>slope_lg_40
slope_45_47 =>slope_lg_40
slope_lg_47=>slope_lg_40

@mgerbaux : could you confirm ?

**Comment by mgerbaux** [comment]
It has been decided and validated by Petzl foundation to keep 5 classes (+ unknown) to be consistent with IGN and Swisstopo slope maps

slope_lt_30 =>slope_lt_30
slope_30_32 =>slope_30_35
slope_33_35 =>slope_30_35
slope_36_38 =>slope_35_40
slope_39_41 =>slope_35_40
slope_42_44 =>slope_40_45
slope_45_47 =>slope_lg_45
slope_lg_47=>slope_lg_45

**Comment by desnoes** [comment]
All previous xreport have been updated, but it is impossible to know whether the update is correct (no access to previous report to compare).
xreport creation => OK
