### ISSUE TITLE
Use SVG fonts for icons

### ISSUE THREAD

**Issue by asaunier** [c2corg/v6_ui#152]
To avoid downloading every icon separately, we should use a font file containing the list of icons (in SVG).

SVG fonts may be created using http://fontello.com/

**Comment by ginold** [comment]
it is already done, a font is used for every route activities and waypoint types. The only place I'm not sure how to work it around is within the waypoints on the openlayers map where an icon has one .svg per waypoint type specified.

May this issue be closed?

**Comment by asaunier** [comment]
@gberaudo @tsauerwein Do you know if one can use SVG fonts for features icons instead of dedicated SVG files?

**Comment by asaunier** [comment]
It seems possible in OL2 according to this fiddle: http://jsfiddle.net/ldonnet/bdzz0ujk/ using font characters (icons) as label. Probably also in OL3?

**Comment by asaunier** [comment]
According to @tsauerwein 

> You can set a label with a custom font:
http://stackoverflow.com/questions/27809479/use-semantic-ui-or-font-awesome-icons-as-markers-in-openlayers3

> Or you create a single sprite image and then use offset+size when defining your ol.style.Icon:
http://openlayers.org/en/master/apidoc/ol.style.Icon.html

**Comment by ginold** [comment]
We already use SVG icons in a font.
