### ISSUE TITLE
Inconsistencies and missing checks in topoguide forms

### ISSUE THREAD

**Issue by brunobesson** [c2corg/v6_ui#1526]
Needs a complete review to catch minor errors, missing feedbacks and additional checks that could be added.

**Comment by desnoes** [comment]
@brunobesson : could you test this issue? I don't k now what has been modified and whaut shall be tested.

**Comment by brunobesson** [comment]
This has been tested by @asaunier and me before. I created the issue to keep a track of the modifications.
