### ISSUE TITLE
Upgrade to AngularJS 1.5?

### ISSUE THREAD

**Issue by asaunier** [c2corg/v6_ui#153]
http://angularjs.blogspot.ch/2016/02/angular-150-ennoblement-facilitation.html
https://docs.angularjs.org/guide/migration#migrating-from-1-4-to-1-5

**Comment by tsauerwein** [comment]
:+1: for upgrading

**Comment by asaunier** [comment]
Closed by https://github.com/c2corg/v6_ui/pull/158
