### ISSUE TITLE
Useless favicon request when making advanced search requests

### ISSUE THREAD

**Issue by asaunier** [c2corg/v6_ui#1533]
In the advanced search pages, a request to https://www.camptocamp.org/favicon-16x16.png is made whenever a request to the API is done. It is probably useless and should be neutralized.

**Comment by brunobesson** [comment]
Isn't it simply because we rewrite the URL, then the browser automatically fetches favicon?

**Comment by asaunier** [comment]
> because we rewrite the URL

What do you mean?

I have noticed this behaviour is not observed when scrolling down the home feed: new feed requests are done but no favicon is requested at the same time.

**Comment by brunobesson** [comment]
When you update your filter (either by changing the bouding box, any criterion, or changing the page offest), the URL is rewritten accordingly.

AFAIK, modern browsers automatically retrieve favicon. Isn't the request made because the URL changed? Anyway, the cache is used, as expecter. Isn't it?

**Comment by asaunier** [comment]
> When you update your filter (either by changing the bouding box, any criterion, or changing the page offest), the URL is rewritten accordingly.

True

> Isn't the request made because the URL changed? 

Perhaps you're right, I don't know. At least that would explain why the favicon is not requested again in the homepage when new feed requests are made.

> Anyway, the cache is used, as expecter. Isn't it?

I am not really sure:

![capture du 2017-03-01 11-33-01](https://cloud.githubusercontent.com/assets/1192331/23456278/127b725a-fe73-11e6-9eb5-4cb157bc5894.png)

**Comment by brunobesson** [comment]
>I am not really sure

This is fine on my side. Can you check that `Disable cache` box isn't check in your network tab?

![movement1](https://cloud.githubusercontent.com/assets/2234024/23456407/936b114a-fe73-11e6-9933-9313e829d50c.png)

**Comment by asaunier** [comment]
You're right, I was developping some other feature and forgot to renable the cache :)
Then I guess the behaviour is normal. Closing the issue then, thanks for the tips!
