### ISSUE TITLE
Field missing in cards

### ISSUE THREAD

**Issue by loicperrin** [c2corg/v6_ui#1544]
Extract from https://github.com/c2corg/v6_ui/issues/398#issuecomment-268776765

There are still some problems (according to https://docs.google.com/spreadsheets/d/1W2kEAyGPc7cw9yKe3hyYIMTNgUDLPsFUD0ccTS8jI5Y/edit?pref=2&pli=1#gid=0):

Last Outings associated to Route:
- [ ]  Desktop & Mobile: Quality should be displayed

Route Search:
- [ ]  Mobile: pb with ski rating only : Space missing between ski ratings

**Comment by desnoes** [comment]
split in #1548 and #1547
