### ISSUE TITLE
Cards contents: quality icon for outings associated to Route

### ISSUE THREAD

**Issue by desnoes** [c2corg/v6_ui#1547]
Quality icon should be displayed for outings associated to Route

**Comment by asaunier** [comment]
PR https://github.com/c2corg/v6_ui/pull/1562 adds the quality icon to the associated docs back:

![capture du 2017-03-22 10-55-45](https://cloud.githubusercontent.com/assets/1192331/24192120/3de5c48c-0eee-11e7-89bb-d3a472f95ef6.png)

The change above impacts all document types, not only the outings cards.
It is more consistent (why showing the quality icon only for outings cards and not for other associated docs such as routes, books or waypoints?). 

Please note though that it sometimes introduces a conflict with the "remove association" icon (trash can), both icons being superposed:

![capture du 2017-03-22 10-55-14](https://cloud.githubusercontent.com/assets/1192331/24192307/bc35b126-0eee-11e7-8bc6-c11f8556ae48.png)

@desnoes @stef74 What do you think?

**Comment by desnoes** [comment]
@asaunier : that's fine for me. Thanks!

**Comment by desnoes** [comment]
ok on demo
