### ISSUE TITLE
Card content: insert GPS icon

### ISSUE THREAD

**Issue by desnoes** [c2corg/v6_ui#1549]
When a route or an outing contains a GPS track, an icon should be inserted in the card. (Location TBD)

See also the images counter issue at https://github.com/c2corg/v6_ui/issues/1780

**Comment by asaunier** [comment]
Proposed solution: add a boolean "has_track" attribute set to true when the ``geom_detail`` is set (no need to transfer the whole geometry when listing cards).
TODO:

common:
* add the attribute in the list of attributes https://github.com/c2corg/v6_common/blob/master/c2corg_common/fields_outing.py#L42 and https://github.com/c2corg/v6_common/blob/master/c2corg_common/fields_route.py#L32

UI:
* upgrade the "common" requirement
* show icon in the outing/route cards if data is 1 => update the card partials + CSS

API:
* upgrade the "common" requirement
* add a boolean "has_track" attribute to the outing and route models (not needed in the archives? in the ``DocumentGeometry`` part or in the root ``Document`` one? perhaps easier and more relevant in the geometry part itself?!)
* set it to true when a detail geometry is added to the outing/route document
* if the detail geometry is removed, set the attribute to false
* create an alembic script to add the attribute and set it to true for existing outings/routes with a detail geometry

**Note: perhaps an actual boolean attribute is not needed in the tables, it could be replaced by a "fake" attribute automatically/on the fly set to true depending if ``geom_detail`` is not null.**

**Comment by tsauerwein** [comment]
> Note: perhaps an actual boolean attribute is not needed in the tables, it could be replaced by a "fake" attribute automatically/on the fly set to true depending if geom_detail is not null.

For example like here:
https://github.com/c2corg/v6_api/blob/9f97ed5b643e6097680e767876cfd1b70c86f3bb/c2corg_api/models/feed.py#L57-L62
https://github.com/c2corg/v6_api/blob/e783fe73fa224adb3358d499a61e987a7ba4fb3c/c2corg_api/views/feed.py#L165-L169

See also: http://docs.sqlalchemy.org/en/latest/orm/mapped_sql_expr.html#using-column-property

**Comment by asaunier** [comment]
> For example like here:

Thanks! Yes, something like ``column_properties`` indeed. I wonder if it would trigger a SELECT request for every item returned by the list queries?

**Comment by tsauerwein** [comment]
> I wonder if it would trigger a SELECT request for every item returned by the list queries?

The `column_property` could be defined as:
```
DocumentGeometry.has_geom_detail = column_property(
    DocumentGeometry.geom_detail != None,
    deferred=True
)
```
(similar to [DocumentGeometry.lon_lat](https://github.com/c2corg/v6_api/blob/596440e/c2corg_api/models/document.py#L404-L406))

In this case no sub-select should be made.

**Comment by asaunier** [comment]
@tsauerwein Really cool, thanks :)

**Comment by asaunier** [comment]
> The column_property could be defined as:
DocumentGeometry.has_geom_detail = column_property(
    DocumentGeometry.geom_detail != None,
    deferred=True
)

Using 
```
DocumentGeometry.has_geom_detail = column_property(
    DocumentGeometry.geom_detail is not None)
```
does not work as expected and causes the following error:
```
    DocumentGeometry.geom_detail is not None)
  File "<string>", line 2, in column_property
  File "/home/alex/v6_api/.build/venv/lib/python3.4/site-packages/sqlalchemy/orm/properties.py", line 120, in __init__
    self._orig_columns = [expression._labeled(c) for c in columns]
  File "/home/alex/v6_api/.build/venv/lib/python3.4/site-packages/sqlalchemy/orm/properties.py", line 120, in <listcomp>
    self._orig_columns = [expression._labeled(c) for c in columns]
  File "<string>", line 1, in <lambda>
  File "/home/alex/v6_api/.build/venv/lib/python3.4/site-packages/sqlalchemy/sql/elements.py", line 4144, in _labeled
    return element.label(None)
AttributeError: 'bool' object has no attribute 'label'
```

(ditto with ``deferred=True``)

``column_property`` seems to expect ``Column`` parameter and not support a boolean:
http://docs.sqlalchemy.org/en/latest/orm/mapping_columns.html#sqlalchemy.orm.column_property
