### ISSUE TITLE
Image and WP deletion 

### ISSUE THREAD

**Issue by desnoes** [c2corg/v6_ui#1552]
It is impossible to delete some images or WP. The message "unexpected error : please consult the server logs" is displayed.
examples:
- https://www.camptocamp.org/images/836367/fr/-
- https://www.camptocamp.org/images/830790/fr/voies-de-la-face-ne-du-rocher-culasson
- https://www.camptocamp.org/waypoints/835726/fr/-

**Comment by asaunier** [comment]
Is it possible to reproduce the error on the demo?
Could you figure out something special with those documents? For instance I see that the images seem to be associated to no other document?

**Comment by desnoes** [comment]
> For instance I see that the images seem to be associated to no other document?

It seems to be a correct guess. I delete the association of an image with an outing and i was able to reproduce the bug.
Image on demo: http://www.demov6.camptocamp.org/images/828457/en/-

**Comment by asaunier** [comment]
Another image I could not delete (the reason is not explicit):
https://www.camptocamp.org/images/861119/fr/de-la-pointe-de-bellevue-au-loin-le-lac-leman

![sans titre](https://cloud.githubusercontent.com/assets/1192331/23988449/9eec31a4-0a2e-11e7-8331-e4c30ddcc875.png)

**Comment by fbunoz** [comment]
On [this outing](https://www.camptocamp.org/outings/861730/fr/grand-ferrand-voie-du-chourum-olympique), the 5 photos was duplicated.
5 photos had been able to be deleted, but some photos generated an error (then I'd be able to delete the other).
But a problem is that on the outing, some duplicated photo always appear in the image list.

**Comment by arnaud-morvan** [comment]
Concerning the outing above, the image title is "1" and this url match with this route : "/images/{id}/{lang}/{version_id}".

**Comment by arnaud-morvan** [comment]
Concerning : https://www.camptocamp.org/images/836367/fr/-
I get this error in the log : Key (document_id)=(836367) is still referenced from table "feed_document_changes"

**Comment by arnaud-morvan** [comment]
Concerning the way point : https://www.camptocamp.org/waypoints/835726/fr/-
I get : Key (document_id)=(835726) is still referenced from table "routes_archives"

**Comment by arnaud-morvan** [comment]
I've openned another issue for the overlapping routes : #1589

**Comment by desnoes** [comment]
It seems to be ok on demo, but it is hard to reproduce the bug and hence test.
