### ISSUE TITLE
Vandalism detection

### ISSUE THREAD

**Issue by fjacon** [c2corg/v6_ui#1554]
@desnoes  We need to have a clearer spec on vandalism detection.

Interesting, we have now the possibility to see recent changes done by a user like this :
https://www.camptocamp.org/whatsnew#u=377
https://api.camptocamp.org/documents/changes?u=377

Surely a good starting point but how do we decide someone is a vandal ?

**Comment by asaunier** [comment]
See also the API issue at https://github.com/c2corg/v6_api/issues/9

**Comment by desnoes** [comment]
Here is a list of requirements
- [ ] the vandalism detection mechanism should be implemented on the API side
- [ ] send an alert if N modifications in X minutes (vandalism from robots) 
- [ ] send an alert if M modifications in Y hours (vandalism of a new account (e.g. Reymond))

To be discussed: do we need to automatically block an account if it deletes or disassociates more than M modifications in Y hours or simply send an alert to moderators and board?

**Comment by cbeauchesne** [comment]
Fixed by daily bot check, rate limiting on API and enhanced whatsnew
