### ISSUE TITLE
Add a tool to remove a linguistic version of a document

### ISSUE THREAD

**Issue by asaunier** [c2corg/v6_ui#1555]
See API issue at https://github.com/c2corg/v6_api/issues/645

TODO:
* add a new entry in the "plus" dropdown next to the "delete document" entry (moderators only) https://github.com/c2corg/v6_ui/blob/master/c2corg_ui/templates/helpers/view.html#L594-L595
* extend the ``app-delete-document`` directive to add an optional lang parameter https://github.com/c2corg/v6_ui/blob/master/c2corg_ui/static/js/deletedocument.js
* update the existing deletion modal window to show that only the locale will be deleted (if no the only one available)
* pass the optional lang parameter to ``deleteDocument`` method in the ``apiservice`` and call the API URL accordingly https://github.com/c2corg/v6_ui/blob/master/c2corg_ui/static/js/apiservice.js#L719-L730

**Comment by desnoes** [comment]
I cannot delete this version of a route : http://www.demov6.camptocamp.org/routes/828490/en/chamechaude-essai-en. Same thing with the italian version : http://www.demov6.camptocamp.org/routes/828490/it/essi-it

WP: same pb with http://www.demov6.camptocamp.org/waypoints/828492/en/essai-en

I did the following experiment:

- i've created a WP (http://www.demov6.camptocamp.org/waypoints/828493/fr/toto-sommet) in french.
- i've created an english version of this document and then deleted it successfully.
- i've created an italian version, and then tried to delete. It was not possible (error message).

It seems it is not possible to delete more than one linguistic version of a document.

**Comment by arnaud-morvan** [comment]
This may be due to the ESDeletedLocale primary key, this table is not purged.

**Comment by asaunier** [comment]
@desnoes @arnaud-morvan Arf, right, the primary key is incorrect.
I have created an issue about this https://github.com/c2corg/v6_api/issues/653 and will make a PR soon.

Thanks for testing :)

**Comment by asaunier** [comment]
PR is available here https://github.com/c2corg/v6_api/pull/654

**Comment by asaunier** [comment]
The PR is now finalized and ready for review.
In my instance it is now possible to delete several locales (linguistic versions) of the same document, following the steps described by @desnoes at https://github.com/c2corg/v6_ui/issues/1555#issuecomment-293480695

**Comment by desnoes** [comment]
ok on demo
