### ISSUE TITLE
Allow contributors to delete personal document <24h

### ISSUE THREAD

**Issue by asaunier** [c2corg/v6_ui#1556]
Make the "delete document" entry in the "plus" button appear for
* personal documents (including outings??)
* created by the current user (for outings: also for associated users?)
* created less than 24h ago

TODO
* Replace the ``isModerator`` test at https://github.com/c2corg/v6_ui/blob/master/c2corg_ui/templates/helpers/view.html#L594 by ``userCtrl.hasEditRights('${doctype}', ${options})`` as for the editing button https://github.com/c2corg/v6_ui/blob/master/c2corg_ui/templates/helpers/view.html#L555-L560 if the document is personal
* Add the creation time (<24h) as additional condition if not a moderator

Problems:
* the document creation time is not available in the view document API request. It's only available in the history request https://github.com/c2corg/v6_api/blob/master/c2corg_api/views/document_history.py#L15 => do we really want to make an additional request for this? Or do we show the action button anyway (no time checking) and let the API returns an error if the deadline is reached? What about skipping this document age limit and let contributors remove any of their personal documents?

**Comment by fjacon** [comment]
@desnoes  is this functionality really necessary ? 
Why can't we allow people to delete their personal doc anytime ?

**Comment by desnoes** [comment]
@fjacon : i've started a discussion with the association to have more information.

**Comment by desnoes** [comment]
@fjacon : this demand comes fom the following requirement. It happens many time that users upload 2 times the same image or 2 friends create the same outing. In these situation, it is useful to allow these users to correct their error in a short delay. This reduces the moderators work. 
On the other hand, the delay shall not be too long to avoid vandalism. It already happened that a user decide to delete all its entries to the topoguide. This situation must be handled differently because the input of this user may be shared with others or combined. In a nutschell, this must be handled on a case by case basis. In this situation a user shall not be capable to delete all his entries, this must be done by a moderator. 

Note that 'personnal' means a document with the  CC by-nc-nd licence.

**Comment by desnoes** [comment]
> Or do we show the action button anyway (no time checking) and let the API returns an error if the deadline is reached?

This solution is fine for me. The error message should be explicit.

**Comment by asaunier** [comment]
@desnoes Who should be allowed to delete a personal document (except moderators)?
* only the document creator (author of the initial version of the document)?
* any associated user (especially for outings)?

**Comment by asaunier** [comment]
@desnoes has just confirmed that

> only the document creator (author of the initial version of the document)

**Comment by desnoes** [comment]
@asaunier : i confirm!

**Comment by desnoes** [comment]
Delete personnal image (< 24h): ok
Delete collaborative image: ok (not possible)
Delete new outing - deletion asked by the creator (< 24h): ok
Delete new outing - deletion asked by a contributor who is not the creator(< 24h): ok (not possible)
Delete new route(< 24h): ok (not possible)
Delete new WP(< 24h): ok (not possible)
Delete collaborative article(< 24h): ok (not possible)
Delete personnal article(< 24h): ok

Delete personnal image (> 24h): ?
Delete created outing  (> 24h): ?
Delete personnal article(> 24h): ?

**Comment by celinestern** [comment]
Delete new outing - deletion asked by the creator (< 24h) with someone else associed to the outing: not possible

**Comment by desnoes** [comment]
Outing impossible to delete (maybe due to the different versions) : http://www.demov6.camptocamp.org/outings/828587/fr/test-supp-sortie-mont-blanc

**Comment by asaunier** [comment]
@desnoes @celinestern Thanks for reporting the problem! I think it's always the same error occuring with documents having several versions.
I have proposed a fix at https://github.com/c2corg/v6_api/pull/661
