### ISSUE TITLE
Outings' conditions displayed in map

### ISSUE THREAD

**Issue by desnoes** [c2corg/v6_ui#1557]
NOTE:  Picto = picto used for outings being or not colored

Objective: display the field 'conditions rating' of an outing on the map.

- If a user select more than one activity => the uncolored picto is displayed (as it is done currently) (TBC)
- If a user select one activity => a colored picto is displayed:
        Excellent: blue 100%
        Good: blue 50%
        Average : yellow
        poor: red 50%
        Awful: red 100%
   
cf. discussion on forum: https://forum.camptocamp.org/t/carto-picto-conditions/177789/69

**Comment by asaunier** [comment]
> If a user select more than one activity => the uncolored picto is displayed

Same question than at https://github.com/c2corg/v6_ui/issues/1558#issuecomment-287314375: why having several activities would prevent from showing colored icons on the outings maps?

**Comment by desnoes** [comment]
> why having several activities would prevent from showing colored icons on the outings maps?
You don't know to which activity the conditions rating is applied. For instance, excellent conditions for hikking could be awful for skiing.

**Comment by asaunier** [comment]
> You don't know to which activity the conditions rating is applied.

But then why allowing the user to set the condition rating in the outing (and displaying it in the final document) when several activities are selected?

Honestly I think this adds unnecessary complexity.

**Comment by desnoes** [comment]
> Honestly I think this adds unnecessary complexity.

Ok, then drop this requirement.

**Comment by stef74** [comment]
ok
