### ISSUE TITLE
Outing' conditions in cards

### ISSUE THREAD

**Issue by desnoes** [c2corg/v6_ui#1558]
Objective: display the field 'conditions rating' of an outing on the card.

Icon : colored circle

- If a user select more than one activity => the icon is not displayed
- If a user select one activity => a colored icon is displayed:
        Excellent: blue 100%
        Good: blue 50%
        Average : yellow
        poor: red 50%
        Awful: red 100%
   
Location of the icon in the card: TBD

**Comment by asaunier** [comment]
This is similar to the quality indicator shown in outing cards. By the way the quality indicator used colored circles before it was changed to a "cheese" picto => perhaps the old way to show the quality data could be used for conditions ratings?
See the changes reverted by https://github.com/c2corg/v6_ui/commit/ff5b51c411bad7504061a2500d4bd00a1ed1487d

> If a user select more than one activity => the icon is not displayed

@desnoes I don't understand why having several activities in the outing would prevent from showing the conditions rating picto? This attribute is not related to the activities, is it?

**Comment by desnoes** [comment]
> why having several activities in the outing would prevent from showing the conditions rating picto? This attribute is not related to the activities, is it?

You don't know to which activity the conditions rating is applied. For instance, excellent conditions for hikking could be awful for skiing.

**Comment by desnoes** [comment]
@asaunier : you can drop the the requirement on multi-activities. All outings are managed the same way.

**Comment by asaunier** [comment]
> Location of the icon in the card: TBD

Any tip about where the icon should be placed?

**Comment by stef74** [comment]
same line than activities. But probably better to wait new card layout to
implement it !

2017-03-17 18:23 GMT+01:00 Alex Saunier <notifications@github.com>:

**Comment by desnoes** [comment]
There are some translation issues that need to be fixed by the association.
I found one bug with the spanish version. I will check whether this is a translation error in Transifex. 

![bug traduction espagnol](https://cloud.githubusercontent.com/assets/19892089/24497586/3eb87e28-153c-11e7-8896-1c2bd803e40b.png)

Would it be possible to have the list of key words used for translation of the field 'conditions' ?

**Comment by desnoes** [comment]
Otherwise, the result is very nice. Good job!

**Comment by asaunier** [comment]
> Would it be possible to have the list of key words used for translation of the field 'conditions' ?

@desnoes Perhaps you mean https://github.com/c2corg/v6_common/blob/master/c2corg_common/attributes.py#L528-L534 ?

**Comment by desnoes** [comment]
@asaunier : no, by 'key word' i mean the string used to tell transifex to replace this string with the translation. For instance '1d_to_3d' which is translated by 'de 1 à 3 jours' in french. I would need the list of those strings to complete the translations. I tried to search them in Transifex by our account is blocked, we need to subscribe.

**Comment by asaunier** [comment]
https://github.com/c2corg/v6_common/blob/master/c2corg_common/attributes.py#L528-L534 are actually the strings pushed to transifex as id of the condition rating values.

> I tried to search them in Transifex by our account is blocked, we need to subscribe.

I have answered by email. Our transifex account is not blocked.

**Comment by desnoes** [comment]
I have corrected the translation issue in spanish.
