### ISSUE TITLE
Incorrect font color in editing forms

### ISSUE THREAD

**Issue by asaunier** [c2corg/v6_ui#1565]
After the recent layout changes, font color of the form inputs are gray in the editing pages:

![capture du 2017-03-22 14-17-48](https://cloud.githubusercontent.com/assets/1192331/24199652/c19c4c58-0f0a-11e7-9e81-56b7f28c2a36.png)

In prod, only the placeholder texts (tips) are gray, actual content is black:

![capture du 2017-03-22 14-22-48](https://cloud.githubusercontent.com/assets/1192331/24199740/0cb74b7a-0f0b-11e7-8765-70ca3e587b62.png)

**Comment by asaunier** [comment]
Fixed by https://github.com/c2corg/v6_ui/pull/1449

**Comment by desnoes** [comment]
fixed on demo
