### ISSUE TITLE
Incorrect card width in advanced search

### ISSUE THREAD

**Issue by brunobesson** [c2corg/v6_ui#1569]
Again, I apologize not to be able to help you on the subject currently, but the latest changes have broken many things I had taken time to work on. E.g. we now have cards with different sizes in the advanced search:
![movement2](https://cloud.githubusercontent.com/assets/2234024/24443222/09b70cb0-1462-11e7-9a37-0b052cd3642b.png)

**Comment by stef74** [comment]
The new design for me fix this issue.

**Comment by asaunier** [comment]
@brunobesson Rather look at the demo. The layout in prod is already outdated.

**Comment by asaunier** [comment]
Closing the issue because the problem can no longer be reproduced in demo or prod.
