### ISSUE TITLE
Cors for picture

### ISSUE THREAD

**Issue by Webfit-project** [c2corg/v6_ui#1572]
CORS is not support for picture on media.camptocamp.org and forum.camptocamp.org.

Example of url :
https://media.camptocamp.org/c2corg_active/1490822742_505480674BI.jpg
https://forum.camptocamp.org/user_avatar/forum.camptocamp.org/courgette/36/3187_1.png

**Comment by desnoes** [comment]
@Webfit-project : is it a blocking point ? (i am not a technical expert, as you may have seen !)

**Comment by Webfit-project** [comment]
Yes to load images without intermediate page that provide the cors. Currently we have made a page that loads the c2c images that the application uses but its better if c2c had the good headers.

**Comment by cbeauchesne** [comment]
I think this is fixed. @Webfit-project feel free to reopen if I'm wrong
