### ISSUE TITLE
Missing associated images for area documents

### ISSUE THREAD

**Issue by asaunier** [c2corg/v6_ui#1583]
It seems associated images are not shown in area documents view pages.
For instance: https://www.camptocamp.org/areas/14454/fr/alpes-juliennes

On the other hand:
* the API actually returns associated images for this document: https://api.camptocamp.org/areas/14454
* the area view template has an associated images section: https://github.com/c2corg/v6_ui/blob/master/c2corg_ui/templates/area/view.html#L81-L84

**Comment by desnoes** [comment]
ok on demo
