### ISSUE TITLE
Routes : image_view with integer slug overlap with images_archive

### ISSUE THREAD

**Issue by arnaud-morvan** [c2corg/v6_ui#1589]
Exemple : https://www.camptocamp.org/images/861752/fr/1
As slug is "1", this url match with : 
images_archive               /images/{id:\d+}/{lang}/{version:\d+}
images_view                  /images/{id:\d+}/{lang}/{slug}

**Comment by arnaud-morvan** [comment]
@alex : I propose to add a token in images_archive route, for example: 
/images/{id:\d+}/{lang}/**version**/{version:\d+}
This may have consequences on the ui side.

**Comment by asaunier** [comment]
> I propose to add a token in images_archive route, for example:
/images/{id:\d+}/{lang}/version/{version:\d+}

That makes sense to me.

> This may have consequences on the ui side.

For sure. For instance: https://github.com/c2corg/v6_ui/blob/master/c2corg_ui/__init__.py#L78-L79
Perhaps only updating the route definitions is enough?

**Comment by desnoes** [comment]
@arnaud-morvan @asaunier : i don't know how to test this issue on demo. Do you have an idea ? Or should we close the issue and reopen it if needed?

**Comment by arnaud-morvan** [comment]
Way to reproduce : create an image with title ~ integer, for example "1".
If you can open the image detail view, everything should be good.

**Comment by desnoes** [comment]
ok on demo
