### ISSUE TITLE
Egg generation by Makefile

### ISSUE THREAD

**Issue by gberaudo** [c2corg/v6_ui#160]
Does anyone know what the egg targets in the Makefile are supposed to do?

I would expect the `$(SITE_PACKAGES)/c2corg_ui.egg-link` target to create an
`.build/venv/lib/python3.4/site-packages/c2corg_ui.egg-link` file, but it is currently not the case.

Is there something broken?

**Comment by asaunier** [comment]
@gberaudo is this issue still valid?
