### ISSUE TITLE
Remove location in associated document

### ISSUE THREAD

**Issue by stef74** [c2corg/v6_ui#1602]
Location is not needed in associated document

**Comment by asaunier** [comment]
What do you call "location"? Could you provide an example screenshot?

**Comment by stef74** [comment]
Location is the v6 code is area. I'm currently taking a screenshoot

2017-04-27 10:45 GMT+02:00 Alex Saunier <notifications@github.com>:

**Comment by stef74** [comment]
![with](https://cloud.githubusercontent.com/assets/3962997/25475806/49ec7166-2b38-11e7-93e5-eb6b71bbcacf.PNG)
![without](https://cloud.githubusercontent.com/assets/3962997/25475807/4a0fbd10-2b38-11e7-8591-e82c1d97316b.PNG)

**Comment by desnoes** [comment]
OK on demo
