### ISSUE TITLE
Use EN strings in activities contextual help partial

### ISSUE THREAD

**Issue by asaunier** [c2corg/v6_ui#1605]
See https://github.com/c2corg/v6_ui/blob/master/c2corg_ui/static/partials/contexthelp/activities.html

**Comment by desnoes** [comment]
@asaunier @arnaud-morvan : i will do find the translation this week-end

**Comment by asaunier** [comment]
@desnoes I have retrieved the strings from v5 at http://c2ci18n.appspot.com/translations/edit/1459

![capture du 2017-04-28 14-56-21](https://cloud.githubusercontent.com/assets/1192331/25529544/e3c3dc8a-2c22-11e7-8f05-5aca3220e71a.png)

Please note that in v5 this contextual help was translated as a single string, with HTML tags embedded in the translations.

In the current case, this contextual help is an HTML file itself containing strings that are independently translated in Transifex, making thing less confusing for translators. The downside is that the whole help text cannot be changed without editing the code at https://github.com/c2corg/v6_ui/blob/8563ebd4743b400df739db129d1f3f1bcf610879/c2corg_ui/static/partials/contexthelp/activities.html

**Comment by asaunier** [comment]
Please note this contextual help might be improved, for instance by adding the activity icons (text only as for now).
