### ISSUE TITLE
Poor cards rendering in guidebook home page on mobile

### ISSUE THREAD

**Issue by desnoes** [c2corg/v6_ui#1623]
The picture is self explaining.
Chrome (last version)

![screenshot_20170505-074444](https://cloud.githubusercontent.com/assets/19892089/25736987/9073f8c8-3175-11e7-9105-e98f4b714e04.png)

**Comment by stef74** [comment]
@desnoes honestly we can manage it by yourself.

**Comment by desnoes** [comment]
@stef74 : ok, i removed the label bug_SA
