### ISSUE TITLE
Dates in outing cards are not translated

### ISSUE THREAD

**Issue by asaunier** [c2corg/v6_ui#1635]
<img width="439" alt="capture d ecran 2017-05-07 a 14 15 50" src="https://cloud.githubusercontent.com/assets/1192331/25781194/c8aa565c-3336-11e7-8664-de6515a3129c.png">
<img width="333" alt="capture d ecran 2017-05-07 a 14 16 52" src="https://cloud.githubusercontent.com/assets/1192331/25781195/c8aed236-3336-11e7-8122-0cea1eb06d90.png">

**Comment by asaunier** [comment]
The reason is that Moment.js, used for formatting dates, returns capitalized month codes (eg. "Feb", "Aug") when using ``MMM`` at https://github.com/c2corg/v6_ui/blob/master/c2corg_ui/static/partials/cards/outings.html#L6

We actually have translation for lowercased month codes:
https://github.com/c2corg/v6_ui/blob/master/c2corg_ui/templates/i18n.html#L349-L361
but not for capitalized ones.

**Comment by asaunier** [comment]
PR is merged, dates are now translated in the homefeed and in the advanced search results. Translation is for some reason not done in associated documents sections of document view pages (as explained in the PR).

**Comment by desnoes** [comment]
The date is not translated when i select another language. Is it a normal behavior ?

**Comment by asaunier** [comment]
> The date is not translated when i select another language. 

Probably because we use one-time binding (``::``) for displaying the date infos:
https://github.com/c2corg/v6_ui/blob/master/c2corg_ui/static/partials/cards/outings.html#L5-L7
```
{{ ::doc['date_end'] | date: 'MMM' | lowercase | translate | limitTo: 3}}
```
One-time binding is used for data that are shown once for all (no change), it reduces the load on the browser. The downside is that changes are not taken into account.
Is it really a problem? People don't change language that often and the next time the page is loaded, the translation is OK.

**Comment by desnoes** [comment]
> Is it really a problem? People don't change language that often and the next time the page is loaded, the translation is OK.

No, it is clearly not a real problem. I juste asked this question to check this is a normal beahvior. I close the issue.
