### ISSUE TITLE
Image file uploader

### ISSUE THREAD

**Issue by asaunier** [c2corg/v6_ui#164]
We need a JS tool to select/drag-drop 1 or more images and upload it to the API images webservice.
~~(By the way could it be used for uploading GPX files as well, or would the GPX files be directly parsed in JS and added to the editing JSON request?).~~

Some interesting libs:
- [flow.js](https://github.com/flowjs/flow.js) and its angular extension: [ng-flow](https://github.com/flowjs/ng-flow) ([demo](http://flowjs.github.io/ng-flow/))
- [ng-file-upload](https://github.com/danialfarid/ng-file-upload) ([demo](https://angular-file-upload.appspot.com/))
- [ngDroplet](https://github.com/Wildhoney/ngDroplet) ([demo](http://ng-droplet.herokuapp.com/))

**Comment by tsauerwein** [comment]
> (By the way could it be used for uploading GPX files as well, or would the GPX files be directly parsed in JS and added to the editing JSON request?).

The GPX files can be parsed in JS. The user could then directly edit the track, for example.

**Comment by asaunier** [comment]
> The GPX files can be parsed in JS. The user could then directly edit the track, for example.

You mean that the user would push his GPX file, the geometry would then be directly shown on the map without any server action and the user could then modify the geometry before pushing to the API.
That would rock!

**Comment by asaunier** [comment]
Tool used in v5: http://www.plupload.com/

**Comment by asaunier** [comment]
In v5 [Plupload](http://www.plupload.com/)  is used and seems to be satifactory because:
* users may drag-drop one or more images at a time
* they can also select files by browsing in the file system
* it provides a per-file loading bar as well as a thumbnail when the image is uploaded
* it relies on HTML5 APIs such as FileAPI
* files are uploaded in small chunks
* big images can be resized before uploading

Angular directives based upon plupload are available:
* https://github.com/sahusoftcom/plupload-angular-directive but marked as "no longer maintained". See demo and doc at http://sahusoftcom.github.io/plupload-angular-directive/
* https://github.com/remotty/angular-plupload but seems not very active
* others but not very active either => maybe everything is done in plupload and the angular directive does not need much changes?

We have also alternate solutions, the main ones that I have found:

[ng-file-upload](https://github.com/danialfarid/ng-file-upload) ([demo](https://angular-file-upload.appspot.com/)) which is pretty active and has plenty of nice features:
- file **upload progress**, cancel/abort
- file **drag and drop**
- **image resize** and center crop (native) and user controlled crop through ngImgCrop.
- **orientation fix** for jpeg image files with exif orientation data
- resumable uploads: pause/resume upload
- native validation support for file type/size, image width/height/aspect ratio, video/audio duration, and ng-required with pluggable custom sync or async validations.
- **show thumbnail or preview** of selected images/audio/videos
- supports CORS and direct upload of file's binary data using Upload.$http()

[flow.js](https://github.com/flowjs/flow.js) and its angular directive [ng-flow](https://github.com/flowjs/ng-flow) ([demo](http://flowjs.github.io/ng-flow/)), pretty active too
> providing multiple simultaneous, stable, fault-tolerant and resumable/restartable file uploads via the HTML5 File API
- Pause/Resume upload
- Recover lost upload
- Error handling
- Drag and Drop with folder reader
- Drop area animation
- Custom upload buttons
- Folder Upload
- Queue management
- Image preview
- File validation
- Upload progress
- Chunk uploads
=> pretty like the same features than for ng-file-upload (except the client-side image resizing?)
See https://github.com/flowjs/ng-flow#how-can-i-drop-files for details

**Comment by asaunier** [comment]
@mfournier recommends to use a S3 or S3-like storage for the images.
Which means we need to support the S3 upload protocol.
Plupload does: http://www.plupload.com/docs/Upload-to-Amazon-S3
ng-file-upload too: https://github.com/danialfarid/ng-file-upload#s3
flow.js seems not: https://github.com/flowjs/flow.js/issues/22#issuecomment-45470440

As far as I can see, ng-file-upload seems a good compromise in terms of:
* features (including S3)
* angular use
* project activity

**Comment by asaunier** [comment]
A point that must be discussed is weither the upload script should push images directly to S3 from the user browser or if only the UI server should be allowed to do so.

## Security issue

Are we 100% sure that no one will be able to push unauthorized content to our bucket?

Plupload and ng-file-upload allow to directly push to S3 and may provide base64-encoded policy and signature. For instance: https://github.com/danialfarid/ng-file-upload#amazon-aws-s3-upload

I'm just wondering if it's not possible to get the policy and signature from the upload tool and reuse it for bad usage? _[actually it seems possible to get a temporary signature from the server side that will authenticate the request to S3?]_

See this article [Browser Uploads to S3 using HTML POST Forms](http://aws.amazon.com/articles/1434/) for info about policy, signature etc.

Se also https://devcenter.heroku.com/articles/s3-upload-python

## Image manipulating

=> to create resized versions of the uploaded images

**Option 1**: resized image copies are created on the API (or some other c2corg server).
If the original image is directly uploaded to the bucket, the system will have to get it back from the bucket, create the resized versions and push them to the bucket.
=> seems not that optimal => in that case it is probably better to make the user browser upload the image to the API and let the API make PUT request to the bucket. By the way it would give more control on the bucket since the policy and signature would never be accessible to the client.

S3 interactions can be done using Boto3: https://aws.amazon.com/fr/sdk-for-python/
Boto3 supports all the AWS services: https://boto3.readthedocs.org/en/latest/reference/services/index.html

**Option 2**:  if we can trigger some background actions in the bucket when an image is uploaded, creating resized copies automatically, the API would never have to manipulate those images.

Perhaps by using Amazon EC2 or Lambda:
https://aws.amazon.com/fr/lambda/details/ 
See this tutorial for processing images with Amazon services: http://aws.amazon.com/articles/1602
A blog about converting images using Lambda (with nodejs): http://jice.lavocat.name/blog/2015/image-conversion-using-amazon-lambda-and-s3-in-node.js/

**Comment by tsauerwein** [comment]
One think to keep in mind: We also have to extract the exif metadata from the images. But we could even do that on the client-side with this library: https://github.com/blueimp/JavaScript-Load-Image

**Comment by tsauerwein** [comment]
> See this tutorial for processing images with Amazon services: http://aws.amazon.com/articles/1602

In this case the image is not directly uploaded to S3 from the client-side. It's first uploaded to the web-application, which does the thumbnail creation, and then further on to S3.

> A blog about converting images using Lambda (with nodejs): http://jice.lavocat.name/blog/2015/image-conversion-using-amazon-lambda-and-s3-in-node.js/

This looks interesting, especially the triggers: If a new file is uploaded to a S3, a *lambda* function is called which creates the thumbnails. :+1:

**Comment by asaunier** [comment]
TODO

* [ ] Create a directive that display a drag-drop area
* [ ] Get S3 signature and policy from the API (see https://github.com/c2corg/v6_api/issues/215)
* [ ] Get EXIF info
* [ ] Resize too big images?
* [ ] Upload images to S3
 * [ ] Loading indicator
 * [ ] Preview
 * [ ] "Cancel this image" tool
 * [ ] Rotate images in the upload interface?
* [ ] Rename uploaded images (before sending them to S3? in S3?)
* [ ] Check that the images uploading has succeeded
* [ ] Send the images data (including filenames) to the API

**Comment by asaunier** [comment]
@ginold @fjacon I guess this issue has been addressed and can be closed?

**Comment by ginold** [comment]
there are still 2-3 points that have not been checked. Maybe we can close this one and report the points into another issue.

**Comment by asaunier** [comment]
Among remaining points listed at https://github.com/c2corg/v6_ui/issues/164#issuecomment-204345064
there are:
* Resize too big images => useful to avoid that people upload MB-sized photos (**not a big deal?**). In v5, I think that images bigger > 2MB were automatically resized by the client-side upload JS lib. I think ngFileUpload (that we use) supports this feature too https://github.com/danialfarid/ng-file-upload#-features
* Rotate images in the upload interface? => **nice to have** since it misoriented images are uploaded to v5 now and then. Automatic detection based on EXIF data seems supported by ngFileUpload

**Comment by asaunier** [comment]
Closing because most of the points have been addressed. Perhaps image rotating could be useful (?) but if yes, it's better to create a dedicated issue.
