### ISSUE TITLE
Markdown unit test

### ISSUE THREAD

**Issue by cbeauchesne** [c2corg/v6_ui#1640]
@asaunier I create a separate issue for that, if we agree on the content, I will make a PR.

I propose this : A folder named tests/ that contains files with two behaviors :

* json files with a list of {id, markdown, expected} -> they will contain short md codes. Having several file will help to organize test case
* Couple of file .md and .html (for instance MyTest.md comes with MyTest.html). .md file contains markdown code, .html file contains expected result.

The code will scan entire folder, and will run test on all files. 

Your opinion?

**Comment by asaunier** [comment]
That sounds good to me, thanks!

**Comment by cbeauchesne** [comment]
PR done
