### ISSUE TITLE
cotometer

### ISSUE THREAD

**Issue by Courgetteandratatouille** [c2corg/v6_ui#1644]
i'd like to reproduce the cotometer on this old page : http://www.pre-prod.dev.camptocamp.org/tools/cotometre

What is the good way to do it ?

**Comment by asaunier** [comment]
First thing is to decide where this tool will be available, how it will be displayed (modal box?) and what it does (use cases).

For the implementation, I recommend creating an AngularJS directive with a partial (template) and controller. See for instance the ``app-delete-document`` or ``app-merge-document`` directives that are shown in a modal box:
* https://github.com/c2corg/v6_ui/blob/master/c2corg_ui/static/js/deletedocument.js
* partials: https://github.com/c2corg/v6_ui/tree/master/c2corg_ui/static/partials
* usage: https://github.com/c2corg/v6_ui/blob/bc6606124a9bcdc17114f7614057de55ad649674/c2corg_ui/templates/helpers/view.html#L133

**Comment by Courgetteandratatouille** [comment]
@asaunier 

Little question, how can i select the good value on the select in create/edit route page from the modal ?

**Comment by asaunier** [comment]
@Courgetteandratatouille It's hard to answer without seeing your PR.
I guess it also depends where your tool is made available, for instance if in the route editing form or in a dedicated page that does not require any interaction with another form.

Please note that in the route editing form it should interact with model ``route.ski_rating``
https://github.com/c2corg/v6_ui/blob/master/c2corg_ui/templates/route/edit.html#L489

Perhaps you could make a first version of the tool that does not interact with the form, only suggesting a rating value that the user would have to set by hand in the form. Then an improvement would be to make the tool communicate with the form.

**Comment by Courgetteandratatouille** [comment]
Ok then i make the PR soon and we see later for improve the cotometer.
