### ISSUE TITLE
Store map preference in localstorage

### ISSUE THREAD

**Issue by desnoes** [c2corg/v6_ui#1646]
Store in user's preferences the status of the map (shown/hidden).
Similar to #1618

**Comment by asaunier** [comment]
Please note that the list/card layout setting (see #1618) is not stored in the user's preferences (as the regions and activities of https://www.camptocamp.org/preferences).

It's simply stored in the browser's localStorage, ie. it's not saved to the API and not restored when the user uses another device (mobilephone, PC, tablet, etc.). On the other hand this setting is saved also for non authenticated users.

**Comment by stef74** [comment]
Is very good thing that is not user global setting. Becasue it clearly also depend on the device. On my 27 inch I would show the map every time, on my laptop 13 inch its interresting to not show

**Comment by asaunier** [comment]
@stef74 has merged a PR about that: https://github.com/c2corg/v6_ui/pull/1657
