### ISSUE TITLE
Swapped activity icons for rock_climbing and mountain_climbing?

### ISSUE THREAD

**Issue by asaunier** [c2corg/v6_ui#1652]
In my dev instance (HEAD of master), it seems the icons of activites rock_climbing and mountain_climbing are swapped with each other:
![capture du 2017-05-12 20-04-29](https://cloud.githubusercontent.com/assets/1192331/26010756/7736921a-374e-11e7-95a8-51d47100e1a3.png)

**Comment by tsauerwein** [comment]
Thanks for noticing! The icon files for rock and mountain climbing were not named correctly. That's why I mixed them up when generating the font.

**Comment by asaunier** [comment]
@tsauerwein Thanks!
By the way it seems your previous PR about slacklining fixed the landing area icon issue: https://github.com/c2corg/v6_ui/issues/1386
(and it's still fixed with your new PR) :)
