### ISSUE TITLE
Long titles break the layout in feed cards

### ISSUE THREAD

**Issue by tsauerwein** [c2corg/v6_ui#1655]
Long titles combined with three feed images cause an overflow:

![screenshot from 2017-05-13 08-52-25](https://cloud.githubusercontent.com/assets/266474/26022906/99f262c8-37b9-11e7-95d6-b614c20fe84d.png)

**Comment by stef74** [comment]
The issue will be probably fixe with the new feed design

**Comment by stef74** [comment]
fixed by new design
