### ISSUE TITLE
Translations are sometimes lost in Transifex

### ISSUE THREAD

**Issue by asaunier** [c2corg/v6_ui#1658]
For some unknown reason, from time to tome some translations done in Transifex are lost and should be restored using the translation memory system of Transifex that suggest possible translations based upon previously done translations.
There might be a glitch in the Transifex synchronisation script?

**Comment by asaunier** [comment]
> should be restored using the translation memory system of Transifex that suggest possible translations based upon previously done translations

See the bottom right section in this capture:
<img width="500" alt="capture d ecran 2017-05-14 a 09 00 26" src="https://cloud.githubusercontent.com/assets/1192331/26031891/0342dbc0-3884-11e7-93b9-7de7d2797859.png">
=> to restore a suggested translation, click on the second icon to the right => the suggestion is then added to the editing area and can be saved as is or edited if it is not exactly the correct one.

**Comment by asaunier** [comment]
I have noticed that some strings from pending branches (unmerged PRs) are (sometimes?) unexpectedly pushed to Transifex.

For instance currently strings ``Hide Map`` and ``Show Map`` are listed in Transifex
![capture du 2017-06-02 11-33-31](https://cloud.githubusercontent.com/assets/1192331/26720172/7cd66486-4787-11e7-87ad-d18911f76d12.png)
whereas they are only available in the unmerged branch ``save-map`` (see PR https://github.com/c2corg/v6_ui/pull/1657).

I think only strings from branch master should be pushed to Transifex. Perhaps we should make sure Travis runs the ``transifex-send`` target only for branch master?
https://github.com/c2corg/v6_ui/blob/master/.travis.yml#L58

**Comment by brunobesson** [comment]
Finally you're aknowledging I was right when I explained that some of my translations were overwritten? :laughing:

**Comment by asaunier** [comment]
In Transifex we have never marked translated strings as "revised". I wonder if "revised" strings are impacted by this instability? Perhaps marking translated strings as revised would solve the problem?

**Comment by asaunier** [comment]
@desnoes had marked all french translations as "revised" a few weeks ago to see if it would prevent from "losing" translations. I have just had a look at Transifex and at least 16 strings were lost (I have restored them) which means revising strings does not help.

**Comment by desnoes** [comment]
@asaunier: bad news !

**Comment by asaunier** [comment]
Travis is triggered whenever a branch is updated on github. According to https://github.com/c2corg/v6_ui/blob/master/.travis.yml#L56-L58 a push to Transifex is done when Travis tests pass, whatever the branch.

@arnaud-morvan do you think it is possible to have this action done only for the master branch? It's not relevant to push strings from branches until they have actually been merged.

**Comment by arnaud-morvan** [comment]
It should be possible to test $TRAVIS_BRANCH : https://docs.travis-ci.com/user/environment-variables/#Default-Environment-Variables
