### ISSUE TITLE
Image upload

### ISSUE THREAD

**Issue by desnoes** [c2corg/v6_ui#1662]
There are numerous feedbacks about bugs during upload of images. See this discussion: https://forum.camptocamp.org/t/impossible-dinserer-une-photo/176600/33

Either some people have a time out message (low data rate connection ?) or when people click on the save button nothing happens (Firefox 53.0.2 (32 bits).

**Comment by asaunier** [comment]
> Either some people have a time out message (low data rate connection ?)

See https://github.com/c2corg/v6_images/issues/32
https://github.com/c2corg/v6_ui/issues/929#issuecomment-266725534

> when people click on the save button nothing happens

The request takes quite a while when a lot of images are uploaded at once: https://github.com/c2corg/v6_api/issues/569

Please note there is a small spinning wheel in the middle of the screen appearing while the request is in progress. Perhaps it is not visible enough?

**Comment by stef74** [comment]
@desnoes still valid ?

**Comment by desnoes** [comment]
@stef74 : yes

**Comment by stef74** [comment]
I relay on forum ...

**Comment by mfournier** [comment]
I applied the changes to production just now. I hope we'll be able to close this issue after confirming the fix works as it should !
