### ISSUE TITLE
Images slideshow

### ISSUE THREAD

**Issue by asaunier** [c2corg/v6_ui#167]
A slideshow is needed to watch the images linked to a given document (or to display the image from its own document view page itself?).

The objectives of the slideshow:
* display the image as big as possible
* browse to previous/next image
* display some essential information (for example "title")
* display some additional information like licence, description, author, image type, EXIF when clicking on a "detail" button
* display a link towards the image "document view page"
* show a download button (nice to have)
* image file editing => nice to have in the future maybe but not needed now!
* responsive

Question: do we need a separated document view page?
* in some way yes, for instance for search engine purpose (image view page URL) and to display information that could hardly fit in the slideshow (for instance the map for georefed images), not alone the history/diff pages
* in some other, it would be cool to avoid multiplicating ways (and pages) to display an image (in v5, I'm not sure everyone knows that it is possible to open the image view page by clicking on some icon that shows up when hovering a thumbnail). Especially if most of the info can be display in the slideshow.

A very good example is photos.google.com! See for instance: https://photos.google.com/u/1/photo/AF1QipO5mqKNzq4Z1yBG0UeL24N98QdRmNPnY_FG7XBi
* every single image has its own URL in the slideshow
* info are available by clicking on a button (and the data presentation is really smart, very compact)
* it's possible to edit infos directly

**Comment by asaunier** [comment]
AngularJS slideshows:
* [ngGallery](http://demo.jankuri.com/ngGallery/)
* [angular-flexslider](https://github.com/thenikso/angular-flexslider) (based on [FlexSlider](http://flexslider.woothemes.com/index.html)

See also
* https://github.com/lokesh/lightbox2/
* https://github.com/sachinchoolur/lightGallery ([demo](http://sachinchoolur.github.io/lightGallery/))
* [OWL Carousel](http://owlgraphic.com/owlcarousel/index.html) ([v2](http://www.owlcarousel.owlgraphic.com/))
* https://github.com/revolunet/angular-carousel
* http://www.sitepoint.com/creating-slide-show-plugin-angularjs/

**Comment by ginold** [comment]
this one looks nice too http://kenwheeler.github.io/slick/

**Comment by fjacon** [comment]
We will use a separate document view page for images.
Slideshow will only provide some info and a link to the document page.

**Comment by asaunier** [comment]
@ginold @fjacon I guess this issue has been addressed and can be closed?

**Comment by ginold** [comment]
Those are just infos, I think the most of them have been addressed and it can be closed.
