### ISSUE TITLE
Confusing month translations in the outing cards

### ISSUE THREAD

**Issue by asaunier** [c2corg/v6_ui#1672]
In outing cards, only the first 3 letters of the month names are shown:
https://github.com/c2corg/v6_ui/blob/master/c2corg_ui/static/partials/cards/outings.html#L6

which may be confusing. For instance in French june and july have the same first 3 letters:
![capture du 2017-06-06 09-35-16](https://cloud.githubusercontent.com/assets/1192331/26818625/b5d6e76c-4a9b-11e7-8610-feaa068e0884.png)

**Comment by desnoes** [comment]
Proposition: JUN for June (latin: Junius, french: Juin) et JUL pour July (Julius/Juillet)

**Comment by asaunier** [comment]
@desnoes I think I have found a simple and efficient solution (#1675)
