### ISSUE TITLE
Preview action

### ISSUE THREAD

**Issue by asaunier** [c2corg/v6_ui#168]
A "preview" action before actually saving an editing form is required (as in v5). The "save" button should be clickable only when the preview has been displayed (to avoid that people create many versions because they have not checked their changes).

**Comment by asaunier** [comment]
The preview being needed when editing a document, we need to use it as a UI AJAX service that would:
* get the attributes from the client UI (without saving them yet)
* generate some HTML using Mako (same renderer and syntax parsers than for the standard detail view)

The generated HTML would then be displayed in the editing flow before allowing to cklick the save button.

**Comment by asaunier** [comment]
Having a preview of the edited document before it is actually saved (at the end of the editing form) is needed so that contributors check their changes (in order to avoid subsequent changes fixing for example formatting errors). In v5 an AJX request is sent to the server that returns some HTML built using  some templates.

Doing so in v6 would be relevant.

The current approach implemented by @ginold is nice. The main downside is that it is not possible to check the final rendering of text attributes with bbcode/markdown formatting.

I was considering we could create a UI webservice that would use the existing ``view.html`` templates, feeding them with the data sent from the editing form instead of the usual API request. The generated HTML/JS code would then be integrated inside the editing form screen.

Several issues though:
* we cannot use the view templates out of the box since some part are not relevant (everything inherited from ``base.html`` + most of the tools like the edit/translate/history buttons etc.). Not sure we should show the associated documents (might be too much stuff in the preview?) even though it would be consistent since the editing form allows to change the associations...
* would the layout behave as expected since the page width will not be the same than in the standard view page => responsiveness issues? Or maybe the layout will adapt out of the box?
* wouldn't this be a bit confusing for contributors to have a preview too similar (!?) to the end view page? I mean that people might think the document is saved whereas it is not?
* would we have conflict between the JS code in the editing form and the preview part?

Should we then:
* display the preview as a separated page when pushing the "preview" button at the end of the editing form? Some ``waypoints/preview`` that would receive the data from the documentediting directive. It would be possible to go back to the editing page, especially if data are changed in the localstorage as in https://github.com/c2corg/v6_ui/issues/250
* stay in the editing page but make the preview webservice use a simplified Mako template with a simplified layout based upon the Mako helpers already used by the view templates?

**Comment by asaunier** [comment]
@tsauerwein Is there a way to define a UI web service / view that would not be cached at all? For instance ``POST waypoints/preview``, that would return some HTML containing the data passed as POST.
Perhaps POST response are never cached anyway?

**Comment by tsauerwein** [comment]
The views explicitly have to be configured to use a cache. And only `GET` should be cached.

**Comment by asaunier** [comment]
Reopening since the following improvements are needed:
* [ ] factorise a bit more the view/preview mako templates? (but since helper functions are used, the common code is not that big)
* [ ] add a loading indicator in the modal box until the preview is actually shown?
* [ ] show map and associations?
* [ ] not sure angular code is correctly executed within the modal preview (for instance it seems that the outing dates are not correctly shown with angular moment and that the interface strings translations does not work)
* [ ] some tests?

**Comment by asaunier** [comment]
> not sure angular code is correctly executed within the modal preview (for instance it seems that the outing dates are not correctly shown with angular moment and that the interface strings translations does not work)

Perhaps the angular code being not executed as expected in the preview is related to an incorrect integration of the HTML provided by the preview service through an Ajax request:
https://github.com/c2corg/v6_ui/blob/ce2996f9c5b3c1314f02f9f66b92aa1e9745b213/c2corg_ui/static/js/documentediting.js#L567
```
$('#preview-container-content').html(response['data']);
```
?

I think I have used this approach because I have not succeeded in making angular "trustAsHtml" the HTML returned by the service => it was always escaped, I think.

**Comment by stef74** [comment]
@asaunier some work allready needed on this ticket ?

**Comment by asaunier** [comment]
Yes, see https://github.com/c2corg/v6_ui/issues/168#issuecomment-245893257
