### ISSUE TITLE
Improve visibility of document translations

### ISSUE THREAD

**Issue by asaunier** [c2corg/v6_ui#1680]
As for now other linguistic versions of a document are available via the "Plus" menu in document view pages. The visibility of this action is pretty poor though.

Perhaps we could add links to the other linguistic version at the top of the document?

Should probably be considered along with the document view page organisation https://github.com/c2corg/v6_ui/issues/1196

**Comment by asaunier** [comment]
The current position of other lang versions is definitely not OK, people not noticing this possibility, rather trying to switch the language using the interface language selector in the top right corner.

Here are feedbacks a dutch user just sent to the dev mailing list:
> * When I google for routes, I only find the french variant of camptocamp (previously this was not the case). It seems that the english variations just don't exist any more?
> * When I change FR to EN settings on the page  (right on top) of a route itself it is not directing me to the EN site.
> * All friends of mine have the same problem. I am wondered that you didn't know about this..

**Comment by desnoes** [comment]
works correctly with routes, waypoints and articles
