### ISSUE TITLE
Handle console.log

### ISSUE THREAD

**Issue by gberaudo** [c2corg/v6_ui#169]
See https://github.com/c2corg/v6_ui/commit/7b6ce29fa29e67fdca61ee003c466bc9bb7a8277#commitcomment-16115370

**Comment by asaunier** [comment]
Are you sure this is the correct commit? I see no connection in it with console.log.

**Comment by gberaudo** [comment]
Fixed

**Comment by fjacon** [comment]
Can we close this ?

**Comment by asaunier** [comment]
Closing this issue since all remaining ``console.log`` are embedded in a ``if (goog.DEBUG) {`` block.
