### ISSUE TITLE
Unsupported L# tags in v6.1.10

### ISSUE THREAD

**Issue by asaunier** [c2corg/v6_ui#1690]
For some reason L# are not correctly supported in release v6.1.10 (v6.1.9 was OK but with a simpler support I think).

It can be observed in the demo. For instance http://www.demov6.camptocamp.org/routes/368130/fr/vallee-d-ailefroide-poire-d-ailefroide-bonne-poire

I have switched the redis cache off on the demo to make sure rendered documents are not retrieved from the cache.

The weird thing seems that sometimes it works, sometimes it doesn't. Well it seems that it works until the dcument is edited, than it's broken.

@olaurendeau Would you have an idea?

**Comment by desnoes** [comment]
Not working:
http://www.demov6.camptocamp.org/routes/826279/fr/haut-de-cry-nemiaz-allah-pero
http://www.demov6.camptocamp.org/routes/826384/fr/la-croix-de-toulouse-paroi-des-salettes-voie-20152016
http://www.demov6.camptocamp.org/routes/825802/fr/rossolino-la-chanson-des-pres-verts

Working:
http://www.demov6.camptocamp.org/routes/825619/fr/le-ponteil-y-a-des-mouches

**Comment by asaunier** [comment]
> Working:
http://www.demov6.camptocamp.org/routes/825619/fr/le-ponteil-y-a-des-mouches

Are you sure?

**Comment by desnoes** [comment]
@asaunier : yes it works ! (Chrome) But this is the only example i can provide :)

**Comment by asaunier** [comment]
In my Chrome it generally does not work (but it has worked once indeed).

**Comment by olaurendeau** [comment]
Hello @desnoes @asaunier 
This is weird indeed, I'll test this on my local environment this morning.
BTW http://www.demov6.camptocamp.org/routes/825619/fr/le-ponteil-y-a-des-mouches is not working for me (Chrome also)

**Comment by olaurendeau** [comment]
Well I didn't get why ...
On my local environment ✅ 
<img width="1114" alt="capture d ecran 2017-06-14 a 11 07 28" src="https://user-images.githubusercontent.com/1516110/27124991-22651540-50f3-11e7-89fc-bb46cb997aee.png">

On demov6 with the same brower it's broken
<img width="1086" alt="capture d ecran 2017-06-14 a 11 07 55" src="https://user-images.githubusercontent.com/1516110/27124953-ffaca072-50f2-11e7-82f8-276b48803775.png">

**Comment by olaurendeau** [comment]
Les wikilinks fonctionnent par contre http://www.demov6.camptocamp.org/routes/564984/fr/cornettes-de-bise-papys-lions

**Comment by brunobesson** [comment]
>so this seems specific to LTags

Is it? Could it be related to #1689 too?
Anyway, in my dev environment, le tags are working properly for Le Ponteil.

**Comment by asaunier** [comment]
> Are we certain that this is master on demov6 ?

Yes. Actually it uses release v6.1.10, wich is a snapshot of master on june, 9th:
https://github.com/c2corg/v6_ui/commits/master

In my local instance (up to date on master):
* http://localhost:6555/routes/825619/fr/le-ponteil-y-a-des-mouches is OK (even after editing the document)
* http://localhost:6555/routes/564984/fr/cornettes-de-bise-papys-lions was KO (L# not parsed, other formatting such as wikilinks OK). I have cleared the server cache (I can't remember if I edited it first) and now it is OK. [tested later: KO, later again : OK]
* http://localhost:6555/routes/56438/fr/cogne-valeille-chandelle-levure remains KO even after clearing the server cache, browser cache and editing the document.
* http://localhost:6555/routes/316655/fr/cogne-valeille-vertigine-di-porcellana was OK but now KO
* I have tried to create a new document with L# => KO [later OK after a server cache clearing]

I cannot really identify a pattern to reproduce the problem. It is very unstable. It seems the parsing is sometimes done, sometimes not.

> Is it? Could it be related to #1689 too?

This problem is weird too. No clue if it is related (both are markdown parsing issues) but at least the problem now occurs all the time in my instance.

**Comment by asaunier** [comment]
I have tried to roll my instance back to release v6.1.9. Perhaps it's by chance but documents are always parsed as expected (videos are still broken with this release though).
Then I suspect something has caused the L# instability after this release.
@olaurendeau Don't you think something in your commit https://github.com/c2corg/v6_ui/commit/9d682a838e48adc063238491542abca7175afc7c could be related? Could we try to disable some of those changes and check if the problem still occurs?

To switch between releases, type for instance ``git checkout v6.1.9``
https://github.com/c2corg/v6_ui/releases

**Comment by asaunier** [comment]
Perhaps a hint: when I run the unit tests on the dev server, I get the following error:
```
======================================================================
FAIL: test_all (c2corg_ui.tests.format.test_format.TestFormat)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/alex/v6_ui/c2corg_ui/tests/format/test_format.py", line 28, in test_all
    do_test(file, text, expected)
  File "/home/alex/v6_ui/c2corg_ui/tests/format/test_format.py", line 18, in do_test
    self.assertEqual(result, expected, id)
nose.proxy.AssertionError: '<h3 [900 chars]p>\n<p>L# | 5b | Nice slab with a slightly har[77 chars]</p>' != '<h3 [900 chars]p>\n<table class="ltag">\n<tbody>\n<tr>\n<td><[291 chars]ble>'
Diff is 1640 characters long. Set self.maxDiff to None to see it. : sample.md
-------------------- >> begin captured logging << --------------------
MARKDOWN: DEBUG: Successfully loaded extension "c2corg_ui.format.wikilinks.C2CWikiLinkExtension".
MARKDOWN: DEBUG: Successfully loaded extension "c2corg_ui.format.img.C2CImageExtension".
MARKDOWN: DEBUG: Successfully loaded extension "c2corg_ui.format.video.C2CVideoExtension".
MARKDOWN: DEBUG: Successfully loaded extension "c2corg_ui.format.important.C2CImportantExtension".
MARKDOWN: DEBUG: Successfully loaded extension "c2corg_ui.format.warning.C2CWarningExtension".
MARKDOWN: DEBUG: Successfully loaded extension "markdown.extensions.nl2br.Nl2BrExtension".
MARKDOWN: DEBUG: Successfully loaded extension "markdown.extensions.toc.TocExtension".
MARKDOWN: DEBUG: Successfully loaded extension "c2corg_ui.format.autolink.AutoLinkExtension".
MARKDOWN: DEBUG: Successfully loaded extension "c2corg_ui.format.ltag.C2CLTagExtension".
--------------------- >> end captured logging << ---------------------
```
No error in my local instance though.

**Comment by olaurendeau** [comment]
@asaunier Do you have the issue on your local instance ?

About your tests :
- http://localhost:6555/routes/56438/fr/cogne-valeille-chandelle-levure Is not supposed to be parsed because of the `L#-+1` tag
- Others examples should be properly parsed

On my local environment (docker-compose with redis activated) I didn't manage to reproduce the issue
Anyway I've added some logs (https://github.com/c2corg/v6_ui/pull/1694) that will display something like this for supported cases
```
ui_1     | 2017-06-15 08:56:27,705 DEBUG [c2corg_ui.views][waitress] API: GET http://api.demov6.camptocamp.org/routes/794986?l=fr
ui_1     | 2017-06-15 08:56:27,708 INFO  [requests.packages.urllib3.connectionpool][waitress] Starting new HTTP connection (1): api.demov6.camptocamp.org
ui_1     | 2017-06-15 08:56:28,157 DEBUG [c2corg_ui.format.ltag][waitress] This block has no ltags and is starting with "## Approche"
ui_1     | 2017-06-15 08:56:28,157 DEBUG [c2corg_ui.format.ltag][waitress] This block has no ltags and is starting with "Prendre depuis Ailefroide le sentier rive droite du torrent de St Pierre puis apr\xe8s un court raidillon au-dessus d&#x27;un torrent, suivre une trace \xe0 gauche dans un pr\xe9, puis suivre les cairns. Le secteur de la Baliverna se trouve juste \xe0 gauche de l&#x27;origine de la vire d&#x27;Ailefroide, \xe0 droite d&#x27;un \xe9boulement blanch\xe2tre. "
ui_1     | 2017-06-15 08:56:28,158 DEBUG [c2corg_ui.format.ltag][waitress] This block has no ltags and is starting with "## Itin\xe9raire"
ui_1     | 2017-06-15 08:56:28,158 DEBUG [c2corg_ui.format.ltag][waitress] This block has no ltags and is starting with "### Derborence (6b obl.)"
ui_1     | 2017-06-15 08:56:28,158 DEBUG [c2corg_ui.format.ltag][waitress] This block has ltags and will be processed and is starting with "L# | 5c | court sur un \xe9peron"
ui_1     | 2017-06-15 08:56:28,159 DEBUG [c2corg_ui.format.ltag][waitress] This block has no ltags and is starting with "## Descente"
ui_1     | 2017-06-15 08:56:28,159 DEBUG [c2corg_ui.format.ltag][waitress] This block has no ltags and is starting with "Descente en 6 rappels plus ou moins dans la voie."
ui_1     | 2017-06-15 08:56:28,160 DEBUG [c2corg_ui.format.ltag][waitress] This block has ltags and will be processed and is starting with "R# | 20m | Relais interm\xe9diaire de la derni\xe8re longueur de la baliverna"
ui_1     | 2017-06-15 08:56:28,167 DEBUG [c2corg_ui.format.ltag][waitress] This block has no ltags and is starting with "- rappel 2*50m / 2*40m possible on croise des relais partout"
ui_1     | 2017-06-15 08:56:28,168 DEBUG [c2corg_ui.format.ltag][waitress] This block has no ltags and is starting with "rappel 2*50m / 2*40m possible on croise des relais partout"
ui_1     | 2017-06-15 08:56:28,168 DEBUG [c2corg_ui.format.ltag][waitress] This block has no ltags and is starting with "14 d\xe9gaines"
ui_1     | 2017-06-15 08:56:28,170 DEBUG [c2corg_ui.format.ltag][waitress] This block has no ltags and is starting with "Derborence: JM Cambon en 1994."
ui_1     | 2017-06-15 08:56:28,174 DEBUG [c2corg_ui.views][waitress] ETag didn't match, returning response object
```

And like this for unsupported ones
```
ui_1     | 2017-06-15 08:59:56,664 DEBUG [c2corg_ui.format.ltag][waitress] There is unsupported LTags in this block => skip it
ui_1     | 2017-06-15 08:59:56,665 DEBUG [c2corg_ui.format.ltag][waitress] There is unsupported LTags in this block => skip it
```

Could we see what it tells us on an environment where the issue occur ?
