### ISSUE TITLE
Enhance print view

### ISSUE THREAD

**Issue by brunobesson** [c2corg/v6_ui#1699]
* [x] Use black and white for wind rose
* [x] Add some text for license

**Comment by asaunier** [comment]
@brunobesson The "ready for testing" label is added only when changes are actually available in the demo (else you cannot test them). When a PR is merged you should rather use label "ready for demo".

**Comment by brunobesson** [comment]
@asaunier oops!
usually I have other examples but not this time. I hesitated (I always do hesitate when I have to do it!) and made the bad choice...
