### ISSUE TITLE
Enhance slideshow

### ISSUE THREAD

**Issue by brunobesson** [c2corg/v6_ui#1709]
* the custom buttons are not placed like other default buttons (fullscreen, close). when sliding, there is a visual glitch
* legend doesn't use pswp `title` attribute, but it's own custom object which doesn't behave appriopriately (among other things, it is no visible on mobile because shown only when hovered)

**Comment by desnoes** [comment]
@brunobesson : i don't know what must be tested. I let you validate.

**Comment by brunobesson** [comment]
It works as expected.
