### ISSUE TITLE
Quotes in version comment make the history page crash

### ISSUE THREAD

**Issue by asaunier** [c2corg/v6_ui#171]
In http://c2corgv6-demo.gis.internal:6555/waypoints/history/37355/fr (Mont Blanc), there's a comment in french that say
> Ajustement d'un titre d'itinéraire

=> that creates a syntax error and most of the page does not behave as expected

**Comment by tsauerwein** [comment]
Wait, why is it `{{mainCtrl.translate('Ajout d'un itinéraire : Traversée Arête des bosses - Aiguille du Midi')}} `? This part should not be translated.

**Comment by asaunier** [comment]
> This part should not be translated.

Indeed. On the other hand we have default comments added by the system such as "edit in fr", "imported from v4", etc. that would make sense to translate!?

**Comment by ginold** [comment]
is it better to create new strings like 'edit in fr' => 'traduire en francais' or use existing ones, like for example translate(edit in) + translate(fr) ?

**Comment by asaunier** [comment]
The less translations we have, the lighter the i18n files to load, the better.
But we have to find a compromise with complexity and flexibility.

> translate(edit in) + translate(fr)

This won't work in language like german since you can have words around the language name ("ins Deutsche übersetzen"?). But it seems you can use expressions in the translation strings, for instance ``translate in {{lang}}``.
Please note that in the history page we anyway have comments coming from the DB such as ``edit in fr``, that we cannot split as you suggest.

**Comment by tsauerwein** [comment]
The system message are not only in English? E.g. if a user with the interface language set to French makes a modification, the system message will also be in French?

If that is the case, I would not try to translate. It is as if the user has entered the message them self, and we don't translate custom messages.

**Comment by asaunier** [comment]
> The system message are not only in English?

The default history/version comments are only in english.
