### ISSUE TITLE
Associated documents should not be listed when viewing an archived document version

### ISSUE THREAD

**Issue by asaunier** [c2corg/v6_ui#172]
The API does not provide associated docs when requested for an archived document version (anyway not really relevant because those are not necessarly the docs that were associated at the time of the requested version).

Mako then throws an error when using the associated docs helpers:
http://c2corgv6-demo.gis.internal:6555/waypoints/37355/fr/1021748
>   File "/home/alex/v6_ui/c2corg_ui/templates/waypoint/view.html", line 121, in render_body
    <div><span translate>Waypoints</span>: ${show_associated_waypoints(waypoint)}
  File "/home/alex/v6_ui/c2corg_ui/templates/helpers.html", line 116, in render_show_associated_waypoints
    % if 'waypoints' in document['associations']:
KeyError: 'associations'

We should simply skip the associated documents blocks when ``version`` is available in the view templates.

Should probably be fixed when PR https://github.com/c2corg/v6_ui/pull/155 is merged, to avoid conflicts.

**Comment by gberaudo** [comment]
Will look at that.

**Comment by asaunier** [comment]
Already fixed by PR #155
