### ISSUE TITLE
Email for login creation contains invalid characters with hotmail provider

### ISSUE THREAD

**Issue by brunobesson** [c2corg/v6_ui#1730]
Random characters in the link are replaced by an equal instead, e.g.

https://www.camptocamp.org/au=h#validate_register_email=regemail_f3b85d3dbe548ab8fc0dec0b492242c645182=c32e0db128ab33911e2ed8f6ca

@desnoes this is a serious issue. Do you think we can handle this with C2C SA with high priority?

**Comment by arnaud-morvan** [comment]
I've created an hotmail address, I can reproduce, the link in the registration email is broken by equal signs inserted at random places. Whose fault is it ? outlook ?

**Comment by brunobesson** [comment]
>Whose fault is it ? outlook ?

Looks like it because only outlook/hotmail users have reported such an issue AFAIK...

**Comment by fjacon** [comment]
It would be a good idea to place a warning somewhere for hotmail user.

**Comment by asaunier** [comment]
I have not been able to reproduce the problem with a gmail address/mailer but this problem might impact also users with email addresses other than hotmail.

For instance a user with a "me.com" (mac user?) has reported that:
> J’ai voulu créé un compte sur CampToCamp.org mais le lien ci-dessous n’est pas opérationnel. Je vois qu’il y a :
> - notamment un signe = dans l’adresse (www.camptocamp.or=g)
> - le mot merci qui est inclus dans le lien

**Comment by mgerbaux** [comment]
This issues has also been reported for msn and free.fr address

**Comment by desnoes** [comment]
@Courgetteandratatouille wrote ; 

> j'ai regardé vite fait a priori le soucis dans les mails vient de 
l'encodage des caracteres, les mails sont envoyés en iso-8859-1 et 
hotmail n'a pas l'air d'apprecier, il faudrait essayer en asci ou utf8. 
(normalement c'est juste un paramètre à changer)

> Petit complément d'information, je pense que ca se passe ici:
https://github.com/c2corg/v6_api/blob/de9e3a730f299b5fcc98183edaee04de7027e1a5/c2corg_api/emails/email_service.py
D'après la doc de la lib utilisé https://github.com/Pylons/pyramid_mailer , l'encodage des caractères est définis de manière "automatique" 
   """
    Find the most human-readable and/or conventional encoding for unicode text.
    Prefers `us-ascii` or `iso-8859-1` and falls back to `utf-8`.
    """
Et ca correspond bien au charset qu'on voit dans la source du mail :). 
Du coup, je pense que pour corriger (disons que j'estime les chances de résolution à 80%) il faut rajouter content_type='utf-8' en option quelque part, mais je ne suis pas trés bon en python, donc j'ai pas encore trouvé ou ni comment.

**Comment by Courgetteandratatouille** [comment]
Hello :)

after a little research, i'am not sure but i think the problem is the charset used by pyramid_mailer.

On my test, iso-8859-1 is used, i guess if we force the utf-8 https://github.com/c2corg/v6_api/blob/de9e3a730f299b5fcc98183edaee04de7027e1a5/c2corg_api/emails/email_service.py here , the problem will be fix.

**Comment by asaunier** [comment]
Anyone knows if the problem occurs with emails sent by the demo?
If yes we could test a branch with changes suggested by @Courgetteandratatouille and check they fix the problem.

**Comment by desnoes** [comment]
i tried to create a new account from the demo. The url seems to be ok (https://www.demov6.camptocamp.org/auth#validate_register_email=regemail_3081f5bd75763eb6ec101473136abb69453a104212e4b2c06b3991742abee881), but i could not complete the procedure. I was asked my login/password, i tried several times but it always asked me to enter the info again. I am 100% i did not make any mistake when typing my pwd.

**Comment by asaunier** [comment]
> I've just created a new account from the demo.

With an hotmail address?

**Comment by Courgetteandratatouille** [comment]
Yes the problem is on the demo too  : 

=0A=
Bonjour=0A=
=0A=
Pour activer votre compte cliquez sur https://www.demov6.campto=3Damp.org/a=
uth#validate_register_email=3Dregemail_2f8864cb9315f600edb35e6bfb=3Ddf45c33=
e3c4952d28456f37a0d4be49da27aa=0A=
=0A=
Merci beaucoup=0A=
L'=E9quipe Camptocamp.org

**Comment by desnoes** [comment]
> With an hotmail address?

No, with my professionnal email address.

**Comment by asaunier** [comment]
> No, with my professionnal email address.

The problem is mostly with hotmail addresses, there are no problem with most of the other email services.

**Comment by asaunier** [comment]
> after a little research, i'am not sure but i think the problem is the charset used by pyramid_mailer.
>
> On my test, iso-8859-1 is used, i guess if we force the utf-8 https://github.com/c2corg/v6_api/blob/de9e3a730f299b5fcc98183edaee04de7027e1a5/c2corg_api/emails/email_service.py here , the problem will be fix.

@Courgetteandratatouille Thanks for the hint!
I have not found a straightforward way to set the charset and had to use some kind of "workaround" (or is it the recommended way?), see PR https://github.com/c2corg/v6_api/pull/676

I have not been able to test it in my instance because I have other problems but will deploy the branch's docker image to the demo in order to test it for real.

**Comment by asaunier** [comment]
The PR may be tested in the demo but it seems it still does not fix the problem: I have created an hotmail.com email address and used it to create an account on the demo but the registration email is still incorrect:
```
Bonjour

Pour activer votre compte cliquez sur [https://www.demov6.campto=amp.org/auth#validate_register_email=regemail_9d7e43c9576a4772c9910ed923=cf6a6862fbb70104d7e4330aedfc2bb50cf25]https://www.demov6.campto=amp.org/auth#validate_register_email=regemail_9d7e43c9576a4772c9910ed923=cf6a6862fbb70104d7e4330aedfc2bb50cf25

Merci beaucoup
L'Ã©quipe Camptocamp.org
```
(No problem when creating an account with a gmail address.)

**Comment by Courgetteandratatouille** [comment]
Ok but with the accent on L'Ã©quipe Camptocamp.org I am almost certain it's a charset problem.

Where the mail (text and link) is generated ?

**Comment by asaunier** [comment]
> Where the mail (text and link) is generated ?

Everything is done in
https://github.com/c2corg/v6_api/blob/master/c2corg_api/emails/email_service.py

The message contents are stored for instance here: https://github.com/c2corg/v6_api/tree/master/c2corg_api/emails/i18n/fr

**Comment by Courgetteandratatouille** [comment]
Hum, the mail is sended in text, and if we test a mail in html ?

**Comment by asaunier** [comment]
> Ok but with the accent on L'Ã©quipe Camptocamp.org I am almost certain it's a charset problem.

Did you have this accent problem when you tested the registration on the demo before I updated it?
If not it probably means my change has broken something else.

I'm a bit in doubt that it's a charset problem because the replacements also concern "standard" characters, for instance ``camptocamp.org`` => ``campto=amp.org``. Don't you think?

I am also quite surprised the problem mostly occur with hotmail and only since a few weeks, whereas nothing has changed in this part (I think) for months. Could it be a change done in the hotmail service or by our email sending service?
@mfournier would you have an idea?

**Comment by gberaudo** [comment]
@Courgetteandratatouille, if I take your raw text, save it to `raw.txt` and call:
`qprint -i -d raw | iconv -f ISO_8859-1 -t utf8`

I get no problem with the charset:
```
Bonjour

Pour activer votre compte cliquez sur https://www.demov6.campto=amp.org/auth#validate_register_email=regemail_2f8864cb9315f600edb35e6bfb=df45c33e3c4952d28456f37a0d4be49da27aa

Merci beaucoup
L'équipe Camptocamp.org
```

So I guess we can not arbitrarily put `utf8` on the data, but we need first to convert it to `utf8`.

Regarding the `c` becoming an `=` I have no idea yet.

**Comment by asaunier** [comment]
> So I guess we can not arbitrarily put utf8 on the data, but we need first to convert it to utf8.

OK, I will try to either remove the charset setting I have just introduced (since it seems we had no encoding problem in the message signature previously?) or add an explicit utf8 conversion.

> Regarding the c becoming an = I have no idea yet.

I will try to change the ``transfer-encoding`` and see if it changes something.

**Comment by asaunier** [comment]
I have updated the PR and changed ``transfer_encoding`` to ``base64`` instead of the default ``quoted-printable``. I have also removed the UTF8 charset setting.
The branch may be tested on the demo. I have tested with gmail and hotmail address and the received messages are OK in both cases.

**Comment by Courgetteandratatouille** [comment]
I made a test on demo and it's ok on hotmail.com :)

**Comment by desnoes** [comment]
i also did a successfull test with a Microsoft outlook email address.
