### ISSUE TITLE
Favicon

### ISSUE THREAD

**Issue by asaunier** [c2corg/v6_ui#175]
As for now, the favicon uses a PNG file: https://github.com/c2corg/v6_ui/blob/master/c2corg_ui/templates/base.html#L18-L19
- it's a bit too big for a favicon
- it's not transparent
- a simplified version (with only the waves of the logo, not the full name) would make more sense (as in v5)

**Comment by ginold** [comment]
there is a favicon, now we just need to make it stand out !

**Comment by mfournier** [comment]
I just wanted to ask advice on this, as these `/favicon.ico` and misc `/apple-touch-icon-*.png` are the top 404 errors in the logs, despite the `<link rel="shortcut icon" ...>` and `<link rel="icon" ...>` statements in templates/base.html.

I supposed these come from clients which attempt to fetch these files directly, without reading the html first. Would it make sense to catch these URLs and redirect them to `static/img/icon.png` ?

**Comment by brunobesson** [comment]
Don't modern browsers automatically fetch favicon? The meta tag is useless, IMHO

**Comment by desnoes** [comment]
@brunobesson : could you test, i did not figure out what must be tested.

**Comment by mgerbaux** [comment]
no preference between the present and proposed favicons ; fill free to close ;o)

**Comment by brunobesson** [comment]
It's working as expected.
Welcome back to the previous logo :wink: (IMHO it's more consistent with the association logo we are still using)
