### ISSUE TITLE
Quotes not escaped in the image gallery titles

### ISSUE THREAD

**Issue by asaunier** [c2corg/v6_ui#1753]
If an image title containes double quotes:

![capture du 2017-07-19 16-29-25](https://user-images.githubusercontent.com/1192331/28372289-9f2064f0-6c9f-11e7-8356-b52c48ca9868.png)

the title is truncated starting at the initial double quote in the image gallery title:

![capture du 2017-07-19 16-29-44](https://user-images.githubusercontent.com/1192331/28372337-b8488782-6c9f-11e7-9d05-cdd7010a6569.png)

See for instance https://www.camptocamp.org/images/298576/fr/trace-du-nouv-chemin-d-acces-au-neve-incline

**Comment by asaunier** [comment]
Closing because a duplicated issue (with a PR) has been created in the meantime: https://github.com/c2corg/v6_ui/issues/1809

**Comment by brunobesson** [comment]
Sorry, I didn't see the match when I created the issue.
