### ISSUE TITLE
Image modification: paragliding activity is not selectable

### ISSUE THREAD

**Issue by desnoes** [c2corg/v6_ui#1758]
When we want to modifiy the activity associated to an image, it is impossible to selec paragliding, the icon is not dispalyed.

![bug modifi activite image](https://user-images.githubusercontent.com/19892089/28511652-6c86c662-704e-11e7-9833-6038b66faa18.png)

**Comment by asaunier** [comment]
Is it possible to select this activity when uploading the image?

**Comment by desnoes** [comment]
@asaunier : yes it is possible, i've just tried.
