### ISSUE TITLE
email confirmation is not received (Free)

### ISSUE THREAD

**Issue by desnoes** [c2corg/v6_ui#1763]
Confirmation messages sent to a user (e.g. pwd modification)  having an email address from french operator Free are not received. It seems they are blocked by Free. The emails are not filtered by the antispam system of Free.

**Comment by asaunier** [comment]
Did it work before we made the changes about the hotmail issue?
The changes are here https://github.com/c2corg/v6_api/pull/676 => mainly switching ``transfer_encoding`` to ``base64`` instead of the default ``quoted-printable``.

**Comment by desnoes** [comment]
At least i've created an account with my free email address before the recent changes. I did it 2-3 month ago.

**Comment by asaunier** [comment]
@desnoes I have tried to use another setting for sent emails, see PR https://github.com/c2corg/v6_api/pull/686
I have updated the demo to have it tested.

I don't know if it will work better but at least it works with my own camptocamp.org email address.
Could you please ask people to test asking for a new password with various email addresses (hotmail, free, gmail, aol etc.)?

**Comment by desnoes** [comment]
sorry @asaunier, i've just seen your message. The email was redirected in the 'indésirable' folder.
I did a test with my .free email address. I did not received the message to change my pwd.

**Comment by asaunier** [comment]
Closing this issue because emails are managed by the API. I have created a dedicated issue at https://github.com/c2corg/v6_api/issues/700
