### ISSUE TITLE
Buggy rendering of route's lift_access attribute

### ISSUE THREAD

**Issue by asaunier** [c2corg/v6_ui#1769]
Reported by email:
> Dans la saisie d'un itinéraire, j'ai sélectionné "Remontées mécaniques" : non
Si je passe en prévisualition, il est marqué : "oui"
Après la saisie de l'itinéraire, si je modifie, il y a 4 choix possibles dans le menu au lieu de 3 (vide, oui, non, pas d'information). Je modifie, prévisualise, retour, et il n'y en a plus que trois choix.

``lift_access`` is a boolean flag in the API: https://github.com/c2corg/v6_api/blob/master/c2corg_api/models/route.py#L75

Perhaps this attribute should be rendered as a checkbox in the editing form.
* If not checked => show nothing in the route page
* If checked => show a "lift access: yes" mention in the route page

Parts that could be changed:
* editing form: https://github.com/c2corg/v6_ui/blob/master/c2corg_ui/templates/route/edit.html#L496-L503
* document page / preview: https://github.com/c2corg/v6_ui/blob/master/c2corg_ui/templates/route/helpers/view.html#L221-L223

**Comment by fbunoz** [comment]
How the old "no info" value will be rendered in the form ?
No need update the API and rebake the BD ?
