### ISSUE TITLE
Outing: Map shifts downwards

### ISSUE THREAD

**Issue by desnoes** [c2corg/v6_ui#1771]
When the number of maps/region is very large, the map at the top of the page shifts downwards and is not displayed correctly. 
exemple: [https://www.camptocamp.org/routes/913558/fr/fontainebleau-chatillon-en-diois](https://www.camptocamp.org/routes/913558/fr/fontainebleau-chatillon-en-diois)

**Comment by asaunier** [comment]
Indeed. I think we should rework the positionning and format of the map as well as drop this "post it" which is not that convenient (might be too small + hide a part of the map) => the content of the post it could be moved to the "figures" part of the page (as in mobile screens).

**Comment by asaunier** [comment]
Is this issue still relevant with the new layout that will come with https://github.com/c2corg/v6_ui/pull/1783 ?
