### ISSUE TITLE
Incorrect document URL in the whatsnew page

### ISSUE THREAD

**Issue by asaunier** [c2corg/v6_ui#1777]
In https://www.camptocamp.org/whatsnew all document links are like https://www.camptocamp.org/articles/903357/fr/1446880 instead of https://www.camptocamp.org/articles/version/903357/fr/1446880

The first URL actually points to the current version of the document whereas the link is supposed to points to a given version (the "version" keyword is missing).

**Comment by desnoes** [comment]
When we click on a route or article, it opens the same view as when we open an older version of the document, while it is the most recent.

![whatsnew](https://user-images.githubusercontent.com/19892089/29980250-3ef1a766-8f49-11e7-8711-ac761a10e0dd.png)

**Comment by asaunier** [comment]
@desnoes That's the expected behaviour.
