### ISSUE TITLE
Outing's information: add the number of associated photos

### ISSUE THREAD

**Issue by desnoes** [c2corg/v6_ui#1780]
Dispaly in the outing's card/list the number of photos associated to this outing. This number is provided by API (see https://github.com/c2corg/v6_api/issues/684).
How to display this number is left open.

See also the GPS flag issue at https://github.com/c2corg/v6_ui/issues/1549

**Comment by asaunier** [comment]
Please note an "has_geom_detail" boolean flag is also available for outings and routes, indicating if the document has a related "GPS track".
