### ISSUE TITLE
Get contextual help content from a UI webservice?

### ISSUE THREAD

**Issue by asaunier** [c2corg/v6_ui#1788]
Currently the HTML content of advanced contextual helps are stored in partials: https://github.com/c2corg/v6_ui/tree/master/c2corg_ui/static/partials/contexthelp
which are eventually concatenated in the final built JS file.

Since the number of contextual help partials is growing fast (thanks to @desnoes :) ), an improvement could be to make the content served on demand by the UI server using an asynchronous request. This way the partials would no longer be part of the built JS file that is downloaded when users visit the UI for the first time (but translations would remain in the overall translation files though).

In addition to a simple UI webservice (serving mako templates instead of AngularJS partials), the suggested change would be to use a ``$http`` request to the UI service instead of retrieving the content from the partials at https://github.com/c2corg/v6_ui/blob/master/c2corg_ui/static/js/contexthelp.js#L29

**Comment by cbeauchesne** [comment]
:) 

This has be done on new UI, by leveraging on articles 🎉
