### ISSUE TITLE
Set default values in outings

### ISSUE THREAD

**Issue by desnoes** [c2corg/v6_ui#1797]
I would like to know how to define the default value of a selector used in the outing edition form. I did not find how to programm it with angularjs.
For instance, the default value of the quality  is hardcoded in documentediting.js (line 673) 
`this.quality = appDocument.document.quality || 'draft';`
 For the quality attribute, i would like to compute a pre-selected value and use it as a default value in the selector. Thus hardcoding is not convenient.
If someone could provide an example, this could be reuse to set some default values (eg. altitude of access point, min/max altitude, elavation gain/loss...).

**Comment by asaunier** [comment]
> For instance, the default value of the quality is hardcoded in documentediting.js (line 673)
this.quality = appDocument.document.quality || 'draft';

This is not hardcoded :)
This code actually sets the value of the ``quality`` attribute either by using the value retrieved from the database (when editing an existing document) or by using the default value ("draft") for new documents.

The code you mention: https://github.com/c2corg/v6_ui/blob/master/c2corg_ui/static/js/editing/documentediting.js#L673
sets the quality selector in the modal window shown when saving the document. The contributor can then change the selector value and submit it. The submitted value is retrieved and integrated in the document here:
https://github.com/c2corg/v6_ui/blob/master/c2corg_ui/static/js/editing/documentediting.js#L631

If you want to precompute the value of the quality selector in the modal box, you may add a function in the ``app.ConfirmSaveController`` controller and use it to set ``this.quality`` at https://github.com/c2corg/v6_ui/blob/master/c2corg_ui/static/js/editing/documentediting.js#L673 based on the other attributes of the document itself ``appDocument.document``.

**Comment by asaunier** [comment]
> If someone could provide an example, this could be reuse to set some default values (eg. altitude of access point, min/max altitude, elavation gain/loss...).

This is done by PR https://github.com/c2corg/v6_ui/pull/1801
See https://github.com/c2corg/v6_ui/pull/1801/commits/8cd7c77952d4170339f8e0a4567f2b988d27ffd5

**Comment by desnoes** [comment]
> See [8cd7c77](https://github.com/c2corg/v6_ui/commit/8cd7c77952d4170339f8e0a4567f2b988d27ffd5)

I found 
`data['elevation_min'] = doc['elevation_min'];
 +    data['elevation_max'] = doc['elevation_max'];
 +    data['height_diff_up'] = doc['height_diff_up'];
 +    data['height_diff_down'] = doc['height_diff_down'];`

Does this means you already preset the values of fields 'elevation_min', 'elevation_max', 'height_diff_up' and 'height_diff_down'? This was my intention, but i have the feeling you already implement it. Could you confirm ?

**Comment by asaunier** [comment]
> Does this means you already preset the values of fields 'elevation_min', 'elevation_max', 'height_diff_up' and 'height_diff_down'?

Yes

**Comment by desnoes** [comment]
you robbed my job :)
