### ISSUE TITLE
Improve alert/feedback messages layout

### ISSUE THREAD

**Issue by asaunier** [c2corg/v6_ui#180]
As for now, feedback messages (login/logout/editing errors etc.) using the ``alerts`` directive https://github.com/c2corg/v6_ui/blob/master/c2corg_ui/static/js/alerts.js are shown at the bottom of the page.

I think we can improve them (mainly styling?) to make them nicer and more obvious.

**Comment by ginold** [comment]
can be closed

**Comment by asaunier** [comment]
Your PR is not merged yet. :)
