### ISSUE TITLE
Add support of outing ratings attributes

### ISSUE THREAD

**Issue by asaunier** [c2corg/v6_ui#1800]
See the original issue at https://github.com/c2corg/v6_ui/issues/1550

See the API issue at https://github.com/c2corg/v6_api/issues/685 and its TODO at https://github.com/c2corg/v6_api/issues/685#issuecomment-336397857

In short: a subset of ratings are added to outings, depending on the outing's activities. See the list of ratings here: https://github.com/c2corg/v6_api/issues/685#issuecomment-333570449

## Displaying of the outing ratings

- [x] show ratings in the outing cards
- [x] show ratings in the outing detail view pages, along with the other outing attributes (height diff etc.)

**Note: to be done by the association**

## Add outing ratings attributes to the outing editing form

- [x] update the v6_common requirements to use https://github.com/c2corg/v6_ui/issues/1550
- [x] add new inputs to the outing editing form, HTML from the route editing form can be reused, see for instance https://github.com/c2corg/v6_ui/blob/master/c2corg_ui/templates/route/edit.html#L520-L531
- [x] make sure ratings are displayed depending on the selected activities. Ratings according to activities are listed here: https://github.com/c2corg/v6_api/issues/685#issuecomment-333570449
- [x] set default values for the ratings attributes using ratings of the initially associated route. See how it is done for setting the default outing title (using the title of the initially associated route) at https://github.com/c2corg/v6_ui/blob/433bbf000567c7b7cdbd30112178c3908a58609e/c2corg_ui/static/js/documentservice.js#L145-L155 [the ratings of the route are actually provided by the association tool]

## Filtering outings according to their ratings

Perhaps to do in a separated PR!?

- [x] add filters to the outings advanced search page
- [ ] ~~(filter home feed according to ratings prefs? => detailed specs are needed if this feature is required)~~

**Comment by asaunier** [comment]
@Courgetteandratatouille We might encounter conflicts with your changes https://github.com/c2corg/v6_ui/pull/1783 since you also have modified the outing editing form.

Concerning the addition of the ratings in the outing cards/list items, this will anyway be managed by the association I think and after your PR is merged.

**Comment by desnoes** [comment]
> Concerning the addition of the ratings in the outing cards/list items, this will anyway be managed by the association I think and after your PR is merged.

Yes. This has to be done simulatneously with the number of images associated to the outing and the presence of geometry.
