### ISSUE TITLE
Incorrect attributes title in access waypoint preview

### ISSUE THREAD

**Issue by asaunier** [c2corg/v6_ui#1802]
When previewing an access waypoint, the titles of attributes "description" / "access" are not the good ones (as when viewing the document).

For instance:

* preview:
![542214f3-2236-4898-b668-c92d11b2563e](https://user-images.githubusercontent.com/1192331/32053098-8e656ee0-ba5a-11e7-99d7-570732b26b4b.png)
* view
![44bd9451-ec19-428f-a89d-b857f30f9195](https://user-images.githubusercontent.com/1192331/32053097-8e4bb9c8-ba5a-11e7-88a2-42c76d26bcd2.png)

Perhaps something like https://github.com/c2corg/v6_ui/blob/master/c2corg_ui/templates/waypoint/view.html#L135-L136 missing in https://github.com/c2corg/v6_ui/blob/master/c2corg_ui/templates/waypoint/preview.html

**Comment by brunobesson** [comment]
I have tried taking a look at this spécific point, but I cannot observe the same behaviour, I have other problems. Maybe it is related to the new design?

* view
![snapshot20](https://user-images.githubusercontent.com/2234024/32697958-0ca10726-c79c-11e7-9828-a0da89d6e5d3.png)

* preview (many fields are missing)
![snapshot21](https://user-images.githubusercontent.com/2234024/32697959-1080874a-c79c-11e7-8df4-9413e9de4792.png)
