### ISSUE TITLE
Image title is not escaped for rendering in slideshow

### ISSUE THREAD

**Issue by brunobesson** [c2corg/v6_ui#1809]
See e.g. https://www.camptocamp.org/images/943426/fr/l1-laja-sospechosa displayed in https://www.camptocamp.org/outings/943425/fr/montrebei-paroi-de-catalogne-el-voltor-feroc#&gid=1&pid=1 : quotes are not escaped. This is both a rendering and XSS issue.

**Comment by asaunier** [comment]
With PR https://github.com/c2corg/v6_ui/pull/1810 it seems that when no title has been provided, the slideshow uses "undefined" instead.
<img width="300" alt="capture d ecran 2017-11-28 a 23 35 39" src="https://user-images.githubusercontent.com/1192331/33348001-017282ac-d495-11e7-9ae4-c895f89c7a4f.png">

**Comment by asaunier** [comment]
> With PR #1810 it seems that when no title has been provided, the slideshow uses "undefined" instead.

It seems the problem can no longer be reproduced (fixed?).
