### ISSUE TITLE
parser crash if video url is invalid on video tag

### ISSUE THREAD

**Issue by cbeauchesne** [c2corg/v6_ui#1812]
Use an invalid url inside a [vidéo] tag, the parser will crash.

    [video]not an url[/video]

It's because the Pattern.unescape function called at the end of handleMatch needs self.markdown property  

To fix this, you need to instanciate C2CVideo class with mâkdown_instance argument.

I will propose a PR this WE

**Comment by stef74** [comment]
@cbeauchesne it is fixed ?

**Comment by cbeauchesne** [comment]
yes all good
