### ISSUE TITLE
Add checkbox to validate account creation

### ISSUE THREAD

**Issue by mgerbaux** [c2corg/v6_ui#1822]
When creating an account, a user should validate that he has read the "terms of use". A link should refer to an article that explain the licenses of contents, a chart of the contributor, the chart of the forum, etc...

**Comment by brunobesson** [comment]
@mgerbaux AFAIK, there is no such article yet, does it? This is a preamble before fixing this issue.

**Comment by mgerbaux** [comment]
Please point to https://www.camptocamp.org/articles/106730/fr (I will delete / reorganize this former article for this new requirement)

**Comment by mgerbaux** [comment]
It seems to work nice :o) thanks @brunobesson 
The checkbox is not very visible on my screen (lack of contrast)
![screenshot at 2017-12-15 21 54 09](https://user-images.githubusercontent.com/22116605/34060150-b513f660-e1e2-11e7-8f9a-380fe7fd455f.png)
