### ISSUE TITLE
title emphasis

### ISSUE THREAD

**Issue by cbeauchesne** [c2corg/v6_ui#1831]
Handle this pattern

    ### title # emphasis

**Comment by stef74** [comment]
ready for testing = on the demo server , it is the case ?

**Comment by cbeauchesne** [comment]
Oups, no sorry, I've missunderstood the meaning of this label.

**Comment by asaunier** [comment]
I have added the "ready for testing" label because it will soon be available on the demo (anticipating a bit).
When a PR has been merged, the related issue should be tagged "ready for demo" (this way we know that it should become "ready for testing" when the demo is updated).

**Comment by cbeauchesne** [comment]
ok
