### ISSUE TITLE
Pictogram syntax

### ISSUE THREAD

**Issue by cbeauchesne** [c2corg/v6_ui#1833]
See https://forum.camptocamp.org/t/migration-bbcode/199173/81?u=charlesb

Based on emoji extension (https://facelessuser.github.io/pymdown-extensions/extensions/emoji/), parser must allow this syntax : 

    :icon-name:

**Comment by cbeauchesne** [comment]
I @asaunier,

On this : https://github.com/c2corg/v6_ui/blob/MarkdownEmojis/c2corg_ui/format/emoji_databases/c2c_activities.py#L1

I need to get the path to static url, can you help me te code it with the good way (guess that this ugly 0f23010 is not **the** good way to do it)

**Comment by asaunier** [comment]
Could you use more explicit commit messages? It should be obvious what a commit does without opening an issue etc.

> I need to get the path to static url

Where do you need this URL? In a python template or in the javascript code.
See for instance https://github.com/c2corg/v6_ui/blob/master/c2corg_ui/templates/base.html#L139

**Comment by cbeauchesne** [comment]
Neither js or python template.

This code will display small icons into article, and for those who are C2C-made, I'd like to simply use icons present into static directory.

This markdown `:skitouring:` will render like `<img src="/static/.../skitouring.svg"/>`

> https://forum.camptocamp.org/t/migration-bbcode/199173/99

**Comment by asaunier** [comment]
The static files root directory is https://github.com/c2corg/v6_ui/tree/master/c2corg_ui/static
and is available at URL https://www.camptocamp.org/static/<uid>/ (absolute) or /static/<uid>/ (relative).

For instance:
https://www.camptocamp.org/static/7e841eb/img/app/googleplay.svg
/static/7e841eb/img/app/googleplay.svg

**Comment by cbeauchesne** [comment]
sorry if the answer seems to be obvious, but how do I get uid?

**Comment by asaunier** [comment]
> how do I get uid?

You can't. It is regenerated randomly (?) whenever a release is done. Actually you can use whatever string. It's used to invalidate caches and force browsers to download the files again after each release.

But it's not mandatory: you can use a URL (absolute or relative) without it. Eg. https://www.camptocamp.org/static/img/app/googleplay.svg

**Comment by cbeauchesne** [comment]
https://www.camptocamp.org/static/img/app/googleplay.svg

👍  Many thanks

**Comment by desnoes** [comment]
It seems the icon for mountain climbing does not display (cf. https://www.demov6.camptocamp.org/articles/951530/fr/essai-images)

**Comment by cbeauchesne** [comment]
Good point, I've forgotten it...

**Comment by brunobesson** [comment]
@cbeauchesne I have opened #2001 for the missing icon. I'm closing this issue.
