### ISSUE TITLE
Clean CSS

### ISSUE THREAD

**Issue by stef74** [c2corg/v6_ui#1835]
since new design some class are not used particulary in list.less (redundancy with card.less)
A specific tool can be help

**Comment by brunobesson** [comment]
#1888 proposes to use stylelint for LESS linting. This won't solve most of the problems exposed here, but it should at least ensure some consistency.

As for detecting duplicated code and such, I should seek for a tool I discovered a while ago that allows to compute CSS code coevrage.

**Comment by stef74** [comment]
I search a tool to detect unused class, do you know it ?

**Comment by brunobesson** [comment]
>I search a tool to detect unused class, do you know it ?

There is no such thing, because to do so, the tool should be able to handle all case on the server side and this is usually not possible. But there exist tools that compute CSS code coverage as you browse a site. This is what I have seen before.

**Comment by brunobesson** [comment]
Maybe it was simply latest chrome :hugs: 

http://vojtechruzicka.com/measuring-javascript-and-css-coverage-with-google-chrome-developer-tools/

**Comment by stef74** [comment]
I have viewed it ... but it's probably work for one page not entire web site. And my side not working ... i h'ave only the globale view with the percentage of unsused code ... but if I click on the file no details on the code itself.

![capture](https://user-images.githubusercontent.com/3962997/33879802-d760f516-df2f-11e7-8cc8-4bc8eea706eb.PNG)

**Comment by brunobesson** [comment]
Maybe just update your browser :wink: 
But, yes, as we do not have an SPA, this is not ideal...

**Comment by stef74** [comment]
I'm on version 62 ...

**Comment by brunobesson** [comment]
I don't know what to say...

Anyway, this is one of the way to solve this. The other one would be IMHO more structured less files. I.e. smaller files and includes.
Also, maybe we should use something like BEM to naming stuff.
But these two points would require to stabilise the new design first before refactoring.

**Comment by stef74** [comment]
After a browser relaunch is good ... I have an option to have separeted css file (not only one), to easy the analysis (the induvidueal file a splited by "usage" ... so gnerely few page).

**Comment by brunobesson** [comment]
>I have an option to have separeted css file

No there isn't such option. But you could tweak the LESS generated file. I see in the Makefile there is also a non minified `build.css` file built, maybe you can directly use it?

**Comment by stef74** [comment]
minification is not a problem (chrome show non minified version)
