### ISSUE TITLE
Image header

### ISSUE THREAD

**Issue by stef74** [c2corg/v6_ui#1836]
current rendesiring is no correct

Remove header or improve proposed by @lbesson

**Comment by lbesson** [comment]
Can you be more precise? (especially on what I proposed :smiley:)

**Comment by stef74** [comment]
I have no special idea, i have just created a new issue separated

**Comment by lbesson** [comment]
the issue as presented here is quite confusing to me: what is exactly the problem?

(I think I understand: should we or not remove the images that is sometimes put in document header - but reading it, I first thought it was link to html headers sent with images)

**Comment by stef74** [comment]
The problem express on forum is image dimension and croping is not good
