### ISSUE TITLE
Alerts syntax

### ISSUE THREAD

**Issue by cbeauchesne** [c2corg/v6_ui#1838]
See https://forum.camptocamp.org/t/migration-bbcode/199173/102?u=charlesb

Handle this syntax : 

```
 !! Ceci est une information neutre
 
 alors que :
 
 !!! Ceci est un warning
 !!! a prendre en compte
 
 mais surtout n'oubliez pas que : 
 
 !!!! Ceci est une
 !!!! information **ultra importante**
```

It must handle new lines, formats, list, blockquote, and could be included in list and blockquotes.

**Comment by desnoes** [comment]
Is it a normal behavior that the icons used for warning and important tags are not displayed ?

**Comment by cbeauchesne** [comment]
Yes, I do not have included anything, except a background and a border.

**Comment by brunobesson** [comment]
ok
for warning icons -> :warning: or :no_entry_sign: or :exclamation:

**Comment by cbeauchesne** [comment]
there is three level : 

1. info : maybe ❓, but in blue 
2. warning : ⚠️ 
3. danger : :bangbang:
 
BTW, I'm not sure that a icon is mandatory. Maybe color is suffisant. I think that a discussion on a forum is needed on this, with two question : 

1. Is it clear enough?
2. if no, what icon to use?
