### ISSUE TITLE
New associations: make sure the new association is not already associated

### ISSUE THREAD

**Issue by asaunier** [c2corg/v6_ui#184]
As for now, with the association adding tool, it is possible to associate again a document that is already associated => the association appears twice in the page.

When reloading the page, the UI crashes (most likely because the API crashed in the background?).

**Comment by tsauerwein** [comment]
The API should raise an error when an association already exists:
https://github.com/c2corg/v6_api/blob/master/c2corg_api/views/association.py#L21-L22

**Comment by asaunier** [comment]
OK, then maybe the ``addassociation`` directive does not take the API error into account?

**Comment by asaunier** [comment]
Actually the association tool should strip already associated docs out of the search results list.

**Comment by ginold** [comment]
already implemented.
