### ISSUE TITLE
Maintenance page

### ISSUE THREAD

**Issue by asaunier** [c2corg/v6_ui#1840]
@lbesson has provided a static page served by HAProxy when all UI instances are down:

<img width="985" alt="capture d ecran 2017-11-30 a 23 46 36" src="https://user-images.githubusercontent.com/1192331/33459011-c718cd6a-d628-11e7-8b51-b253936a3929.png">

Note that this page will be served in case of an unwanted server breakdown as well. Perhaps we should make this page a bit more generic to address this situation too.

**Comment by brunobesson** [comment]
@asaunier you mean the content (the text) should cover a wider range of situations, i.e. both a maintenance and a technical issue?

**Comment by asaunier** [comment]
@brunobesson Exactly

**Comment by brunobesson** [comment]
Then this is only a translation issue. Maybe we could simply ask on the forum? The french text would be `Le site est en cours de maintenance ou connait un souci technique et n'est donc (...)`

**Comment by brunobesson** [comment]
English part: `This website is under maintenance or experiencing a technical issue and will be back soon (...)` and `To see if interruption has ended (...)`
