### ISSUE TITLE
New georeferenced docs are not returned by the filter when a bbox criteria is given

### ISSUE THREAD

**Issue by fbunoz** [c2corg/v6_ui#1843]
I don't know if it is an UI or API bug.

For instance, last outings in France and around : https://www.camptocamp.org/outings#bbox=-536346%252C4932558%252C1156276%252C7314948
The last outing is dated from 29/11/2017.
When we remove bbox criteria, some outings appear, which are in France, and from 30/11/2017.
Then, it seems that any outing created after 29/11/2017 is not visible using a bbox criteria.
The bbox criteria is put by default when we access to the filter.

This bug is also available for routes and WP (and xreports ?).

**Comment by asaunier** [comment]
@fbunoz Is this issue still valid? I see recent outings in https://www.camptocamp.org/outings#bbox=-536346%252C4932558%252C1156276%252C7314948

Anyway it is not a UI issue, all data issues are generally only related to the API.
