### ISSUE TITLE
JS error when edit xreport

### ISSUE THREAD

**Issue by brunobesson** [c2corg/v6_ui#1848]
To be investigated

![snapshot2](https://user-images.githubusercontent.com/2234024/33503860-9d4f6f6c-d6e5-11e7-8d2c-ae6bf5026816.png)

**Comment by asaunier** [comment]
If you add "?debug" in the URL you load the actual JS files, not the minified ones, it helps understand where the problem is. It does not work in prod but OK in a local instance.

**Comment by brunobesson** [comment]
This problem is related to user cards. I'll try to provide a full fix today.

**Comment by brunobesson** [comment]
>I'll try to provide a full fix today.

And there it is. Note that I have not done a lot of work on user cards though. This need some more love.
