### ISSUE TITLE
region cards broken

### ISSUE THREAD

**Issue by Courgetteandratatouille** [c2corg/v6_ui#1853]
Since the last change, the area cards are broken.

https://screenshots.firefox.com/ahTaL2fVjXcLTEu4/www.camptocamp.org

**Comment by stef74** [comment]
fix in #1839

2017-12-06 9:40 GMT+01:00 Nicolas Michel <notifications@github.com>:

**Comment by Courgetteandratatouille** [comment]
ok nice :)
