### ISSUE TITLE
Last forum topics displayed on homepage should be filtered according to forum categories

### ISSUE THREAD

**Issue by mgerbaux** [c2corg/v6_ui#1854]
For guests (and everybody to begin simple), the Last forum topics displayed on homepage should be filtered according to forum categories (e.g not display forum bistrot, comments, P++, moderation…)

In a second time, this could be managed for identifed user with forum preference

**Comment by brunobesson** [comment]
Simple PR until we found a more satisfactory solution: #1871

**Comment by mgerbaux** [comment]
I do not understand the behavior… or it does not work ?
My last posts (https://forum.demov6.camptocamp.org/latest) do not appear on home page, so as they do according to their category…

**Comment by brunobesson** [comment]
Dunno. But the categories on the demo are not the same that the ones in prod!

**Comment by brunobesson** [comment]
I mean the ids are not the same

**Comment by mgerbaux** [comment]
But i have replied to message already displayed on demo homepage...
I will have other tests tommorow

**Comment by desnoes** [comment]
same comments as @mgerbaux. Do you mean @brunobesson, il is not possible to test on demo since the IDs are differents ?

**Comment by brunobesson** [comment]
Somehow, yes. What you could do is determine that some posts do not appear. But you need to know the corresponding ids.

**Comment by fbunoz** [comment]
It is not an ID problem.
When I add a response on a topic already on the homepage, near the end of the topic list, I expect the topic is going up.
But instead, another topic which wasn't on the home page appear at the top !
Ex : I posted here : https://forum.demov6.camptocamp.org/t/acces-col-de-pailheres/173147/2
And it's this topic which appear at the top : https://forum.demov6.camptocamp.org/t/radio-secours-montagne/137561

I found the bug : we must remove page=1 criteria from Discourse API request, then the response is correct : 
https://forum.demov6.camptocamp.org/latest.json?exclude_category_ids[]=95&exclude_category_ids[]=113&exclude_category_ids[]=94&exclude_category_ids[]=96&exclude_category_ids[]=42&exclude_category_ids[]=41&exclude_category_ids[]=40&exclude_category_ids[]=43&exclude_category_ids[]=44&exclude_category_ids[]=45&exclude_category_ids[]=97&exclude_category_ids[]=54&exclude_category_ids[]=47&exclude_category_ids[]=29&exclude_category_ids[]=136&exclude_category_ids[]=146&exclude_category_ids[]=56&exclude_category_ids[]=64&exclude_category_ids[]=55

**Comment by brunobesson** [comment]
@fbunoz thx, I reported your fix, we will test this soon!
