### ISSUE TITLE
Multilang dates

### ISSUE THREAD

**Issue by ginold** [c2corg/v6_ui#186]
We will need to handle dates in multiple languages, for example in posts, versions of a document etc.
Do we already have a tool for that? if not, I suggest using http://momentjs.com/ 
not only it translates dates but also it's ultra useful for manipulating date and time.
And there is an angular directive for that https://github.com/urish/angular-moment

**Comment by asaunier** [comment]
That looks interesting indeed.
As for now, it seems the date are always displayed in english, for instance:
> Jun 19, 2015 10:06:42 PM
