### ISSUE TITLE
on diff screen, hide map if location has not changed

### ISSUE THREAD

**Issue by cbeauchesne** [c2corg/v6_ui#1874]
because it's a huge waste of place

**Comment by brunobesson** [comment]
It is quite easy to solve this, I'll provide a PR.
My (aside) question is: how is the diff supposed to present a change in the GPX file (if any) of a route? Currently, there is only a point shown (I assume it the the geocenter computed from associated waypoints). Should it show the difference for the GPX track to it?

**Comment by desnoes** [comment]
Ok on demo
