### ISSUE TITLE
Map mouse wheel zooming vs page scrolling

### ISSUE THREAD

**Issue by asaunier** [c2corg/v6_ui#189]
See https://github.com/c2corg/v6_ui/pull/106#issuecomment-186569509

> Yay, check this example: http://bl.ocks.org/tsauerwein/raw/38dc9e71a6781da42017/

> The code is here: https://gist.github.com/tsauerwein/38dc9e71a6781da42017

> Or even simpler: http://bl.ocks.org/tsauerwein/raw/1941fdb6703fb4820933/
Code: https://gist.github.com/tsauerwein/1941fdb6703fb4820933
(Idea borrowed from here)

**Comment by asaunier** [comment]
Really cool, thanks @tsauerwein !
What version do you recommend? The simpler one?

**Comment by tsauerwein** [comment]
The simpler one should be fine.
