### ISSUE TITLE
Manage documents marked as merged

### ISSUE THREAD

**Issue by asaunier** [c2corg/v6_ui#190]
Example in v5: http://www.camptocamp.org/summits/300435/fr/dolomites-de-brenta
In v6, as for now one get an error 500: http://c2corgv6-demo.gis.internal:6555/waypoints/300435/fr => the error seems the same than for https://github.com/c2corg/v6_ui/issues/137

See also https://github.com/c2corg/v6_api/issues/73

**Comment by tsauerwein** [comment]
For more information see https://github.com/c2corg/v6_ui/issues/238

**Comment by asaunier** [comment]
> When a merged document is requested, the API will return:
{"redirects_to": 12345, "available_langs": ["en", "fr"]}

Nice! We'll then be able to make a 301 redirection on the UI side.

**Comment by fjacon** [comment]
is this done ?
