### ISSUE TITLE
Some text fields are not shown on a preview

### ISSUE THREAD

**Issue by fbunoz** [c2corg/v6_ui#1909]
The route text field "gear" doesn't appear on the preview : 
https://www.demov6.camptocamp.org/routes/edit/54591/fr
It's a regression since Courgette design (the bug exist in prod).

**Comment by desnoes** [comment]
The pedestrian access does not appear in the preview of 'hut' WP.

**Comment by fbunoz** [comment]
Same problem with "restriction access" field in climbing waypoint.
