### ISSUE TITLE
Incorrect map extent when showing North Pole

### ISSUE THREAD

**Issue by asaunier** [c2corg/v6_ui#192]
See for instance http://c2corgv6-demo.gis.internal:6555/waypoints/list/limit/30/offset/270

![map_extent](https://cloud.githubusercontent.com/assets/1192331/13250502/993d72e8-da2a-11e5-9da5-78765fac61b9.jpg)

**Comment by tsauerwein** [comment]
The Mercator projection is not appropriate around the poles.

**Comment by asaunier** [comment]
OK, so we can't really do something for this issue since we won't use another projection.
