### ISSUE TITLE
Remaining issues related to new design

### ISSUE THREAD

**Issue by stef74** [c2corg/v6_ui#1947]
remaining points of #1808 

Je liste ici les petits soucis cosmétique que je vois. Chrome, écran 1200px.
- [ ] Bouton d'éditions un peu trop "collés" au corps de la page : 
<img src="https://forum.camptocamp.org/uploads/default/original/2X/2/234fdbfa7a0353ffe5fc18f0b43c0630c1133ea3.png" width="79" height="208">
<img src="https://forum.camptocamp.org/uploads/default/original/2X/a/a9a74fd68a0ce04cb3c19475ef884af65632afd6.png" width="272" height="32">

- [ ] h4 headers font size is bigger than h3 headers 

 - [ ] empty associated outings section should have a default text
![screenshot_20171123-174849](https://user-images.githubusercontent.com/2234024/33505076-5b4c3d8e-d6ea-11e7-99a4-a8d2347addb1.png)

- [ ] Date is missing in the xreports cards in the home feed (it could be added below the title as for outings):
![capture du 2017-12-05 09-43-05](https://user-images.githubusercontent.com/1192331/33597770-b6d90fca-d9a0-11e7-91b7-9e32ff6e24bb.png)

- [ ] Initial author has been removed from outing cards listed in a route pages

- [ ] In outing pages, there is an activity filter for the associated routes. Eg. https://www.camptocamp.org/outings/950651/fr/le-chantonnet-tete-de-ferret-la-dotse-en-circuit

I don't think it was provided before the layout change. Not sure it is really useful since there is generally not that much routes associated to an outing.

* [ ] When associating a WP to a route, since the WP listing section is placed in a quite remote location compared to the association tool, it's hard to realize that the associating has actually worked (it seems nothing happened whereas the WP has been added somewhere else).

Perhaps we could have several instances of the association tool (``app-add-association`` directive), with one at the bottom of the WP list. It is possible to adapt the list of searched document types using the ``dataset`` attribute, eg. ``dataset="wrcbx"``
https://github.com/c2corg/v6_ui/blob/master/c2corg_ui/templates/route/view.html#L167
See https://github.com/c2corg/v6_ui/blob/master/c2corg_ui/static/js/utils.js#L8-L33 for the list of doctypes.
  
* [x] "outing" badge (near the title) is not translated in outing pages => it seems the string is not available in Transifex, most likely because it has not been marked as "translate"-able in the templates

* [ ] activity icons are no longer displayed near the outing page titles despite they are added in the templates: https://github.com/c2corg/v6_ui/blob/master/c2corg_ui/templates/outing/view.html#L97

* [ ] When the mouse cursor hovers a data block (figures, description, etc.) in a document (route, outing, etc.) it turns to a pointer, which does not make sense since the block is not clickable.
It is probably related to the ``ficontent`` class:
https://github.com/c2corg/v6_ui/blob/364c4f7f714533242ea874606c8506c75e74bcd1/less/viewdetails.less#L16
Example of use: https://github.com/c2corg/v6_ui/blob/78ef975cae6732c15d369366d210e7b21b6113b8/c2corg_ui/templates/route/view.html#L143

**Comment by stef74** [comment]
@brunobesson @cbeauchesne @asaunier you have reported this point ... do you confirm they already exist (for the 1st point ... because it is old).

**Comment by asaunier** [comment]
@stef74 The last points I have reported are still valid.

Concerning: 
> xreports home page : the map cannot be folded.

There is not map on the xreports home page!?
https://www.camptocamp.org/serac

>￼ On ne peut pas replier la section sur l'application mobile.

Should we really mention problems with the mobile app in this issue? I don't think so.

> should editiion map be expandable? If yes, buttons positioning should be improved

Already fixed by @brunobesson at https://github.com/c2corg/v6_ui/pull/1939

**Comment by stef74** [comment]
@asaunier I think is on search ...

**Comment by brunobesson** [comment]
The same for me (although I didnt check): all points listed should still be valid
