### ISSUE TITLE
action description on mobile

### ISSUE THREAD

**Issue by stef74** [c2corg/v6_ui#1949]
- [ ] on mobile, action description in feed is too long and always ellipsed
![screenshot_20171125-175706](https://user-images.githubusercontent.com/2234024/33503414-ead466b8-d6e3-11e7-8474-2ff42b616f94.png)

**Comment by stef74** [comment]
@cbeauchesne you have reported this point ... how you image to improve it ? 

For me is correct ... show the full text on multiline is not a good idea

**Comment by cbeauchesne** [comment]
are you sure it's me? BTW, i agree that a multiline wouldn't be a goid solution

**Comment by stef74** [comment]
@cbeauchesne i'm not sure ...

**Comment by brunobesson** [comment]
I reported it. The best solution would be to find a shorter text.

But more generally : on mobile, the cards are in a single column so we could remove many ellipses.

**Comment by fbunoz** [comment]
The summary is a short text by definition. But this text can be 2-3 lines, and not only 5 words.
We mustn't reduce the summary to 5 words only to avoid ellipsis on cards.
The design must be adapted to the content, and not the content to the design.
There is no problem to remove ellipsis and to allow several lines on mobile.
On desktop, I think there is no problem : there are already several heights for cards.
We can add a max-height and an overflow scroll or hidden to prevent the case with a long text in the summary (before it is reduced by a modo or an user).

The summary is made to be displayed on cards, list and other places outside the doc itself.

**Comment by stef74** [comment]
for me "action description" is not the summary, it's "bidule a ajouter ..."

Clearly define which text need to be fully displayed and which can be ellipsed on mobile and desktop (sorry but not speicific for each screen size).

But please do a global synthesis.

**Comment by fbunoz** [comment]
To simplify the code and the quality, a summary field has been added on V6, to be displayed in cards as "bidule à ajouter".
It is just for outings that the summary does not exist. We can replace it by infos from data fields, or form "conditions" text field (first 200 char for instance).
