### ISSUE TITLE
Alias for the "translate" directive that would not be extracted

### ISSUE THREAD

**Issue by asaunier** [c2corg/v6_ui#195]
When translating data that are for instance provided by the API (using a mako variable or some angular expression), one cannot use the usual ``translate`` directive because then the variable is added to PO files by the translations extracting tool.

A workaround is to use ``{{mainCtrl.translate('${some_variable}')}}`` since it is not recognized by the extractor. The downside is that we have ``{{ }}`` that appear in the page until the translation is done, wich is ugly.

A solution would be to have an alias for the usual ``translate`` directive that could be use the same way but won't be "extracted" to the PO files.

@tsauerwein has suggested to write something like
```
app.module.directive('translate-enum', angular.module('gettext').directive('translate'));
```

but I get an Closure compiler error:
> ERROR - actual parameter 2 of angular.Module.prototype.directive does not match formal parameter
ERR! compile found   : angular.Module
ERR! compile required: (Array<(Function|null|string)>|Function|null|undefined)
ERR! compile app.module.directive('translate-enum', angular.module('gettext').directive('translate'));

**Comment by tsauerwein** [comment]
As Angular allows to prefix attributes with `x-` or `data-` (see [Directives - normalization](https://docs.angularjs.org/guide/directive#normalization)), we can use `x-translate` which is not extracted:

    <span x-translate>${a["area_type"]}</span>

**Comment by asaunier** [comment]
Really cool! Thanks!

Then we'll have to replace most of the ``{{mainCtrl.translate()}}`` by this ``x-translate``.

**Comment by asaunier** [comment]
I have tested the ``x-translate`` directive and it works as expected:
* translations are done, as with ``translate``
* embedded strings are not extracted to the PO files.

@ginold since you make a lot of changes in the template, you're probably the best one to integrate this ``x-translate`` directive instead of the ``{{mainCtrl.translate()}}`` workarouds, this would avoid conflicts among PR.
