### ISSUE TITLE
Map recenter text field not working properly

### ISSUE THREAD

**Issue by asaunier** [c2corg/v6_ui#1954]
This tool, available in the maps, for instance in the advanced search pages, is based upon the https://photon.komoot.de/ service.

It was broken a few days ago according to https://forum.camptocamp.org/t/probleme-recherche-sur-la-carte/204205

Now it's back but it seems searching on a city no longer works, one get results looking like addresses?
Perhaps something has changed in the service and it must be reconfigured?

**Comment by desnoes** [comment]
> Perhaps something has changed in the service and it must be reconfigured?

Do you know where is-it configured ? which file ?

**Comment by desnoes** [comment]
@asaunier : i found how to correct the bug. I add filtering based on osm tags ('&osm_tag=place:city&osm_tag=place:town&osm_tag=place:village'). The result is fine, all the street's names are removed.
I prepare a PR.

**Comment by desnoes** [comment]
ok on demo
