### ISSUE TITLE
Automatic line break when legend is larger than image size

### ISSUE THREAD

**Issue by cbeauchesne** [c2corg/v6_ui#1969]
When legend is larger than image, the redactor tends to add manual break lines on an arbitrary positioè . This behavior must be automatic.

**Comment by fbunoz** [comment]
The [V5 solution](https://github.com/c2corg/camptocamp.org/blob/master/web/static/sass/_base.scss#L427) : 

    figure.MI {
        display: inline-table;
        max-width: 250px;
    }

Maybe another solution using flexbox ?
