### ISSUE TITLE
Bug when header title is 'global'

### ISSUE THREAD

**Issue by cbeauchesne** [c2corg/v6_ui#1979]
Try this header on a article 

    ## global

Generated id is still used by th UI.

Don't know if the bet way is prefixing ids, or avoid $("#global") js calls.

**Comment by cbeauchesne** [comment]
See ML discussion.

Possible solutuons : 

* prefix ihm ids
* prefix mardown ids
* list all ihm ids, and forbid them in markdown

**Comment by cbeauchesne** [comment]
Adopted solution : prfix id. 

`c2c_`is ok?

**Comment by cbeauchesne** [comment]
UI ids

**Comment by brunobesson** [comment]
OK for `c2c_` prefix.
