### ISSUE TITLE
Tool to create a new document from the currently displayed one

### ISSUE THREAD

**Issue by asaunier** [c2corg/v6_ui#198]
Related to https://github.com/c2corg/v6_ui/issues/191

As in v5, the users should be able to create routes from a WP page, or an outing from a route page.
Outing creation is a bit special since people generally know if they already have created an outing.

For creating a route, in v5 there is a "create a new route" from every summit page:
http://www.camptocamp.org/summits/37511/fr/tete-a-vincent#routes

In v6 we could have the same. But as suggested by @ginold it would make sense that users use the association tool first to figure out if the route does not already exist. If it doesn't, the association tool should provide a "create route" button that would open the route creating form (with the WP pre-associated).
We need to find a way to make this process obvious to users...

**Comment by fjacon** [comment]
to be closed ?
see also #375

**Comment by asaunier** [comment]
Clearly not.

This is a global issue.
For instance how can a user create a new route?
From the advanced search page ? From the simple search widget? From a "create a new route associated to this WP" in the WP detail view pages?

**Comment by stef74** [comment]
@loicperrin @desnoes could you discuss on this point internally ?

**Comment by loicperrin** [comment]
We propose to add a button in the WP detail view pages to create a new route associated to this WP.

**Comment by asaunier** [comment]
> We propose to add a button in the WP detail view pages to create a new route associated to this WP.

Actually we have not placed such a button because we thought that people should search if the route does not already exist, using the association tool.
When searching for an association, if there is no result, the association tool offers buttons to create new associated documents:
<img width="602" alt="capture d ecran 2016-11-05 a 09 43 27" src="https://cloud.githubusercontent.com/assets/1192331/20028838/96e1b618-a33c-11e6-9843-5162ffbf7205.png">

There is still in issue though, because such buttons are only shown if no result can be found, which does not happen that often because the search engine finds a bit too many results I think and because for routes, if the name is quite common and used for other unrelated routes (eg. "face N"), you'll find a bunch of unrelevant results.
Perhaps the "create a new ..." tool should appear after each set of results anyway?

I have created a dedicated issue: https://github.com/c2corg/v6_ui/issues/849

We could also add an explicit button in the list of associated routes (eg. "Add a new route to this WP"), a bit like for routes/outings:
<img width="707" alt="capture d ecran 2016-11-05 a 09 41 09" src="https://cloud.githubusercontent.com/assets/1192331/20028880/69347682-a33d-11e6-97ab-69b3fd20ec8c.png">
but that won't encourage contributors to check first if the route already exists.

**Comment by loicperrin** [comment]
>We could also add an explicit button in the list of associated routes (eg. "Add a new route to this WP"), a bit like for routes/outings:

I think that this is the best solution. Normally people will check that the route does not exist in the list before creating it. People will do not think to try to associate a route to add a new one (it is not very logical).
There can be problems for WP/Access or WP/hut, as there are not always associated to eache relevant route. A solution could be to add the button only on WP/summit, but it is a bit more complicated.

**Comment by fbunoz** [comment]
> such buttons are only shown if no result can be found

No, they are always shown on the demo.

> People will do not think to try to associate a route to add a new one (it is not very logical).

A solution is to rename the tool : "Add an association or create a new route linked to the current" (or a name like that :-).
It implies that the search on key word return only the routes around the current WP (in a radius of 20km for instance). It is also useful for a simple association.

**Comment by stef74** [comment]
@fjacon when this issue is planned ? Is not blocking ... but important in term of ergonomy
