### ISSUE TITLE
Remove id attributes from element added into TOC

### ISSUE THREAD

**Issue by cbeauchesne** [c2corg/v6_ui#1980]
Otherwise, user anchors on headers are useless...

**Comment by cbeauchesne** [comment]
Well, raw Html is replaced for parsing by placeholders. It means that we need to do a early post-processing and parse Html fragment, with all incertitud it means.

It's far mor reliable to do a custom extension that handle the old-good {#id}

**Comment by brunobesson** [comment]
OK.
