### ISSUE TITLE
Design of text subtitle

### ISSUE THREAD

**Issue by fbunoz** [c2corg/v6_ui#1982]
The subtitle design must be improved : 

- add margin
- use decreasing font size since h2 (# tag) to h6 (##### tag), with h6 size equal to body text size (today h5 size is smaller than body text !)

**Comment by RichardWeng** [comment]
Hi,
Some questions about that: 

1. h1 and h2 cannot be used by contributors, correct ?
1. I can't find where h2 is used.
1. Do you know an article where all title levels (h3 to h6) are used ?
1. Title sizes are defined in em on Discourse, but in px on the topoguide. Should I define them in em for the topoguide too ?
1. When I try to put an h6 title (`#####Niveau 4`) in an outing or in an article, I get this: ` <h6 id="niveau-4">Niveau 4</h6>`

**Comment by brunobesson** [comment]
You could use the demo to create articles as you wish. He topmost level is #.
I believe there is a fix for h6 which is not yet propagated on the demo, but using dev tools you could manually add one yourself.

As for em vs px, I would in all cases avoir em and rather use remove.

**Comment by RichardWeng** [comment]
ok thanks

**Comment by cbeauchesne** [comment]
on point 5 it's a bug, it will be fixed by next release

**Comment by fbunoz** [comment]
A first draft : 

![test_niveaux_de_titres_-_2018-01-24_21 12 09](https://user-images.githubusercontent.com/3902555/35354742-0184cf0e-0143-11e8-9825-262729939611.png)

```
.viewdoc .ficontent h2 {
    font-size: 2em;
    margin: 1.5em 0 0.5em;
    font-weight: bold;
}
.viewdoc .ficontent h3 {
    font-size: 1.5em;
    margin: 1.1em 0 0.4em;
    font-weight: bold;
}
.viewdoc .ficontent h4 {
    font-size: 1.2em;
    margin: 1.2em 0 0.5em;
    font-weight: bold;
}
.viewdoc .ficontent h5 {
    font-size: 1.1em;
    font-weight: bold;
    margin: 1em 0 0.2em;
}
.viewdoc .ficontent h6 {
    font-size: 1em;
    font-weight: bold;
    margin: 1em 0 0;
}
```

**Comment by loicperrin** [comment]
> A first draft :

OK for me.

**Comment by brunobesson** [comment]
>All text sizes must be defined in em.

That's nonsense.

**Comment by fbunoz** [comment]
> That's nonsense.

You don't understand how the font size works.

The basic font-size is defined on "body" at 14px.
When we define a font-size for a sub block of body at 1.5em, the browser set the size to 1.5 * 14 = 21px.
If we change the basic font size, all sizes keep the same ratio about the basic size.
We should alsso change the basic font-size to use em instead of px
Read the guidelines in this article : https://www.alsacreations.com/article/lire/563-gerer-la-taille-du-texte-avec-les-em.html

**Comment by brunobesson** [comment]
Please... Have you read what I wrote? 
Do you know the difference between em and rem ?
What you are describing is precisely the behaviour of rem units.I am not in favor of px units nor em, but rem.

**Comment by fbunoz** [comment]
New version using rem for font-zize (and em for margin; it's better).

To work correctly, we must add a font-size on html tag, because rem use html tag font-size as reference, and not body. For now, font-size is 10px on html and 14px on body, then a rem on subtitle is not proportional to text size.

```

html {
	font-size: 100%;
}

body {
	font-size: 100%;
}

.viewdoc .ficontent h2 {
    font-size: 2rem;
    margin: 1.5em 0 0.5em;
    font-weight: bold;
}
.viewdoc .ficontent h3 {
    font-size: 1.5rem;
    margin: 1.1em 0 0.4em;
    font-weight: bold;
}
.viewdoc .ficontent h4 {
    font-size: 1.2rem;
    margin: 1.2em 0 0.5em;
    font-weight: bold;
}
.viewdoc .ficontent h5 {
    font-size: 1.1rem;
    font-weight: bold;
    margin: 1em 0 0.2em;
}
.viewdoc .ficontent h6 {
    font-size: 1rem;
    font-weight: bold;
    margin: 1em 0 0.2em;
}

.viewdoc .ficontent h2:first-child,
.viewdoc .ficontent h3:first-child,
.viewdoc .ficontent h4:first-child,
.viewdoc .ficontent h5:first-child,
.viewdoc .ficontent h6:first-child,
.viewdoc .ficontent h2 + h3,
.viewdoc .ficontent h3 + h4,
.viewdoc .ficontent h4 + h5,
.viewdoc .ficontent h5 + h6
{
    margin-top: 0.6em;
}

```

**Comment by loicperrin** [comment]
It does not concern subtitles, but a higher margin-top for paragraphs would be better. I propose: 
```
  p {
    margin-top: 10px;
    margin-bottom: 0;
}
```
On demo, the font size seems to be higher than in production, but this seems not due to recent modifications.

**Comment by fbunoz** [comment]
There is a logic in top/bottom margin : all blocks used in a text field (p, ol, ul, ...) have a bottom margin, and not a top margin.
We can change to a top margin, but for all block types, not only p.
But I think it's not necessary to change.
We can just use a 0.5em bottom margin for all block types (avoid px margin for text design).

In the CSS, there are 2 rules for p bottom margin. Some clean is useful.

**Comment by loicperrin** [comment]
> We can just use a 0.5em bottom margin for all block types (avoid px margin for text design).

Ok for this if the effect is to have a more higher margin between 2 paragraphs (that is the initial need).
Can someone report this in the CSS?

**Comment by stef74** [comment]
@loicperrin this ticket is in demo ... so we have to validated it or not. If some evolution is needed a new ticket must be opened.

**Comment by brunobesson** [comment]
I am closing this issue, fixed on demo. @loicperrin @fbunoz please open another issue for the additional issues, as stated by @stef74
