### ISSUE TITLE
WP show page crashing because of reprojection

### ISSUE THREAD

**Issue by asaunier** [c2corg/v6_ui#20]
The WP detail page returns a 500 Server Error with the following message in the logs:

> [Thu Nov 05 14:50:00.508357 2015] [wsgi:error] [pid 8146] [client 10.27.71.4:46254] Truncated or oversized response headers received from daemon process 'c2corg_ui-ui': /var/www/vhosts/c2cassoc_c2corgv6/private/v6_ui/apache/app-c2corg_ui.wsgi

Only when serving pages with Apache/mod_wsgi. OK with pserve.

The crash is triggered by the use of the reprojection function "transform" in the template:
https://github.com/c2corg/v6_ui/blob/master/c2corg_ui/templates/waypoint/view.html#L6

Actually using this function directly in the Pyramid view also makes the page crash. I have tried to isolate the guilty line and it seems it is related to `pyproj.Proj`:

```
source_proj = pyproj.Proj(init=source_epsg)
```

https://github.com/c2corg/v6_ui/blob/master/c2corg_ui/views/document.py#L78
If this line or the next one (defining the destination projection) is used (even though no reprojection is finally done), we get the error.

**Comment by tsauerwein** [comment]
Something to test (`threads=1`):

    WSGIDaemonProcess c2corg_ui-{instanceid} python-path={site_packages} threads=1

in https://github.com/c2corg/v6_ui/blob/master/apache/wsgi.conf.in

**Comment by asaunier** [comment]
I have added ``threads=1`` to https://github.com/c2corg/v6_ui/blob/master/apache/wsgi.conf.in#L2 in the main dev instance but I still get the same error when loading the WP detail page (with the transform function).

**Comment by gberaudo** [comment]
The issue does not appear on my machine (Apache + installed ui).
libapache2-mod-wsgi 4.3.0-1build1
apache2 2.4.12-2ubuntu2

On demo:
libapache2-mod-wsg 4.3.0-1
apache2 2.4.10-10+deb8u3

**Comment by asaunier** [comment]
Perhaps an issue with the versions of pyproj/apache2/libapache2-mod-wsgi on the dev server since it works on your computer.

apache2 and libapache2-mod-wsg versions are the ones quoted in 
https://packages.debian.org/fr/jessie/libapache2-mod-wsgi
https://packages.debian.org/fr/jessie/apache2

Perhaps we could try using another version of python-pyproj.

https://packages.debian.org/fr/jessie/python-pyproj mentions 1.8.9-1.1
We use the last version: 1.9.4 https://pypi.python.org/pypi/pyproj

**Comment by asaunier** [comment]
To prevent the demo instance from crashing I have just disabled the reprojection in the WP view page: 45c701bf4a0beef67afe08f1569e4fa217bc1afe

It's a temporary change, until we find a solution.

**Comment by mfournier** [comment]
The `Truncated or oversized response headers received from daemon process` reminds me of an issue I encountered with apache several years ago. If I remember correctly, some sort of limit was hardcoded in a `#define` in apache, although it was a configuration tunable in nginx.

If this is the same sort of issue, it looks like gunicorn offers a couple of buttons we could try turning:
http://docs.gunicorn.org/en/latest/settings.html#security

Is the problem isolated and easily reproduicible ? If we can intercept these problematic headers with tcpdump, it will be easier to understand what sort of limit is hit and which piece of software is truncating the data.

**Comment by asaunier** [comment]
> Is the problem isolated and easily reproduicible ?

With apache/mod_wsgi it seems to me the problem always occured when calling a waypoint page such as http://c2corgv6.demo-camptocamp.com/waypoints/37737/fr when commit https://github.com/c2corg/v6_ui/commit/45c701bf4a0beef67afe08f1569e4fa217bc1afe is reverted.

Currently the above page fails, perhaps because I tried to revert the change but I am not sure gunicorn has been restarted to take the change into account. See https://github.com/c2corg/v6_ui/pull/83#issuecomment-228756831

**Comment by asaunier** [comment]
The problem can still be reproduced when reverting 45c701b even with tha recent changes adding gunicorn (but apache seems to be sill used) https://github.com/c2corg/v6_ui/pull/83

No error appears in the apache logs (perhaps reported somewhere else) but I get a 500 error when trying to use the reprojected geometry in the mako templates.

**Comment by tsauerwein** [comment]
We could try directly with the Python GDAL bindings: http://gis.stackexchange.com/a/78850/3328

**Comment by tsauerwein** [comment]
Or use a formula from here: http://wiki.openstreetmap.org/wiki/Mercator

**Comment by tsauerwein** [comment]
Or we first test with Docker, because that will be how we will use it at the end.

**Comment by asaunier** [comment]
> Or we first test with Docker, because that will be how we will use it at the end.

Testing with the final infra would make sense indeed. Because it's a bit weird that we cannot use pyproj (actually the crash occurs when instanciating a pyproj object).

**Comment by fjacon** [comment]
I cannot reproduce today on http://www.demov6.camptocamp.org/
@asaunier can you ?

**Comment by asaunier** [comment]
> I cannot reproduce today on http://www.demov6.camptocamp.org/

No surprise because the reprojection has been disabled: https://github.com/c2corg/v6_ui/blob/master/c2corg_ui/templates/waypoint/view.html#L25-L27

Currently the coordinates are shown using the 3857 projection instead of lon/lat:
![sans titre](https://cloud.githubusercontent.com/assets/1192331/20133018/0c334d56-a666-11e6-907c-b7fc9eb69e92.png)
which is not really relevant.

I haven't tested recently (and not on the exoscale server) but we always had the problem on the demo instance of the dev server.
Possible workarounds:
* make a JS reprojection instead of using python
* do not show this attribute

**Comment by tsauerwein** [comment]
> Possible workarounds:

Or use this formula directly: http://wiki.openstreetmap.org/wiki/Mercator#Python
