### ISSUE TITLE
xreport and waypoint : move area block in "Infos" block

### ISSUE THREAD

**Issue by fbunoz** [c2corg/v6_ui#2023]
See these doc : 
https://www.camptocamp.org/xreports/972990/fr/avalanche-mont-de-l-etoile
https://www.camptocamp.org/waypoints/103699/fr/orpierre-quiquillon
The text is masked by the localisation post-it.

The localisation info should be moved into "informations" block, as for outings and routes.

**Comment by cbeauchesne** [comment]
Images are impacted too.
