### ISSUE TITLE
Discourse/API login seems broken

### ISSUE THREAD

**Issue by asaunier** [c2corg/v6_ui#203]
If a user logs in in the UI, he is not authenticated in the forum.
When clicking on the "login" button in the forum, the user is redirected to the UI auth page but the login fails saying that "discourse login failed".

Perhaps a config problem?

**Comment by gberaudo** [comment]
I updated the discourse sso secret. It should be fixed now.

**Comment by asaunier** [comment]
Thanks @gberaudo it is now possible to login both from the UI or from the forum and be recognized when browsing in either the UI or the forum.

On the other hand the log out is not propagated:
* when clicking the "Log out" button in Discourse, one is logged out in Discourse but not in the UI.
* when clicking the "Log out" button in the UI, one is logged out in the UI but not in Discourse.

**Comment by gberaudo** [comment]
The first point is expected.
The second point is a mismatch of the API key. See https://github.com/c2corg/v6_api/pull/160.

**Comment by asaunier** [comment]
@gberaudo OK for closing this issue? The logout issue is described here I think https://github.com/c2corg/v6_forum/issues/5
