### ISSUE TITLE
Handle document URLs with no lang param

### ISSUE THREAD

**Issue by asaunier** [c2corg/v6_ui#204]
In v5 documents [1] may contain other document URLs with no lang parameter (only the doc type and the doc id) [2].

Such URLs redirect to the "most appropriate" lang version (depending on the lang prefs and the available lang versions). A similar behaviour is needed in v6.

By the way document URLs should contain slugs (but the current version with no slug should also work). See https://github.com/c2corg/v6_ui/issues/109

[1] for instance http://www.camptocamp.org/summits/37355/fr/mont-blanc
[2] for instance http://www.camptocamp.org/routes/55289

**Comment by tsauerwein** [comment]
From the API this should already be ok: If a language is given as parameter, associated documents include the "best" language.

**Comment by asaunier** [comment]
When such a URL is called, we would need to make a request to the API to get the list of available lang for the given document and make a 301 "Moved permanently" redirection to the URL with the most appropriate lang (+ slug). If there's only one lang available, the choice is easy. If several, we would take the priority listed here https://github.com/c2corg/v6_common/blob/master/c2corg_common/attributes.py#L2 
Makes sense? Feasible?

**Comment by tsauerwein** [comment]
This works already. For example when you request `/waypoints/38575?l=fr`, associations will include the French translation or the 2nd "best" translation.

    {
      "waypoint_type": "summit",
      "associations": {
        "waypoints": [...],
        "recent_outings": {
          "total": 27,
          "outings": [{
            "locales": [{
              "lang": "fr",                         <-- outing in french
              "version": 1,
              "title": "Aiguilles de Chamonix (et envers des aiguilles)\u00a0: Travers\u00e9e des Aiguilles de Chamonix S-N"
            }],
            "activities": ["mountain_climbing"],
            "version": 1,
            "date_start": "2014-07-16",
            "author": {
              "user_id": 4960,
              "username": "pgatta"
            },
            "document_id": 543208,
            "date_end": "2014-07-16",
            "available_langs": null
          }, {
            "locales": [{
              "lang": "en",                    <-- outing in the 2nd best locale
              "version": 1,
              "title": "Aiguilles de Chamonix: Travers\u00e9e des Aiguilles de Chamonix S-N"
            }],
            "activities": ["mountain_climbing"],
            "version": 1,
            "date_start": "2010-07-26",
            "author": {
              "user_id": 230990,
              "username": "nielsvanveen"
            },
            "document_id": 231002,
            "date_end": "2010-07-26",
            "available_langs": null
          }, ..
          ]
        },
       ...
      "document_id": 38575
    }

**Comment by tsauerwein** [comment]
As discussed with @asaunier: When calling `/{document_type}/{document_id}` (without `lang`, for example `/waypoints/123`), a redirect should be made to the *best* locale. On the UI server-side, a request is made to the API to get the available locales for a document (such web-service has to be added to the API). Then using the cookie which contains the interface language, the *best* locale is chosen and a redirect to e.g. `/waypoints/123/fr/slug` is made.

To avoid problems with Varnish, this view is not cached.
