### ISSUE TITLE
fat finger on licence id attribute on route page

### ISSUE THREAD

**Issue by cbeauchesne** [c2corg/v6_ui#2042]

**Comment by brunobesson** [comment]
what does this mean?

**Comment by cbeauchesne** [comment]
https://github.com/c2corg/v6_ui/blob/master/c2corg_ui/templates/helpers/view.html#L21

data -target is licence, and id is license

Both spelling are good, but they must be the same.

**Comment by brunobesson** [comment]
One is french,the other one English, AFAIK. But I must be the one responsible for this typo...

**Comment by cbeauchesne** [comment]
licence is british english :)
