### ISSUE TITLE
Compilation error in search.js?

### ISSUE THREAD

**Issue by asaunier** [c2corg/v6_ui#206]
When running ``make build`` I notice a non-blocking error in the console:
```
info closure-util Compiling 419 sources
ERR! compile /home/alex/v6_ui/c2corg_ui/static/js/search.js:29: WARNING - parameter $ does not appear in <anonymous>'s parameter list
ERR! compile         function(scope, element) {
ERR! compile         ^

```

**Comment by tsauerwein** [comment]
This does not look right:
https://github.com/c2corg/v6_ui/blame/master/c2corg_ui/static/js/search.js#L27

**Comment by asaunier** [comment]
> This does not look right:

Indeed. I will update my PR to fix it as well.
