### ISSUE TITLE
Picto are not dispalyed

### ISSUE THREAD

**Issue by desnoes** [c2corg/v6_ui#2065]
When searching eg. a route or a waypoint, the pictos of the items contained in the map area are not displayed.

**Comment by brunobesson** [comment]
All pictos have disappeared. I assume I must be responsible for it, and because I seem the only one to be available lately, I didn't give you time to test the demo. Sorry guys.
I'll have a look ASAP.

**Comment by desnoes** [comment]
@brunobesson : i am available for testing. Just tell me.
