### ISSUE TITLE
Images cannot be edited

### ISSUE THREAD

**Issue by desnoes** [c2corg/v6_ui#2073]
The last version has introduced a bug. It is not possible to edit some images.
See for instance the images in this outing: https://www.camptocamp.org/outings/984991/fr/col-de-la-petite-vaudaine-depuis-casserousse#&gid=1&pid=2
or
https://www.camptocamp.org/images/985704/fr/cima-di-solda-en-1900-par-photoglob

**Comment by cbeauchesne** [comment]
i can't reproduce the bug on my dev env, anyone does?

**Comment by brunobesson** [comment]
I'll have a look tonight

**Comment by brunobesson** [comment]
This may be related to the (my) updates to python libs.
See #2076

**Comment by desnoes** [comment]
Ok on demo
