### ISSUE TITLE
bootstrap-slider should not be selectable in filters

### ISSUE THREAD

**Issue by FabriceSalvaire** [c2corg/v6_ui#2074]
else nasty things appear like selection of the values and drag-and-drop of the slider ...

Fix to apply to the slider and values :

```
-webkit-user-select: none; /* Safari */        
-moz-user-select: none; /* Firefox */
-ms-user-select: none; /* IE10+/Edge */
user-select: none; /* Standard */
```

**Comment by brunobesson** [comment]
Could you more explicit about the nasty things? I do not understand how to reproduce them.

**Comment by FabriceSalvaire** [comment]
@brunobesson 

J'ai réimplémenté un range slider en m'inspirant du code de c2c. Sous Firefox 59, j'ai observé plusieurs problèmes en testant la réactivité de l'interface:

* sélection du texte environnent lorsqu'on déplace le curseur au delà du slider,
* un drag du slider et
* un déplacement du curseur lié au mouvement de la souris

*que je ne sais pas reproduire de manière systématique*, il faut en gros s’énerver sur la souris ...

Tout cela semble avoir disparu en appliquant un  **user-select: none** qui ne coûte rien

Mon explication est qu'il y a des interférences entre les mouse events, le comportement par défaut du browser et le fonctionnement attendu d'une UI.

**Comment by FabriceSalvaire** [comment]
quelques copies d'écran, pour le 3ème point il faudrait une vidéo, grosso modo il faut déplacer le curseur, sortir du div pour initier un drag, relâcher le bouton, ensuite le curseur continue à bouger avec la souris ... 

Le curseur n'est pas centré verticalement ???

![c2c-slider-1](https://user-images.githubusercontent.com/2358471/38626379-bb1eb7d6-3dac-11e8-9690-d0974fc82d0c.png)

![c2c-slider-2](https://user-images.githubusercontent.com/2358471/38626419-d1af9970-3dac-11e8-9d76-6a4ff1a12a3f.png)

![c2c-slider-3](https://user-images.githubusercontent.com/2358471/38626381-bd03fc96-3dac-11e8-9e65-51bf28b68be7.png)

**Comment by brunobesson** [comment]
OK, thanks, got you point. I'll provide a PR for this point. Concerning the vertical centering of bullets, there is also an ongoing PR, it should be fixed soon.

**Comment by FabriceSalvaire** [comment]
No autoprefixer ?

**Comment by brunobesson** [comment]
@FabriceSalvaire nope, this is not enabled on this project yet. Feel free to provide a MR if you like :wink:

**Comment by desnoes** [comment]
@brunobesson @FabriceSalvaire : I cannot reproduce the bug. I consider the bug is fixed.
