### ISSUE TITLE
Comments about document view page (detailed view)

### ISSUE THREAD

**Issue by asaunier** [c2corg/v6_ui#209]
Issues reported about the current presentation/organisation of the document view pages:

_(to be continued)_

## Short info (figures) section

* [x] maps info takes too much room => this is a minor info => every map should fit on a single line, no need to bold the editor name (by the way the map ``code`` is missing).
*  [ ] "short" attributes should not be displayed on distinct lines => we need to group them by meaning (for instance ratings would have a line, elevations another, etc.). A little like the ratings shown in the outings (see http://www.camptocamp.org/outings/694820/fr/mont-blanc-arete-des-bosses) on the contrary of the ratings shown in the routes pages in v5 (see  http://www.camptocamp.org/routes/53781/fr/mont-blanc-arete-des-bosses). To make the info more explicit we would need pictos instead of strings (+ showing the strings as tooltips). _[To be confirmed for ratings since there are many of them and not all very explicit...]_
*  [x] multi-select attributes (activities, best periods, route types) should as far as possible be shown on a single line, not as bullet lists.
*  [x] for activities pictos should be used
*  [x] Some info should only be displayed when true. For instance "lift acces" => if there is no lift access, it's no use saying so, only when such a possibility is available. In that case we don't need to say "lift access: yes", simply "lift access". On the other hand some other yes/no attributes must be displayed if set, whatever the value. For instance for huts: wardened? has blankets? etc.)
*  [ ] gear: the text attribute is displayed in the text section ("description") whereas some related info ("glacier_gear") is placed in the "figures" => all gear data should be at the same place. By the way depending on some route attributes (activities, some ratings), automatic gear links should be displayed as well. For instance http://www.camptocamp.org/routes/48864/fr/rochers-de-la-couarra-voie-normale => autolink "Ski and snowboard touring, snowshoeing"

Suggestion for displaying activities and ratings:
*  [ ] show activity icons on a dedicated line for each activity
*  [ ] on each activity line, show the ratings concerned by the activity
*  [ ] nice to have (?!): be able to unfold the rating lines to explicitly have the ratings names displayed on separated lines

## Associated docs

*  [x] route cards should contain the ``title_prefix`` as well _(to be discussed: it is a bit complicated...)_

## Map

*  [x] a little bigger in height??
*  [x] the postit pin is ambiguous: one may think the postit will move with the map => what about removing the pin and only show the postit?

**Comment by asaunier** [comment]
* [ ] associated docs cards are not clickable (unless one clicks on the text) in WP detail views

**Comment by asaunier** [comment]
I have updated the todo list and checked points that are now done.

**Comment by ginold** [comment]
I have most likely already fixed it in my current pr. That was due probably because a card had no content but the title, now there are icons or elevation info that take more space and therefore you can click wherever you want on the card.

**Comment by ginold** [comment]
@asaunier are the remaining points still valid ? are they in accordance with client's wishes or have they changed since?  ( and what about "nice to have" and "suggestions"?)

**Comment by asaunier** [comment]
This issue is quite old with points not very consistent with other issues created in the meantime, it's better to close it.
