### ISSUE TITLE
Menu layout and content

### ISSUE THREAD

**Issue by asaunier** [c2corg/v6_ui#210]
Layout: see Altimax

Content to add:
* banner block
* footer/disclaimer/partners block
* moving the interface lang selector to the menu (as in the wireframes) would make sense (the string "browse site in" is needed to help clarifying it's not the document lang version selector).
* what about moving the social networks links here as well?

**Comment by asaunier** [comment]
The banner block should use a standard size. See http://blog.kinoa.com/wp-content/uploads/2013/06/format_publicite_internet_netoides1.jpg

Most likely 160x320.

What's the actual banner size in Altimax' layout?

**Comment by ginold** [comment]
I use a standard size (16/9) already, it's just not 160x320px because our menu isnt' that wide max 250px).

**Comment by asaunier** [comment]
We need to use an official banner size. See http://blog.kinoa.com/wp-content/uploads/2013/06/format_publicite_internet_netoides1.jpg for examples.

> 160x320px because our menu isnt' that wide (max 250px).

160px is the width here.

**Comment by ginold** [comment]
*320x160 :) our is 240px on 135px 16/9

**Comment by asaunier** [comment]
* [ ] The client told me that the logo of Fondation Petzl is not required. It will appear in some of the banners.
Than it can be removed from the menu.

**Comment by asaunier** [comment]
* [ ] The URLs of Facebook and Twitter buttons are the ones of Camptocamp SA (G+ is OK). The correct URLs are https://twitter.com/camptocamporg and https://www.facebook.com/camptocamp.org/

**Comment by asaunier** [comment]
* [ ] Having a clearer background-color (white?) for the simple search input would make it more visible and nicer.
