### ISSUE TITLE
rock type filter is not displayed if via errata activity is selectionned

### ISSUE THREAD

**Issue by cbeauchesne** [c2corg/v6_ui#2108]

**Comment by brunobesson** [comment]
@cbeauchesne could you provide an example? I tested both editing and viewing, and this is working for me...

**Comment by cbeauchesne** [comment]
Here available filters with https://www.camptocamp.org/routes#act=via_ferrata : 

![image](https://user-images.githubusercontent.com/11915659/40574439-3fc7b0bc-60d2-11e8-9f42-55488733652a.png)

rock_type should be visible.
