### ISSUE TITLE
Topoguide migrating : abstract tag

### ISSUE THREAD

**Issue by fbunoz** [c2corg/v6_ui#213]
The current script to migrate the topoguide, detects the [abs] tags to put the content into the new abstract field.
In the V5, there are 2 tags to define an abstract : [abs] and [abstract]. They are decoded in the same html code. "abs" is only a shortcut for "abstract".
The content between [abstract] tags must be migrated as the [abs] tags.

**Comment by tsauerwein** [comment]
Thanks for reporting! I moved the ticket to https://github.com/c2corg/v6_api/issues/165
