### ISSUE TITLE
Spelling piolet in the aid text

### ISSUE THREAD

**Issue by BorutK** [c2corg/v6_ui#2163]
Suppress the **s** in "piolets" in the third sentence of the aid text of the Specific gear section which appears when creating a new Route document (fr).

![image](https://user-images.githubusercontent.com/23487253/44199382-40b12780-a144-11e8-98ce-bf591d55c000.png)

It should read:

> ...DVA, sonde, crampons, piolet, matériel de...

or maybe even better (putting "piolet" before "crampons"):

> ...DVA, sonde, piolet, crampons, matériel de...

**Comment by brunobesson** [comment]
This is a transifex (i18n) issue, not an UI issue. I made a suggestion (couldn't save it, because I have not enough rights).

@desnoes could you give me more access rights so that I can submit such modifications?

**Comment by desnoes** [comment]
@brunobesson: i cannot give you the access rights, i do not have the rights. @asaunier: can you do that ?
I can do the modification on transifex tonight.

**Comment by desnoes** [comment]
i will check at home. I have a bug with Transifex at the office. This is the second time i find a huge number of untranslated items (~330!!), which does not corresponds to reality.

**Comment by asaunier** [comment]
> This is the second time i find a huge number of untranslated items (~330!!),

I observe this too:
1275
Toutes
330
Non traduites
0
Non révisées

**Comment by brunobesson** [comment]
Appart from the rights on transifex, this issue is now solved.
