### ISSUE TITLE
Add warning message/control about "revision comment" length

### ISSUE THREAD

**Issue by mgerbaux** [c2corg/v6_ui#2179]
When editing a doc, if the field to describe modification is more than 200 characters, the modification cannot be saved and there is the warning message "unexpected error : please consult the server logs".

But is is very hard for contributor to find what is wrong with its contribution !

**Comment by asaunier** [comment]
2 things are needed:
* add a check on the API side that would either return an error if length > 200 or cut the message off to 200 chars
* add a restriction to the HTML field in the UI side (most likely add a ``maxlength="200"`` attribute to the editing form

**Comment by cbeauchesne** [comment]
Seems to be close, @asaunier @brunobesson do not hesitate to reopen if I'm wrong
