### ISSUE TITLE
Forum topics integration (comments page)

### ISSUE THREAD

**Issue by gberaudo** [c2corg/v6_ui#219]
https://meta.discourse.org/t/embedding-discourse-comments-via-javascript/31963

**Comment by tsauerwein** [comment]
This is for the comment section below documents?

**Comment by gberaudo** [comment]
Yes

**Comment by gberaudo** [comment]
The official way to embed discourse is by using an iframe as explained in the link above.
Then, there are two possibilities:
- automagics where Discourse automatically creates the topic / first post with some content magically
  crawled from the UI document (seems a bad idea and did not worked when tested);
- providing a reference to an existing topic (worked OK, tested with an existing topic).

**If there is no topic yet**
A new feature of Discourse is the possibility to create a new topic with a URL:
`/new-topic?title=123434_fr&category=commentaires du topoguide/comments`.
That would be good if we were able to prevent the user to mess with the pre-filled title
and the choice of the category.
The alternative is to have the API create a fake first message and continue with the case where the topic already exists.

**If there is already a topic**
When a topic already exists for the document + locale, then we can embed the comments
using an iframe. The user is able to continue the discussion by clicking on a button and being
redirected to the forum. The problem is that we do not know the topic id and there is nothing
convenient in Discourse to retrieve it from the browser.
The topic id can be found in a redirect (see https://meta.discourse.org/t/accessing-a-specific-topic-from-a-user-script/24901); exporting a small proxy on the API would do the trick.

**Comment by ginold** [comment]
related to #458
