### ISSUE TITLE
Use minified files for ui-bootstrap

### ISSUE THREAD

**Issue by asaunier** [c2corg/v6_ui#231]
When loading a page, unminified files ``ui-bootstrap.js`` and ``ui-bootstrap-tpls.js`` are downloaded.
We should use the ``.min.js`` versions in non-debug mode.

**Comment by ginold** [comment]
apparently there are no mimified files in angular-bootstrap, should we mimify them ourself?

**Comment by tsauerwein** [comment]
Maybe the idea is to create a custom build which only contains the components that you actually need? https://angular-ui.github.io/bootstrap/

**Comment by asaunier** [comment]
That would make sense indeed!
We do need minified files with only the minimal used code.

**Comment by ginold** [comment]
ok, will do it in another pr. So where will i put those mimified custom js?
that can't be node_modules (we will have to remove the ui-boostrap line
from package.json), nor static/js where we have only our stuff. Or can we?
could be nice if we could download custom builds with npm 🤔

On Wed, Mar 16, 2016 at 7:02 PM, Alex Saunier <notifications@github.com>
wrote:

> That would make sense indeed!
> We do need minified files with only the minimal used code.
>
> —
> You are receiving this because you were assigned.
> Reply to this email directly or view it on GitHub
> <https://github.com/c2corg/v6_ui/issues/231#issuecomment-197460336>
>



-- 

*Adam Gina*JavaScript Developer
adam.gina@camptocamp.com

*Camptocamp SA*EPFL Innovation Park
Bâtiment A
1015 Lausanne

Tel + 41 21 619 10 10
http://www.camptocamp.com

**Comment by asaunier** [comment]
Doing a dedicated PR would indeed make sense.
No clue if one can get custom builds with npm. If not, perhaps we could save them in some subdir of ``static/``? @tsauerwein @gberaudo what do you think?

**Comment by tsauerwein** [comment]
`static/lib` sounds ok for me. Please add a short readme on how the ui-bootstrap files were created.

**Comment by gberaudo** [comment]
+1 for `static/lib sounds`.
