### ISSUE TITLE
Use ?a=0 option to request data for edition

### ISSUE THREAD

**Issue by tsauerwein** [c2corg/v6_ui#233]
With https://github.com/c2corg/v6_api/pull/149 it is now possible to request data for the edition page without associations and area. E.g. `/waypoints/38575?a=0`.

**Comment by fjacon** [comment]
Are we going to use it ?

**Comment by asaunier** [comment]
Is this issue still valid?
Hasn't ``?a=0`` been replaced by ``?e=1``? I think I have used it in the editing directive.
https://github.com/c2corg/v6_ui/blob/master/c2corg_ui/static/js/apiservice.js#L207-L211

**Comment by tsauerwein** [comment]
Yes right, it is `e=1` [now](https://github.com/c2corg/v6_api/blob/65241c6/c2corg_api/views/waypoint.py#L148-L150).
