### ISSUE TITLE
Feedbacks on route editing

### ISSUE THREAD

**Issue by asaunier** [c2corg/v6_ui#234]
(more to come)

* [x] Icons for activities "escalade" and "rocher haute montagne" are switched
* [x] Icon for activity "mountain bike" is missing (at least in the demo)

**Comment by ginold** [comment]
probably because of the corrected typo in 'moutain biking'

**Comment by asaunier** [comment]
Same problem than for waypoint editing (see https://github.com/c2corg/v6_ui/issues/242#issuecomment-199018593) => fields groups are sometimes not relevant + too many steps.

Here is a recommendation (similar to WP editing):

* step 1: text attributes and map
 * title
 * lang
 * map (should be big enough to draw a route) + a file upload field to upload a GPS track
 * summary
 * description (big enough to type a lot of text)
 * remarks
 * gear
* step 2: figures
 * activities
 * "figures" attributes depending on the activities
* step 3: associations...
* step 4: preview

**Comment by ginold** [comment]
i still don't know where to put : 

glacier_gear 
locales.slope
ski_exposition
hiking_mtb_exposition
lift_access

**Comment by asaunier** [comment]
* [ ] attributes "route_configuration_types", "duration_types" and "glacier_gear" are not required attributes, whatever the activity, see https://github.com/c2corg/v6_common/blob/master/c2corg_common/fields_route.py

* [ ] "Elévation min" => this attribute name or translation looks weird.

* [ ] Not sure what causes the error, but when editing an existing route, one gets the following error:
> "None" is not a mapping type: Does not implement dict-like functionality.

* [ ] "duration_types": this attribute (available in the editing form) does not exist in the model. The real name is "durations" and it's a multi-select field: https://github.com/c2corg/v6_api/blob/master/c2corg_api/models/route.py#L64

**Comment by asaunier** [comment]
Discussed with the client, here is a proposal for the route editing form structure:

### step 1

title + lang
activities

### step 2

map + upload GPX
associations of WP and routes

### step 3

(configuration => or maybe in step1 if that's too many items in step3)

orientations
route_types
route_configuration_types
(climbing_outdoor_types)
(rock_types)

("numbers" => we must find another name, "numbers" does not mean much)
altitudes
deniv
longueur

(ratings)
cotations ...
exposition ...
slope

### step 4

summary
description
remarks
gear + glacier_gear
route_history
external_resources (biblio) + associations livres

quality

### step 5

preview

**Comment by ginold** [comment]
is `duration_types` attribute the same as `duration` in outing? 
is it also a select-multiple tag?

**Comment by tsauerwein** [comment]
For outings, `duration` is the duration in minutes. And for routes it is a multi-select of these values: https://github.com/c2corg/v6_common/blob/master/c2corg_common/attributes.py#L287-L299

**Comment by fbunoz** [comment]
A route should have a field "duration_difficulties", with the same format as for outings.
But if it is not done, it will be completed by the association.

**Comment by asaunier** [comment]
> for routes it is a multi-select of these values: https://github.com/c2corg/v6_common/blob/master/c2corg_common/attributes.py#L287-L299

In days!

For an outing there is 3 duration/timing fields:
* ``duration = Column(SmallInteger)`` ("Durée totale de la sortie" in the google docs)
* ``duration_difficulties = Column(SmallInteger)`` ("Temps de parcours des difficultés")
* ``timing = Column(String)`` ("Heure de départ et de passage")

See
https://github.com/c2corg/v6_api/blob/master/c2corg_api/models/outing.py#L70-L72
https://github.com/c2corg/v6_api/blob/master/c2corg_api/models/outing.py#L149

That sounds to me a bit redundant and too precise...

**Comment by asaunier** [comment]
> A route should have a field "duration_difficulties"

I indeed see it in the google docs ("Temps de parcours des difficultés"), being a "liste à choix unique". But it seems missing in https://github.com/c2corg/v6_api/blob/master/c2corg_api/models/route.py#L28
I have created an issue: https://github.com/c2corg/v6_api/issues/216

On the other hand we actually have "Temps de parcours total" ("liste à choix multiple").

**Comment by asaunier** [comment]
Fixed by #266
