### ISSUE TITLE
Waypoint view page is broken

### ISSUE THREAD

**Issue by asaunier** [c2corg/v6_ui#235]
A 500 error is returned when loading a waypoint detail view page. The logs say:

> [Mon Mar 14 21:03:18.409201 2016] [wsgi:error] [pid 26057] [remote 10.27.71.4:26380]   File "/var/www/vhosts/c2cassoc_c2corgv6/private/v6_ui/c2corg_ui/templates/waypoint/view.html", line 194, in render_body
[Mon Mar 14 21:03:18.409207 2016] [wsgi:error] [pid 26057] [remote 10.27.71.4:26380]     ${show_associated_routes(waypoint)}
[Mon Mar 14 21:03:18.409212 2016] [wsgi:error] [pid 26057] [remote 10.27.71.4:26380]   File "/var/www/vhosts/c2cassoc_c2corgv6/private/v6_ui/c2corg_ui/templates/helpers/view.html", line 103, in render_show_associated_routes
[Mon Mar 14 21:03:18.409219 2016] [wsgi:error] [pid 26057] [remote 10.27.71.4:26380]     % if 'title_prefix' in route['locales'][0] and route.locales[0]['title_prefix']:
[Mon Mar 14 21:03:18.409224 2016] [wsgi:error] [pid 26057] [remote 10.27.71.4:26380] AttributeError: 'dict' object has no attribute 'locales'

**Comment by tsauerwein** [comment]
Is this related to https://github.com/c2corg/v6_api/pull/183? Is your api instance up-to-date?

**Comment by ginold** [comment]
Mine is not and I didn't get this error. I will update after the scrum

**Comment by asaunier** [comment]
When this issue is fixed, could you update the demo instance?

**Comment by asaunier** [comment]
> Is your api instance up-to-date?

I have updated the UI and API on saturday, dropped the DB and run a new migration (~1h15).

**Comment by ginold** [comment]
now it's all to date for me and i received those errors and repaired them.

On Tue, Mar 15, 2016 at 6:56 PM, Alex Saunier <notifications@github.com>
wrote:

> Is your api instance up-to-date?
>
> I have updated the UI and API on saturday, dropped the DB and run a new
> migration (~1h15).
>
> —
> You are receiving this because you were assigned.
> Reply to this email directly or view it on GitHub
> <https://github.com/c2corg/v6_ui/issues/235#issuecomment-196948372>
>



-- 

*Adam Gina*JavaScript Developer
adam.gina@camptocamp.com

*Camptocamp SA*EPFL Innovation Park
Bâtiment A
1015 Lausanne

Tel + 41 21 619 10 10
http://www.camptocamp.com

**Comment by asaunier** [comment]
Any news about this issue? Is there a PR somewhere?
This is a prioritary task. Thanks!

**Comment by ginold** [comment]
Maybe we can merge mockup-style pr with this issue resolved ? now it should
be better with all the corrections you suggested.
Aat least i don't have any issues with waypoints now and my api is up to
date.
I will update the pr very soon

On Wed, Mar 16, 2016 at 7:01 PM, Alex Saunier <notifications@github.com>
wrote:

> Any news about this issue? Is there a PR somewhere?
> This is a prioritary task. Thanks!
>
> —
> You are receiving this because you were assigned.
> Reply to this email directly or view it on GitHub
> <https://github.com/c2corg/v6_ui/issues/235#issuecomment-197459838>
>



-- 

*Adam Gina*JavaScript Developer
adam.gina@camptocamp.com

*Camptocamp SA*EPFL Innovation Park
Bâtiment A
1015 Lausanne

Tel + 41 21 619 10 10
http://www.camptocamp.com

**Comment by asaunier** [comment]
> Maybe we can merge mockup-style pr with this issue resolved ?

OK, I hadn't understood you fixed it in the mockup-style pr.
