### ISSUE TITLE
Handle protected documents

### ISSUE THREAD

**Issue by tsauerwein** [c2corg/v6_ui#239]
API issue: https://github.com/c2corg/v6_api/issues/217

With https://github.com/c2corg/v6_api/pull/191 the `protected` field of documents will be included. Protected documents can only be edited by moderators.

In the UI maybe we can disable the edit button and show a hover message ("Document is protected, ...") when a user is not moderator. The edit page should also show a "not authorized" message and the form should not be shown.

Example for a protected document in v5:
http://www.camptocamp.org/summits/213785/it/piramide-ovest-di-somalbosco

**Comment by asaunier** [comment]
The protection status of a document is set in a document attribute, right?
Wich means we could have a "protected" attribute in the editing forms only available to the moderators?

**Comment by tsauerwein** [comment]
I was thinking about providing a separate web-service for changing the protected status (similar to merging a document). The protected checkbox might be a bit lost in the normal editing form, so maybe it's better to have an explicit command to lock/unlock a document (as part of the moderator tools).

**Comment by asaunier** [comment]
In v5, the lock/unlock function is indeed a separated function.

Wouldn't it save time to have a checkbox in the editing forms (only for moderators)? We would not have to create a dedicated webservice, it's quite similar to the "quality" attribute (~metadata), and locking/unlocking creates a new version in the history anyway (doesn't it?).

Since it is a special tool for advanced users, it's not that a big deal if it is a bit lost. As I said it could be in a metadata section placed near the "save" button, containing also the quality attribute and the "comments about the change" attribute.

**Comment by tsauerwein** [comment]
> Wouldn't it save time to have a checkbox in the editing forms (only for moderators)? We would not have to create a dedicated webservice, it's quite similar to the "quality" attribute (~metadata), and locking/unlocking creates a new version in the history anyway (doesn't it?).

For me it would actually be easier to have a separate web-service.

**Comment by asaunier** [comment]
OK then. I have created an issue about that in the API: https://github.com/c2corg/v6_api/issues/217

I guess it would be a function available in the "More" menu button.

**Comment by asaunier** [comment]
@fjacon This task cannot be done until the API webservice for it is available: https://github.com/c2corg/v6_api/issues/217

**Comment by asaunier** [comment]
TODO:

* [ ] add a "protect" (resp. "unprotect") action in the "plus" button (after the "merge" and "delete" actions) - only for moderators
* [ ] this new action should call the protect/unprotect API service, see https://github.com/c2corg/v6_api/issues/217
* [ ] display a warning in the document if it is protected? (a bit like the disclaimer in archived versions of a document? https://www.camptocamp.org/waypoints/37355/fr/1305265)

**Comment by desnoes** [comment]
It works correctly on demo
