### ISSUE TITLE
Don't send geometry back to the API when editing a WP if it has not changed

### ISSUE THREAD

**Issue by asaunier** [c2corg/v6_ui#24]
See
https://github.com/c2corg/v6_ui/pull/22#issuecomment-154417573
> Just one thing I'm wondering: the WP geometry is loaded from the API in EPSG:3857, then converted to 4326 for displaying in the form. To avoid having tons of decimals, those lon/lat are rounded at 6 digits. Will it cause slight differences when reprojecting to 3857 and, as a result, a new version in the database even though the user has not changed the coordinates?
See https://github.com/c2corg/v6_ui/blob/map-directive/c2corg_ui/static/js/documentediting.js#L167-L172

and
https://github.com/c2corg/v6_ui/pull/22#issuecomment-154420808
> When the geometry is included in an update request, a new geometry version is always created. If the geometry is not included in the request, it will not change the geometry. So, it's in the responsibility of the client to only send the geometry if changes have been made.

**Comment by gberaudo** [comment]
I discussed about this with @asaunier.

We do not have control on all clients so if we want to be sure the database is not filled by equal geometries we have to implement a check at the API level.

As an optimization it makes sense to propose an update mode where the client omit the geometry and the API can skip the above check. On the API it could be handled with a dedicated method or by checking for a specific geometry value (null?).

**Comment by tsauerwein** [comment]
> We do not have control on all clients so if we want to be sure the database is not filled by equal geometries we have to implement a check at the API level.

What clients will actually write to the API?

Using [Shapely](http://toblerity.org/shapely/manual.html#object.almost_equals) it is quite easy to check if two geometries are equal. But I would like to avoid this check, because it would be relatively expensive for lines.

**Comment by asaunier** [comment]
> What clients will actually write to the API?

UI and mobile app at least.
Maybe some partners even though nothing concrete as for now (I have read that Petzl might use the API to push articles that are also hosted in their CMS).
The association would like to give access to the API so that other content providers (other mountain website for instance) may read from and possibly write to the API.

If we rely too much on the client-side there are risks that someone pushes the geometry everytime a change is made in the document even though the geom is unchanged.
On the other hand I admit that it would make sense no to send the geom back if unchanged in order to save bandwith and CPU (for checking if the geom has changed).

**Comment by gberaudo** [comment]
TODO:
- [ ] detect almost equals geometries in API and skip geometry update;
- [ ] accept the `skip` keyword instead of a geometry in the API and skip geometry update;
- [ ] send the `skip` keyword instead of a geometry in the UI when the geometry did not change.
