### ISSUE TITLE
General layout

### ISSUE THREAD

**Issue by asaunier** [c2corg/v6_ui#241]
Cards layout should be consistent in all pages. Please make sure to use the same HTML and CSS (using mako helpers):
* [x] list page cards are underlined when the mouse cursor hovers the card (not in associated docs cards in WP/route detail view pages) => do not underline.

Forms:
* [x] in Firefox, bullets appear in front of checkboxes lists => please remove the bullets
* [x] it seems not systematic but sometimes the standard checkbox appears in front of the "fancy" checkbox. If it cannot be fixed easily, we can live with the standard checkboxes...
![screencapture-c2corgv6-demo-camptocamp-com-routes-1458492586002](https://cloud.githubusercontent.com/assets/1192331/13905762/42587398-eec9-11e5-9ecd-4b5930cea000.png)
* [x] We don't need to toggle off (fold) the sections in the editing forms => users must see all the fields. In addition when closing the sections, some parts are still visible (see screenshot below) => please remove the toggle buttons in editing forms.
![screencapture-c2corgv6-demo-camptocamp-com-waypoints-edit-642972-fr-1458494871561](https://cloud.githubusercontent.com/assets/1192331/13905783/cc3c8716-eec9-11e5-933a-78a4e6f07a28.png)

**Comment by ginold** [comment]
As for underlining, is the card completely underlined or only the title ? I find that at least the title should be underlined or change color on hover so that something happens, without anything there will be something missing and lacking interaction.

**Comment by ginold** [comment]
checkboxes are fixed in the current pr.

**Comment by ginold** [comment]
i see you have 2 times the logos in the sidemenu! is it a screenshot bug?

**Comment by asaunier** [comment]
> As for underlining, is the card completely underlined or only the title (it does underline in associated documents too) ?

I would say we need only to change the color (of the title, maybe of the background or the border) when hovering the card. I don't find underlining meaningful since it makes more sense to underline when actually hovering a link (here the whole card is clickable, not only the title).

> But you spoke about 'bullets' and then about 'standard' checkboxes in firefox, did you mean the same thing?

No, that's 2 distinct problems.

Bullets, see this screenshot with my FF 45 / MacOS X:
<img width="921" alt="capture d ecran 2016-03-21 a 14 49 04" src="https://cloud.githubusercontent.com/assets/1192331/13920808/221c0124-ef75-11e5-9208-f2b26b0f4140.png">

"standard" checkbox: see the first screenshot at the beginning of this issue: you can see that there is 2 checkboxes at the same time: the standard one + the green one. In Chrome 49.

> i see you have 2 times the logos in the sidemenu! is it a screenshot bug?

Yes, please ignore this.

**Comment by asaunier** [comment]
The issues about the checkboxes seem fixed. Thanks!

* [ ] Concerning the card styling when hovering, as I said:

> do not underline

=> that does not make sense to underline a title when the card is hovered => a change should apply to the whole card to make it obvious that the card itself is a kind of button. For instance: change the background-color, the border or enlarge a bit the card...

* [ ] Make the title badge ("outing", "route", "waypoint", etc.) clickable, redirecting to the list page of the given document type.

* [ ] The "More" button in the detail view pages does not react when not clicking exactly on the icon (for instance on the colored border around). It works if one clicks on the icon itself. No problem with the editing button, even when clicking on the border, outside of the icon.

* [ ]

**Comment by asaunier** [comment]
* [ ] Cards should always have the same width in a given list of cards. Currently if a waypoint has 3 routes, the 2 first ones may be displayed one the same line (each being half the width of the page) whereas the 3rd one takes the whole page width (ie twice the width of the others) => this is not consistent => same width for all even though the full page width is not used for the last cards line.

**Comment by ginold** [comment]
i wanted it to be responsive -> adapt with depending on how much cards there are per row. Now it's 1/3 (big screen) or 1/2 of the row (smaller)

**Comment by ginold** [comment]
i think this issue can be closed?

**Comment by asaunier** [comment]
Let me check/test your PRs first :)

**Comment by asaunier** [comment]
Fixed by #266
