### ISSUE TITLE
Feedbacks on waypoint editing

### ISSUE THREAD

**Issue by asaunier** [c2corg/v6_ui#242]
* [x] Yes/no attributes (eg. "gas unstaffed") should also be set to none (if the info is not available) => the radio buttons should be uncheckable. Perhaps use a "exclusive" checkboxes that supports 0 or 1 value.
* [x] paragliding_ratings: this is not a quality rating based on stars :P Please use a standard dropdown with values 1 to 5.

**Comment by asaunier** [comment]
Concerning the organisation of the attributes (steps), it is currently a bit complicated and not intuitive. Probably too many steps.

Here is a recommendation:
* step 1: text fields and map
 * title
 * lang
 * map
 * long/lat/elevation
 * summary
 * description
 * map info (with auto-associated maps list)
* step 2: figures
 * waypoint_type
 * other "figures" attributes (including orientation etc.)
* step 3: preview before saving

**Comment by ginold** [comment]
I did it, but putting everything in figures makes the form very long. You forgot about contact, access, transports, ratings...
But if it's better that way :no_mouth:

**Comment by ginold** [comment]
isn't a 'Rating' most commonly represented with stars ? If it's not a special value like those letters in other ratings why not use stars ? 5 = 5 stars, it's very speaking :star: :star: :star: :star: :star: 
Or tell me that users will not get what the stars are and are so used to a scale 1-5, then ok :P

**Comment by tsauerwein** [comment]
It's more about the difficulty of a route. For the real *rating* there is a field `awesomeness` for outings. That's where we can use stars.

**Comment by ginold** [comment]
that's exactly what I did, this time i would not let it go if it weren't stars :gun:  
got it!

**Comment by asaunier** [comment]
> isn't a 'Rating' most commonly represented with stars ? 

That's not a quality rating. It's a difficulty indicator. A paragliding takeoff with difficulty 5 is very difficult, not very cool :P

**Comment by ginold** [comment]
whoa so difficult it must be awesome hardcore!

**Comment by asaunier** [comment]
> I did it, but putting everything in figures makes the form very long. You forgot about contact, access, transports, ratings...
But if it's better that way

Don't make too much changes about this. It's still discussed by the client. I'm urging them to make a choice.

**Comment by asaunier** [comment]
Errors reported about the WP editing form:

* [ ] Type "canyon" is missing in https://github.com/c2corg/v6_common/blob/master/c2corg_common/attributes.py#L17-L55

Climbing indoor:
* [ ] routes_quantity => not a height, only a quantity => no need for "m" in the input suffix
* [ ] elevation is not relevant
* [ ] maps_references is not relevant

**Comment by asaunier** [comment]
Climbing outdoor:
* [ ] orientations: use the campass instead of checkboxes (as for routes)

**Comment by asaunier** [comment]
> Yes/no attributes (eg. "gas unstaffed") should also be set to none (if the info is not available) => the radio buttons should be uncheckable. Perhaps use a "exclusive" checkboxes that supports 0 or 1 value.

@ginold Are you sure this point can be checked? In the demo the yes/no attributes are still set using 2 radio buttons and it's not possible to unset them when you have checked one of the radios.

**Comment by asaunier** [comment]
Huts:
* [ ] "access_period" => used to specify when the hut is open/wardened => nothing to do with an "access" => the "access" section is not relevant here.

**Comment by asaunier** [comment]
Discussed with the client. the fields in the WP editing form must be reorganised to make it more consistent.

Depending on the waypoint_type, we would have 2 to 3 steps (not including the "preview" step before saving).

## Here are the steps and fields for "simple" waypoints (summits, passes, places etc.)

### step 1

title + lang
waypoint_type
elevation (+ prominence _for summits_)
longitude + latitude
interactive map
maps_references

### step 2

summary
description
associations

_Fields for other types will be provided in additional comments below._

**Comment by asaunier** [comment]
## Climbing indoor

### step 1

title + lang
waypoint_type
longitude + latitude
interactive map
~~elevation~~
~~maps_references~~

### step 2

climbing_styles + climbing_indoor_types
routes_quantity + height_max
climbing_rating_min + climbing_rating_median + climbing_rating_max
URL + phone

### step 3

summary
description
~~associations~~

**Comment by asaunier** [comment]
## climbing_outdoor

### step 1

title + lang
waypoint_type
longitude + latitude
interactive map
maps_references

### step 2

climbing_outdoor_types + climbing_styles
orientation + best_periods
rock_types
routes_quantity + equipment_ratings
height_min + height_max + height_median 
climbing_rating_min +  climbing_rating_max + climbing_rating_median
rain_proof + children_proof + access_time
URL

### step 3

associations
summary
description
access_period
quality

**Comment by asaunier** [comment]
## accomodations

### step 1

title + lang
waypoint_type
elevation + longitude + latitude
interactive map
maps_references

### step 2

custodianship + capacity_staffed + capacity
URL + phone + phone_custodian
matress_unstaffed + blanket_unstaffed + gas_unstaffed + heating_unstaffed

### step 3

associations
summary
access_period
description
quality

**Comment by asaunier** [comment]
## access

### step 1

title + lang
waypoint_type
elevation + elevation min
longitude + latitude
interactive map
maps_references?

### step 2

lift_access + parking_fee
snow_clearance
public_transportation_rating
public_transportation_types

### step 3

associations
summary
access_period
road access (= description?)
public transportation access (= access?)
quality

**Comment by asaunier** [comment]
Paragliding WP, webcam, weather stations: 2 steps if not a lot of dedicated attributes, 3 steps if quite a lot (eg. paragliding)

**Comment by ginold** [comment]
and have you thought about any names for those steps ?

**Comment by ginold** [comment]
what is quality ?!

**Comment by asaunier** [comment]
> have you thought about any names for those steps ?

Not yet. I ask the client and let you know.

> what is quality ?!

https://github.com/c2corg/v6_api/blob/master/c2corg_api/models/document.py#L65
It's a meta attribute about the status of the document:
https://github.com/c2corg/v6_api/blob/master/c2corg_api/models/document.py#L28-L34
useful to figure out the documents that must be improved (or even not publicly listed, for example the empty outings).

**Comment by asaunier** [comment]
Fixed by #266
