### ISSUE TITLE
How to display ratings in route pages

### ISSUE THREAD

**Issue by asaunier** [c2corg/v6_ui#243]
Here is a proposal from the client. There are still blur points. I have asked the client to make changes and will update the scheme below as soon as possible:

```
The ratings are organized by block. Each block depends on one or several activities. A block is showed if at least one of its activities is selected in the outing.
A space to showed is coded as #. The blocks are concatenated with 2 space as separator.

Block A : snow_ice_mixed, mountain_climbing, rock_climbing, ice_climbing, via_ferrata
global_rating ## rock_free_rating>rock_required_rating[A0] # aid_rating # ice_rating # mixed_rating # via_ferrata_rating ## engagement_rating # risk_rating ## equipment_rating # exposition_rock_rating

- ">rock_required_rating" is showed only if : rock_free_rating is filled, and rock_free_rating is > rock_required_rating.
- [A0] (without bracket) is showed only if equipment_rating = P1 or P1+, and if aid_rating is empty.

Block B : skitouring
ski_rating/ski_exposition # labande_global_rating/labande_ski_rating

Block C : hiking
hiking_rating

Block D : snowshoeing
snowshoe_rating

Block E : mountain_biking
mtb_up_rating # mtb_down_rating

Block F : hiking, mountain_biking
hiking_mtb_exposition
```

**Comment by asaunier** [comment]
Examples:

Cascade et NGM :             D  4+ M1                   II X1    P4 
Rocher  et escalade :        D  6a>5cA0 A1           II X1    P4 E1       (le A1 correspond à l'artif obligatoire) 
Rocher + Cascade  :         D  6a>5cA0 A1 4+ M2  II X1    P4 E1

**Comment by ginold** [comment]
updated, should be ok now.

**Comment by ginold** [comment]
can be closed?

**Comment by asaunier** [comment]
Of course since the PR is merged.

**Comment by asaunier** [comment]
Reopening the issue since it seems there are still problems according to https://github.com/c2corg/v6_ui/issues/433#issuecomment-226810272

**Comment by stef74** [comment]
@shortoland please test

**Comment by shortoland** [comment]
@stef74 

I can still see some problems:

- I don't think blocks are separated by 2 spaces.
- For a ski and hiking route, hiking rating is placed in between ski ratings: pb ?
- Block A: order is not respected
- Rock_climbing: rock_free_rating is displayed twice

**Comment by ginold** [comment]
could you give an example where `rock_free_rating` is displayed twice in a `rock_climbing` route?

**Comment by ginold** [comment]
@stef74 see https://github.com/c2corg/v6_ui/issues/577 for an example image with every rating possible, it should be in the correct order now.

**Comment by shortoland** [comment]
@ginold 

Here is an example (grey route): rick_free_rating (7a+) is displayed twice. You can find other ones by filtering on "rock climbing" activity.

![image13](https://cloud.githubusercontent.com/assets/20488365/18206397/ce4ca088-7126-11e6-9998-46d38ac5bee4.png)

**Comment by shortoland** [comment]
@ginold It seems the issue is still there

**Comment by ginold** [comment]
demo has not been updated yet.

**Comment by stef74** [comment]
@shortoland please test

**Comment by shortoland** [comment]
[ ] Order is not respected for ski ratings
[ ] For a ski and hiking route, hiking rating is still placed in between ski ratings
[ ] For hiking, blocks C and F are switched
[ ] For mountain biking, blocks E and F are switched
[ ] Block A: order is not respected

**Comment by ginold** [comment]
@shortoland please tell me if those problems appear on the list page on the cards, or on the detailed view page of a document ? both?

if in both, please be precise and state where which of the following problems appear.

**Comment by shortoland** [comment]
@ginold 

- Order not respected for ski rating: appear on cards only:

![image100](https://cloud.githubusercontent.com/assets/20488365/18542373/dcbb6bdc-7b2a-11e6-82fa-2ac44572b6e7.png)

- Hiking rating placed in between ski ratings for a ski and hiking route: pb solved, but order not respected on cards only: ski rating should be first, ski ratings switched (see previous item). Card "Depuis Oberems, Gruben"

![image101](https://cloud.githubusercontent.com/assets/20488365/18542528/ab3e2076-7b2b-11e6-9468-711f3fa4409a.png)

- C and F blocks switched for hiking: on cards only. See Grand Colon: Eperon W

![image103](https://cloud.githubusercontent.com/assets/20488365/18542632/369d4c50-7b2c-11e6-8252-27db31fccd0c.png)

- E and F blocks switched for mountain biking: on cards only.

![image102](https://cloud.githubusercontent.com/assets/20488365/18542731/9ee99052-7b2c-11e6-8700-f6980164baa0.png)

- Order nor respected for block A: seems to appear on cards only. For example, global rating is not displayed first (La Noire _ Pointe 3386m : Beau comme un reve)

![image104](https://cloud.githubusercontent.com/assets/20488365/18542796/f7f71f70-7b2c-11e6-8793-da7a1b425a9f.png)

Hope it helps ...

**Comment by asaunier** [comment]
@shortoland thanks for the screenshots and examples. I guess the first screenshot is not the correct one :P

**Comment by shortoland** [comment]
@asaunier Oups, better now ;-)

**Comment by fjacon** [comment]
@ginold : Toutes les corrections ont été faites ?

**Comment by ginold** [comment]
je crois que #697 a apporté des améliorations mais je n'ai pas eu de retour.

**Comment by stef74** [comment]
@shortoland @loicperrin @desnoes could you test and close

**Comment by shortoland** [comment]
Still some (new) issue...

- [ ] Mountain biking: full rating not displayed on cards (first card in grey).

![image1](https://cloud.githubusercontent.com/assets/20488365/19976218/256ce8c0-a1ef-11e6-9a6c-756e9355d3f8.png)

The other old ones seem to be solved.

**Comment by stef74** [comment]
See #1195
