### ISSUE TITLE
Keep the documentediting controller as generic as possible

### ISSUE THREAD

**Issue by asaunier** [c2corg/v6_ui#246]
https://github.com/c2corg/v6_ui/blob/master/c2corg_ui/static/js/documentediting.js contains some document_type specific parts (waypoint_type, date, etc.).

It would be better that specific data/parts are added for instance in inheriting controllers (possible?).

**Comment by asaunier** [comment]
I feel a bit concerned about the ``DocumentEditingController`` because it seems to me it integrates more and more code that is document_type-specific.

I think we should have a generic ``DocumentEditingController`` that could be extended into ``OutingEditingController``, ``WaypointEditingController`` if needed.

We could define dedicated directives as we do now, since it would not duplicate much code.
Or maybe we can change the directive controller according to some directive attribute?

What do you think?

**Comment by ginold** [comment]
Maybe simply create OutingService ,WpService and so on, where we would put every doc-specific functions and call them as needed?
