### ISSUE TITLE
Fixes needed for outings

### ISSUE THREAD

**Issue by asaunier** [c2corg/v6_ui#247]
* [x] Handle outings with different start/end dates (see https://github.com/c2corg/v6_ui/issues/245)
* [x] Do we really need to have the activities displayed twice (icon in the title + name in the figures)?
* [x] The associated routes should also be more obvious, and be shown higher in the page.
* [x] Take the ``conditions_levels`` attribute into account: kind of array attribute. Example: http://c2corgv6-demo.gis.internal:6545/outings/504542 See also the rendering in v5: http://www.camptocamp.org/outings/504542/fr/mont-rogneux-par-le-versant-s-et-pointe-du-parc

**Comment by asaunier** [comment]
Porting here this comment from https://github.com/c2corg/v6_ui/pull/240#issuecomment-200794897

Personal comment field at step1 of the editing form:
* [ ] typo in field title
* [ ] the placeholder "write your comment" should disappear when the focus is on the field
* [ ] What is difference between this field and "description" at step 4?

**Comment by asaunier** [comment]
* [ ] The "Add an outing" button in the page header always opens the outing editing page and THEN tests if the user is authenticated, redirecting him to the login page. Which is ugly: the editing form appear briefly before the user is redirected. It would be better that the check is done when clicking on the button. Please use the ``appEditButton`` directive as for the button available in the list page.

**Comment by asaunier** [comment]
Association tool:
* [ ] Should only search among routes (at least for associating routes) => there's a parameter to add to the URL in order to restrict the search to routes: ``?t=r`` See https://github.com/c2corg/v6_api/blob/master/c2corg_api/views/search.py#L46-L61
* [ ] We need the same thing to associate contributors to the outing
* [ ] As for now, picking a result in the association tool redirects to the result itself instead of making the association.

**Comment by asaunier** [comment]
* [ ] Contributors associated to an outing are not displayed in the outing detail page (only the participants mentioned in the text field).

**Comment by asaunier** [comment]
* [ ] Move the date out of the badge. Because:
 * the date should be more visible => as subtitle, almost the same size (at least not too smaller) than the main title, on a distinct line
 * for several-day outings, the date will take too much room in the badge

* [ ] The arrow icon (=guidebook icon) is missing in the badge => that's not consistent with routes and WP. By the way make the badge clickable (see https://github.com/c2corg/v6_ui/issues/241#issuecomment-202126294)

**Comment by asaunier** [comment]
Related to the "description"/"personal comments" comment above: https://github.com/c2corg/v6_ui/issues/247#issuecomment-200839736

* [ ] "weather and conditions" is quite an important part (at least conditions for activities such as skiing, ice climbing, etc.) => this block should be open by default
* [ ] if a field is not set (for instance "description" or "personal comments") do not show "description is not available", just don't show the field.

**Comment by ginold** [comment]
i'm REALLY not fond of renaming 'description' to 'personal comment' or 'comment', it makes no sense for me! A description is a description, a comment may be a description.

**Comment by asaunier** [comment]
Fixed by #266
