### ISSUE TITLE
Fallback when API is down

### ISSUE THREAD

**Issue by asaunier** [c2corg/v6_ui#25]
As for now when the API is down (for instance pserve off), the UI WP URL shows a pyramid error page with message

>   File "/home/alex/v6_ui/c2corg_ui/views/document.py", line 72, in _get_documents
>     return content if resp.status == 200 else []
> AttributeError: 'dict' object has no attribute 'status'

**Comment by tsauerwein** [comment]
It's because you are returning a dictionary here:
https://github.com/c2corg/v6_ui/blob/master/c2corg_ui/views/document.py#L35

Maybe you want to return the original response instead?

**Comment by asaunier** [comment]
Are you sure that's the problem?
https://github.com/c2corg/v6_ui/blob/master/c2corg_ui/views/document.py#L35 actually returns a "resp" output with a "status" attribute, doesn't it?

By the way I have noticed that sometimes the API fails but returns an HTML page as the "content" (instead of a JSON output - or maybe as the value of a JSON attribute?). I don't remember in what cases.

**Comment by tsauerwein** [comment]
> Are you sure that's the problem?
> https://github.com/c2corg/v6_ui/blob/master/c2corg_ui/views/document.py#L35 actually returns a "resp" output with a "status" attribute, doesn't it?

It returns a dictionary, so you would have to use `resp['status']`.

> By the way I have noticed that sometimes the API fails but returns an HTML page as the "content" (instead of a JSON output - or maybe as the value of a JSON attribute?). I don't remember in what cases.

Could you please log the request when this happens again?

**Comment by asaunier** [comment]
> It returns a dictionary, so you would have to use resp['status'].

Do you mean we should use
```
return content if resp['status'] == 200 else []
```
instead of
```
return content if resp.status == 200 else []
```
at https://github.com/c2corg/v6_ui/blob/master/c2corg_ui/views/document.py#L72 ?

> Could you please log the request when this happens again?

OK

**Comment by tsauerwein** [comment]
Yes. Or return the original response (which you get from the `http.request()` call).

**Comment by asaunier** [comment]
Perhaps we don't need that try/except? I don't remember why I have used it? Maybe to handle contents (errors) that do not fit in ``json.loads`` but is it really a problem?

Maybe
```
    def _call_api(self, url, method='GET', body=None, headers=None):
        http = httplib2.Http()
        resp, content = http.request(
            url, method=method, body=body, headers=headers
        )
        return resp, json.loads(content)
```
would be enough?

**Comment by tsauerwein** [comment]
:+1:

**Comment by asaunier** [comment]
I have tried to do so but it does not solve the problem. If the API is down, the UI crashes with a Mako error because ``error: [Errno 111] Connection refused``

>   File "/home/alex/v6_ui/c2corg_ui/views/waypoint.py", line 23, in view
    waypoint, locale = self._get_document(id, culture)
  File "/home/alex/v6_ui/c2corg_ui/views/document.py", line 53, in _get_document
    resp, document = self._call_api(url)
  File "/home/alex/v6_ui/c2corg_ui/views/document.py", line 30, in _call_api
    url, method=method, body=body, headers=headers
  File "/home/alex/v6_ui/.build/venv/local/lib/python2.7/site-packages/httplib2/__init__.py", line 1609, in request
    (response, content) = self._request(conn, authority, uri, request_uri, method, body, headers, redirections, cachekey)
  File "/home/alex/v6_ui/.build/venv/local/lib/python2.7/site-packages/httplib2/__init__.py", line 1351, in _request
    (response, content) = self._conn_request(conn, request_uri, method, body, headers)
  File "/home/alex/v6_ui/.build/venv/local/lib/python2.7/site-packages/httplib2/__init__.py", line 1272, in _conn_request
    conn.connect()
  File "/home/alex/v6_ui/.build/venv/local/lib/python2.7/site-packages/httplib2/__init__.py", line 928, in connect
    raise socket.error, msg
error: [Errno 111] Connection refused

Well, I guess this problem should be address at the same time a better error handling system is done.

See also https://github.com/c2corg/v6_ui/issues/9 and https://github.com/c2corg/v6_ui/issues/8

**Comment by tsauerwein** [comment]
#8 and #9 are about an error handling system on the client side? This kind of error should be caught on the server side (-> #27)

**Comment by asaunier** [comment]
> #8 and #9 are about an error handling system on the client side?

Indeed.

> This kind of error should be caught on the server side (-> #27)

+1 Having a dedicated issue actually makes sense, thanks.

**Comment by fjacon** [comment]
Can we close this one ?

**Comment by asaunier** [comment]
I don't know.

Now when the API is down, the advanced search page no longer crashes as described in the inital comment of this issue, but an "unknown error" alert is displayed...

**Comment by asaunier** [comment]
Another example of incorrect handling of an API crash:

* the API encouters a ``sqlalchemy.exc.ProgrammingError`` when requested for a waypoint and returns a 500 status
* the UI server code (view page) then crash because of an unexpected response (HTML instead of JSON):
> json.decoder.JSONDecodeError

Please note that this happens in dev mode (pyramid returns an HTML error stack). Perhaps we don't have it in prod mode.

**Comment by tsauerwein** [comment]
> the API encouters a sqlalchemy.exc.ProgrammingError when requested for a waypoint and returns a 500 status

When did you get this error?

**Comment by asaunier** [comment]
I just had it in my instance because my DB was outdated (no articles) whereas the API was trying to make a query on articles. I have updated my DB and it solved the problem.

**Comment by asaunier** [comment]
In the demo (prod mode), there's currently a 500 error when asking the API for some document (eg. outing) => the API returns a standard 500 error:

<img width="1046" alt="capture d ecran 2016-10-08 a 17 35 28" src="https://cloud.githubusercontent.com/assets/1192331/19214183/a4251132-8d7d-11e6-8552-0078bbf96d16.png">

The UI then also returns a similar 500 error when trying to display such a document. That's no surprise since the API is 500, anyway the UI couldn't display anything. But instead of displaying a raw 500 error, we should display a customized 500 error page, as the existing v6 404 page.
So perhaps this issue is simply a duplicate of https://github.com/c2corg/v6_ui/issues/518

**Comment by stef74** [comment]
@desnoes not bug is an optimization
