### ISSUE TITLE
Simple search tool

### ISSUE THREAD

**Issue by asaunier** [c2corg/v6_ui#252]
List of reported problems:
* [ ] When there are more than 10 results for a document type, a bouton at the end of the list should allow to open the advanced search/list page with all the results
* [ ] Not sure if it is a UI or an API problem: sometimes the search tool only returns waypoints results, no route (despite they are the routes of the provided WP). For instance with "Mont de grange"

**Comment by tsauerwein** [comment]
> sometimes the search tool only returns waypoints results, no route (despite they are the routes of the provided WP)

The API [returns](http://c2corgv6-api.demo-camptocamp.com/search?q=mont%20de%20grange&pl=en) the results also for routes. Maybe this is a Typeahead bug (see https://github.com/GFDRR/thinkhazard/pull/369)?

**Comment by asaunier** [comment]
* [ ] The document title is not enough to choose among the suggested docs.
 * [ ] For WP we would need for instance the WP type, elevation or some region.
 * [ ] For routes, the activities etc.

**Comment by fjacon** [comment]
@tsauerwein could you make a rough estimate on this ?

**Comment by tsauerwein** [comment]
@fjacon I added the estimates to the corresponding Trello card.

**Comment by tsauerwein** [comment]
@asaunier or @ginold, could you please specify which additional fields are required for each document type?

**Comment by asaunier** [comment]
> could you please specify which additional fields are required for each document type?

Do you mean the fields to be indexed (used for searching) and/or the fields to be displayed in the list of results?

**Comment by tsauerwein** [comment]
The latter.

**Comment by asaunier** [comment]
I have noticed that when the API is down, the search tool shows no result (no surprise) and suggest to create the documents. Just wondering if the search tool should not warn the API is down instead?

**Comment by asaunier** [comment]
> The latter.

OK thanks
I have asked the client. I will add feedbacks in the issue.
