### ISSUE TITLE
Waypoint layout

### ISSUE THREAD

**Issue by asaunier** [c2corg/v6_ui#253]
In detail view pages:
* [x] the waypoint type icon should appear in the title (as the activities in routes or outings pages).
* [x] the associated regions should be clickable (redirecting towards the pages of the given regions). Including on a mobile phone => should we use cards?
* [ ] the layout of associated regions is not consistent and too complicated: the 1st one is bold, the 3rd one is underlined (and if there is only one, it is both bold and underlined!) => use the same simple layout for all associated regions.
* [ ] ~~the associated regions should be listed in the following order: range > admin_limits > country (see https://github.com/c2corg/v6_common/blob/master/c2corg_common/attributes.py#L507-L511)~~
* [x] in the post-it, remove the "elevation" prefix => only display the elevation with the "m" suffix

**Comment by asaunier** [comment]
@ginold Is this issue addressed by your PR https://github.com/c2corg/v6_ui/pull/266 ?

**Comment by ginold** [comment]
the first yes, the last yes, the rest would be but still the API does not return the areas in order, so they appear randomly.

**Comment by ginold** [comment]
and 'redirecting towards the pages of the given regions' I don't see what you mean? or we just haven't created a 'regions page' yet?

**Comment by asaunier** [comment]
What about having a simple and consistent layout for all associated areas (no underlining, no bolding etc.)?

> or we just haven't created a 'regions page' yet?

Yes. But we will have to create them. As in v5, for instance: http://www.camptocamp.org/areas/14410/fr/mont-blanc

**Comment by ginold** [comment]
It would be an option if the api returned the list in order. And that was exactly the reason I did some styling - as I don't know an area, i can mistake he region for a city or the city for maybe even a country i've never heard of? Styling gives you this information. The other easy solution would be to write 'country' : ... 'admin:'... etc

**Comment by asaunier** [comment]
Honestly I don't think we need to distinguish the styling of ranges, admininistrative areas (cantons/departements) and countries. Those are just areas.

**Comment by asaunier** [comment]
I have striked through the task about the order of associated regions since it should be done by the API: https://github.com/c2corg/v6_api/issues/210

Remains only the styling of the areas: simple link, not distinguishing the area types.

**Comment by ginold** [comment]
are sure about this? When i stumble upon some areas i don't know, i don't know which one is the city and which one is the area, even country may be unknown...how do you want to distinguish? i find it it's an important information.

**Comment by asaunier** [comment]
It's not distinguished in v5. No one asked to distinguish. No need to distinguish :)

**Comment by ginold** [comment]
done. It can be closed - the update is coming in the next pr :)
