### ISSUE TITLE
WP update fails with JS error

### ISSUE THREAD

**Issue by asaunier** [c2corg/v6_ui#26]
When pushing the "Save" button after editing a WP, we get a JS error that prevent from requesting the API.

Chrome:
> TypeError: Illegal invocation
    at forEach (angular.js:326)
    at copy (angular.js:816)
    at copy (angular.js:782)
    at copy (angular.js:822)
    at copy (angular.js:782)
    at copy (angular.js:822)
    at copy (angular.js:782)
    at copy (angular.js:822)
    at copy (angular.js:782)
    at copy (angular.js:804)

Firefox:
> Error: 'nodeType' getter called on an object that does not implement interface Node.
Ra@http://c2corgv6-demo.gis.internal:6555/node_modules/angular/angular.min.js:6:483
r@http://c2corgv6-demo.gis.internal:6555/node_modules/angular/angular.min.js:7:227
Ca@http://c2corgv6-demo.gis.internal:6555/node_modules/angular/angular.min.js:11:3
Ca@http://c2corgv6-demo.gis.internal:6555/node_modules/angular/angular.min.js:11:340
Ca@http://c2corgv6-demo.gis.internal:6555/node_modules/angular/angular.min.js:11:70
Ca@http://c2corgv6-demo.gis.internal:6555/node_modules/angular/angular.min.js:11:340
Ca@http://c2corgv6-demo.gis.internal:6555/node_modules/angular/angular.min.js:11:70
Ca@http://c2corgv6-demo.gis.internal:6555/node_modules/angular/angular.min.js:11:340
Ca@http://c2corgv6-demo.gis.internal:6555/node_modules/angular/angular.min.js:10:404
Ca@http://c2corgv6-demo.gis.internal:6555/node_modules/angular/angular.min.js:11:158
Ca@http://c2corgv6-demo.gis.internal:6555/node_modules/angular/angular.min.js:11:70
Ca@http://c2corgv6-demo.gis.internal:6555/node_modules/angular/angular.min.js:11:340
Ca@http://c2corgv6-demo.gis.internal:6555/node_modules/angular/angular.min.js:11:70
Ca@http://c2corgv6-demo.gis.internal:6555/node_modules/angular/angular.min.js:11:340
Ca@http://c2corgv6-demo.gis.internal:6555/node_modules/angular/angular.min.js:11:70
Ca@http://c2corgv6-demo.gis.internal:6555/node_modules/angular/angular.min.js:11:340
Ca@http://c2corgv6-demo.gis.internal:6555/node_modules/angular/angular.min.js:11:70
Ca@http://c2corgv6-demo.gis.internal:6555/node_modules/angular/angular.min.js:11:340
Ca@http://c2corgv6-demo.gis.internal:6555/node_modules/angular/angular.min.js:10:404
Ca@http://c2corgv6-demo.gis.internal:6555/node_modules/angular/angular.min.js:11:158
Ca@http://c2corgv6-demo.gis.internal:6555/node_modules/angular/angular.min.js:11:70
Ca@http://c2corgv6-demo.gis.internal:6555/node_modules/angular/angular.min.js:11:340
Ca@http://c2corgv6-demo.gis.internal:6555/node_modules/angular/angular.min.js:11:70
Ca@http://c2corgv6-demo.gis.internal:6555/node_modules/angular/angular.min.js:11:340
Ca@http://c2corgv6-demo.gis.internal:6555/node_modules/angular/angular.min.js:11:70
Ca@http://c2corgv6-demo.gis.internal:6555/node_modules/angular/angular.min.js:11:340
Ca@http://c2corgv6-demo.gis.internal:6555/node_modules/angular/angular.min.js:11:70
Ca@http://c2corgv6-demo.gis.internal:6555/node_modules/angular/angular.min.js:11:340
Ca@http://c2corgv6-demo.gis.internal:6555/node_modules/angular/angular.min.js:10:404
Ca@http://c2corgv6-demo.gis.internal:6555/node_modules/angular/angular.min.js:11:158
Ca@http://c2corgv6-demo.gis.internal:6555/node_modules/angular/angular.min.js:11:70
Ca@http://c2corgv6-demo.gis.internal:6555/node_modules/angular/angular.min.js:11:340
Ca@http://c2corgv6-demo.gis.internal:6555/node_modules/angular/angular.min.js:11:70
Ca@http://c2corgv6-demo.gis.internal:6555/node_modules/angular/angular.min.js:11:340
Ca@http://c2corgv6-demo.gis.internal:6555/node_modules/angular/angular.min.js:11:70
Ca@http://c2corgv6-demo.gis.internal:6555/node_modules/angular/angular.min.js:11:340
Ca@http://c2corgv6-demo.gis.internal:6555/node_modules/angular/angular.min.js:11:70
Ca@http://c2corgv6-demo.gis.internal:6555/node_modules/angular/angular.min.js:11:340
Ca@http://c2corgv6-demo.gis.internal:6555/node_modules/angular/angular.min.js:10:404
Ca@http://c2corgv6-demo.gis.internal:6555/node_modules/angular/angular.min.js:11:158
Ca@http://c2corgv6-demo.gis.internal:6555/node_modules/angular/angular.min.js:11:70
Ca@http://c2corgv6-demo.gis.internal:6555/node_modules/angular/angular.min.js:11:340
Ca@http://c2corgv6-demo.gis.internal:6555/node_modules/angular/angular.min.js:11:70
Ca@http://c2corgv6-demo.gis.internal:6555/node_modules/angular/angular.min.js:11:340
Ca@http://c2corgv6-demo.gis.internal:6555/node_modules/angular/angular.min.js:11:70
Ca@http://c2corgv6-demo.gis.internal:6555/node_modules/angular/angular.min.js:11:340
Ca@http://c2corgv6-demo.gis.internal:6555/node_modules/angular/angular.min.js:11:70
Ca@http://c2corgv6-demo.gis.internal:6555/node_modules/angular/angular.min.js:11:340
Ca@http://c2corgv6-demo.gis.internal:6555/node_modules/angular/angular.min.js:10:404
Ca@http://c2corgv6-demo.gis.internal:6555/node_modules/angular/angular.min.js:11:158
Ca@http://c2corgv6-demo.gis.internal:6555/node_modules/angular/angular.min.js:11:70
Ca@http://c2corgv6-demo.gis.internal:6555/node_modules/angular/angular.min.js:11:340
Ca@http://c2corgv6-demo.gis.internal:6555/node_modules/angular/angular.min.js:11:70
Ca@http://c2corgv6-demo.gis.internal:6555/node_modules/angular/angular.min.js:11:340
Ca@http://c2corgv6-demo.gis.internal:6555/node_modules/angular/angular.min.js:11:70
Ca@http://c2corgv6-demo.gis.internal:6555/node_modules/angular/angular.min.js:11:340
Ca@http://c2corgv6-demo.gis.internal:6555/node_modules/angular/angular.min.js:11:70
Ca@http://c2corgv6-demo.gis.internal:6555/node_modules/angular/angular.min.js:11:340
Ca@http://c2corgv6-demo.gis.internal:6555/node_modules/angular/angular.min.js:11:70
Ca@http://c2corgv6-demo.gis.internal:6555/node_modules/angular/angular.min.js:11:340
gl.prototype.H@http://c2corgv6-demo.gis.internal:6555/static/build/build.js:274:36
fb.prototype.functionCall/<@http://c2corgv6-demo.gis.internal:6555/node_modules/angular/angular.min.js:198:110
Ac[c]</<.compile/</</f@http://c2corgv6-demo.gis.internal:6555/node_modules/angular/angular.min.js:227:195
Me/this.$get</k.prototype.$eval@http://c2corgv6-demo.gis.internal:6555/node_modules/angular/angular.min.js:125:116
Me/this.$get</k.prototype.$apply@http://c2corgv6-demo.gis.internal:6555/node_modules/angular/angular.min.js:125:330
Ac[c]</<.compile/</<@http://c2corgv6-demo.gis.internal:6555/node_modules/angular/angular.min.js:227:245
gf/c@http://c2corgv6-demo.gis.internal:6555/node_modules/angular/angular.min.js:32:280

**Comment by gberaudo** [comment]
This is due to the model containing an `ol.geom.Point`.
We should only use json in the models.

**Comment by asaunier** [comment]
Thanks for the tip.

Perhaps we should fix this problem at the same time than https://github.com/c2corg/v6_ui/issues/24
