### ISSUE TITLE
URL for editing steps

### ISSUE THREAD

**Issue by asaunier** [c2corg/v6_ui#260]
@ginold Do you think it would be possible/not too complicated that each step in the editing form has its own anchor in the URL (for instance #step1), that would be refreshed when passing from one step to another?

That would allow for instance to open the editing form directly at a given step (in the future we could for instance have a small link near an attribute in the detail view page that would open the editing step dealing with the attribute).

**Comment by ginold** [comment]
no doubt it's possible, but frankly I would prefer to focus on other more important things for now. But I'll keep it in mind.

**Comment by asaunier** [comment]
Sure, it's not a priority :)

**Comment by gberaudo** [comment]
When creating a form and pressing the `tab` key, the content of the window is shifted half way
and the user get stuck between two steps. Fixing this looks related to having a proper anchor for each step.
Do we already have an open issue for this?
