### ISSUE TITLE
"Add an outing" button in route detail view

### ISSUE THREAD

**Issue by asaunier** [c2corg/v6_ui#269]
When clicking on "Add an outing" in route detail view, the opened URL should contain a parameter giving the document_id of the route.
This route should then be directly listed in the associated routes of the outing.

Related to https://github.com/c2corg/v6_ui/issues/227

**Comment by asaunier** [comment]
Related to https://github.com/c2corg/v6_ui/issues/256 as well

**Comment by fjacon** [comment]
Duplicate of https://github.com/c2corg/v6_ui/issues/198
