### ISSUE TITLE
Support of the "quality" field

### ISSUE THREAD

**Issue by asaunier** [c2corg/v6_ui#272]
All documents (except maybe user profiles) have a "quality" attribute that is used to figure out they should be improved or even filtered (for instance to hide outings almost empty).

TODO:
* [x] Use "quality_types" values from https://github.com/c2corg/v6_common/blob/master/c2corg_common/attributes.py#L610-L616 in the editing forms
* [x] Send the quality value to the API when editing a document (required attribute)
* [x] Display the quality attribute in the document detail views and list views (more instructions to come)
* [x] Set a default quality value for documents migrated from v5: ``correct``(3rd level)
* [x] Set a default quality value when creating a document (default value of the dropdown): ``medium``(2nd level), whatever the document type

Related to https://github.com/c2corg/v6_common/issues/18 and https://github.com/c2corg/v6_api/issues/220

**Comment by stef74** [comment]
For quality display use a colored disc : http://www.camptocamp.org/images/755110/fr/picto-completude-couleurs-seules-20px

An bulble infos show the quality name

**Comment by asaunier** [comment]
You can post images directly in the issues by drag-dropping them in a comment:
![1462784786_839360498](https://cloud.githubusercontent.com/assets/1192331/16228529/dd78dc8c-37b7-11e6-9e93-622de8bc07a8.png)

**Comment by asaunier** [comment]
Currently the quality is displayed as text in the documents (not with the disk icons shown above).
And not displayed in the cards I think.

**Comment by ginold** [comment]
the quality field is now displayed in the view as well as on the cards.
Can be closed?

**Comment by ginold** [comment]
@asaunier  ?

**Comment by stef74** [comment]
@shortoland please test
For me quality icon is not good in outing ... quality not show in route ? (reminder the specification for card content : https://docs.google.com/spreadsheets/d/1W2kEAyGPc7cw9yKe3hyYIMTNgUDLPsFUD0ccTS8jI5Y/edit?usp=sharing)

**Comment by shortoland** [comment]
@ginold Are you sure it is ready for testing ? I still see text and no disk icons.

**Comment by shortoland** [comment]
![image100](https://cloud.githubusercontent.com/assets/20488365/18544524/4c186d7c-7b35-11e6-8ba1-ee68c4fc8c80.png)

**Comment by stef74** [comment]
@ginold it is ready for test ?

**Comment by ginold** [comment]
yep it's already online.

**Comment by shortoland** [comment]
- Icon for "excellent" is black (same as "empty"), instead of yellow star:

![image1](https://cloud.githubusercontent.com/assets/20488365/18836738/95ec3f76-8401-11e6-8c7c-d5c547fe2488.png)

- Some WP don't have a quality icon: see "Boulderhaus"

![image2](https://cloud.githubusercontent.com/assets/20488365/18836767/b2dc28bc-8401-11e6-8b58-15a71f072e24.png)

- Quality is editable in any type of document, whereas I think it should be set automatically, depending on how the document is filled.

- Associated route to WP: quality shouldn't be displayed (Desktop & Mobile)

![image3](https://cloud.githubusercontent.com/assets/20488365/18837191/2abe0ae8-8403-11e6-9763-cfb7276fc43d.png)

- Associated WP: quality shouldn't be displayed (Desktop & Mobile)

![image4](https://cloud.githubusercontent.com/assets/20488365/18837229/484297b4-8403-11e6-8379-5cc51b2eb236.png)

**Comment by asaunier** [comment]
> * Icon for "excellent" is black (same as "empty"), instead of yellow star:
> * Associated route to WP: quality shouldn't be displayed (Desktop & Mobile)
> * Associated WP: quality shouldn't be displayed (Desktop & Mobile)

@ginold has fixed those 3 points. Visible in the demo

> Some WP don't have a quality icon: see "Boulderhaus"

This seems to be a problem with the API which does not provide the ``quality`` attribute for this WP, whereas it does for most others (and also when editing "Boulderhaus"):
![sans titre](https://cloud.githubusercontent.com/assets/1192331/18927581/ccc7eb3c-85bc-11e6-8067-9e3622a377ca.png)
Perhaps an ElasticSearch index problem as suggested at https://github.com/c2corg/v6_ui/issues/655#issuecomment-250255893 ?

> Quality is editable in any type of document, whereas I think it should be set automatically, depending on how the document is filled.

I don't think so. Auto-filling of the quality field has been dropped from the project perimeter (maybe in the future).

**Comment by tsauerwein** [comment]
> Perhaps an ElasticSearch index problem as suggested at #655 (comment) ?

*Interesting*. It is unrelated to ElasticSearch. I opened a ticket on the API: https://github.com/c2corg/v6_api/issues/404

**Comment by asaunier** [comment]
Thanks @tsauerwein for the tip and issue.
I remove @ginold from the assignees of this issue since he has completed his work, what remains being related to  c2corg/v6_api#404

**Comment by fjacon** [comment]
https://github.com/c2corg/v6_api/issues/404 is closed.
should we close this issue ?

**Comment by stef74** [comment]
@asaunier can we close ?

**Comment by asaunier** [comment]
For me OK for closing
