### ISSUE TITLE
Routes editing form

### ISSUE THREAD

**Issue by asaunier** [c2corg/v6_ui#277]
* [x] It seems that when creating a skitouring (or snowshoeing) route, some mountainbiking fields still appear in the editing form: mtb_length_trail, mtb_height_diff_portages

**Comment by asaunier** [comment]
* [ ] Some list array attributes are not correctly set when no value is selected. For instance "route_types". Or maybe an API issue ? Related to https://github.com/c2corg/v6_ui/issues/110#issuecomment-208433615 and https://github.com/c2corg/v6_api/issues/145
* [ ] When updating a route with ``geometry: null``, the API says:
> {"description": "\"None\" is not a mapping type: Does not implement dict-like functionality.", "name": "document.geometry", "location": "body"}
Also an API issue?

**Comment by tsauerwein** [comment]
> When updating a route with geometry: null, the API says: > {"description": "\"None\" is not a mapping type: Does not implement dict-like functionality.", "name": "document.geometry", "location": "body"} Also an API issue?

Yes.

**Comment by asaunier** [comment]
OK I have created an issue in the API https://github.com/c2corg/v6_api/issues/226 and removed striked it through here.
