### ISSUE TITLE
Waypoint detail view

### ISSUE THREAD

**Issue by asaunier** [c2corg/v6_ui#280]
* [x] For "access" waypoints, the ``access period`` attribute is displayed in the "figures" section, which does not make sense since it is a text attribute that can potentially be quite long. See for instance http://c2corgv6-demo.gis.internal:6555/waypoints/735236/en => this attribute (and all other text attribute) should be displayed in the usual text section along with description.

**Comment by asaunier** [comment]
* [ ] Yes/no/no info attributes are not correctly displayed. For instance if a user has checked "no heating" in a hut editing form, the info will not be displayed in the detail view (as if "no info" was checked) => should display "Heating: no".

**Comment by ginold** [comment]
I will check that, can you give me an id of a wapoint with heating: no?

**Comment by asaunier** [comment]
Just create one! :P

**Comment by ginold** [comment]
are there other fields that are required to be showed even if their value = false ? 
for example, we have discussed that lift_access doesn't have to be shown if it's value = false, just show properties that are set to true.

**Comment by asaunier** [comment]
For me if you have yes/no/no info => "yes" and "no" should be displayed, "no info" should not.
Concerning "lift_access", we could drop value "no" and follow the above rule as well.

**Comment by asaunier** [comment]
* [ ] Don't use angular when Mako can be used for displaying data. For instance http://c2corgv6-demo.gis.internal:6555/waypoints/636651/fr ("climbing_outdoor" WP), ``rock_types`` is formatted using Angular like this:
```
      <article ng-init="rock_types = [&#39;gres&#39;]">
        <span translate class="value-title">rock_types</span><br>
        <span x-translate ng-repeat="type in rock_types" class="value">{{type}}{{$last ? '' : ', '}}</span>
      </article>
```
=> this is not the good way. It shows ugly angular brackets whereas Mako provides a boolean ``${loop.last}`` that can be used to know if this the last iteration of the loop. See http://docs.makotemplates.org/en/latest/runtime.html#the-loop-context

```
      <article>
        <span translate class="value-title">rock_types</span><br>
        % for rock_type in rock_types:
          <span x-translate class="value">${rock_type}</span>${'' if loop.last else ', '}
        % endfor
      </article>
```
Ditto for other data if needed.

**Comment by asaunier** [comment]
> Yes/no/no info attributes are not correctly displayed. For instance if a user has checked "no heating" in a hut editing form, the info will not be displayed in the detail view (as if "no info" was checked) => should display "Heating: no".

I think there is a bug in your recent changes. Yes/no work but "no info" is evaluated to "yes" at least the first time a migrated hut is modified!?

**Comment by asaunier** [comment]
> I think there is a bug in your recent changes. Yes/no work but "no info" is evaluated to "yes" at least the first time a migrated hut is modified!?

I have investigated and found out that if fields such as ``blanket_unstaffed`` is set to ``null``, the API understands it as "true" whereas if it not set/provide at all the field remains ``None``.
https://github.com/c2corg/v6_api/issues/229
