### ISSUE TITLE
Features icons on maps

### ISSUE THREAD

**Issue by asaunier** [c2corg/v6_ui#285]
* [x] When hovering a feature, its icon is magnified. But the standard-sized icon is still visible underneath.
* [ ] Features icons are too stacked on the map
* [ ] To avoid downloading every icon separately, we should use a font file containing the list of icons (in SVG). See maybe also https://github.com/c2corg/v6_ui/issues/152
* [x] Conflict between the "mouseover" and the "click" select interactions: when the icon is enlarged by the the mouseover, the feature is no longer found when clicking on it (see https://github.com/c2corg/v6_ui/pull/521#issuecomment-235838965)
* [x] When a feature style has been modified by the card mouseover in the advanced search, the feature icon is no longer updated/enlarged at feature mouseover (see https://github.com/c2corg/v6_ui/pull/521#issuecomment-235656710)

**Comment by asaunier** [comment]
> Features icons are too stacked on the map

Moving here the related issue #338 that I will consequently close as duplicate.

@tsauerwein suggested:
> When clicking on the map, we could show a popup with a list of features at that point.

@asaunier replied:
> Would it actually solve the current issue (too many icons at the same place)? Or do you mean we could have a cluster layout + a popup listing the object at this point?

**Comment by asaunier** [comment]
> ￼ When hovering a feature, its icon is magnified. But the standard-sized icon is still visible underneath.

Instead of showing a bigger image, a solution could be to keep the same size of icon but to change the color. This way the standard icon is not visible at all.

**Comment by ginold** [comment]
Copy from #152 
It seems possible in OL2 according to this fiddle: http://jsfiddle.net/ldonnet/bdzz0ujk/ using font characters (icons) as label. Probably also in OL3?
According to @tsauerwein

You can set a label with a custom font:
http://stackoverflow.com/questions/27809479/use-semantic-ui-or-font-awesome-icons-as-markers-in-openlayers3

Or you create a single sprite image and then use offset+size when defining your ol.style.Icon:
http://openlayers.org/en/master/apidoc/ol.style.Icon.html

**Comment by tsauerwein** [comment]
Because it is a bit tricky to use sprites with SVG files, we might consider generating a font with the SVG images.

**Comment by asaunier** [comment]
Several points of this issue are already fixed by https://github.com/c2corg/v6_ui/pull/521

> Features icons are too stacked on the map

I would leave this as is. Because we need to keep the icons distinct so that they may interact with the cards in the advanced search page. In addition with the pagination, we don't show too many features at the same time. When the map is zoomed to a "usable" area, the problem is greatly limited.

> To avoid downloading every icon separately, we should use a font file containing the list of icons (in SVG)

and

> Because it is a bit tricky to use sprites with SVG files, we might consider generating a font with the SVG images.

Currently we use ``ol.style.Icon`` to render the point features on the map. But it seems it's not possible to pass a CSS class instead of the file ``src``. http://openlayers.org/en/latest/apidoc/ol.style.Icon.html
Is there a way to pass an SVG font file and specify what character should be used?
