### ISSUE TITLE
Waypoint editing form

### ISSUE THREAD

**Issue by asaunier** [c2corg/v6_ui#286]
* [x] Don't show (and don't get) associated outings (see for instance http://c2corgv6-demo.gis.internal:6555/waypoints/edit/735236/en)

**Comment by asaunier** [comment]
* [x] Typo for equipment_ratings See https://github.com/c2corg/v6_ui/pull/289
* [ ] Incorrect types in JSON request for list attributes such as equipment_ratings, climbing_outdoor_types, etc. See https://github.com/c2corg/v6_ui/issues/110#issuecomment-208433615

**Comment by ginold** [comment]
i replaced all the letters by simply keeping only the degree sign, is that ok for you?

**Comment by asaunier** [comment]
> i replaced all the letters by simply keeping only the degree sign, is that ok for you?

No, we need to keep the E or N suffixes (but they should remain as is, even though the coord is negative).
