### ISSUE TITLE
Unexpected behavior for alert message for sign-in/registration

### ISSUE THREAD

**Issue by tsauerwein** [c2corg/v6_ui#295]
When entering wrong credentials for the sign-in or wrong information for the registration an error message is shown. This error popup looks like a modal dialog, that is it is centered in the middle and the background is slightly grayed out. But it does not behave like a modal dialog, I can still click on links, enter text and when I click on the grayed-out background, the dialog does not disappear.

**Comment by tsauerwein** [comment]
With #302, is the dialog closed when you click on the background?

**Comment by tsauerwein** [comment]
I still does not behave like a normal modal. If you click on the background, the dialog does not disappear.

**Comment by ginold** [comment]
i can handle that
