### ISSUE TITLE
Redirect after login might fail

### ISSUE THREAD

**Issue by tsauerwein** [c2corg/v6_ui#296]
1. Go to http://c2corgv6-demo.gis.internal/
2. Click on "Sign in".
3. Click on "No account yet?"
4. Remember that you actually have an account and click again on "Sign in" in the top menu.
5. The URL now looks like this: http://c2corgv6-demo.gis.internal/auth?from=http%3A%2F%2Fc2corgv6-demo.gis.internal%2Fauth%3Ffrom%3Dhttp%253A%252F%252Fc2corgv6-demo.gis.internal%252F
6. If you now successfully login, you will be redirected to the login page. Which is confusing because you are not sure if you are logged-in or not.

**Comment by asaunier** [comment]
Indeed :)

To combine with https://github.com/c2corg/v6_ui/issues/270 maybe?
