### ISSUE TITLE
Don't show "bin" icon in the cards when not authenticated

### ISSUE THREAD

**Issue by asaunier** [c2corg/v6_ui#297]
As for now a "bin/trash can" icon appears in the cards of associated documents (for instance in a WP page). It should only appear for users with permission "moderator".

**Comment by tsauerwein** [comment]
> It should only appear for users with permission "moderator".

The API does not enforce that an user is moderator. Every user can add/remove associations. I think we had a discussion about that?

**Comment by asaunier** [comment]
I don't remember the discussion, maybe :)

In v5, any authenticated user may create an association, only moderators may remove them.
It would indeed be consistent and handy that auth users may remove associations but since it is a quite destructive action, it might be safer to be a bit conservative :)

At least the button should not be displayed for anonymous users and a confirmation step is needed. See also https://github.com/c2corg/v6_ui/issues/191

**Comment by fjacon** [comment]
OK for last suggestion :  button should not be displayed for anonymous users and a confirmation step is needed.
