### ISSUE TITLE
Fix page title

### ISSUE THREAD

**Issue by asaunier** [c2corg/v6_ui#3]
The page title is a block defined in the base template:
https://github.com/c2corg/v6_ui/blob/master/c2corg_ui/templates/base.html#L9

The block is overloaded by inheriting templates:
https://github.com/c2corg/v6_ui/blob/master/c2corg_ui/templates/waypoint/view.html#L11-L13

It would be useful to use the document title as the page title. In the example above:
https://github.com/c2corg/v6_ui/blob/master/c2corg_ui/templates/waypoint/view.html#L15

The problem is that variables passed to the child templates are not available in the parent template and adding such variables in the pagetitle block generates an error. Most likely the same problem than http://stackoverflow.com/questions/16640078/pass-variable-from-called-mako-template-to-inherited-template
A namespace problem?
http://docs.makotemplates.org/en/latest/inheritance.html#using-the-parent-namespace-to-augment-defs

**Comment by tsauerwein** [comment]
Mako makes this really complicated. A work-around would be to extract the locale in the view and pass it as additional argument to the template. By doing this the variable `locale` will be available in the base and child template. See:
https://github.com/c2corg/v6_ui/commit/8d6d24f9574e9452875e7bcf8202a7207e7f3e59

The advantage is also that you could handle the case that the requested locale is not available.

**Comment by asaunier** [comment]
Thanks for the example commit. I will integrate it into the "editing" branch I'm working on:
https://github.com/c2corg/v6_ui/tree/editing

Passing only the current "locale" to the template is a problem though.
Because we need to get the other available cultures for a given document (and make it obvious that those cultural versions are available, for instance by adding links).
On the other hand it's a pity to get all attributes in all available cultures only to display links. I don't really know what we could do. Make an additional request to the API to a service that would list the available cultures?

About your comment:
https://github.com/c2corg/v6_ui/blob/8d6d24f9574e9452875e7bcf8202a7207e7f3e59/c2corg_ui/views/waypoint.py#L37-L38
```
# FIXME: what if desired culture is not available?
# either return 404 or select another culture (culture = ...)
```
If the required page is something like waypoints/1234/fr we want to show the "fr" cultural version. If it is not available => 404.

**Comment by tsauerwein** [comment]
> On the other hand it's a pity to get all attributes in all available cultures only to display links. I don't really know what we could do. Make an additional request to the API to a service that would list the available cultures?

We could add a field `available_locales` to the response:

        {
            'document_id': 123,
            ...
            'available_locales': ['en', 'fr'],
            'locales': [
                {'culture': 'en', ...}
            ]
        }

> If the required page is something like waypoints/1234/fr we want to show the "fr" cultural version. If it is not available => 404.

That sounds reasonable to me.

**Comment by asaunier** [comment]
> We could add a field available_locales to the response:

That would be a solution. Having the document titles in those culture as well might be a nice to have.

As for now, I pass an "other_cultures" dict to the templates:
https://github.com/c2corg/v6_ui/blob/editing/c2corg_ui/views/document.py#L60-L69
https://github.com/c2corg/v6_ui/blob/editing/c2corg_ui/templates/waypoint/view.html#L19-L26
but still relies on the full request with all cultures...
