### ISSUE TITLE
Map recentering tools

### ISSUE THREAD

**Issue by fjacon** [c2corg/v6_ui#304]
user position, simple search, geonames/OSM?, predefined C2C regions

**Comment by fjacon** [comment]
According to offer : geonames only

**Comment by asaunier** [comment]
For geonames see 
https://github.com/camptocamp/agridea_geoacorda/blob/master/jsapi/src/searchcontrol.js
https://github.com/camptocamp/agridea_geoacorda/blob/master/jsapi/src/partials/main.html#L46

**Comment by asaunier** [comment]
The "recenter on my position" directive has been pushed to master. But it only works with localhost or in an HTTPS page. Currently on the demo, pressing the button (in the advanced search maps) does nothing except displaying in the console:
> getCurrentPosition() and watchPosition() are deprecated on insecure origins. To use this feature, you should consider switching your application to a secure origin, such as HTTPS. See https://goo.gl/rStTGz for more details.

The geonames tool is still WIP.
