### ISSUE TITLE
Quality attribute in documents (1d)

### ISSUE THREAD

**Issue by fjacon** [c2corg/v6_ui#307]
- [x] Add the quality attribute in editing forms
- [x] Show the attribute in detailed view and list pages?
- [ ] Outings with poor quality are not shown in the list pages or on the home page feed

**Comment by asaunier** [comment]
Duplicate of https://github.com/c2corg/v6_ui/issues/272 ?

**Comment by fjacon** [comment]
sorry, closing

**Comment by loicperrin** [comment]
Reopen for this item:

- [ ] Outings with poor quality are not shown in the list pages or on the home page feed

**Comment by asaunier** [comment]
> Outings with poor quality are not shown in the list pages

That doesn't make sense. The advanced search pages has a "quality" filter for this needed. So nothing to do for list pages.

Home page feed, see https://github.com/c2corg/v6_api/issues/432
But honestly, for me it's not that easy!

**Comment by loicperrin** [comment]
> That doesn't make sense. The advanced search pages has a "quality" filter for this needed. So nothing to do for list pages.

OK
