### ISSUE TITLE
Use maintained fork of Typeahead

### ISSUE THREAD

**Issue by tsauerwein** [c2corg/v6_ui#309]
The official version of Typeahead is no longer maintained, we should use a fork that is actively developed: https://github.com/corejavascript/typeahead.js

See also: https://github.com/camptocamp/ngeo/issues/958

**Comment by asaunier** [comment]
Does it simply require to update this line https://github.com/c2corg/v6_ui/blob/master/package.json#L26 ?

**Comment by tsauerwein** [comment]
> Does it simply require to update this line https://github.com/c2corg/v6_ui/blob/master/package.json#L26 ?

Yes, maybe some modifications will be necessary for changes in Typeahead. It would make sense to do this switch as part of https://github.com/c2corg/v6_ui/pull/311.

**Comment by asaunier** [comment]
:+1:

**Comment by ginold** [comment]
Trying to install the maintained forks seems to be 'not-so-well-maintained' :+1: 

`npm install corejs-typeahead
npm ERR! 404 Not Found
npm ERR! 404 
npm ERR! 404 'corejs-typeahead' is not in the npm registry.`

I don't know how I should proceed from here?

**Comment by tsauerwein** [comment]
What irony.. ;)

You can use: `npm install github:corejavascript/typeahead.js#v0.11.1`

**Comment by ginold** [comment]
npm install github:corejavascript/typeahead.js#v0.11.1 `Cloning into bare repository...fatal: remote error: is not a valid repository name`

npm install github:corejavascript/typeahead.js      -||-

npm install corejs-typeahead `Cannot read property 'latest' of undefined` `corejs-typeahead' is not in the npm registry.`

npm install https://github.com/corejavascript/typeahead.js  `Error: ENOENT`

I think we might want to postpone this update maybe :)

**Comment by tsauerwein** [comment]
You seem to be using a different version of npm. Try it like this:

    npm install git://github.com/corejavascript/typeahead.js#v0.11.1

Same syntax as for ol3 or ngeo:
https://github.com/c2corg/v6_ui/blob/master/package.json#L21-L22

**Comment by ginold** [comment]
I updated npm yesterday and it took me some time to realize that it made my builds impossible. When trying to do a make check or make build I got errors like 'command not found, no receipt for build.js' or something like that. Finally @gberaudo helped me out and we had to go back and install an old version of NPM. Maybe we should watch out for this in the future.
Besides, I updated the package.json in and it is good and runnin'.

**Comment by fjacon** [comment]
to be closed ?

**Comment by ginold** [comment]
can be closed when #311  will be merged

**Comment by asaunier** [comment]
> can be closed when #311 will be merged

This PR is merged => closing the current issue.

**Comment by gberaudo** [comment]
We are now using the fork but a very old version (actually the latest official release from Twitter).
The fork did not release any version so far; have someone tested with their master branch?
