### ISSUE TITLE
Contents of the cards

### ISSUE THREAD

**Issue by asaunier** [c2corg/v6_ui#312]
- [ ] waypoint
- [ ] route
- [ ] outing

**Comment by ginold** [comment]
what is this issue about ?

**Comment by asaunier** [comment]
It's about deciding what data should be displayed in what cards for what document types.

For instance for waypoints:
* standard cards (used in the advanced search list page, in associated-WP sections, etc.): title + elevation + WP type (as icon) + region?
* simple search results cards (for the simple search + association tools): most likely the same data but in a more compact way?

**Comment by asaunier** [comment]
Duplicate of https://github.com/c2corg/v6_ui/issues/398
