### ISSUE TITLE
Data sent back to the API when editing a document

### ISSUE THREAD

**Issue by asaunier** [c2corg/v6_ui#313]
When a document is saved in the UI editing forms, the whole model is sent to the API, including ``areas`` and ``associations``.

Could it be a problem? For instance if the list of areas is updated for some reason?
Is it a waste of bandwidth if those attributes are not taken into account anyway?
Should we remove them before sending the request?

**Comment by tsauerwein** [comment]
They should be ignored in the API. But to reduce the amount of data that is transfered, they could be omitted.

**Comment by asaunier** [comment]
``associations`` is taken into account to update the associations. ``areas`` is anyway no longer retrieved in editing mode, thus not sent back at the API either.
