### ISSUE TITLE
SEO tips

### ISSUE THREAD

**Issue by asaunier** [c2corg/v6_ui#33]
It might be interesting to add SEO metas in the pages to indicate what pages should be indexed/followed. See https://yoast.com/robots-meta-tags/

A sitemap might also be useful:
https://support.google.com/webmasters/answer/156184?hl=fr

**Comment by tsauerwein** [comment]
About languages: http://nimbupani.com/declaring-languages-in-html-5.html

**Comment by asaunier** [comment]
Use slugs in the documents URLs /as in v5!). See #50

**Comment by ginold** [comment]
slugs are used, robots meta tags were added. Can be closed?

**Comment by tsauerwein** [comment]
The sitemap is still missing, but there is a new ticket for it: https://github.com/c2corg/v6_ui/issues/343

**Comment by asaunier** [comment]
Indeed @ginold @tsauerwein 
Closing.
