### ISSUE TITLE
Show documents as popup on the map when clicking them

### ISSUE THREAD

**Issue by fjacon** [c2corg/v6_ui#333]

**Comment by ginold** [comment]
Not sure to understand how it is supposed to work. Is it an extra enhancement ? has it been requested and described by the client?

**Comment by asaunier** [comment]
I am not sure it is really relevant to show a popup on the map when clicking on a feature:
* as for now, clicking on a feature opens the related document page, having to open the popup and then click on some link would add an extra step/click
* what data should be displayed in the popup? A card? But cards are already displayed in the list of result for the advanced search page (or the list of associated WP etc. for detail view pages)

I suggest to skip the popups and to replace them by a better interactions between cards and map features in the advanced search pages. See https://github.com/c2corg/v6_ui/pull/521

**Comment by tsauerwein** [comment]
I think this is relevant when you have multiple documents at the same position. If a click only returns a single document, you could jump to the document page. But if you get multiple documents, you would have to select the document you want. The popup could simply show a list of the document names.

**Comment by ginold** [comment]
In order to not disturb the already implemented click functionality, the popup could appear on hover - at the same time it highlights the card from the list.

**Comment by asaunier** [comment]
I am not sure we have that many cases where we have several features at the exact same place. It seems to me the hover/click interactions only "returns" one feature at a time.

The hover interactions already highlights and displays the name of the feature. With PR https://github.com/c2corg/v6_ui/pull/521 it also hilights the matching card in the list of results. For me it's already quite satisfaying and I don't think we have time to make more work on this part.

So I think we should restrict to what's suggested in https://github.com/c2corg/v6_ui/pull/521
