### ISSUE TITLE
Change the list pages to interact with the API for the advanced search

### ISSUE THREAD

**Issue by asaunier** [c2corg/v6_ui#337]
Discussed with @tsauerwein 

For the advanced search page, we need advanced interactivity in order to take into account the criterias and map extent set while searching (and to add criterias to the URL).

As for now the advanced search / list page is rendered server-side (for SEO reasons).

To avoid mixing server-side rendering and angular rendering, we suggest that:
* the rendering of the results list (+ the criterias form?) is made by angular and fed by AJAX. even when loading the page (that, by the way, will load a bit faster, at least the base page with no results).
* the existing list page server-side rendering is reused as a "sitemap" view that can be used by search engines to index the site. The sitemap will not be displayed to end users.

**Comment by asaunier** [comment]
related to https://github.com/c2corg/v6_api/pull/252

**Comment by tsauerwein** [comment]
> the existing list page server-side rendering is reused as a "sitemap" view that can be used by search engines to index the site. The sitemap will not be displayed to end users.

I was rather thinking of using sitemap.xml files, see https://github.com/c2corg/v6_api/issues/205

**Comment by asaunier** [comment]
OK, I didn't mean we would use the current list pages exactly as is, changing the templates to return an XML sitemap is indeed possible.
