### ISSUE TITLE
Sitemaps for SEO

### ISSUE THREAD

**Issue by asaunier** [c2corg/v6_ui#343]
Related to https://github.com/c2corg/v6_ui/issues/337 and https://github.com/c2corg/v6_api/issues/205

According to http://www.sitemaps.org/protocol.html
- a sitemap file cannot contain more than 50'000 URLs (and should be < 10MB)
- several sitemap files can be created and linked in a sitemapindex file (with the same URL number and weight limits)

What we could do:
- have sitemaps dedicated to a given document types (waypoints, routes, outings, etc.)
- for each document type, a sitemap document would contain X URLs (10? 30? 100? 1000?)
  - we would then have Y sitemaps for a given document type (`Y = ceil(number of document for this type / X)`)
- those `sitemaps` would be listed in one (or several?) `sitemapindex`

If listing `sitemapindex` files in a `sitemapindex` file is possible (not sure!) we could have the following structure:

```
main sitemapindex
  waypoints sitemapindex
    sitemap with waypoints from 1 to X
    sitemap with waypoints from X+1 to 2X
    ...
  routes sitemapindex
    sitemap with routes from 1 to X
    sitemap with routes from X+1 to 2X
    ...
```

This way we could have a main "sitemap" view/Mako template listing the "sitemapindex" for each document type.
Each document type view class would have a "sitemapindex" view/template that would point to as many sitemaps as needed to dispatch the total number of documents for this type.
Finally we would have a "sitemap" view/template that would be used to list the URLs.

This works only if it possible to have several levels of sitemapindex. Not sure...

Another issue about sitemaps:
- when a document is modified, its "lastmod" attribute in the sitemap must be updated accordingly (else the document might not be crawled again by the search engines). Which mean that parent sitemap's `lastmod` must be updated as well.
- deleted/created docs will also impact the content of the sitemaps/sitemapindex.

How can we make sure the sitemaps are kept up-to-date?

Can this be related to https://github.com/c2corg/v6_ui/issues/144 ?

Could we have some kind of event such as "document updated" (resp. created/deleted), with watchers that would update caches, sitemaps etc.?

**Comment by tsauerwein** [comment]
> This works only if it possible to have several levels of sitemapindex. Not sure...

Or the main index contains the links for all document types.

> How can we make sure the sitemaps are kept up-to-date?
> 
> Can this be related to #144 ?
> 
> Could we have some kind of event such as "document updated" (resp. created/deleted), with watchers that would update caches, sitemaps etc.?

We shouldn't overthink this one. We can simply cache the sitemap for 1/2 days and then recreate it from scratch,

**Comment by asaunier** [comment]
> Or the main index contains the links for all document types.

You mean we would have a single sitemapindex containing a list of sitemaps of whatever document type? That would work indeed. The downside is that we then could not distribute the generating of the sitemapindex among the various document-type-related views and do everything in the general document view (with requests to the API to get the total number of documents for each type).

> We shouldn't overthink this one. We can simply cache the sitemap for 1/2 days and then recreate it from scratch,

Right. That sounds simpler.

**Comment by asaunier** [comment]
@fjacon what do you think? WP5?

**Comment by fjacon** [comment]
marked as wp5

**Comment by stef74** [comment]
@asaunier what is the remaining job ?

**Comment by asaunier** [comment]
Nothing has been done yet.

**Comment by asaunier** [comment]
Having a robots.txt file would also make sense.
