### ISSUE TITLE
Bad rendering of the radio buttons in the history page

### ISSUE THREAD

**Issue by asaunier** [c2corg/v6_ui#344]
![sans titre](https://cloud.githubusercontent.com/assets/1192331/14979021/19851b3c-1120-11e6-92a5-75de45ea3a34.png)

**Comment by fjacon** [comment]
@asaunier @ginold looks good to me.
can we close ?

**Comment by asaunier** [comment]
> can we close ?

Nope, the problem has not been fixed.
Try for instance to click on some other radio button in http://c2corgv6.demo-camptocamp.com/routes/history/45168/fr

**Comment by stef74** [comment]
@shortoland could you please test

**Comment by shortoland** [comment]
OK for me, I close
