### ISSUE TITLE
Make removing association less prominent

### ISSUE THREAD

**Issue by tsauerwein** [c2corg/v6_ui#349]
Currently all associated documents have a big red trash bin in their card. In my opinion this trash bin is too prominent, unlinking a document is not a common operation that justifies such a visual prominence.

I would propose to add a small arrow, which shows a menu to unlink the document (similar to how it is done on Facebook). Also, currently it is not clear if you are deleting the document or simply deleting the association. There should also be a confirmation dialog ("Are you sure ..."), because it is not that simple to undo the deletion. 

![edit-facebook-status-update](https://cloud.githubusercontent.com/assets/266474/15244836/71dab158-1903-11e6-902e-fe8f9a57e188.png)

**Comment by asaunier** [comment]
:+1:

**Comment by ginold** [comment]
already implemented.
