### ISSUE TITLE
Redirect user when logging out from an authenticated-only page

### ISSUE THREAD

**Issue by asaunier** [c2corg/v6_ui#350]
When the current page is only relevant for authenticated users, if the user clicks on the "log out" button, he should be redirected to some public page (eg. home page or the auth page?) and not stay in the current page since he has no longer permission to see/use it. For instance:
* [x] account page
* [x] edit page

**Comment by gberaudo** [comment]
I would rather stay in current page for several reasons, notably:
- we need to implement displaying a message when the user is not logged in on these pages anyway;
- it is easy to handle token expiration the same way;
- the user can switch account easily.

**Comment by asaunier** [comment]
I do think it is a no sense for instance to display the "account page" (which is used to edit the user's settings) when the user is no longer authenticated: it's definitely confusing to display page the user has no right to see.

> we need to implement displaying a message when the user is not logged in on these pages anyway;

Yes and no. The user should be redirected to the authentication page (if not already logged in) when trying to access a auth-only page, with the "from" parameter set to the initial page, and (would be clearer) a message saying "please log in to access this page".

> the user can switch account easily.

Redirecting to the auth page (with the "from" parameter) does the job.

**Comment by gberaudo** [comment]
OK, implemented it in #360.
