### ISSUE TITLE
Simple search / association tool is not stable enough

### ISSUE THREAD

**Issue by asaunier** [c2corg/v6_ui#351]
The results are not always the same, sometimes for the same keyword only WP results are shown, sometimes only routes, sometimes both.
Expected behaviour for the simple search tool: results for all configured document types are always shown.

The route associating tool in the outing creation interface ("routes taken") works surprisingly, sometimes showing the "no result" partial and then the actual results:
<img width="660" alt="capture d ecran 2016-05-14 a 13 25 56" src="https://cloud.githubusercontent.com/assets/1192331/15268291/fbce7f80-19d9-11e6-8948-ca33a82b6f5c.png">

In addition it's a bit surprising that when typing "Dent de Barme" for instance, results like "Dent d'Oche" show up for instance, like if the search was on "dent" OR "barme". Here we want "dent" AND "barme".
At least the results with "dent" AND "barme" should be displayed first in the list.
See https://github.com/c2corg/v6_api/issues/206

**Comment by ginold** [comment]
most likely it shows 'no results' because there are no results for the others datasets (wp or/and outings).

**Comment by tsauerwein** [comment]
Search for "dent de" has results for all types:
http://c2corgv6-api.demo-camptocamp.com/search?q=dent%20de

But in this context (for `routes_taken`) you only want to see routes, right? So I guess the other document types should be hidden?

**Comment by asaunier** [comment]
> But in this context (for routes_taken) you only want to see routes, right? So I guess the other document types should be hidden?

Of course :)

Anyway I don't think it makes sense to show "no result" and then the results for the routes.

**Comment by tsauerwein** [comment]
> Anyway I don't think it makes sense to show "no result" and then the results for the routes.

That's what I mean with "So I guess the other document types should be hidden?". :)

**Comment by stef74** [comment]
@shortoland please test

**Comment by shortoland** [comment]
Behaviour has improved ("no result" not displayed anymore), but there is still a problem when searching for "dent de barme" for example: corresponding results are not displayed first:

![image100](https://cloud.githubusercontent.com/assets/20488365/18544434/da15dda4-7b34-11e6-89fa-b8fa61d848b8.png)

**Comment by stef74** [comment]
@asaunier what is the next step ?

**Comment by asaunier** [comment]
@stef74 perhaps @fjacon is better placed to answer your question

**Comment by stef74** [comment]
@fjacon could you give us visibility ?

**Comment by desnoes** [comment]
Basic search for articles with keyword 'petzl': the result is not appropiate, some articles do not contain the keyword 'petzl' (example: http://www.demov6.camptocamp.org/articles/731476/fr/changer-d-approche-11-idees-de-sorties-montagne-sans-voiture-au-depart-de-lyon)

**Comment by tsauerwein** [comment]
> The results are not always the same, sometimes for the same keyword only WP results are shown, sometimes only routes, sometimes both.
> Expected behaviour for the simple search tool: results for all configured document types are always shown.

I wasn't able to reproduce this behavior.

> Behaviour has improved ("no result" not displayed anymore), but there is still a problem when searching for "dent de barme" for example: corresponding results are not displayed first:

Moved to https://github.com/c2corg/v6_api/issues/557


> Basic search for articles with keyword 'petzl': the result is not appropiate, some articles do not contain the keyword 'petzl' (example: http://www.demov6.camptocamp.org/articles/731476/fr/changer-d-approche-11-idees-de-sorties-montagne-sans-voiture-au-depart-de-lyon)

This was related to the advanced search, see https://github.com/c2corg/v6_api/issues/397.
