### ISSUE TITLE
Routes attributes problems

### ISSUE THREAD

**Issue by asaunier** [c2corg/v6_ui#353]
* [ ] In /routes/736743/fr in the "hauteurs" section, one can see both "Dénivelé des difficultés: 104 m" and "difficulties_height: 1700 m" => looks like there are a duplicate field...

**Comment by fjacon** [comment]
same problem in camptocamp.org v5 ?

**Comment by fbunoz** [comment]
difficulties_height = altitude where the difficulties start ("altitude du début des difficultés").
Then it is not a duplicate field.
The route in v5 : http://www.camptocamp.org/routes/736743/fr/breche-du-peigne-versant-n

**Comment by tsauerwein** [comment]
See also: https://github.com/c2corg/v6_api/blob/master/c2corg_api/models/route.py#L48-L55
```
    # altitude du debut des difficultes
    difficulties_height = Column(SmallInteger)

...

    # Denivele des difficultes
    height_diff_difficulties = Column(SmallInteger)
```

**Comment by asaunier** [comment]
OK, then maybe the name of the attribute is a bit confusing. Shouldn't it be something like "difficulties_elevation"?
If you think it's OK like this, no problem for closing the issue.

**Comment by tsauerwein** [comment]
`difficulties_height` was the term used in v5. Feel free to change it to `difficulties_elevation` if you want.

**Comment by asaunier** [comment]
No it's OK. Closing the issue.
