### ISSUE TITLE
Errors remaining when creating/editing a route

### ISSUE THREAD

**Issue by asaunier** [c2corg/v6_ui#356]
* [ ] If set, the main waypoint name (``title_prefix``) should appear in front of the ``title`` input field. It should not be editable but changes when the main waypoint changes.
* [ ] ratings for activity "via ferrata" are missing.

**Comment by ginold** [comment]
Is it possible to merge all those related issues into a single one, for example 'creating/editing form issues' ? all 'errors remaining when creating/editing xxx'  + 'save cancel buttons'

**Comment by asaunier** [comment]
Sure, fill free to create a new issue aggregating those issues before closing them.

**Comment by asaunier** [comment]
Closed because duplicate of https://github.com/c2corg/v6_ui/issues/363
