### ISSUE TITLE
Layout

### ISSUE THREAD

**Issue by asaunier** [c2corg/v6_ui#357]
* [ ] ``h2``and ``h3`` titles in the document content (markdown formatting) have the same size.

**Comment by ginold** [comment]
could you specify where exactly do you find h2 and h3 with the same size?

**Comment by asaunier** [comment]
Simply edit a document and add in a description attribute something like:
```
## Some h2 title
### Some h3 title
```

**Comment by asaunier** [comment]
Closed because duplicate of https://github.com/c2corg/v6_ui/issues/363
