### ISSUE TITLE
WP 4 UI remaining errors/fixes

### ISSUE THREAD

**Issue by ginold** [c2corg/v6_ui#363]
I allowed myself to create a single bigger issue with all the others gathered here because we have so many of them that I have troubles navigating between them.
- [x] don't list outings in simple-search

- [x] If set, the main waypoint name (title_prefix) should appear in front of the title input field. It should not be editable but changes when the main waypoint changes.

- [x] ratings for activity "via ferrata" are missing.

- [x] h2 and h3 titles in the document content (markdown formatting) have the same size.

- [x]  users-associating tool crashes, see c2corg/v6_api#286

- [x]  routes-associating tool should not try to make the association directly and wait that the outing editing is done (ditto for the users tool in OUTING editing form)

- [x]  the "summary" page blocks because of "outing_type" and "elevation" attribute that do not exist in the editing form. For instance https://github.com/c2corg/v6_ui/search?utf8=%E2%9C%93&q=outing_type

- [x] When creating an outing, the outing title should be set by default to the name of the first associated route.

- [x]  the association tool should strip already associated docs out of the search results list.

- [x] Cancel and Save (or Preview) buttons should be available at every step

- [ ]  The dropdown list is cut off if not enough space below to render the full list of results => should display above in that case. (AWAITING INFO)

- [ ] ~~Show WP hierarchy ("sommet/sur-sommet", etc.) => how to do this with cards? See #348~~

- [x]  The "plus" button in the detail view page no longer reacts when clicking on it.

**Comment by asaunier** [comment]
@fjacon Should we close the other issues since they are all grouped here?

> ratings for activity "via ferrata" are missing.

@ginold This is for route editing, not outing editing. See https://github.com/c2corg/v6_common/blob/master/c2corg_common/fields_route.py#L174

**Comment by fjacon** [comment]
Yes we should close the other issues
thanks!

**Comment by asaunier** [comment]
An other problem I have just noticed:

* [ ] The "plus" button in the detail view page no longer reacts when clicking on it.

**Comment by asaunier** [comment]
* [ ] When associating a document (for instance a route to the current WP), if the related associated-docs block is not shown yet, the newly associated-document card is not visible until the page is reloaded.

**Comment by ginold** [comment]
solved in #328 while ago. 
BTW have a look at it, it should be mergeable.

**Comment by asaunier** [comment]
> The dropdown list is cut off if not enough space below to render the full list of results => should display above in that case. (AWAITING INFO)

I don't remember what the problem is. I will open an issue later if I get more info or feedbacks about it.

> the association tool should strip already associated docs out of the search results list.

That looks not that simple to implement, either on the API side or in the angular directives stack.
I see that v5 does not strip already associated docs out.
I guess we can ignore this problem for the moment and open an issue later if really needed.

**Comment by tsauerwein** [comment]
> That looks not that simple to implement, either on the API side or in the angular directives stack.

To do it on the API side you would have to send the associations that are currently selected when doing the search. Doing it client-side makes more sense to me. E.g. in `filter`: 
https://github.com/c2corg/v6_ui/blob/master/c2corg_ui/static/js/simplesearch.js#L248

**Comment by ginold** [comment]
It makes more sense indeed. But there is a lot going on to make it work, for example in the association-tool: the association tool is a <add-association> directive, witch has as template a <search> directive. The problem is that the end of the chain - the search directive - has to be aware of the document's associations in order to filter them. 

How do you communicate between controllers so that the search-controller knows about the details-view-controller document's associations?

**Comment by tsauerwein** [comment]
> How do you communicate between controllers so that the search-controller knows about the details-view-controller document's associations?

You can define a factory or service that contains the active associations and inject that instance in your two controllers. See also:
http://stackoverflow.com/questions/21919962/share-data-between-angularjs-controllers
http://stackoverflow.com/questions/20181323/passing-data-between-controllers-in-angular-js

**Comment by asaunier** [comment]
* [ ] Perhaps this issue/PR should also take into account the radio buttons pb in the history page:
https://github.com/c2corg/v6_ui/issues/344

**Comment by ginold** [comment]
If you have a little spare time, please do it yourself because I still don't get how this thing works :p you can add a commit to this pr.

**Comment by asaunier** [comment]
> If you have a little spare time, please do it yourself because I still don't get how this thing works :p you can add a commit to this pr.

OK we can fix it later in a separated PR. Let's get this one ready first.
