### ISSUE TITLE
"show more outings" button in route pages

### ISSUE THREAD

**Issue by asaunier** [c2corg/v6_ui#364]
In route pages, if the route has more than 10 outings, a "show more" button is displayed. It is supposed to redirect to the advanced search page listing all outings of this route.

As for now the button only redirects to the base outings search/list page. With no filtering parameter:
https://github.com/c2corg/v6_ui/blob/master/c2corg_ui/templates/helpers/view.html#L180

TODO:
* [x] add a ``route_id=1234567`` parameter to the target URL
* [x] make sure the API supports that kind of filter

**Comment by fjacon** [comment]
@tsauerwein is it feasible for alpha 1 ?

**Comment by tsauerwein** [comment]
A request to the API with [/outings?r=45967](http://c2corgv6-api.demo-camptocamp.com/outings?r=45967) returns the outings for a route (or with [/outings?wp=37355](http://c2corgv6-api.demo-camptocamp.com/outings?wp=37355)  for a waypoint). Note that this kind of query can (currently) not be combined with other filters.

**Comment by asaunier** [comment]
OK cool. So it means that we only have to add such params to the "show more" buttons.

**Comment by asaunier** [comment]
That would probably make more sense to assign the issue to @ginold or myself since it is finally a UI guidebook issue, not an API one.

**Comment by asaunier** [comment]
@tsauerwein 

> or with /outings?wp=37355 for a waypoint

Wouldn't it be more consistent to use ``/outings?w=37355`` instead ("w", not "wp")?
The ``type`` attribute in the documents returned by the API uses ``r`` or ``w``, not ``wp``.

**Comment by tsauerwein** [comment]
> Wouldn't it be more consistent to use /outings?w=37355 instead ("w", not "wp")?

Feel free to change it if you prefer it that way.

**Comment by asaunier** [comment]
>>Wouldn't it be more consistent to use /outings?w=37355 instead ("w", not "wp")?
> Feel free to change it if you prefer it that way.

See https://github.com/c2corg/v6_api/pull/295
