### ISSUE TITLE
Upgrade of components?

### ISSUE THREAD

**Issue by asaunier** [c2corg/v6_ui#365]
Pyramid 1.7 went out a few days ago:
http://docs.pylonsproject.org/projects/pyramid/en/latest/whatsnew-1.7.html
Would it be worth upgrading (so that c2corg UI and API stick to the latest versions)?

Same question for AngularJS whose latest version if 1.5.5 whereas we use 1.5.0.

**Comment by gberaudo** [comment]
We might be affected by the change regarding exception views. +1 for trying the update.

**Comment by asaunier** [comment]
Pyramid has not been upgraded yet but we now use AngularJS 1.5.6 (see https://github.com/c2corg/v6_ui/pull/451)

**Comment by fjacon** [comment]
What is the status of this issue ?
Should we freeze now the components ?

**Comment by tsauerwein** [comment]
Can this one be closed now?

**Comment by asaunier** [comment]
Yes
