### ISSUE TITLE
Add a "show more" button for associated routes blocks if len(routes)>30

### ISSUE THREAD

**Issue by asaunier** [c2corg/v6_ui#367]
See https://github.com/c2corg/v6_api/pull/294/files/e8db0a635a88691e13ea6b8c89e3681f319dbaed..4f0413c8db7f06076a812b090ab67d5021965b30#r64564087

**Comment by tsauerwein** [comment]
Just a note: You get a `total` field, so you could check if `total > len(routes)`. And currently the advanced search does not support to get routes for waypoint, This is a good argument to add that functionality.

**Comment by asaunier** [comment]
> so you could check if total > len(routes)

When would you need to do this?

> And currently the advanced search does not support to get routes for waypoint

You mean it's not possible (yet) to ask a URL such as ``routes?w=123456`` ?

**Comment by asaunier** [comment]
> You mean it's not possible (yet) to ask a URL such as routes?w=123456 ?

I have created an issue: https://github.com/c2corg/v6_api/issues/297
