### ISSUE TITLE
Advanced search UI (step 2)

### ISSUE THREAD

**Issue by asaunier** [c2corg/v6_ui#368]
TODO see https://github.com/c2corg/v6_ui/pull/373

**Comment by asaunier** [comment]
The work on this issue is in progress. I have several questions though:

To avoid changing the way the advanced search works with level1-filters (a new search is triggered whenever a filter is changed), I wonder if could not simply do the same for the filters shown when clicking on the "more filters" button? The list of result cards is no (fully?) visible when having "More filters" but the user can still see the items changing on the map.
Then the "cancel and close" or "apply filters" buttons would no longer be useful and could be replaced by a simple "Close" or "See the results" button.

The sliders are currently (easily) used to filter a given numeric attribute to some range (eg. elevation).
That would be cool to be able to use the sliders for non numeric attributes, for instance the ratings (users would for instance use the sliders to filter on routes rated from 6a to 6c or PD+ to AD+). But I don't really know if this is possible because:
* the sliders expect numeric values, eg. 1, 2, 3, 10, 100, not strings such as 6a, 6c, PD+ or AD+
* can the API really compare ratings and return routes whose ratings would be in a given range of ratings?

I was also wondering if we could use the sliders approach to avoid multiplicating the min/median/max attributes. For example with climbing_outdoor_site waypoints, we have height_min, heigh_max, height_median
https://github.com/c2corg/v6_api/blob/master/c2corg_api/search/mappings/waypoint_mapping.py#L37-L42
I don't know how we could do that, but as a user I would expect to use the sliders to provide the min/max height and that the API gives me back the list of WP whose height_min/height_max (height_median?) fit the range. That's a bit tricky because the filtering would be done on several attributes...

**Comment by tsauerwein** [comment]
> can the API really compare ratings and return routes whose ratings would be in a given range of ratings?

The API doesn't know that for example PD+ < AD+. If you want routes with a rating between PD and ED, you would have to set a filter with `PD-,PD,PD+,...,ED-,ED,ED+`. Maybe not very practical.

> I was also wondering if we could use the sliders approach to avoid multiplicating the min/median/max attributes.

Wouldn't filtering on `heigh_max` be enough?

**Comment by asaunier** [comment]
> The API doesn't know that for example PD+ < AD+. If you want routes with a rating between PD and ED, you would have to set a filter with PD-,PD,PD+,...,ED-,ED,ED+. Maybe not very practical.

That's not really handy, indeed.

And note very logical.
For instance with ``access_time``, which is a pseudo-numeric field:
https://github.com/c2corg/v6_common/blob/master/c2corg_common/attributes.py#L206-L220
we could not simply say that we're looking of access_time=10,45 but access_time=10min,15min,20min,30min,45min (not to mention the hours).

And wouldn't it cause performance issues? I guess it's more efficient to have a ``rating < somevalue`` clause then a ``rating in (<a bunch of values>)`` one. With the latter you can't really use indexes in postgres, can you? What about elasticsearch?

> Wouldn't filtering on heigh_max be enough?

Maybe yes.

**Comment by asaunier** [comment]
I more and more think we are going to have usability and code problems with the ratings questions I mentioned above. As for now I have something like:
![search](https://cloud.githubusercontent.com/assets/1192331/15934511/20cc27c6-2e64-11e6-92f4-d1a442f1b6e5.png)
which means that if I am looking for a climbing site with routes rating from 5b to 6c for instance, I have to:
* open the "min rating" filter and check all ratings up to 5b
* ditto for the "max rating" filter: check all rating from 6c and above

I could use a single-select dropdown list but then the code shoud convert "min_rating" from "5b" to "2,3a,3b,3c,4a,4b,4c,5a,5b". Oops! And if such a filter is provided in the URL (permalink), it should do the reverse conversion. Re-oops!

In addition I don't think it is very user-friendly (and state-of-the-art UI) to have use several filters to do so. The most convenient solution would be to have a single "rock climbing rating" slider I could use to set the min rating and the max rating I am expecting. Of course that means the API should use the provided min value to compare with attribute "rating_min" and the max value with "rating_max".

**Comment by tsauerwein** [comment]
Yes, I agree.

For search fields that are somehow sortable (like ratings) we can index a number instead of the constant in ElasticSearch. For example for the rating `'2': 0`, for `'3a': 1` and so on. When doing a search, you could query `..&rating=5a,7a` to search for routes with ratings between 5a and 7a. In the API we would translate the rating constants to numbers. That would be relatively simple to implement.



> In addition I don't think it is very user-friendly (and state-of-the-art UI) to use several filters to do so. The most convenient solution would be to have a single "rock climbing rating" slider I could use to set the min rating and the max rating I am expecting. Of course that means the API should use the provided min value to compare with attribute "rating_min" and the max value with "rating_max".

Yes! I am already doing something similar for `start_date`/`end_date` for outings. We can do the same for ratings/height/....

**Comment by asaunier** [comment]
> For search fields that are somehow sortable (like ratings) we can index a number instead of the constant in ElasticSearch. For example for the rating '2': 0, for '3a': 1 and so on. When doing a search, you could query ..&rating=5a,7a to search for routes with ratings between 5a and 7a. In the API we would translate the rating constants to numbers. That would be relatively simple to implement.

That would be cool indeed!

> I am already doing something similar for start_date/end_date for outings. We can do the same for ratings/height/....

:+1:

**Comment by asaunier** [comment]
I have merged PR https://github.com/c2corg/v6_ui/pull/373 because it was getting too big and will create a new branch/PR.

Still to be addressed:

TODO
* [ ] add the missing route filters
* [ ] outing filters
* [ ] Skip the map extent when filtering on a WP or a route ID? (with permalink like ``outings?r=123456``)
* [ ] Handle date filters

TOFIX
* [ ] slider handles are not fully reset when clearing filters

* [ ] Hilight the feature on the map when hovering a card (and vice-versa?)
* [ ] allow to bypass the map extent filtering as in Airbnb?
