### ISSUE TITLE
Blank cards in debug mode

### ISSUE THREAD

**Issue by asaunier** [c2corg/v6_ui#369]
When debug mode is on (``?debug``), the advanced search cards + the simple search results cards ("suggestion") remain blank.

A similar code is used in both cases and the issue (and solution!) is most likely the same. Perhaps because the partials are not included as expect when using
```
  var template = function(doctype) {
    return $templateCache.get('/static/partials/suggestion_' + doctype + '.html');
  };
```
https://github.com/c2corg/v6_ui/blob/master/c2corg_ui/static/js/suggestiondirective.js#L11-L13
https://github.com/c2corg/v6_ui/blob/master/c2corg_ui/static/js/card.js#L17-L19

**Comment by fjacon** [comment]
can this be closed ?

**Comment by asaunier** [comment]
No, the problem is still valid => not possible to work in debug mode in the advanced search pages for instance, which is not very handy :(

**Comment by ginold** [comment]
In the other project on EPFL, in prod mode it works with `angular.templateCache` as well, but when in dev mode, the actual HTML templates are loaded. We should have the same behavior.

**Comment by asaunier** [comment]
Could you point where this is done in EPFL code?

**Comment by asaunier** [comment]
> In the other project on EPFL, in prod mode it works with angular.templateCache as well, but when in dev mode, the actual HTML templates are loaded. We should have the same behavior.

I am not sure EPFL use the templateCache the same way we do.

I mean, the partials we pass as ``templateUrl`` in our directives actually work fine in debug mode. But not the dynamic template paths, like https://github.com/c2corg/v6_ui/blob/e1724c8c11fa5483bd78954a9c042f54a1132bc1/c2corg_ui/static/js/card.js#L18 and I don't see such system in https://github.com/camptocamp/epfl_authgeoportail/search?utf8=%E2%9C%93&q=templateCache&type=Code

**Comment by ginold** [comment]
@sbrunner should know!

**Comment by asaunier** [comment]
Actually it is no surprise that code like https://github.com/c2corg/v6_ui/blob/master/c2corg_ui/static/js/card.js#L17-L19
```
return $templateCache.get('/static/partials/cards/' + doctype + '.html');
```
does not work in debug mode. Because it tries to retrieve some template cache that has never been create (with ``$templateCache.put()``), except in the "prod" mode that explicitely creates those template cache https://github.com/c2corg/v6_ui/blob/master/c2corg_ui/templates/templatecache.js#L36

A solution would be to include the built template cache file in debug mode as well in ``templates/base.html``:
```
     <script src="${request.static_url('%s/photoswipe/dist/photoswipe-ui-default.js' % node_modules_path)}"></script>
     <script src="${request.route_url('deps.js')}"></script>
     <script src="${request.static_url('c2corg_ui:static/js/main.js')}"></script>
+    <script src="${request.static_url('c2corg_ui:static/build/templatecache.js')}"></script>
 % else:
```
That indeed fixes the card issue in debug mode but then all templates are retrieved from the template cache and no longer from the partial files themselves (running ``make build`` is then needed when changing something in the partials).

Actually we would need to test whether ``$templateCache`` has the template in cache. If not the partial should be retrieved with some way and than put to ``$templateCache``. That looks like the tricky part.

**Comment by asaunier** [comment]
> Actually we would need to test whether $templateCache has the template in cache. If not the partial should be retrieved with some way and than put to $templateCache. That looks like the tricky part.

I have tried
```
  var template = function(doctype) {
    var path = '/static/partials/cards/' + doctype + '.html';
    var tpl = $templateCache.get(path);
    if (goog.DEBUG && !tpl) {
      $http.get(path).success(function(html) {
        $templateCache.put(path, html);
        tpl = html;
      }); 
    }   
    return tpl;
  }; 
```
but since ``$http.get()`` makes an aynchronous request, the ``template`` function has ended before the template has actually been retrieved...

I have also found this piece of code for a similar problem
https://github.com/angular/angular.js/issues/1039#issuecomment-10673465
using
```
compile: function(tElement, tAttrs) {
      var tplURL = '/static/partials/cards/' + tAttrs.type + '.html';
      templateLoader = $http.get(tplURL, {cache: $templateCache})
        .success(function(html) {
          tElement.html(html);
        });

      return function (scope, element, attrs) {
        templateLoader.then(function (templateText) {
          element.html($compile(tElement.html())(scope));
        });
      };
    }
```
It works if a ``type`` attribute is hard-coded in the card directive: 
```
<div class="list-item" ng-class="[searchCtrl.doctype]" ng-repeat="doc in searchCtrl.documents">
    <app-card app-card-doc="doc" type="waypoints"></app-card>
  </div>
```
but fails if I try to get the type from the passed documents:
```
<div class="list-item" ng-class="[searchCtrl.doctype]" ng-repeat="doc in searchCtrl.documents">
    <app-card app-card-doc="doc" type="doc.type"></app-card>
  </div>
```
=> the content of ``type`` is evaluated litteraly, not interpreted.
