### ISSUE TITLE
Upgrade AngularJS and extensions

### ISSUE THREAD

**Issue by asaunier** [c2corg/v6_ui#37]
We use Angular 1.3.5 (default version shipped with pyramid_closure) whereas latest angular version is 1.4.8 (1.4.7 in ngeo).

We also use angular-gettext 1.1.3 whereas latest version is 2.1.2 according to https://github.com/rubenv/angular-gettext/blob/master/bower.json

**Comment by gberaudo** [comment]
I have just done this on my branch.
