### ISSUE TITLE
Duplicated property in appx.SimpleSearchDocument?

### ISSUE THREAD

**Issue by asaunier** [c2corg/v6_ui#374]
I see that type `appx.SimpleSearchDocument` has both properties `document_type` and `documentType`:
https://github.com/c2corg/v6_ui/blob/master/c2corg_ui/externs/appx.js#L38-L47

`document_type` seems not used in the simple search controller:
https://github.com/c2corg/v6_ui/blob/master/c2corg_ui/static/js/simplesearch.js

Perhaps it can be removed?

**Comment by gberaudo** [comment]
Keeping the version with the underscore would be consistent with the other properties.

**Comment by asaunier** [comment]
Perhaps. But the first question to answer: do we really need to have both properties?

**Comment by gberaudo** [comment]
@asaunier, obviously we only want one.

**Comment by asaunier** [comment]
I guess so :)
OK reformulating my question: why do we have those 2 properties ? what can we do to have only one? where should we made changes? who will take care of this?

**Comment by gberaudo** [comment]
These two properties were introduced by @tsauerwein in f06fcca8.
I looked quickly to the commit and it might be a mistake since only one property is used.
@tsauerwein do you have some input about this?

**Comment by tsauerwein** [comment]
If I check the actual response of the simple search both definitions are wrong:
http://c2corgv6-api.demo-camptocamp.com/search?q=mon&pl=en

There is only `type`.

**Comment by gberaudo** [comment]
What a `coup de théâtre`!

**Comment by asaunier** [comment]
I have tried to remove ``document_type`` and ``documentType`` and to replace them by ``type`` but it doesn't work (no compilation error but the simple search returns blank results). Ditto if only ``document_type``. It works if only ``documentType``. No idea why. See https://github.com/c2corg/v6_ui/pull/444

**Comment by stef74** [comment]
@asaunier this question is allready relevant ?

**Comment by ginold** [comment]
I thought i had already answered this question: `documentType` was set in the times when `type` was not returned by the API yet, so we have to track it down and remove it from it's origin!
