### ISSUE TITLE
New outing button in waypoint detail view page

### ISSUE THREAD

**Issue by asaunier** [c2corg/v6_ui#375]
I have noticed there is a "add a new outing to this document" button in the list of recents outings in a WP detail view page.

I am not sure it is relevant since it opens the outing creation form with a GET parameter ``?waypoints=123456`` => but it doesn't really help choosing a route to be associated to the outing.

On the other hand it would make sense to show an "add route to this WP" button in the WP detail view pages (as in v5).

### In v5

The "add an outing" button is only available in the route detail view page, not in the summit detail view pages.
For instance: http://www.camptocamp.org/summits/40576/fr/dome-des-glaciers
On the other hand the summit detail view page offers a "add a route" button.

Climbing outdoor sites are an exception in v5:
* outings may be directly associated or created from a "climbing outdoor site" page
* such pages have a "add your outing" button
* such pages have no "add a route" button
See for instance http://www.camptocamp.org/sites/102326/fr/gaillands

### In v6

* climbing outdoor sites are waypoints just like summits
* it should be possible to create route ("add route" button) from such pages, just like in summit pages or any other WP page. Routes may also be associated to climbing outdoor sites, as to any WP types.
* @tsauerwein is it possible to have outings directly associated to "climbing outdoor" WP? I guess outings associated to climbing outdoor site in v5 will also be associated in v6 thanks to the migration script?
* should we introduce a special case for climbing outdoor WP and add a "add your outing" button to the climbing outdoor WP detail view pages (as in v5)? To any WP-type detail view pages?
* @ginold told me that currently the "remove association" buttons in the "recent outings" cards in WP pages do not work since the association is indirect (outings are associated to routes that are associated to the current WP). Except maybe for outings related to "climbing outdoor"?
* what about routes indirectly associated to a WP (through WPs that are associated to the current WP)? I guess it will not be possible to dissociate them either...

This is a quite complicated topic...

**Comment by fjacon** [comment]
Also see : https://github.com/c2corg/v6_ui/issues/402#issuecomment-234656396

**Comment by asaunier** [comment]
Having outings directly associated to climbing sites as in v5 is not possible. And not a good thing because it would create another exception. It's better to keep the standard relationships between pages: waypoints <> routes <> outings

Here is a possible workflow for v6:

- outings in climbing_sites can only be associated to/created from regular routes. Those routes could be multi- or single-pitch (no distinction).
- if someone wants to add an outing to a climbing-site, he/she must create first at least one route associated to the climbing site.
- since in v5 some outings are directly associated to climbing_sites, the v5>v6 migration script must convert those direct associations. For instance by creating a dummy route (named the same way than the climbing site) that will be associated between the climbing site WP and the outing. 

By the way: in v5, it is not possible to create outings associated to indoor climbing_sites. In v6, I suggest to drop this restriction: same behaviour for all WP (summits, accesses, indoor climbing sites, outdoor climbing sites, etc.).

**Comment by stef74** [comment]
For migration : created generic route
For outing : route needed 
No direct outing with WP

**Comment by loicperrin** [comment]
> By the way: in v5, it is not possible to create outings associated to indoor climbing_sites

In V6 it will be possible to create routes associated to each type of WP (even indoor climbing_sites), and then to create outings on this routes.

**Comment by asaunier** [comment]
Closing this issue because:
* the "create outing" button has been removed from the WP detail views
* an API issue already exists concerning the migration of climbing_outdoor_sites related outings from v5 => https://github.com/c2corg/v6_api/issues/351
