### ISSUE TITLE
Associated routes are no longer displayed in the WP detail view pages

### ISSUE THREAD

**Issue by asaunier** [c2corg/v6_ui#376]
Only the "recent outings" are.

**Comment by fjacon** [comment]
I understand is it due to the fact that we get too many associated routes. Correct ?

**Comment by asaunier** [comment]
I don't think it is related: the associated route section is missing even for WP with a few associated routes. The matching API request does actually return the associated routes => it's a UI problem, not an API one.

**Comment by asaunier** [comment]
> I don't think it is related

Mmmmm, actually I am not that sure.

I have noticed that in my own instance, with a not up-to-date version of the API (mid of last week), the associated routes appeared until I upgraded my API (no associated routes since then). My API still returns associated routes but maybe something has changed (in the format of the response?) and the UI no longer find the associated routes in the API response?

I am investigating...

**Comment by tsauerwein** [comment]
> My API still returns associated routes but maybe something has changed (in the format of the response?) and the UI no longer find the associated routes in the API response?

Yes, the format has changed with https://github.com/c2corg/v6_api/pull/294. Sorry I didn't mention it explicitly.
https://github.com/c2corg/v6_api/blob/master/c2corg_api/views/waypoint.py#L358-L364
