### ISSUE TITLE
Editing a way point : Comment about the changes 

### ISSUE THREAD

**Issue by fjacon** [c2corg/v6_ui#378]
"Comment about the changes" should appear as mandatory.
(missing a *)

**Comment by asaunier** [comment]
Are you sure? That looks like an optional field (that people generally omit in wikis :P ).

**Comment by fjacon** [comment]
This is the field used for describing a revision of the document
Also the "save" button does not work if the field is empty

**Comment by asaunier** [comment]
I'm pretty sure this field is optional. And it's not in the list of required attributes for waypoints:
https://github.com/c2corg/v6_common/blob/master/c2corg_common/fields_waypoint.py#L11-L17

There must be another problem with the "save" button. For instance if you make a change only in the map but not in an attribute, the "save" button does not detect that you have made changes and stay disabled (I think there's an issue about that but could not find it in github...)

**Comment by fjacon** [comment]
ok, closing the issue
