### ISSUE TITLE
Edit a waypoint : change association cannot be saved

### ISSUE THREAD

**Issue by fjacon** [c2corg/v6_ui#387]
Edit a waypoint
Add an association
the "save" button is not clickable (I guess because the change is not detected)

**Comment by ginold** [comment]
it is due to the form.$valid and $pristine things, that won't update until you at least touch one of the required fields, for example the title ;/

**Comment by fjacon** [comment]
then how can I just change or add association ?

**Comment by ginold** [comment]
There is the stupid way : add/change association and then type anything in the title and delete it after (or maybe just clicking on the title-filed is enough).
Indeed it is something to fix.

**Comment by asaunier** [comment]
If it is too complicated to handle the "Save" button status beacuse of non form-related elements (map, associations), we could simply remove those form.$valid and $pristine things.

**Comment by asaunier** [comment]
By the way: when the preview is available, it will make sense to replace the "Save" button by a "Preview" button and to show the "Save" button only on the preview page.

**Comment by tsauerwein** [comment]
Can't you manually call `$setDirty` when something related to the associations changes?
https://docs.angularjs.org/api/ng/type/form.FormController

**Comment by ginold** [comment]
yeah, we should be able to create our own check like `canBeSaved = hasActivity && hasTitle && hasAssociation ` etc

**Comment by fjacon** [comment]
@ginold @asaunier what is the status of this issue ?

**Comment by ginold** [comment]
it is fixed. Closing.
