### ISSUE TITLE
Icons

### ISSUE THREAD

**Issue by asaunier** [c2corg/v6_ui#390]
> tu peux demander au client quel picto préfère-t-il quand il y en a 2 de mêmes à choix : Cascade1-2, Lac1-2, SAE1-2, Bisse?

Here are the icons the client prefers:
- cascade1
- lac1
- sae1 (but none of the 2 proposals is really good - it's a pity that Altimax has not taken into account the suggestion to use something like the climbing gym icon of http://www.6a-escalade.com/wp-content/uploads/2011/02/boom+bref+buzz_picto.jpg)
- bisse2

**Comment by fjacon** [comment]
@ginold @asaunier can we close this ?

**Comment by asaunier** [comment]
I don't think the WP icons have been updated.

**Comment by stef74** [comment]
@shortoland please test

**Comment by shortoland** [comment]
@stef74 When can I find the references icons ? It's hard for me to check without more information.

**Comment by ginold** [comment]
Here is a screenshot of waypoint-type icons
![screenshot from 2016-09-13 09 01 52](https://cloud.githubusercontent.com/assets/7814311/18464337/c0f8bac6-7990-11e6-9e13-e5312fb654de.png)

**Comment by shortoland** [comment]
@ginold Would you have a screen shot for 'old' ones as well ?

**Comment by shortoland** [comment]
There is a confusion between "Camping" and "Camp de base"
"Cascade" is reversed (up/down)
When creating a webcam, an URL is required, but there is not specific field to give information

Not listed (and not tested) during WP creation: Confluent, Falaise, Glacier, Rimaye, Camping, Webcam, Bisse 1, Cascade 2, Accès/parking, Crevasse, Lac 2, SAE 2.

**Comment by ginold** [comment]
![screenshot from 2016-09-14 09 57 41](https://cloud.githubusercontent.com/assets/7814311/18504268/b6a12942-7a61-11e6-9822-9195bf39cde8.png)

**Comment by stef74** [comment]
@shortoland please test

**Comment by shortoland** [comment]
[ ] Icon for "Camping" is the one for "Camp de base"
[ ] "Cascade" is reversed (up/down)
[ ] Not listed during WP creation: Confluent, Falaise, Glacier, Rimaye, Accès/parking, Crevasse
[ ] Not tested (created but can't see it): Webcam

**Comment by ginold** [comment]
points not listed during WP creation is another problem i think - moving it from here.

webcam icon looks so :
![screenshot from 2016-09-26 15 51 39](https://cloud.githubusercontent.com/assets/7814311/18837128/f98a4ea0-8402-11e6-9219-117fd8fa1ae1.png)

**Comment by asaunier** [comment]
> Not listed (and not tested) during WP creation: Confluent, Falaise, Glacier, Rimaye, Camping, Webcam, Bisse 1, Cascade 2, Accès/parking, Crevasse, Lac 2, SAE 2.

@shortoland Some of those WP are no longer supported. The official list of waypoint types is here: https://github.com/c2corg/v6_common/blob/master/c2corg_common/attributes.py#L17-L51
Icons with 1 or 2 are variants of the same icon => only one is needed.

**Comment by shortoland** [comment]
@asaunier My last list is the one transfered to #650

**Comment by asaunier** [comment]
@shortoland I don't understand. For me all waypoint types listed in #650 are not relevant (I have closed the issue by the way).

**Comment by shortoland** [comment]
@asaunier I agree, but I was speaking of versions 1 or 2 of some icons.
I did not have the official list when checking icons.

**Comment by asaunier** [comment]
* [ ] Not sure it has been fixed in some branch/PR but the "basecamp" icon is missing in the UI. For instance http://c2corgv6.demo-camptocamp.com/waypoints/722667/fr/cashapampa

**Comment by ginold** [comment]
oops, i renamed it to camp_site !

**Comment by asaunier** [comment]
> Not sure it has been fixed in some branch/PR but the "basecamp" icon is missing in the UI. 

Fixed, even though the icon centering is a bit weird:
![sans titre](https://cloud.githubusercontent.com/assets/1192331/18926084/b786ceb0-85b6-11e6-870a-b2290f6a818c.png)

**Comment by ginold** [comment]
thats because the icon has to fit into the canvas with the other icons 
![screenshot from 2016-09-29 09-10-16](https://cloud.githubusercontent.com/assets/7814311/18944241/9854772c-8624-11e6-933e-94a07fe8cb0c.png)
I could stretch it to the top and move a little.

**Comment by tsauerwein** [comment]
> I could stretch it to the top and move a little.

Centering would be good.

**Comment by ginold** [comment]
it's not really a solution, because it would appear in the middle of the text in cards:
![screenshot from 2016-09-29 09-29-25](https://cloud.githubusercontent.com/assets/7814311/18944720/40e25588-8627-11e6-92dd-89168b4841e7.png)

but i can move and center it in the svg file, as this is the one that is loaded through ol3 separately and not from the font.

**Comment by asaunier** [comment]
Isn't it possible to "vertical center" the elements of the line (icon and text)?

**Comment by asaunier** [comment]
Do we have an icon for users/profiles?

**Comment by ginold** [comment]
you mean a generic one? if yes, we can use the one found in the outing cards.

**Comment by asaunier** [comment]
> you mean a generic one?

Yes, like the icons for WP, routes, outings etc.

**Comment by ginold** [comment]
then `.icon-user` is your friend!

**Comment by asaunier** [comment]
> then .icon-user is your friend!

OK thanks!

Actually I need an SVG icon to show it on the map (not a class or an SVG font). This file is a good candidate: https://github.com/c2corg/v6_ui/blob/master/c2corg_ui/static/img/social/user.svg
On the other hand it has 2 problems:
* a bit too big, I have to apply ridiculous scales to show it the good size on the map
* black instead of orange, as the other map icons like https://github.com/c2corg/v6_ui/blob/master/c2corg_ui/static/img/documents/images.svg https://github.com/c2corg/v6_ui/blob/master/c2corg_ui/static/img/documents/outings.svg

Would it make sense to create a ``profiles.svg`` (not ``user.svg`` because the module name of the user profiles document is ``profiles``), a bit smaller and orange, stored in https://github.com/c2corg/v6_ui/blob/master/c2corg_ui/static/img/documents/ ?

**Comment by ginold** [comment]
would you prefer to change this one, or create a second one ?

**Comment by asaunier** [comment]
I don't know. Can we use the same file both for the map and in the other places already using it like the outing cards?

**Comment by asaunier** [comment]
Is there an icon for:
* [ ] articles
* [ ] areas
* [ ] books
* [ ] xreports  (accident reports)
?

I think I had the case of a missing article icon in the homepage feed timeline.

**Comment by ginold** [comment]
I don't see any icons for those document types. If there are not - should I look for one in the bootstrap's default icons? create one myself? ask our design company to do it?

**Comment by asaunier** [comment]
> I don't see any icons for those document types

It seems such icons are not provided.

> should I look for one in the bootstrap's default icons? create one myself? ask our design company to do it?

@fjacon can we ask the designer for those icons?
@ginold can you see bootstrap icons that could match?

**Comment by ginold** [comment]
the bootstrap's icon that could pass:

accidents: `glyphicon-exclamation-sign` or `glyphicon glyphicon-alert`
books: `glyphicon glyphicon-book`

**Comment by asaunier** [comment]
> accidents: glyphicon-exclamation-sign or glyphicon glyphicon-alert

Indeed, thanks.
What about using the icon from v5? 
https://github.com/c2corg/camptocamp.org/blob/master/web/static/images/svg/xreports.svg

> books: glyphicon glyphicon-book

:+1: 
The v5 icon is ugly.

For areas, let's use the v5 icon: https://github.com/c2corg/camptocamp.org/blob/master/web/static/images/svg/areas.svg

For articles, the v5 icon is https://github.com/c2corg/camptocamp.org/blob/master/web/static/images/svg/articles.svg
I guess it's OK to use it in v6 as well. 

@ginold could you add the icons in the needed places (SVG fonts? SVG single icons?):
* articles, xreports, areas => use v5 icons
* books => use glyphicon-book
Please note the articles and books are not geolocalized, thus do not require a map icon.

**Comment by ginold** [comment]
v5 icons could be a good option, but they are much different from the ones we use - they are not 'flat'. Should I import and use them 'as is' or should I flatten them and make them more similar to the others?

**Comment by asaunier** [comment]
As you want but improving those icons is a low priority task. Don't spend too much time on this.

By the way, do we really need those icons? For xreports, for sure since they will be shown on a map. But what about areas, articles and books? In detail view pages, such icons are not shown, only badges, right? Where else do we use icons?

**Comment by asaunier** [comment]
> By the way, do we really need those icons?

I guess we need them, at least of the feed timeline?

**Comment by ginold** [comment]
- xreports - needed
- articles - icon would be needed to put into the side menu!
- books - same as above? and below (if there will be a books/index.html list page).
- areas - 'might be useful' to put them into the cards "parce que c'est joli", if not they are a little empty with just some text. The best would be to have an appropriate icon for each area type.

**Comment by asaunier** [comment]
> books - same as above? and below (if there will be a books/index.html list page).

There will be an advanced search page for books. But in the guidebook section (as for route, WP, etc.). No dedicated entry in the sidemenu as for articles.

> The best would be to have an appropriate icon for each area type.

That's not that useful. Only one icon for all area type is OK.

**Comment by stef74** [comment]
I close if we need some work on icon we open a dedicated issue
