### ISSUE TITLE
Enable opening cards in a new tab

### ISSUE THREAD

**Issue by asaunier** [c2corg/v6_ui#393]
As for now the cards use an ``ng-click`` to open the bound document:
https://github.com/c2corg/v6_ui/blob/master/c2corg_ui/static/partials/card_waypoints.html#L1

A drawback of this method is that it is not possible to open the bound document in a new tab.
Using an ``ng-href`` should make it possible. Please note that in editing mode, the card should not open the bound document (the link should be disabled).

**Comment by ginold** [comment]
i'm taking care of that!
