### ISSUE TITLE
Impossible to save an outing if date is manually filled

### ISSUE THREAD

**Issue by loicperrin** [c2corg/v6_ui#401]
I try to create an outing (either from a waypoint or with "Ajouter une sortie" button).
I have filled some flelds but not all the fields. For the start date, I fill the fiel manually "04/06/2016".
When trying to save, I have the following message:
"    date_end is missing
    date_start is missing
    Required
    Required"
If the start date is filled using the button (calendar), it is possible to save.

**Comment by asaunier** [comment]
With change #417 it is now impossible to set a date by hand.

**Comment by loicperrin** [comment]
OK, bug fixed.
