### ISSUE TITLE
Outing creating: difficult to associate a route

### ISSUE THREAD

**Issue by loicperrin** [c2corg/v6_ui#402]
I try to create an outing from a waypoint.
It 's difficult to find the route to associate, because the tool "routes_taken" searches the route in the whole database. It should be better to have a selector that lists the routes asssociated to the waypoint from which the outing is created.

**Comment by ginold** [comment]
actually the "create an outing from a waypoint" shouldn't be available (the card should not appear), if I remember well this option should only be available from the route view page. Am I right, @asaunier ?

**Comment by fjacon** [comment]
In V6 : outing can only be created form route.
For climbing outdoor site, it will be necessary to create associated routes.
now, the question is how do we migrate V5 to V6 ?

**Comment by fjacon** [comment]
MigrationV5 to V6 : a generic route should be created for Climbing site.

**Comment by loicperrin** [comment]
> In V6 : outing can only be created form route.
OK (the outing test n°1 has to be modified).

**Comment by ginold** [comment]
Is this issue still valid?

**Comment by loicperrin** [comment]
> OK (the outing test n°1 has to be modified).

I have modified it. If this instruction "MigrationV5 to V6 : a generic route should be created for Climbing site" is given in another issue, this one can be closed.

**Comment by fjacon** [comment]
Closing.
Topic discussed in https://github.com/c2corg/v6_ui/issues/375
