### ISSUE TITLE
Minor problems on outing creation

### ISSUE THREAD

**Issue by loicperrin** [c2corg/v6_ui#403]
- [x] In the first step, the fields are not aligned (Durée, Longueur totale)
- [x] In the first step, "Parcours partiel" should be a checkbox

(- [x] Step 2: date should be pre-filled with today date )

- [x] Step 2: the field "Commentaires sur l'accès" should be located with other fields related to "Accès"
- [x] Step 2: "Transports publics" should be a checkbox
- [x] Step 3: language should be pre-filled with the currently selected language for the interface
- [x] Step 3 : the default title of the outing does not begin with the name of the main waypoint => all new outings will be named "Versant W" or "Face N"

( - [ ] In the first step, the fields should be pre-filled either from the associated route or from the GPS track (when associated) )
( - [ ] Step 2: the "Glacier" field should not appear if the associate route(s) have no "matériel glacier" )

**Comment by asaunier** [comment]
> Step 2: date should be pre-filled with today date

I am not sure this is a good idea. In v5 outings dates are often incorrectly set because people don't realize that the default date (the current date) is not the good one. If no default date is set, people will have to pay attention to the date of the outing. Please note that the calendar is automatically set to today's date when opened the first time.

> Step 3: language should be pre-filled with the language of the navigator

You mean the currently selected language for the interface I guess.

**Comment by loicperrin** [comment]
> You mean the currently selected language for the interface I guess.

Yes ! (I have modified the issue).

For the pre-filled date, it is to discussed indeed.

**Comment by stef74** [comment]
Please add also 

- [ ] Snow information ("quantité de neige", "qualité de la neige", "altitude de la neige à la montée",...) should not appear in activities for which it is not relevant (climbing, hiking, ...). See the google sheet "Outings" for more details.

- [ ] The table "Enneigement par zones" does not appear in creation form for theses activities but appears when displaying the outing.

**Comment by ginold** [comment]
@stef74, "Enneigement par zones" is a default field for every outing, no matter what activity it has? 
according to this sheet https://docs.google.com/spreadsheets/d/110umbpgS1CUDtzeJ62fNBvn9UBHl_wSbXx5xhFlQTng/edit#gid=792641820 and https://github.com/c2corg/v6_common/blob/master/c2corg_common/fields_outing.py, it is the case.

**Comment by ginold** [comment]
Snow information does not appear for activities it is not relevant: it only appears when you have selected two activities that have uncommon fields, for example for hiking AND snowshoeing selected, snow information will appear.

**Comment by ginold** [comment]
@loicperrin 

> the default title of the outing does not begin with the name of the main waypoint => all new outings will be named "Versant W" or "Face N"

You mean that the default outing title should be "versant W" or "face N" instead of `main_waypoint_title` : `route_title` (assigned only when the first route is associated)?

**Comment by loicperrin** [comment]
> "Enneigement par zones" is a default field for every outing, no matter what activity it has?
according to this sheet

??? In line 36, columns N to X, only 4 activities should display ""Enneigement par zones".

>You mean that the default outing title should be "versant W" or "face N" instead of main_waypoint_title : route_title (assigned only when the first route is associated)? 
No, the default title should be main_waypoint_title : route_title. Now it seems to be OK (when I have created this ticket, the main_waypoint_title was not present).

**Comment by ginold** [comment]
Sorry, I misread. Anyway, it is already like this and enneigement par zones is displayed only if at least one of those 4 activities is selected.

**Comment by asaunier** [comment]
>  In the first step, the fields should be pre-filled either from the associated route or from the GPS track (when associated)

Setting default values of the outing attributes with the attributes of the associated routes is not a minor task. By the way I don't think this task is listed in the specs. @fjacon what do you think?

**Comment by loicperrin** [comment]
See #499

**Comment by asaunier** [comment]
Reopening the issue and marking it as "fixed and ready for testing"

**Comment by asaunier** [comment]
* [ ] There is probably a problem with the styles of associated routes when creating an outing:
![sans titre](https://cloud.githubusercontent.com/assets/1192331/16990494/729f0722-4e98-11e6-8c72-94d01a2374be.png)

**Comment by loicperrin** [comment]
* [ ] Step 3: language should be pre-filled with the currently selected language for the interface
is not fixed: now the default language is always english: it should be the currently selected language for the interface

> There is probably a problem with the styles of associated routes when creating an outing
This problem is only for large screens.

I have not entirely tested "Snow information" display (pb with demo server).

**Comment by asaunier** [comment]
> Step 3: language should be pre-filled with the currently selected language for the interface
is not fixed: now the default language is always english: it should be the currently selected language for the interface

This is not restricted to outings: all doc types are impacted. I have created a dedicated issue at https://github.com/c2corg/v6_ui/issues/510
It's better not to duplicate issue and would recommend to neutralize your report.

**Comment by stef74** [comment]
@loicperrin please test

**Comment by loicperrin** [comment]
There is still a problem of fields alignment in step 1 (left and right alignment) on medium screen (on large screen it is OK).

Other problems are fixed.
![issue403](https://cloud.githubusercontent.com/assets/19718055/17263606/2a845856-55e2-11e6-91e6-b1991b649e99.jpg)

**Comment by stef74** [comment]
@loicperrin @shortoland please test

**Comment by shortoland** [comment]
@stef74 @loicperrin OK for me. Loïc, do you confirm ?

**Comment by loicperrin** [comment]
OK
