### ISSUE TITLE
Problem after saving an outing 

### ISSUE THREAD

**Issue by loicperrin** [c2corg/v6_ui#404]
I try to create an outing. I have filled several fields. When I save it, the following error message displays:
---
Internal Server Error

The server encountered an internal error or misconfiguration and was unable to complete your request.

Please contact the server administrator at [no address given] to inform them of the time this error occurred, and the actions you performed just before this error.

More information about this error may be available in the server error log.
---
The URL displayed is outings/736971/fr, so it seems that the outing has been created, but if I try to display it (copy/paste in URL address), I get the same error message.
This outing is not visible on the topoguide page.

**Comment by ginold** [comment]
does this happen every time you create an outing or is it occasional? If it happens sometimes, please try to write down the steps you make in order to reproduce this bug.

**Comment by loicperrin** [comment]
I have this problem once, and I don't succeed to reproduce it today. 
But if I try to display the outing outings/736971/fr, I have still Error 500. Maybe there is more information on this "wrong" outing in the log files or in database?

**Comment by ginold** [comment]
`Failed to load resource: the server responded with a status of 404 (Not Found)` @tsauerwein looks like you are the best to fix it up!

**Comment by tsauerwein** [comment]
> Failed to load resource: the server responded with a status of 404 (Not Found) @tsauerwein looks like you are the best to fix it up!

When are you getting this error? The API correctly returns the document for this outing: http://c2corgv6-api.demo-camptocamp.com/outings/737037?l=fr

**Comment by asaunier** [comment]
It's probably not an API issue, rather a UI template error. The apache logs of the UI say that

> [Mon Jun 20 12:59:29.912019 2016] [wsgi:error] [pid 28435] [remote 10.27.71.4:576]   File "/var/www/vhosts/c2cassoc_c2corgv6/private/v6_ui/c2corg_ui/templates/outing/view.html", line 138, in render_body
[Mon Jun 20 12:59:29.912025 2016] [wsgi:error] [pid 28435] [remote 10.27.71.4:576]     ${get_document_locale_text(locale, 'weather')}
[Mon Jun 20 12:59:29.912032 2016] [wsgi:error] [pid 28435] [remote 10.27.71.4:576]   File "/var/www/vhosts/c2cassoc_c2corgv6/private/v6_ui/c2corg_ui/templates/helpers/view.html", line 261, in render_get_document_locale_text
[Mon Jun 20 12:59:29.912038 2016] [wsgi:error] [pid 28435] [remote 10.27.71.4:576]     % if condition['level_snow_height_soft'] != '':
[Mon Jun 20 12:59:29.912136 2016] [wsgi:error] [pid 28435] [remote 10.27.71.4:576] KeyError: 'level_snow_height_soft'

**Comment by fjacon** [comment]
@ginold fixed ?

**Comment by ginold** [comment]
probably yes, I remember having worked on this issue, but I can't reproduce it...so probably it's fixed.

**Comment by loicperrin** [comment]
Not reproduced, so probably fixed.
