### ISSUE TITLE
Outing creation: missing fields

### ISSUE THREAD

**Issue by loicperrin** [c2corg/v6_ui#405]
- [x] The field "Frequentation" is missing (cf. line 37 of https://docs.google.com/spreadsheets/d/110umbpgS1CUDtzeJ62fNBvn9UBHl_wSbXx5xhFlQTng/edit#gid=792641820)
- [x] The field "Altitude de déchaussage" is missing (cf. line 30 of https://docs.google.com/spreadsheets/d/110umbpgS1CUDtzeJ62fNBvn9UBHl_wSbXx5xhFlQTng/edit#gid=792641820)

- [x] It seems not possible to associate other members to the outing

- [x] The field "Qualité du document" is present in the creation/modification form, but is not displayed in the saved outing.

**Comment by ginold** [comment]
"Altitude de déchaussage" is available, it is named "Altitude de la neige à la descente".

**Comment by loicperrin** [comment]
When I modify an outing (for example outings/edit/736952/fr), I do not see "Altitude de la neige à la descente" (I have also noticed this problem in creation, but now there seem to be a problem with outing creation on demo).

**Comment by ginold** [comment]
I have just fixed it, now wait until the demo is updated and you are good to test it again.

**Comment by loicperrin** [comment]
I cannot see "Altitude de la neige à la descente" when I create an outing (activity ski).

**Comment by ginold** [comment]
You mean while creating an outing with activity ski, or after creation it does not appear?

**Comment by loicperrin** [comment]
Both ! See:
![issue405e](https://cloud.githubusercontent.com/assets/19718055/16965967/c476f23a-4e02-11e6-8ba8-4054a5f89667.jpg)

See also outings/724495/fr, whereas it is OK in v5.

**Comment by loicperrin** [comment]
For display, see also outings/724495/fr, whereas it is OK in v5.

**Comment by ginold** [comment]
Ok, now i see :) I will have a look.

Next time when you see something unexpected, there may be an error that you can directly copy and write here. You can check it in the browsers console by clicking F12 and going to 'console' in chrome : 
![screenshot from 2016-07-20 11 31 59](https://cloud.githubusercontent.com/assets/7814311/16981998/c55f904c-4e6d-11e6-971d-ac2488f014a6.png)

and in firefox under 'web console' :
![screenshot from 2016-07-20 11 32 34](https://cloud.githubusercontent.com/assets/7814311/16982005/d3aaa218-4e6d-11e6-889f-4fa01aa026a2.png)

**Comment by stef74** [comment]
it's ready for test ?

**Comment by fjacon** [comment]
@ginold does your PR fix the problem ?
has the demo be updated ?

**Comment by ginold** [comment]
I think I already solved this problem but I'm not sure if the demo has been updated since. @asaunier  ?

**Comment by asaunier** [comment]
I have just updated the demo.

**Comment by stef74** [comment]
@loicperrin please test

**Comment by loicperrin** [comment]
> I cannot see "Altitude de la neige à la descente" (altitude de dechaussage) when I create an outing (activity ski) [same pb in edition and display mode]

Not fixed!

![issue405](https://cloud.githubusercontent.com/assets/19718055/17263705/c8dca724-55e2-11e6-9928-8112436b362f.jpg)

**Comment by loicperrin** [comment]
"Altitude de la neige à la descente" (altitude de dechaussage) is OK for other "snow activities".

**Comment by stef74** [comment]
@loicperrin please test

**Comment by loicperrin** [comment]
OK when creating/editing an outing, but still KO when displaying the outing
![issue405-display](https://cloud.githubusercontent.com/assets/19718055/17909629/97a29040-6985-11e6-8331-16091248f38c.jpg)

**Comment by ginold** [comment]
Are you sure? i just created an outing on the demo instance and both values are displayed :
![screenshot from 2016-08-26 15 10 50](https://cloud.githubusercontent.com/assets/7814311/18006322/57d6b830-6b9f-11e6-8a65-8adaa893d5b7.png)

**Comment by loicperrin** [comment]
The field has been displayed in your outing indeed. I have suppressed activity "Raquette" and "Parapente" and now it is no more displayed. It seems that when activity is "ski, surf", the value of the field is suppressed, and then it is not displayed.
You can also see this outing to reproduce the pb: outings/736955

**Comment by ginold** [comment]
indeed this field was saved but not displayed when only skitouring was selected. The fix is coming soon.

**Comment by stef74** [comment]
@loicperrin please test

**Comment by loicperrin** [comment]
OK
