### ISSUE TITLE
Outing creation: problems with dates

### ISSUE THREAD

**Issue by loicperrin** [c2corg/v6_ui#406]
See issue #401 
But there are other problems with dates:
- [x] When I select 04/06/2016 (with calendar tool), the date 03/06/2016 is saved in the outing.
- [x] Then I try to modify this starte date, and replace the date 03/06/2016 by 11/06/2016, but 11/06/2016 is put in start date (that's OK) and 03/06/2016 is saved in end date (that's KO)
- [x] I can select a start date after the end date (the tool should control that end date is after start date)
- [x] New problem with date: it is no more displayed in the outing (I think it was in Alpha1).

**Comment by loicperrin** [comment]
New problem with date: it is no more displayed in the outing (I think it was in Alpha1).

**Comment by shortoland** [comment]
Display is OK.
Pb with end date in case of several days outing: the displayed day is the day before the entered one.

**Comment by stef74** [comment]
@fjacon please fix the lastest point

**Comment by stef74** [comment]
@loicperrin please test

**Comment by loicperrin** [comment]
OK
