### ISSUE TITLE
Problems with outing modifications

### ISSUE THREAD

**Issue by loicperrin** [c2corg/v6_ui#407]
* [x] It is not possible to modify "Conditions d'enneigement par zones": the table is empty and when clicking on "Ajouter une ligne", nothing happens

* [x] When I select a "Transports publics", it is displayed in the outing. But if I modified this outing, it is not selected in the form. Please notice that "Transport publics" have to be replaced by a checkbox (already mentionned in another issue).

(see outings/edit/736972/fr to reproduce this problems)

**Comment by asaunier** [comment]
> In step 4 (Review/Résumé): it seems to be possible to modify the fields Titre, Commentaires personnels and Conditions. In fact only the modifications in the title are saved.

The "review/résumé" should not be tested. It's a temporary page that should be replaced by a real preview page. See https://github.com/c2corg/v6_ui/issues/168

**Comment by loicperrin** [comment]
I have suppressed the bug on "review/résumé", but added another one.

**Comment by asaunier** [comment]
> It is not possible to modify "Conditions d'enneigement par zones": the table is empty and when clicking on "Ajouter une ligne", nothing happens

I have noticed that when opening the editing page of an already existing outing, the JS console complains that:
> angular.js:13642 Error: [ngRepeat:dupes] http://errors.angularjs.org/1.5.6/ngRepeat/dupes?p0=cond%20in%20outing.locales%5B0%5D.conditions_levels&p1=string%3Ae&p2=e

which is probably the reason why the "conditions_levels" table is not displayed correctly.

https://docs.angularjs.org/error/ngRepeat/dupes?p0=cond%20in%20outing.locales%5B0%5D.conditions_levels&p1=string:e&p2=e
says that
> Error: ngRepeat:dupes
Duplicate Key in Repeater
Duplicates in a repeater are not allowed. Use 'track by' expression to specify unique keys. Repeater: cond in outing.locales[0].conditions_levels, Duplicate key: string:e, Duplicate value: e

**Comment by ginold** [comment]
conditions_levels problem is due to the fact that it happens to be hardcoded for empty strings, if it has not been set (required by API). See  https://github.com/c2corg/v6_api/issues/266

**Comment by ginold** [comment]
public transport issue -> see #333

**Comment by ginold** [comment]
> "Transport publics" have to be replaced by a checkbox 

it could be a checkbox, but I will replace it by a selection tool with values yes, no, and nothing because it is more coherent to the design, a single checkbox in the middle of selection tools is not nice.

**Comment by asaunier** [comment]
A checkbox is easier to use than a dropdown and it's no use select "public transportation: no" when creating an outing, you just check it if you came with the PT. Else you ignore the attribute.

In the outings advanced search I have used a checkbox, not a dropdown.

**Comment by loicperrin** [comment]
> A checkbox is easier to use than a dropdown

I agree. In fact a checkbox would be better also for "Parcours Partiel" (and maybe for other fields yes/no...)

**Comment by ginold** [comment]
There is no problem for me to change it to a checkbox instead of a select box, it is just REALLY ugly having one checkbox between 10 select box.

**Comment by ginold** [comment]
Please choose
![screenshot from 2016-06-30 10 15 27](https://cloud.githubusercontent.com/assets/7814311/16481483/ca52172c-3eab-11e6-865e-bf2d626dc6d3.png)

![screenshot from 2016-06-30 10 16 41](https://cloud.githubusercontent.com/assets/7814311/16481484/cb9f9b72-3eab-11e6-9fe6-970061c11db4.png)

**Comment by asaunier** [comment]
It's not that ugly :p and usability is more important than beauty.
You could keep the attribute name on a first line (as for the other attributes) and display the checkbox alone on the following line. See what has been done for the outings advanced search:
![sans titre](https://cloud.githubusercontent.com/assets/1192331/16482758/9f70c4da-3eb1-11e6-97bf-299f3df92d3e.png)

**Comment by loicperrin** [comment]
Outing modification is no more possible: when I display my outing, "Modify" button disappears.
"Modify" button seems to be OK for routes.

**Comment by asaunier** [comment]
* [ ] Concerning the single checkboxes in the outing editing form, would it be possible to align the label and the checkbox to the left instead of centering them as in the following screenshot? It would be more consistent with the other fields.
![sans titre](https://cloud.githubusercontent.com/assets/1192331/16989626/391ab1e8-4e95-11e6-80e6-91a9d056ddb9.png)

**Comment by loicperrin** [comment]
"Modification" button now appears. 
OK for other problems. 
I let this issue open just for checkbox left alignment, as proposed by @asaunier

**Comment by loicperrin** [comment]
OK
