### ISSUE TITLE
Problem with translating an outing

### ISSUE THREAD

**Issue by loicperrin** [c2corg/v6_ui#409]
- [x] From outing outings/edit/736972/en I try to create an english version. If fill some text fields, but when saving, I have the following error message:
    [{'level_place': '', 'level_snow_height_total': <colander.null>, 'level_comment': '', 'level_snow_height_soft': <colander.null>}] is not a string: {'conditions_levels': ''}
    at least one user required
    at least one route required

- [x] If I try to fill the table "Conditions d'enneigement par zones", I have the same message.
- [x] And there is one user and one route associated to this french outing.

**Comment by ginold** [comment]
> at least one user required
at least one route required

sounds like the API hasn't been updated on the demo ? it's an old error.

**Comment by asaunier** [comment]
> sounds like the API hasn't been updated on the demo ?

I think I made sure to update the API of the demo instance on June 8th. Last commit of the API demo instance is 124646d04cd2b19a88e049f98dd13dad771a927c

**Comment by loicperrin** [comment]
Fixed.
