### ISSUE TITLE
Error 400, activities not iterable when creating a Route

### ISSUE THREAD

**Issue by gberaudo** [c2corg/v6_ui#41]
The UI displays and sends a string instead of a collecition: `{activities: "rock_climbing",…}`

**Comment by tsauerwein** [comment]
Could this be a bug in the API?

**Comment by asaunier** [comment]
I guess that the API expects a list of activities but gets a string.

**Comment by ginold** [comment]
is this issue still valid? it's been a while.

**Comment by asaunier** [comment]
A list of activities is actually passed.
