### ISSUE TITLE
Smartphone : problems when creating an outing

### ISSUE THREAD

**Issue by loicperrin** [c2corg/v6_ui#410]
- [x] When creating an outing, the field "qualité du document" is not visible on my screen (too low), so I cannot change it.
- [x] When displaying an outing on a smartphone, the last column in the table "Enneigement par zones" is not redeable. See outings/737005/fr for example.

**Comment by loicperrin** [comment]
Another minor problem with smartphone : the language box is too small (the language is cut when selected).

**Comment by fjacon** [comment]
@ginold Fixed ?

**Comment by ginold** [comment]
not entirely.

**Comment by ginold** [comment]
@loicperrin is the problem with qualite du document still valid? I cannot reproduce the problem, the field is always visible on my phone and in the browsers i tested on.

**Comment by loicperrin** [comment]
The problem with qualite du document is fixed, but not the 2 others (language box and Enneigement par zone).

**Comment by ginold** [comment]
L'enniegement par zones (condition levels) is fixed, maybe you haven't noticed that it is possible to scroll to left and right when on mobile to see the rest of the table (ex http://c2corgv6.demo-camptocamp.com/outings/736699/fr).
Maybe it is not the most comfortable way of doing but I don't know how we could fit such a large table on a small screen otherwise.

**Comment by loicperrin** [comment]
I had not noticed the horizontal scroll indeed. But on my smartphone (Androïd), it does not work very well.
It would be much better to adapt the width of the columns to the width of the screen: in V5 this table is well displayed. See for example this outing: https://www.camptocamp.org/outings/767595/fr/pic-de-l-etendard-versant-ne-voie-normale-a-ski

**Comment by ginold** [comment]
What phone, browser and android version are you using (settings -> about device -> software info) ? On mine it works perfectly well.

V5 is displayed entirely, same as on desktop so it is not adapted to a mobile and you still have to zoom in and pan (at least on my mobile and my desktop's responsive mode).

**Comment by loicperrin** [comment]
Sony XPeria M2 - Androïd 4.4.4 - Chrome
Mathieu has also tested this on galaxy j5, android, and for him, it is not good too.

**Comment by loicperrin** [comment]
As said in previous comment, this horizontal scroll does not work very much.

**Comment by ginold** [comment]
We have just tested on Alex'es really old phone and it works!
are you sure you see a horizontal scrollbar and you swipe from right to left and not left to right? (alex did it the first time and thought it didn't work).
![screenshot from 2016-09-05 12 48 34](https://cloud.githubusercontent.com/assets/7814311/18245709/173769f8-7367-11e6-8f0e-1bf0da67c965.png)

**Comment by asaunier** [comment]
> are you sure you see a horizontal scrollbar and you swipe from right to left and not left to right? (alex did it the first time and thought it didn't work).

It's not possible to move the scrollbar by touching the screen. But it works when touching and moving the table itself.

**Comment by loicperrin** [comment]
> It's not possible to move the scrollbar by touching the screen. But it works when touching and moving the table itself.

Right! I have also noticed this, that's why I thought it does not work. But it is not user friendly:
- who will think to move the table itself (instead of the scrollbar)?
- even when moving the table, it is very difficult to read text. See for example: outings/724495

**Comment by ginold** [comment]
>  But it is not user friendly 

you are completely right, but there is no way of showing the whole table without having to scroll or showing it whole at a time, and both solutions are mediocre.

As from css-tricks:
![](https://cdn.css-tricks.com/wp-content/uploads/2011/04/doublesuck.png)


Possible solutions:

- hide the least important columns: are there columns that are not important and that we could simply not display on the smartphone? maybe `neige fraiche` and `epaisseur totale`?

-  we could try to display the table not from left to right, but as a list up to bottom, see (on a smartphone or resize your window) https://css-tricks.com/examples/ResponsiveTables/responsive.php

**Comment by stef74** [comment]
@loicperrin @shortoland please test

**Comment by loicperrin** [comment]
The table is much easier to read on smartphone now. Thanks!

I have noticed a new little defect:
- [ ] in the outing detail view, the button "Add a comment" (at the bottom of the page) is not visible on smartphone

**Comment by asaunier** [comment]
> in the outing detail view, the button "Add a comment" (at the bottom of the page) is not visible on smartphone

This is not related to this issue (pb in editing form of outings). I have created a dedicated issue: https://github.com/c2corg/v6_ui/issues/868
