### ISSUE TITLE
route creation : display of criteria

### ISSUE THREAD

**Issue by desnoes** [c2corg/v6_ui#411]
**Document**: routes/736969/fr (ski), routes/737010/it (climbing), routes/737012/de (hiking), routes/737013/es (snowshoeing), routes/737014/en (Mountain Bike), routes/737015/fr (Via Ferrata)

Tests done on a PC.
## Multiple activities

When criterion 'Dénivelé des difficultés', 'Hauteur des difficultés' and 'Longueur de l'itinéraire' are not valued, the entire section 'Hauteurs' disappear, nothing is displayed. This bug appears for the following activities: ski, climbing, hiking. Maybe the problem comes from criterion 'Hauteur des difficultés'. In fact, when a route is created with another activity (alpinism) and then i modify the activity (alpinism => ski), criterion 'Hauteur des difficultés'  does not appear and the final display is correct.
- [x] Criteria 'Durée(jours)' is not displayed. When we modify the document, the value of this criteria is lost (checkbox is unchecked). In addition, it is possible to select multiple values.
- [x] Criteria 'Matériel glacier' is not displayed
## criteria for ski
- [x] Missing parameter :  Temps de parcours des difficultés, Qualité du document
- [x] Unexpected : Hauteur des difficultés

> ginold: this property will show up only if you have selected at least one activity that has 'difficulties height', so it may appear for others that don't require it.

Bug: parameter 'Longueur de l'itinéraire' is present while it is not in the list of criteria for search (https://docs.google.com/spreadsheets/d/1LTE1UIjsDTdZauDgR4rKe2UCtXF6LG-ELH53Qwy1nmI/edit#gid=1914256141). I don't understand why it was defined as a parameter for ski activity. To be removed ?

> ginold: this parameter has been added to the search filters.
## criteria for rocher haute montagne
- [x] Missing parameters :  
  - Temps de parcours des difficultés
  - Qualité du document
## criteria for rocher haute montagne
- [x] Missing parameters :  
  - Longueur du tronçon. Utility of this parameter ?
  - Temps de parcours des difficultés
  - Qualité du document
## criteria for ice climbing
- [x] Missing parameters :  
  - Temps de parcours des difficultés
  - Qualité du document
## criteria for hiking
- [x] Unexpected criterion : Hauteur des difficultés

> ginold: it is defined here, that it should show up for hiking as well https://github.com/c2corg/v6_common/blob/master/c2corg_common/fields_route.py . Is it false?
> 
> desnoes: you are right, it is defined in the list of fields. I thougth this was a bug in the spec.
- [x] Missing parameters :  
  - Temps de parcours des difficultés
  - Qualité du document
- [x] Bug: parameters 'Dénivelé des difficultés' and 'Dénivelé de l'approche' are defined but not used in the list of criteria for search (https://docs.google.com/spreadsheets/d/1LTE1UIjsDTdZauDgR4rKe2UCtXF6LG-ELH53Qwy1nmI/edit#gid=1914256141). To be removed ?
## criteria for snowshoeing
- [x] Unexpected criterion : Hauteur des difficultés

> same as above 
- [x] Missing parameters :  
  - Temps de parcours des difficultés
  - Qualité du document
- [x]  Bug: parameters 'Dénivelé des difficultés' and 'Dénivelé de l'approche' are defined but not used in the list of criteria for search (https://docs.google.com/spreadsheets/d/1LTE1UIjsDTdZauDgR4rKe2UCtXF6LG-ELH53Qwy1nmI/edit#gid=1914256141). To be removed ?
## criteria for Mountain bike
- [x]  Unexpected criterion : Hauteur des difficultés

> same as above. 
- [x]  Missing parameters :  
  - Temps de parcours des difficultés
  - Qualité du document
- [x] Bug: parameters 'Dénivelé des difficultés' and 'Dénivelé de l'approche' are defined but not used in the list of criteria for search (https://docs.google.com/spreadsheets/d/1LTE1UIjsDTdZauDgR4rKe2UCtXF6LG-ELH53Qwy1nmI/edit#gid=1914256141). To be removed ?
## criteria for Via Ferrata
- [x] Missing criteria : 'Engagement' and 'Qualité de l'équipement en place'
- [x] Section 'Cotations' is missing.
## criteria for Climbing

TBD

**Comment by ginold** [comment]
> Bug: parameters 'Dénivelé des difficultés' and 'Dénivelé de l'approche' are defined but not used in the list of criteria for search (...)

Both of the parameters have been added in the meantime to the search filters, to I will ignore this one.

**Comment by ginold** [comment]
> Criteria 'Durée(jours)' is not displayed. When we modify the document, the value of this criteria is lost (checkbox is unchecked). In addition, it is possible to select multiple values.

It has been defined as a multiple checkbox in the sheet, see line 44 https://docs.google.com/spreadsheets/d/1p7-RakklDot9gFnciEGox75833zU0ZuC5pRAoLZKziY/edit#gid=1418510514

**Comment by loicperrin** [comment]
> Criteria 'Matériel glacier' is not displayed

Not fixed in Alpha2

**Comment by desnoes** [comment]
Is it ready for test or should i wait ?

**Comment by ginold** [comment]
Not ready yet, maybe tomorrow.

**Comment by desnoes** [comment]
ok, i wait for the green light.

----- Mail original -----
De: "ginold" <notifications@github.com>
À: "c2corg/v6_ui" <v6_ui@noreply.github.com>
Cc: "desnoes" <mathieu.desnoes@free.fr>, "Author" <author@noreply.github.com>
Envoyé: Lundi 25 Juillet 2016 12:24:13
Objet: Re: [c2corg/v6_ui] route creation : display of criteria (#411)



Not ready yet, maybe tomorrow.

**Comment by ginold** [comment]
Apparently we have decided to not implement some of the features of this PR (for ex. not implementing "Temps de parcours des difficultés").
Missing filters have already been added, missing fields have been fixed in another package. 
I only have a few lines of code to add and it's good to be tested again.

**Comment by asaunier** [comment]
I guess this issue is fixed and ready to be tested => I tag it accordingly.

**Comment by stef74** [comment]
@desnoes please test

**Comment by stef74** [comment]
@desnoes @shortoland please test

**Comment by desnoes** [comment]
je m'en occupe à partir de ce soir.

----- Mail original -----
De: "stef74" <notifications@github.com>
À: "c2corg/v6_ui" <v6_ui@noreply.github.com>
Cc: "desnoes" <mathieu.desnoes@free.fr>, "Mention" <mention@noreply.github.com>
Envoyé: Lundi 12 Septembre 2016 13:55:05
Objet: Re: [c2corg/v6_ui] route creation : display of criteria (#411)



@desnoes @shortoland please test

**Comment by desnoes** [comment]
Activity 'Rocher haute montagne': parameter 'longueur de l'itinéraire is missing.

**Comment by stef74** [comment]
need to be fixed

**Comment by asaunier** [comment]
Closing because remaining points have been moved to https://github.com/c2corg/v6_ui/issues/791#issuecomment-258128441
