### ISSUE TITLE
route modification

### ISSUE THREAD

**Issue by desnoes** [c2corg/v6_ui#412]
**All kind of activities**

- Impossible to change the language, 
- the duration value is lost (checkbox is unchecked). 
- When we modify the activity or a criteria in the Configuration section (e.g. orientation), it is impossible to save the document. We can save modifications only if we modify a number or a text with the keyboard.

**Comment by ginold** [comment]
this is normal that you cannot change the language : the document that has been created in one language will remain in this language and cannot be modified. Imagine you wrote your description in french and someone changes it to german? In order to modify the language, you have to click on the right button "more" -> translate into another lang.

**Comment by desnoes** [comment]
I understand your point. This means however that when a route is created, no error is allowed on the selection of the language.

----- Mail original -----
De: "ginold" <notifications@github.com>
À: "c2corg/v6_ui" <v6_ui@noreply.github.com>
Cc: "desnoes" <mathieu.desnoes@free.fr>, "Author" <author@noreply.github.com>
Envoyé: Mardi 14 Juin 2016 12:53:03
Objet: Re: [c2corg/v6_ui] route modification (#412)



this is normal that you cannot change the language : the document that has been created in one language will remain in this language and cannot be modified. Imagine you wrote your description in french and someone changes it to german? In order to modify the language, you have to click on the right button "more" -> translate into another lang.

**Comment by asaunier** [comment]
> This means however that when a route is created, no error is allowed on the selection of the language.

I don't understand what this means. You still have to select a language when creating a language, don't you?

**Comment by desnoes** [comment]
> I don't understand what this means. You still have to select a language when creating a language, don't you?

Yes you have to select a language, but if you made a mistake you cannot correct it. For instance, I create a route in english and this was an error i wanted to select french. In this case, I cannot modify the language, i have to create the route in french and then cancel the route in english. We are facing this kind of problem regularly in V5.

**Comment by tsauerwein** [comment]
For me it would make sense that you can change the language when you create a new document (but not when editing a document).

**Comment by asaunier** [comment]
> In this case, I cannot modify the language, i have to create the route in french and then cancel the route in english. We are facing this kind of problem regularly in V5.

Yep that's the case in v5. But that's for a good reason. With the wiki system you cannot change the old version, you can only create a new one. That would create a huge mess and complications if the "lang" attribute could be changed between 2 versions.

> For me it would make sense that you can change the language when you create a new document (but not when editing a document).

+1

We won't change this behaviour.

**Comment by fjacon** [comment]
I think this ticket can be closed.
