### ISSUE TITLE
Responsive design improvement

### ISSUE THREAD

**Issue by stef74** [c2corg/v6_ui#414]
The full menu appear on too small windows (about 1000 pixel ?). Could you change it to appear arround 1600 pixels.

An other change can be also the 2° colonum creation arround 1400px ... it's too "early" with full menu. 

The title document size is too big with the full menu, in mobile the title si also too big. 

( ginold: solution already suggested
On mobile the snow condition table is unreadable ...
Ex : http://c2corgv6.demo-camptocamp.com/outings/594600/fr the table of snow condition have truncated text due to the two small width available. )

**Comment by ginold** [comment]
Could you please attach a screenshot? i'm not sure what menu you are speaking of (1000-1600px is pretty enormous).

Ok for the snow condition tables :+1:

**Comment by stef74** [comment]
I'm speaking of left menu the pixel is the size of windows

**Comment by stef74** [comment]
![capture](https://cloud.githubusercontent.com/assets/3962997/16039675/768c67b4-322b-11e6-9a0d-6d05922cf5d8.PNG)

**Comment by asaunier** [comment]
By the way the left menu is hidden by the ad banner when the window height is too small. The ad banner should be displayed behind the menu (or not be displayed at all?).

![issue403](https://cloud.githubusercontent.com/assets/19718055/17263606/2a845856-55e2-11e6-91e6-b1991b649e99.jpg)

**Comment by stef74** [comment]
@asaunier can we close ?

**Comment by asaunier** [comment]
The ad banner issue has been fixed.
