### ISSUE TITLE
Text formatting issue

### ISSUE THREAD

**Issue by stef74** [c2corg/v6_ui#420]
http://c2corgv6.demo-camptocamp.com/routes/265151/fr

List are not well formatted ( no return chart on list item)

V5 reference : http://www.camptocamp.org/routes/265151/fr/route-du-soleil-col-du-simplon-realp

**Comment by fjacon** [comment]
You just need to add a line break (done on demo server)
is that OK ?

**Comment by stef74** [comment]
@fjacon yes for new document ... but for old document how to manage (migration ?) For me there too many document impacted

**Comment by asaunier** [comment]
Related to https://github.com/c2corg/v6_ui/issues/131

**Comment by asaunier** [comment]
I close this issue since it's already part of #131
