### ISSUE TITLE
Supression association

### ISSUE THREAD

**Issue by celinestern** [c2corg/v6_ui#421]
Impossible to supress a principal WP definite after, even if they are other WP associate
Only possible with normal WP.

By it's possible to supress every association to normal WP, and to make it orphan.

**Comment by asaunier** [comment]
> Impossible to supress a principal WP definite after

Indeed. The API forbids deassociating the main waypoint. Another waypoint should be made the main waypoint and then the former main waypoint can be deassociated.

> By it's possible to supress every association to normal WP, and to make it orphan.

Indeed. But is it really a problem? It's already like this in v5.

**Comment by celinestern** [comment]
ok for me, you can close
