### ISSUE TITLE
Impossible to change lat/lon on WP

### ISSUE THREAD

**Issue by tsauerwein** [c2corg/v6_ui#423]
Originally reported in https://github.com/c2corg/v6_api/issues/320:

> Changes in lat/lon on WP are not registred. You can save, but it stay the same!

**Comment by stef74** [comment]
@shortoland could you please test

**Comment by shortoland** [comment]
Changes are now taken into account, but it's impossible to display an old version by clicking on it.
Shall I close this ticket and open a new one ?

**Comment by shortoland** [comment]
Changes are now taken into account, but it's not possible to see old versions when clicking them.
As this issue is already reported in #482, I close this ticket.

**Comment by asaunier** [comment]
> it's impossible to display an old version by clicking on it.
Shall I close this ticket and open a new one ?

You mean you get an error page when requesting an old version of a document? If yes I have just noticed it and working on a fix. Creating an issue is useful (by the way it has no connection at all with the current issue so the current issue is not the good place to report the problem :P ).

**Comment by asaunier** [comment]
I have created an issue for the problem you reported: https://github.com/c2corg/v6_ui/issues/519

**Comment by shortoland** [comment]
I thought this issue was mentionned in #492

**Comment by asaunier** [comment]
You mean #482?

#482 is a pull request, not an issue. Pull requests cannot be used to report problem, especially merged (=closed) ones. In addition I don't see where the history crash is mentioned, perhaps we don't speak of the same problem?

**Comment by shortoland** [comment]
OK, you're right. Not sure I am very efficient before catching everything :-/
I made an extrapolation, and thought they were linked.
Anyway, seing old versions is now solved.
