### ISSUE TITLE
Error while saving a change

### ISSUE THREAD

**Issue by tsauerwein** [c2corg/v6_ui#424]
Originally reported in https://github.com/c2corg/v6_api/issues/319

> Impossible to save change in document (outing, routes, etc...) without activate "Courte description des changements" in review, this field is not marked as obligatory (*)

**Comment by asaunier** [comment]
@celinestern Could you give an example of changes that you cannot save without filling "Courte description des changements"? This field is indeed not mandatory and I cannot reproduce the problem (for instance if I save the title of a route, I have no problem saving the document).

**Comment by celinestern** [comment]
Now it's working! 
But before, I could'nt save changes. I had to write something in "Courte description" to save. Otherwise I had the "Interdiction sign".

**Comment by stef74** [comment]
Please test

**Comment by celinestern** [comment]
it look ok for me now. Problem didn't exist anymore

**Comment by celinestern** [comment]
ok you can close
