### ISSUE TITLE
Outing creation from route page

### ISSUE THREAD

**Issue by tsauerwein** [c2corg/v6_ui#425]
Originally reported in c2corg/v6_api#318

> Impossible to create a new outing from a route page. It only works from the "accueil-topoguide" page.

**Comment by asaunier** [comment]
@celinestern Could you give more precisions about the actions you do when creating an outing from a route page? I have just tried to do so and had no problem if all the required fields are provided. Do you get an error message?

**Comment by celinestern** [comment]
When I try "Pas encore de sortie sur cet itinéraire, Add a new one to this document", I got this error message:

oops

La page que vous demandez n'existe pas ou est cassée.

/routes/736969/'http:/c2corgv6.demo-camptocamp.com/outings/add' + '

Retourner à la page précédente ou essayez les pages suivantes

**Comment by celinestern** [comment]
But if you still have a outing to an route, you can add an second outing without problems

**Comment by stef74** [comment]
@shortoland could you please test

**Comment by shortoland** [comment]
OK for me, I close

**Comment by celinestern** [comment]
OK for me too, now it work. You can close.
