### ISSUE TITLE
Size of card

### ISSUE THREAD

**Issue by stef74** [c2corg/v6_ui#427]
Globally card are too big, especaly on card with no many information. Some field missing in card?

Adpat card size with number of card information ( not necessary dynamic size, WP card need to be more small than route card) . You can also probably add one more column in desktop for WP card.

**Comment by stef74** [comment]
ex of complex doc : http://c2corgv6.demo-camptocamp.com/routes/265151/fr

**Comment by stef74** [comment]
Please waiting adding content of card #398 before changing anything

**Comment by asaunier** [comment]
* [ ] In the advanced search pages, when there are only a few results, cards are unexpectedly stetched to fit the whole section height instead of keeping their normal height:
![sans titre](https://cloud.githubusercontent.com/assets/1192331/18950217/24be3ef4-863f-11e6-9c46-965b9ba02b17.png)

**Comment by asaunier** [comment]
* [ ] Is it normal that all cards in the same "row" have the same size, whatever their content?
![sans titre2](https://cloud.githubusercontent.com/assets/1192331/18955065/17252408-8656-11e6-9fb2-40e8fa410cdb.jpg)

* [ ] By the way the left image is bigger in the card (225.75x337.95 !) than its actual size (167x250):
http://c2corgv6-images.demo-camptocamp.com/active/1474374902_2051852365MI.jpg

**Comment by ginold** [comment]
>  Is it normal that all cards in the same "row" have the same size, whatever their content?
i guess so. It's the flex property and i'm thinking about going back to columns because it's not how flex-box is supposed to work, apparently.
I'll have a look.

**Comment by ginold** [comment]
How can a Medium Image be 167x250.... :camera:

**Comment by asaunier** [comment]
It seems that all points of this issue have been addressed. Closing.
