### ISSUE TITLE
Hide or extend size map

### ISSUE THREAD

**Issue by stef74** [c2corg/v6_ui#428]
On mobile fixed size map for search is too limiting number of result card. Please possibility to hide or full windows (as altimax maquette).

Same possibility can be offer in desktop mode.

Same approach for map in document (offer possibility to hide or show in full windows size)

**Comment by asaunier** [comment]
I guess that we need to keep the map extent (as much as possible) when resizing the map. Else it will impact the search results since the map extent is used as geom filter.

**Comment by tsauerwein** [comment]
> I guess that we need to keep the map extent (as much as possible) when resizing the map. Else it will impact the search results since the map extent is used as geom filter.

When you hide the map, no problem(?).
When you make the map *full extent*, the extent will change. But that is ok.

**Comment by asaunier** [comment]
> When you hide the map, no problem(?).
When you make the map full extent, the extent will change. But that is ok.

I know. For the advanced search, this feature is not trivial!

**Comment by asaunier** [comment]
Perhaps the FullScreen control from OpenLayers coud be used? http://openlayers.org/en/latest/examples/full-screen.html

**Comment by tsauerwein** [comment]
> Perhaps the FullScreen control from OpenLayers coud be used?

Yes, for example like here:
https://github.com/camptocamp/agridea_geoacorda/blob/212e90ccaac8193703386e7079179c8862b8351a/jsapi/src/mapcontrols.js#L220-L249
https://github.com/camptocamp/agridea_geoacorda/blob/master/jsapi/src/maincontroller.js

**Comment by stef74** [comment]
In mobile the map in advanced search limit the number of resultat (only 1 card) ... and scrolling si very complex (limited area to scroll).

In landscape mode is completely unusable !!!!
![img_0760](https://cloud.githubusercontent.com/assets/3962997/19639283/1e7e1530-99d8-11e6-9b5e-20e23264f3ea.PNG)
![img_0763](https://cloud.githubusercontent.com/assets/3962997/19639284/1e7f56b6-99d8-11e6-8751-35fb64e6db9a.PNG)

**Comment by ginold** [comment]
yeah this is embarrassing and even more difficult because iphone on safari has it's own bottom bar that cannot be hidden. Maybe we could add a switch to hide/show the map and display only the cards by default?

**Comment by asaunier** [comment]
@stef74 it has already been reported at https://github.com/c2corg/v6_ui/issues/657
Please use the latter issue instead.

**Comment by stef74** [comment]
See News issue
