### ISSUE TITLE
Outing : Date (Calendar)

### ISSUE THREAD

**Issue by desnoes** [c2corg/v6_ui#429]
- It is possible to choose a date in the futur => need an additional check to avoid this possibility

- Add some help for entering manually the date. For instance, i want to create an outing dating from 01/11/2010, it is much faster to do it manually than using the calendar.

**Comment by ginold** [comment]
most likely we should make manual entering of date impossible (there are a few reasons for that and it saves a lot of checking). Selection only through calendar should be possible. 
A lot of services work so: booking.com, facebook...

**Comment by desnoes** [comment]
In this case, it should not be possible to type an entry in the box on the left of the calendar picto. This would avoid confusion.

----- Mail original -----
De: "ginold" <notifications@github.com>
À: "c2corg/v6_ui" <v6_ui@noreply.github.com>
Cc: "desnoes" <mathieu.desnoes@free.fr>, "Author" <author@noreply.github.com>
Envoyé: Jeudi 16 Juin 2016 09:12:40
Objet: Re: [c2corg/v6_ui] Outing : Date (Calendar) (#429)



most likely we should make manual entering of date impossible (there are a few reasons for that and it saves a lot of checking). Selection only through calendar should be possible. 
A lot of services work so: booking.com, facebook...

**Comment by ginold** [comment]
Yep, it is done so in the upcoming package.

**Comment by desnoes** [comment]
not possible to selecte a date in the futur => ok
no possible to enter a date manually => ok
