### ISSUE TITLE
Display Outing / route / Waypoints

### ISSUE THREAD

**Issue by loicperrin** [c2corg/v6_ui#433]
- [x] The table "Enneigement par zone" is displayed even if it is empty and even in activity for which it is not relevant (see outings/737006/fr or outings/737036/fr).
- [x] Smartphone : All blocs should be displayed without having to clic on "Détails", "Association", ...
See wireframes : https://projects.invisionapp.com/share/MK53LLARJ#/screens/108058201. It should be better to open each bloc by default.
- [x] Smartphone : On the route page, the associated outings are visible only in a small bloc in which it is difficult to scroll.

**Comment by desnoes** [comment]
> toto

**Comment by desnoes** [comment]
## OUTINGS

- [ ] sections (Itinéraire emprunté, Commentaires sur le refuge...) should not be hidden when the document is opened. See http://c2corgv6.demo-camptocamp.com/outings/737032/fr.

- [ ] Associated WP should be classified and grouped accoridng to their type (parking, summit,...)

- [ ] Display on the map the pictos of the associated WP with the possibility to open this WP by clicking on the picto (cf. V5)

- [ ] List of participants: increase spacing between names

- [ ] Title: reduce the font size. For instance in the table for snow conditions, titles are written in 2 lines because the font size is too large (ex: http://c2corgv6.demo-camptocamp.com/outings/736972/fr)

- [ ] The link with weather forecast is missing

- [ ] Cotations should be displayed (at the top just under the title of the outing)

**Comment by stef74** [comment]
- [ ] In information block remove activity "name" and replace by pinto

**Comment by stef74** [comment]
## ROUTE

- [ ] place abstract in dedicated block

**Comment by stef74** [comment]
## waypoints

- [ ] please

 show the waypoints 'name' not 'point de passage' on the title of WP.

**Comment by asaunier** [comment]
> Unit: no space between the altitude and 'm': write '545m' instead of '545 m'

There is a space between the units, at least in french:
https://fr.wikipedia.org/wiki/Wikip%C3%A9dia:Conventions_typographiques#Unit.C3.A9s_de_mesure
> Les symboles d’unités de mesure ne comportent pas de point abréviatif, sont habituellement écrits en minuscules et sont séparés du nombre par une espace insécable.

> The link with weather forecast is missing

What weather forecast? Where is this point described?
What about routes? It's far more useful to have a weather forecast for routes document then for outings (since the latter can be outdated and not matching the weather forecast).

> Cotations should be displayed (at the top just under the title of the outing)

What do you mean? Like a part of the title (as the date for instance)? Is it really a that important info to put in the title section?

> please show the waypoints 'name' not 'point de passage' on the title of WP.

What do you mean? What is the "waypoints 'name'"?

**Comment by desnoes** [comment]
> There is a space between the units, at least in french in V5

The rule of 'no spacing' was applied to avoid edition problem (figure on the right side of a line and the unit of the left side of the following line). At least an unbreakable space should be inserted between the figure and the unit.

> What weather forecast? Where is this point described? What about routes? It's far more useful to have a weather forecast for routes document then for outings (since the latter can be outdated and not matching the weather forecast).

You are right, this is for route, i mixed up. In V5, the weather forecast is a field with links toward weather forecast web sites. Maybe it was not considered for V6.

**Comment by stef74** [comment]
- [ ] In mobile remove topic title in information block (toot many space used in portait).
![capture](https://cloud.githubusercontent.com/assets/3962997/16225570/93f6174c-37a7-11e6-85d9-33aeb80679ad.PNG)

**Comment by stef74** [comment]
example : 
http://imgur.com/BlGUeJU
http://imgur.com/OIYfi6z

**Comment by asaunier** [comment]
> example : 
before : http://imgur.com/BlGUeJU
after : http://imgur.com/OIYfi6z

From my perspective the "before" is less confusing than the "after". Is it that obvious that the last section contains maps and the section before contains ratings?

**Comment by loicperrin** [comment]
> From my perspective the "before" is less confusing than the "after". Is it that obvious that the last section contains maps and the section before contains ratings?
The title are useless, except maybe for the last 2 sections (they could be added just before the line).

> For instance why do we have an orientation together with regions??
It could be separated indeed.

**Comment by desnoes** [comment]
> From my perspective the "before" is less confusing than the "after". Is it that obvious that the last section contains maps and the section before contains ratings?

No confusion for me, but maybe  we should ask the question to a beginner .

**Comment by stef74** [comment]
The goal is to optimize the number  of information visible in mobile ( and
only in
Mobile) and avoid scrolling for primary informations

Le lundi 27 juin 2016, desnoes <notifications@github.com> a écrit :

> From my perspective the "before" is less confusing than the "after". Is it
> that obvious that the last section contains maps and the section before
> contains ratings?
>
> No confusion for me, but maybe we should ask the question to a beginner .
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/c2corg/v6_ui/issues/433#issuecomment-228659818>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/ADx4dRvBzW9dadAE6vv6K1GVOJnt7LX0ks5qP2WZgaJpZM4I31R8>
> .
>


-- 
Sent from Gmail Mobile

**Comment by asaunier** [comment]
Perhaps there is less scrolling required but beginners will get lost if there are not enough labels.

**Comment by stef74** [comment]
The label of field allrealy exist, is only the category.

The best way for this topic is probably do an A/B testing in beta with more
people than V6 team.



2016-06-27 9:37 GMT+02:00 Alex Saunier <notifications@github.com>:

**Comment by ginold** [comment]
@desnoes 

> Associated outings: write the number of pictures in the card corresponding to an outing

what do you mean by number of pictures?

**Comment by desnoes** [comment]
I meant how much pictures are associated to an outing. This is an very useful indicator to decide whether to clic or not on an outing card to view some pictures of a route.

----- Mail original -----
De: "ginold" <notifications@github.com>
À: "c2corg/v6_ui" <v6_ui@noreply.github.com>
Cc: "desnoes" <mathieu.desnoes@free.fr>, "Mention" <mention@noreply.github.com>
Envoyé: Mardi 5 Juillet 2016 11:11:45
Objet: Re: [c2corg/v6_ui] Display Outing / route / Waypoints (#433)



@desnoes 



Associated outings: write the number of pictures in the card corresponding to an outing 

what do you mean by number of pictures?

**Comment by loicperrin** [comment]
Why this issue has been closed? It seems that some problems are not fixed yet.

**Comment by stef74** [comment]
@loicperrin could identify remaining problem ?

**Comment by loicperrin** [comment]
I don't remember precisely which problems I had identified, but at least it seems that unchecked problems are not solved. For instance, this one:

>  Cotations should be displayed (at the top just under the title of the outing)

**Comment by asaunier** [comment]
> Cotations should be displayed (at the top just under the title of the outing)

That doesn't make sense! The ratings are shown in the associated route cards. Period.

**Comment by loicperrin** [comment]
> That doesn't make sense! The ratings are shown in the associated route cards

Yes, you are right. I don't know why this has been reported. @desnoes could you verify if some unchecked problems are still relevant?

**Comment by stef74** [comment]
@shortoland could you check is unchecked box are still relevant.

**Comment by shortoland** [comment]
Here are the unchecked boxes I have finally checked:

- WP associated to the route should be displayed on the map. See #362

- Display on the map the pictos of the associated WP with the possibility to open this WP by clicking on the picto (cf. V5)

I don't understand what represent the following requests:

- Associated outings: write the number of pictures in the card corresponding to an outing

- place abstract in dedicated block

I am not sure the following requests are still relevant:

- Cotations should be displayed (at the top just under the title of the outing)

**Comment by asaunier** [comment]
> I am not sure the following requests are still relevant:
Cotations should be displayed (at the top just under the title of the outing)

It's not. See https://github.com/c2corg/v6_ui/issues/433#issuecomment-254629596

**Comment by asaunier** [comment]
* [ ] SEO links of associated documents are displayed whereas they should remain hidden (only used so that search engines may browse among associated documents even though not supporting the associated document cards). We have the problem for all documents with associated cards.

Example with an outing: http://c2corgv6.demo-camptocamp.com/routes/139437/fr/sapey-pointe-de-dran-l-archetype
![sans titre](https://cloud.githubusercontent.com/assets/1192331/19534329/a47556fa-9643-11e6-88b3-ccf924a1eabd.png)

**Comment by dkocich** [comment]
@asaunier 
> SEO links of associated documents are displayed

I am sorry, my mistake from today afternoon - I will fix it now, it should be just one line.

**Comment by loicperrin** [comment]
> Associated outings: write the number of pictures in the card corresponding to an outing

It is still relevant (this functionality exists in V5), but if I remember well, this can cause performance problems.

> place abstract in dedicated block

This probably means that abstract in route description (V5) should be imported in abstract field (V6). For me it is OK.

**Comment by stef74** [comment]
So they are not major point ... I push ni next version

**Comment by shortoland** [comment]
@stef74 Should we close this ticket ?

**Comment by stef74** [comment]
If no action still needed ... yes :-)

2016-10-24 18:11 GMT+02:00 shortoland <notifications@github.com>:
