### ISSUE TITLE
Outing creation : snow information should not appear in some activities

### ISSUE THREAD

**Issue by loicperrin** [c2corg/v6_ui#434]
Snow information ("quantité de neige", "qualité de la neige", "altitude de la neige à la montée",...) should not appear in activities for which it is not relevant (climbing, hiking, ...). See the google sheet "Outings" for more details.
The table "Enneigement par zones" does not appear in creation form for theses activities but appears when displaying the outing.

**Comment by stef74** [comment]
includes in #403
