### ISSUE TITLE
Organize code by components

### ISSUE THREAD

**Issue by gberaudo** [c2corg/v6_ui#44]
Currently there is one directory for all less files, one for all js, one for all html partials.
The idea would be to group files by component.

Each component folder would contain the less, js and html for the component.
Examples of projects using components:
- https://github.com/geoadmin/mf-geoadmin3/tree/master/src
- https://github.com/Geoportail-Luxembourg/geoportailv3/tree/master/geoportailv3/static

**Comment by asaunier** [comment]
Is this issue still valid?
