### ISSUE TITLE
Problems with advanced search of waypoints

### ISSUE THREAD

**Issue by loicperrin** [c2corg/v6_ui#440]
When I modify the waypoints selection by choosing "Type" or "Altitude", it is OK the first times. But after some trials (> 3-4, but it is not fixed), the field "Type" and "Altitude" cannot be modified anymore. It is always OK for the "Titre" field.

**Comment by fbunoz** [comment]
I observe this bug if I open and close "More filter", but  it works if I don't touch "More filter".

**Comment by loicperrin** [comment]
On desktop I am almost sure that I have not opened "More filter" when observing this bug.
I have also seen it on smartphone, maybe due to accidental click on "More filter".

**Comment by asaunier** [comment]
I cannot reproduce the problem either with Chrome or Firefox: I can play with the elevation or types filters as long as I want, whether the "more filters" section is open or not.

**Comment by loicperrin** [comment]
Now I cannot reproduce this problem (Firefox on Desktop  and Chrome on Smartphone). Strange...

**Comment by asaunier** [comment]
Please reopen the issue if it can be reproduced. I have tested again on the demo and noticed no problem.
