### ISSUE TITLE
Document organisation

### ISSUE THREAD

**Issue by stef74** [c2corg/v6_ui#449]
Document organization are not consistent with wiframe validated.

Route :
1. Titre
2. abstract (not in wireframe)
3. Key information (same as card)
4. Map
5. Other information
6. WP associated 
7. descriptions
8. outing associated
9. images
10. other... 

Currently abstract is managed in description bloc ... please isolated it.

Outings :
1. Title
2. partipant
3. route associated 
4. map
5. condition (list fied)
6. condition (text field)
7. image
8. personnal comment

You can also review WP doc (use same structure as route).

The desktop mode is not validated in wiframe please use this one :
- route : https://docs.google.com/drawings/d/1t3uL9OLoDR0QkG9SRrXpaxN_ypyX3xK-Zoy46Clk3XY/edit
- outing : https://docs.google.com/drawings/d/1MtTXpiwNU2kWC6sEs5_1YIRhntGy5Q-SnTyP_NC6rlg/edit

For map we are no sure is better in left column (square format) or in right column (left format) could you do a test on a complex document a send us a screenshoot.

**reference** : 

_https://projects.invisionapp.com/share/MK53LLARJ#/screens_

_Some typical document_  

Sommet "classique" : http://c2corgv6.demo-camptocamp.com/waypoints/39663/fr
Sommet "de qualité" : http://c2corgv6.demo-camptocamp.com/waypoints/37355/fr
sommet "complexe" http://c2corgv6.demo-camptocamp.com/waypoints/107049/fr
Sommet  "complexe" : http://c2corgv6.demo-camptocamp.com/waypoints/199108/fr

itinéraire "complexe/de qualité" : http://c2corgv6.demo-camptocamp.com/routes/53874/fr
itinéraire "complexe/de qualité" :  http://c2corgv6.demo-camptocamp.com/routes/55698/fr
itinéraire "complexe : raid" : http://c2corgv6.demo-camptocamp.com/routes/265151/fr
Itinéraire "standard" : http://c2corgv6.demo-camptocamp.com/routes/45338/fr
Itinéraire "ébauche" : http://c2corgv6.demo-camptocamp.com/routes/275009/fr

sortie "complexe/de qualité" : http://c2corgv6.demo-camptocamp.com/outings/594600/fr
sorties "standard" : http://c2corgv6.demo-camptocamp.com/outings/675860/fr
sortie "basique" : http://c2corgv6.demo-camptocamp.com/outings/667986/fr

site d'escalade "de qualité" : http://c2corgv6.demo-camptocamp.com/waypoints/658110/fr
site d'escalade "basique" : http://c2corgv6.demo-camptocamp.com/waypoints/576282/fr

accès "complexe" : http://c2corgv6.demo-camptocamp.com/waypoints/104458/fr
accès "basique" : http://c2corgv6.demo-camptocamp.com/waypoints/675538/fr
## Synthesis
- [ ] Review Outing organization in desktop and mobile
- [ ] Review Route organization in desktop and mobile
- [ ] Review WP organization in desktop and mobile
- [ ] Order Associated WP by type

**Comment by asaunier** [comment]
> For map we are no sure is better in left column (square format) or in right column (left format)

Aren't you afraid that in the left column the map will be way too small?

**Comment by stef74** [comment]
Probably ... But in same case is not a problem. The best approach is test
...

Le mardi 21 juin 2016, Alex Saunier <notifications@github.com> a écrit :

> For map we are no sure is better in left column (square format) or in
> right column (left format)
>
> Aren't you afraid that in the left column the map will be way too small?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/c2corg/v6_ui/issues/449#issuecomment-227366342>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/ADx4dRLGw6TCq1ic7J9fz5sAKFK1sB5dks5qN5gGgaJpZM4I6GE3>
> .
>


-- 
Sent from Gmail Mobile

**Comment by ginold** [comment]
@stef74, What exactly is abstract?

**Comment by asaunier** [comment]
@ginold "abstract" is actually the "summary" attribute available in the document model https://github.com/c2corg/v6_api/blob/master/c2corg_api/models/document.py#L228

**Comment by fjacon** [comment]
It seems to me that it will be necessary to re-work the wireframes and the design as they are not fully validated.

Our suggestion is first to finish the development of all functions for beta version, and then to have a phase of design adjustment. This phase is to be considered as extra work. It should also be added to the planning.

I think this needs to be discussed.

**Comment by asaunier** [comment]
* [ ] By the way the info about the licence of the document is shown nowhere.

**Comment by stef74** [comment]
@fjacon the license problem probably need a dedicated issue (this point is need for go live).

**Comment by asaunier** [comment]
In addition there are many attributes whose positioning or grouping is not that relevant.

For example:
* [ ] in outings, it would make sense to group the "avalanche signs" (selected in a dropdown and placed in the "information" block in the detail view) and the text field "avalanche_infos".
* [ ] in climbing sites, ratings etc. could be more relevantly grouped in the information block (there's an issue, I don't find it)

**Comment by stef74** [comment]
see #1196
