### ISSUE TITLE
Images base URL cannot be hard-coded in the JS files

### ISSUE THREAD

**Issue by asaunier** [c2corg/v6_ui#459]
See https://github.com/c2corg/v6_ui/blob/master/c2corg_ui/static/js/constants.js#L40

Because it is then not possible to adapt the URL value depending on the instance that runs the app.

As for ``apiUrl`` a module value must be created and injected in the JS controllers.
https://github.com/c2corg/v6_ui/blob/master/c2corg_ui/templates/base.html#L143

**Comment by arnaud-morvan** [comment]
This would be done when #455 is merged
