### ISSUE TITLE
Menu on discourse forum

### ISSUE THREAD

**Issue by ginold** [c2corg/v6_ui#461]
I have created 2 different styles for the menu on discourse forum page.
One with menu on the top, like on ubuntu.discrouse :
http://c2corgv6-discourse.demo-camptocamp.com/?preview-style=1e6de3bd-3b54-41f3-966c-b9b1c93d4648

And the second which is more c2corg.v6-like, but I stopped going further because I dont' know how to import CSS classes and SVG icons into discourse, so any glitches are normal.
http://c2corgv6-discourse.demo-camptocamp.com/?preview-style=7d20cade-645c-46d8-8956-de59416683ef

I would stick to the first one, it is much more easily maintainable.
BTW how to import generated links if I don't want to hardcode them? like the URLs of the links in the menus with request.static_url....

**Comment by asaunier** [comment]
Both are cool! :)

> One with menu on the top, like on ubuntu.discrouse

http://discourse.ubuntu.com/ I presume :)

The first one is a bit simpler and probably more consistent with the usual discourse layout. Could we avoid relying on the horizontal scrollbar when reducing the screen width?

The second one is more consistent with the UI layout. Probably a bit more complex to implement. There are weird things as for now when reducing the screen width.

The big advantage of the second layout it the possibility to have more "menu content" such as the ad banner and the footer links.

**Comment by ginold** [comment]
Sure, both have pros and cons. I would prefer that we choose one and stick to it instead of spending unnecessary time on working on a version that we will not take.

**Comment by fjacon** [comment]
@stef74 : To be discussed with the association

**Comment by asaunier** [comment]
Shouldn't this issue "moved" to https://github.com/c2corg/v6_forum/issues?

**Comment by fjacon** [comment]
yes, please do it

**Comment by asaunier** [comment]
OK this issue is replaced by https://github.com/c2corg/v6_forum/issues/41

**Comment by asaunier** [comment]
> yes, please do it

Done. But the alpha2 tag is missing in the forum repo.
