### ISSUE TITLE
Ad banner size

### ISSUE THREAD

**Issue by asaunier** [c2corg/v6_ui#462]
The size of the ad banner currently shown in the demo is 240x135px, which matches no standard banner size.

The most adapted format seems to be the "1/2 skyscraper" which is 160x320px.
See http://blog.kinoa.com/wp-content/uploads/2013/06/format_publicite_internet_netoides1.jpg

**Comment by ginold** [comment]
It would surely be moment to choose one and adapt the menu accordingly, especially when I'm working on the discourse menu.

**Comment by asaunier** [comment]
The chosen format is the "1/2 skyscraper" which is 160x320px.
See http://blog.kinoa.com/wp-content/uploads/2013/06/format_publicite_internet_netoides1.jpg
