### ISSUE TITLE
Special characters are not displayed correctly in feature label

### ISSUE THREAD

**Issue by tsauerwein** [c2corg/v6_ui#470]
For example:
http://c2corgv6.demo-camptocamp.com/waypoints/736949/fr

The title is 'Test site escalade avec "orientations"', the label for the feature on the map is displayed with '"Test site escalade avec &#_34;orientations&#_34;"'.

**Comment by arnaud-morvan** [comment]
This is due to template engine which apply html_entities by default. It should be solved by adding "| n" to all string ouputs in javascript blocks, exemple : 
```
title: "${title | n}"
```

**Comment by asaunier** [comment]
Thanks for the tips!

I have already tried ``title: "${title | n}"`` but then the JSON is incorrect like this
```
"title": "Some title with unescaped "quotes""
```
=> the embedded quotes must be escaped. With
```
"title": "${dumps(locale['title']) | n}",
```
the result is also incorrect:
```
"title": ""Test site escalade avec \"orientations\"""
```

**Comment by arnaud-morvan** [comment]
When using dumps you do not have to put enclosing quotes as dumps already enclose with quotes

**Comment by asaunier** [comment]
Of course! I must be a little overloaded and not thinking correctly :P 
Thanks for your precious help :)
