### ISSUE TITLE
Images slideshow defaults

### ISSUE THREAD

**Issue by arnaud-morvan** [c2corg/v6_ui#478]
* [x] activities and categories values and other metadatas (aperture, shutter speed etc) are lost after reloading the page. They appear first in the template, but on a reload they are lost.

**Comment by asaunier** [comment]
* [ ] By the way, some images have no EXIF info (for instance a drawing). The info section in the images viewer display "undefined" for such data => do not display the info at all if not available.

**Comment by asaunier** [comment]
* [ ] As for now the original images used in the thumbnails bar (ie. potentially several MB files) => rather use small (resized) images

**Comment by fjacon** [comment]
We will use image document page where we will have associated document. And we get a permalink.

**Comment by asaunier** [comment]
Is there still work to do about this issue?

**Comment by ginold** [comment]
>  Georef data (in the EXIF or provided via the geoloc tool) are not displayed anywhere... we need a map somewhere...

is not done. The map is available in the detailed-view and i think we probably don't want any map on the slide itself, or do we? 

And if the image is geolocated already, i don't think it will be recognized by the ui/api. At least I have never worked with a geolocated image through EXIF, beacuse I have not had any example image  :P

**Comment by asaunier** [comment]
It's OK if the map is only shown in the image detail view page.

> At least I have never worked with a geolocated image through EXIF, beacuse I have not had any example image

Here is an example of image with embedded coordinates:
http://www.camptocamp.org/images/466723/fr/tete-tsernou-et-tete-a-pierre-grept-depuis-la-pointe-n
It's an image of mine so I can provide you the original file if needed. Let me know.

**Comment by asaunier** [comment]
Closing this issue because the remaining part (coords in EXIF) is not really related to the slideshow and has been moved to a dedicated issue: https://github.com/c2corg/v6_ui/issues/737
