### ISSUE TITLE
Filter on quality on equipment is not working

### ISSUE THREAD

**Issue by HSERGERAERT** [c2corg/v6_ui#492]
Selection of actitivity "climbing".
Filters are active.
Selection of "quality of equipment" with a ranking P1-P1+ => no result. 
Any active selection on "quality of equipment" makes a wrong result => no selection.
Result is false.

If Free climbing grade is active, same result, any selection will provide "no selection".

Tests faits avec Google Chrome Version 51.0.2704.103 m

**Comment by asaunier** [comment]
Rather an API issue: when selecting "quality of equipment" with a rating P1-P1+ a query to the API is made with params ``act=rock_climbing&prat=P1%2CP1%2B`` which matches the ``prat`` filter of the API: https://github.com/c2corg/v6_api/blob/master/c2corg_api/search/mappings/route_mapping.py#L75-L77

**Comment by asaunier** [comment]
The Elastic Search index in the demo had not been updated => the search engine had no data when applying filters.
I have recreated the index on the demo and this use case (as well as others, provided by email) seem to work now.

**Comment by HSERGERAERT** [comment]
New tests made after correction, tests are successful. I close the ticket.
