### ISSUE TITLE
Outing creation: problem to associate other members

### ISSUE THREAD

**Issue by loicperrin** [c2corg/v6_ui#493]
* [ ] When creating an outing, the tool to associate other members does not find some members: it's OK for "Bruno Besson", "Frédéric Bunoz", but it does not find "LaurentB2", "Pierre P",.... And there is no more "Plus de résultats" button to see more results.
* [ ] ~~When associated, the login of the member is displayed instead of his name (for me: loicperrin, instead of "Loïc Perrin").~~ Moved to https://github.com/c2corg/v6_ui/issues/528

**Comment by ginold** [comment]
The first point is rather an searching/indexing issue, @tsauerwein or @gberaudo would be better for solving it.

**Comment by tsauerwein** [comment]
@asaunier, you might want to add the 2nd point to https://github.com/c2corg/v6_ui/issues/528.

**Comment by asaunier** [comment]
> @asaunier, you might want to add the 2nd point to #528.

Thanks, done.

**Comment by stef74** [comment]
@loicperrin please test

**Comment by loicperrin** [comment]
OK
