### ISSUE TITLE
Crash when comparing two versions of a route with no geometry at all

### ISSUE THREAD

**Issue by shortoland** [c2corg/v6_ui#508]
I have created the folowing route: 
http://c2corgv6.demo-camptocamp.com/routes/736979/fr

After making changes and saving different versions, I try to compare two of them and get 2 issues:
http://c2corgv6.demo-camptocamp.com/routes/history/736979/fr

- First I have a pb with checkbox which are duplicated:
![image1](https://cloud.githubusercontent.com/assets/20488365/16996226/a32a5e42-4eb0-11e6-9045-d05f55b74c07.png)

- Then when clicking to get the result, I have the following error message:

Internal Server Error

The server encountered an internal error or misconfiguration and was unable to complete your request.

Please contact the server administrator at [no address given] to inform them of the time this error occurred, and the actions you performed just before this error.

More information about this error may be available in the server error log.

**Comment by asaunier** [comment]
> First I have a pb with checkbox which are duplicated:

This is not an error. You have 2 checkboxes for the intermediate version to be able to choose if the selected version should be the left version to compare, or the right one.

This already works like this in v5: http://www.camptocamp.org/routes/history/54092/fr
or in wikipedia: https://fr.wikipedia.org/w/index.php?title=Dassault_Mirage_III&action=history

> Then when clicking to get the result, I have the following error message:

Indeed. Here is the error message found in the logs:

> [Wed Jul 20 19:35:11.761438 2016] [wsgi:error] [pid 6423] [remote 10.27.71.4:1600]   File "/var/www/vhosts/c2cassoc_c2corgv6/private/v6_ui/c2corg_ui/views/route.py", line 73, in diff
[Wed Jul 20 19:35:11.761479 2016] [wsgi:error] [pid 6423] [remote 10.27.71.4:1600]     return self._diff()
[Wed Jul 20 19:35:11.761576 2016] [wsgi:error] [pid 6423] [remote 10.27.71.4:1600]   File "/var/www/vhosts/c2cassoc_c2corgv6/private/v6_ui/c2corg_ui/views/document.py", line 183, in _diff
[Wed Jul 20 19:35:11.761617 2016] [wsgi:error] [pid 6423] [remote 10.27.71.4:1600]     field_diffs = diff_documents(doc_v1, doc_v2)
[Wed Jul 20 19:35:11.761814 2016] [wsgi:error] [pid 6423] [remote 10.27.71.4:1600]   File "/var/www/vhosts/c2cassoc_c2corgv6/private/v6_ui/c2corg_ui/diff/differ.py", line 39, in diff_documents
[Wed Jul 20 19:35:11.761856 2016] [wsgi:error] [pid 6423] [remote 10.27.71.4:1600]     return _get_field_diffs(doc1, doc2)
[Wed Jul 20 19:35:11.761942 2016] [wsgi:error] [pid 6423] [remote 10.27.71.4:1600]   File "/var/www/vhosts/c2cassoc_c2corgv6/private/v6_ui/c2corg_ui/diff/differ.py", line 57, in _get_field_diffs
[Wed Jul 20 19:35:11.761983 2016] [wsgi:error] [pid 6423] [remote 10.27.71.4:1600]     if val1.get('version') != val2.get('version') and not (
[Wed Jul 20 19:35:11.762066 2016] [wsgi:error] [pid 6423] [remote 10.27.71.4:1600] AttributeError: 'NoneType' object has no attribute 'get'

**Comment by asaunier** [comment]
Concerning the diff error, it seems related to the fact the route has no geometry at all (it is not even associated to a WP), which makes the following code crash:
https://github.com/c2corg/v6_ui/blob/master/c2corg_ui/diff/differ.py#L49-L59
(the compared geometries are ``None``).

By the way I don't remember if it legal to have a route with no associated WP (at least it is possible in the UI)!?

**Comment by shortoland** [comment]
Alex: thanks for the explanation concerning the 2 checkboxes.
I have added a hut as a WP, and the issue when comparing is still there.

**Comment by asaunier** [comment]
Could you give the URL of the WP page?

**Comment by shortoland** [comment]
Here is the url of the route, is it what you need ?
http://c2corgv6.demo-camptocamp.com/routes/edit/736979/fr
I just added a hut as a "Points de passage associés". I suppose this is what you name a WP.
Tell me if I am wrong or misunderstood ... it's not that easy to catch everything quickly ;-)

**Comment by shortoland** [comment]
And in case inserting a WP is mandatory, we should get a warniong/error message in case there is none.

**Comment by asaunier** [comment]
Sorry I misread your comment and thought you had the problem with the versions of a WP.
Associating a hut to the route has created a default geometry and the diff between the 2 most recent versions of the route seems to work as expected. It still doesn't work with older versions but it's no surprise: the old versions remain unchanged and still lack a geometry.

> And in case inserting a WP is mandatory, we should get a warniong/error message in case there is none.

It would make sense yes but should be reported in a dedicated issue I think.

**Comment by shortoland** [comment]
OK, I think I fully understand now :-)
I close this ticket and will open a new one then.

**Comment by asaunier** [comment]
I prefer we keep this issue open: perhaps it will be solved if we decide route cannot be created without an associated WP (separated issue for this). But if not, the problem is still there.

In your new issue, please add a link to the current issue.

**Comment by fjacon** [comment]
It will not be possible to create a route without an associated WP.
