### ISSUE TITLE
No rating block for via ferrata

### ISSUE THREAD

**Issue by stef74** [c2corg/v6_ui#509]
On http://c2corgv6.demo-camptocamp.com/routes/edit/342031/fr 
I have no rating block.

If I add an other activity rating block appear with good rating field (for both activities)

Previsoulys this route is multiple activity I have changed to via ferrata activity.

**Comment by stef74** [comment]
@ginold not fixed on my example.

**Comment by ginold** [comment]
I see, I'm surprised something went wrong because I had fixed it. 
Refixing it right now.

**Comment by ginold** [comment]
Ok I understood the problem !
@stef74, I think we didn't add the property materiel glacier for activity via ferrata and therefore it doens't appear, but when you select another activity that does, it works.
Should we add materiel glacier for via ferrata?

**Comment by stef74** [comment]
we don't have to add materiel de glacier for via ferrata activity

2016-07-29 11:41 GMT+02:00 ginold <notifications@github.com>:

**Comment by ginold** [comment]
Ok, so I remove the field "materiel glacier" when only via ferrata is selected.

**Comment by loicperrin** [comment]
In fact there is no rating block when only one activity is selected. When 2 activities, the rating blocks appears (and mixed for the 2 activities).

**Comment by asaunier** [comment]
> In fact there is no rating block when only one activity is selected. When 2 activities, the rating blocks appears (and mixed for the 2 activities).

I think this has been fixed last week by https://github.com/c2corg/v6_ui/pull/545/files
I have upgraded the demo, please test again :)

**Comment by shortoland** [comment]
Looks good to me, I close the ticket
