### ISSUE TITLE
Document creation: incorrect default lang

### ISSUE THREAD

**Issue by asaunier** [c2corg/v6_ui#510]
When creating a new document (route/outing/...), the language selected by default in the editing form is "english" whereas my interface is in french => the default language should be the same than the interface language.

**Comment by ginold** [comment]
I'm using `gettextCatalog.currentLanguage` that you suggested. But console.logging `gettextCatalog.currentLanguage` always gives me 'en' as response, whereas `gettextCatalog` and clicking on currentLanguage gives the correct language ;/

**Comment by asaunier** [comment]
We have to investigate this point. ``gettextCatalog.currentLanguage`` is successfully used in other parts of the code.

**Comment by ginold** [comment]
apparently, currentLanguage came to early and was read as English by default. Hopefully it seems to work with `$cookies.get('interface_lang');`

**Comment by asaunier** [comment]
Perhaps but this approach does not seem correct to me. We should have a unified way to figure the current interface language out.
