### ISSUE TITLE
Add error message if no WP is associated to a new route

### ISSUE THREAD

**Issue by shortoland** [c2corg/v6_ui#511]
It seems it's mandatory to associate a WP when creating a new route, so could it be possible to display an error message (requesting to add a WP) when this is not done ?

**Comment by shortoland** [comment]
#508

**Comment by loicperrin** [comment]
A route cannot be created with no associated  WP.
When saving such a route, an error message should be displayed (similar to routes without activity), and the route is not saved, until a WP is associated.

**Comment by stef74** [comment]
@loicperrin @shortoland please test

**Comment by shortoland** [comment]
OK, error message added.

**Comment by loicperrin** [comment]
It is OK when saving a route without associated WP: there is an error message.
But once saved, if I remove the WP, no error message is displayed and the route has no more associated WP.

**Comment by ginold** [comment]
you mean - when you go to the view page, you can delete the last associated waypoint ? (not the editing page)

**Comment by loicperrin** [comment]
> you mean - when you go to the view page, you can delete the last associated waypoint ? (not the editing page)

Yes exactly. An error message should be added in this case (as for the main waypoint for example).

**Comment by stef74** [comment]
@loicperrin @shortoland  please test

**Comment by shortoland** [comment]
There is now an error message when deleting the last WP of a route in edition mode.
I haven't been able to remove a WP in a view mode.
OK for me, I close the ticket. Loic, feel free to reopen if needed.

**Comment by loicperrin** [comment]
OK for this. But there is another problem: I create another issue.
