### ISSUE TITLE
'Matériel glacier' is not displayed

### ISSUE THREAD

**Issue by desnoes** [c2corg/v6_ui#514]
The selection of a filed in 'Materiel glacier'is not displayed
http://c2corgv6.demo-camptocamp.com/routes/edit/736977/it

**Comment by ginold** [comment]
yes it is : 3rd step under "materiel". Probably it's not the best place for this field. Where do you think it should be moved to?

**Comment by desnoes** [comment]
When you save the new route, this field is not displayed. You can check with the example i gave above.

**Comment by stef74** [comment]
@desnoes please test

**Comment by desnoes** [comment]
the bug has been corrected
