### ISSUE TITLE
'Durées' : modification of title

### ISSUE THREAD

**Issue by desnoes** [c2corg/v6_ui#515]
In the information section, the field 'durée' is displayed. The title should be modified to give the unit measure: 'Durées' => 'Durées (jours)'
cf. http://c2corgv6.demo-camptocamp.com/routes/736977/it

**Comment by asaunier** [comment]
Unless the unit should appear next to the attribute value, this change should be done in the interface translations (ie. by the translation team).

**Comment by desnoes** [comment]
No, this concerns only the title. 
i close the issue. 

----- Mail Original ----- 
De: "Alex Saunier" <notifications@github.com> 
À: "c2corg/v6_ui" <v6_ui@noreply.github.com> 
Cc: "desnoes" <mathieu.desnoes@free.fr>, "Author" <author@noreply.github.com> 
Envoyé: Jeudi 21 Juillet 2016 22h17:48 GMT +01:00 Amsterdam / Berlin / Berne / Rome / Stockholm / Vienne 
Objet: Re: [c2corg/v6_ui] 'Durées' : modification of title (#515) 



Unless the unit should appear next to the attribute value, this change should be done in the interface translations (ie. by the translation team).
