### ISSUE TITLE
Route creation: 'exposition ski' is not located in the correct section

### ISSUE THREAD

**Issue by desnoes** [c2corg/v6_ui#517]
In the last page of the creation of a route (Revue), the field 'Exposition ski' is located in the 'Gear' section while it should be located in the 'Ratings' section with the other fields dedicated to ski.

**Comment by ginold** [comment]
For now, the Revue page should not be considered nor reviewed at all because it will change drastically, we have plans for it. At the moment, it is just a provisional page.

**Comment by asaunier** [comment]
Indeed, see https://github.com/c2corg/v6_ui/issues/168
