### ISSUE TITLE
Show a custom page for 500-errors

### ISSUE THREAD

**Issue by asaunier** [c2corg/v6_ui#518]
In prod mode, when a page crashes (500 Internal Server Error), the standard apache page is displayed
![sans titre](https://cloud.githubusercontent.com/assets/1192331/17056976/7dc495c4-5017-11e6-9c70-e8d79470ee41.png)

It would be better to display a custom page similar to the 404 custom page already available in the app.

Please note that in dev mode, useful info are provided, which would be worth displaying anyway.

![sans titre](https://cloud.githubusercontent.com/assets/1192331/17057041/e48ad688-5017-11e6-83bd-f9a9e87bb787.png)

**Comment by stef74** [comment]
not mandatory for go live ...
