### ISSUE TITLE
Add filter in doc list

### ISSUE THREAD

**Issue by loicperrin** [c2corg/v6_ui#523]
- [ ] In the page of a WP : associated routes should be displayed:
  1) grouped by activity
  2) in alphabetic order for a same activity
- [ ] In the page of a route: associated WP should be diplayed:
  1) grouped by WP type (first summits, second: parkings, third: huts,...)
  2) in alphabetic order for a same WP type

**Comment by asaunier** [comment]
> In the page of a WP : associated routes should be displayed:
1) grouped by activity

How should card be grouped when routes have several activities?

**Comment by fjacon** [comment]
Proposition : 
- order by name
- Always keep a link to advanced search (even if less than 30 results
@tsauerwein any opinion ?

**Comment by loicperrin** [comment]
In the page of a WP : associated routes should be displayed (as in V5):
1) grouped by activity, with a sub-title for each activity containing routes
2) in alphabetic order (route name) for a same activity
3) when routes have several activities, the cards are duplicated in each activity

**Comment by asaunier** [comment]
For me this solution is not satisfaying because duplicating multiactivity-route cards will take even more space (scroooooolling) and will confuse people (as already the case in v5 - remember Ro's recent email...) if they don't realize that's the same routes.

**Comment by tsauerwein** [comment]
We could display all routes of a waypoint in one group (in alphabetic order) and provide a filter on the activities at the top of the group. Something like this:

![c2c-activities-filter](https://cloud.githubusercontent.com/assets/266474/17204751/9164f76a-54a7-11e6-9e6f-5a198f19271d.png)

**Comment by stef74** [comment]
@tsauerwein great idea !

**Comment by fjacon** [comment]
Indeed, it is also additional work : about 1 day. 
@stef74  Is that OK for you ?

**Comment by loicperrin** [comment]
> @tsauerwein great idea ! 

+1

**Comment by stef74** [comment]
Ok we validated the solution of @tsauerwein . For filtering use the icon instead a text. @fjacon please send the extention to hervé.

**Comment by asaunier** [comment]
Solutions discussed with @tsauerwein to implement this filtering:

> I guess we could add an "ng-show" condition to the app-card element, a bit like this:
```
<div class="list-item" ng-repeat="doc in ${associations}">
  <app-card app-card-doc="doc" ng-show="doc.activities.indexOf(filteredActivity) !== -1"></app-card>
</div>
```

> You can also use a filter with "ng-repeat":
http://fdietz.github.io/recipes-with-angular-js/common-user-interface-patterns/filtering-and-sorting-a-list.html
https://docs.angularjs.org/api/ng/filter/filter

**Comment by fjacon** [comment]
Ressource Estimation : 3 days

**Comment by asaunier** [comment]
> We could display all routes of a waypoint in one group (in alphabetic order) and provide a filter on the activities at the top of the group. Something like this:
>
> ![c2c-activities-filter](https://cloud.githubusercontent.com/assets/266474/17204751/9164f76a-54a7-11e6-9e6f-5a198f19271d.png)

@stef74 @desnoes Should the associated document filter tool allow to choose several activities at the same time, or only one at a time is enough?

**Comment by stef74** [comment]
Hummm several for escalade/RHM case ... but i'm not sure is possible to have route with those two activities (but possible if the new definition).

**Comment by desnoes** [comment]
I would start with a simple solution: one at a time.

**Comment by desnoes** [comment]
@asaunier : it is eventually possible to select several activities at the same time. You confirm ?

**Comment by asaunier** [comment]
> it is eventually possible to select several activities at the same time. You confirm ?

Yes. You may test it for instance here http://www.demov6.camptocamp.org/waypoints/39526/fr/pic-coolidge

**Comment by desnoes** [comment]
Yes i observed it during my test, i just wanted to have a confirmation. It works very fine.
