### ISSUE TITLE
Markers on map are flashing when hovering them

### ISSUE THREAD

**Issue by asaunier** [c2corg/v6_ui#527]
When the mouse cursor hovers a WP/route/outing on the map, the icon often "vibrates", showing alternatively the highlighted icon and the normal one.

The behaviour is probably dued to the fact that SVG icons with a complex shape are used. When the mouse cursor moves, it is sometimes above a part of the icon, sometimes not.

Using more massives/circular/square icons, or at least their "active" shapes, would probably help prevent this behaviour.

**Comment by tsauerwein** [comment]
The icons contain transparent areas, which are ignored by ol3. When hovering the transparent area of an icon, the feature is not selected. We could show a (semi-) transparent circle behind the actual icon.

**Comment by asaunier** [comment]
That would be cool indeed. Does that require to change the SVG icon or is it possible to add this background circle dynamically?

**Comment by tsauerwein** [comment]
The [style function](https://github.com/c2corg/v6_ui/blob/b1dc8b3930d2b87b6bc02dac2b68eeaa911bf21b/c2corg_ui/static/js/map/map.js#L347) can return an array of styles. The first style would be a style with the circle, the 2nd style the icon.

**Comment by asaunier** [comment]
Since PR https://github.com/c2corg/v6_ui/pull/521 has been merged, this behaviour has greatly been reduced.

**Comment by tsauerwein** [comment]
> ... has greatly been reduced.

The problem that we are using transparent icons is still there.

**Comment by asaunier** [comment]
True. Actually it depends a lot on the shape of the icon.

**Comment by tsauerwein** [comment]
Fixed with https://github.com/c2corg/v6_ui/pull/581
