### ISSUE TITLE
Dynamic dates according to locale

### ISSUE THREAD

**Issue by gberaudo** [c2corg/v6_ui#53]
We can format dates with `number | date`, however there is no way to specify/change the
locale we want to use. In addition, we need to depend on ngLocale.
See:
- https://docs.angularjs.org/guide/i18n
- https://github.com/lgalfaso/angular-dynamic-locale

**Comment by tsauerwein** [comment]
We could define a custom filter which takes the locale into account. For example similar to this one:
https://github.com/camptocamp/provelobern_bicyclerouteplanner/blob/master/app/provelobern/static/js/maincontroller.js#L779-L809

**Comment by gberaudo** [comment]
Good idea.
https://github.com/google/closure-library/blob/master/closure/goog/i18n/datetimesymbols.js
https://github.com/google/closure-library/blob/master/closure/goog/i18n/datetimeformat.js#L107

**Comment by asaunier** [comment]
Fixed by #266
