### ISSUE TITLE
Field value on new line

### ISSUE THREAD

**Issue by stef74** [c2corg/v6_ui#531]
Some value are on new line ... and some other is on the same line of the label field. A new line is needed only if have not enough space

See attachement 
![capture1](https://cloud.githubusercontent.com/assets/3962997/17171715/2f745baa-53f2-11e6-83a1-3a2da39f6f71.PNG)
![capture2](https://cloud.githubusercontent.com/assets/3962997/17171713/2f72141c-53f2-11e6-8976-790587e1cf50.PNG)
![capture3](https://cloud.githubusercontent.com/assets/3962997/17171714/2f726174-53f2-11e6-9ba1-b20ea9943cde.PNG)

**Comment by stef74** [comment]
demo is updated ?

**Comment by asaunier** [comment]
No, I won't update the demo every time a pull request is merged :)

**Comment by stef74** [comment]
So don't put ready for test ... ;-)

2016-07-27 14:26 GMT+02:00 Alex Saunier <notifications@github.com>:
