### ISSUE TITLE
Issue when zooming on swiss map with firefox

### ISSUE THREAD

**Issue by shortoland** [c2corg/v6_ui#535]
When using the swiss map (swisstopo) with firefox, I have a display issue (tiles duplication) when zooming 'a lot':

![image1](https://cloud.githubusercontent.com/assets/20488365/17176287/373da7f0-540c-11e6-82a5-c7436adfbc6d.png)

**Comment by tsauerwein** [comment]
It looks like we have to restrict the maximum zoom-level.

**Comment by shortoland** [comment]
Yes, not sure we need this zoom-level.
Have the same issue when using IE, Chrome or Safari.

**Comment by shortoland** [comment]
It's OK, thanks !
