### ISSUE TITLE
Outing creation/modification: pb with "signe d'avalanche" field

### ISSUE THREAD

**Issue by loicperrin** [c2corg/v6_ui#546]
* [x] When this field is not empty (for any value selected), the outing cannot be saved: an error message is displayed ("recent_avalanche" is not iterable).
* [x] When modifying an outing, the current value of this field is not selected

**Comment by fjacon** [comment]
@ginold is is ready for testing ?

**Comment by ginold** [comment]
yes, it's already available on the demo.

**Comment by stef74** [comment]
@loicperrin please test

**Comment by loicperrin** [comment]
OK
