### ISSUE TITLE
Todolist creation of a new document type

### ISSUE THREAD

**Issue by asaunier** [c2corg/v6_ui#548]
For instance for creating the "article" document type

API side (to be moved in an API issue?)
* [ ] model
* [ ] pyramid view + routes
* [ ] search (indexing + search mapping)
* [ ] tests
* [ ] migration

UI side:
* [ ] pyramid view + routes
* [ ] view template
* [ ] editing template
* [ ] advanced search template
* [ ] association + simple search cards

Feel free to update the list!

**Comment by asaunier** [comment]
Is this "issue" really needed?
@ginold @dkocich do you think it is useful for adding the support of articles/books?

If not, we can close it.

**Comment by tsauerwein** [comment]
A wiki page would maybe be a better place, because it is not really an "issue".

**Comment by asaunier** [comment]
Indeed.
Actually this list is a bit too general. Not sure it is really useful either as an issue or a wiki page.
Anyway it's probably a good practise to create a todolist in a dedicated issue or PR when adding a new document type. Like for areas for instance: https://github.com/c2corg/v6_ui/issues/668#issue-180026487
