### ISSUE TITLE
Avoid that page elements "jump" when loading

### ISSUE THREAD

**Issue by tsauerwein** [c2corg/v6_ui#551]
On detail pages (e.g. http://c2corgv6.demo-camptocamp.com/routes/737035/fr), when loading/reloading the page, the elements below the map jump down when the map is shown.

The problem is that the height of the map is set on the `viewport` element (in [viewdetails.less](https://github.com/c2corg/v6_ui/blob/e1724c8c11fa5483bd78954a9c042f54a1132bc1/less/viewdetails.less#L497-L517)). When the page is loaded, the viewport element does not exist yet, so that the browser does not know how much space the map element will take. Only when the map is initialized, the height defined in the CSS is applied.

It would be better to set the height on the map element itself.

**Comment by fjacon** [comment]
@ginold : it seems fixed ? can you confirmed ?

**Comment by asaunier** [comment]
Not fixed at all, at least in the demo.
