### ISSUE TITLE
Use # instead of query params for filters in URL

### ISSUE THREAD

**Issue by tsauerwein** [c2corg/v6_ui#554]
The listing pages use query parameters to encode filters in the URL (e.g. `waypoints?bbox=...&...`). The problem is that the page can not be cached properly, because if the query params are different, the browser cache (and also Varnish) will treat the requests as two different pages (while the rendered page served to the client-side is actually the same no matter what filter is set).

Instead we should encode the filter parameters with `#bbox=...&...`.

**Comment by asaunier** [comment]
> Instead we should encode the filter parameters with #?bbox...&....

Advanced search parameters are added (and read) using ``ngeo.Location`` https://camptocamp.github.io/ngeo/master/apidoc/ngeo.Location.html
So using another syntax depends on its support by ``ngeo.Location``.
