### ISSUE TITLE
Usernames available in the HTML

### ISSUE THREAD

**Issue by asaunier** [c2corg/v6_ui#555]
In outing detail view pages, the HTML contains a ``documentData`` module value with the list of associated documents. Among those associated docs, there are the associated users for whom id, full name and username are provided.

I am wondering if providing the username could not be a security breach since it is probably a part of the authentication data. Or maybe it's the "pseudo" used in forum pages?

**Comment by fjacon** [comment]
@tsauerwein what is your opinion on this ?

**Comment by tsauerwein** [comment]
I don't consider it a problem that the username is public. That's the case for most/all community sites. But if it is not required from the UI side, we don't need to return it.

**Comment by ginold** [comment]
so, if it is not a problem, can this issue be closed @asaunier  ?

**Comment by asaunier** [comment]
According to @tsauerwein 

> But if it is not required from the UI side, we don't need to return it.

Is this attribute used in the UI?
If not, what should we do to remove it from the data provided by the API? In that case, is it an API-only issue? If yes we could create the API issue and close this one.

**Comment by asaunier** [comment]
``username`` is no longer passed to the UI.
