### ISSUE TITLE
Simplifying uploaded GPX tracks

### ISSUE THREAD

**Issue by asaunier** [c2corg/v6_ui#556]
Since PR https://github.com/c2corg/v6_api/issues/342 and https://github.com/c2corg/v6_api/pull/358 have been merged, associated routes with `geom_detail` data (line geometry) are displayed on the map of WP detail view pages.

2 problems might occur though:
- associated route geometries are embedded in the page HTML and might be quite big if not simplified enough (see https://github.com/c2corg/v6_api/issues/359)
- if there are too many lines on the map, the latter can be hard to read and use

We need to evaluate whether this feature is adapted or not.

**Comment by fjacon** [comment]
Can we find examples of big route geometries ?

**Comment by asaunier** [comment]
Waypoint "Mont de Grange" has several associated routes with GPS tracks:
http://c2corgv6.demo-camptocamp.com/waypoints/37737/fr

including this one which looks pretty big:
http://c2corgv6.demo-camptocamp.com/routes/211687/fr
v5 :  http://www.camptocamp.org/routes/211687/fr/mont-de-grange-traversee-bel-air-coicon
The associated GPX file in v5 is >800 KB big (300 points).
I have noticed even bigger tracks but don't remember where to find them.

**Comment by asaunier** [comment]
> The associated GPX file in v5 is >800 KB big (300 points).

A contributor has recently tried to upload a 2.7 MB track. Uploading big tracks in v5 fails (file size check?). It should not be possible in v6 either.
The best solution would be to apply automatically some simplification on uploaded tracks. Probably on the API side anyway but also client side in the editing page (when drag-dropping a track on the map?).

**Comment by asaunier** [comment]
For track simplification on the client side, perhaps see this website http://www.mygpsfiles.com/app/

**Comment by tsauerwein** [comment]
ol3 supports simplification: http://openlayers.org/en/master/apidoc/ol.geom.MultiLineString.html#simplify

**Comment by asaunier** [comment]
Finally the associated routes tracks are no longer displayed in the WP pages. But simplifying uploaded GPX tracks would be useful when users upload really big GPX tracks.

As a result I keep the issue open but have changed its title.

**Comment by asaunier** [comment]
For me this issue is important and should be considered earlier than "Later" because if a user upload a 2MB track in their outing, the 2MB geometry will be loaded when the outing page is loaded!

**Comment by tsauerwein** [comment]
This is actually already implemented, see: https://github.com/c2corg/v6_ui/blob/ff93861549d61f6a52ed587d006d7cd9968b40a0/c2corg_ui/static/js/map/map.js#L844
