### ISSUE TITLE
Incorrect filter in waypoint detail view badges

### ISSUE THREAD

**Issue by asaunier** [c2corg/v6_ui#567]
In a document detail view page, right next to the title is displayed a badge with the document type. This badge is clickable and opens the advanced search page for the given doc type.

For waypoints, the badge URL contains a ``wtyp`` filter parameter, but with the old ``?`` syntax instead of the new ``#``one:
https://github.com/c2corg/v6_ui/blob/master/c2corg_ui/templates/waypoint/view.html#L88
As a result the filter is ignored in the opening advanced search page.

Questions:
* what is the best way to use ``#`` instead of ``?`` here? Perhaps simply by replacing
```
onClick="window.location='${request.route_url('waypoints_index', _query={'wtyp': waypoint['waypoint_type']})}'"
```
by
```
onClick="window.location='${request.route_url('waypoints_index') + '#wtyp=' + waypoint['waypoint_type']}'"
```
?
* I wonder if this filter, as is, is really relevant. For other document types we have no such filter. Should we drop it? Add other filter such as a bbox (for the waypoints of the same type in the same area?)?

**Comment by tsauerwein** [comment]
> what is the best way to use # instead of ? here? Perhaps simply by replacing

Yes. Similar to this: https://github.com/c2corg/v6_ui/pull/557/commits/9d3032b83be50264b315847444ea0d87c0ad4efa#diff-fc5e7699c71efab8fb7885cb1cab2675
