### ISSUE TITLE
Optimize slugification and use lighter API service

### ISSUE THREAD

**Issue by asaunier** [c2corg/v6_ui#568]
As for now, the slugification service uses a standard "get document" API request that returns the full attributes of the document whereas only the title is needed.
https://github.com/c2corg/v6_ui/blob/master/c2corg_ui/views/document.py#L423

When https://github.com/c2corg/v6_api/issues/364 is addressed, the UI side should use this new light service instead.

**Comment by fjacon** [comment]
https://github.com/c2corg/v6_api/issues/364 is closed.

**Comment by asaunier** [comment]
Yes, PR https://github.com/c2corg/v6_ui/pull/572 fixes this issue.

**Comment by tsauerwein** [comment]
https://github.com/c2corg/v6_ui/pull/572 is not yet merged.
