### ISSUE TITLE
Use different API address for UI server side

### ISSUE THREAD

**Issue by tsauerwein** [c2corg/v6_ui#578]
Currently the same API address is used to make request from the UI client-side and from the UI server side. On the UI server side it would be better to use a more direct address/host name.

**Comment by asaunier** [comment]
It's already the case, see
https://github.com/c2corg/v6_ui/blob/c1f6ae7595cba65452c73a9ed202fdb42b019ab2/c2corg_ui/views/document.py#L139
https://github.com/c2corg/v6_ui/blob/master/config/main#L6-L7

**Comment by tsauerwein** [comment]
Perfect, thanks!
