### ISSUE TITLE
Version is not updated when editing a document

### ISSUE THREAD

**Issue by tsauerwein** [c2corg/v6_ui#586]
Steps to reproduce:

1) I go to the page to edit a document, e.g. `/routes/edit/736901/ca`.
2) I change the title.
3) I press save.
4) Then I change the title and press save again.
5) I see the error message: "Version of ca has changed: Conflict"

When successfully updating a document, the new document version has to be used.

**Comment by ginold** [comment]
_maybe_ fixed in my PR https://github.com/c2corg/v6_ui/pull/582/commits/52979490511a2a52358223d77323c407bcc18fa7

I had this error and it fixed it.

**Comment by tsauerwein** [comment]
Yes, that looks good!
