### ISSUE TITLE
Poor loading notifications

### ISSUE THREAD

**Issue by asaunier** [c2corg/v6_ui#593]
As for now when authenticating/registering/resetting/changing the account data, there is nothing indicating something is going on in the background.

A (partial) PR addresses this problem but needs more work I think: https://github.com/c2corg/v6_ui/pull/457

**Comment by asaunier** [comment]
This issue is a bit critical I think: for instance when you try to register, nothing tells you that a request is pending: no loading indicator, the submit button remains active => if the response is not fast (it generally isn't) you just want to click several times on the button.

There's probably a similar problem with several other write actions.

**Comment by dkocich** [comment]
Maybe something like this can be used? https://chieffancypants.github.io/angular-loading-bar/

**Comment by asaunier** [comment]
> Maybe something like this can be used? https://chieffancypants.github.io/angular-loading-bar/

That looks great indeed!
Would be useful for https://github.com/c2corg/v6_ui/issues/456#issuecomment-247940897 as well

**Comment by tsauerwein** [comment]
I've set up angular-loading-bar for another project, and it worked out of the box.

When we set it up, we have to make it sure that it plays nicely with already existing loading indicators (for example for the feed or advanced search).

**Comment by asaunier** [comment]
See also https://github.com/c2corg/v6_ui/pull/925
