### ISSUE TITLE
rename non-route-specific functions

### ISSUE THREAD

**Issue by ginold** [c2corg/v6_ui#594]
some functions that seem to be route-specific are in fact used also for other documents, so their names should be more generic, for example `get_route_activities` shoud become `get_document_activities` because it's used within outings, routes and images.

**Comment by asaunier** [comment]
There's also ``show_route_title`` which seems used for all document types: 
https://github.com/c2corg/v6_ui/search?utf8=%E2%9C%93&q=show_route_title
https://github.com/c2corg/v6_ui/blob/d5b38e1ab35851437826cf39c2887a52275f3c4d/c2corg_ui/templates/helpers/view.html#L61

**Comment by fjacon** [comment]
Should we do this rapidly ?

**Comment by asaunier** [comment]
That's not critical but the more we wait, the more those tools will be used (when adding new document types such as articles, books, areas, etc.) => more changes to do later.
