### ISSUE TITLE
Missing strings in Transifex

### ISSUE THREAD

**Issue by fbunoz** [c2corg/v6_ui#602]
In Transifex, it misses all the strings used in the options of the single or multiple choice fields.

**Comment by asaunier** [comment]
Please be more precise.

**Comment by fbunoz** [comment]
Je ne vais pas passer du temps à faire la liste exacte des chaines qui
manquent s'il y a un import automatique dans transifex avec parsage du code.
Comme il manque des centaines de chaines, c'est qu'il y a un gros problème
dans l'import automatique.

Je donne quand même des exemples. Il manque toutes les options des champs :
- route_type
- route_configuration_type
- climbing_outdoor_type
- rock_type
- cotation globale alpi (et oui, en DE ce ne sont pas les même symboles)
- matériel de glacier
- déneigement
- type de transport en commun
- public_transportation_rating
- climbing_styles
- pluie
- adapté aux enfants

Et surement d'autres (je n'ai pas regardé dans les sorties).


2016-09-06 17:11 GMT+02:00 Alex Saunier <notifications@github.com>:

**Comment by asaunier** [comment]
> Je ne vais pas passer du temps à faire la liste exacte des chaines qui
manquent s'il y a un import automatique dans transifex avec parsage du code.
Comme il manque des centaines de chaines, c'est qu'il y a un gros problème
dans l'import automatique.

Please don't assume things you know nothing about!
It's probably because those strings are not autodetected for some reason (not marked as to be translated for instance), not being related with the Transifex sync tool.

> Il manque toutes les options des champs :

OK thanks, it helps a lot to have an example, rather than a general "it doesn't work" :P

**Comment by asaunier** [comment]
I think there are 2 explanations that are combined:
* single/multi choice fields are generally built dynamically and their values are not explicitly available in the templates, this are not auto-extracted/pushed to Transifex. Those strings must be added in this fake template used to specify by hand the strings to be translated if there are not already available in another template https://github.com/c2corg/v6_ui/blob/master/c2corg_ui/templates/i18n.html
* it seems the following syntax when using a variable expression is defective and that the translation does not work as expected: ``<span x-translate>{{type}}</span>``. Using ``<span>{{type | translate}}</span>`` work but I don't remember if does not make the variable ``type`` to be extracted and added to Transifex.

**Comment by asaunier** [comment]
Closing as duplicate of https://github.com/c2corg/v6_ui/issues/627
