### ISSUE TITLE
Incorrect i18n string "difficulties length"

### ISSUE THREAD

**Issue by fbunoz** [c2corg/v6_ui#603]
In routes :
- for reading, the difficulties length field title ("Longueur des difficultés") uses the transifex ID difficulties_length
- for edition, the difficulties length field title uses another transifex ID : 
  difficulties_height or height_diff (with the same translation : "Hauteur des difficultés" => doublon ?). It must be difficulties_length.

I don't know where the difficulties_height or height_diff ID are needed. I may be wrong, but there is no need for "Hauteur des difficultés". Only "Dénivelé des difficultés" and "Longueur des difficultés" are needed.

**Comment by asaunier** [comment]
I have changed the title of the issue because it is not related with Transifex. Transifex is a third-party service for translating the interface strings. The actual translation format is "gettext".

**Comment by asaunier** [comment]
Is this issue still relevant? fixed in the meantime?
I can no longer find ``difficulties_length`` in the UI code: https://github.com/c2corg/v6_ui/search?utf8=%E2%9C%93&q=difficulties_length&type=Code

**Comment by stef74** [comment]
@shortoland please test

**Comment by shortoland** [comment]
I changed the translation for "difficulties_height" from "Hauteur des difficultés" to "Longueur des difficultés". But I cannot fond where "Hauteur des difficultés" was used in the demo ...
Anyway, sometimes it's very hard for me to understand the real meaning of english strings.
And as I am not the only translator in english, feel free to check/modify my translations if needed ;-)

**Comment by asaunier** [comment]
@shortoland OK for closing this issue?
