### ISSUE TITLE
Debug mode does not work on the dev server

### ISSUE THREAD

**Issue by asaunier** [c2corg/v6_ui#606]
On the dev/demo server, either in the demo instance or in a personal dev instance, when using the debug mode (`?debug` in the URL), one gets JS errors:

```
goog.require could not find: app.MainController
```

most likely because `closure-deps.js` cannot be downloaded ("500 Internal Server Error").

For instance: http://c2corgv6.demo-camptocamp.com/?debug => http://c2corgv6.demo-camptocamp.com/closure-deps.js is 500

The apache logs say:

> [Wed Sep 07 17:53:20.429204 2016] [wsgi:error] [pid 29942] [remote 10.27.71.4:63826] mod_wsgi (pid=29942): Exception occurred processing WSGI script '/var/www/vhosts/c2cassoc_c2corgv6/private/v6_ui/apache/app-c2corg_ui.wsgi'.
> [Wed Sep 07 17:53:20.429450 2016] [wsgi:error] [pid 29942] [remote 10.27.71.4:63826] Traceback (most recent call last):
> [Wed Sep 07 17:53:20.429775 2016] [wsgi:error] [pid 29942] [remote 10.27.71.4:63826]   File "/var/www/vhosts/c2cassoc_c2corgv6/private/v6_ui/.build/venv/lib/python3.4/site-packages/pyramid/router.py", line 236, in **call**
> [Wed Sep 07 17:53:20.429800 2016] [wsgi:error] [pid 29942] [remote 10.27.71.4:63826]     response = self.invoke_subrequest(request, use_tweens=True)
> [Wed Sep 07 17:53:20.429872 2016] [wsgi:error] [pid 29942] [remote 10.27.71.4:63826]   File "/var/www/vhosts/c2cassoc_c2corgv6/private/v6_ui/.build/venv/lib/python3.4/site-packages/pyramid/router.py", line 211, in invoke_subrequest
> [Wed Sep 07 17:53:20.429889 2016] [wsgi:error] [pid 29942] [remote 10.27.71.4:63826]     response = handle_request(request)
> [Wed Sep 07 17:53:20.429949 2016] [wsgi:error] [pid 29942] [remote 10.27.71.4:63826]   File "/var/www/vhosts/c2cassoc_c2corgv6/private/v6_ui/c2corg_ui/caching/cacheversion.py", line 43, in **call**
> [Wed Sep 07 17:53:20.429965 2016] [wsgi:error] [pid 29942] [remote 10.27.71.4:63826]     return self.handler(request)
> [Wed Sep 07 17:53:20.430028 2016] [wsgi:error] [pid 29942] [remote 10.27.71.4:63826]   File "/var/www/vhosts/c2cassoc_c2corgv6/private/v6_ui/.build/venv/lib/python3.4/site-packages/pyramid/tweens.py", line 62, in excview_tween
> [Wed Sep 07 17:53:20.430043 2016] [wsgi:error] [pid 29942] [remote 10.27.71.4:63826]     reraise(*attrs['exc_info'])
> [Wed Sep 07 17:53:20.430111 2016] [wsgi:error] [pid 29942] [remote 10.27.71.4:63826]   File "/var/www/vhosts/c2cassoc_c2corgv6/private/v6_ui/.build/venv/lib/python3.4/site-packages/pyramid/compat.py", line 148, in reraise
> [Wed Sep 07 17:53:20.430134 2016] [wsgi:error] [pid 29942] [remote 10.27.71.4:63826]     raise value
> [Wed Sep 07 17:53:20.430183 2016] [wsgi:error] [pid 29942] [remote 10.27.71.4:63826]   File "/var/www/vhosts/c2cassoc_c2corgv6/private/v6_ui/.build/venv/lib/python3.4/site-packages/pyramid/tweens.py", line 22, in excview_tween
> [Wed Sep 07 17:53:20.430204 2016] [wsgi:error] [pid 29942] [remote 10.27.71.4:63826]     response = handler(request)
> [Wed Sep 07 17:53:20.430253 2016] [wsgi:error] [pid 29942] [remote 10.27.71.4:63826]   File "/var/www/vhosts/c2cassoc_c2corgv6/private/v6_ui/.build/venv/lib/python3.4/site-packages/pyramid/router.py", line 158, in handle_request
> [Wed Sep 07 17:53:20.430274 2016] [wsgi:error] [pid 29942] [remote 10.27.71.4:63826]     view_name
> [Wed Sep 07 17:53:20.430335 2016] [wsgi:error] [pid 29942] [remote 10.27.71.4:63826]   File "/var/www/vhosts/c2cassoc_c2corgv6/private/v6_ui/.build/venv/lib/python3.4/site-packages/pyramid/view.py", line 547, in _call_view
> [Wed Sep 07 17:53:20.430357 2016] [wsgi:error] [pid 29942] [remote 10.27.71.4:63826]     response = view_callable(context, request)
> [Wed Sep 07 17:53:20.430450 2016] [wsgi:error] [pid 29942] [remote 10.27.71.4:63826]   File "/var/www/vhosts/c2cassoc_c2corgv6/private/v6_ui/.build/venv/lib/python3.4/site-packages/pyramid/viewderivers.py", line 442, in rendered_view
> [Wed Sep 07 17:53:20.430471 2016] [wsgi:error] [pid 29942] [remote 10.27.71.4:63826]     result = view(context, request)
> [Wed Sep 07 17:53:20.430533 2016] [wsgi:error] [pid 29942] [remote 10.27.71.4:63826]   File "/var/www/vhosts/c2cassoc_c2corgv6/private/v6_ui/.build/venv/lib/python3.4/site-packages/pyramid/viewderivers.py", line 147, in _requestonly_view
> [Wed Sep 07 17:53:20.430668 2016] [wsgi:error] [pid 29942] [remote 10.27.71.4:63826]     response = view(request)
> [Wed Sep 07 17:53:20.430732 2016] [wsgi:error] [pid 29942] [remote 10.27.71.4:63826]   File "/var/www/vhosts/c2cassoc_c2corgv6/private/v6_ui/.build/venv/src/pyramid-closure/pyramid_closure/views.py", line 48, in depsjs
> [Wed Sep 07 17:53:20.430755 2016] [wsgi:error] [pid 29942] [remote 10.27.71.4:63826]     root, prefix=request.static_url(prefix)))
> [Wed Sep 07 17:53:20.430819 2016] [wsgi:error] [pid 29942] [remote 10.27.71.4:63826]   File "/var/www/vhosts/c2cassoc_c2corgv6/private/v6_ui/.build/venv/src/pyramid-closure/pyramid_closure/closure/depswriter.py", line 145, in _GetRelativePathToSourceDict
> [Wed Sep 07 17:53:20.430834 2016] [wsgi:error] [pid 29942] [remote 10.27.71.4:63826]     path_to_source[prefixed_path] = source.Source(source.GetFileContents(path))
> [Wed Sep 07 17:53:20.430891 2016] [wsgi:error] [pid 29942] [remote 10.27.71.4:63826]   File "/var/www/vhosts/c2cassoc_c2corgv6/private/v6_ui/.build/venv/src/pyramid-closure/pyramid_closure/closure/source.py", line 125, in GetFileContents
> [Wed Sep 07 17:53:20.430913 2016] [wsgi:error] [pid 29942] [remote 10.27.71.4:63826]     return fileobj.read()
> [Wed Sep 07 17:53:20.430975 2016] [wsgi:error] [pid 29942] [remote 10.27.71.4:63826]   File "/usr/lib/python3.4/encodings/ascii.py", line 26, in decode
> [Wed Sep 07 17:53:20.431001 2016] [wsgi:error] [pid 29942] [remote 10.27.71.4:63826]     return codecs.ascii_decode(input, self.errors)[0]
> [Wed Sep 07 17:53:20.431076 2016] [wsgi:error] [pid 29942] [remote 10.27.71.4:63826] UnicodeDecodeError: 'ascii' codec can't decode byte 0xdb in position 4068: ordinal not in range(128)

=> unicode problem?

No problem with debug mode in localhost.

**Comment by tsauerwein** [comment]
This is about running `make serve` vs. using Apache? You have the problem when using Apache?

**Comment by asaunier** [comment]
> You have the problem when using Apache?

Yes, see the demo instance http://c2corgv6.demo-camptocamp.com/?debug

But I also have the problem in my dev instance on the dev server, whereas it uses paster.

**Comment by asaunier** [comment]
Same problem with http://ui.alpha3.demov6.camptocamp.org/?debug ("Internal Server Error")

**Comment by brunobesson** [comment]
Is this still the case?
I only saw this issue recently (I was wondering for a long time how to debug js :clap: ), so just tested it and got no such error in the console.

**Comment by brunobesson** [comment]
Hmm. Got this error when trying to see a profile page. I don't remember which other page was working.

**Comment by asaunier** [comment]
> Is this still the case?

It is. Adding ``?debug`` to the prod or demo URLs causes a internal server error.
