### ISSUE TITLE
Uploading images in a document does not refresh its cache

### ISSUE THREAD

**Issue by asaunier** [c2corg/v6_ui#608]
Step to reproduce:
* upload an image in a document detail view => the thumbnail is dynamically added in the document
* reload the page => the new image thumbnail is no longer displayed
* edit the document => the thumbnail now appears

**Comment by ginold** [comment]
as mentioned in https://github.com/c2corg/v6_common/pull/31

**Comment by tsauerwein** [comment]
Indeed, when creating a new document, the cache keys of associated documents are not updated. I reproduced in the API: https://github.com/c2corg/v6_api/commit/6a1fc159618b4c2bfe9ae5a3df99739c253aa03f
