### ISSUE TITLE
Missing associations in an image detail-view?

### ISSUE THREAD

**Issue by asaunier** [c2corg/v6_ui#609]
Recently we added the support of image pages, especially the detail view page.
As far as I can see, in the image detail view, no associations are displayed.
Is it because those images really have no associated document (this is not likely because images are always added from another document detail view page, thus being associated to it).
It seems the associations data are missing in image detail API response!? => rather an API issue?

**Comment by tsauerwein** [comment]
It should work. For example the following request returns the linked waypoints:
http://c2corgv6-api.demo-camptocamp.com/images/24429

Releated to https://github.com/c2corg/v6_ui/issues/608?

**Comment by asaunier** [comment]
You're right, http://c2corgv6.demo-camptocamp.com/images/24429/fr/eee actually has an associated WP.

But I could not find a single image from http://c2corgv6.demo-camptocamp.com/images that has an associated document in its detail view page!?

> Releated to #608?

Is it really a cache problem?
I have tried opening a bunch of image detail view pages (probably never opened, so not already cached) from http://c2corgv6.demo-camptocamp.com/images and never found any associated doc.

**Comment by tsauerwein** [comment]
> But I could not find a single image from http://c2corgv6.demo-camptocamp.com/images that has an associated document in its detail view page!?

Did you confirm that the images that you've checked actually do have associations in the database?

**Comment by asaunier** [comment]
> Did you confirm that the images that you've checked actually do have associations in the database?

Nope, I have not checked but as I said I have tried randomly a bunch of images from http://c2corgv6.demo-camptocamp.com/images and none had associated documents. Which is very unlikely because:
* in v5 (and v6) it is not possible to upload an image and not have it associated to another document => it should at least be associated to the document where it has been uploaded. Mainly outings since people generally upload images to their outings.
* in v5 it is not possible to deassociate an image from a document, except for moderators, but that's not common.

As a result I suspect there is a problem with the migration of the images associations.
For instance in v6 http://c2corgv6.demo-camptocamp.com/images/733245/fr/contraste-sudnord has no associated doc whereas in v5 http://www.camptocamp.org/images/733245/fr/contraste-sud-nord has an associated outing.
Perhaps the image-outing association have not been migrated in v6 as expected?

**Comment by tsauerwein** [comment]
> As a result I suspect there is a problem with the migration of the images associations.
> For instance in v6 http://c2corgv6.demo-camptocamp.com/images/733245/fr/contraste-sudnord has no associated doc whereas in v5 http://www.camptocamp.org/images/733245/fr/contraste-sud-nord has an associated outing.
> Perhaps the image-outing association have not been migrated in v6 as expected?

I checked for this image, there is an association in the database:

     733237;"o";733245;"i"

So, it seems to be a problem in the API.

**Comment by asaunier** [comment]
Indeed http://c2corgv6-api.demo-camptocamp.com/images/733245 returns no association at all.

I have created an API issue at https://github.com/c2corg/v6_api/issues/389

**Comment by ginold** [comment]
Is this issue still valid ? most of the images on my machine do return associations. And it seems to be an API issue, so it should be closed here.

**Comment by asaunier** [comment]
> Is this issue still valid ? 

It seems so. See for instance my example above.
http://c2corgv6-api.demo-camptocamp.com/images/733245 => no associated docs
http://c2corgv6.demo-camptocamp.com/images/733245/fr/contraste-sudnord => no associated docs
http://www.camptocamp.org/images/733245/fr/contraste-sud-nord => at least an associated outing (and areas?)

**Comment by ginold** [comment]
but as stated - this is an api issue and should be removed from the ui's issues?

**Comment by asaunier** [comment]
You're right.
On the other hand it's convenient to keep the issue open on the UI side as well. Else it might be recreated by the testers.

**Comment by stef74** [comment]
API issue was closed ... could you cnfirm if issue can be closed ?

**Comment by asaunier** [comment]
> API issue was closed ... could you cnfirm if issue can be closed ?

I still observe the problem.

For instance this outing has associated images http://www.demov6.camptocamp.org/outings/813273/fr/dalle-a-bornet-sortie-des-artistes
for instance http://www.demov6.camptocamp.org/images/813281/fr/dalle-a-bornet.-sortie-des-artistes.-de-la-vire. (first in the slideshow) but no associated outing is mentioned in the image detail view.

**Comment by tsauerwein** [comment]
The API includes the outings:
http://api.demov6.camptocamp.org/images/813281

**Comment by asaunier** [comment]
OK so it means there is a problem on the UI side.
