### ISSUE TITLE
Additional WMS and vector layers in the maps

### ISSUE THREAD

**Issue by asaunier** [c2corg/v6_ui#610]
I think the specs mention additional layers that should be displayed in the UI maps:
- vector layers (guidebook items: waypoints, routes, outings, images, etc.) in addition to the vector data already displayed in the map
- raster layers (WMS or tiles). For instance the slope layer available in v5: http://www.camptocamp.org/map?map_x=793203.7630048&map_y=5766698.4405443&map_zoom=15&tree_layers=slopes

Vector layers can use the API to get the data to display using some adapted format (eg. GeoJSON or some other vector format, or even vector tiles).

The slope layer is a c2corg-hosted WMS layer using shapefiles in v5: https://github.com/c2corg/camptocamp.org/blob/master/mapdata/c2corg-wms2.map.in#L600-L639

TODO:
- [ ] add a layertree in map directive
- [ ] have a special service in the API to feed the vector layers?
- [ ] install mapserver (in the UI? in the API?) and describe the slope layer in the mapfile
- [ ] host the slopes shapefiles in some docker container?

**Comment by stef74** [comment]
@fjacon could you please give visibility on slope layer topic ( important for ski activity).

**Comment by fjacon** [comment]
To setup a mapserver and a WMS for slope layer is not included in original offer. I consider it as extra work. In any case, it is not feasible for go live.

**Comment by AlexisDemongeot** [comment]
Spanish layers : 
http://www.ign.es/ign/layoutIn/actividadesIDEservicios.do

User conditions : http://www.idee.es/espanol-lisige

**Comment by asaunier** [comment]
We most likely don't need to set a mapserver up because:
* waypoints/routes/... vector layers will be fed by the API services (as in the advanced search pages)
* data tiles such as "slopes > 30°" are now provided by Swisstopo and IGN APIs, we probably don't need our own layer as in v5
* other layers from those external service would be interesting (eg. restricted areas)

Swisstopo layers:
* see Capabilities at http://wmts.geo.admin.ch/1.0.0/WMTSCapabilities.xml?lang=fr
* slopes > 30° ``ch.swisstopo.hangneigung-ueber_30``
* wildlife preservation areas ``ch.bafu.wrz-jagdbanngebiete_select``

IGN:
* slopes > 30° ``GEOGRAPHICALGRIDSYSTEMS.SLOPES.MOUNTAIN`` https://www.geoportail.gouv.fr/donnees/carte-des-pentes (but I don't see it in the list of layers available through the IGN API contracts)

**Comment by asaunier** [comment]
Possible implementation:

1. Create an ``app-layertree`` directive (optionally?) embedded in the map directive: a bit like the ``app-baselayer-selector`` directive https://github.com/c2corg/v6_ui/blob/master/c2corg_ui/static/partials/map/map.html#L23
1. The directive would should show a "layers" button with some icon.
1. Clicking on the button would for instance open a modal. It could be based on ``ngeo.modalDirective`` https://camptocamp.github.io/ngeo/master/apidoc/ngeo.modalDirective.html 
1. The modal would contain a layertree based upon ``ngeo.LayertreeDirective``. See doc at https://camptocamp.github.io/ngeo/master/apidoc/ngeo.layertreeDirective.html and example at https://camptocamp.github.io/ngeo/master/examples/layertree.html
1. The layertree could contain a node for each document type (internal layers) as well as external WMS or WMTS layers such as IGN's or swisstopo's "slopes >30°" layers (see comments above).

### Questions:

Perhaps we need to set services on the API side to get the document-types layers with a GeoJSON output: currently data are returned using a custom JSON format (with embedded GeoJSON elements for geometries), see the advanced search pages. We cannot use the latter output directly for feeding a vector layer on the map.

In addition the standard API format returns a limited number of results for each request. OK for narrow map extents but how can we manage large extents with a lot of data?
In a standard we can't really use pagination as in the advanced search pages.
Perhaps data clustering as in http://openlayers.org/en/latest/examples/earthquake-clusters.html ?
