### ISSUE TITLE
Incorrect recentering in detail view maps

### ISSUE THREAD

**Issue by asaunier** [c2corg/v6_ui#612]
There's something weird with the maps embedded in the detail view pages.
See for instance: http://c2corgv6-demo.gis.internal:6555/routes/708857/fr/mont-brion-tour-du-mont-brion
=> map is no longer recentered on the vector features but a bit to the west.

When zooming in/out using the +/- buttons of the map, the features remain stuck in the bottom right corner!?

This must be quite recent because I have only noticed it this morning.

**Comment by ginold** [comment]
when I move the mouse, the markers on the map get triggered without touching them oO like 30px away from the circle.

**Comment by asaunier** [comment]
@tsauerwein do you observe the problem in your instance? If not what's the last commit of your instance? Just trying to figure out what change introduced this problem.

**Comment by tsauerwein** [comment]
Even on http://c2corgv6-demo.gis.internal:6555/routes/708857/fr/mont-brion-tour-du-mont-brion I can't observe the effects that you two are describing (with FF and Chrome).

**Comment by asaunier** [comment]
Here is what I see when loading http://c2corgv6-demo.gis.internal:6555/routes/708857/fr/mont-brion-tour-du-mont-brion

<img width="1292" alt="capture d ecran 2016-09-09 a 13 42 41" src="https://cloud.githubusercontent.com/assets/1192331/18385872/63b5a1b2-7693-11e6-93ec-861089dae345.png">

Ditto with FF and Safari on my laptop. But I don't think I have noticed it yesterday at this office with my desktop (screen size?).

**Comment by tsauerwein** [comment]
![c2c-map-issue](https://cloud.githubusercontent.com/assets/266474/18385967/f797a4fc-7693-11e6-9ff4-8fa0a760439a.png)

**Comment by tsauerwein** [comment]
I wouldn't be surprised if this is related to setting the size of viewport element (see https://github.com/c2corg/v6_ui/issues/551).

**Comment by tsauerwein** [comment]
Ok, I was able to reproduce by setting the pixel ratio to 2.

**Comment by tsauerwein** [comment]
It's because of this:
https://github.com/c2corg/v6_ui/blob/master/less/viewdetails.less#L545-L549

**Comment by fjacon** [comment]
@tsauerwein @asaunier any idea how to solve this ?

**Comment by tsauerwein** [comment]
The styling should not be set on elements that are created by OpenLayers (same problem as with #551). @ginold knows the CSS part the best.
