### ISSUE TITLE
Route creation : WP unavailable after creation (error 500)

### ISSUE THREAD

**Issue by mgerbaux** [c2corg/v6_ui#613]
When creating a route, WP that are associated during the creation process are unavailable after (500 Internal Server Error). Example : http://c2corgv6.demo-camptocamp.com/waypoints/109614/fr/habert-de-chamechaude

Edit : It seems no to be always the case...

**Comment by tsauerwein** [comment]
@asaunier The API returns the document without error (http://c2corgv6-api.demo-camptocamp.com/waypoints/109614). Something in the UI logs?

**Comment by asaunier** [comment]
There's probably an error in the mako templates/helpers. The UI apache logs say:

> [Tue Sep 13 09:23:37.936215 2016] [wsgi:error] [pid 25832] [remote 10.27.71.4:63314]   File "/var/www/vhosts/c2cassoc_c2corgv6/private/v6_ui/c2corg_ui/templates/waypoint/view.html", line 67, in render_moduleConstantsValues
[Tue Sep 13 09:23:37.936226 2016] [wsgi:error] [pid 25832] [remote 10.27.71.4:63314]     ${associated_routes_featurelist(waypoint)}
[Tue Sep 13 09:23:37.936234 2016] [wsgi:error] [pid 25832] [remote 10.27.71.4:63314]   File "/var/www/vhosts/c2cassoc_c2corgv6/private/v6_ui/c2corg_ui/templates/helpers/view.html", line 258, in render_associated_routes_featurelist
[Tue Sep 13 09:23:37.936240 2016] [wsgi:error] [pid 25832] [remote 10.27.71.4:63314]     % if 'geometry' in route and route.get('geometry').get('geom_detail'):
[Tue Sep 13 09:23:37.936251 2016] [wsgi:error] [pid 25832] [remote 10.27.71.4:63314] AttributeError: 'NoneType' object has no attribute 'get

**Comment by asaunier** [comment]
The API no longer returns the associated routes geometries for a WP document. So this problem should no longer be observed.

**Comment by stef74** [comment]
@mgerbaux please test again and close if it's ok.
