### ISSUE TITLE
icons in the image gallery have disappeared

### ISSUE THREAD

**Issue by ginold** [c2corg/v6_ui#614]
the top right buttons (close, full-screen) have disappeared, apparently a path error where the png file with the icons is no more found (http://c2corgv6.demo-camptocamp.com/static/f72c289/build/default-skin.png)

**Comment by tsauerwein** [comment]
These files are referenced from the [Photoswipe stylesheet](https://github.com/c2corg/v6_ui/blob/d5d548c7db5163e9aaf6389b76b2e70b83bf28ba/c2corg_ui/templates/base.html#L34)? I guess we have to copy the files in `node_modules/photoswipe/dist/default-skin` to the build folder. Similar to the files for moment.js and carousel, see https://github.com/c2corg/v6_ui/blob/e2ca1536e9e0c2f9dcabec37591c20c309f1b321/Makefile#L270-L277

**Comment by fjacon** [comment]
@ginold have you try @tsauerwein suggestion ?

**Comment by ginold** [comment]
@tsauerwein  i added a few lines of code that will copy the needed skins. Is it enough to only change this in the makefile and it will be executed automatically ?

**Comment by tsauerwein** [comment]
No, the new target `photoswipe-skins` that you have created must be set as the dependency of another target (for example of the target `less`). This is a good introduction for Makefiles: https://www.smashingmagazine.com/2015/10/building-web-applications-with-make/
