### ISSUE TITLE
Route creation: problem with long labels

### ISSUE THREAD

**Issue by loicperrin** [c2corg/v6_ui#617]
This problem probably comes from translation: the item "boucle avec retour au pied de la voie" hides the following item (test on medium screen: 1366x768)
![issue617](https://cloud.githubusercontent.com/assets/19718055/18454374/28962198-7944-11e6-91e2-28a2469a2282.jpg
)

**Comment by ginold** [comment]
this also happens on bigger screens. Maybe we can think of a shorter name? that would solve the problem.

**Comment by desnoes** [comment]
I also have the same issue with a large screen (can't tell you its size).
The 2 titles are identical (Type d'itinéraire) whereas the second one should be Configuration.

**Comment by loicperrin** [comment]
> The 2 titles are identical (Type d'itinéraire) whereas the second one should be Configuration.
For this, we only have to modify translation.

**Comment by loicperrin** [comment]
> Maybe we can think of a shorter name?

The problem is that we cannot control the size in the 7 languages.
Another solution would be to (I copy/paste in french):

> Il suffit de réduire la largeur prise par la rose des vents et d'augmenter le largeur des listes à droite. Puis de limiter le colonnage en 2 colonnes pour des écrans assez grands. Et enfin de modifier le display des spans de la case à cocher et du texte pour "table-cell".

Example: http://imgur.com/4OCQQAc

**Comment by shortoland** [comment]
I have modified translations in french and english. Other should follow.

**Comment by stef74** [comment]
@loicperrin @shortoland can we close ?

**Comment by loicperrin** [comment]
Thanks to translation modification, the problem is solved.
