### ISSUE TITLE
Changes required to match API new simple/advanced search attributes

### ISSUE THREAD

**Issue by asaunier** [c2corg/v6_ui#619]
This PR in the API makes the simple/advanced search + association attributes consistent: https://github.com/c2corg/v6_api/pull/391

Those changes have impacts on the UI side. Merging PR https://github.com/c2corg/v6_api/pull/391 will most likely break the UI.

The following changes are required:
* [x] Users in outings now have their id as ``document_id`` instead of ``id``
* [x] Route associations for waypoints no longer include ``geometry_detail`` => remove the associated routes geometry in WP maps (unless we can get the geometry with some other way?)
* [x] The structure for recent_outings has been changed from ``'recent_outings': {'outings': ...}}`` to ``'recent_outings': {'documents': ...}}`` (same for ``all_routes``).

**Comment by asaunier** [comment]
> Users in outings now have their id as document_id instead of id

@tsauerwein do you have examples of actions that are impacted by this change?

**Comment by tsauerwein** [comment]
> @tsauerwein do you have examples of actions that are impacted by this change?

For example here:
https://github.com/c2corg/v6_ui/blob/f72c289c22b4d85c7cbff0e82062b69b70e35a12/c2corg_ui/static/js/outingediting.js#L81
https://github.com/c2corg/v6_ui/blob/f72c289c22b4d85c7cbff0e82062b69b70e35a12/c2corg_ui/static/js/outingediting.js#L152-L155
https://github.com/c2corg/v6_ui/blob/ab598ce7865714a083df20fe1e79652c3680f4e1/c2corg_ui/tests/views/data/outing.json#L69-L76

**Comment by asaunier** [comment]
Concerning https://github.com/c2corg/v6_ui/blob/f72c289c22b4d85c7cbff0e82062b69b70e35a12/c2corg_ui/static/js/outingediting.js#L152-L155
I thought we could remove this piece of code. But if I do, ``id`` is not set in the ``associations.users`` item and the API fails saving the outing saying that
> description: "Required"
location: "body"
name: "associations.users.0.id"

Shoulldn't the API accept ``document_id`` instead of ``id`` in the outings recording requests?

**Comment by tsauerwein** [comment]
> Shouldn't the API accept document_id instead of id in the outings recording requests?

Yes, that would now be more consistent. It can be changed here:
https://github.com/c2corg/v6_api/blob/master/c2corg_api/models/schema_utils.py#L69-L70

**Comment by asaunier** [comment]
You mean changing to
```
class SchemaAssociationUser(MappingSchema):
    document_id = SchemaNode(Integer())
```
would make the trick?

**Comment by tsauerwein** [comment]
> ... would make the trick?

It *should*.
