### ISSUE TITLE
route creation: 'comparer les versions sélectionnées' does not work

### ISSUE THREAD

**Issue by desnoes** [c2corg/v6_ui#633]
Route with 2 versions: http://c2corgv6.demo-camptocamp.com/routes/736982/de/essai-alpha-3-climbing
when i clic on 'comparer les versions sélectionnées' , i have the following error message
![error message](https://cloud.githubusercontent.com/assets/19892089/18658943/66963f28-7f07-11e6-82ce-2884e2516799.jpg)

**Comment by asaunier** [comment]
The apache logs:

> [Tue Sep 20 09:22:53.892375 2016] [wsgi:error] [pid 18377] [remote 10.27.71.4:26430] mod_wsgi (pid=18377): Exception occurred processing WSGI script '/var/www/vhosts/c2cassoc_c2corgv6/private/v6_ui/apache/app-c2corg_ui.wsgi'.
[Tue Sep 20 09:22:53.893114 2016] [wsgi:error] [pid 18377] [remote 10.27.71.4:26430] Traceback (most recent call last):
[Tue Sep 20 09:22:53.893639 2016] [wsgi:error] [pid 18377] [remote 10.27.71.4:26430]   File "/var/www/vhosts/c2cassoc_c2corgv6/private/v6_ui/.build/venv/lib/python3.4/site-packages/pyramid/router.py", line 236, in __call__
[Tue Sep 20 09:22:53.893747 2016] [wsgi:error] [pid 18377] [remote 10.27.71.4:26430]     response = self.invoke_subrequest(request, use_tweens=True)
[Tue Sep 20 09:22:53.893899 2016] [wsgi:error] [pid 18377] [remote 10.27.71.4:26430]   File "/var/www/vhosts/c2cassoc_c2corgv6/private/v6_ui/.build/venv/lib/python3.4/site-packages/pyramid/router.py", line 211, in invoke_subrequest
[Tue Sep 20 09:22:53.893955 2016] [wsgi:error] [pid 18377] [remote 10.27.71.4:26430]     response = handle_request(request)
[Tue Sep 20 09:22:53.894116 2016] [wsgi:error] [pid 18377] [remote 10.27.71.4:26430]   File "/var/www/vhosts/c2cassoc_c2corgv6/private/v6_ui/c2corg_ui/caching/cacheversion.py", line 43, in __call__
[Tue Sep 20 09:22:53.894253 2016] [wsgi:error] [pid 18377] [remote 10.27.71.4:26430]     return self.handler(request)
[Tue Sep 20 09:22:53.894500 2016] [wsgi:error] [pid 18377] [remote 10.27.71.4:26430]   File "/var/www/vhosts/c2cassoc_c2corgv6/private/v6_ui/.build/venv/lib/python3.4/site-packages/pyramid/tweens.py", line 62, in excview_tween
[Tue Sep 20 09:22:53.894561 2016] [wsgi:error] [pid 18377] [remote 10.27.71.4:26430]     reraise(*attrs['exc_info'])
[Tue Sep 20 09:22:53.894681 2016] [wsgi:error] [pid 18377] [remote 10.27.71.4:26430]   File "/var/www/vhosts/c2cassoc_c2corgv6/private/v6_ui/.build/venv/lib/python3.4/site-packages/pyramid/compat.py", line 148, in reraise
[Tue Sep 20 09:22:53.894825 2016] [wsgi:error] [pid 18377] [remote 10.27.71.4:26430]     raise value
[Tue Sep 20 09:22:53.894920 2016] [wsgi:error] [pid 18377] [remote 10.27.71.4:26430]   File "/var/www/vhosts/c2cassoc_c2corgv6/private/v6_ui/.build/venv/lib/python3.4/site-packages/pyramid/tweens.py", line 22, in excview_tween
[Tue Sep 20 09:22:53.894974 2016] [wsgi:error] [pid 18377] [remote 10.27.71.4:26430]     response = handler(request)
[Tue Sep 20 09:22:53.895079 2016] [wsgi:error] [pid 18377] [remote 10.27.71.4:26430]   File "/var/www/vhosts/c2cassoc_c2corgv6/private/v6_ui/.build/venv/lib/python3.4/site-packages/pyramid/router.py", line 158, in handle_request
[Tue Sep 20 09:22:53.895124 2016] [wsgi:error] [pid 18377] [remote 10.27.71.4:26430]     view_name
[Tue Sep 20 09:22:53.895241 2016] [wsgi:error] [pid 18377] [remote 10.27.71.4:26430]   File "/var/www/vhosts/c2cassoc_c2corgv6/private/v6_ui/.build/venv/lib/python3.4/site-packages/pyramid/view.py", line 547, in _call_view
[Tue Sep 20 09:22:53.895293 2016] [wsgi:error] [pid 18377] [remote 10.27.71.4:26430]     response = view_callable(context, request)
[Tue Sep 20 09:22:53.895428 2016] [wsgi:error] [pid 18377] [remote 10.27.71.4:26430]   File "/var/www/vhosts/c2cassoc_c2corgv6/private/v6_ui/.build/venv/lib/python3.4/site-packages/pyramid/viewderivers.py", line 413, in viewresult_to_response
[Tue Sep 20 09:22:53.895481 2016] [wsgi:error] [pid 18377] [remote 10.27.71.4:26430]     result = view(context, request)
[Tue Sep 20 09:22:53.895577 2016] [wsgi:error] [pid 18377] [remote 10.27.71.4:26430]   File "/var/www/vhosts/c2cassoc_c2corgv6/private/v6_ui/.build/venv/lib/python3.4/site-packages/pyramid/viewderivers.py", line 123, in _class_requestonly_view
[Tue Sep 20 09:22:53.895633 2016] [wsgi:error] [pid 18377] [remote 10.27.71.4:26430]     response = getattr(inst, attr)()
[Tue Sep 20 09:22:53.895763 2016] [wsgi:error] [pid 18377] [remote 10.27.71.4:26430]   File "/var/www/vhosts/c2cassoc_c2corgv6/private/v6_ui/c2corg_ui/views/route.py", line 83, in diff
[Tue Sep 20 09:22:53.895816 2016] [wsgi:error] [pid 18377] [remote 10.27.71.4:26430]     return self._diff()
[Tue Sep 20 09:22:53.895926 2016] [wsgi:error] [pid 18377] [remote 10.27.71.4:26430]   File "/var/www/vhosts/c2cassoc_c2corgv6/private/v6_ui/c2corg_ui/views/document.py", line 382, in _diff
[Tue Sep 20 09:22:53.895982 2016] [wsgi:error] [pid 18377] [remote 10.27.71.4:26430]     self._get_cache_key_diff, get_etag_key=self._get_etag_key_diff)
[Tue Sep 20 09:22:53.896128 2016] [wsgi:error] [pid 18377] [remote 10.27.71.4:26430]   File "/var/www/vhosts/c2cassoc_c2corgv6/private/v6_ui/c2corg_ui/views/document.py", line 131, in _get_or_create
[Tue Sep 20 09:22:53.896171 2016] [wsgi:error] [pid 18377] [remote 10.27.71.4:26430]     page_html = render_page(*loaded_data)
[Tue Sep 20 09:22:53.896253 2016] [wsgi:error] [pid 18377] [remote 10.27.71.4:26430]   File "/var/www/vhosts/c2cassoc_c2corgv6/private/v6_ui/c2corg_ui/views/document.py", line 355, in render_page
[Tue Sep 20 09:22:53.896307 2016] [wsgi:error] [pid 18377] [remote 10.27.71.4:26430]     field_diffs = diff_documents(doc_v1, doc_v2)
[Tue Sep 20 09:22:53.896420 2016] [wsgi:error] [pid 18377] [remote 10.27.71.4:26430]   File "/var/www/vhosts/c2cassoc_c2corgv6/private/v6_ui/c2corg_ui/diff/differ.py", line 39, in diff_documents
[Tue Sep 20 09:22:53.896476 2016] [wsgi:error] [pid 18377] [remote 10.27.71.4:26430]     return _get_field_diffs(doc1, doc2)
[Tue Sep 20 09:22:53.896563 2016] [wsgi:error] [pid 18377] [remote 10.27.71.4:26430]   File "/var/www/vhosts/c2cassoc_c2corgv6/private/v6_ui/c2corg_ui/diff/differ.py", line 57, in _get_field_diffs
[Tue Sep 20 09:22:53.896605 2016] [wsgi:error] [pid 18377] [remote 10.27.71.4:26430]     if val1.get('version') != val2.get('version') and not (
[Tue Sep 20 09:22:53.896718 2016] [wsgi:error] [pid 18377] [remote 10.27.71.4:26430] AttributeError: 'NoneType' object has no attribute 'get'

**Comment by shortoland** [comment]
The issue seems to be solved

**Comment by asaunier** [comment]
I don't think so. See for instance http://c2corgv6.demo-camptocamp.com/routes/diff/736982/de/1164761/1164780

**Comment by shortoland** [comment]
Strange. I could reproduce the issue this morning on a route, but it's OK now: http://c2corgv6.demo-camptocamp.com/routes/diff/736976/fr/1164751/1164769

**Comment by asaunier** [comment]
The problem seems related to https://github.com/c2corg/v6_ui/blob/master/c2corg_ui/diff/differ.py#L57
```
            if val1.get('version') != val2.get('version') and not (
                    val1.get('geom') is None and val2.get('geom') is None):
```
in
```
        val1 = obj1.get(field)
        val2 = obj2.get(field)

        if field == 'locales':
            locale1 = val1[0]
            locale2 = val2[0]
            field_diffs += _get_field_diffs(locale1, locale2)
        elif field == 'geometry':
            if val1.get('version') != val2.get('version') and not (
                    val1.get('geom') is None and val2.get('geom') is None):
                field_diffs.append(FieldDiff('geometry', ''))
```
In the example http://c2corgv6.demo-camptocamp.com/routes/diff/736982/de/1164761/1164780 both ``val1`` and ``val2`` (values of the ``geometry`` attribute of both document versions) are ``None``.

2 questions:
* that's strange that ``geometry`` is ``None``. Or maybe there was no associated WP when the route versions have been created? Is it still possible?
* should we add a test to make sure neither ``val1`` and ``val2`` are ``None``?

@tsauerwein what do you think?

**Comment by tsauerwein** [comment]
> that's strange that geometry is None. Or maybe there was no associated WP when the route versions have been created? Is it still possible?

During the migration the default geometries for routes are only set for the latest version. So, it is possible.

> should we add a test to make sure neither val1 and val2 are None?

Sounds good.

**Comment by stef74** [comment]
@shortoland please test

**Comment by shortoland** [comment]
I made several tests, and it seems to be OK
