### ISSUE TITLE
Inversion of picto

### ISSUE THREAD

**Issue by desnoes** [c2corg/v6_ui#634]
At least in the route creation formulaire, the pictos 'Rocher haute montagne' and 'escalade' are inverted.

**Comment by asaunier** [comment]
@ginold perhaps something easy to fix? Is it simply a switch between 2 icon filenames?

**Comment by asaunier** [comment]
A fix has been applied (but won't be available in alpha3).

**Comment by stef74** [comment]
@asaunier when it's ready for test ?

**Comment by ginold** [comment]
already online

**Comment by shortoland** [comment]
Problem solved
