### ISSUE TITLE
How to bracket text in Transifex ?

### ISSUE THREAD

**Issue by shortoland** [c2corg/v6_ui#637]
Which parameters should we use in Transifex to bracket some text ?

**Comment by asaunier** [comment]
What do you mean with "bracket some text"? Could you give an example?

**Comment by shortoland** [comment]
When translating a string in Transifex, I would like it to be displayed "bracketed" in the website.

See the following Transifex comment/issue: https://www.transifex.com/camptocamp-association/c2corg_ui/translate/#fr/$/95136933?issue=yes

Is it clearer ?

**Comment by asaunier** [comment]
I still don't understand. What is "bracketed"?

**Comment by shortoland** [comment]
Oups, sorry, I made a translation mistake. I mean put in quotes.

Should be clearer now ;-)

**Comment by asaunier** [comment]
You mean "double quotes" I guess.
Have you noticed a problem with using double quotes in the translations?

**Comment by shortoland** [comment]
Not yet, but we would like to be sure of how to do that, as it seemed to be a source of problems in v5.

**Comment by asaunier** [comment]
So there is no problem yet :)
I think double quotes can be used normally.

I have updated the translations in the demo and they are displayed as expected in the editing form:
![sans titre](https://cloud.githubusercontent.com/assets/1192331/18667307/542f0cf6-7f30-11e6-9aaf-61f9bc0aa411.png)

I close the issue. Please reopen it if you noticed problems with double quotes or other characters in the translations.

**Comment by shortoland** [comment]
OK, thanks
