### ISSUE TITLE
Add a "follow" button in user profile pages

### ISSUE THREAD

**Issue by asaunier** [c2corg/v6_ui#640]
* create a button directive:
 * [x] When visitor is registered and viewing a user profile: make an API request to check if this user is followed and toggle the “Follow” button accordingly.
 * [x] When clicking the “Follow” button, make an API request to toggle the following status.
* [x] remove the "favorite" button on other pages

Relies on https://github.com/c2corg/v6_api/issues/401

**Comment by ginold** [comment]
>   remove the "favorite" button on other pages

you mean the follow button only appears on user pages?

**Comment by asaunier** [comment]
Yes

**Comment by asaunier** [comment]
It would be more relevant to create the user profile page (at least a first version with only the wiki part) before creating the "user follow" directive. See https://github.com/c2corg/v6_ui/issues/335
