### ISSUE TITLE
'Ajouter à mes favoris' does not work

### ISSUE THREAD

**Issue by desnoes** [c2corg/v6_ui#645]
When i click on 'Ajouter à mes favoris', noting happens. The color of the picto does not change.
I did not find any information in my profile.

**Comment by asaunier** [comment]
This feature is not available yet.

I close your issue since it is already described in https://github.com/c2corg/v6_ui/issues/335 and  https://github.com/c2corg/v6_ui/issues/640

**Comment by desnoes** [comment]
Maybe it could be worse to update the testbook. This test was planned for alpha 3.
