### ISSUE TITLE
Route: Impossible to add a comment

### ISSUE THREAD

**Issue by desnoes** [c2corg/v6_ui#646]
When i click on 'Publier le premier commentaire' i have the following message. Then the message disappear and nothing happens.
![comment](https://cloud.githubusercontent.com/assets/19892089/18738146/3de05094-8099-11e6-8447-8279ecb755b2.jpg)

**Comment by desnoes** [comment]
Error from my side. It seems to work (but note very easy to understand how to write the comment)

**Comment by asaunier** [comment]
I think I also had this error once.
Do you remember what you have done to get this error?

Perhaps there's a problem anyway? For instance:
> note very easy to understand how to write the comment

**Comment by desnoes** [comment]
i've got the error when i tried to add a comment on the german version of the document. When i switched to the french version i could add 2 comments. Then when i switched again to german i was able to add a comment. Maybe there is a problem when there is no comment on a doc yet and the language (profile) and the doc's language are not the same ?

**Comment by desnoes** [comment]
i tried with another document and i cannot add a comment on the french version. There is a pb with Discourse
![comment 2](https://cloud.githubusercontent.com/assets/19892089/18738364/6164b8fa-809b-11e6-9b4a-a7409937e534.jpg)

**Comment by arnaud-morvan** [comment]
For the first problem, as discourse shows as a popup, it is possible that the thread has been created, but the popup was blocked. In such case, refresh the page, and the discussion should appear (but empty). Note that you should allow popup for the domain in your browser.

**Comment by desnoes** [comment]
i have allowed popup for the V6 web site. i still have the second problem

**Comment by asaunier** [comment]
Are the problems reported in this issue limited to routes? If for any document type, it would be useful to edit the title of the issue ("Edit" button on the right).

**Comment by desnoes** [comment]
i will test for other type of documents.

----- Mail original -----
De: "Alex Saunier" <notifications@github.com>
À: "c2corg/v6_ui" <v6_ui@noreply.github.com>
Cc: "desnoes" <mathieu.desnoes@free.fr>, "State change" <state_change@noreply.github.com>
Envoyé: Jeudi 29 Septembre 2016 11:16:17
Objet: Re: [c2corg/v6_ui] Route: Impossible to add a comment (#646)



Are the problems reported in this issue limited to routes? If for any document type, it would be useful to edit the title of the issue ("Edit" button on the right).

**Comment by asaunier** [comment]
I think you won't be able to test because we have shut the forum down on the demo. It was probably responsible for load problems with the dev server...

**Comment by desnoes** [comment]
Tell me when i could test.

----- Mail original -----
De: "Alex Saunier" <notifications@github.com>
À: "c2corg/v6_ui" <v6_ui@noreply.github.com>
Cc: "desnoes" <mathieu.desnoes@free.fr>, "State change" <state_change@noreply.github.com>
Envoyé: Jeudi 29 Septembre 2016 12:13:05
Objet: Re: [c2corg/v6_ui] Route: Impossible to add a comment (#646)



I think you won't be able to test because we have shut the forum down on the demo. It was probably responsible for load problems with the dev server...

**Comment by arnaud-morvan** [comment]
> we have shut the forum down on the demo
This should be the source of the second problem as the message said "error with discourse".

**Comment by stef74** [comment]
what is the status on this issue ?

**Comment by arnaud-morvan** [comment]
Note that I've just stopped forum.demov6.camptocamp.org, to restore the new imported database.
Forum will be restarted as soon as database restore finish.

It is already needed to allow popups for the domain.

I do not see any reason to keep this issue open.
