### ISSUE TITLE
not all wp types listed during creation

### ISSUE THREAD

**Issue by ginold** [c2corg/v6_ui#650]
[ ] Not listed during WP creation: Confluent, Falaise, Glacier, Rimaye, Accès/parking, Crevasse

**Comment by asaunier** [comment]
Access actually exists: https://github.com/c2corg/v6_common/blob/master/c2corg_common/attributes.py#L26

"parking" = "access"

All the other WP types are no longer needed.
Have you seen them mentioned somewhere?

**Comment by asaunier** [comment]
> Have you seen them mentioned somewhere?

Probably here: https://github.com/c2corg/v6_ui/issues/390#issuecomment-246752985
