### ISSUE TITLE
Topoguide's url

### ISSUE THREAD

**Issue by shortoland** [c2corg/v6_ui#656]
Following Charles Dixon's tests:

url for topoguide is: http://c2corgv6.demo-camptocamp.com/routes#bbox=-857237,3946514,1657236,7253485

- Charles thinks that the value for bbox is not pertinent

- Indeed, modifying this value doesn't change anything

**Comment by asaunier** [comment]
Hi @shortoland 

What are those Charles Dixon's tests?

I do assure you that the ``bbox`` parameter is relevant and useful (it's the extent of the map, used as a geographical filter). It changes when you pan or zoom the map. If you reload the page, its value is taken into account to set the map extent.
Users are not supposed to change the parameter by hand even though it is possible (but you have to provide relevant values which is not that simple).

**Comment by shortoland** [comment]
@asaunier This was more a question than an issue.
More informations about Charles' tests:
http://www.camptocamp.org/forums/viewtopic.php?pid=2213805#p2213805
