### ISSUE TITLE
Advanced search pages in mobile screens

### ISSUE THREAD

**Issue by asaunier** [c2corg/v6_ui#657]
As for now, the advanced search pages are hard to use with a smartphone because there are too many elements for such a small screen and the elements are too small making them barely usable:
- [x] it would be better to show the sections separately:
  - search results (cards) by default with buttons to open the filters and the map
  - map (full screen? see https://github.com/c2corg/v6_ui/issues/428) with a button to close the map and go back to the results
  - filters: all filters at once with a button to show the results or clear the filters (not primary filters only until the user has clicked "all filters")
- [x] horizontal scrolling should be neutralized, especially in the filters section because it conflicts with the use of the horizontal double-sliders (when trying to move the slider's handles, the full section is scrolled horizontally)
- [x] All filters should be displayed on a dedicated line (one filter per line). As for now the primary filters (generally 3) are displayed on the same line which makes it harder to use them (whereas they are the main filters!).
- [x] Activities cannot be selected anymore once you scroll down the list.

**Comment by stef74** [comment]
@asaunier what is the remaining job for beta ?

**Comment by asaunier** [comment]
Nothing has been done yet.

**Comment by stef74** [comment]
In landscape mode advanced search is not usable 
![img_0763](https://cloud.githubusercontent.com/assets/3962997/19640035/3cbf6a0a-99db-11e6-8a1e-b7eebc464c1e.PNG)

**Comment by stef74** [comment]
@ginold as you mentionned in #428 a simple way is on mobile 

> Maybe we could add a switch to hide/show the map and display only the cards by default?

**Comment by ginold** [comment]
@asaunier what do you think of this issue as #799 has been merged?

**Comment by asaunier** [comment]
I think it's better to keep it open until further testing is done by the association.

**Comment by stef74** [comment]
When is avalaible on demo server ?

2016-11-02 9:35 GMT+01:00 Alex Saunier <notifications@github.com>:

**Comment by asaunier** [comment]
No idea. @fjacon @arnaud-morvan ?

**Comment by stef74** [comment]
Great Job !
