### ISSUE TITLE
X-Frame-Options warning

### ISSUE THREAD

**Issue by asaunier** [c2corg/v6_ui#663]
Chrome console complains that

```
X-Frame-Options may only be set via an HTTP header sent along with a document. It may not be set inside <meta>.
```

Seems related to https://github.com/c2corg/v6_ui/blob/master/c2corg_ui/templates/base.html#L25
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Frame-Options

Why do we need this meta?

**Comment by tsauerwein** [comment]
If I get it right, we would have to set `X-Frame-Options` in the Pyramid view instead of in the HTML?

This was added in https://github.com/c2corg/v6_ui/pull/486.

**Comment by stef74** [comment]
X-Frame-Option is deprecated the could way to prevent framing is to use CSP (not supported by old browser ...)

**Comment by asaunier** [comment]
According to https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Frame-Options

> The X-Frame-Options HTTP response header can be used to indicate whether or not a browser should be allowed to render a page in a <frame>, <iframe> or <object> . Sites can use this to avoid clickjacking attacks, by ensuring that their content is not embedded into other sites.

> There are three possible directives for X-Frame-Options:
X-Frame-Options: DENY
X-Frame-Options: SAMEORIGIN
X-Frame-Options: ALLOW-FROM https://example.com/

It should be passed as an HTTP header, not as an HTML meta. In apache:
```
Header always append X-Frame-Options SAMEORIGIN
```
in nginx:
```
add_header X-Frame-Options SAMEORIGIN;
```

Please note that the UI also uses iframes for the ad banners (same domain iframes) and - I think - for authenticating to discourse.

**Comment by tsauerwein** [comment]
Is this header even needed? It was added in https://github.com/c2corg/v6_ui/commit/09f45d0a6f0ead82474e737abbfa75a10957fe51 to show the Discourse comments. But why would we have to set `X-Frame-Options` to `allow` for that?!

I can't test at the moment, because Discourse seems to be down. But I would propose to remove this tag to get rid of the embarrassing console error.

**Comment by asaunier** [comment]
OK for me if @arnaud-morvan agrees.

**Comment by arnaud-morvan** [comment]
www.demov6.camptocamp.org host is already allowed in discourse customize external integration settings, for the comments category.

GET ``http://forum.demov6.camptocamp.org/embed/comments?topic_id=172053``
returns ``X-Frame-Options:ALLOWALL``

I  do not reproduce the console log, but adding X-Frame-Options in parent page should have no effect.
