### ISSUE TITLE
Incorrect image size displayed in image detail view pages

### ISSUE THREAD

**Issue by asaunier** [c2corg/v6_ui#670]
It seems that the original file is displayed in the image detail view pages: that's a problem, especially if the original image is quite big (>1 MB)
* [x] the "BI" image should be displayed instead
* [x] the original image is displayed (direct link - not in the current page) when clicking on the BI image.

As in v5: http://www.camptocamp.org/images/807159/fr/cabane-de-graetli-chocolat-cali-sieste-et-le-papa-qui-s-impatiente-sachant-la-journee-est-encore-lon

**Comment by asaunier** [comment]
* [ ] Also it seems that thumbnails are square again!? I thought we used thumbnails keeping the original image ratio? Anyway those distorted square images are not OK. See also https://github.com/c2corg/v6_images/issues/11
* [ ] By the way I notice that those square thumbnails are 120x120px whereas they are displayed in 150x150 in the carousel => either the carousel is too big or the thumbnails are too small.

**Comment by ginold** [comment]
>  the "BI" image should be displayed instead

:+1:  but I think a BI should be bigger than ~800x600 pixels and MI surely bigger than ~250x180 pixels!!

**Comment by ginold** [comment]
>  either the carousel is too big or the thumbnails are too small.

i'd say the thumbnails are too small and their quality is poor - even with 120x120 they should look more detailed! I would make them slightly bigger - 200x200 ?

**Comment by asaunier** [comment]
I don't understand. Do we really use square thumbnails ("SI" images)? I thought carousel thumbnails kept the proportions of original images? Don't they?

**Comment by asaunier** [comment]
Please don't mark an issue as fixed until the related PR is merged.

**Comment by ginold** [comment]
Gallery thumbnails -> square SI (natural 120x120 stretched up to 150x150)
click on thumbnail -> open gallery with BI

**Comment by asaunier** [comment]
OK thanks.

> Gallery thumbnails -> square SI (natural 120x120 stretched up to 150x150)

It means the thumbnails should be regenerated at the correct size. See https://github.com/c2corg/v6_images/issues/6
