### ISSUE TITLE
Is is really useful to build/test with Node 4 and Node 6 ?

### ISSUE THREAD

**Issue by arnaud-morvan** [c2corg/v6_ui#674]
IMHO, as this is not a framework, it add not necessary complexity in travis configuration, and not necessary differences between projects deployment scripts.

**Comment by tsauerwein** [comment]
For me it would be ok to say we are using Node 6 for the project, and only to test with Node 6 if it simplifies things.

**Comment by asaunier** [comment]
+1

**Comment by asaunier** [comment]
What would it imply?
Removing the following lines in ``.travis.yaml``:
* https://github.com/c2corg/v6_ui/blob/master/.travis.yml#L21
* https://github.com/c2corg/v6_ui/blob/master/.travis.yml#L56-L62

That's it?
