### ISSUE TITLE
Missing criteria on WP's search

### ISSUE THREAD

**Issue by shortoland** [c2corg/v6_ui#679]
Not sure this is an issue, but at least a question.

When searching a WP that has several attributes, it's sometimes not possible to filter on those.

For example , when searching a hut, I cannot filters on the following criteria:
"nombre de places hors gardiennage"
"matelas hors gardiennage"
"couvertures hors gardiennage"
"gaz hors gardiennage"
"chauffage hors gardiennage"
In that case, I think it's mandatory to be able to filter on those parameters.

**Comment by asaunier** [comment]
Are you sure those criterias appear in the google sheet describing the search criterias for huts?

**Comment by stef74** [comment]
https://docs.google.com/spreadsheets/d/1LTE1UIjsDTdZauDgR4rKe2UCtXF6LG-ELH53Qwy1nmI/edit#gid=985873791

**Comment by shortoland** [comment]
@asaunier I would say yes. But I did not find the detailed legend for criteria in the google doc.

**Comment by asaunier** [comment]
Those attributes are not to be used has filter criterias according to https://docs.google.com/spreadsheets/d/1LTE1UIjsDTdZauDgR4rKe2UCtXF6LG-ELH53Qwy1nmI/edit#gid=1455968768 which is the revised document we used.

Anyway who need to search a hut filtering on the blanket info? That kind of information is a secondary information that you use to adapt your gear after selecting the hut.

**Comment by asaunier** [comment]
@shortoland I close the issue because there's nothing to do about it, as I have explained in my previous comment. Anyway I think it is very low priority.
