### ISSUE TITLE
Map problems with IE

### ISSUE THREAD

**Issue by asaunier** [c2corg/v6_ui#685]
Testing IE11/Win7 (with Browserstack) the following problems are observed in maps:
## Detail view page
- [ ] except OSM (because it's the default one?), no other baselayer (Bing, Esri, IGN, Swisstopo) can be loaded => the map remains blank (it seems there is a JS error that makes the switch crash - "indexSizeError")
- [ ] SVG icons are not displayed on the map (one only sees the white background disk), whatever the baselayer. By the way only one white disk is shown even though there should be several features on the map
  ![sans titre](https://cloud.githubusercontent.com/assets/1192331/19105493/82c900b8-8ae2-11e6-9160-db2d36634a66.png)
## Advanced search

The advanced search page seems to work, taking into account the map extent (for instance when zooming in) but:
- [ ] result icons are not shown on the map, only one white background dishk (probably same error than above)
- [ ] impossible to change the baselayer
- [ ] the map tiles are initially loaded as expected but when the mouse cursor hovers cards in the result list, they are kind of zoomed out as in the following screenshot:
  ![sans titre](https://cloud.githubusercontent.com/assets/1192331/19105713/bc2229f6-8ae3-11e6-84f4-35072dcd6a53.png)

**Comment by tsauerwein** [comment]
Some of the map problems could be related to https://github.com/c2corg/v6_ui/issues/612

**Comment by asaunier** [comment]
Changing the baselayer in the editing form maps works as expected.

**Comment by asaunier** [comment]
Tested using Browserstack.com:
* OK with Edge 14 and 13 on Windows 10.
* KO with IE 11 on Win 8.1
* but OK on IE 10 on Win 8 !?

**Comment by stef74** [comment]
KO on IE 11 on win 7

**Comment by stef74** [comment]
Since 01/16 IE 11 about 7% of global traffic but high decreasing since september. Now is 30K sessions/Month

**Comment by ginold** [comment]
Loading the map on IE gives the following error in the console :` SCRIPT5022: IndexSizeError`

**Comment by stef74** [comment]
In beta IE is not used ... so we can explain to user than IE not working and use an alternate browser ...
