### ISSUE TITLE
Minor problems with recent changes

### ISSUE THREAD

**Issue by asaunier** [c2corg/v6_ui#687]
@ginold I have noticed a few minor problems with recent changes (I should have noticed them while reviewing :P):
* [x] instead of introducing some new strings for the tooltip of the "add" buttons in the index pages like "Add a new route" (see https://github.com/c2corg/v6_ui/blob/master/c2corg_ui/templates/route/index.html#L40) it would be better to reuse the string already available like "Create a new route" https://github.com/c2corg/v6_ui/blob/db741a204caa23ff281bfc551e6be937f95ac847/c2corg_ui/static/partials/suggestions/empty.html#L3 => always reuse strings whenever possible, it saves some work for translators and some weight in the translations files.

I have also noticed some incorrect strings to translate, pushed to Transifex 
* [x] incorrect/unneeded "translate" directive at https://github.com/c2corg/v6_ui/blob/71c0ef6ebe251a33bfdcd95d5a1bfd06d79f96cc/c2corg_ui/static/partials/slideinfo.html#L40-L42 (by the way do we really need ``<a>`` tags in a ``button``?)
* [x] incorrect/unneeded "translate" directive at https://github.com/c2corg/v6_ui/blob/master/c2corg_ui/templates/index.html#L33

* [x] Note sure it is a problem but I notice that linebreaks in translated strings are pushed to Transifex as well. That's probably a bit confusing. I guess we should get rid of them: https://github.com/c2corg/v6_ui/blob/master/c2corg_ui/templates/index.html#L19-L21
![sans titre](https://cloud.githubusercontent.com/assets/1192331/19109014/b526a978-8af3-11e6-9aa3-74fafa9534a6.png)

**Comment by ginold** [comment]
>  by the way do we really need <a> tags in a button?

one doesn't have <a> tag because it's a `protected-btn-directive` so it takes care of redirecting, whereas the other one is a normal link. If i wanted to write 1st <button> and 2nd only <a> i would have to style them accordingly.

**Comment by asaunier** [comment]
OK, thanks for the explanation :)
