### ISSUE TITLE
Problem with scroll down in advanced search pages

### ISSUE THREAD

**Issue by shortoland** [c2corg/v6_ui#692]
I am using Windows 10 and Firefox 49.0.1.

I am on the route search page, I select "VTT" activity, then click on "Tous les filtres":
http://c2corgv6.demo-camptocamp.com/routes#bbox=-857237,3946514,1657236,7253485&act=mountain_biking

The criteria are displayed, but I am unable to go down and click "Voir les résultats": when scrolling down, the page automatically goes up again.

**Comment by asaunier** [comment]
Is this problem observed only for moutain biking routes or also with other activities or document types (waypoints? outings? etc.)?

**Comment by shortoland** [comment]
The problem is observed for all activities having too many filters that cannot be displayed on the screen (with need to scroll down).

This concerns: "Neige, glace et mixte", "Rocher Haute Montagne", "Escalade" and "Cascade".

**Comment by asaunier** [comment]
Seem to be fixed by https://github.com/c2corg/v6_ui/pull/799
