### ISSUE TITLE
Issue when searching a VTT route

### ISSUE THREAD

**Issue by shortoland** [c2corg/v6_ui#693]
I am on the route search page and select VTT activity.

There is no result, whereas there are some VTT routes in the database:

![image3](https://cloud.githubusercontent.com/assets/20488365/19117556/b26d8726-8b19-11e6-8b9e-cdfa8c67bf95.png)

It seems to be OK with other activities.

**Comment by asaunier** [comment]
The synchronisation script (that propagates changes made to the document to the search engine) has been turned off on the demo (because of load problems). I have relaunched the scripts and now there are results when filtering on mountain biking.

**Comment by shortoland** [comment]
@asaunier OK, it's much better, I close the ticket.
