### ISSUE TITLE
Delete association between an outing and a route

### ISSUE THREAD

**Issue by shortoland** [c2corg/v6_ui#694]
I go on the outing page http://c2corgv6.demo-camptocamp.com/outings/723667/fr/pic-de-l-affron-depuis-le-refuge-wallon, entered by BenB.

I click on the trash included in the corresponding route card:

![image4](https://cloud.githubusercontent.com/assets/20488365/19118859/12fd5fa4-8b1e-11e6-9555-01e8585f3b55.png)

After confirmation, I can delete the association between the route and the outing:

![image5](https://cloud.githubusercontent.com/assets/20488365/19118895/37f6d4ca-8b1e-11e6-8b31-27529ef0c3e2.png)

I don't think it's normal I am allowed to do that.

**Comment by asaunier** [comment]
Indeed, only moderators (and associated users) should be able to edit or remove an association in an outing document.

You have no moderator permissions since the "edit" button does not appear on the right side of the page.

**Comment by tsauerwein** [comment]
> Indeed, only moderators (and associated users) should be able to edit or remove an association in an outing document.

I don't think the API enforces this constraint at the moment.

**Comment by asaunier** [comment]
Then we should create an API issue too.
It's not consistent to prevent people to edit the outing but to let them change the associations.

* [ ] By the way the "add association" tool should be shown in personal documents (as outings) only for moderators and associated users.

**Comment by loicperrin** [comment]
2 questions:
- If I am the author of the outing, it is authorized to desassociate the last associated route? I think it should not
- Are the moderators permissions available in demo? In fact I have modified an outing created by Tintin, but maybe it is due to moderators rights (and so it would be correct)

**Comment by asaunier** [comment]
> If I am the author of the outing, it is authorized to desassociate the last associated route? I think it should not

Why?

> Are the moderators permissions available in demo?

Yes

**Comment by tsauerwein** [comment]
> Then we should create an API issue too.

See https://github.com/c2corg/v6_api/issues/414

**Comment by loicperrin** [comment]
> Why?

Because the outing has no more associated route. It is the same kind of problem as for routes when we delete the last associated WP.

**Comment by asaunier** [comment]
> Because then the outing has no more associated route. It is the same kind of problem as for routes when we delete the last associated WP.

Right!

**Comment by ginold** [comment]
what we can do for now is to not let the user to delete the last associated route, because an outing requires at least one.

**Comment by stef74** [comment]
this issue is tagged pull request ready, normal ?

**Comment by asaunier** [comment]
> this issue is tagged pull request ready, normal ?

I don't know. Perhaps @ginold meant that a PR for this issue was ready: https://github.com/c2corg/v6_ui/pull/726 Since the PR has been merged 10 days ago, perhaps the issue should be tagged "ready for demo" (or even "fixed and ready to be tested" since it is probably available in the demo).

**Comment by asaunier** [comment]
Closing this issue because changes have been made in the UI and the API to give access to association addition/removal only to the authorized users.
