### ISSUE TITLE
Incorrect georef is added to uploaded images

### ISSUE THREAD

**Issue by asaunier** [c2corg/v6_ui#696]
All images recently uploaded to the demo (including simple screenshots like http://c2corgv6.demo-camptocamp.com/images/737030/fr/asdads) surprisingly have a geometry, always set to some point in Wallis!

When uploading the image above I have just typed a random title and pick "collaborative" as type. That's all.

Where does this geometry come from?

**Comment by ginold** [comment]
because of the hard-coded thing in HTML :

```
<%block name="moduleConstantsValues">
  module.value('mapFeatureCollection', {
    "type": "FeatureCollection",
    "properties": {},
    "features": [{
      "type": "Feature",
      "geometry": {"type": "Point", "coordinates": [901624.4172679152, 5858812.695644485]},
      "properties": {
        "title": ${dumps(locale['title']) | n},
        "lang": "${locale['lang']}",
        "documentId": ${image['document_id']},
        "module": "images"
      }
    }]
  });
```

I remember I just wanted to see if it worked and forgot to remove it :P

**Comment by asaunier** [comment]
OK, could you remove this piece of code please? :)
