### ISSUE TITLE
Failed during upload of an image

### ISSUE THREAD

**Issue by HSERGERAERT** [c2corg/v6_ui#698]
I can't load any image to a route. I use Google Chrome, recent version (53.xxx)

Steps :
1/ I select a route from the topoguide, for instance http://c2corgv6.demo-camptocamp.com/routes/569329/fr/presles-buis-papilusion
2/ I click on button "Insert images", in french "Ajouter des images", I get the screen drop and drag
3/ I place one image from a local image on my computer, I get the following screen (inserted)
4/ I register and then I get the error message "Failed during saving"
5/ I can't add any other image for drop and drag

![image_load](https://cloud.githubusercontent.com/assets/20357260/19146807/865faef6-8bb5-11e6-9b2b-f71046837214.JPG)

**Comment by arnaud-morvan** [comment]
For now there an error on the API side if title is empty.
We have planned to allow images without title but this is not done for now.
Related with https://github.com/c2corg/v6_api/issues/399

**Comment by asaunier** [comment]
> For now there an error on the API side if title is empty.

OK that's the probably the problem. I get the same error if no title is provided. But works as expected if a title (and a type) is provided.

**Comment by ginold** [comment]
It would be nice to indicate which image exactly needs a type when clicking on save.

**Comment by asaunier** [comment]
> It would be nice to indicate which image exactly needs a type when clicking on save.

It would be simpler (and more user-friendly) to set a default type for all images. In v5 the default type is the type of the document to which you push the image.

**Comment by HSERGERAERT** [comment]
Unfortunately this is not due to a missing title or activity or ...
I made a new test and put the missing information, same result, "Failed during saving"
![image_load_2](https://cloud.githubusercontent.com/assets/20357260/19150207/dde52844-8bc5-11e6-8e10-3a363f4e39f2.JPG)

**Comment by asaunier** [comment]
The demo is being upgraded (new migration of the DB, which is not complete).
I also had that error message when testing a few minutes ago on http://c2corgv6.demo-camptocamp.com/routes/569329/fr/presles-buis-papilusion

But it's OK on http://ui.alpha3.demov6.camptocamp.org/routes/569329/fr/presles-buis-papilusion

**Comment by ginold** [comment]
>  It would be simpler (and more user-friendly) to set a default type for all images. In v5 the default type is the type of the document to which you push the image.

I will make a PR with this proposition!

**Comment by HSERGERAERT** [comment]
I agree with the default type, the default type like "divers" should correspond to an image not displayed on the home.

**Comment by ginold** [comment]
as far as I know, there is no type "divers", there are :
```
    'collaborative',
    'personal',
    'copyright'
```

**Comment by asaunier** [comment]
@HSERGERAERT I think you're confounding "type" and "categories" attributes.
"categories" is not a mandatory attribute, we don't need to set a default category.

@ginold 
Please note that only moderators can set an image type to "copyright" (mainly used for book covers). Standard users may only choose between "personal" and "collaborative".

**Comment by HSERGERAERT** [comment]
The loading of image is still an issue even with a title, a category, and activity and type.
On server test http://c2corgv6.demo-camptocamp.com/ , it doesn't work "Failed saving the changes"
On server test http://c2corgv6.demo-camptocamp.com/ it works

I see one more difference between the two environment, on server http://c2corgv6.demo-camptocamp.com/ the type is set with a default value.

**Comment by asaunier** [comment]
That looks like a weird and tricky issue because I have no problem uploading an image either on http://c2corgv6.demo-camptocamp.com/routes/569329/fr/presles-buis-papilusion or http://ui.alpha3.demov6.camptocamp.org/routes/569329/fr/presles-buis-papilusion

In both cases I have just set the a dummy title and make sure the image type was set (either default or not). Using Firefox 49 or Chromium Version 53.0.2785.143 Built on Ubuntu , running on Ubuntu 16.04 (64-bit)

**Comment by asaunier** [comment]
Tested at home with Chrome 53 on MacOS X => no problem when uploading images on
http://c2corgv6.demo-camptocamp.com/routes/569329/fr/presles-buis-papilusion or http://ui.alpha3.demov6.camptocamp.org/routes/569329/fr/presles-buis-papilusion

**Comment by HSERGERAERT** [comment]
Bonjour,
pouvez-vous tester tous les trois le chargement d'une image sur le document
http://c2corgv6.demo-camptocamp.com/routes/569329/fr/presles-buis-papilusion

En mettant un titre "Photo test", une activité "Escalade", une catégorie
"Action" et un type "Personnel" et dire si ça marche ou pas pour vous.
Moi ça ne marche pas.
Hervé



2016-10-13 0:55 GMT+02:00 Alex Saunier <notifications@github.com>:

**Comment by HSERGERAERT** [comment]
Salut
ça marche pour moi… une fois qu'on s'est déconnecté/reconnecté. Sinon, ça
envoyait effectivement un "failed saving change"


2016-10-13 8:20 GMT+02:00 Hervé SERGERAERT <herve.sergeraert@gmail.com>:

**Comment by HSERGERAERT** [comment]
OK, maintenant ça marche pour moi aussi ! Il fallait se déconnecter et se
reconnecter.
Je le note dans le ticket.
Bien vu Martin !

2016-10-13 8:50 GMT+02:00 Martin Gerbaux <martin.gerbaux@camptocamp.org>:

**Comment by HSERGERAERT** [comment]
The issue can be closed, a disconnect and reconnect was required to run correctly.
Ticket is closed.
