### ISSUE TITLE
Shared config/attributes between the UI and the API

### ISSUE THREAD

**Issue by asaunier** [c2corg/v6_ui#7]
Some config/attributes are shared between the UI and the API. For instance:
* cultures/langs
* activities
* waypoint_types
* ???

Perhaps also the attributes of the documents, their type and if they are mandatory (for validating in the UI).

As for now we have:
https://github.com/c2corg/v6_ui/blob/master/c2corg_ui/attributes.py
https://github.com/c2corg/v6_api/blob/master/c2corg_api/attributes.py

@tsauerwein suggested that
> We could have a project "c2corg_common" or "c2corg_constants" in which all constants, attributes, etc. are defined. This project would be a dependency of the api and ui project.

**Comment by tsauerwein** [comment]
I think it would be a good idea to have this *common* project. Could you create a new repository (c2corg/v6_common)?

**Comment by asaunier** [comment]
Done: https://github.com/c2corg/v6_common

**Comment by tsauerwein** [comment]
Great, thanks. I will create this project once https://github.com/c2corg/v6_api/pull/44 is merged.
