### ISSUE TITLE
Prefer standard javascript over goog

### ISSUE THREAD

**Issue by gberaudo** [c2corg/v6_ui#70]
Some of the functions provided by goog already exist in the ES5 standard. For example:
- Function.bind;
- Array.forEach.

These goog functions allowed to support browsers that are now deprecated and that we do not intend to support. Because we don't need these functions and also because standard code is more maintanable, when we have a choice we should prefer standard javascript.

**Comment by asaunier** [comment]
Is this issue still valid?
I would it's rather something to keep in mind when writing JS code then an action to do (unless we still have code to convert?).

**Comment by gberaudo** [comment]
Yes, we still have a handful of them.

**Comment by asaunier** [comment]
I close this issue because it's more a coding-standard recommendation that must be kep in mind than an issue (else it will stay open forever).
