### ISSUE TITLE
Issue with route display

### ISSUE THREAD

**Issue by shortoland** [c2corg/v6_ui#707]
In the route search page, I select activity "Cascade de glace".

Route "Directocouilles" is displayed, whereas it hasn't the "Cascade de glace" icon:

![image13](https://cloud.githubusercontent.com/assets/20488365/19185035/265c7e28-8c80-11e6-9803-a4abba3fbaf5.png)

Then I click on this route: both icons are displayed there:

![image14](https://cloud.githubusercontent.com/assets/20488365/19185064/43d52568-8c80-11e6-8d77-052aa80a396d.png)

So, there is an information mismatch between those two sources.

**Comment by ginold** [comment]
Hard to tell what is going on because there are both activities in my instance of the application. Maybe the demo is not 100% up to date.
![Uploading Screenshot from 2016-10-07 13-11-50.png…]()

**Comment by asaunier** [comment]
I have updated the demo yesterday evening.
Perhaps it's related to the syncer scripts? They were down until this morning (the demo database has been recreated yesterday and I had stop them during the process).

**Comment by shortoland** [comment]
Looks good now, I think I can close the ticket. I will open a new one in case it happens again.
