### ISSUE TITLE
Parsing of [img] tags

### ISSUE THREAD

**Issue by asaunier** [c2corg/v6_ui#712]
c2corg v5 uses a special [img] tag:
* a filename is never provided
* always based upon the image document_id => this way when the image is modified (title, new file, etc.), it's always up-to-date when embedded in documents.
* it's possible to specify what size of the image to use as well as alignment params

See the tag usage at http://www.camptocamp.org/articles/151910/fr/aide-mise-en-forme-du-texte#image

The tricky part of this tag is to convert the image id into a real image URL. This is discussed in this comment+following ones: https://github.com/c2corg/v6_ui/issues/131#issuecomment-245639695

Part of issue https://github.com/c2corg/v6_ui/issues/131

**Comment by asaunier** [comment]
My opinion on the approach to use (to be discussed!):

> Advantages of using some kind of image proxy on the API side could be:
* the code would be simpler => probably some sqlalchemy on the API side (+some caching!?) and a quite simple tag conversion in the UI, a bit like https://github.com/c2corg/v6_ui/blob/master/c2corg_ui/format/wikilinks.py
* if the image is updated (new filename but same document id), the UI part is still valid and its cache does not have to be invalidated to take into account the new filename => only the output of the proxy service on the API side has to be refreshed.

**Comment by arnaud-morvan** [comment]
I think proxy service in API is the better way too. I will start working on it ASAP.

**Comment by arnaud-morvan** [comment]
Done for the API proxy service, could use [api_url]/images/proxy/{document_id} to get a redirection to image.
No option for now concerning the resized images, proxy redirect to original image.

**Comment by asaunier** [comment]
> No option for now concerning the resized images, proxy redirect to original image.

That's obviously a problem. We can't ask for the original image when only a thumbnail is embedded in the document :P 

https://github.com/c2corg/v6_api/pull/422#issuecomment-252650951
> no cache for now, not sure this is necessary.

Why?
Document detail views are actually cached, as well the API request to build them. Why not caching the API requests that are used to display an image? If not, whenever someone displays an article with embedded images, API/DB requests will be done to get the image filenames. A bit a pity, don't you think?

**Comment by tsauerwein** [comment]
Views that use the application cache make a query to the database to get the current cache version of a document, for every request.

In this case, only one query is made to fetch a single column. When using the cache, you would first make a query to get the cache version. And if there is no entry in the cache, you would make a second query to get the filename. So, using the application cache is not really beneficial.

But we should check that Varnish caches requests to this view for a small amount of time.

**Comment by asaunier** [comment]
OK, makes sense then. Thanks for the explanation.

**Comment by asaunier** [comment]
Concerning the image size, please note that in v5, embedded images generally use the MI format as default. See for instance http://www.camptocamp.org/articles/763495/fr/changer-d-approche-10-idees-de-sortie-dans-la-metro-grenobloise

Since we consider enlarging MI images to 800px (see https://github.com/c2corg/v6_images/issues/5), this format would no longer be relevant for embedded images.
We should rather user SI images (thumbnails) instead as default.

**Comment by arnaud-morvan** [comment]
If we only need the SI image, I can change the redirection.
Else I can add a size parameter in image/proxy route.

**Comment by asaunier** [comment]
According to http://www.camptocamp.org/articles/151910/fr/aide-mise-en-forme-du-texte#image
> Il est également possible d'afficher l'image en taille réelle grâce au mot-clé "big" : [img=identifiant position big /]

> Else I can add a size parameter in image/proxy route.

+1

**Comment by arnaud-morvan** [comment]
Now the defaut is the original image, could get resized image with for example : /images/proxy/5555?size=BI
