### ISSUE TITLE
Cannot upload images to owned outing

### ISSUE THREAD

**Issue by ginold** [c2corg/v6_ui#715]
the "add images" button does not appear even though I'm the author of the outing

**Comment by asaunier** [comment]
@shortoland could you test?
For me it's OK, I see the button in my outings. But I have moderator rights, so I see the button in all outings :P

**Comment by ginold** [comment]
I tried to work this out and there is a problem with `Authentication.hasEditRightsOuting_` function - the users that are sent to the functions are 1 time out of 2 `undefined` and at the end the functions returns false :confused:

**Comment by asaunier** [comment]
I have suggested a fix with https://github.com/c2corg/v6_ui/pull/819 => the permissions for using the "edit" button are the same than for using the "image upload" button. If you can edit the page, you can also add images.
