### ISSUE TITLE
Changing image type in image editing form

### ISSUE THREAD

**Issue by asaunier** [c2corg/v6_ui#718]
(@shortoland or someone else: could you confirm the comments below, I have moderator rights, thus can do things standard users cannot)

We have to make sure that only moderators can change the image type of an already existing image.
Other contributors may only change their personal image to collaborative (they cannot change their collaborative images to personal).

Perhaps this restriction should also be implemented (if not already) in the API.

**Comment by tsauerwein** [comment]
> Perhaps this restriction should also be implemented (if not already) in the API.

There is some kind of check:
https://github.com/c2corg/v6_api/blob/master/c2corg_api/views/image.py#L137-L147

Not sure if this is what you want?

**Comment by asaunier** [comment]
That's what I was looking for.

By the way it makes me realize that contributors may change their own "personal" images to make them "collaborative" => I have updated my initial comment.

**Comment by tsauerwein** [comment]
> By the way it makes me realize that contributors may change their own "personal" images to make them "collaborative"

That makes sense. But it does not seem to work with the current logic in the API.

**Comment by asaunier** [comment]
Mmm, yes, according to the code you have pointed, users may change their own collaborative images to personal, right?

**Comment by tsauerwein** [comment]
> Mmm, yes, according to the code you have pointed, users may change their own collaborative images to personal, right?

Creators can change from "personal" to "collaborative". But it seems they can not change their own images from "collaborative" back to "personal".

**Comment by asaunier** [comment]
> Creators can change from "personal" to "collaborative". But it seems they can not change their own images from "collaborative" back to "personal"

That's what we want!

**Comment by shortoland** [comment]
When trying to create a new outing or adding images, I have the following error message: "Failes saving the changes"

![image1](https://cloud.githubusercontent.com/assets/20488365/19285382/092a3cf0-8ffa-11e6-93cc-660f4103e750.png)

**Comment by ginold** [comment]
As for now, the title is required and not filling the field will throw this error.

**Comment by asaunier** [comment]
> When trying to create a new outing or adding/modifying an image, I have the following error message: "Failed saving the changes"

Already reported at https://github.com/c2corg/v6_ui/issues/698
@ginold has given the explanation.

**Comment by shortoland** [comment]
I also tried filling the title, and I tried again right now, and I confirm the problem.

**Comment by ginold** [comment]
The last thing you could try is to log out and log in back, then upload the image :(

**Comment by asaunier** [comment]
> The last thing you could try is to log out and log in back, then upload the image :(

It seems it solved the problem for @HSERGERAERT  See https://github.com/c2corg/v6_ui/issues/698#issuecomment-253428839

By the way, those last messages have no connection with the current issue. I will remove them a bit later when every one has read them.

**Comment by shortoland** [comment]
Indeed, it's much better now :-)
I confirm I can change from personal to collaborative, but not from collaborative to personal.

3 questions/remarks (maybe need to open new tickets, let me know):
- I cannot add images on a personal outing
- I cannot delete an image I have uploaded
- When viewing an image, clicking on "Voir les détails" doesn't make anything

**Comment by asaunier** [comment]
I have removed the unrelated comments.

> I cannot add images on a personal outing

Already reported! https://github.com/c2corg/v6_ui/issues/727

> I cannot delete an image I have uploaded

After it has been saved? If yes: that's normal. It's not possible even in v5 (and deleting documents is not implemented yet in v6, even for moderators)
Or in the upload preview before saving? I have just tested: not problem with my user at least.

> When viewing an image, clicking on "Voir les détails" doesn't make anything

I guess it has also been reported.
Anyway it's not related to the current issue.

**Comment by shortoland** [comment]
After it has been saved? If yes: that's normal. It's not possible even in v5 (and deleting documents is not implemented yet in v6, even for moderators)
Or in the upload preview before saving? I have just tested: not problem with my user at least.

=> After it has been saved, so it's normal.

**Comment by fjacon** [comment]
@asaunier issue to be closed ? dont see anything left to handle or everything is reported somewhere else

**Comment by asaunier** [comment]
Don't know. Some one should test (I have moderator rights).

**Comment by shortoland** [comment]
@fjacon Yes, I close the ticket
