### ISSUE TITLE
duplicate naming in outing-editing

### ISSUE THREAD

**Issue by ginold** [c2corg/v6_ui#719]
![screenshot from 2016-10-11 12-27-13](https://cloud.githubusercontent.com/assets/7814311/19267266/1b553dd6-8fae-11e6-83ad-63296bff02e4.png)

we have 2 times "itineraire emprunte" which I find superfluous. Maybe i can move the input field just above the first title and remove the 2nd one? Or change the naming of the field.

**Comment by asaunier** [comment]
Good catch!
What about simply renaming the association tool title to "Associated routes" and remove this title above the associated routes cards => tool + cards beeing in the same section.

**Comment by ginold** [comment]
or maybe the problem is in the translation - i now see both strings are the same in french, but in English they are "route_description" and "routes_taken"

**Comment by ginold** [comment]
@shortoland could you please change the translation of the "route_description" string, so that we don't have the same translation for both ?

**Comment by shortoland** [comment]
Done:
route_description => Description de l'itinéraire
No changes for the other ones:
taken_route => itinéraire emprunté
associated routes => itinéraires associés
I close the ticket, feel free to reopen if needed.
