### ISSUE TITLE
Associated images are not shown in outing detail views

### ISSUE THREAD

**Issue by asaunier** [c2corg/v6_ui#727]
When uploading an image to an outing, the thumbnail is no longer visible when refreshing the page.
Ditto for images already associated to the outings before the migration.

It seems that the API does not return images associations for outings?
Related to https://github.com/c2corg/v6_api/issues/412 ?

**Comment by stef74** [comment]
https://github.com/c2corg/v6_api/issues/412 is closed

**Comment by asaunier** [comment]
Associated images are actually displayed in the outings detail view page, as expected.

On the other hand it seems not possible to add a new image to an existing outing:
* the image is actually uploaded, and the thumbnail is added to the carousel
* but when reloading the page, the new image does not appear. In the UI logs, the API reports that "ETag match, returning 304 HTTP Not Modified Response", the associations are actually unchanged in the API response.
=> there's probably another problem, perhaps related to https://github.com/c2corg/v6_ui/issues/715 btw?
I have opened a dedicated issue: https://github.com/c2corg/v6_ui/issues/814

No problem with route detail view pages for instance.
