### ISSUE TITLE
Sidemenu for beta and v6.0

### ISSUE THREAD

**Issue by asaunier** [c2corg/v6_ui#732]
For the beta and v6.0 there is no accident report section (and no "community"/association section?).

It would make sense to remove those to entries in the sidemenu. Or perhaps to make them point to the v5  URLs? Since the articles will be available in v6 beta, we could make the "association" sidemenu entry point to some v6 article. 
@stef74 @HSERGERAERT what do you think?

In addition I wonder if we really need the "Homepage" entry since clicking on the logo already gives access to the homepage (and it's a common way to do so on most websites). Should we remove it?
It would allow to save some space vertically and allow to display the ad banner for smaller screens (when the screen is not high enough, the ad banner is hidden).

**Comment by stef74** [comment]
First I said yes ... but it can be a teasing. No link with v5 (indexation
problem) ... just infobox that say " bientôt ;-)"

You can remove "home" entry

2016-10-14 10:08 GMT+02:00 Alex Saunier <notifications@github.com>:

**Comment by asaunier** [comment]
> No link with v5 (indexation
problem) ... just infobox that say " bientôt ;-)"

What do you mean by "infobox"?

Honestly I would prefer we stay simple, we have too many things to do.
Possible solutions:
* remove the entry
* hard-coded URL to v5
* disable link (entry is here but it's not clickable)

**Comment by stef74** [comment]
disable link ...

2016-10-14 10:57 GMT+02:00 Alex Saunier <notifications@github.com>:

**Comment by mgerbaux** [comment]
> we could make the "association" sidemenu entry point to some v6 article. 

_Camptocamp association_ can point to the corresponding V6 article of http://www.camptocamp.org/articles/106726/fr/camptocamp-association
 _Base de données accidents_ can point to the corresponding V6 article of http://www.camptocamp.org/articles/697210/fr/base-serac-de-recits-d-incidents-et-accidents

**Comment by asaunier** [comment]
> Camptocamp association can point to the corresponding V6 article of http://www.camptocamp.org/articles/106726/fr/camptocamp-association

OK

> Base de données accidents can point to the corresponding V6 article of http://www.camptocamp.org/articles/697210/fr/base-serac-de-recits-d-incidents-et-accidents

What about pointing to the v5 URL http://www.camptocamp.org/xreports ?

**Comment by mgerbaux** [comment]
> What about pointing to the v5 URL http://www.camptocamp.org/xreports ?
I think it should be better to point v5 URL http://www.camptocamp.org/xreports from the "Serac" article.
Having Serac article as the V6 entry also allows to explain why xreports documents are not available on V6.0

**Comment by asaunier** [comment]
OK

**Comment by asaunier** [comment]
* [ ] The links in the sidemenu footer should be updated as well.
