### ISSUE TITLE
Remove/hide the map container in advanced search page for no-geom document types

### ISSUE THREAD

**Issue by asaunier** [c2corg/v6_ui#733]
When the map filter is disabled in an advanced search page (for instance for articles, areas or books), the map directive is actually disabled but the map container remains => it should be removed (the badge section with the number of results should probably be moved somewhere else).

![sans titre](https://cloud.githubusercontent.com/assets/1192331/19380386/5bcf3e2a-91f7-11e6-895e-7495943044da.png)

**Comment by stef74** [comment]
is probably relevant to offer the possibility to hide the map for all
document ...

2016-10-14 10:17 GMT+02:00 Alex Saunier <notifications@github.com>:

**Comment by asaunier** [comment]
> is probably relevant to offer the possibility to hide the map for all
document ...

I think it's something different. Here there's no map at all but the styles are not adapted.

Giving the possibility to fold/unfold the map (see also the mobile screens issue https://github.com/c2corg/v6_ui/issues/657) is an additional feature.

**Comment by ginold** [comment]
this is a 100% css issue. I can handle that later.
