### ISSUE TITLE
build error in closure-util

### ISSUE THREAD

**Issue by mfournier** [c2corg/v6_ui#74]
When installing/building the project from scratch (as of 15f1b97) on a standard debian jessie environment, I stall on this error:
```
mkdir -p c2corg_ui/static/build/
./node_modules/openlayers/node_modules/.bin/closure-util build build.json c2corg_ui/static/build/build.js
info closure-util Reading build config
info closure-util Getting Closure dependencies
info closure-util Compiling 414 sources

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: spawn ENOENT
    at errnoException (child_process.js:1000:11)
    at Process.ChildProcess._handle.onexit (child_process.js:791:34)
make: *** [c2corg_ui/static/build/build.js] Error 8
Makefile:120: recipe for target 'c2corg_ui/static/build/build.js' failed
The command '/bin/sh -c make -f config/main install' returned a non-zero code: 2
```

**Comment by tsauerwein** [comment]
What version of Node and npm are you using?

**Comment by mfournier** [comment]
Sorry, I wasn't explicit about this. The default versions coming with debian jessie are npm-1.4.21+ds-2 and nodejs-0.10.29~dfsg-2 (which looks like the same which are installed on c2corgv6-demo.gis.internal). Thanks for taking a look @tsauerwein !

**Comment by tsauerwein** [comment]
There is an open issue for ngeo for this Node/npm configuration: https://github.com/camptocamp/ngeo/issues/433

Probably there were some errors when `npm install` was run in your case. Node 4 should work fine.

**Comment by tsauerwein** [comment]
Mark proposed to use nvm in our Makefile to make sure that a "good" Node/npm version is used. I think that this would be a good idea, similar to a virtualenv for Python.

**Comment by gberaudo** [comment]
I never used nvm so maybe it is a good idea but I fear it may also be cumbersome in the long run.

**Comment by mfournier** [comment]
I'm afraid I still have this error in a more up to date environment (with nodejs 4.2.4), and also when using closure-util 1.8.0 (by forcing the use of https://github.com/openlayers/ol3/commit/925a89ecdbc).

nb: travis-ci's build environment doesn't seem to have this problem, but using stock ubuntu 12.04.5 doesn't provide anything reasonably recent when it comes to nodejs.

**Comment by mfournier** [comment]
Ok, so a recent version of nodejs yields a slightly different error message: `Error: spawn java ENOENT`.

Simply installing the JRE solved the problem...

**Comment by mfournier** [comment]
@gberaudo, @tsauerwein: BTW, while searching around for different nodejs versions, I came accross https://github.com/nodesource/distributions which seems to be a more suitable way to get a modern nodejs version than nvm.

**Comment by tsauerwein** [comment]
I added the requirements to the readme file (see https://github.com/c2corg/v6_ui/pull/75).

Glad to hear that it now works for you. nvm is handy if you quickly want to switch between different Node versions, but it is not needed if you want just one fixed version. For your docker containers it makes sense to use a distribution by NodeSource.
