### ISSUE TITLE
Associations problems in articles

### ISSUE THREAD

**Issue by asaunier** [c2corg/v6_ui#741]
I have just upgraded the demo (ditto in my dev instance). If I look at an article, say http://c2corgv6.demo-camptocamp.com/articles/713242/fr/procedure-documentation-technique-petzl I notice the following problems:

* [x] when searching for a document to associate (I have typed "grange"), the console reports that
```
Uncaught TypeError: Cannot read property 'length' of undefined
app.Document.hasAssociation	documentservice.js:102
(anonymous function)		simplesearch.js:319
```
* [x] I have not been able to associate a WP or a route (not tested other doc types) because of ``invalid association type : association`` (the associations request status is "400 Bad Request")
* [x] we don't need the following section:
![sans titre](https://cloud.githubusercontent.com/assets/1192331/19445056/28e95c5e-9493-11e6-8598-c66f39265e10.png)

**Comment by asaunier** [comment]
* [ ] Perhaps it's possible to remove the commented out code at https://github.com/c2corg/v6_ui/blob/master/c2corg_ui/templates/article/view.html#L62-L72 ?

**Comment by dkocich** [comment]
Ok. I am working on that right now.
