### ISSUE TITLE
Incorrect criteria when we select 6b+, P1+, A0+, ...

### ISSUE THREAD

**Issue by fbunoz** [c2corg/v6_ui#742]
When we select a criteria which contain a '+', it is not taken account.
For exemple, I select the free climbing rating range between 6a+ and 6b+ : the number of results doesn't change about all grades.
http://c2corgv6.demo-camptocamp.com/routes#bbox=-607746,3535588,1407745,7664411&act=rock_climbing&rrat=6a%20,6b%20&l=fr

If I choose a range between 6a and 6b+, only 6a is taken account.
Ther is the same problem with all ratings whose some grades contin a '+'.

**Comment by asaunier** [comment]
It seems that the "+" symbol is understood as the space " " symbol (which is urlencoded "%20").

**Comment by asaunier** [comment]
I guess we should URL-encode the values of the criterias when adding them to the URL
https://developer.mozilla.org/fr/docs/Web/JavaScript/Reference/Objets_globaux/encodeURIComponent

Perhaps here: https://github.com/c2corg/v6_ui/blob/master/c2corg_ui/static/js/search/searchfilters.js#L175

@tsauerwein would it make sense to do it in ``ngeo.Location``?
https://github.com/camptocamp/ngeo/blob/master/src/services/location.js

**Comment by stef74** [comment]
@asaunier for me this point is key for beta ...

**Comment by tsauerwein** [comment]
> @tsauerwein would it make sense to do it in ngeo.Location?

PR is here: https://github.com/camptocamp/ngeo/pull/2002

**Comment by asaunier** [comment]
Argh, I was just about to make a PR :P 
But in v6_ui. It's probably better to do it in ngeo (if it's OK to upgrade our ngeo/openlayers).
