### ISSUE TITLE
Advertisement banner

### ISSUE THREAD

**Issue by desnoes** [c2corg/v6_ui#743]
The advertisement banner is not displayed. It should be located in the left column. I do not observe it. I removed adblock for the V6 test site (http://ui.alpha3.demov6.camptocamp.org). I use Firefox 49.0.1.

**Comment by stef74** [comment]
I use the 45 ESR ... without problem banner is show.

**Comment by asaunier** [comment]
Your screen is most likely too small. If there is not enough space, the ad banner cannot be shown.
In my screen:
![sans titre](https://cloud.githubusercontent.com/assets/1192331/19469303/08a68434-951b-11e6-8247-e50f9361c4ba.png)
