### ISSUE TITLE
issue on installation

### ISSUE THREAD

**Issue by stef74** [c2corg/v6_ui#744]
![capture](https://cloud.githubusercontent.com/assets/3962997/19476954/34062398-953c-11e6-99ca-19db41614634.PNG)

I'm trying to install UI project ... i have an error on install. 

Script try to resolve private adress for github why ? the initial clone work perfectly (so dns resolution for github.com work).

**Comment by tsauerwein** [comment]
You are behind a proxy? Make sure that the proxy is also configured for npm.

**Comment by stef74** [comment]
Yes we have a proxy ... but the VM have no issue to connect to github via git command in terminal ...

**Comment by tsauerwein** [comment]
Git is using the env. var `HTTP_PROXY`, for npm you have to specify it explicitly. See also: https://jjasonclark.com/how-to-setup-node-behind-web-proxy

**Comment by stef74** [comment]
Ok it's work without proxy. I test with proxy later ...

Just notice a mistake on port to navigate on website is 6555.

Currently i have no data ... but i use an internal adress of you ... I will change with demo environnement
