### ISSUE TITLE
Single information block for mobile

### ISSUE THREAD

**Issue by tsauerwein** [c2corg/v6_ui#747]
On mobile the information block (General, Height, Rating, Maps) consists of multiple containers that are collapsed by default. It would be more convenient to have a single container, so that you do not have to click on each container to show the information.

![c2corg-mobile-infos](https://cloud.githubusercontent.com/assets/266474/19479906/16f24aea-9549-11e6-8da8-fd9225116dd4.png)

**Comment by ginold** [comment]
I do really find this solution convenient - you open what interests you and you don't have to scroll 20 times when you have a long description.

**Comment by tsauerwein** [comment]
To be clear: I am only proposing to have a single container for "General, Height, Rating, Maps". I don't want to change the other block.
