### ISSUE TITLE
Issues with translations

### ISSUE THREAD

**Issue by shortoland** [c2corg/v6_ui#749]
I have noticed the following issue several times during the last days:
- there are new strings to translate in Transifex,
- I usually translate them in french and english,
- after a few days "my" translations are deleted and need to be done again :-(

For example, I have recently translated the 18 new strings displayed in french and english.

Can you explain why this happens ? It's really boring to make the same work 2 or 3 times ...
Could it be possible not to delete already translated strings ?

**Comment by asaunier** [comment]
> For example, I have recently translated the 18 new strings displayed in french and english.

Could you give examples of strings for which the translations have been lost?

**Comment by shortoland** [comment]
Yes: the 18 untranslated strings in Transifex for french and english:
Create a new article
Informations
Last articles
article
article body
article_categories
article_type
association
c2c_meetings
collab
expeditions
gear_and_technique
mountain_environment
site_info
soft_mobility
stories
tags
topoguide_supplements

**Comment by asaunier** [comment]
No idea for the others but
> Informations
is related to this change: https://github.com/c2corg/v6_ui/pull/734

When a translated strings is changed in the source code, the translation is lost in Transifex.

According to https://github.com/c2corg/v6_ui/pull/734#issuecomment-253806016 there should be a "Translation Memory" in Transifex that should make translation suggestions according to former translations. Hasn't Transifex suggested a translation for "Informations"?

**Comment by tsauerwein** [comment]
> According to #734 (comment) there should be a "Translation Memory" in Transifex that should make translation suggestions according to former translations. Hasn't Transifex suggested a translation for "Informations"?

Is it enabled? http://docs.transifex.com/setup/enabling-translation-memory-autofill/

**Comment by dkocich** [comment]
Ehm. I am sorry... but also I am not sure if all the strings were available before my change and I could delete them all.

**Comment by shortoland** [comment]
The translation memory is enabled (thanks), but translators still have to click propositions one by one (x3 languages for me).

**Comment by shortoland** [comment]
At least we have identified the reason. I agree to close the issue.
