### ISSUE TITLE
Missing "search/add/remove associations" on the document view pages

### ISSUE THREAD

**Issue by dkocich** [c2corg/v6_ui#750]
We have many valid associations here - https://github.com/c2corg/v6_common/blob/master/c2corg_common/associations.py , but not all are used in the UI view pages (to search, add or remove association).

That means it is required to (for each different document type ):
- check "searchable" dataset settings and add valid document type
  https://github.com/c2corg/v6_ui/blob/master/c2corg_ui/templates/route/view.html#L140 (f.e. here only waypoint, route now without images - articles are in PR now)

- Rewrite `addassociation.js` associate function, which checks for swapping of parent-child relation between two documents 
https://github.com/c2corg/v6_ui/blob/master/c2corg_ui/static/js/addassociation.js#L90-L97

**Comment by fjacon** [comment]
What is the status of this issue ?

**Comment by stef74** [comment]
@tsauerwein what is the status ?

**Comment by tsauerwein** [comment]
Some associations are not shown because there are simply too many, for example outings for certain routes (they are shown under "recent outings"). @stef74, if you are missing associations please open a dedicated issue.
