### ISSUE TITLE
Replace "username" by "name" in the UI

### ISSUE THREAD

**Issue by asaunier** [c2corg/v6_ui#765]
"username" is actually a login. Only "name" (aka guidebook name) and "forum_username" are public user names. 

However "username" is still used in many places in the UI.
We should then use "name" instead of "username" in the UI pages (except in the auth and account pages of course).

Question: should we use "name" for the user menu (top of the page) instead of "username"? Since it's only displayed for the current user, it's not a big deal (and is probably shorted than the full name).

Related to https://github.com/c2corg/v6_api/pull/447 and https://github.com/c2corg/v6_api/issues/436

**Comment by tsauerwein** [comment]
> Question: should we use "name" for the user menu (top of the page) instead of "username"? Since it's only displayed for the current user, it's not a big deal (and is probably shorted than the full name).

+1

**Comment by fjacon** [comment]
@stef74 opinion ?
