### ISSUE TITLE
"Forum username" is translated with "Pseudo"

### ISSUE THREAD

**Issue by tsauerwein** [c2corg/v6_ui#767]
I noticed that the label "Forum username" is translated to French with "Pseudo" in the account page. This might be a bit confusing.

**Comment by asaunier** [comment]
That's a translation issue isn't it?
In french "pseudo" (especially in c2corg) pseudo is well-admitted as the forum name.
Anyway it's the responsibility of the translators/assocation, not ours. I would close the issue.

**Comment by tsauerwein** [comment]
Without knowing the background, I would have assumed that "pseudo" is the login name. I am not sure if everyone understands that this is related to the forum.

**Comment by asaunier** [comment]
OK you're right. @shortoland what do you think?

**Comment by shortoland** [comment]
I translated it without knowning the context. I can easily change it in "Identifiant forum". Do you agree ? Any other suggestion ?

For the moment, we have the fofllowing translations for strings with "username":
Forum username => Pseudo
Username => Identifiant
forum_user username => Identifiant du forum

What would "forum_user username" be ?

**Comment by asaunier** [comment]
What about simply translating "Forum username" to "Pseudo forum" in French?
It's not an "identifiant" (which is often understood as "login").

> What would "forum_user username" be ?

Arf, it's used only in the registration form:
https://github.com/c2corg/v6_ui/blob/ce2996f9c5b3c1314f02f9f66b92aa1e9745b213/c2corg_ui/templates/auth.html#L74-L82

In my opinion it's a duplicate string of "Forum username" and  should simply be replaced by "Forum username".

**Comment by asaunier** [comment]
I have proposed a fix for "forum_user username", see https://github.com/c2corg/v6_ui/issues/777

Concerning the translation of "Forum username", I think it's up to the translation team and that it's none of the dev team's business, thus should not be reported here. Is there a place for reporting and managing translation issues? In Transifex maybe?

**Comment by shortoland** [comment]
I have changed translation for "forum username" in "pseudo forum".
I just wanted your opinion for translation, as you know the context very well. Of course I won't ask developpers to help on translations.

And yes, it's possible to report issues in Transifex.

Should we close ?
