### ISSUE TITLE
User profile improvements and fixes

### ISSUE THREAD

**Issue by asaunier** [c2corg/v6_ui#769]
- [x] Fix user/profile icon on the map. See https://github.com/c2corg/v6_ui/issues/390#issuecomment-255041415
- [x] Show `forum_username` in user profile when  https://github.com/c2corg/v6_api/pull/447 is merged.

**Comment by asaunier** [comment]
* [ ] Show (guidebook) moderator rights (what about forum moderator rights?)

**Comment by asaunier** [comment]
@ginold do you think you could have a look at 
> Fix user/profile icon on the map

**Comment by ginold** [comment]
Yes I'm working on it right now

**Comment by stef74** [comment]
@ginold what is the status ?

**Comment by ginold** [comment]
not merged yet, but you can see the expected result under https://github.com/c2corg/v6_ui/pull/822

**Comment by asaunier** [comment]
> ￼ Show (guidebook) moderator rights (what about forum moderator rights?)

This part is not done yet because changes in the API are still required (low prio): https://github.com/c2corg/v6_api/issues/463

"forum moderator rights" info is not available (part of Discourse, not in the API).

**Comment by stef74** [comment]
@asaunier it is relevant to close and open dedicted issue for modereator right (not critical for v6.0 ... probably v6.1 or 2). ?

**Comment by asaunier** [comment]
> it is relevant to close and open dedicted issue for modereator right (not critical for v6.0 ... probably v6.1 or 2). ?

👍
