### ISSUE TITLE
Basic Auth on demo blocks the profile asynchronous requests

### ISSUE THREAD

**Issue by asaunier** [c2corg/v6_ui#771]
The demo UI is protected by a Basic Auth. The demo API is not.

When loading a profile page, an additional UI request (to the UI!) is made to figure out if the visitor can view the profile details. It seems the Basic Auth is not transfered to such asynchronous requests to the UI and a password is prompted (and never accepted, so the password window is shown again and again).

**Comment by asaunier** [comment]
We should probably pass an ``Authorization`` header to the UI asynchronous request. See for instance: http://stackoverflow.com/questions/17380731/get-url-content-with-basic-authentication-with-java-and-async-http-client

But we don't want to make change in the code, just for the demo and its basic auth protection...

**Comment by stef74** [comment]
Why you not disable auth and add robot.txt with no index/no follow directive ?

**Comment by asaunier** [comment]
> Why you not disable auth and add robot.txt with no index/no follow directive ?

This is the responsibility of the association to decide whether the basic auth should be disabled or not.

robots.txt => see https://github.com/c2corg/v6_ui/pull/784

**Comment by asaunier** [comment]
Suggested by @tsauerwein 
> we could make an exception in the Apache basic auth configuration for ``profiles/data/*`` UI requests

**Comment by asaunier** [comment]
> we could make an exception in the Apache basic auth configuration for ``profiles/data/*`` UI requests

As for now the basic auth protection is added to https://github.com/c2corg/v6_ui/blob/master/apache/wsgi.conf.in like this:
```
 <Location {base_url}>
   WSGIProcessGroup c2corg_ui-{instanceid}
   WSGIApplicationGroup %{{GLOBAL}}
+  Order deny,allow
+  Allow from all
+  AuthName "Registry Authentication"
+  AuthType basic
+  AuthUserFile "/var/www/vhosts/c2cassoc_c2corgv6/private/htpasswd"
+  Require valid-user
 </Location>
```

Adding
```
Require expr %{REQUEST_URI} =~ m#^/profiles/data/.*#
```
(see http://stackoverflow.com/questions/8978080/htaccess-exclude-one-url-from-basic-auth)
like this
```
 <Location {base_url}>
   WSGIProcessGroup c2corg_ui-{instanceid}
   WSGIApplicationGroup %{{GLOBAL}}
+  Order deny,allow
+  Allow from all
+  AuthName "Registry Authentication"
+  AuthType basic
+  AuthUserFile "/var/www/vhosts/c2cassoc_c2corgv6/private/htpasswd"
+  Require expr %{REQUEST_URI} =~ m#^/profiles/data/.*#
+  Require valid-user
 </Location>
```
seems to skip the basic auth for ``profiles/data/`` URLs. It is then possible to access the profiles pages without being bothered again by the basic auth prompt.

But I notice there the non-public profiles all return "This profile is only available to authenticated users." even though I'm authenticated. Probably another problem (with Apache? this part is OK in dev instances I think). I will open a dedicated issue.

**Comment by asaunier** [comment]
> But I then notice the non-public profiles all return "This profile is only available to authenticated users." even though I'm authenticated. Probably another problem (with Apache? this part is OK in dev instances I think). See #793

PR #794 fixes the problem with Apache, stripping the ``Authorization`` header out (#793).

But when the basic auth is enable we now have a conflict between the usual v6 ``JWT`` auth token (passed in the ``Authorization`` header) and the basic auth ``Authorization`` header:
* when authenticated the UI ``profile/data`` service receives the JWT token in the ``Authorization`` header (eg. ``JWT token="eyJhbGci..."``)
* when anonymous it receives the basic auth header as the ``Authorization`` header (eg. ``Basic YzJjb3...``)

In the latter case, the API seems to send a not correctly formatted response, because the UI cashes complaining that:
>    resp, data = self._call_api(url, headers)
  File "/var/www/vhosts/c2cassoc_c2corgv6/private/v6_ui/c2corg_ui/views/document.py", line 163, in _call_api
    return resp, resp.json()
  File "/var/www/vhosts/c2cassoc_c2corgv6/private/v6_ui/.build/venv/lib/python3.4/site-packages/requests/models.py", line 733, in json
    return json.loads(self.text, **kwargs)
  File "/usr/lib/python3.4/json/__init__.py", line 318, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.4/json/decoder.py", line 343, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.4/json/decoder.py", line 361, in raw_decode
    raise ValueError(errmsg("Expecting value", s, err.value)) from None
ValueError: Expecting value: line 1 column 1 (char 0)

**Comment by asaunier** [comment]
> when the basic auth is on, we now have a conflict between the usual v6 JWT auth token (passed in the Authorization header) and the basic auth Authorization header:

Should I test that the ``Authorization`` actually starts with ``JWT token`` (as in https://github.com/c2corg/v6_ui/blob/master/c2corg_ui/static/js/auth/authservice.js#L311) at https://github.com/c2corg/v6_ui/blob/master/c2corg_ui/views/profile.py#L90 ?

**Comment by tsauerwein** [comment]
Also with the config in https://github.com/c2corg/v6_ui/issues/771#issuecomment-256060707 to ignore`/profiles/data/`, do you get the Basic Auth Authentication header?

**Comment by asaunier** [comment]
Yes, when basic auth is on, even with ``Require expr %{REQUEST_URI} =~ m#^/profiles/data/.*#`` the basic auth header is passed to ``profiles/data`` and forwarded to the API.

**Comment by tsauerwein** [comment]
Aye, I am afraid we can't use Basic Auth together with the JWT token. I think we should focus on https://github.com/c2corg/v6_ui/pull/784

**Comment by asaunier** [comment]
Yes, or we could simply warn the client that there are conflicts with the Basic Auth when loading profiles as anonymous user (I think it's OK when authenticated) which make their rendering not correct in that case. But it's maybe not a big issue, the rest of the UI is not impacted I think.

> I think we should focus on #784

I think the PR is ready. Feel free to review it :)

**Comment by asaunier** [comment]
Change described at https://github.com/c2corg/v6_ui/issues/771#issuecomment-256060707 has been applied to the demo on our dev server: http://c2corgv6.demo-camptocamp.com/

Profiles (public or not) are now displayed as expected when the visitor is an authenticated user.
When browsing anonymously, profiles (public or not) are not displayed as expected (but at least there is no basic auth error or prompt) because the basic auth header is transfered to the API. It's OK when the basic auth protection is disabled.
See explanations above.

We won't make more changes about this basic auth side effect since the basic auth protection has been temporary set for the demo (and will not be used in production).

**Comment by asaunier** [comment]
@arnaud-morvan @fjacon 

Do you think it is worth committing this change in https://github.com/c2corg/v6_ui/blob/master/apache/wsgi.conf.in
```
 <Location {base_url}>
   WSGIProcessGroup c2corg_ui-{instanceid}
   WSGIApplicationGroup %{{GLOBAL}}
+  Order deny,allow
+  Allow from all
+  AuthName "Registry Authentication"
+  AuthType basic
+  AuthUserFile "/var/www/vhosts/c2cassoc_c2corgv6/private/htpasswd"
+  Require expr %{{REQUEST_URI}} =~ m#^/profiles/data/.*#
+  Require valid-user
 </Location>
```
or is it OK to apply it by hand in the exoscale demo? You should already have some manual changes since the basic auth is on in this demo.

If we commit it, it should be mentioned in https://github.com/c2corg/v6_ui/issues/639 in order to revert it before going live.
