### ISSUE TITLE
Cache document editing pages 

### ISSUE THREAD

**Issue by asaunier** [c2corg/v6_ui#780]
AFAIK editing forms (pages for creating/editing a document) are not cached.

It would probably make sense they would because:
- they don't really contain data and thus don't have to be invalidated when the docs change
- the creation form is the same for a given document type whatever the document id
- the editing form slightly changes from a document to another (but could we get the document id/lang from the URL with angular instead of passing it in the mako template?)

**Comment by asaunier** [comment]
> AFAIK editing forms (pages for creating/editing a document) are not cached.

Maybe they are?

I have just tried to make changes in the outing editing form and cannot set my changes until a run the ``clear-cache`` target.

**Comment by tsauerwein** [comment]
See https://github.com/c2corg/v6_ui/pull/552#issuecomment-237853939

> I have just tried to make changes in the outing editing form and cannot set my changes until a run the clear-cache target.

Does the development server reload when you make changes to the template files?

**Comment by asaunier** [comment]
> See #552 (comment)
I didn't set up caching for editing pages (e.g. /waypoints/edit/733087/fr). Edit pages for different documents differ in two lines (the lines where the document id and lang are set). So, a separate page for each document and lang would have to be cached. Because there are less edits than views, and to avoid that the cache is filled up too much, I decided not to cache these pages.

That makes sense indeed. Actually it would if we could get rid of those ``document_id``/``lang`` in editing form template => the same page would be used for all docs, would it? Or since the URL would remain different, it would not share the cache anyway?

> Does the development server reload when you make changes to the template files?

It seems not.

**Comment by tsauerwein** [comment]
> That makes sense indeed. Actually it would if we could get rid of those document_id/lang in editing form template => the same page would be used for all docs, would it? Or since the URL would remain different, it would not share the cache anyway?

If you could get rid  of document_id/lang, the page could be cached in Redis. But Varnish would create a separate version for each document, because the URL is different. But you could use fragment params for document_id and lang. See also https://github.com/c2corg/v6_ui/issues/554
