### ISSUE TITLE
Waypoint 'summit': field 'Proéminence'

### ISSUE THREAD

**Issue by desnoes** [c2corg/v6_ui#788]
I don't understand the meaning of this field. A text must be added to help the user.
The display of the document is rather confusion. There are 2 fields related to altitude.
The 'Altitude' of the summit => ok, same as in V5
In the section 'Altitudes', there is the field 'Proéminence'. This is totally confusing. What is the altitude of the summit at the end ?

**Comment by tsauerwein** [comment]
For an explanation see for example: https://fr.wikipedia.org/wiki/Hauteur_de_culminance

But yes, it would be good to show a description.

**Comment by asaunier** [comment]
Perhaps it's simply because it's a silly attribute that no one will ever use or fill in...

**Comment by desnoes** [comment]
I fully agree with your comment Alex. I would remove this field from the list, it is totally confusing.

**Comment by asaunier** [comment]
Closing because moved to issue #791
