### ISSUE TITLE
Waypoint 'summit': field 'Type de rocher' is missing

### ISSUE THREAD

**Issue by desnoes** [c2corg/v6_ui#789]
cf.  https://docs.google.com/spreadsheets/d/1Q_fl7UQKPMgzlnk5tvAGqrmesrwfA5gges8p25XLes8/edit#gid=1502780869

If this field is not considered any more, please remove it from the spread sheet.

**Comment by tsauerwein** [comment]
It's defined in the API: https://github.com/c2corg/v6_api/blob/master/c2corg_api/models/waypoint.py#L102-L104

Maybe it's missing in the forms?

**Comment by asaunier** [comment]
Closing because moved to issue https://github.com/c2corg/v6_ui/issues/791
