### ISSUE TITLE
Synchronize login/logout on UI and forum

### ISSUE THREAD

**Issue by gberaudo** [c2corg/v6_ui#79]
Ideally, the user should be logged on the forum at the same time as on the ui.
However,  the authentication mechanism are separate between the forum and the UI, so it may not always be the case.

TODO:
- [X] login to forum by reusing the UI authentication page, https://github.com/c2corg/v6_ui/pull/78;
- [X] creating a user directly in the forum is blocked, changing email in the forum is blocked (forum config);
- [X] logout from the forum when the user logs out from the UI (possible from c2c API by using discourse API);

**Comment by tsauerwein** [comment]
Maybe the Discourse Wordpress plugin is helpful:
https://github.com/discourse/wp-discourse

**Comment by tsauerwein** [comment]
For the login to Discourse when the user logins into the main site, there seems to be a trick with an iframe:
https://meta.discourse.org/t/issue-bleeding-edge-external-sso-prohibits-returning-to-host-app/24759/13

But maybe things have improved since then.

**Comment by asaunier** [comment]
@gberaudo Can this issue be updated (checklist) or even be closed?
