### ISSUE TITLE
WP creation : field 'Document quality'

### ISSUE THREAD

**Issue by desnoes** [c2corg/v6_ui#797]
I created an access WP and observed an error in the field 'Document Quality'. In the list, one finds 'Service regulier' which is an option normally devoted to the field 'Accessibilité en transports en commun'. There is maybe a traduction error with Transiflex (cf. https://github.com/c2corg/v6_ui/issues/792).

**Comment by desnoes** [comment]
i have the same bug with the creation of an outdoor climbing site

**Comment by asaunier** [comment]
> In fact the same string can be used several times, in different situations, with different translations.

That's exactly the reason of the problem!

Concerning the problem reported by @desnoes I notice that ``good`` is used as a value of
* ``quality`` https://github.com/c2corg/v6_common/blob/master/c2corg_common/attributes.py#L601
* ``public_transportation_ratings`` https://github.com/c2corg/v6_common/blob/master/c2corg_common/attributes.py#L107
* ``condition_ratings`` https://github.com/c2corg/v6_common/blob/master/c2corg_common/attributes.py#L529

which means that the translation of ``good`` will be the same for all 3 attributes!

If we don't want to use the same translation, the values in the attributes should be different.

**Comment by asaunier** [comment]
Closing because transfered to https://github.com/c2corg/v6_ui/issues/705#issuecomment-256283109

@desnoes @shortoland please now report such problems in the existing issue https://github.com/c2corg/v6_ui/issues/705
