### ISSUE TITLE
WP creation: field 'capacity_staffed' in shelter

### ISSUE THREAD

**Issue by desnoes** [c2corg/v6_ui#798]
When i create a shelter, the field 'capacity_staffed' is displayed while it is not listed in the specifications (https://github.com/c2corg/v6_common/blob/master/c2corg_common/fields_waypoint.py). It should be remode, there is not custodian in this case.

**Comment by asaunier** [comment]
Closing because transfered to https://github.com/c2corg/v6_ui/issues/791
