### ISSUE TITLE
Add a generic messaging system for the actions feedback

### ISSUE THREAD

**Issue by asaunier** [c2corg/v6_ui#8]
A generic tool that would display various messages coming from the UI application (error messages, confirmations of a successful action, welcome message after logging in, etc.) would be useful.

**Comment by asaunier** [comment]
Not sure it should be a separated tool or not, but we also need a "waiting" message (with a spinner?) displayed when an AJAX request or a redirection is done.

**Comment by tsauerwein** [comment]
For the loading indicator, this might be useful:
http://stackoverflow.com/a/15976991/119937
https://github.com/cgross/angular-busy

**Comment by asaunier** [comment]
For actions feedback (AJAX requests etc.) that require displaying some message (error, confirmation, etc.), we might use Bootstrap's alert, showing a small (closable/vanishable) rectangle in some page corner:
http://angular-ui.github.io/bootstrap/#/alert

What do you think?
Do you have other tools to suggest?

**Comment by gberaudo** [comment]
There is also http://bootboxjs.com/ we used for schweizmobil.

**Comment by asaunier** [comment]
Thanks for the tip @gberaudo 
We need non modal messages (that can be closed by the user or autofade after some timeout), else they would be too obstrusive. Not sure those bootboxes can do (I have tested quite fast)?

**Comment by gberaudo** [comment]
There is a cross to close the alert boxes, would it do?
It is possible to set a timeout and call `hide` on the box.
Don't know about fading.

**Comment by asaunier** [comment]
> There is also http://bootboxjs.com/ we used for schweizmobil.

OK bootbox might be OK for showing feedback messages or modals in some cases.

I have "reviewed" a bit the AngularUI Boostrap tools as well as other [AngularUI modules](http://angular-ui.github.io/) and they might be interesting for other features we will need. For instance:
* Carousel http://angular-ui.github.io/bootstrap/#/carousel for showing images in the documents
* Datepicker http://angular-ui.github.io/bootstrap/#/datepicker
* Modal http://angular-ui.github.io/bootstrap/#/modal
* Popover http://angular-ui.github.io/bootstrap/#/popover for inline help messages
* Progressbar http://angular-ui.github.io/bootstrap/#/progressbar for image uploading or document creation process status?
* Tabs http://angular-ui.github.io/bootstrap/#/tabs for document content?
* Typeahead http://angular-ui.github.io/bootstrap/#/typeahead for autocompletion (is it what we use for the simple search widget?)
* Accordion http://angular-ui.github.io/bootstrap/#/accordion for collapsing some parts of the pages?
* Scroll https://github.com/angular-ui/ui-scroll  or Scrollpoint https://github.com/angular-ui/ui-scrollpoint for infinite scrolling or other scrolling features?
* Slider https://angular-ui.github.io/ui-slider/demo/demo.html for filtering interface (there are 2-slider tools in the wireframes)
* ui-select https://github.com/angular-ui/ui-select for special select list (for instance to list the participants to an outing - see the wireframes there is something that looks like http://plnkr.co/edit/juqoNOt1z1Gb349XabQ2?p=preview)
* ui-tinyMCE https://github.com/angular-ui/ui-tinymce for WYSIWYG text editor
* Uploader https://htmlpreview.github.io/?https://github.com/angular-ui/ui-uploader/master/demo/index.html for uploading images?
* Validate https://htmlpreview.github.io/?https://github.com/angular-ui/ui-validate/master/demo/index.html (form validation)
