### ISSUE TITLE
Make "quality" and "change comment" more obvious in the editing form

### ISSUE THREAD

**Issue by asaunier** [c2corg/v6_ui#800]
As for now the "quality" and "change comment" inputs in the WP editing form are placed in a dedicated step at the very end of the form. Since people can save the form from any step, it's most likely that many won't even notice this final step and fill those inputs in.

We should probably move them to another step or make sure the "save" button is not clickable until the step is reached.

Probably same issue for other document types.

**Comment by ginold** [comment]
what do you think about putting both fields into a modal window after clicking on save?

 - click on save
 - modal appears with "document quality" and "change comments"
 - click one more time to approve the saving

Get rid of the "review" step.

**Comment by asaunier** [comment]
> what do you think about putting both fields into a modal window after clicking on save?

That looks like a good idea.
Well it adds a click to save a document but at least it makes those 2 (metadata) attributes more obvious indeed. And having the ``quality`` attribute set correctly is important.

So OK for me.

> Get rid of the "review" step.

+1 anyway!
