### ISSUE TITLE
Style for map tools looks broken (FF)

### ISSUE THREAD

**Issue by tsauerwein** [c2corg/v6_ui#801]
![c2corg-map-tools](https://cloud.githubusercontent.com/assets/266474/19725865/6214f348-9b88-11e6-9b41-a400e7dffa1f.png)

It looks better on Chrome.

**Comment by asaunier** [comment]
Honestly I am not a CSS expert. I don't think I am the good one to be assigned to this issue :P

**Comment by ginold** [comment]
i guess i am :P

**Comment by tsauerwein** [comment]
Another problem (noticed with Chrome): The recenter and filter box might overlap.
![c2corg-map-tools-overlap](https://cloud.githubusercontent.com/assets/266474/19801051/d8598f5c-9cfd-11e6-975b-a0f7b9eb725e.png)

**Comment by asaunier** [comment]
> The recenter and filter box might overlap.

This is not limited to Chrome. It always happens when the map is too narrow (especially since the French translation is longer than the original string).
Perhaps we should rethink where the map tools are placed.

**Comment by ginold** [comment]
- [ ] on mobile landscape mode - the map is a bit too hight and it's impossible to access the top buttons
