### ISSUE TITLE
Open embedded images in a slideshow

### ISSUE THREAD

**Issue by asaunier** [c2corg/v6_ui#805]
Sequel of https://github.com/c2corg/v6_ui/issues/712 and https://github.com/c2corg/v6_ui/pull/775

The PR above add the support of the `[img]` tags, used to embed images in a document.
When a caption is provided, it is made clickable and points to the image detail view page.

![sans titre](https://cloud.githubusercontent.com/assets/1192331/19739992/45f07a22-9bbd-11e6-91c0-918dd9189aef.png)

As for now, clicking on the image does nothing. It would make sense to enlarge the clicked image and show it in the usual slideshow tool. (or at least to open the image detail view page?).

**Comment by ginold** [comment]
:ok_hand:  looks badass

**Comment by asaunier** [comment]
@ginold I have assigned this issue to you (and me as supporter) because you seems to be the one that knows best how we could open those embedded image in the slideshow.
I think this will imply to make changes in the ``[img]`` tag parser:
https://github.com/c2corg/v6_ui/blob/master/c2corg_ui/format/img.py#L41-L86
to add the HTML code that will open the slideshow when clicking the image.
I can also help if you tell me what code to add.

**Comment by asaunier** [comment]
> It would make sense to enlarge the clicked image and show it in the usual slideshow tool. (or at least to open the image detail view page?).

PR https://github.com/c2corg/v6_ui/pull/853 implements the "at least" option (open the image detail view page).

But it would be better to open the image in the slideshow if possible.

**Comment by ginold** [comment]
Will it be a big missing feature if clicking on an image opens only the image you clicked, without letting you to navigate between all the other images within the text?

**Comment by asaunier** [comment]
I would say it's OK, even though it would make sense to show other images too (but I guess you don't know what are the other embedded images when you click on an embedded image).

Please note that in v5, embedded images must be associated to the document. So, actually, clicking an embedded image is a bit similar to clicking the image thumbnail in the carousel.
See for instance http://www.camptocamp.org/articles/763495/fr/changer-d-approche-10-idees-de-sortie-dans-la-metro-grenobloise

As for now we have no longer this constraint in v6, probably because we have never implemented it (not sure whether it was required or not).
