### ISSUE TITLE
Capitalize some of the translated strings

### ISSUE THREAD

**Issue by asaunier** [c2corg/v6_ui#808]
Many translated strings in the code are not correctly upper-cased (whereas the Transifex translations are).
The rule should be: same case for the code strings and the translations.

It would make sense to review the code and upper-case some of those code strings.
Please note that the existing translations for those changed strings are lost, not completely thanks to Transifex's translation memory but it requires manual actions for all those strings in all languages.

Then it's better to have the approval of the translation team (at least @shortoland ) and to do it once for all, so that translators don't have to fix the translations several times.

**Comment by ginold** [comment]
* uppercase = UPPERCASE
* capitalize = Capitalize

I think we sometimes use the same capitalized string where it should not - we could create a second filter in `filters.js` (capitalize already exists) and use it to lowercase/capitalize where needed.

**Comment by asaunier** [comment]
> uppercase = UPPERCASE
capitalize = Capitalize

OK thanks. I have updated the title :)

> I think we sometimes use the same capitalized string where it should not - we could create a second filter in filters.js (capitalize already exists) and use it to lowercase/capitalize where needed.

Do we have that many cases of strings that are sometimes lowercase, sometimes capitalize?
I would say that it's not that common.
