### ISSUE TITLE
Default map baselayer?

### ISSUE THREAD

**Issue by asaunier** [c2corg/v6_ui#810]
As for now OSM is the default map base layer.

Do we really meet their usage policy, mainly concerning the traffic? Other points of http://wiki.openstreetmap.org/wiki/Tile_usage_policy#Requirements are OK I think.

I don't remember if we had considered using another default base layer? Bing? Esri Maps?

See https://github.com/c2corg/v6_ui/issues/67

**Comment by tsauerwein** [comment]
Mapbox has a really nice basemap: https://www.mapbox.com/maps/outdoors/

The association could inquire if they get a license for free.

Otherwise the Esri Map would also be ok as default base map.

**Comment by asaunier** [comment]
I meant "a default base layer among the existing base layers" :P 

> Otherwise the Esri Map would also be ok as default base map.

OK, so we could switch to Esri Map by default. I don't remember their terms of use either.
@stef74 OK for you?

**Comment by stef74** [comment]
You’re limited to 50,000,000 transactions in a twelve month

2016-10-27 14:40 GMT+02:00 Stephane Peiti <stephane.peiti@gmail.com>:

**Comment by stef74** [comment]
ok for switching to ESRI I remeber terme of use is OK

2016-10-27 14:29 GMT+02:00 Alex Saunier <notifications@github.com>:
