### ISSUE TITLE
Impossible to add new images to an outing?

### ISSUE THREAD

**Issue by asaunier** [c2corg/v6_ui#814]
It seems not possible to add a new image to an existing outing:
* the image is actually uploaded, and the thumbnail is added to the carousel
* but when reloading the page, the new image does not appear. In the UI logs, the API reports that "ETag match, returning 304 HTTP Not Modified Response", the associations are actually unchanged in the API response.

No problem with route detail view pages for instance.

perhaps related to https://github.com/c2corg/v6_ui/issues/715 ?

**Comment by tsauerwein** [comment]
> the image is actually uploaded, and the thumbnail is added to the carousel

Was the image uploaded/created correctly? E.g. can you check that it was created in the database?

**Comment by asaunier** [comment]
> Was the image uploaded/created correctly? E.g. can you check that it was created in the database?

The image is correctly uploaded and created. It is added to the database. The image document is created as expected (I can load the image page in my browser).

But the API keeps omitting the image when answering the outing detail request. I have flushed the API cache ("clear-cache") and the new image is still not added to the outing's ``associations`` attribute.

Looks like an API issue, right?

**Comment by tsauerwein** [comment]
> The image is correctly uploaded and created. It is added to the database. The image document is created as expected (I can load the image page in my browser).

Has the association between the outing and the image been created?

**Comment by asaunier** [comment]
It seems not!

**Comment by tsauerwein** [comment]
The problem with the API, could you please test with the UI?

**Comment by asaunier** [comment]
It now works as expected. Thanks for the fix!
