### ISSUE TITLE
Filepaths vs web caches

### ISSUE THREAD

**Issue by asaunier** [c2corg/v6_ui#82]
To prevent problems with reverse proxies or browser caches, the URL of static files should change when updating the UI app, for instance using uuids.

Not sure something is already available in the project. What about the ``version`` config in https://github.com/c2corg/v6_ui/blob/master/common.ini.in#L10 ?

**Comment by tsauerwein** [comment]
See also: http://docs.pylonsproject.org/projects/pyramid/en/1.6-branch/narr/assets.html#cache-busting

**Comment by gberaudo** [comment]
What about doing like in schweizmobil where we prefix by the git hash?

**Comment by asaunier** [comment]
> What about doing like in schweizmobil where we prefix by the git hash?

Yep. By the way we have a ``version`` param in https://github.com/c2corg/v6_ui/blob/master/common.ini.in#L10 that is set using the git hash in the default config: https://github.com/c2corg/v6_ui/blob/master/config/default#L4 but set back to 0 in config/dev (?) https://github.com/c2corg/v6_ui/blob/master/config/dev#L3

**Comment by asaunier** [comment]
> See also: http://docs.pylonsproject.org/projects/pyramid/en/1.6-branch/narr/assets.html#cache-busting

Requires Pyramid 1.6 which will be provided by https://github.com/c2corg/v6_ui/issues/139

**Comment by asaunier** [comment]
Since we now use Pyramid 1.6, I have taken a look at Pyramid cache busting tools quoted by @tsauerwein : 
http://docs.pylonsproject.org/projects/pyramid/en/1.6-branch/narr/assets.html#cache-busting

The simplest solution based upon ``QueryStringConstantCacheBuster(str(int(time.time())))``works out of the box by adding the example code to https://github.com/c2corg/v6_ui/blob/master/c2corg_ui/__init__.py#L10 => all ``static/`` URLs added by ``request.static_url`` in the mako templates get a ``x=123456`` parameter added to their querystring.

But as the doc says:
> This is almost never what you want in production as it does not allow fine-grained busting of individual assets.

Not to mention that

> Many caching HTTP proxies will fail to cache a resource if the URL contains a query string.

I have also tried the ``GitCacheBuster`` class that uses the file git hash but:
* the code example seems wrong (the ``def tokenize(self, pathspec):`` signature should probably rather be ``def tokenize(self, request, subpath, kw):`` as in https://github.com/Pylons/pyramid/blob/b791e9ee69e98032950f97e09a98baadddbe9f91/pyramid/static.py#L208)
* it also adds a ``x=...`` param to the querystring
* I think ``git rev-parse HEAD``returns the last commit hash, whatever the file, which means we cannot use cache-busting only when the file has changed (maybe not a big deal? at least it should work for built files as well).

Please note that GeoMapFish also uses a cachebusting system:
https://geomapfish-demo.camptocamp.net/1.6/theme/Transport
* 1.6:
 * https://github.com/camptocamp/c2cgeoportal/blob/1.6/c2cgeoportal/__init__.py#L307-L314
 * https://github.com/camptocamp/c2cgeoportal/blob/1.6/c2cgeoportal/lib/cacheversion.py
* 2:
 * https://github.com/camptocamp/c2cgeoportal/blob/master/c2cgeoportal/__init__.py#L343-L351
 * https://github.com/camptocamp/c2cgeoportal/blob/master/c2cgeoportal/lib/cacheversion.py

Might also be related to the server caching system https://github.com/c2corg/v6_ui/issues/144
