### ISSUE TITLE
How to change closed/open sections status in detail view pages

### ISSUE THREAD

**Issue by asaunier** [c2corg/v6_ui#831]
@ginold I know that the association would like to change the default status (open/closed) of some sections in the outings or other detail view pages.

I don't know what sections are concerned so no need to do such changes now, but could you explain in this issue how this default status is set in the detail view pages? What makes a section closed or open at page loading? Thanks!

**Comment by ginold** [comment]
Easy:

it works with the bootstrap's `data-toggle`  and `data-target`. For example:

`<div data-toggle="collapse" data-target="#divToToggle"></div>`
`<div class="class="collapse in" id="divToToggle"></div>`

clicking on the first div will open/close the #divToToggle. It is closed by default if the class is "collapse" and open if it has both "collapse in", bootstrap works with those classes and takes care of them, you just have to define the initial state - collapse or collapse in.

http://www.w3schools.com/Bootstrap/bootstrap_collapse.asp

**Comment by asaunier** [comment]
OK, it seems quite simple, thanks :)

I leave the issue open because it might be useful to the association dev team.
