### ISSUE TITLE
Permissions to add/remove associations in a detail view page

### ISSUE THREAD

**Issue by asaunier** [c2corg/v6_ui#836]
As for now it seems that:
- [x] anyone (if auth) may add or remove a route association in an outing, even though they are not associated to the outing or moderators (clearly not OK)
- [x] anyone (if auth) may remove an association from a collaborative document (ditto for personal docs I guess). Is it OK?

What about outing associations in image detail view pages? See https://github.com/c2corg/v6_ui/pull/820

See also https://github.com/c2corg/v6_ui/issues/694

**Comment by fbunoz** [comment]
> anyone (if auth) may remove an association from a collaborative document (ditto for personal docs I guess). Is it OK?

It is not OK.
Only moderators can remove an association from a collaborative document.
Or we can allow removing an association few minutes after a member add an association.

**Comment by stef74** [comment]
@fjacon @ginold When it is planned ?

**Comment by ginold** [comment]
I'm working on it right now, it should be `ready for demo` today or tomorrow.

**Comment by stef74** [comment]
@ginold Wgat is the status ?

**Comment by ginold** [comment]
Waiting for review and for answers to a few questions. Maybe you can answer those questions in the meantime? see the description of https://github.com/c2corg/v6_ui/pull/961

**Comment by loicperrin** [comment]
I cannot test this because I am moderator and impossible to create a new account for testing (see #1115 )

**Comment by fbunoz** [comment]
I tested with my non modo account : it seems correct, I can't edit or remove an association on an outings of another user, on a route or an article.
