### ISSUE TITLE
Yellow list with intersecting areas in the outing view page is too long

### ISSUE THREAD

**Issue by dkocich** [c2corg/v6_ui#847]
I just tried to create a longer trip around half of France and that yellow list with areas totally destroyed the whole layout. The list should be limited somehow (maybe by a number of visible items with the ability to scroll down).

![image](https://cloud.githubusercontent.com/assets/6165660/20013848/f3cb2392-a2b4-11e6-858d-8f2d241c2a01.png)

**Comment by asaunier** [comment]
That's pretty unlikely but I admit it could happen (for instance for very long multi-day trekkings).

Anyway the page structure might change a bit. See https://github.com/c2corg/v6_ui/issues/449
As a result the map will probably be less wide. Not sure using such a block on the map will still be possible.
