### ISSUE TITLE
Creating new documents using the simple search / association tool

### ISSUE THREAD

**Issue by asaunier** [c2corg/v6_ui#849]
When searching for an association, if there is no result, the association tool offers buttons to create new associated documents:
<img width="602" alt="capture d ecran 2016-11-05 a 09 43 27" src="https://cloud.githubusercontent.com/assets/1192331/20028838/96e1b618-a33c-11e6-9843-5162ffbf7205.png">

There is still in issue though, because such buttons are only shown if no result can be found, which does not happen that often because the search engine finds a bit too many results I think and because for routes, if the name is quite common and used for other unrelated routes (eg. "face N"), you'll find a bunch of unrelevant results.
Perhaps the "create a new ..." tool should appear after each set of results anyway?

**Comment by asaunier** [comment]
See also https://github.com/c2corg/v6_ui/issues/1086

**Comment by asaunier** [comment]
Moving here the related issue https://github.com/c2corg/v6_ui/issues/1086

<img width="650" alt="capture d ecran 2016-12-03 a 17 31 40" src="https://cloud.githubusercontent.com/assets/1192331/20860693/94b5f324-b97e-11e6-81e2-ab0d32a1d0fd.png">

* Why "no result" when there are articles found? => rename this title or even remove it 
* Why showing it before the articles list anyway?

I have the feeling this "create a new..." block is not OK:
* [ ] since it appears even when there are results, it should be renamed to "no match?". Or we could simply remove the title.
* [ ] Perhaps the "create" button should be right at the end of the list of every document type (matching the dataset, for instance ``dataset="wcb"``) => if no result for a given doc type, show the doc type title + "no match" + the create button?
* [ ] Never show the "create" buttons when the association tool is within an editing form. See https://github.com/c2corg/v6_ui/issues/1059.
* [ ] Btw the "create" buttons are not really relevant in the association tool because clicking on such a button will indeed create a document but not associate it to the previous document.
* [ ] It is not relevant to show "create" buttons for document types that are not listed in the tool's ``dataset``.

At short term, perhaps we should simply disable the "create" buttons in the association tool because they would require a lot of work to make the behaviour consistent.

**Comment by asaunier** [comment]
Minimal changes have been made in #1109 
The issue should remain open anyway but could be postpone to another milestone.

**Comment by stef74** [comment]
Ok for 1st approach
