### ISSUE TITLE
Merge JS lib and CSS files

### ISSUE THREAD

**Issue by asaunier** [c2corg/v6_ui#85]
As for now, we have several node_modules files that are loaded from the HTML including in standard mode: https://github.com/c2corg/v6_ui/blob/master/c2corg_ui/templates/base.html#L74-L80

Merging those lib files in a single one would be useful.

**Comment by tsauerwein** [comment]
For libraries like jQuery, Angular and TypeAhead we could also consider using CDN URLs so that these libraries might already be in the browser cache from visiting other sites that use the same libraries.

**Comment by tsauerwein** [comment]
See also: http://stackoverflow.com/a/21099939/119937

**Comment by asaunier** [comment]
OK, that indeed makes sense!

**Comment by gberaudo** [comment]
By using a CDN you expose user's privacy to the CDN (referrer, cookie).
There is also the risk of the CDN being hacked and serving malwares.
It also adds a failure point: if the CDN is down c2c becomes unusable.

In modern browsers it is possible to protect from CDN malwares by using subresource integrity: https://hacks.mozilla.org/2015/09/subresource-integrity-in-firefox-43/

For the first point, it is a choice to make between user's privacy and speed.

**Comment by tsauerwein** [comment]
Or we concatenate all dependencies into a single file. We would have a `deps.js` and a `build.js` file. The `build.js` is going to change more often, so we wouldn't have to invalidate the cache for the `deps.js` file every time.

**Comment by gberaudo** [comment]
Concatenating all dependencies into a signle `deps.js` file looks good to me.

**Comment by asaunier** [comment]
Sounds good to me to have a deps.js file. As mentioned by @tsauerwein upgrading the libs will occur not that often.

**Comment by tsauerwein** [comment]
Same for CSS files (I updated the title).
