### ISSUE TITLE
Broken links

### ISSUE THREAD

**Issue by stef74** [c2corg/v6_ui#852]
I'm crawling the website to identify broken link.

I'm not abale to crawl with commande line tool due to no sitemap exist ... i have found other more graphical tool but limited to 500 crawling.

Many issue are allready identified. 

- [ ] waypoint wikilink (like /summit/ ... ) issue existe in API 

- [ ] user / profile link are correctly migrated for the moment (issue existe in API)

- [ ] in v5 creation acount page is /Signup now is http://www.demov6.camptocamp.org/auth#to=%2F, they concern about 10 link in article 
http://www.demov6.camptocamp.org/articles/697210/fr/base-serac-de-recits-d-incidents-et-accidents
http://www.demov6.camptocamp.org/articles/238570/fr/aide-topoguide-comment-renseigner-un-acces-parking
http://www.demov6.camptocamp.org/articles/106920/fr/aide-topoguide-presentation
http://www.demov6.camptocamp.org/articles/107005/fr/aide-album-images-photos
http://www.demov6.camptocamp.org/articles/108776/fr/aide-personnaliser-c2c
http://www.demov6.camptocamp.org/articles/188258/fr/aide-topoguide-refuges-gites-abris-camps-de-base-bivouacs
http://www.demov6.camptocamp.org/articles/697210/es/base-serac-de-relatos-de-incidentes-y-accidentes
http://www.demov6.camptocamp.org/articles/108240/fr/camptocamp-association-comment-adherer
http://www.demov6.camptocamp.org/articles/106785/fr/aide-forum

- [ ] mail contact http://www.demov6.camptocamp.org/forums/misc.php?email=108544
concern 2 articles 

http://www.demov6.camptocamp.org/articles/121965/fr/credits
http://www.demov6.camptocamp.org/articles/106746/fr/aide-generalites

- [ ] need to review all "article d'aide" ... many link are broken but manual change is easy

- [ ] http://www.demov6.camptocamp.org/outings/conditions doesn't exist in v6.0

**Comment by asaunier** [comment]
>  waypoint wikilink (like /summit/ ... ) issue existe in API
> user / profile link are correctly migrated for the moment (issue existe in API)

Wikilinks can be fixed in the migration script, see https://github.com/c2corg/v6_api/issues/417#issuecomment-255579022

For links for external websites, see https://github.com/c2corg/v6_ui/issues/644

> in v5 creation acount page is /Signup now is http://www.demov6.camptocamp.org/auth#to=%2F, they concern about 10 link in article

It's better to change the links in those articles. Ditto for mail contact

**Comment by stef74** [comment]
- [ ] change link on external site for v5 list not supported

**Comment by tsauerwein** [comment]
@stef74 FYI A sitemap is now available at http://www.demov6.camptocamp.org/sitemap.xml

**Comment by asaunier** [comment]
@stef74 Are there tasks related to this issue? Could the "golive" milestone be removed if it's rather an "info" ticket?
Not having this issue in the list of golive issue would help figuring out what is actually left before golive. Thanks.

**Comment by stef74** [comment]
@asaunier @HSERGERAERT according to herve I create milestone association ... for me is not just in infos ... but some action is needed by association
