### ISSUE TITLE
Homepage intro picture

### ISSUE THREAD

**Issue by asaunier** [c2corg/v6_ui#855]
As for now the big picture shown in the homepage for "guests" is fixed (one of mine: https://github.com/c2corg/v6_ui/blob/master/c2corg_ui/static/img/home/slide1.jpg).

Problems:
* it's always the same
* it might be not relevant for the golive (a ski image would make more sense)
* since it's currently integrated in the v6_ui files, its licence is probably the same than the rest of the code (?), ie. AGPL, which seem to make approached photographers a bit reluctant (commercial use is not forbidden etc.)

It would make sense to use some images posted on the website, for instance if some kind of "like" system is implemented etc. Maybe in the future.

At a shorter term it would make sense to
* [ ] have a pool of images, stored somewhere outside of our github repo (for licence reasons).
* [ ] have a config file listing those images as well as their authors and licence (and ?)
* [ ] make them being randomly displayed in the homepage, with an attribution section telling who's the author and what's the licence.

Beware of the cache => would we need some kind of angular directive to handle the images?
Perhaps there is already some tools existing to do so?

**Comment by stef74** [comment]
It is relevant to store fix image on S3 directly ? Alex B. propose some photo for Go live (discussion in progress)

**Comment by tsauerwein** [comment]
> have a pool of images, stored somewhere outside of our github repo (for licence reasons).

If it's just a question of license, you don't have to move the images in a separate repository or alike (for example see http://softwareengineering.stackexchange.com/questions/245033/if-i-use-lgpl-licensed-images-in-my-open-source-software-project-do-i-have-to-u). We could add a second license file stating something like "File x, y, ... are licensed under ...". This should be enough.

> make them being randomly displayed in the homepage, with an attribution section telling who's the author and what's the licence.

For now, as long we are using static files, this could be done in the "Credits" article.

**Comment by asaunier** [comment]
> If it's just a question of license, you don't have to move the images in a separate repository or alike 

OK thanks for the tip!
That would be more convenient if the images are hosted in the repo, this way they would be available out of the box.

**Comment by stef74** [comment]
@asaunier you do the job ?

**Comment by asaunier** [comment]
What job?
No info about what image to use with what licence and attribution has been provided.

**Comment by brunobesson** [comment]
As for the license, yes, we do: CC BY-NC-SA.
Attribution si Alex Buisse and his website http://www.alexbuisse.com/.

I send you the image per email. Should the image not be large enough, then we should contact Alex Buisse directly.

**Comment by asaunier** [comment]
If it could be the same size than https://github.com/c2corg/v6_ui/blob/master/c2corg_ui/static/img/home/slide1.jpg it would make things easier: simple image replacement.

**Comment by brunobesson** [comment]
The proportion is the same, but the new image is a little bit smaller (1200px wide instead of 1500px). Is that ok for you?

**Comment by asaunier** [comment]
No clue. @ginold what do you think?

**Comment by asaunier** [comment]
The image has been updated. I set the issue "ready for demo" and have postponed the milestone: changes for golive have been done, other changes about having several images have to be addressed later.

**Comment by stef74** [comment]
it's OK !

**Comment by tsauerwein** [comment]
On bigger screens the new image looks a bit unfortunate, because it is too small:

![image](https://cloud.githubusercontent.com/assets/266474/20926814/a3d9df2c-bbbe-11e6-8547-d025a941550f.png)
