### ISSUE TITLE
Server-related tasks

### ISSUE THREAD

**Issue by asaunier** [c2corg/v6_ui#856]
* [ ] Make sure documents and static files (CSS/JS) are served gzipped by the server

**Comment by asaunier** [comment]
> Make sure documents and static files (CSS/JS) are served gzipped by the server

It seems gzip compression is not enabled on the demov6:

![sans titre](https://cloud.githubusercontent.com/assets/1192331/20816444/96b7855a-b822-11e6-9b70-daa6b48359ad.png)

See http://superuser.com/questions/295360/how-to-know-if-a-site-is-gzipped
https://www.nginx.com/resources/admin-guide/compression-and-decompression/

**Comment by stef74** [comment]
@asaunier is in trello so we can close ?

**Comment by asaunier** [comment]
@stef74 It's here https://trello.com/c/j6RLfiF4/14-make-sure-documents-and-static-files-css-js-are-served-gzipped-by-the-server
