### ISSUE TITLE
Bugs with Articles

### ISSUE THREAD

**Issue by fbunoz** [c2corg/v6_ui#865]
- [x] Filter on article category return always no result.
- [x] Filter on article name return always no result.
- [x] Association tool doesn't work for article : no article can be found using the tool, on any page.
- [x] On an article page, the linked outings are not listed.

**Comment by stef74** [comment]
label association is for Camptocamp Association ... not for relationship between doc

**Comment by dkocich** [comment]
I am not sure why this does not work. On the other testing server that we have, the problems 1, 2 and 3 are OK now.

**Comment by asaunier** [comment]
> On the other testing server

Which one? The "dev" one?
We don't even know what server @fbunoz has tested :P

**Comment by asaunier** [comment]
I give the answer myself (just tested it): OK on http://c2corgv6.demo-camptocamp.com/articles but KO on http://www.demov6.camptocamp.org/articles
The first one is much more up-to-date than the second one. => updating the checklist above.

**Comment by asaunier** [comment]
> On an article page, the linked outings are not listed.

Not that critical. Moving to 6.1

**Comment by fbunoz** [comment]
> We don't even know what server @fbunoz has tested

I tested with http://www.demov6.camptocamp.org server, the only one which must be used for testing by the Association.

**Comment by asaunier** [comment]
> I tested with http://www.demov6.camptocamp.org server, the only one which must be used for testing by the Association.

That's correct indeed :)
But it's worth checking on the other server as well (at least for people like you). This way you can ignore problems that are already fixed :)

**Comment by stef74** [comment]
@fbunoz @shortoland could you test ?

**Comment by shortoland** [comment]
@stef74 Not yet ready for test

**Comment by stef74** [comment]
@fbunoz @shortoland please test

**Comment by fbunoz** [comment]
All the points are fixed.
