### ISSUE TITLE
metadata in the package

### ISSUE THREAD

**Issue by dkocich** [c2corg/v6_ui#874]
While I was installing I saw some warnings in the log - package.json is missing few fields which can be maybe added later for completeness of the project metadata. https://docs.npmjs.com/files/package.json 

```
npm WARN c2corg_ui@0.0.1 No repository field.
npm WARN c2corg_ui@0.0.1 license should be a valid SPDX license expression
```

Especially info about the license can be useful. For now in the [package.json](https://github.com/c2corg/v6_ui/blob/master/package.json#L10), there is BSD, but https://spdx.org/licenses/ contains few valid identifiers for BSD and it is maybe not clear which one is applied here. We also have other GNU license file saved in the project files.

**Comment by tsauerwein** [comment]
As we are not publishing a NPM package this metadata is not really relevant. But feel free to fill the fields to hide the warning.

The license is AGPL: https://github.com/c2corg/v6_ui/blob/master/LICENSE
