### ISSUE TITLE
Problems with images

### ISSUE THREAD

**Issue by loicperrin** [c2corg/v6_ui#875]
- [x] when I click on an image in a document, a "i" appears with the mouse goes over the image. In this panel the button "Voir les détails" has no effect. The only mean I have found to see the image details is to click on the button "Modifier" (which works), and then to cancel modifications.
- [ ] ~~when an image is added in an outing, in the image details page, the association to the outing does not appear. If we associate a document (route for example) from the image details page, this association is visible.~~

**Comment by asaunier** [comment]
> when I click on an image in a document, a "i" appears with the mouse goes over the image. In this panel the button "Voir les détails" has no effect. The only mean I have found to see the image details is to click on the button "Modifier" (which works), and then to cancel modifications.

I think it's already reported here: https://github.com/c2corg/v6_ui/issues/736
Correct?

> when an image is added in an outing, in the image details page, the association to the outing does not appear. If we associate a document (route for example) from the image details page, this association is visible.

Perhaps the demo you have tested (the official one?) is really not up-to-date? Because I have pushed a change to fix this last week and in the "dev" demo, it's OK.

By the way I notice that in the slideshow mode, the "full screen" and "close" icons are missing in the top right corner, near the "info" button. I think I have seen them recently...
@ginold do you know what happened?

**Comment by loicperrin** [comment]
>I think it's already reported here: #736
Correct?

Not exactly: for me the link to the image page is never active (the first time I open the slidewhow too)

> Perhaps the demo you have tested (the official one?) is really not up-to-date?

No it was the "dev demo", but now it works.

**Comment by asaunier** [comment]
> No it was the "dev demo", but now it works.

I did an upgrade this evening, perhaps it came with it.

> Not exactly: for me the link to the image page is never active

Sorry, I misread your sentence (it was clear enough though!).
The link is clickable in Chrome, as expected. But you're right: not with Firefox! (other browsers?)

**Comment by ginold** [comment]
this has been fixed in #805  !

I noticed it when testing - it worked on chrome but not in ff, very strange. Turned out to be an incorrect HTML construction -> the button was like `<button><a href/></button>` instead of `<a href><button></button></a>`.
According to MSD: 

> The a element may be wrapped around entire paragraphs, lists, tables, and so forth, even entire sections, so long as there is no interactive content within (e.g. buttons or other links).

Closing!
