### ISSUE TITLE
Feed: wrong message when uploading an image

### ISSUE THREAD

**Issue by loicperrin** [c2corg/v6_ui#878]
In the feed we can see some "update messages" whereas updates should not be taken into account in the feed. Probably these messages appear when an image is uploaded in a document. In this case the message should be something like "xxx has added an image to yyy".

**Comment by tsauerwein** [comment]
There are three different feed activity types: `created`, `updated` and `added_photos`.

`created` is used when a user creates a new document (except images, user-profiles and areas).
`added_photos` is used when a user adds images to a document, and the user is not the creator of the document.
`updated` is used when a user adds images to a document, and the user is the creator of the document. And also when a new participant is added to an outing.

**Comment by asaunier** [comment]
That makes sense indeed.

But perhaps it's a bit confusing though because:
* if you see "x has updated an outing" in the feed and look at the history of the outing you might see only one version => eg. x had updated an image in the mean time. Not that critical I admit but then it would make sense to show the uploaded images in the feed item (I think it's not the case currently). Wouldn't it be clearer and more consistent that the image uploads are always advertised as "has added images", whether the uploader has created the outing or not?
* people may think all updates are advertised in the feed (maybe in a future evolution?), which is not the case.

**Comment by loicperrin** [comment]
>updated is used when a user adds images to a document, and the user is the creator of the document. And also when a new participant is added to an outing.

Are you sure: in the feed I see the message "xxx has updated an outing" when I add an image to a document I have created, but not when a new participant is added to an outing.

>Wouldn't it be clearer and more consistent that the image uploads are always advertised as "has added images", whether the uploader has created the outing or not?

Yes, I think so!

**Comment by tsauerwein** [comment]
> Are you sure? in the feed I see the message "xxx has updated an outing" when I add an image to a document I have created, but not when a new participant is added to an outing.

I just tested, and it works:

* I create a new outing.
* In the feed I see an entry: "... has created an outing."
* I add a new participant to the outing.
* The feed now shows: "... has updated the outing." with the time updated.

What exactly did you do?

> Not that critical I admit but then it would make sense to show the uploaded images in the feed item

Yes, see: https://github.com/c2corg/v6_ui/issues/816

> Wouldn't it be clearer and more consistent that the image uploads are always advertised as "has added images", whether the uploader has created the outing or not?

The idea behind the current behaviour is that not too many feed entries should be created. When someone makes an outing, they first create the outing and then in a second step add the images. So, you would always see two entries in the feed: "created an outing" and "added images". To keep the feed compacter, we combine these two events into a single one.

**Comment by asaunier** [comment]
> When someone makes an outing, they first create the outing and then in a second step add the images. So, you would always see two entries in the feed: "created an outing" and "added images". To keep the feed compacter, we combine these two events into a single one.

That definitely makes sense to have only one entry in the feed for those 2 steps. Ditto when the user associate participants.

In both cases the feed shows "... has updated the outing.", right?

Then except the images not shown in the feed entry after uploading them (but this issue is described at #816) the behaviour of the feed is consistent.

@loicperrin please close the issue if it's OK for you.

**Comment by tsauerwein** [comment]
> In both cases the feed shows "... has updated the outing.", right?

Correct.

**Comment by loicperrin** [comment]
>What exactly did you do?

Maybe my action has been grouped in another one in the feed.
I cannot test this evening: "Getting feed data failed: Unknown error" in both demo (SA and c2c.org)

**Comment by asaunier** [comment]
> I cannot test this evening: "Getting feed data failed: Unknown error" in both demo 

As usual, when the database is reset: log out and in again :)

**Comment by loicperrin** [comment]
> As usual, when the database is reset: log out and in again

Yes of course!
It works => issue closed.

**Comment by tsauerwein** [comment]
> As usual, when the database is reset: log out and in again :)

Is there are a ticket for this? The error message should be more explicit.

**Comment by asaunier** [comment]
> Is there are a ticket for this? The error message should be more explicit.

This should not happen in production: we won't reset the database once in prod.

**Comment by tsauerwein** [comment]
> This should not happen in production: we won't reset the database once in prod.

But the problem that a request is made with an invalid token could still happen.

**Comment by asaunier** [comment]
OK, then it would make sense to create a dedicated issue (I think there is none yet).

**Comment by loicperrin** [comment]
> OK, then it would make sense to create a dedicated issue

OK. See #901
