### ISSUE TITLE
Adapt the image sizes in cards, feed, detail views

### ISSUE THREAD

**Issue by asaunier** [c2corg/v6_ui#886]
Perhaps it's OK and there is nothing to do but I wondered if there were adaptations to do in the UI to take into account the new sizes of resized images. See https://github.com/c2corg/v6_images/issues/6#issuecomment-256309185

> * BI: max 1500px (aspect and ratio preserved) => used for slideshow and detail view pages (will most likely be shrunk in detail view pages)
> * MI: max 400px (aspect and ratio preserved) => used for embedded images and bigger image in cards
> * SI: 200px (square or not, I don't know ; if square, aspect ratio must be preserved) => for carousel thumbnails and smaller images in cards?

@ginold what do you think?

**Comment by ginold** [comment]
It looks right to me. Maybe the only adaptations to do in the UI will be to change the image suffix (MI,SI,BI) because the size has changed and is now bigger than the original.

**Comment by asaunier** [comment]
Thanks! Could you please list here those suffix changes that should be done and in what pages?

**Comment by ginold** [comment]
After a quick look it all seems to be ok :

- feed cards :+1:  
- gallery thumbnail :+1:  
- slideshow image :+1:  
- embedded image :+1:  
- image in image-details-view :+1:  
- image in image-editing:+1:  

did I forget something?

**Comment by asaunier** [comment]
It seems OK then, thanks. I close the issue.
