### ISSUE TITLE
Profile pages are broken (no attribute '_get_with_etag')

### ISSUE THREAD

**Issue by asaunier** [c2corg/v6_ui#893]
Profile pages are no longer accessible, they return a 500 error (both demos, my personal instance as well).

According to the logs below, it seems related to the cache system. This seems pretty recent, maybe a side effect of the changes about the sitemap?

> [Wed Nov 09 22:27:19.559693 2016] [wsgi:error] [pid 20086] [remote 10.27.71.4:63366]     response = getattr(inst, attr)()
[Wed Nov 09 22:27:19.559768 2016] [wsgi:error] [pid 20086] [remote 10.27.71.4:63366]   File "/var/www/vhosts/c2cassoc_c2corgv6/private/v6_ui/c2corg_ui/views/profile.py", line 71, in profile
[Wed Nov 09 22:27:19.559793 2016] [wsgi:error] [pid 20086] [remote 10.27.71.4:63366]     self._get_cache_key)
[Wed Nov 09 22:27:19.559873 2016] [wsgi:error] [pid 20086] [remote 10.27.71.4:63366]   File "/var/www/vhosts/c2cassoc_c2corgv6/private/v6_ui/c2corg_ui/views/document.py", line 122, in _get_or_create
[Wed Nov 09 22:27:19.559899 2016] [wsgi:error] [pid 20086] [remote 10.27.71.4:63366]     get_etag_key, get_response_html, self.debug, self.request)
[Wed Nov 09 22:27:19.559958 2016] [wsgi:error] [pid 20086] [remote 10.27.71.4:63366]   File "/var/www/vhosts/c2cassoc_c2corgv6/private/v6_ui/c2corg_ui/views/document.py", line 460, in get_or_create
[Wed Nov 09 22:27:19.559984 2016] [wsgi:error] [pid 20086] [remote 10.27.71.4:63366]     not_modified, api_cache_key, loaded_data = load_data(old_api_cache_key)
[Wed Nov 09 22:27:19.560044 2016] [wsgi:error] [pid 20086] [remote 10.27.71.4:63366]   File "/var/www/vhosts/c2cassoc_c2corgv6/private/v6_ui/c2corg_ui/views/profile.py", line 66, in load_data
[Wed Nov 09 22:27:19.560069 2016] [wsgi:error] [pid 20086] [remote 10.27.71.4:63366]     self._get_profile_info(id, lang, old_api_cache_key)
[Wed Nov 09 22:27:19.560128 2016] [wsgi:error] [pid 20086] [remote 10.27.71.4:63366]   File "/var/www/vhosts/c2cassoc_c2corgv6/private/v6_ui/c2corg_ui/views/profile.py", line 75, in _get_profile_info
[Wed Nov 09 22:27:19.560153 2016] [wsgi:error] [pid 20086] [remote 10.27.71.4:63366]     not_modified, api_cache_key, document = self._get_with_etag(
[Wed Nov 09 22:27:19.560225 2016] [wsgi:error] [pid 20086] [remote 10.27.71.4:63366] AttributeError: 'Profile' object has no attribute '_get_with_etag

**Comment by tsauerwein** [comment]
Interesting, are there no tests for this part? :P

**Comment by asaunier** [comment]
It seems not, my bad!

**Comment by ginold** [comment]
I didn't say anything because it was a problem on my instance, as usual.. :D
