### ISSUE TITLE
Pictures can't be loaded on Beta test server of C2C

### ISSUE THREAD

**Issue by HSERGERAERT** [c2corg/v6_ui#894]
We can't see the picture after an upload. The upload action itself seems to work, no error message seen on screen.
This happens on Beta tests demo server, example http://www.demov6.camptocamp.org/outings/815701/fr/chamechaude-versant-w, it works well on the SA demo server.
This might be linked with bucket activities to upload pictures on Beta server (Marc F. actions)

On the outing, we only get the picto image, and not the image itself.
![capture](https://cloud.githubusercontent.com/assets/20357260/20165935/b0258860-a711-11e6-9d5b-6523cf274cd4.JPG)

**Comment by asaunier** [comment]
I have observed the same problem: I have just tried to upload 4 images on http://www.demov6.camptocamp.org/routes/751904/fr/col-emile-pic-traversee-glacier-blanc-greatergreater-glacier-des-agneaux

No error was thrown but the 4 images are broken in the carousel and in the slideshow (see screenshot in previous comment). When I try to load those images I get:
http://sos.exo.io/c2corg_demov6_active1479144473_249593468BI.jpg
```
<Error>
<Code>NoSuchBucket</Code>
<Message>The specified bucket does not exist</Message>
<BucketName>c2corg_demov6_active1479144473_249593468BI.jpg</BucketName>
<RequestId>bd48ea69-ca03-4cf7-9cfd-c201035898c3</RequestId>
<HostId>bd48ea69-ca03-4cf7-9cfd-c201035898c3</HostId>
</Error>
```

**Comment by arnaud-morvan** [comment]
Yesterday, I've removed the ending ``/`` in ``image_url``, because browser was trying to get images with ``bucket//key``.
I do not really understand, but I've just readded the ending ``/`` in ``image_url`` and all seems to work fine now.

**Comment by arnaud-morvan** [comment]
I get it : image detail view adds a ``\`` at the end of ``image_url``.
http://sos.exo.io/c2corg_demov6_active//1479214556_1000405130BI.jpg Failed to load 
Example: http://www.demov6.camptocamp.org/images/815750/fr/-

**Comment by asaunier** [comment]
Perhaps related to https://github.com/c2corg/v6_ui/issues/910 ?
