### ISSUE TITLE
IGN baselayers are missing in the demo

### ISSUE THREAD

**Issue by asaunier** [c2corg/v6_ui#895]
Probably a config problem with the IGN API key, not available for the demo URL.
I will have a look at the IGN key settings.

It should already be OK for the prod URL.

**Comment by asaunier** [comment]
The IGN settings are OK for URL http://www.demov6.camptocamp.org/
But the API key used for this demo (``9qxhimhvm24i40p8j86n7de3``) is registered for the "dev" demo (http://c2corgv6.demo-camptocamp.com/).

The API key that should be used for http://www.demov6.camptocamp.org/ is ``u2hnvshmi7absub9qkpunb3o``

I think the config for this demo is incorrect. @arnaud-morvan could you double-check please?

**Comment by arnaud-morvan** [comment]
I've set this new key in the composition, recreated the v6_ui container and flushed the cache. IGN base layer now display correctly on the demo.

**Comment by HSERGERAERT** [comment]
This is still not running well on Beta server

**Comment by asaunier** [comment]
It works for detail view pages. For instance http://www.demov6.camptocamp.org/routes/670647/fr/vallee-d-ailefroide-poire-d-ailefroide-ami-de-30-ans

But not on the advanced search pages: http://www.demov6.camptocamp.org/routes#bbox=700642%252C5603006%252C717993%252C5630715
Requested tiles are refused with message ``Wrong referer or wrong IP Adress or wrong User-Agent``.

That's strange that 2 behaviours are observed whereas the map tool is the same. I see no difference for referer or user agent. No idea for IP but that would be surprising.

**Comment by arnaud-morvan** [comment]
Works with Chromium, but not Firefox on my side. Same for all routes/views.

**Comment by arnaud-morvan** [comment]
I've disabled my Firefox RefControl for IGN WMTS (referer set to localhost for other development purpose) and it works as expected now.

**Comment by asaunier** [comment]
I think it is only a cache problem: OK for all URLs above when resetting or disabling the browser cache.

@HSERGERAERT Could you please try to empty your cache and test again?

**Comment by HSERGERAERT** [comment]
Yes it works, you was right, I had to remove the cache. I close !
