### ISSUE TITLE
Route creation: problem with icons display on map

### ISSUE THREAD

**Issue by desnoes** [c2corg/v6_ui#896]
When i create a route but i did not select a main WP, the route is created but icons (summit, access) are not displayed on the map.
Exemple: http://www.demov6.camptocamp.org/routes/815707/fr/essai-beta-rhm

**Comment by fbunoz** [comment]
See also : https://github.com/c2corg/v6_ui/issues/1026

**Comment by stef74** [comment]
@desnoes allready a problme ?

**Comment by desnoes** [comment]
Bug has been fixed with the setting of a main WP by default.
