### ISSUE TITLE
Add a WayPoint does not work

### ISSUE THREAD

**Issue by fjacon** [c2corg/v6_ui#90]
http://c2corgv6.demo-camptocamp.com/waypoints/add

No WP is created

**Comment by fjacon** [comment]
autant pour moi, je n'étais pas connecté !

**Comment by asaunier** [comment]
Yes, as for now, nothing prevents unauth users from accessing the editing forms. In addition the feedbacks message are not displayed yet.
Both issues are quoted in https://github.com/c2corg/v6_ui/issues/57
