### ISSUE TITLE
Problem with comment creation on documents

### ISSUE THREAD

**Issue by loicperrin** [c2corg/v6_ui#900]
When trying to add a comment on an outing, I get the following error: "Error with Discourse : Internal Server Error"

**Comment by stef74** [comment]
@loicperrin do you confirm the issue ?

**Comment by arnaud-morvan** [comment]
Probably due to the missing discourse api key in v6_api that I add this morning.
So this may be fixed now.

**Comment by loicperrin** [comment]
Now it works.

**Comment by loicperrin** [comment]
It does not work anymore.
Same origin?

**Comment by arnaud-morvan** [comment]
Not the same origin, discourse_api_key seems good.

Discourse says : Can't verify CSRF token authenticity

**Comment by arnaud-morvan** [comment]
I suspect that this is due to system user renaming

**Comment by arnaud-morvan** [comment]
After restore of the datamigration Discourse database and API container rebuild all works fine. Closing.
