### ISSUE TITLE
Deconnection necessary after database reset

### ISSUE THREAD

**Issue by loicperrin** [c2corg/v6_ui#901]
After a reset of database, before deconnection, we get this error: ""Getting feed data failed: Unknown error".
The database will not be reset anymore in production but the problem that a request is made with an invalid token could still happen.

**Comment by asaunier** [comment]
I don't think that's the real problem. I would rather say that the error message should be more explicit when an invalid token is detected (eg. "Your connection has expired. Please authenticate again.").
