### ISSUE TITLE
Some picto are not dispayed correctly

### ISSUE THREAD

**Issue by fbunoz** [c2corg/v6_ui#909]
On Firefox 38.7.0 / CentOS 6.7, some pictos are not displayed correctly.
See the screen capture on this outing : http://www.demov6.camptocamp.org/outings/815753/fr/pas-de-la-coche-versant-e

**Comment by asaunier** [comment]
Please add the screenshots directly in the issue.

Here they are:

![1479232957_371006277bi](https://cloud.githubusercontent.com/assets/1192331/20324944/db8e008e-ab82-11e6-91bf-5ce59f035f54.png)

![1479232956_1460289867bi](https://cloud.githubusercontent.com/assets/1192331/20324945/db8e5138-ab82-11e6-898e-214c8fa529b6.png)

I also copy here what you have reported in the forum of the association:

> Dans les cards du fil d'activité, il y a des images. Mais souvent, il y a juste le cadre des images, car l'url indiquée dans le code est invalide :
background-image: url(//sos.exo.io/c2corg_demov6_active1479025574_280720615MI.jpg)
au lieu de
background-image: url(//sos.exo.io/c2corg_demov6_active/1479025574_280720615MI.jpg)
Mais ce n'est pas tout le temps, en rechargeant la page, ça fonctionne parfois, et d'autres fois il y a 2 // (ce qui est aussi invalide) :
background-image: url(//sos.exo.io/c2corg_demov6_active//1479025574_280720615MI.jpg)

@arnaud-morvan It looks like something you have noticed/changed today, doesn'it?

**Comment by asaunier** [comment]
@ginold Could it be a problem of SVG fonts not correctly supported by older browsers? How old is FF38? Latest version is FF 50.
OK I have found the answer: FF38 was out in may 2015 https://www.mozilla.org/en-US/firefox/38.0/releasenotes/ Not so long ago.

Mine was FF 45 before it has just auto-upgraded and the icons were fine.

**Comment by ginold** [comment]
:fearful: ... it will be of no surprise if I say that I have no idea. 
Needs further investigation.

**Comment by stef74** [comment]
I propose to not take time on this issue ... just test if more recent FF is work.

**Comment by ginold** [comment]
People, **update** your browsers! :P
