### ISSUE TITLE
The comments is broken on image doc

### ISSUE THREAD

**Issue by fbunoz** [c2corg/v6_ui#911]
The comments don't work on a image doc : http://www.demov6.camptocamp.org/images/815757/fr/design-fil-d-activite
A Discourse error directly showed in the doc : 
> Oups ! Cette page n'existe pas ou est privée.

**Comment by brunobesson** [comment]
@fbunoz it this still the case? See e.g. https://www.camptocamp.org/images/832152/fr/-

**Comment by desnoes** [comment]
i did not observed any problem
