### ISSUE TITLE
Ad banner integration in the sidemenu

### ISSUE THREAD

**Issue by desnoes** [c2corg/v6_ui#912]
The advertisment picture overlap the community section
see
![pub accueil](https://cloud.githubusercontent.com/assets/19892089/20360210/1f28e7ae-ac33-11e6-9726-e3f296c17dac.jpg)

**Comment by asaunier** [comment]
Actually it only happens when the banner starts overlapping the menu. If you shrink a little more the screen in height, the banner is removed.

I think it worked correctly until the "version ..." link was added in the footer of the menu column. There's probably some CSS to update.

In fact this "version" link probably takes a bit too much space or could be placed somewhere else (no idea where!?) or maybe be removed before the ad banner when the height is too small?

**Comment by stef74** [comment]
@desnoes @shortoland could you test ?

**Comment by asaunier** [comment]
@stef74 The issue is marked as "ready for demo" (not "fixed and ready to be tested"), which means a PR has been merged but that the fix is not available in the demo yet.

**Comment by stef74** [comment]
Ok it''s misunderstanding of the label .....

**Comment by desnoes** [comment]
The banner has disappeared !
![pub](https://cloud.githubusercontent.com/assets/19892089/20573034/44b510d0-b1ae-11e6-9db3-148e9c4c6c78.jpg)

**Comment by HSERGERAERT** [comment]
Je l'aie
[image: Images intégrées 1]

Hervé

Coordinateur Projet V6
*Camptocamp Association*
Tél. +33 6 2563 5290

2016-11-23 18:54 GMT+01:00 desnoes <notifications@github.com>:

**Comment by asaunier** [comment]
> The banner has disappeared !

The banner is not shown when there is not enough space. Your screen is too small :P

**Comment by desnoes** [comment]
Is a screen size of 17.3 inch is considered as small :)

**Comment by asaunier** [comment]
It's rather a question of resolution.
Perhaps there are too many things in the sidemenu...

**Comment by tsauerwein** [comment]
One thing to consider: The ad provider is paying the association to show the ad. But if there is not enough space, and the ad is not shown, the ad would still be loaded and count as "shown" even if it is not visible. This might be a problem.

**Comment by desnoes** [comment]
@mgerbaux : please be informed of the problem identified by Tobbias.

**Comment by ginold** [comment]
When I have time I will try to always show the ad, whatever the size available, by shrinking the ad itself.

**Comment by asaunier** [comment]
> always show the ad, whatever the size available, by shrinking the ad itself.

That could be a solution indeed. But is it OK with the clients that banners are shrunk?
Isn't some work needed on the menu itself to have more space for the banner?
Perhaps the footer takes too much space and there is too many entries in the menu (do we really need "Home" and "Camptocamp Association" menu items for instance?).

**Comment by stef74** [comment]
I propose to go with shunk approach for Go live ... and rework after (dedicated issue top open).

**Comment by mgerbaux** [comment]
All the solution that allow to get more place in the menu to display add banners on smaller screen are welcome. A little shrunking (10-15 %) of banners are acceptable I think.

To get more space :
- Why not putting social network icons vertically along the add banner ?
- I think that version number will be deleted at the end of the beta period ?

I think also that in a close future, we should add one other item in the menu : more link/prepare your outinf

**Comment by asaunier** [comment]
> I think that version number will be deleted at the end of the beta period ?

I don't think so. But it's not a problem: it's already removed before the ad banner when the menu is not high enough. Perhaps we could do the same with the social network icons or the footer links?

By the way the footer could be a bit rework. For instance:
* place the 3 social network icons vertically (and a bit lower) as when the menu is folded
* move the footer links and version number to the right of those icons
* reduce the footer margins
* ...

**Comment by shortoland** [comment]
@stef74 No anymore overlap for me

**Comment by desnoes** [comment]
@stef74 i confirm, it is displayed correctly now. I close the issue.
