### ISSUE TITLE
route creation display: the unit (meter) is missing for 2 fields

### ISSUE THREAD

**Issue by desnoes** [c2corg/v6_ui#913]
All type of activities: the unit (meter) is missing for the field 'denivelé de l'approche'. See example below.
VTT: the unit (meter) is missing for the field 'Portage VTT'. See example below
http://www.demov6.camptocamp.org/routes/822279/fr/tete-de-vauclave-essai-beta-vtt

![iti vtt](https://cloud.githubusercontent.com/assets/19892089/20364265/bdf4edb0-ac42-11e6-8717-0db743a10029.jpg)

**Comment by stef74** [comment]
@desnoes @shortoland could you test ?

**Comment by desnoes** [comment]
i have tested, the bug has not been fixed.

**Comment by asaunier** [comment]
> i have tested, the bug has not been fixed.

Again: label "ready for demo" means the fix is not available on the demo yet (the issue would be labelled as "fixed and ready to be tested").

**Comment by desnoes** [comment]
The bug has been fixed, i close the issue
