### ISSUE TITLE
Scroll issue on iOs 10.1.1

### ISSUE THREAD

**Issue by fgravin** [c2corg/v6_ui#920]
I run the site in Safari.
I click on TopoGuide, then a long list of spots is displayed, i can't scroll properly the list.
Very slow, buggy.

Seems it's because the pan (for scroll) trigger a click on elements, so they are selected and it blocks the scroll.

**Comment by asaunier** [comment]
Thanks @fgravin for the feedback!
I have tested in a "desktop" Safari 10 and have notice nothing special.
Then tested in Browserstack with setting "iphone 7 - iOS 10.0" with nothing special either: no long list of spits, no strange behaviour when panning downwards (except maybe that the card I touch is pressed down - but the link is not triggered and the scroll works).

**Comment by dkocich** [comment]
I believe that all PC tools for simulating of mobiles can't catch all possible errors.
We can maybe try some tools at least when the page will be accessible without the login/pass.
  
https://search.google.com/search-console/mobile-friendly
https://testmysite.thinkwithgoogle.com/
http://ready.mobi/

**Comment by stef74** [comment]
Hello,

I have just tested on same condition (same browser and OS).

For me rendering is correct ... but scrolling is no "smooth" ("saccadé" in french)

Your tools is not able to detect this type of issue ... probably is due to bug on safari side. 

If someone have a version 10.0 or 9.x to confirm ?

**Comment by stef74** [comment]
@ginold this point is very boring ... we have identified that the feed are buggued ... so what is technaly the difference between this two type of list

**Comment by ginold** [comment]
Difference between feed list and advanced-search lists?
Nothing much to be honest - same cards, just displayed differently, and the advanced-search has a map but this should have no effect.

It could be nice to hear from other users if they experience this error. "Not smooth" makes me immediately think of a slow device. On older phones or on laptops (even on my very powerful laptop while on battery = lower performance) some pages are sluggish. Happens on my Galaxy S7 sometimes too.

**Comment by stef74** [comment]
I havé tested on two iPhone 5c same issue ... we lastest ios

**Comment by stef74** [comment]
I close because OS related
