### ISSUE TITLE
The geonames search does not work in https

### ISSUE THREAD

**Issue by asaunier** [c2corg/v6_ui#923]
When using an advanced search with an HTTPS URL, 
https://www.demov6.camptocamp.org/routes#bbox=-593070%252C3794863%252C1393069%252C7405136
the geonames-based recentering tool does not work ("not result") because the service is not available in HTTPS.

Actually it is available but as a premium webservice (not free): http://www.geonames.org/commercial-webservices.html

**Comment by tsauerwein** [comment]
Possible solutions:
* The association is willing to pay for the premium service.
* We set up a proxy.
* We use an alternative service, e.g. [Photon](http://photon.komoot.de/) or [OSMNames](http://osmnames.org/api/)

**Comment by stef74** [comment]
The cost of premium service is 720€/ years.

So what is the time needed to setup the two other solution ?

**Comment by tsauerwein** [comment]
> So what is the time needed to setup the two other solution ?

<0.5 d

**Comment by HSERGERAERT** [comment]
What is the advantage right now to work with https:// if this function is working with http:// ?

**Comment by asaunier** [comment]
It's mandatory to use https service when the calling page is https. Else the browser complains or even blocks the requests.

**Comment by HSERGERAERT** [comment]
Sure. Do we have strong argues to use an https:// starting page instead of the http://, at least until this issue is solved. This issue is linked to milestone v6.1, I have a bad feeling if the recenter on is not working at go-live

**Comment by tsauerwein** [comment]
In 2016 there are little reasons not use HTTPS everywhere (for example see here if you need arguments: https://developers.google.com/web/fundamentals/security/encrypt-in-transit/why-https). Changing the geo search provider is a fairly simple change, this should not block us from using HTTPS.

**Comment by stef74** [comment]
@tsauerwein I agree with you but starting HTTPS post live is not a big issue ... currently many point are not ready for live ... so priority is not HTTPS.

**Comment by asaunier** [comment]
Please not the "recenter on my position" button  (on the map) does not work if not in https.

**Comment by tsauerwein** [comment]
Tiens, cadeau : https://github.com/c2corg/v6_ui/pull/1001 :)

**Comment by asaunier** [comment]
@tsauerwein OH-MY-GOD This is sooooooo cool!!

The service works in https indeed. But I have also figure out it returns results not only for cities but also for places, regions or mountains (actually all data available in OSM I guess).
It also finds addresses (not sure it is that useful in our case, but perhaps it is not a big deal unless we have too many results). I have noticed a few minor problems I will report in the PR.
