### ISSUE TITLE
Simple search does not work in some cases

### ISSUE THREAD

**Issue by fjacon** [c2corg/v6_ui#93]
Example : search with "Bonneville"

This WP : http://c2corgv6.demo-camptocamp.com/waypoints/643020/fr
title : La Bonneville-sur-Iton

is never found.

**Comment by tsauerwein** [comment]
I renamed the waypoint you've created to "La Bonneville-sur-Iton". It's the same issue as https://github.com/c2corg/v6_ui/issues/92

I am looking into it: https://github.com/c2corg/v6_api/issues/127
