### ISSUE TITLE
Waypoint, routes and outings without geometry

### ISSUE THREAD

**Issue by tsauerwein** [c2corg/v6_ui#930]
Currently when trying to open http://www.demov6.camptocamp.org/outings/694060 an error is shown.

The problem is that the outing has not geometry. During the migration the geometries for routes are set from associated waypoints, and the geometries for outings are set from associated routes. But there are 171 waypoints that do not have a geometry. So, no geometry can be set for the associated routes and outings.

**Comment by asaunier** [comment]
@stef74 @fbunoz @loicperrin @desnoes Can we assume that all 171 waypoints will be georeferenced in v5 before the golive?

**Comment by stef74** [comment]
Yes but need to communicate quickly
-- 
Sent from Gmail Mobile

**Comment by asaunier** [comment]
I think that all migrated WP had a geometry.
