### ISSUE TITLE
Profiles page are sometimes not displayed

### ISSUE THREAD

**Issue by mgerbaux** [c2corg/v6_ui#933]
using firefox 44.0 sous linux

Often these pages are not displayed : http://imgur.com/a/zsQMd
Sometimes it is long to get
Sometimes it is OK

When not displayed, in JS debug  console :
```
Error: invalid 'in' operand b.data
Lz@http://www.demov6.camptocamp.org/static/4c851e7/build/build.js:825:21
Jz.prototype.za@http://www.demov6.camptocamp.org/static/4c851e7/build/build.js:824:84
pC/<@http://www.demov6.camptocamp.org/static/4c851e7/build/build.js:979:163
e/<@http://www.demov6.camptocamp.org/static/4c851e7/build/deps.js:170:20
vf/this.$get</m.prototype.$eval@http://www.demov6.camptocamp.org/static/4c851e7/build/deps.js:184:343
vf/this.$get</m.prototype.$digest@http://www.demov6.camptocamp.org/static/4c851e7/build/deps.js:181:412
vf/this.$get</m.prototype.$apply@http://www.demov6.camptocamp.org/static/4c851e7/build/deps.js:185:111
l@http://www.demov6.camptocamp.org/static/4c851e7/build/deps.js:136:320
J@http://www.demov6.camptocamp.org/static/4c851e7/build/deps.js:141:34
gg/</t.onload@http://www.demov6.camptocamp.org/static/4c851e7/build/deps.js:142:4
```

it seems right using Chromium browser

**Comment by asaunier** [comment]
The problem seems not to occur systematically (I have not been able to reproduce it but @mgerbaux has shown it to me on his laptop).

A few more info:
- when it happens, the additional request to ``http://<ui_host>/profiles/data/<user_id>/fr`` is 500
- the logs report that
```
[Sat Nov 19 10:28:37.245569 2016] [wsgi:error] [pid 19707] [remote 10.27.71.4:63366]   File "/var/www/vhosts/c2cassoc_c2corgv6/private/v6_ui/c2corg_ui/views/profile.py", line 97, in data
[Sat Nov 19 10:28:37.245594 2016] [wsgi:error] [pid 19707] [remote 10.27.71.4:63366]     resp, data = call_api(self.settings, url, headers)
[Sat Nov 19 10:28:37.245660 2016] [wsgi:error] [pid 19707] [remote 10.27.71.4:63366]   File "/var/www/vhosts/c2cassoc_c2corgv6/private/v6_ui/c2corg_ui/views/__init__.py", line 100, in call_api
[Sat Nov 19 10:28:37.245686 2016] [wsgi:error] [pid 19707] [remote 10.27.71.4:63366]     return resp, resp.json()
[Sat Nov 19 10:28:37.245765 2016] [wsgi:error] [pid 19707] [remote 10.27.71.4:63366]   File "/var/www/vhosts/c2cassoc_c2corgv6/private/v6_ui/.build/venv/lib/python3.4/site-packages/requests/models.py", line 733, in json
[Sat Nov 19 10:28:37.245791 2016] [wsgi:error] [pid 19707] [remote 10.27.71.4:63366]     return json.loads(self.text, **kwargs)
[Sat Nov 19 10:28:37.245853 2016] [wsgi:error] [pid 19707] [remote 10.27.71.4:63366]   File "/usr/lib/python3.4/json/__init__.py", line 318, in loads
[Sat Nov 19 10:28:37.245878 2016] [wsgi:error] [pid 19707] [remote 10.27.71.4:63366]     return _default_decoder.decode(s)
[Sat Nov 19 10:28:37.245936 2016] [wsgi:error] [pid 19707] [remote 10.27.71.4:63366]   File "/usr/lib/python3.4/json/decoder.py", line 343, in decode
[Sat Nov 19 10:28:37.245958 2016] [wsgi:error] [pid 19707] [remote 10.27.71.4:63366]     obj, end = self.raw_decode(s, idx=_w(s, 0).end())
[Sat Nov 19 10:28:37.246004 2016] [wsgi:error] [pid 19707] [remote 10.27.71.4:63366]   File "/usr/lib/python3.4/json/decoder.py", line 361, in raw_decode
[Sat Nov 19 10:28:37.246024 2016] [wsgi:error] [pid 19707] [remote 10.27.71.4:63366]     raise ValueError(errmsg("Expecting value", s, err.value)) from None
[Sat Nov 19 10:28:37.246112 2016] [wsgi:error] [pid 19707] [remote 10.27.71.4:63366] ValueError: Expecting value: line 1 column 1 (char 0)
```
=> perhaps a problem (not a JSON content?) with what the API returns to the UI service

**Comment by tsauerwein** [comment]
> => perhaps a problem (not a JSON content?) with what the API returns to the UI service

Do you see anything in the API logs?

**Comment by asaunier** [comment]
I think I have seen nothing in the error logs.

**Comment by asaunier** [comment]
I suspect it is related to the Basic Auth (wrong header ``Authorization`` passed to the API). See https://github.com/c2corg/v6_ui/issues/771#issuecomment-256482659

Not sure though: I have just tested to remove the Basic Auth on the "dev" demo => it worked for me in FF (had the problem before with FF), not for @mgerbaux (same error apparently).

**Comment by tsauerwein** [comment]
I was able to reproduce the error with this profile: https://www.demov6.camptocamp.org/profiles/13096/fr

I am not logged-in, and the profile is marked as non-public. The request to the API (http://api.demov6.camptocamp.org/profiles/13096) returns:

```
{
"name": "...",
"document_id": 13096,
"not_authorized": true
}
```

This makes the UI fail (https://www.demov6.camptocamp.org/profiles/data/13096/fr): "Internal Server Error"

On the client-side I see the following error in the console:

```
deps.js:157 TypeError: Cannot use 'in' operator to search for 'errors' in <html>
  <head> ...
```
I think it is related to this code: https://github.com/c2corg/v6_ui/blob/7706d2f/c2corg_ui/static/js/alertservice.js#L130

We should:

- Make sure that the UI server-side is able to deal with non-public profiles when no authentication token is provided.
- Make sure that the UI client-side is more resilient when trying to show the error message for failed requests.

**Comment by asaunier** [comment]
> Make sure that the UI server-side is able to deal with non-public profiles when no authentication token is provided.

When the UI profile data service crashes, the UI server-side logs report that
```
[Mon Nov 28 12:19:10.513552 2016] [wsgi:error] [pid 19900] [remote 10.27.71.4:512]   File "/var/www/vhosts/c2cassoc_c2corgv6/private/v6_ui/c2corg_ui/views/profile.py", line 97, in data
[Mon Nov 28 12:19:10.513571 2016] [wsgi:error] [pid 19900] [remote 10.27.71.4:512]     resp, data = call_api(self.settings, url, headers)
[Mon Nov 28 12:19:10.513772 2016] [wsgi:error] [pid 19900] [remote 10.27.71.4:512]   File "/var/www/vhosts/c2cassoc_c2corgv6/private/v6_ui/c2corg_ui/views/__init__.py", line 100, in call_api
[Mon Nov 28 12:19:10.513789 2016] [wsgi:error] [pid 19900] [remote 10.27.71.4:512]     return resp, resp.json()
[Mon Nov 28 12:19:10.514329 2016] [wsgi:error] [pid 19900] [remote 10.27.71.4:512]   File "/var/www/vhosts/c2cassoc_c2corgv6/private/v6_ui/.build/venv/lib/python3.4/site-packages/requests/models.py", line 733, in json
[Mon Nov 28 12:19:10.514357 2016] [wsgi:error] [pid 19900] [remote 10.27.71.4:512]     return json.loads(self.text, **kwargs)
[Mon Nov 28 12:19:10.514700 2016] [wsgi:error] [pid 19900] [remote 10.27.71.4:512]   File "/usr/lib/python3.4/json/__init__.py", line 318, in loads
[Mon Nov 28 12:19:10.514730 2016] [wsgi:error] [pid 19900] [remote 10.27.71.4:512]     return _default_decoder.decode(s)
[Mon Nov 28 12:19:10.515124 2016] [wsgi:error] [pid 19900] [remote 10.27.71.4:512]   File "/usr/lib/python3.4/json/decoder.py", line 343, in decode
[Mon Nov 28 12:19:10.515155 2016] [wsgi:error] [pid 19900] [remote 10.27.71.4:512]     obj, end = self.raw_decode(s, idx=_w(s, 0).end())
[Mon Nov 28 12:19:10.515221 2016] [wsgi:error] [pid 19900] [remote 10.27.71.4:512]   File "/usr/lib/python3.4/json/decoder.py", line 361, in raw_decode
[Mon Nov 28 12:19:10.515245 2016] [wsgi:error] [pid 19900] [remote 10.27.71.4:512]     raise ValueError(errmsg("Expecting value", s, err.value)) from None
[Mon Nov 28 12:19:10.515287 2016] [wsgi:error] [pid 19900] [remote 10.27.71.4:512] ValueError: Expecting value: line 1 column 1 (char 0)
```

It seems there is a problem with https://github.com/c2corg/v6_ui/blob/master/c2corg_ui/views/__init__.py#L100
```
    if resp.status_code == 304:
        # no content for 'not modified'
        return resp, {}
    else:
        return resp, resp.json()
```
It seems that the API returns a 401 response but with no JSON body => makes ``resp.json()`` crash.

The weird thing is that the API should not return a 401 response here: if the profile is not public and the user not logged in, the expected API response should be:
```
{
"name": "...",
"document_id": 13096,
"not_authorized": true
}
```

It seems it's related to the Basic Auth again. When the API returns a 401 for a profile data request, I see that the request headers are like:
```
HEADERS {'Authorization': 'Basic YzJjb3JnOmMyY29yZw=='}
```
which is not the kind of ``Authorization`` header the API expects.

A week ago I had try to remove the basic auth on the "dev demo", we still had the same problems. But perhaps the BasicAuth header was still provided to the API.

I think we should reconsider this issue when the Basic Auth protection is eventually removed.
All those profile problems were not observed when working on dev instances with no Basic Auth.

**Comment by mgerbaux** [comment]
Should it be in test ?
It does not seem to work for me…
![capture du 2016-12-01 10 18 22](https://cloud.githubusercontent.com/assets/22116605/20788129/adbb4de0-b7af-11e6-91da-e1237ab39150.png)

**Comment by asaunier** [comment]
> Should it be in test ? Or shoud it be OK on the prod version with no authorisation ?

I think it should work when the Basic Auth will be removed. See my comments above.
