### ISSUE TITLE
WP creation 'Shelter': field 'capacuty_staffed'

### ISSUE THREAD

**Issue by desnoes** [c2corg/v6_ui#940]
The field 'capacity_staffed' shall not be considered for the creation of a shelter (see https://github.com/c2corg/v6_common/blob/master/c2corg_common/fields_waypoint.py). The result is correct, only the field 'capacity' is displayed.

![abri](https://cloud.githubusercontent.com/assets/19892089/20455122/33ff91d2-ae54-11e6-9e8f-7161dcae108d.jpg)

**Comment by ginold** [comment]
closing because this problem has already been mentioned in #791
