### ISSUE TITLE
WP creation 'climbing_indoor': 'elevation' shall not be requested

### ISSUE THREAD

**Issue by desnoes** [c2corg/v6_ui#941]
It is not possible to complete the creation of the document. The 'elevation' is required while it is not specified in the 'required' section (https://github.com/c2corg/v6_common/blob/master/c2corg_common/fields_waypoint.py)

![sae](https://cloud.githubusercontent.com/assets/19892089/20455289/bfe4b87c-ae58-11e6-88af-406468dc8be4.jpg)

**Comment by ginold** [comment]
yes it is, look closely: https://github.com/c2corg/v6_common/blob/master/c2corg_common/fields_waypoint.py#L16

```
DEFAULT_REQUIRED = [
    'locales',
    'locales.title',
    'geometry',
    'geometry.geom',
    'elevation'
]
```

**Comment by asaunier** [comment]
@ginold It's not. Look closely:
https://github.com/c2corg/v6_common/blob/master/c2corg_common/fields_waypoint.py#L94-L99
:p 

What you are pointed at are the default required fields for waypoints but for "climbing_indoor" the default setting is not used.

**Comment by ginold** [comment]
Nice one! :p so @desnoes probably means that elevation is not required for 'climbing_indoor' only (missing info in the issue description).

**Comment by desnoes** [comment]
'elevation' is not considered for the 'climbing_indoor' WP and only for this WP.

**Comment by stef74** [comment]
@mgerbaux could you test ?

**Comment by stef74** [comment]
@desnoes could you test ?

**Comment by desnoes** [comment]
the bug has not been fixed. Elevation is still required and it is not possible to complete the creation of this WP.

----- Mail original -----
De: "stef74" <notifications@github.com>
À: "c2corg/v6_ui" <v6_ui@noreply.github.com>
Cc: "desnoes" <mathieu.desnoes@free.fr>, "Mention" <mention@noreply.github.com>
Envoyé: Vendredi 2 Décembre 2016 10:18:25
Objet: Re: [c2corg/v6_ui] WP creation 'climbing_indoor': 'elevation' shall not be requested (#941)



@desnoes could you test ?

**Comment by desnoes** [comment]
i retested and the bug disappeared !


----- Mail original -----
De: "mathieu desnoes" <mathieu.desnoes@free.fr>
À: "c2corg/v6_ui" <reply@reply.github.com>
Cc: "Mention" <mention@noreply.github.com>, "c2corg/v6_ui" <v6_ui@noreply.github.com>
Envoyé: Vendredi 2 Décembre 2016 10:35:00
Objet: Re: [c2corg/v6_ui] WP creation 'climbing_indoor': 'elevation' shall not be requested (#941)

the bug has not been fixed. Elevation is still required and it is not possible to complete the creation of this WP.

----- Mail original -----
De: "stef74" <notifications@github.com>
À: "c2corg/v6_ui" <v6_ui@noreply.github.com>
Cc: "desnoes" <mathieu.desnoes@free.fr>, "Mention" <mention@noreply.github.com>
Envoyé: Vendredi 2 Décembre 2016 10:18:25
Objet: Re: [c2corg/v6_ui] WP creation 'climbing_indoor': 'elevation' shall not be requested (#941)



@desnoes could you test ?

**Comment by mgerbaux** [comment]
it is OK for me
