### ISSUE TITLE
WP creation 'Access': title errors

### ISSUE THREAD

**Issue by desnoes** [c2corg/v6_ui#942]
- [ ] 'Accès' shall be replaced by 'Accès routier'.
- [x] 'Période de gardiennage' shall be replaced by 'Période de déneigement ou d'ouverture'.

![access](https://cloud.githubusercontent.com/assets/19892089/20455395/6c23867a-ae5b-11e6-9a1f-058c47d61acc.jpg)

**Comment by stef74** [comment]
Us only a translation issue ?

**Comment by fbunoz** [comment]
No, because the string "Accès" is used for other WPs, and the string "Période de gardiennage" is used for the huts.

**Comment by asaunier** [comment]
This issue has already been reported by @loicperrin at https://github.com/c2corg/v6_ui/issues/705#issuecomment-258557772

**Comment by shortoland** [comment]
Indeed, "Accès" is used twice and should be duplicated.

access_period is used for accesses
opening_periods is used for huts
Translations were switched, I have corrected that.

access_period is now  Période de déneigement ou d'ouverture
 opening_periods is now Période de gardiennage

**Comment by brunobesson** [comment]
`access_period` problem is already fixed.
#1401 attempts at solving the remaining translation issue.

**Comment by asaunier** [comment]
@brunobesson Can this issue be closed since your PR has been merged?

**Comment by brunobesson** [comment]
I.... think so. In prod, result seems fine to me.
