### ISSUE TITLE
Filter : do not updaye result before closing a multi choice selector

### ISSUE THREAD

**Issue by fbunoz** [c2corg/v6_ui#943]
When I want to filter the routes on skitouring, snowshoeing, or hiking, I need to open the activities selector, and select 3 check box.
But the result is updated at each selection, then the server is loaded for anything, and the user must wait between each select.
I think it should better update the result when the select box is closed by the user.
This behaviour is useful for all mumti choice selector.

**Comment by asaunier** [comment]
@tsauerwein has anticipated your request and already fixed it https://github.com/c2corg/v6_ui/pull/934

**Comment by stef74** [comment]
@tsauerwein when  ils available on demo ?

**Comment by asaunier** [comment]
@tsauerwein is not responsible for updating the demo and thus cannot answer your question.

**Comment by fjacon** [comment]
The results are updated if the filters are not changed after 700ms

**Comment by stef74** [comment]
@fbunoz @shortoland please test

**Comment by fbunoz** [comment]
With the delay, the filter behavior is OK for me.
