### ISSUE TITLE
Impossible to create a route on new waypoints

### ISSUE THREAD

**Issue by mgerbaux** [c2corg/v6_ui#945]
After creating a new waypoint, it is impossible to create an associated route
- there is no link  in the waypoint page to add a new route
- if using the route creation interface, the recently created waypoint is not proposed by the association tool (problem of indexation ?)

**Comment by mgerbaux** [comment]
@stef74 : should it put for milestone GoLive ? (I think yes)

**Comment by stef74** [comment]
For the first point an issue allready exist

**Comment by asaunier** [comment]
> For the first point an issue allready exist

https://github.com/c2corg/v6_ui/issues/198

**Comment by asaunier** [comment]
> there is no link in the waypoint page to add a new route

will be fixed by #1060

> if using the route creation interface, the recently created waypoint is not proposed by the association tool (problem of indexation ?)

Tested on the demov6 and it works. It was probably an indexing problem.

**Comment by loicperrin** [comment]
Fixed
