### ISSUE TITLE
snow level table is unavailable at outing creation

### ISSUE THREAD

**Issue by mgerbaux** [c2corg/v6_ui#946]
For outing creation with "winter" activities, it is impossible to define snow conditions by area
- there is no line by default
- the button to add a line is not functionnal.

This is OK when editing the outing, a line is present and the button is working

**Comment by desnoes** [comment]
it've tested, it seems ok. @mgerbaux please confirm.

**Comment by mgerbaux** [comment]
> 

OK for me
