### ISSUE TITLE
Mobile : quality or field error popup showed after 2 clicks on the save button

### ISSUE THREAD

**Issue by fbunoz** [c2corg/v6_ui#948]
On desktop, when we clic on the save button, the quality popup, or a missing field error, must appear
But on mobile nothing appear. We must clic a 2nd time on save button to the popup be visible.

**Comment by asaunier** [comment]
What is the "store button"?
Could you also precise the issue title? It seems related to the mobile browsing, right?

**Comment by ginold** [comment]
I think @fbunoz  meant "the save button"

**Comment by dkocich** [comment]
It is maybe related to the `:hover` styles ([stackoverflow here](http://stackoverflow.com/questions/12594522/two-clicks-required-when-only-one-should-be-needed-on-ipad-iphone))? Depends on the device, if it is virtualized/physical...

**Comment by fbunoz** [comment]
> What is the "store button"?
Could you also precise the issue title? It seems related to the mobile browsing, right?

Yes, it's the save button :)
This behaviour has been seen on android and iphone.
The popup seems to be created behind the current layer instead of over, but I didn't see into the HTML/CSS.

**Comment by fbunoz** [comment]
This bug is always active, for all docs types.
I think is blocking, as if the user test saving by cliquing on the cancel button, he lose all the data which he has entered in the form...

**Comment by ginold** [comment]
I think something is wrong here: who would try to _save_ by clicking on the _cancel_ button ? :P

Just tested on my phone : no issues when clicking on any buttons in the editing form ... (chrome and stock android browser).
What phones/browsers do you use?

**Comment by asaunier** [comment]
> Just tested on my phone : no issues when clicking on any buttons in the editing form ...

No phone to test. But in Chromium with a small screen (mobile layout), I don't see any problem either testing on demov6.

**Comment by fbunoz** [comment]
> What phones/browsers do you use?

Firefox 50.0 on Android 4.4.

**Comment by fbunoz** [comment]
Maybe the behavior is wanted by the dev : 
- On first clic, no action is done, but the button tooltip appear (the button is shfted left to make a place for the tooltip, but the tooltpi appear at the left :) .
- On the second clic, the action is done.

It avoids to clic on a button without knowing exactly what it does.

**Comment by brunobesson** [comment]
Those tooltips on mobile are a problem, I intend to have a look at it sometimes, they should usually be deactivated.

**Comment by stef74** [comment]
I reproduce in my ipad mini not on myi phone
