### ISSUE TITLE
Incorrect API config in the demo UI?

### ISSUE THREAD

**Issue by asaunier** [c2corg/v6_ui#958]
I notice that all request to the API made from the demo UI have double slashes before the path. For instance ``http://api.demov6.camptocamp.org//users/login``.

The API paths in the UI "api service" actually starts with a ``/``:
https://github.com/c2corg/v6_ui/blob/master/c2corg_ui/static/js/apiservice.js#L377
https://github.com/c2corg/v6_ui/blob/master/c2corg_ui/static/js/apiservice.js#L71

@arnaud-morvan Has the ``api_url`` in the demo config a trailing ``/``?
In the (unused?) demo config saved in the repo, it has not:  https://github.com/c2corg/v6_ui/blob/master/config/demo#L5

Perhaps an issue similar to the double slashes in the image URLs?
https://github.com/c2corg/v6_ui/issues/910

**Comment by arnaud-morvan** [comment]
Yes, demov6 ui config was having an ending slash.
I've removed the ending slash for api_url and api_url internal, recreated the ui container and flushed the cache.
Should be good now in demov6.
