### ISSUE TITLE
Outing creation on a new route: route not associated and cannot be associated

### ISSUE THREAD

**Issue by loicperrin** [c2corg/v6_ui#959]
I have created a new route: http://www.demov6.camptocamp.org/routes/822428/fr/test
If I create an outing on this route, it is not associated to the outing (it is OK if the route already contains an outing).
And if I try to add the route manually, I cannot find it (maybe it due to issue https://github.com/c2corg/v6_api/issues/285).

**Comment by fjacon** [comment]
I have an Internal Server Error when I try to add an outing to a route I just created.

**Comment by tsauerwein** [comment]
The outing has been created: https://www.demov6.camptocamp.org/outings/824705/fr/test-fred-itineraire-1

And the API returns the outing without error: http://api.demov6.camptocamp.org/outings/824705

There seems to be a problem on the UI server side.

**Comment by ginold** [comment]
```
 File "/home/agina/NetBeansProjects/C2C.org/v6_ui/c2corg_ui/templates/base.html", line 149, in render_body
    vcRecaptchaServiceProvider.setSiteKey('${settings["recaptcha_site_key"]}');
  File "/home/agina/NetBeansProjects/C2C.org/v6_ui/c2corg_ui/templates/outing/view.html", line 37, in render_moduleConstantsValues
    <%
TypeError: 'NoneType' object is not subscriptable
```

and line 37

```
  <%
      geometry = outing['geometry']['geom_detail'] \
          if outing['geometry']['geom_detail'] else outing['geometry']['geom']
  %>
```

**Comment by asaunier** [comment]
It seems the outing has no geometry at all whereas a default geometry should come from the associated routes or WP, shouldn't it?

**Comment by tsauerwein** [comment]
> It seems the outing has no geometry at all whereas a default geometry should come from the associated routes or WP, shouldn't it?

The outing does not have geometry, because the route does not have one. And the route does not have a geometry, because it does not have a main waypoint.

**Comment by asaunier** [comment]
OK thanks for precising.
I guess there is the same problem with the associated route? It has no geom at all?

Of course we could change the code mentioned by @ginold but I am not sure it is the real problem.
The real problem is that outings or routes may have no geometry.

If the route has no geometry and no main WP, would it be possible to fallback and use geometries of associated WP?

**Comment by tsauerwein** [comment]
> If the route has no geometry and no main WP, would it be possible to fallback and use geometries of associated WP?

That would be possible.

But as long as there are waypoints without geometry, we have to expect routes and outings without geometry.

**Comment by stef74** [comment]
@asaunier assoication have to add a geometry to all waypoint ?

**Comment by asaunier** [comment]
> assoication have to add a geometry to all waypoint ?

I think that the association has georefed all WP with a missing geom in v5. @fbunoz can you confirm?

**Comment by loicperrin** [comment]
> I think that the association has georefed all WP with a missing geom in v5

I confirm.

**Comment by asaunier** [comment]
@loicperrin great job, thanks!!

It would be cool if the association could make sure that all new WP is georefed before v5 is turned read-only.

**Comment by fjacon** [comment]
So, should we go on with this ? : If the route has no geometry and no main WP, would it be possible to fallback and use geometries of associated WP?

**Comment by stef74** [comment]
Do you consider is blocking point ? if assoication ensure all WP have georef

**Comment by asaunier** [comment]
Perhaps there is still a problem if someone creates a route with no main WP and no GPS/drawn geom => the route will have no geom, so do the associated outings.

**Comment by loicperrin** [comment]
I think the best way to solve this (and other issues) is, as proposed by @fjacon :

> If the route has no geometry and no main WP, the route should use geometries of associated WP

**Comment by ginold** [comment]
and how this geometry looks like? will it be the geometry of the 1st associated waypoint? or an area that fits all the associated waypoints? other?

**Comment by fbunoz** [comment]
To choose the coord of the geom, it is better to use the average of all wp
if possible. Or use the higher wp.

**Comment by tsauerwein** [comment]
It would probably make sense to handle this in the API.

**Comment by loicperrin** [comment]
Fixed.
