### ISSUE TITLE
Python 3 changes break apache mode

### ISSUE THREAD

**Issue by asaunier** [c2corg/v6_ui#96]
Same problem with the API: https://github.com/c2corg/v6_api/issues/130
=> In the main instance (apache) the UI crashes (error 500) because failing to import a module:

> [Tue Jan 12 19:02:02.333639 2016] [wsgi:error] [pid 21679] [remote 10.27.71.4:512] mod_wsgi (pid=21679): Target WSGI script '/var/www/vhosts/c2cassoc_c2corgv6/private/v6_ui/apache/app-c2corg_ui.wsgi' cannot be loaded as Python module.
[Tue Jan 12 19:02:02.333887 2016] [wsgi:error] [pid 21679] [remote 10.27.71.4:512] mod_wsgi (pid=21679): Exception occurred processing WSGI script '/var/www/vhosts/c2cassoc_c2corgv6/private/v6_ui/apache/app-c2corg_ui.wsgi'.
[Tue Jan 12 19:02:02.333961 2016] [wsgi:error] [pid 21679] [remote 10.27.71.4:512] Traceback (most recent call last):
[Tue Jan 12 19:02:02.334048 2016] [wsgi:error] [pid 21679] [remote 10.27.71.4:512]   File "/var/www/vhosts/c2cassoc_c2corgv6/private/v6_ui/apache/app-c2corg_ui.wsgi", line 3, in <module>
[Tue Jan 12 19:02:02.334259 2016] [wsgi:error] [pid 21679] [remote 10.27.71.4:512]     application = get_app('/var/www/vhosts/c2cassoc_c2corgv6/private/v6_ui/production.ini')
[Tue Jan 12 19:02:02.334301 2016] [wsgi:error] [pid 21679] [remote 10.27.71.4:512]   File "/var/www/vhosts/c2cassoc_c2corgv6/private/v6_ui/.build/venv/lib/python3.4/site-packages/pyramid/paster.py", line 31, in get_app
[Tue Jan 12 19:02:02.334445 2016] [wsgi:error] [pid 21679] [remote 10.27.71.4:512]     global_conf=options)
[Tue Jan 12 19:02:02.334653 2016] [wsgi:error] [pid 21679] [remote 10.27.71.4:512]   File "/var/www/vhosts/c2cassoc_c2corgv6/private/v6_ui/.build/venv/lib/python3.4/site-packages/paste/deploy/loadwsgi.py", line 247, in loadapp
[Tue Jan 12 19:02:02.334980 2016] [wsgi:error] [pid 21679] [remote 10.27.71.4:512]     return loadobj(APP, uri, name=name, **kw)
[Tue Jan 12 19:02:02.335025 2016] [wsgi:error] [pid 21679] [remote 10.27.71.4:512]   File "/var/www/vhosts/c2cassoc_c2corgv6/private/v6_ui/.build/venv/lib/python3.4/site-packages/paste/deploy/loadwsgi.py", line 272, in loadobj
[Tue Jan 12 19:02:02.335067 2016] [wsgi:error] [pid 21679] [remote 10.27.71.4:512]     return context.create()
[Tue Jan 12 19:02:02.335108 2016] [wsgi:error] [pid 21679] [remote 10.27.71.4:512]   File "/var/www/vhosts/c2cassoc_c2corgv6/private/v6_ui/.build/venv/lib/python3.4/site-packages/paste/deploy/loadwsgi.py", line 710, in create
[Tue Jan 12 19:02:02.335143 2016] [wsgi:error] [pid 21679] [remote 10.27.71.4:512]     return self.object_type.invoke(self)
[Tue Jan 12 19:02:02.335171 2016] [wsgi:error] [pid 21679] [remote 10.27.71.4:512]   File "/var/www/vhosts/c2cassoc_c2corgv6/private/v6_ui/.build/venv/lib/python3.4/site-packages/paste/deploy/loadwsgi.py", line 146, in invoke
[Tue Jan 12 19:02:02.335201 2016] [wsgi:error] [pid 21679] [remote 10.27.71.4:512]     return fix_call(context.object, context.global_conf, **context.local_conf)
[Tue Jan 12 19:02:02.335255 2016] [wsgi:error] [pid 21679] [remote 10.27.71.4:512]   File "/var/www/vhosts/c2cassoc_c2corgv6/private/v6_ui/.build/venv/lib/python3.4/site-packages/paste/deploy/util.py", line 55, in fix_call
[Tue Jan 12 19:02:02.335366 2016] [wsgi:error] [pid 21679] [remote 10.27.71.4:512]     val = callable(*args, **kw)
[Tue Jan 12 19:02:02.335418 2016] [wsgi:error] [pid 21679] [remote 10.27.71.4:512]   File "/var/www/vhosts/c2cassoc_c2corgv6/private/v6_ui/c2corg_ui/__init__.py", line 41, in main
[Tue Jan 12 19:02:02.335466 2016] [wsgi:error] [pid 21679] [remote 10.27.71.4:512]     config.scan(ignore='c2corg_ui.tests')
[Tue Jan 12 19:02:02.335492 2016] [wsgi:error] [pid 21679] [remote 10.27.71.4:512]   File "/var/www/vhosts/c2cassoc_c2corgv6/private/v6_ui/.build/venv/lib/python3.4/site-packages/pyramid/config/__init__.py", line 930, in scan
[Tue Jan 12 19:02:02.335693 2016] [wsgi:error] [pid 21679] [remote 10.27.71.4:512]     ignore=ignore)
[Tue Jan 12 19:02:02.335735 2016] [wsgi:error] [pid 21679] [remote 10.27.71.4:512]   File "/var/www/vhosts/c2cassoc_c2corgv6/private/v6_ui/.build/venv/lib/python3.4/site-packages/venusian/__init__.py", line 205, in scan
[Tue Jan 12 19:02:02.336042 2016] [wsgi:error] [pid 21679] [remote 10.27.71.4:512]     __import__(modname)
[Tue Jan 12 19:02:02.336090 2016] [wsgi:error] [pid 21679] [remote 10.27.71.4:512]   File "/var/www/vhosts/c2cassoc_c2corgv6/private/v6_ui/c2corg_ui/views/document.py", line 5, in <module>
[Tue Jan 12 19:02:02.336249 2016] [wsgi:error] [pid 21679] [remote 10.27.71.4:512]     from urllib.parse import urlencode
[Tue Jan 12 19:02:02.336307 2016] [wsgi:error] [pid 21679] [remote 10.27.71.4:512] ImportError: No module named parse

**Comment by mfournier** [comment]
Fixed, see issue c2corg/v6_api#130 for the details
