### ISSUE TITLE
ESRI background map is not shown in Chrome

### ISSUE THREAD

**Issue by tsauerwein** [c2corg/v6_ui#962]
For example on https://www.demov6.camptocamp.org/routes the ESRI background map is not show. In the console there is an error:

```
Failed to load resource: net::ERR_INSECURE_RESPONSE
https://server.arcgisonline.com/arcgis/rest/services/World_Topo_Map/MapServer/WMTS?layer=World_Topo_Map&style=default&tilematrixset=GoogleMapsCompatible&Service=WMTS&Request=GetTile&Version=1.0.0&Format=image%2Fjpeg&TileMatrix=6&TileCol=31&TileRow=21
```

**Comment by asaunier** [comment]
I have just tested https://www.demov6.camptocamp.org/routes in my Chromium: no problem with the ESRI tiles!?

**Comment by tsauerwein** [comment]
Which version of Chromium are you using? My version is Version 53.0.2785.143.

**Comment by tsauerwein** [comment]
In Chrome 47.0.2526.111 it works for me, it seems to be a recent change.

**Comment by asaunier** [comment]
Same version it seems:
Version 53.0.2785.143 Built on Ubuntu , running on Ubuntu 16.04 (64-bit)

**Comment by ginold** [comment]
I cant load them either but I think this has been happening to me since 1-2 weeks.

**Comment by tsauerwein** [comment]
This seems to be related to a bug in Chromium: https://sslmate.com/blog/post/ct_redaction_in_chrome_53

Updating Chromium should fix the problem, I will give it a try.

**Comment by tsauerwein** [comment]
Yep, updating Chromium fixed the problem for me. I think in this case we can close this issue.
