### ISSUE TITLE
Size of document-embedded images

### ISSUE THREAD

**Issue by asaunier** [c2corg/v6_ui#964]
Tags such as ``[img=123456 big/]`` in a document are replaced by an ``img`` HTML tag showing the ``BI`` image. Since BI images are bigger in v6 (up to 1500px), the document layout may be badly distorted.
The image should instead be shrunk to at least fit in the document description section width.

**Comment by ginold** [comment]
I think it is already the case: whatever the width is, it should fit the description width.

**Comment by asaunier** [comment]
See for instance http://www.demov6.camptocamp.org/articles/792303/fr/armenie-a-ski-de-randonnee

I have used ``[img=822359 big/]`` in the article content.

![sans titre](https://cloud.githubusercontent.com/assets/1192331/20556977/ca36cb94-b169-11e6-9de3-7db1140b9560.jpg)

**Comment by asaunier** [comment]
Oh wait! The demo is not up-to-date! Sorry, perhaps it's OK then.

**Comment by ginold** [comment]
Yeah I noticed yesterday that my PR on embedded images was not yet available on the demo.

**Comment by asaunier** [comment]
It works in the demo now.
