### ISSUE TITLE
Map : "recenter on" is not working anymore

### ISSUE THREAD

**Issue by HSERGERAERT** [c2corg/v6_ui#965]
Test made on demov6.
You can select "Lyon" or "Grenoble" or "Finhaut",  or "Paris" the map is not recentered anymore.
It's working on http://c2corgv6.demo-camptocamp.com/

**Comment by asaunier** [comment]
Thanks @HSERGERAERT for reporting the problem. Actually it's already described (and explained) in https://github.com/c2corg/v6_ui/issues/923

Closing the issue, since it's a duplicate.
