### ISSUE TITLE
Outing - Block Associated route still display an empty area when closed

### ISSUE THREAD

**Issue by dribagnac** [c2corg/v6_ui#966]
When I am displaying an outing, for eg 
http://www.demov6.camptocamp.org/outings/821396/fr/pointe-de-chalune-par-le-col-de-la-ramaz-depuis-sommand#/&gid=1&pid=4

   I want to close the block _Associated route_, a small DIV is still displayed (div class="associated-documents collapse")
![screenshot-www demov6 camptocamp org 2016-11-23 11-15-20](https://cloud.githubusercontent.com/assets/995825/20558100/caf1202a-b16e-11e6-9f93-197793214e53.png)

**Comment by ginold** [comment]
probably because `.associated-documents` has a `padding-top`, which does not play too well with bootstraps `.collapse `

**Comment by brunobesson** [comment]
It's both the `padding-bottom: 10px` and the `border: 1px solid #eee` properties.
They are defined in https://github.com/c2corg/v6_ui/blob/master/less/viewdetails.less#L325

But don't you think we could remove them? The visuals are OK for me without (it's lighter, I don't like having too many imbricated borders).

**Comment by asaunier** [comment]
That doesn't look like a critical problem. I have postponed it to 6.1.

**Comment by brunobesson** [comment]
See PR #1018

The boxes collapse nicely, plus IMHO the design is lighter and more attractive. When the content needs scrollbars, I find it properly integrated too.

**Comment by stef74** [comment]
@brunobesson you PR fix this issue ?

**Comment by brunobesson** [comment]
Yes, it does. You can close the issue.
