### ISSUE TITLE
Default value of quality dropdown in editing forms

### ISSUE THREAD

**Issue by asaunier** [c2corg/v6_ui#971]
As for now the quality dropdown is set to a blank value when creating a new document (the API converts it to "draft" I think).

It would make more sense that the default quality is directly displayed in the dropdown ("draft" I think).
Dropping this line should do the job:
https://github.com/c2corg/v6_ui/blob/master/c2corg_ui/templates/helpers/edit.html#L56

**Comment by desnoes** [comment]
@asaunier @brunobesson : i did not understand the objective of this PR. I cannot test it.

**Comment by desnoes** [comment]
@asaunier: thanks for the explanation. It works fine.
