### ISSUE TITLE
Lien profil topoguide -> profil forum

### ISSUE THREAD

**Issue by jmarcmod** [c2corg/v6_ui#973]
**Sur la page profil topoguide, il faudrait ajouter un lien vers la page profil forum.**
- ex. mon profil topoguide : https://www.camptocamp.org/profiles/9354/fr
- ex. mon profil forum : https://forum.camptocamp.org/users/J.Marc/summary

_(9354 = ID contributeur, J.Marc = pseudo forum)_

NB : dans le profil topoguide, il y a dans le bloc _Informations_ une ligne _Pseudo forum: J.Marc_ ; on pourrait rendre ce pseudo cliquable, ouvrant ainsi le profil forum.

Facile à coder selon Alex.

**Comment by AlexisDemongeot** [comment]
OK pour moi.

**Comment by celinestern** [comment]
Ok it's working

**Comment by desnoes** [comment]
C'est ok pour moi aussi
@jmarcmod : peux-tu valider que cela fonctionne ?

**Comment by jmarcmod** [comment]
> peux-tu valider que cela fonctionne ?
@desnoes : en apparence oui, mais il y a un bug : quand on clique sur le pseudo forum dans le profil topo, on ouvre le profil forum en restant dans le même onglet ; il est alors logique, pour revenir au profil topo, de faire un retour arrière via le navigateur ; mais ça ne fait que rafraichir le profil forum, on ne revient pas sur le topoguide... pour contourner le bug il faut ouvrir le profil forum dans un nouvel onglet, mais on ne le fait que si on connait le bug.
@stef74 : je rouvre l'issue...

**Comment by asaunier** [comment]
@jmarcmod @desnoes @stef74 Cette modif c'est juste un lien qui ouvre par exemple la page http://forum.demov6.camptocamp.org/users/Miko
Cette adresse semble renvoyer systématiquement vers http://forum.demov6.camptocamp.org/users/Miko/activity

Du coup si on fait "back" dans le navigateur on retombe sur http://forum.demov6.camptocamp.org/users/Miko qui va a nouveau renvoyer vers http://forum.demov6.camptocamp.org/users/Miko/activity => donc pas possible de retourner en arrière avec "back".

3 possibilités : 
* cette dernière page est bien la page profil forum qu'on veut afficher. Dans ce cas j'utilise http://forum.demov6.camptocamp.org/users/Miko/activity comme lien au lieu de http://forum.demov6.camptocamp.org/users/Miko et le retour en arrière devrait fonctionner.
* on peut configurer Discourse pour qu'il ne fasse pas de redirection quand on charge http://forum.demov6.camptocamp.org/users/Miko (dans ce cas je ne sais pas ce que fait cette page) ?
* on utilise une autre URL de Discourse pour le profil forum. Dans ce cas laquelle ?

Quelqu'un peut me dire ce qu'il vaut mieux faire ? Merci :)

**Comment by stef74** [comment]
La 1er solution pour moi ...

**Comment by jmarcmod** [comment]
Sans hésiter, la 1ère solution également.
Ça semble simple à faire, ça donne ce qu'on souhaite, et ça n'aura pas de dommage collatéral.

**Comment by desnoes** [comment]
première solution aussi

----- Mail original -----
De: "jmarcmod" <notifications@github.com>
À: "c2corg/v6_ui" <v6_ui@noreply.github.com>
Cc: "desnoes" <mathieu.desnoes@free.fr>, "Mention" <mention@noreply.github.com>
Envoyé: Jeudi 5 Janvier 2017 12:35:35
Objet: Re: [c2corg/v6_ui] Lien profil topoguide -> profil forum (#973)



Sans hésiter, la 1ère solution également. 
Ça semble simple à faire, ça donne ce qu'on souhaite, et ça n'aura pas de dommage collatéral.

**Comment by asaunier** [comment]
OK merci pour les retours. Je viens de proposer le changement en conséquence : https://github.com/c2corg/v6_ui/pull/1303

Ca ne sera pas dans la prochaine MAJ de la prod, celle d'après seulement. D'ici là ca sera l'URL qui ne permet pas de revenir facilement en arrière (comme dans la démo).

**Comment by jmarcmod** [comment]
C'est parfait désormais !

**Comment by desnoes** [comment]
it's ok
