### ISSUE TITLE
Create new SVG icon for reports?

### ISSUE THREAD

**Issue by dkocich** [c2corg/v6_ui#974]
To add reports to the UI (https://github.com/c2corg/v6_ui/pull/905) I probably need some new icon for them to put reports in the map. Nothing is in the folder right now.

Right now I am using [waypoints/misc.svg](https://github.com/c2corg/v6_ui/blob/master/c2corg_ui/static/img/documents/waypoints/misc.svg). Something similar can be maybe used just with an exclamation mark instead of the mountain?. 
![image](https://cloud.githubusercontent.com/assets/6165660/20563377/9e7cfe1e-b188-11e6-8583-002c9422986e.png)

**Comment by asaunier** [comment]
See also https://github.com/c2corg/v6_ui/issues/390#issuecomment-257816638

A possibility would be to use the v5 icon: https://github.com/c2corg/camptocamp.org/blob/master/web/static/images/svg/xreports.svg
