### ISSUE TITLE
Map is too confusing in the editing form

### ISSUE THREAD

**Issue by asaunier** [c2corg/v6_ui#976]
I have read a feedback that said it's not that obvious what the map in the editing form is used for. People might not figure out they can draw a route, georef a waypoint etc.

Perhaps it's simply a missing title?

**Comment by stef74** [comment]
Simple title for go live is sufficient. We have to wrok on contextual help.

**Comment by ginold** [comment]
as we have a small text for association-tool explaining that you can search for a route and add it, we should maybe add something similar for the map.
