### ISSUE TITLE
Timezones are not handled correctly

### ISSUE THREAD

**Issue by tsauerwein** [c2corg/v6_ui#977]
I just created an outing and the feed shows "... created ... an hour ago".

**Comment by stef74** [comment]
For me is not blocking issue

**Comment by tsauerwein** [comment]
I should have provided more details. The problem is more fundamental. In v5 all date times were stored without time zone. When setting up the data model for v6, we did the same. Luckily the problem was revealed by our demo server which seems to use a different time zone as system time. We should make sure that we store date times with a time zone. Otherwise we will have problems when the site is used from a different time zone or simply with winter/summer time changes.

I would consider that as blocking.

**Comment by dkocich** [comment]
Storing the time zone preference in the user profile can be maybe a solution? They can fill it during registration or after in profile settings. UTC time could be adjusted on UI according to user's current setting.

**Comment by tsauerwein** [comment]
> Storing the time zone preference in the user profile can be maybe a solution? They can fill it during registration or after in profile settings. UTC time could be adjusted on UI according to user's current setting.

To start with I would simply take the default timezone of the users system. For example like here: https://css-tricks.com/localizing-times-in-javascript/

**Comment by stef74** [comment]
@tsauerwein Ok for "blocking"

**Comment by stef74** [comment]
@tsauerwein When do you think this issue is fixed ?

**Comment by tsauerwein** [comment]
@stef74 Today/tomorrow.

**Comment by tsauerwein** [comment]
Fixed with https://github.com/c2corg/v6_api/pull/536 and https://github.com/c2corg/v6_ui/pull/1020.

The best way to test this is by creating a custom profile for Chrome, see http://stackoverflow.com/a/39533934/119937
