### ISSUE TITLE
Outing: impossible to modify

### ISSUE THREAD

**Issue by desnoes** [c2corg/v6_ui#979]
I have created an outing (https://www.demov6.camptocamp.org/outings/824708/fr/pas-de-vauclave-traversee-egreatergreaterw-de-chialvetta-a-larche). The modify buttom is not displayed. It is impossible to modify an outing.
![modify](https://cloud.githubusercontent.com/assets/19892089/20573620/f53e40d2-b1b0-11e6-85a0-2bf06adfc942.jpg)

**Comment by asaunier** [comment]
You are not authenticated!

**Comment by desnoes** [comment]
How do we say 'boulet'  ?

Sorry!
