### ISSUE TITLE
Original image can't be displayed

### ISSUE THREAD

**Issue by fbunoz** [c2corg/v6_ui#980]
On the page of an image, when I clic on the image, it appears the popup to download a file instead of displaying the original image : 
https://www.demov6.camptocamp.org/images/821218/fr/versant-w-des-pics-de-berlanche-et-du-grand-charnier-d-allevard
Original : https://sos.exo.io/c2corg_demov6_active/1478985804_2074619315.jpg

**Comment by asaunier** [comment]
Closing because this issue has been fixed longtime ago.
See for instance https://www.camptocamp.org/images/821218/fr/versant-w-des-pics-de-berlanche-et-du-grand-charnier-d-allevard
