### ISSUE TITLE
upper cards are cut in serach results in guidebook

### ISSUE THREAD

**Issue by fjacon** [c2corg/v6_ui#982]
like this 
![cards](https://cloud.githubusercontent.com/assets/1583203/20590654/c3331828-b224-11e6-9089-688a5d27c144.png)

**Comment by dkocich** [comment]
This happens for me only in firefox and sometimes the card is (half)empty - depending on the browser window size. Chromium is fine, I could not see any problem.
![image](https://cloud.githubusercontent.com/assets/6165660/20592471/f980d92a-b22d-11e6-8096-5b3739e4daea.png)

**Comment by asaunier** [comment]
This issue is a duplicate of https://github.com/c2corg/v6_ui/issues/690

**Comment by gottferdom** [comment]
See a CSS solution for cards break in https://github.com/c2corg/v6_ui/issues/690#issuecomment-262917358

**Comment by asaunier** [comment]
I suggest this issue is closed, since already reported in #690
OK for you @fjacon ?

**Comment by fjacon** [comment]
ok
