### ISSUE TITLE
Routes - search by activities (mountain biking / via feratta) returns nothing

### ISSUE THREAD

**Issue by dkocich** [c2corg/v6_ui#983]
When I try to search activities by only "mountain biking" or "via feratta" I get no results. Search by other activities works fine.

This problem is on localhost and also on both test servers.

![image](https://cloud.githubusercontent.com/assets/6165660/20591853/ea1839e0-b22a-11e6-8c36-1bfadd12c9b4.png)

**Comment by tsauerwein** [comment]
These two activities were only added in v6, so there are no routes yet.

**Comment by dkocich** [comment]
Ok, looks fine after creating and searching them... Closing issue
