### ISSUE TITLE
Image detail view page

### ISSUE THREAD

**Issue by asaunier** [c2corg/v6_ui#984]
Not an urgent issue, and probably to be handled in combination with the "document organisation" issue https://github.com/c2corg/v6_ui/issues/449

The current organisation of image detail view pages does not seem relevant to me:
* the image is shown AFTER the description (which can be pretty long as in https://www.demov6.camptocamp.org/images/208579/fr/face-n-des-grandes-jorasses-quelques-itineraires)
* the image is shown in the same column than the description => the whole usable page width is not used

At least I would recommend to:
* show the image right after the page title
* display it outside of the "description" column so that it spans all over the page width
* the image should fit the available width (with a max-width/max-width depending on the BI image dimensions).

**Comment by desnoes** [comment]
In the example (https://www.demov6.camptocamp.org/images/208579/fr/face-n-des-grandes-jorasses-quelques-itineraires), the image is not displayed and when clicking on the link an error message is returned.
Is it the expected result ?

**Comment by asaunier** [comment]
The file has probably never been migrated to the demo and was not available before the current change. Please rather user an image document with an actual file available. For instance:
http://www.demov6.camptocamp.org/images/829468/fr/-

By the way, prefer using http URLs for the demo, https is not well supported in the demo.
