### ISSUE TITLE
Article scroll from TOC to header divs

### ISSUE THREAD

**Issue by dkocich** [c2corg/v6_ui#986]
Here [article link](http://www.demov6.camptocamp.org/articles/376302/fr/changer-d-approche-10-idees-de-sorties-montagne-sans-voiture-dans-les-pyrenees-orientales). Under summary there is Table of Content
![image](https://cloud.githubusercontent.com/assets/6165660/20593998/be5de07a-b234-11e6-911f-8beae7aedbd6.png)

When you click on the link, the page should be moved to some header, but it is not because of wrong parsing of TOC from DB?

The URLs contains extra slash after the hash. When I remove it (Chromium), the redirection works correctly. 
_...Url...#/col-de-la-perche-traversee-des-bouillouses-a-la-vallee-deyne_

I could not see any options to handle it in the [Setting of TOC extension in the UI formatting files](https://github.com/c2corg/v6_ui/blob/master/c2corg_ui/format/__init__.py#L34) or ([docs of TOC extension](https://pythonhosted.org/Markdown/extensions/toc.html)).

Later maybe some animation to the scrolling can be added and also a button to "move up to TOC again".

**Comment by asaunier** [comment]
Thanks for reporting the problem. Actually I had already mentioned it in the PR about the TOC tags: https://github.com/c2corg/v6_ui/pull/695

@tsauerwein suggested it might be related to ``ngeoLocation``, see https://github.com/c2corg/v6_ui/pull/695#issuecomment-251945496

> The URLs contains extra slash after the hash. When I remove it, the redirection works correctly.

Tested in FF and Chromium: when I remove the extra slash, it's added again, thus the link never works.

**Comment by desnoes** [comment]
@dkocich @asaunier : i have just tested on FF, i did not observe any bug. When i click on the toc link, the page is moved to the correct header.

**Comment by dkocich** [comment]
now it works for me also (FF, Chromium)

**Comment by desnoes** [comment]
Thank you for your quick answer David. It also works on my mobile. I close the issue.
