### ISSUE TITLE
Document editing: enable the "save" button only at last step?

### ISSUE THREAD

**Issue by asaunier** [c2corg/v6_ui#987]
I am pretty sure people will click the save button before reaching the last step of a document editing. This might result in uncomplete documents or several archive versions (successive editing to fix missing data).

Shouldn't we make sure they go to the last step before the "save" button is clickable?

**Comment by ginold** [comment]
First we had this button on the last step, then we moved it to be always visible... if the button is only clickable when all the necessary fields are set AND if you are on the last step, I think there is a UX issue :P 

I would say it should be one or the other - or buttons at the end, or as it is now.

**Comment by brunobesson** [comment]
As commented by @asaunier in #1150 maybe we should have a higher priority for this issue.
