### ISSUE TITLE
not all float buttons have box shadow

### ISSUE THREAD

**Issue by brunobesson** [c2corg/v6_ui#988]
There are four float buttons: edit / add images / comments / plus (dropdown)
The plus button has no box-shadow (it is a rule for dropdowns - https://github.com/c2corg/v6_ui/blob/master/less/floatbuttons.less#L127), which I find disturbing. Is this a design choice?
(whether I would like to have the box-shadow is another question)

**Comment by ginold** [comment]
I don't remember why, but it's a good catch! Maybe it's some very old code, along with `app-edit-button` seen above, which doesn't even exist anymore. You're right - all the buttons should have a shadow (or not).

**Comment by brunobesson** [comment]
For now, maybe we could add the shadow, because all other buttons have it. I can propose a PR for this this evening if you like.
As whether we should have a shadow or not, I would rather not, but this should be discussed with more people, more globally<sup>*</sup> and is certainly not the priority.

(*) IMHO, we could sharpen the corners a little bit, remove some frames to lighten the layout, etc. But this is another subject!

**Comment by brunobesson** [comment]
#1402 chooses to remove box-shadow from buttons.

**Comment by desnoes** [comment]
I am unable to test, i did not catch the modification.
