### ISSUE TITLE
Float buttons for mobile

### ISSUE THREAD

**Issue by brunobesson** [c2corg/v6_ui#989]
Several issues
* the tooltips should be disabled on mobile layout (maybe using https://developer.mozilla.org/en-US/docs/Web/API/Window/matchMedia? I haven't looked how it is implementing, through javascript or html attributes - otherwise hidden with CSS)
* the description text is too small (for once :smile:) and when on 2 lines cannot be read entirely
* on desktop Firefox with resized window only:
  * buttons are moving when mouse passes nearby

**Comment by gottferdom** [comment]
I do'nt know if I should open another ticket for this, but the dropdown menu for mobile layout feels badly positioned to me. It's pretty easy to correct, I might take some time to look after it if you confirm you are OK to enhance it.

**Comment by brunobesson** [comment]
This issue was solved some time ago now.
