### ISSUE TITLE
Preview not working for waypoint

### ISSUE THREAD

**Issue by brunobesson** [c2corg/v6_ui#992]
When trying to edit waypoint (http://c2corgv6.demo-camptocamp.com/waypoints/815664/fr/mail-de-jorc)
No modification, but directly clicking preview produces an error notification:

> Un problème de serveur a empêché la prévisualisation

In the console: 
`Error: a is undefined
hB.prototype.vn/<@http://c2corgv6.demo-camptocamp.com/static/df51f3f/build/build.js:899:373
e/<@http://c2corgv6.demo-camptocamp.com/static/df51f3f/build/deps.js:170:20
vf/this.$get</m.prototype.$eval@http://c2corgv6.demo-camptocamp.com/static/df51f3f/build/deps.js:184:343
vf/this.$get</m.prototype.$digest@http://c2corgv6.demo-camptocamp.com/static/df51f3f/build/deps.js:181:412
vf/this.$get</m.prototype.$apply@http://c2corgv6.demo-camptocamp.com/static/df51f3f/build/deps.js:185:111
l@http://c2corgv6.demo-camptocamp.com/static/df51f3f/build/deps.js:136:320
J@http://c2corgv6.demo-camptocamp.com/static/df51f3f/build/deps.js:141:34
gg/</t.onload@http://c2corgv6.demo-camptocamp.com/static/df51f3f/build/deps.js:142:4`

**Comment by asaunier** [comment]
Good catch!
The logs in my dev instance say:
>   File "/home/alex/v6_ui/c2corg_ui/templates/waypoint/preview.html", line 0, in render_body
  File "/home/alex/v6_ui/.build/venv/lib/python3.4/site-packages/mako/runtime.py", line 525, in _populate
    d[ident] = getattr(self, ident)
  File "/home/alex/v6_ui/.build/venv/lib/python3.4/site-packages/mako/runtime.py", line 625, in __getattr__
    (self.name, key))
AttributeError: Namespace '__anon_0x7fbc6879d4e0' has no member 'get_waypoint_orientation'

=> there's a missing "s" in ``get_waypoint_orientation`` in https://github.com/c2corg/v6_ui/blob/master/c2corg_ui/templates/waypoint/preview.html#L33 and https://github.com/c2corg/v6_ui/blob/master/c2corg_ui/templates/waypoint/preview.html#L4

See https://github.com/c2corg/v6_ui/blob/master/c2corg_ui/templates/waypoint/helpers/view.html#L385

**Comment by loicperrin** [comment]
Same pb when trying to preview an outing I have tried to create on this route: http://www.demov6.camptocamp.org/routes/824741/fr/voie-normale-test
Maybe it is due to the fact that the route has no geom (no main WP)

**Comment by asaunier** [comment]
@loicperrin I don't think the problem you report is related to the preview. I have tried to edit another outing and the preview works as expected. The outing you mention cannot even be shown ("internal server error").

**Comment by loicperrin** [comment]
> I have tried to edit another outing and the preview works as expected

Yes it works for most outings, but 

> The outing you mention cannot even be shown ("internal server error")

Yes. If I save it I have this error, but if I preview it before saving, I have the same problem as for waypoints.

**Comment by asaunier** [comment]
You're right. I have tried to create a new outing and I got the following error when loading the preview:

>   File "/home/alex/v6_ui/c2corg_ui/templates/outing/preview.html", line 33, in render_body
    ${get_outing_participants(outing)}
  File "/home/alex/v6_ui/c2corg_ui/templates/outing/helpers/view.html", line 158, in render_get_outing_participants
    <%
KeyError: 'locales'

**Comment by loicperrin** [comment]
Fixed!
