### ISSUE TITLE
Use range slider for journey duration

### ISSUE THREAD

**Issue by brunobesson** [c2corg/v6_ui#998]
In route edition: maybe we could use a range slider to select the journey duration (with a range slider like the one used to filter elevation in advanced search). By default, it could be set on one.

The current solution has to many checkboxes IMHO.

By the way, is it consistent to select e.g. 1day or 3 days but not 2?

**Comment by fbunoz** [comment]
> By the way, is it consistent to select e.g. 1day or 3 days but not 2?

No, and if a slider can avoid this, it would be fine.
