### ISSUE TITLE
Comments display a 404 page in image view

### ISSUE THREAD

**Issue by arnaud-morvan** [c2corg/v6_ui#999]
See: http://www.demov6.camptocamp.org/images/821567/fr/pointe-de-chalune

This is missing in image view template: 
```
module.value('documentData', {
...
 "topic_id": ${dumps(locale.get('topic_id'))}
```
Specific issue about comments in image view from #972

**Comment by asaunier** [comment]
The PR is not merged. So it's not "ready for demo" yet :P
